Repository matrix-org/matrix-react-sdk, pull requests merged in 2019-11, with the labels that each got.

#3602 Match identity server registration to the IS r0.3.0 spec
  src/IdentityAuthClient.js
Labels: release-blocker, spec

#3641 Fix positioning, size, and colour of the composer e2e icon
  res/css/views/rooms/_MessageComposer.scss
  src/components/views/rooms/MessageComposer.js
  src/components/views/rooms/SlateMessageComposer.js
Labels: release-blocker

#3673 Fix override behaviour of system vs defined themes
  src/i18n/strings/en_EN.json
  src/settings/Settings.js
  src/theme.js
Labels: release-blocker

#2959 Add button to clear all notification counts, sometimes stuck in historical
  src/components/views/settings/Notifications.js
  src/i18n/strings/en_EN.json
Labels: blocked
