Repository matrix-org/matrix-react-sdk, pull requests merged in 2020-05, with the labels that each got.

#4549 Differentiate copy for own untrusted device dialog
  src/i18n/strings/en_EN.json
  src/verification.js
Labels: phase:3, story:1

#4554 set the meta tag for theme-color to the same theme css background
  src/theme.js
Labels: Community PR

#4555 Add copy to SSO prompts during cross-signing setup
  src/async-components/views/dialogs/secretstorage/CreateSecretStorageDialog.js
  src/components/views/dialogs/InteractiveAuthDialog.js
  src/i18n/strings/en_EN.json
Labels: release-blocker

#4584 Acquire a new session before enacting deactivation
  src/components/views/dialogs/DeactivateAccountDialog.js
  src/i18n/strings/en_EN.json
Labels: release-blocker

#4494 Prevent PersistedElements overflowing scrolled areas
  res/css/views/rooms/_AppsDrawer.scss
  src/components/views/elements/PersistedElement.js
  src/components/views/rooms/AuxPanel.js
Labels: Community PR

#4641 Revert default font size to 15px
  src/settings/Settings.js
Labels: release-blocker
