Repository matrix-org/matrix-react-sdk, pull requests merged in 2020-04, with the labels that each got.

#4339 Fix Hangul typing does not work properly
  src/components/views/rooms/BasicMessageComposer.js
Labels: Community PR

#4357 Use singular copy when only deleting one device
  src/components/views/settings/DevicesPanel.js
  src/i18n/strings/en_EN.json
Labels: release-blocker

#4356 Support deactivating your account with SSO
  src/components/views/dialogs/DeactivateAccountDialog.js
  src/i18n/strings/en_EN.json
Labels: release-blocker

#4371 Retry the request for the master key from SSSS on login
  src/components/structures/MatrixChat.js
Labels: cross-signing-sprint, phase:3, story:1

#4412 Remove end-to-end message info option when cross-signing is used
  src/components/views/messages/MessageActionBar.js
Labels: cross-signing-sprint, phase:3, story:1

#4470 Assert type of domNode as HTMLElement to fix build
  src/components/views/rooms/Autocomplete.tsx
Labels: Community PR

#4532 Fix device verification toasts not disappearing
  src/DeviceListener.js
Labels: phase:3, story:1
