Repository matrix-org/matrix-react-sdk, pull requests merged in 2020-10, with the labels that each got.

#5280 Fix call container avatar initial centering
  res/css/views/voip/_CallContainer.scss
Labels: hacktoberfest-accepted

#5283 Fix naive pinning limit and app tile widgetMessaging NPE
  src/components/views/elements/AppTile.js
  src/stores/WidgetStore.ts
Labels: release-blocker

#5294 Fix StopGapWidget infinitely recursing
  src/components/views/elements/AccessibleTooltipButton.tsx
  src/components/views/rooms/MessageComposer.js
  src/stores/widgets/StopGapWidget.ts
Labels: release-blocker

#5304 [Release] Use new preparing event for widget communications
  package.json
  src/components/views/elements/AppTile.js
  src/stores/widgets/StopGapWidget.ts
  yarn.lock
Labels: release-blocker

#5306 [Release] Fix templating for v1 jitsi widgets
  src/stores/widgets/StopGapWidget.ts
Labels: release-blocker

#5301 Changed rainbow algorithm
  src/utils/colour.js
  src/utils/colour.ts
Labels: Community PR

#5334 Fix Jitsi OpenIDC auth
  src/stores/widgets/StopGapWidget.ts
Labels: release-blocker

#5349 docs: added comment explanation
  src/components/structures/MatrixChat.tsx
Labels: Community PR
