Repository matrix-org/matrix-react-sdk, pull requests merged in 2020-01, with the labels that each got.

#3803 Fix ability to remove avatars
  src/components/views/room_settings/RoomProfileSettings.js
  src/components/views/settings/ProfileSettings.js
Labels: release-blocker

#3918 Don't list every single alias when there's many
  src/TextForEvent.js
  src/i18n/strings/en_EN.json
Labels: release-blocker

#3919 Don't list every single alias when there's many
  src/TextForEvent.js
  src/i18n/strings/en_EN.json
Labels: release-blocker

#3944 Use https for recaptcha for all non-http protocols
  src/components/views/auth/CaptchaForm.js
Labels: Community PR

#3958 Tweak styling of the unread indicator circle.
  res/css/views/rooms/_TopUnreadMessagesBar.scss
Labels: Community PR

#3973 Update copy for right panel verification
  src/components/views/dialogs/DeviceVerifyDialog.js
  src/components/views/right_panel/EncryptionInfo.js
  src/components/views/verification/VerificationShowSas.js
  src/i18n/strings/en_EN.json
Labels: cross-signing-sprint, story:2

#3977 Adjust icons with in person with design
  res/css/views/rooms/_InviteOnlyIcon.scss
  res/css/views/rooms/_MessageComposer.scss
  res/css/views/rooms/_RoomHeader.scss
  res/css/views/rooms/_RoomTile.scss
Labels: cross-signing-sprint, story:3

#3975 Replace Verify button in UserInfo verification with "Learn more"
  res/css/views/right_panel/_UserInfo.scss
  src/components/views/right_panel/EncryptionInfo.js
  src/components/views/right_panel/UserInfo.js
  src/components/views/right_panel/VerificationPanel.js
  src/components/views/verification/VerificationShowSas.js
  src/i18n/strings/en_EN.json
Labels: cross-signing-sprint, story:2

#3994 Change verify user text
  src/components/views/right_panel/UserInfo.js
  src/i18n/strings/en_EN.json
Labels: cross-signing-sprint, story:2

#3995 Add advanced option to keep secret storage in memory for session
  src/CrossSigningManager.js
  src/components/views/settings/tabs/user/LabsUserSettingsTab.js
  src/i18n/strings/en_EN.json
  src/settings/Settings.js
Labels: cross-signing-sprint, story:1

#4017 Apply copy edits to security setup flow
  src/CrossSigningManager.js
  src/async-components/views/dialogs/keybackup/CreateKeyBackupDialog.js
  src/async-components/views/dialogs/secretstorage/CreateSecretStorageDialog.js
  src/components/views/auth/InteractiveAuthEntryComponents.js
  src/components/views/dialogs/keybackup/RestoreKeyBackupDialog.js
  src/components/views/toasts/SetupEncryptionToast.js
  src/i18n/strings/en_EN.json
Labels: cross-signing-sprint, story:1
