Repository matrix-org/matrix-react-sdk, pull requests merged in 2020-03, with the labels that each got.

#4169 Disable registration flows on SSO servers (for patch release)
  src/components/structures/auth/Login.js
  src/components/structures/auth/Registration.js
  src/i18n/strings/en_EN.json
Labels: release-blocker

#4159 Include a mark as read X under the scroll to unread button
  res/css/views/rooms/_TopUnreadMessagesBar.scss
  src/components/views/rooms/TopUnreadMessagesBar.js
  src/i18n/strings/en_EN.json
Labels: blocked

#3892 Moved read receipts to the bottom of the EventTile.
  res/css/views/rooms/_EventTile.scss
  src/components/views/rooms/EventTile.js
Labels: Community PR

#4193 Remove extraneous tab stop from room tree view.
  src/components/views/rooms/RoomList.js
Labels: Community PR

#4221 Fix: make alternative addresses UX less confusing
  res/css/views/elements/_EditableItemList.scss
  res/css/views/room_settings/_AliasSettings.scss
  res/css/views/settings/tabs/_SettingsTab.scss
  src/components/views/elements/EditableItemList.js
  src/components/views/room_settings/AliasSettings.js
  src/components/views/room_settings/RoomPublishSetting.js
  src/components/views/settings/tabs/room/GeneralRoomSettingsTab.js
  src/i18n/strings/en_EN.json
Labels: release-blocker

#4223 Fix key backup trust text for cross-signing
  src/components/views/settings/KeyBackupPanel.js
Labels: cross-signing-sprint, phase:3, story:1

#4241 Improve Keyboard Shortcuts. Add alt-arrows & alt-shift-arrows
  res/css/views/dialogs/_KeyboardShortcutsDialog.scss
  src/accessibility/KeyboardShortcuts.tsx
  src/components/structures/LoggedInView.js
  src/components/structures/RoomSubList.js
  src/components/views/rooms/RoomList.js
  src/components/views/rooms/RoomTile.js
  src/components/views/rooms/SendMessageComposer.js
  src/i18n/strings/en_EN.json
Labels: release-blocker

#4244 Add shortcut CmdOrCtrl+. to toggle right panel
  src/Keyboard.ts
  src/accessibility/KeyboardShortcuts.tsx
  src/components/structures/GroupView.js
  src/components/structures/LoggedInView.js
  src/components/structures/RoomView.js
  src/i18n/strings/en_EN.json
  src/stores/RightPanelStore.js
Labels: release-blocker

#4268 Log and display secret sharing cache state
  src/CrossSigningManager.js
  src/components/views/settings/CrossSigningPanel.js
  src/i18n/strings/en_EN.json
Labels: cross-signing-sprint, phase:3, story:1

#4270 Wait for SSSS upgrade to complete
  src/DeviceListener.js
  src/components/views/toasts/SetupEncryptionToast.js
Labels: phase:3, story:1

#4296 Added the /html command
  src/SlashCommands.js
  src/i18n/strings/en_EN.json
Labels: Community PR
