Repository matrix-org/matrix-react-sdk, pull requests merged in 2020-07, with the labels that each got.

#4892 Highlight "Jump to Bottom" badge when appropriate
  res/css/views/rooms/_JumpToBottomButton.scss
  src/components/structures/RoomView.js
  src/components/views/rooms/JumpToBottomButton.js
Labels: blocked

#5036 Convert right_panel to TS
  src/components/structures/LoggedInView.tsx
  src/components/structures/RightPanel.js
  src/components/views/groups/GroupMemberList.js
  src/components/views/messages/MKeyVerificationRequest.js
  src/components/views/right_panel/EncryptionInfo.tsx
  src/components/views/right_panel/EncryptionPanel.tsx
  src/components/views/right_panel/GroupHeaderButtons.tsx
  src/components/views/right_panel/HeaderButton.tsx
  src/components/views/right_panel/HeaderButtons.js
  src/components/views/right_panel/HeaderButtons.tsx
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/components/views/right_panel/UserInfo.js
  src/components/views/right_panel/VerificationPanel.tsx
  src/components/views/rooms/Stickerpicker.js
  src/components/views/toasts/VerificationRequestToast.tsx
  src/dispatcher/actions.ts
  src/dispatcher/payloads/AfterRightPanelPhaseChangePayload.ts
  src/dispatcher/payloads/SetRightPanelPhasePayload.ts
  src/dispatcher/payloads/ToggleRightPanelPayload.ts
  src/settings/Settings.js
  src/stores/RightPanelStore.ts
  src/stores/RightPanelStorePhases.ts
  src/verification.js
Labels: Community PR

#5070 Fix various small regressions in the room list's behaviour
  res/css/structures/_CustomRoomTagPanel.scss
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomSublist.tsx
  src/stores/notifications/RoomNotificationState.ts
  src/stores/room-list/algorithms/Algorithm.ts
  src/stores/room-list/algorithms/list-ordering/ImportanceAlgorithm.ts
  src/utils/objects.ts
Labels: release-blocker
