Repository matrix-org/matrix-react-sdk, pull requests merged in 2021-09, with the labels that each got.

#6658 Threading exploration work
  .stylelintrc.js
  res/css/views/messages/_MessageActionBar.scss
  res/css/views/right_panel/_RoomSummaryCard.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_MessageComposer.scss
  res/img/element-icons/message/thread.svg
  src/MatrixClientPeg.ts
  src/components/structures/MessagePanel.tsx
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/structures/ThreadView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/messages/MessageActionBar.js
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/RightPanelStorePhases.ts
Labels: T-Enhancement

#6716 Clear currentRoomId when viewing home page, fixing document title
  src/components/structures/MatrixChat.tsx
Labels: T-Defect

#6717 Fix EmojiPicker filtering to lower case emojibase data strings
  src/components/views/emojipicker/EmojiPicker.tsx
Labels: T-Defect

#6721 When creating private spaces, make the initial rooms restricted if supported
  src/components/structures/SpaceRoomView.tsx
Labels: T-Enhancement

#6715 Reload suggested rooms if we see the state change down /sync
  src/stores/SpaceStore.tsx
  test/stores/SpaceStore-test.ts
  test/stores/room-list/SpaceWatcher-test.ts
Labels: T-Enhancement

#6722 Show autocomplete sections vertically
  res/css/views/rooms/_Autocomplete.scss
Labels: T-Defect

#6723 Fix the Image View not openning for some pinned messages
  src/components/views/elements/ImageView.tsx
Labels: T-Defect

#6725 When creating subspaces properly set restricted join rule
  src/components/views/dialogs/CreateSubspaceDialog.tsx
Labels: T-Defect

#6719 Remove arbitrary limits from send/receive events for widgets
  src/stores/widgets/StopGapWidgetDriver.ts
Labels: Sponsored, T-Enhancement

#6695 Don't send prehistorical events to widgets during decryption at startup
  src/stores/widgets/StopGapWidget.ts
Labels: Sponsored, T-Defect

#6702 Replace fake username in EventTilePreview with a proper loading state
  res/css/_components.scss
  res/css/views/elements/_EventTilePreview.scss
  src/components/views/elements/EventTilePreview.tsx
  src/components/views/settings/LayoutSwitcher.tsx
  src/components/views/settings/tabs/user/AppearanceUserSettingsTab.tsx
Labels: T-Defect

#6703 Allow to use basic html to format invite messages
  src/components/views/elements/InviteReason.tsx
  src/components/views/rooms/RoomPreviewBar.js
Labels: T-Enhancement

#6707 Make GH actions clone from the correct fork and cleanup
  .github/workflows/develop.yml
  scripts/fetchdep.sh
Labels: T-Task

#6720 Replace eventIsReply util with replyEventId getter
  src/components/structures/ThreadView.tsx
  src/components/views/elements/ReplyThread.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  test/components/views/rooms/SendMessageComposer-test.js
Labels: T-Task

#6714 Only make the initial space rooms suggested by default
  src/components/structures/SpaceRoomView.tsx
  src/createRoom.ts
Labels: T-Defect

#6710 Add autoplay for voice messages
  src/audio/ManagedPlayback.ts
  src/audio/Playback.ts
  src/audio/PlaybackClock.ts
  src/audio/PlaybackManager.ts
  src/audio/PlaybackQueue.ts
  src/components/views/messages/MAudioBody.tsx
  src/components/views/rooms/VoiceRecordComposerTile.tsx
Labels: Sponsored, T-Enhancement

#6726 Split autoplay GIFs and videos into different settings
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MVideoBody.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/handlers/AccountSettingsHandler.ts
Labels: T-Enhancement

#6733 Don't rely on rooms having timelines to use when checking widgets
  src/stores/widgets/StopGapWidget.ts
Labels: X-Release-Blocker, T-Task

#6734 Improve performance of widget startup slightly
  src/stores/widgets/StopGapWidget.ts
Labels: T-Task

#6619 Migrate components to TypeScript
  src/components/structures/RoomDirectory.tsx
  src/components/structures/RoomView.tsx
  src/components/views/avatars/MemberAvatar.tsx
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/JumpToBottomButton.tsx
  src/components/views/rooms/ReadReceiptMarker.tsx
  src/components/views/rooms/RoomDetailList.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomUpgradeWarningBar.tsx
  src/components/views/rooms/SimpleRoomHeader.tsx
  src/components/views/rooms/TopUnreadMessagesBar.tsx
  src/components/views/settings/AvatarSetting.tsx
  src/components/views/settings/ChangeAvatar.tsx
  src/components/views/settings/ChangeDisplayName.tsx
  src/components/views/settings/DevicesPanel.tsx
  src/components/views/settings/DevicesPanelEntry.tsx
  src/components/views/settings/IntegrationManager.tsx
  src/components/views/settings/ProfileSettings.tsx
Labels: T-Task

#6735 Fix state initialisation for DevicesPanel
  src/components/views/settings/DevicesPanel.tsx
Labels: T-Task

#6731 Fix bug where one party's media would sometimes not be shown
  src/CallHandler.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#6736 Fix ProfileSettings when avatarUrl is null
  src/components/views/settings/ProfileSettings.tsx
Labels: T-Task

#6739 Improve form handling in and around space creation
  src/components/structures/SpaceRoomView.tsx
  src/components/views/elements/RoomAliasField.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
Labels: T-Enhancement

#6729 Fix explore rooms button not working during space creation wizard
  src/components/structures/SpaceRoomView.tsx
Labels: T-Defect

#6730 Don't context switch room on SpaceStore ready as it can break permalinks
  src/stores/SpaceStore.tsx
Labels: T-Defect

#6737 Serialize and retry mass-leave when leaving space
  src/utils/membership.ts
  src/utils/space.tsx
Labels: T-Enhancement

#6700 Show call length during a call
  src/DateUtils.ts
  src/components/structures/CallEventGrouper.ts
  src/components/views/audio_messages/Clock.tsx
  src/components/views/messages/CallEvent.tsx
  src/i18n/strings/en_EN.json
  test/utils/DateUtils-test.ts
Labels: T-Enhancement

#6728 Stop automatic playback of voice messages if a non-voice message is encountered
  src/audio/PlaybackQueue.ts
Labels: Sponsored, T-Enhancement

#6636 Make ForgotPassword UX slightly more user friendly
  res/css/structures/auth/_Login.scss
  src/components/structures/auth/ForgotPassword.tsx
Labels: T-Defect

#6582 Add bubble highlight styling
  res/css/views/rooms/_EventBubbleTile.scss
Labels: T-Enhancement

#6738 Add missing pluralisation i18n strings for Spaces
  src/i18n/strings/en_EN.json
Labels: T-Defect

#6740 Add logging to debug stuck toast bug
  src/DeviceListener.ts
Labels: T-Task

#6749 Fix replies not appearing in timeline
  src/components/structures/MessagePanel.tsx
Labels: T-Task

#6745 Prefer matrix.to alias links over room id in spaces & share
  src/components/views/dialogs/ShareDialog.tsx
  src/components/views/spaces/SpacePublicShare.tsx
Labels: T-Enhancement

#6682 Create narrow mode for Composer
  res/css/views/rooms/_MessageComposer.scss
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/Stickerpicker.tsx
  src/components/views/rooms/VoiceRecordComposerTile.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#6742 Convert widget OIDC exchange dialog to TS (fixing it)
  src/components/views/dialogs/WidgetOpenIDPermissionsDialog.tsx
Labels: T-Defect

#6751 Fix scroll being stuck at bottom
  src/components/structures/ScrollPanel.tsx
Labels: X-Release-Blocker, T-Defect

#6748 Fix Space creation wizard go to my first room button behaviour
  src/components/structures/SpaceRoomView.tsx
Labels: T-Defect

#6750 Migrate MessageActionBar to TypeScript
  src/components/views/messages/MessageActionBar.tsx
Labels: T-Task

#6756 fix typing of olmVersion in settings
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
Labels: T-Task

#6755 Fix thread creation flow
  src/components/structures/ThreadView.tsx
Labels: T-Task

#6705 Use disptacher to answer/reject calls in call tiles
  src/components/structures/CallEventGrouper.ts
Labels: X-Release-Blocker, T-Task

#6757 Update changelog generator
  package.json
  yarn.lock
Labels: T-Task

#6758 Fix types in release mode again
  src/audio/PlaybackQueue.ts
  src/stores/widgets/StopGapWidgetDriver.ts
Labels: T-Task

#6744 Space panel accessibility improvements
  src/components/views/spaces/SpacePanel.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
Labels: T-Enhancement

#6761 Fix regressed tab view buttons in space update toast
  src/stores/SpaceStore.tsx
Labels: T-Defect

#6746 Respect m.space.parent relations if they hold valid permissions
  src/stores/SpaceStore.tsx
  test/stores/SpaceStore-test.ts
Labels: T-Enhancement

#6747 hide no-op m.room.encryption events and better word param changes
  src/components/views/messages/EncryptionEvent.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#6763 Improve types based on new TS in js-sdk
  src/components/views/right_panel/EncryptionPanel.tsx
  src/components/views/right_panel/VerificationPanel.tsx
  src/components/views/verification/VerificationShowSas.tsx
Labels: T-Task

#6762 Switch type check to GitHub Actions
  .github/workflows/lint.yaml
  scripts/ci/js-sdk-to-release.js
  scripts/ci/js-sdk-to-release.sh
Labels: T-Task

#6765 Make space members and user info behave more expectedly
  src/components/structures/RightPanel.tsx
  src/components/views/context_menus/SpaceContextMenu.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#6760 Improve tooltips on space quick actions and explore button
  src/components/structures/LeftPanel.tsx
  src/components/views/rooms/RoomList.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#6764 Improve the upgrade for restricted user experience
  src/components/views/dialogs/RoomSettingsDialog.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/utils/RoomUpgrade.ts
Labels: T-Enhancement

#6767 Rename type checking script
  .github/workflows/typecheck.yaml
Labels: T-Task

#6769 Remove unnecessary pushd
  .github/workflows/typecheck.yaml
Labels: T-Task

#6770 Use cursor:pointer on space panel buttons
  res/css/structures/_SpacePanel.scss
Labels: T-Defect

#6766 Add config option to turn on in-room event sending timing metrics
  src/ContentMessages.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/sendTimePerformanceMetrics.ts
  src/settings/Settings.tsx
Labels: X-Release-Blocker, Sponsored, T-Enhancement

#6693 Render guest settings only in public rooms/spaces
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/components/views/spaces/SpaceSettingsVisibilityTab.tsx
Labels: T-Defect

#6773 [Release] Add config option to turn on in-room event sending timing metrics
  src/ContentMessages.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/sendTimePerformanceMetrics.ts
  src/settings/Settings.tsx
Labels: X-Release-Blocker, Sponsored, T-Enhancement

#6771 Debounce read marker update on scroll
  src/components/structures/ScrollPanel.tsx
  src/components/structures/TimelinePanel.tsx
Labels: X-Release-Blocker, T-Defect

#6774 Debounce read marker update on scroll
  src/components/structures/ScrollPanel.tsx
  src/components/structures/TimelinePanel.tsx
Labels: T-Defect

#6753 Reintroduce "Create narrow mode for composer"
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_MessageComposer.scss
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadView.tsx
  src/components/views/elements/AccessibleTooltipButton.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/Stickerpicker.tsx
  src/components/views/rooms/VoiceRecordComposerTile.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#6772 Force refresh threads timeline
  src/components/structures/ThreadView.tsx
  src/components/structures/TimelinePanel.tsx
Labels: T-Task

#6776 Fix message bubble corners being wrong in the presence of hidden events
  src/components/structures/MessagePanel.tsx
Labels: T-Defect

#6724 Deduplicate join rule management between rooms and spaces
  src/components/views/dialogs/SpaceSettingsDialog.tsx
  src/components/views/settings/JoinRuleSettings.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/components/views/spaces/SpaceSettingsVisibilityTab.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  src/hooks/useLocalEcho.ts
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#6780 Fix build issues from two conflicting PRs landing without merge conflict
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/components/views/spaces/SpaceSettingsVisibilityTab.tsx
Labels: T-Defect

#6727 Remove Element-specifc screen-sharing code out of the js-sdk
  src/@types/global.d.ts
  src/components/views/elements/DesktopCapturerSourcePicker.tsx
  src/components/views/voip/CallView.tsx
Labels: T-Task

#6779 Adapt and re-use the RolesRoomSettingsTab for Spaces
  src/components/views/dialogs/SpaceSettingsDialog.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#6786 Redirect from /#/welcome to /#/home if already logged in
  src/components/structures/MatrixChat.tsx
Labels: T-Defect

#6783 Optimize input label transition on focus
  res/css/views/elements/_Field.scss
Labels: T-Enhancement

#6792 Fix automatic field population in space create menu not validating
  src/components/views/spaces/SpaceCreateMenu.tsx
Labels: T-Enhancement

#6790 Hide mute/unmute button in UserInfo for Spaces as it makes no sense
  src/components/views/right_panel/UserInfo.tsx
Labels: T-Enhancement

#6791 Fix broken edge case with public space creation with no alias
  src/components/views/spaces/SpaceCreateMenu.tsx
Labels: T-Defect

#6794 Fix autocomplete not having y-scroll
  res/css/views/rooms/_Autocomplete.scss
Labels: T-Defect

#6793 Fix emoji picker and stickerpicker not appearing correctly when opened
  src/components/structures/ContextMenu.tsx
  src/components/views/rooms/MessageComposer.tsx
Labels: T-Defect

#6801 Fix emoji picker and stickerpicker not appearing correctly when opened
  src/components/structures/ContextMenu.tsx
Labels: T-Defect

#6802 Fix autocomplete not having y-scroll
  res/css/views/rooms/_Autocomplete.scss
Labels: T-Defect

#6803 Stop spinner on space preview if the join fails
  src/components/structures/SpaceRoomView.tsx
Labels: T-Defect

#6798 Fix edge case space issues around creation and initial view
  src/components/structures/SpaceHierarchy.tsx
  src/components/views/rooms/RoomTile.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
  src/hooks/useEventEmitter.ts
  src/hooks/useRoomState.ts
Labels: T-Defect

#6800 Simplify Space Panel layout and fix some edge cases
  res/css/structures/_SpacePanel.scss
Labels: T-Enhancement

#6797 Fix edge cases around joining new room which does not belong to active space
  src/stores/SpaceStore.tsx
Labels: T-Defect

#6796 Remove replies from hidden events when shown with `messages.ViewSourceEvent`
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#6808 Convert `/context_menus` and `/avatars` to TS
  src/components/views/avatars/MemberStatusMessageAvatar.tsx
  src/components/views/context_menus/GenericElementContextMenu.tsx
  src/components/views/context_menus/GenericTextContextMenu.tsx
  src/components/views/context_menus/StatusMessageContextMenu.tsx
  src/components/views/rooms/MessageComposer.tsx
Labels: T-Task

#6806 Remove `message_send_failed` dispatch
  src/Resend.ts
  src/components/structures/MatrixChat.tsx
Labels: T-Task

#6795 Make message bubble font size consistent
  res/css/views/rooms/_EventBubbleTile.scss
Labels: T-Defect

#6785 Fix various message bubble alignment issues
  res/css/views/rooms/_EventBubbleTile.scss
Labels: T-Defect

#6784 Replace plain text emoji at the end of a line
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/editor/range.ts
Labels: T-Enhancement

#6782 Don't show screensharing dialog on web
  src/components/views/voip/CallView.tsx
Labels: X-Release-Blocker, T-Task

#6777 Fix room list scroll jumps
  res/css/views/rooms/_RoomSublist.scss
Labels: T-Defect

#6781 Improve `MatrixCall` media handling
  src/MediaDeviceHandler.ts
Labels: T-Task

#6812 Fix checks to show prompt to start new chats
  src/components/views/rooms/RoomList.tsx
Labels: T-Defect

#6813 Pin typescript/types version
  package.json
  yarn.lock
Labels: T-Task

#6809 Show updated relation reply from edited message
  src/components/views/elements/ReplyThread.tsx
Labels: T-Enhancement

#6814 yarn upgrade
  package.json
  yarn.lock
Labels: T-Task

#6319 Show "Message" in the user info panel instead of "Start chat"
  src/components/views/right_panel/UserInfo.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#6594 Delabs Spaces, iterate some copy and move communities/space toggle to preferences
  res/css/structures/_GroupFilterPanel.scss
  res/css/structures/_SpacePanel.scss
  res/css/structures/_SpaceRoomView.scss
  res/css/views/beta/_BetaCard.scss
  res/css/views/settings/tabs/user/_PreferencesUserSettingsTab.scss
  res/img/betas/.gitkeep
  res/img/betas/spaces.png
  src/components/structures/GroupFilterPanel.tsx
  src/components/structures/LegacyCommunityPreview.tsx
  src/components/structures/LoggedInView.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/MyGroups.js
  src/components/structures/SpaceRoomView.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/SettingsStore.ts
  src/settings/controllers/IncompatibleController.ts
  src/stores/SpaceStore.tsx
  test/components/views/rooms/RoomList-test.js
  test/end-to-end-tests/src/scenario.js
  test/end-to-end-tests/src/scenarios/spaces.js
  test/end-to-end-tests/src/usecases/create-space.js
  test/end-to-end-tests/src/usecases/room-settings.js
  test/stores/SpaceStore-setup.ts
  test/stores/SpaceStore-test.ts
  test/stores/room-list/SpaceWatcher-test.ts
Labels: T-Enhancement

#6787 Convert `/structures` to TS
  src/components/structures/EmbeddedPage.tsx
  src/components/structures/GenericErrorPage.tsx
  src/components/structures/IndicatorScrollbar.tsx
  src/components/structures/MainSplit.tsx
  src/components/structures/RoomStatusBar.tsx
  src/components/structures/SearchBox.tsx
  src/components/structures/UserView.tsx
  src/components/structures/ViewSource.tsx
  src/components/views/dialogs/AddExistingToSpaceDialog.tsx
  src/components/views/dialogs/ForwardDialog.tsx
  src/components/views/dialogs/LeaveSpaceDialog.tsx
  src/components/views/dialogs/ManageRestrictedJoinRuleDialog.tsx
Labels: T-Task

#6805 Add warning that some spaces may not be relinked to the newly upgraded room
  src/components/views/settings/JoinRuleSettings.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#6819 Fix abuse of MainSplit in LegacyCommunityPreview and build
  src/components/structures/LegacyCommunityPreview.tsx
  src/components/structures/MainSplit.tsx
Labels: T-Task

#6821 Fix missing null guard in space hierarchy pagination
  src/components/structures/SpaceHierarchy.tsx
Labels: T-Defect

#6818 Say Joining space instead of Joining room where we know its a space
  src/components/structures/SpaceHierarchy.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/i18n/strings/en_EN.json
  src/stores/ThreepidInviteStore.ts
Labels: T-Enhancement

#6828 Fix reactions aria-label not being a string and thus being read as [Object object]
  src/components/views/elements/MemberEventListSummary.tsx
  src/components/views/messages/ReactionsRowButton.tsx
  src/i18n/strings/en_EN.json
  src/utils/FormattingUtils.ts
Labels: T-Defect

#6823 Fix last character duplication with `Automatically replace plain text emoji` on
  src/components/views/rooms/BasicMessageComposer.tsx
Labels: X-Release-Blocker, T-Defect

#6817 Show updated relation reply from edited message - v2
  src/components/views/elements/ReplyThread.tsx
  test/components/views/elements/ReplyThread-test.js
Labels: T-Enhancement

#6832 Fix pill deletion on Firefox 78
  src/components/views/rooms/BasicMessageComposer.tsx
Labels: T-Defect

#6831 Convert end-of-line emoji when editing
  src/components/views/rooms/EditMessageComposer.tsx
Labels: X-Release-Blocker, T-Defect

#6836 Pass `PR_NUMBER` to builds
  .github/workflows/layered-build.yaml
  .github/workflows/typecheck.yaml
Labels: T-Task

#6830 Fix accessing field on oobData which may be undefined
  src/components/views/rooms/RoomPreviewBar.tsx
Labels: T-Defect

#6838 Convert `/room_settings` to TS
  src/components/views/room_settings/RoomProfileSettings.tsx
  src/components/views/room_settings/UrlPreviewSettings.tsx
Labels: T-Task

#6837 Don't `fakeDeletion()` when `CTRL` is pressed
  src/components/views/rooms/BasicMessageComposer.tsx
Labels: T-Defect

#6844 Revert Firefox composer deletion hacks
  src/components/views/rooms/BasicMessageComposer.tsx
Labels: T-Defect

#6826 Improve string for leaving space in leave dialog
  src/components/views/dialogs/LeaveSpaceDialog.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#6842 Always show root event of a thread in room's timeline
  src/components/structures/MessagePanel.tsx
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#6815 Convert `/src/components/views/elements` to TS
  src/async-components/views/dialogs/eventindex/ManageEventIndexDialog.tsx
  src/components/structures/LeftPanelWidget.tsx
  src/components/views/dialogs/CryptoStoreTooNewDialog.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/elements/AppWarning.tsx
  src/components/views/elements/DialogButtons.tsx
  src/components/views/elements/DirectorySearchBox.tsx
  src/components/views/elements/EditableText.tsx
  src/components/views/elements/EditableTextContainer.tsx
  src/components/views/elements/LanguageDropdown.tsx
  src/components/views/elements/LazyRenderList.tsx
  src/components/views/elements/PersistedElement.tsx
  src/components/views/elements/PersistentApp.tsx
  src/components/views/elements/PowerSelector.tsx
  src/components/views/elements/Spoiler.tsx
  src/components/views/elements/SyntaxHighlight.tsx
  src/components/views/elements/TextWithTooltip.tsx
  src/components/views/elements/crypto/VerificationQRCode.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/right_panel/WidgetCard.tsx
  src/components/views/rooms/Stickerpicker.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/stores/widgets/StopGapWidget.ts
Labels: T-Task

#6839 Convert `/src/components/views/rooms` to TS
  src/components/views/dialogs/UntrustedDeviceDialog.tsx
  src/components/views/right_panel/VerificationPanel.tsx
  src/components/views/rooms/AppsDrawer.tsx
  src/components/views/rooms/E2EIcon.tsx
  src/components/views/rooms/EntityTile.tsx
  src/components/views/rooms/EventTile.tsx
  src/resizer/resizer.ts
Labels: T-Task

#6547 Update muting in calls to work with the js-sdk call upgrade changes
  src/components/views/voip/CallView.tsx
Labels: T-Task

#6846 Prune unused strings from translation
  src/i18n/strings/ar.json
  src/i18n/strings/az.json
  src/i18n/strings/be.json
  src/i18n/strings/bg.json
  src/i18n/strings/ca.json
  src/i18n/strings/cs.json
  src/i18n/strings/da.json
  src/i18n/strings/de_DE.json
  src/i18n/strings/el.json
  src/i18n/strings/en_US.json
  src/i18n/strings/eo.json
  src/i18n/strings/es.json
  src/i18n/strings/et.json
  src/i18n/strings/eu.json
  src/i18n/strings/fa.json
  src/i18n/strings/fi.json
  src/i18n/strings/fr.json
  src/i18n/strings/ga.json
  src/i18n/strings/gl.json
  src/i18n/strings/he.json
  src/i18n/strings/hi.json
  src/i18n/strings/hr.json
  src/i18n/strings/hu.json
  src/i18n/strings/id.json
  src/i18n/strings/is.json
  src/i18n/strings/it.json
  src/i18n/strings/ja.json
  src/i18n/strings/jbo.json
  src/i18n/strings/kab.json
  src/i18n/strings/ko.json
  src/i18n/strings/lt.json
  src/i18n/strings/lv.json
  src/i18n/strings/ml.json
  src/i18n/strings/nb_NO.json
  src/i18n/strings/nl.json
  src/i18n/strings/nn.json
  src/i18n/strings/oc.json
  src/i18n/strings/pl.json
  src/i18n/strings/pt.json
  src/i18n/strings/pt_BR.json
  src/i18n/strings/ro.json
  src/i18n/strings/ru.json
  src/i18n/strings/sk.json
  src/i18n/strings/sl.json
  src/i18n/strings/sq.json
  src/i18n/strings/sr.json
  src/i18n/strings/sr_Latn.json
  src/i18n/strings/sv.json
  src/i18n/strings/ta.json
  src/i18n/strings/te.json
  src/i18n/strings/th.json
  src/i18n/strings/tr.json
  src/i18n/strings/tzm.json
  src/i18n/strings/uk.json
  src/i18n/strings/vi.json
  src/i18n/strings/vls.json
  src/i18n/strings/zh_Hans.json
  src/i18n/strings/zh_Hant.json
Labels: T-Task

#6843 Convert `/src/components/views/settings/` to TS
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/settings/ChangePassword.tsx
  src/components/views/settings/SecureBackupPanel.tsx
  src/components/views/settings/account/EmailAddresses.tsx
  src/components/views/settings/account/PhoneNumbers.tsx
  src/components/views/settings/discovery/EmailAddresses.tsx
  src/components/views/settings/discovery/PhoneNumbers.tsx
  src/components/views/settings/tabs/room/GeneralRoomSettingsTab.tsx
  src/components/views/settings/tabs/room/NotificationSettingsTab.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/components/views/terms/InlineTermsAgreement.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#6850 Fix resizers not letting go
  src/resizer/resizer.ts
Labels: T-Defect

#6743 Convert `/src/components/views/dialogs` to TS
  src/CountlyAnalytics.ts
  src/components/views/dialogs/BaseDialog.tsx
  src/components/views/dialogs/FeedbackDialog.tsx
  src/components/views/dialogs/IncomingSasDialog.tsx
  src/components/views/dialogs/IntegrationsDisabledDialog.tsx
  src/components/views/dialogs/IntegrationsImpossibleDialog.tsx
  src/components/views/dialogs/InteractiveAuthDialog.tsx
  src/components/views/dialogs/KeySignatureUploadFailedDialog.tsx
  src/components/views/dialogs/LazyLoadingDisabledDialog.tsx
  src/components/views/dialogs/LazyLoadingResyncDialog.tsx
  src/components/views/dialogs/ManualDeviceKeyVerificationDialog.tsx
  src/components/views/dialogs/MessageEditHistoryDialog.tsx
  src/components/views/dialogs/QuestionDialog.tsx
  src/components/views/dialogs/SessionRestoreErrorDialog.tsx
  src/components/views/dialogs/SetEmailDialog.tsx
  src/components/views/dialogs/SlashCommandHelpDialog.tsx
  src/components/views/dialogs/StorageEvictedDialog.tsx
  src/components/views/dialogs/TabbedIntegrationManagerDialog.tsx
  src/components/views/dialogs/TextInputDialog.tsx
  src/components/views/dialogs/UploadFailureDialog.tsx
  src/components/views/dialogs/WidgetOpenIDPermissionsDialog.tsx
  src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx
  src/components/views/dialogs/security/SetupEncryptionDialog.tsx
Labels: T-Task

#6852 Fix spacing for message composer buttons
  res/css/views/rooms/_MessageComposer.scss
Labels: T-Defect

#6854 Fix spacing for message composer buttons
  res/css/views/rooms/_MessageComposer.scss
Labels: T-Defect

#6856 Fix `AppsDrawer` soft crash
  src/components/views/rooms/AppsDrawer.tsx
Labels: T-Defect

#6851 Set comprehensive set of props for thread's MessagePanel
  src/components/structures/ThreadView.tsx
Labels: T-Task

#6858 Close thread view when changing room
  src/components/structures/RightPanel.tsx
Labels: T-Task

#6859 Move timestamp to the right in thread's context
  res/css/views/rooms/_EventTile.scss
Labels: T-Task

#6860 Fix the User View
  src/components/structures/RightPanel.tsx
  src/components/structures/UserView.tsx
Labels: T-Defect

#6857 Change CIDER state persistence key to cater for threads
  src/components/views/rooms/SendMessageComposer.tsx
Labels: T-Task

#6862 Convert `/src/usercontent` to TS
  src/usercontent/index.ts
Labels: T-Task

#6866 Convert `/src/stores` to TS
  src/@types/global.d.ts
  src/Lifecycle.ts
  src/components/views/elements/AppTile.tsx
  src/components/views/elements/PersistentApp.tsx
  src/stores/ActiveWidgetStore.js
  src/stores/ActiveWidgetStore.ts
  src/stores/WidgetStore.ts
  src/stores/widgets/StopGapWidget.ts
Labels: T-Task

#6864 Convert `/src/rageshake` to TS
  src/@types/global.d.ts
  src/rageshake/rageshake.ts
Labels: T-Task

#6863 Convert `/src/utils` to TS
  src/utils/DirectoryUtils.ts
  src/utils/HostingLink.ts
  src/utils/KeyVerificationStateObserver.ts
  src/utils/MegolmExportEncryption.ts
Labels: T-Task

#6861 Convert `/src/components/views/messages` to TS
  src/components/views/messages/EditHistoryMessage.tsx
  src/components/views/messages/MKeyVerificationConclusion.tsx
  src/components/views/messages/MjolnirBody.tsx
  src/components/views/messages/RedactedBody.tsx
  src/components/views/messages/RoomAvatarEvent.tsx
  src/components/views/messages/RoomCreate.tsx
  src/components/views/rooms/EventTile.tsx
Labels: T-Task

#6701 Add ability to expand and collapse long quoted messages
  res/css/views/elements/_ReplyThread.scss
  res/css/views/messages/_MessageActionBar.scss
  res/img/element-icons/collapse-message.svg
  res/img/element-icons/expand-message.svg
  src/components/structures/ContextMenu.tsx
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/elements/ReplyThread.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/messages/TextualBody.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/ReplyTile.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#6824 Fix space admin check false positive on multiple admins
  src/components/views/dialogs/LeaveSpaceDialog.tsx
Labels: T-Defect

#6865 Fix pills being cut off in message bubble layout
  res/css/views/elements/_RichText.scss
Labels: T-Defect

#6699 Improve AUX panel behaviour
  res/css/structures/_RoomView.scss
  src/components/structures/RoomView.tsx
  src/components/views/rooms/AuxPanel.tsx
  src/components/views/voip/CallViewForRoom.tsx
Labels: T-Enhancement

#6871 Fix issue with preview panel close button not appearing for certain messages containing a URL
  src/components/views/rooms/LinkPreviewGroup.tsx
Labels: T-Defect

#6874 Null guard around the matrixClient in SpaceStore
  src/stores/SpaceStore.tsx
Labels: T-Defect

#6825 Happily handle empty text messages
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/dialogs/ConfirmRedactDialog.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/editor/serialize.ts
Labels: T-Enhancement

#6879 Pluck out JoinRuleSettings styles so they apply in space settings too
  res/css/_components.scss
  res/css/views/settings/_JoinRuleSettings.scss
  res/css/views/settings/tabs/room/_SecurityRoomSettingsTab.scss
  src/components/views/settings/JoinRuleSettings.tsx
Labels: T-Defect

#6882 Remove extra 'are' in README
  README.md
Labels: T-Task

#6880 Fix timeline autoscroll with non-standard DPI settings.
  src/components/structures/ScrollPanel.tsx
Labels: T-Defect

#6881 Ensure that sub-spaces aren't considered for notification badges
  src/stores/SpaceStore.tsx
Labels: T-Defect

#6883 Remove stale new in the spaces beta toast & modal
  src/i18n/strings/en_EN.json
  src/stores/SpaceStore.ts
Labels: T-Task

#6878 Fix space children without specific `order` being sorted after those with one
  src/stores/SpaceStore.ts
Labels: T-Defect

#6886 Fix spaces null-guard breaking the dispatcher settings watching
  src/stores/SpaceStore.ts
Labels: T-Defect

#6885 Allow closing Dropdown via its chevron
  src/components/views/elements/Dropdown.tsx
Labels: T-Enhancement

#6867 Allow for customization of compound colors
  res/themes/light-custom/css/_custom.scss
Labels: T-Task
