Repository matrix-org/matrix-react-sdk, pull requests merged in 2021-12, with the labels that each got.

#7247 Fix automatic space switching wrongly going via Home for room aliases
  src/stores/spaces/SpaceStore.ts
Labels: T-Defect

#7073 Replace breadcrumbs with recently viewed menu
  res/css/_components.scss
  res/css/structures/_ContextualMenu.scss
  res/css/structures/_LeftPanel.scss
  res/css/views/avatars/_BaseAvatar.scss
  res/css/views/elements/_InteractiveTooltip.scss
  res/css/views/rooms/_RecentlyViewedButton.scss
  res/img/element-icons/clock.svg
  src/components/structures/LeftPanel.tsx
  src/components/views/elements/InteractiveTooltip.tsx
  src/components/views/rooms/RecentlyViewedButton.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/BreadcrumbsStore.ts
  test/components/views/elements/InteractiveTooltip-test.ts
Labels: T-Enhancement

#7245 Update Space Panel scrollable region
  res/css/structures/_SpacePanel.scss
  res/css/structures/_UserMenu.scss
  src/components/structures/IndicatorScrollbar.tsx
  src/components/views/spaces/SpacePanel.tsx
Labels: T-Enhancement

#7226 Don't show edit button for hidden edit events
  src/utils/EventUtils.ts
Labels: T-Task

#7242 Hide clear cache and reload button if crash is before client init
  src/components/structures/LoggedInView.tsx
  src/components/views/elements/ErrorBoundary.tsx
Labels: T-Defect

#7243 Fix wrongly sized default sub-space icons in space panel
  res/css/structures/_SpacePanel.scss
Labels: T-Defect

#7240 Disallow sending empty feedbacks
  src/components/views/dialogs/FeedbackDialog.tsx
Labels: T-Defect

#7248 Fix user menu bottom stroke
  res/css/structures/_UserMenu.scss
Labels: T-Task

#7249 Autofocus device panel entry when renaming device
  src/components/views/settings/DevicesPanelEntry.tsx
Labels: T-Enhancement

#7251 Break long words in pinned messages to prevent overflow
  res/css/views/right_panel/_PinnedMessagesCard.scss
Labels: T-Defect

#7179 Fix setBotPower to not use `.content`
  src/ScalarMessaging.ts
Labels: T-Defect

#7252 Fix broken i18n in Forgot & Change password
  src/components/structures/auth/ForgotPassword.tsx
  src/components/views/settings/ChangePassword.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7239 Fix textual message stripping new line
  src/HtmlUtils.tsx
  test/components/views/messages/TextualBody-test.js
Labels: T-Defect

#7254 Tweak roving tab index focus behaviour
  src/accessibility/RovingTabIndex.tsx
Labels: T-Task

#7256 Fix video calls
  src/components/views/rooms/RoomHeader.tsx
Labels: T-Defect

#7259 Fixes more instances of double-translation
  src/components/structures/auth/ForgotPassword.tsx
  src/components/views/auth/RegistrationForm.tsx
  src/components/views/dialogs/RegistrationEmailPromptDialog.tsx
Labels: T-Defect

#7255 Improve ease of focusing on Room list Search
  res/css/structures/_LeftPanel.scss
  src/components/structures/RoomSearch.tsx
Labels: T-Enhancement

#7260 Decorate view keyboard shortcuts link as a link
  res/css/views/settings/tabs/user/_PreferencesUserSettingsTab.scss
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7261 Add utility method mxLoginWithAccessToken to login with existing access token
  src/@types/global.d.ts
  src/Lifecycle.ts
  src/MatrixClientPeg.ts
Labels: T-Task

#7264 Make composer buttons react to settings without having to change room
  src/components/views/rooms/MessageComposer.tsx
  src/settings/Settings.tsx
Labels: T-Enhancement

#7266 Remove the `Screen sharing is here!` dialog
  src/components/views/rooms/RoomHeader.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7258 Render mini user menu for when space panel is disabled
  res/css/structures/_LeftPanel.scss
  res/css/structures/_SpacePanel.scss
  res/css/structures/_UserMenu.scss
  src/components/structures/LeftPanel.tsx
  src/components/views/rooms/RoomListHeader.tsx
Labels: T-Defect

#7268 Revert https://github.com/matrix-org/matrix-react-sdk/pull/7246
  test/end-to-end-tests/synapse/install.sh
Labels: T-Task

#7233 Ensure my votes from a different device show up
  src/components/views/messages/MPollBody.tsx
  test/components/views/messages/MPollBody-test.tsx
Labels: T-Task

#7270 Make a few colors customizable
  res/themes/light-custom/css/_custom.scss
Labels: T-Task

#7271 Task/colors-13
  res/css/views/messages/_ReactionsRowButton.scss
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light/css/_light.scss
Labels: T-Task

#7269 Hide votes in a poll until you voted
  src/components/views/messages/MPollBody.tsx
  src/i18n/strings/en_EN.json
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/messages/__snapshots__/MPollBody-test.tsx.snap
Labels: T-Task

#7274 Don't inhibit current room notifications if user has Modal open
  src/BasePlatform.ts
  src/Notifier.ts
Labels: T-Enhancement

#7272 When accepting DM from People metaspace don't switch to Home
  src/stores/spaces/SpaceStore.ts
  test/stores/SpaceStore-test.ts
Labels: T-Defect

#7279 Refactor matrix-linkify module
  src/HtmlUtils.tsx
  src/Markdown.ts
  src/components/structures/MatrixChat.tsx
  src/linkify-matrix.ts
  src/utils/permalinks/Permalinks.ts
  test/Markdown-test.ts
  test/linkify-matrix-test.ts
Labels: T-Task

#6936 Analytics opt in for posthog
  res/css/_components.scss
  res/css/views/dialogs/_Analytics.scss
  res/css/views/dialogs/_AnalyticsLearnMoreDialog.scss
  res/css/views/toasts/_AnalyticsToast.scss
  res/img/element-shiny.svg
  res/img/tick-circle.svg
  src/Analytics.tsx
  src/Lifecycle.ts
  src/PosthogAnalytics.ts
  src/components/structures/MatrixChat.tsx
  src/components/views/dialogs/AnalyticsLearnMoreDialog.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/dispatcher/actions.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/controllers/PseudonymousAnalyticsController.ts
  src/settings/handlers/AccountSettingsHandler.ts
  src/toasts/AnalyticsToast.tsx
  test/end-to-end-tests/src/scenarios/toast.js
Labels: T-Enhancement

#7287 Don't allow calls when the connection the server has been lost
  src/CallHandler.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7289 Update URL when room aliases are modified
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomView.tsx
Labels: T-Defect

#7288 In People & Favourites metaspaces always show all rooms
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomSublist.tsx
Labels: T-Enhancement

#7278 Expose PL control for pinned events when lab enabled
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7277 Dropdown follow wai-aria practices for expanding on arrow keys
  src/components/views/elements/Dropdown.tsx
Labels: T-Enhancement

#7276 Finish sending pending messages before leaving room
  src/components/structures/MatrixChat.tsx
  src/utils/membership.ts
Labels: T-Enhancement

#7290 Fix labs exploding when lab group is empty
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
Labels: T-Defect

#7135 Simple static location sharing
  package.json
  res/css/_common.scss
  res/css/_components.scss
  res/css/views/location/_LocationPicker.scss
  res/css/views/messages/_MLocationBody.scss
  res/css/views/rooms/_MessageComposer.scss
  res/img/element-icons/room/composer/location.svg
  src/components/views/location/LocationPicker.tsx
  src/components/views/location/LocationShareType.tsx
  src/components/views/messages/MLocationBody.tsx
  src/components/views/messages/MessageEvent.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/controllers/SettingController.ts
  test/setupTests.js
  yarn.lock
Labels: T-Enhancement

#7185 Custom location sharing.
  src/components/views/location/LocationPicker.tsx
  src/components/views/messages/MLocationBody.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7262 Add edits and replies to the right panel timeline & prepare the timelineCard to share code with threads
  src/components/structures/RightPanel.tsx
  src/components/views/right_panel/TimelineCard.tsx
Labels: T-Defect

#7291 Fix: Warning: Unsupported style property pointer-events. Did you mean pointerEvents?
  src/components/views/elements/AppTile.tsx
Labels: T-Defect

#7234 Add CSS variable to make the UI gaps consistent and fix the resize handle position
  res/css/_common.scss
  res/css/structures/_MainSplit.scss
  res/css/structures/_MatrixChat.scss
  res/css/structures/_RoomView.scss
  res/css/views/elements/_ResizeHandle.scss
  res/css/views/rooms/_AppsDrawer.scss
  res/css/views/voip/_CallView.scss
  res/css/views/voip/_CallViewForRoom.scss
Labels: T-Enhancement

#7280 Fix jump to bottom on message send
  src/components/structures/RoomView.tsx
Labels: T-Defect

#7294 Make emoji picker search placeholder localizable
  src/components/views/emojipicker/Search.tsx
Labels: T-Defect

#7295 Allow sharing manual location without giving location permission
  src/components/views/location/LocationPicker.tsx
Labels: T-Defect

#7292 Corrected the alignment of the Edit button on LoginPage.
  res/css/views/elements/_ServerPicker.scss
Labels: T-Defect

#7230 Update space panel expand mechanism
  res/css/structures/_SpacePanel.scss
  res/css/structures/_UserMenu.scss
  res/img/element-icons/expand-space-panel.svg
  src/KeyBindingsDefaults.ts
  src/KeyBindingsManager.ts
  src/accessibility/KeyboardShortcuts.tsx
  src/components/structures/LoggedInView.tsx
  src/components/structures/UserMenu.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/dispatcher/actions.ts
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7293 Fix input field behaviour inside context menus
  src/components/structures/ContextMenu.tsx
  src/components/structures/LoggedInView.tsx
Labels: T-Defect

#7300 Fix wrong indentation with nested ordered list unnesting list on edit
  src/editor/deserialize.ts
  test/editor/deserialize-test.js
Labels: T-Defect

#7303 Fix issue with room list resizer getting clipped in firefox
  res/css/views/rooms/_RoomSublist.scss
Labels: T-Defect

#7304 fix leaking unit test for Registration
  test/components/structures/auth/Registration-test.js
Labels: T-Task

#7305 Allow ending polls
  res/css/views/context_menus/_MessageContextMenu.scss
  res/css/views/messages/_MPollBody.scss
  res/img/element-icons/trophy.svg
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/dialogs/EndPollDialog.tsx
  src/components/views/messages/MPollBody.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
  src/polls/consts.ts
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/messages/__snapshots__/MPollBody-test.tsx.snap
Labels: T-Task

#7309 💚 Update PR description editing action
  .github/workflows/netlify.yaml
Labels: T-Task

#7312 Fix html exporting and improve output size
  src/utils/exportUtils/HtmlExport.tsx
  src/utils/exportUtils/exportCSS.ts
  tsconfig.json
Labels: T-Defect

#7306 Make clear button images visible in high contrast theme
  res/themes/light-high-contrast/css/_light-high-contrast.scss
Labels: T-Defect

#7308 Iterate room context menus for DMs
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/rooms/RoomTile.tsx
Labels: T-Enhancement

#7314 Add vertical spacing between buttons when they go over multiple lines
  res/css/_common.scss
  res/css/views/settings/_CryptographyPanel.scss
  res/css/views/settings/_SecureBackupPanel.scss
Labels: T-Defect

#7315 Fix favourites and people metaspaces not rendering their content
  res/css/views/rooms/_RoomSublist.scss
Labels: T-Defect

#7281 Make tooltips keyboard accessible
  res/css/views/elements/_TextWithTooltip.scss
  src/components/views/elements/AccessibleTooltipButton.tsx
  src/components/views/elements/ActionButton.tsx
  src/components/views/elements/InfoTooltip.tsx
  src/components/views/elements/TextWithTooltip.tsx
  src/components/views/elements/Tooltip.tsx
  src/components/views/elements/TooltipButton.tsx
  src/components/views/elements/TooltipTarget.tsx
  src/components/views/rooms/EventTile.tsx
  test/components/views/elements/TooltipTarget-test.tsx
  test/components/views/elements/__snapshots__/TooltipTarget-test.tsx.snap
Labels: T-Enhancement

#7302 Correct tab order in room preview dialog
  res/css/views/rooms/_RoomPreviewBar.scss
  src/components/views/rooms/RoomPreviewBar.tsx
  test/components/views/rooms/RoomPreviewBar-test.tsx
  test/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
  test/test-utils.js
Labels: T-Defect

#7310 Add descriptions to ambiguous links for screen readers
  res/css/_components.scss
  res/css/views/elements/_ExternalLink.scss
  res/css/views/settings/_ProfileSettings.scss
  src/components/views/dialogs/ShareDialog.tsx
  src/components/views/elements/ExternalLink.tsx
  src/components/views/settings/ProfileSettings.tsx
  src/i18n/strings/en_EN.json
  test/components/views/elements/ExternalLink-test.tsx
  test/components/views/elements/__snapshots__/ExternalLink-test.tsx.snap
Labels: T-Enhancement

#7316 Improve accessibility of opening space create menu
  src/components/views/spaces/SpaceCreateMenu.tsx
Labels: T-Defect

#7319 default export for TooltipTarget
  src/components/views/elements/InfoTooltip.tsx
  src/components/views/elements/TextWithTooltip.tsx
  src/components/views/elements/TooltipButton.tsx
  src/components/views/elements/TooltipTarget.tsx
  test/components/views/elements/TooltipTarget-test.tsx
Labels: T-Task

#7318 Support reactions, replies and forwards of polls
  res/css/views/messages/_MPollBody.scss
  src/utils/EventUtils.ts
Labels: T-Task

#7311 Put room settings form elements in fieldsets
  res/css/_common.scss
  res/css/_components.scss
  res/css/views/dialogs/_SettingsDialog.scss
  res/css/views/elements/_SettingsFlag.scss
  res/css/views/settings/_SettingsFieldset.scss
  src/components/views/elements/SettingsFlag.tsx
  src/components/views/room_settings/AliasSettings.tsx
  src/components/views/room_settings/UrlPreviewSettings.tsx
  src/components/views/settings/SettingsFieldset.tsx
  src/components/views/settings/tabs/room/GeneralRoomSettingsTab.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/components/views/spaces/SpaceSettingsVisibilityTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/SettingsFieldset-test.tsx
  test/components/views/settings/__snapshots__/SettingsFieldset-test.tsx.snap
Labels: T-Enhancement

#7324 Don't show options button when the user can't modify widgets
  src/components/views/right_panel/RoomSummaryCard.tsx
Labels: T-Defect

#7327 Update yarn.lock
  package.json
  yarn.lock
Labels: T-Task

#7116 Spotlight search labs
  res/css/_components.scss
  res/css/views/avatars/_DecoratedRoomAvatar.scss
  res/css/views/dialogs/_SpotlightDialog.scss
  src/Rooms.ts
  src/accessibility/RovingTabIndex.tsx
  src/components/structures/RoomSearch.tsx
  src/components/structures/SearchBox.tsx
  src/components/views/dialogs/SpotlightDialog.tsx
  src/dispatcher/actions.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/accessibility/RovingTabIndex-test.tsx
Labels: T-Enhancement

#7320 Show poll question in message preview
  src/stores/room-list/MessagePreviewStore.ts
  src/stores/room-list/previews/PollStartEventPreview.ts
  test/stores/room-list/previews/PollStartEventPreview-test.ts
Labels: T-Task

#7326 Don't send a poll response event if you are voting for your current c…
  src/components/views/messages/MPollBody.tsx
  test/components/views/messages/MPollBody-test.tsx
Labels: T-Defect

#7332 Don't show polls in timeline if polls are disabled
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#7334 No-op action:join if the user is already invited for scalar
  src/ScalarMessaging.ts
Labels: T-Defect

#7328 don't collapse spaces in inline code blocks
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#7331 Only show poll previews when the polls feature is enabled
  src/stores/room-list/MessagePreviewStore.ts
Labels: T-Defect

#7340 Keep all previously approved widget capabilities when requesting new capabilities
  src/stores/widgets/StopGapWidgetDriver.ts
  src/utils/iterables.ts
  test/utils/iterables-test.ts
Labels: T-Defect

#7343 Fix naming of set-theory utils to match convention
  src/stores/widgets/StopGapWidgetDriver.ts
  src/utils/arrays.ts
  src/utils/iterables.ts
  src/utils/maps.ts
  src/utils/objects.ts
  test/utils/arrays-test.ts
  test/utils/iterables-test.ts
Labels: T-Task

#7344 Update Typescript to 4.5
  package.json
  src/@types/global.d.ts
  src/ContentMessages.tsx
  yarn.lock
Labels: T-Task

#7338 Update status message in the member list and user info panel when it is changed
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/MemberTile.tsx
  src/hooks/useUserStatusMessage.ts
Labels: T-Enhancement

#7345 Show votes in replied-to polls (pass in getRelationsForEvent)
  src/components/views/elements/ReplyChain.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/ReplyTile.tsx
Labels: T-Defect

#7347 update olm to 3.2.8
  package.json
  yarn.lock
Labels: T-Task

#7335 Iterate space panel toggle collapse interaction
  res/css/structures/_SpacePanel.scss
Labels: T-Enhancement

#7341 Fix upgraded rooms wrongly showing up in spotlight
  src/components/views/dialogs/SpotlightDialog.tsx
Labels: T-Defect

#7299 Always unhide widgets on layout change (pinning a widget)
  src/components/structures/RoomView.tsx
Labels: T-Enhancement

#7354 Fix thread filter being cut-off on narrow screens
  res/css/views/right_panel/_ThreadPanel.scss
  src/components/structures/ThreadPanel.tsx
Labels: T-Defect

#7357 Debounce User Info start dm "Message" button
  src/components/views/right_panel/UserInfo.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7336 Fix accessibility regressions
  src/accessibility/RovingTabIndex.tsx
  src/accessibility/Toolbar.tsx
  src/components/views/avatars/DecoratedRoomAvatar.tsx
  src/components/views/context_menus/ThreadListContextMenu.tsx
  src/components/views/elements/TextWithTooltip.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/RoomTile.tsx
Labels: X-Release-Blocker, T-Defect

#7363 Fix room search sometimes not opening spotlight
  src/components/structures/RoomSearch.tsx
Labels: T-Defect

#7364 Fix room join spinner in room list header
  src/components/views/rooms/RoomListHeader.tsx
Labels: T-Defect

#7365 Fix useUserStatusMessage exploding on unknown user
  src/hooks/useUserStatusMessage.ts
Labels: T-Defect

#7367 Tweak FacePile tooltip to include whether or not you are included
  src/components/views/elements/FacePile.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7369 Use lazy rendering in the AddExistingToSpaceDialog
  src/components/structures/AutoHideScrollbar.tsx
  src/components/views/dialogs/AddExistingToSpaceDialog.tsx
  src/components/views/emojipicker/EmojiPicker.tsx
Labels: T-Enhancement

#7361 Update room context menu copy
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/rooms/RoomTile.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7362 Add Heading components
  res/css/_components.scss
  res/css/views/typography/_Heading.scss
  src/components/views/typography/Heading.tsx
  test/components/views/typography/Heading-test.tsx
  test/components/views/typography/__snapshots__/Heading-test.tsx.snap
Labels: T-Task

#7372 Add `/jumptodate` slash command
  src/SlashCommands.tsx
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Enhancement

#7383 Use semantic heading on dialog component
  res/css/_common.scss
  res/css/views/dialogs/_SettingsDialog.scss
  src/components/views/dialogs/BaseDialog.tsx
Labels: T-Enhancement

#7386 Fix narrow mode composer buttons for polls labs
  src/components/views/rooms/MessageComposer.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7380 Prevent escape to cancel edit from also scrolling to bottom
  src/components/views/rooms/EditMessageComposer.tsx
Labels: T-Defect

#7385 Add internationalisation to progress strings in room export dialog
  src/components/views/dialogs/ExportDialog.tsx
  src/i18n/strings/en_EN.json
  src/utils/exportUtils/Exporter.ts
  src/utils/exportUtils/HtmlExport.tsx
  src/utils/exportUtils/JSONExport.ts
  src/utils/exportUtils/PlainTextExport.ts
Labels: T-Defect

#7378 Pin qrcode to fix e2e verification bug
  package.json
  yarn.lock
Labels: T-Defect

#7379 [Release] Pin qrcode to fix e2e verification bug
  package.json
  yarn.lock
Labels: X-Release-Blocker

#7382 Make compact layout only apply to Modern layout
  src/components/structures/LoggedInView.tsx
  src/components/views/elements/Field.tsx
  src/components/views/settings/tabs/user/AppearanceUserSettingsTab.tsx
  src/settings/Settings.tsx
  src/settings/controllers/IncompatibleController.ts
Labels: T-Defect

#7387 Use the moved makePollContent function from js-sdk
  src/components/views/elements/PollCreateDialog.tsx
Labels: T-Task

#7388 Use UnstableValue for all location constants
  src/components/views/messages/MLocationBody.tsx
  src/components/views/messages/MessageEvent.tsx
  src/components/views/rooms/MessageComposer.tsx
Labels: T-Task

#7389 Fix MaxListenersExceededWarning
  src/components/structures/RoomView.tsx
Labels: T-Task

#7375 Don't include the accuracy parameter in location events if accuracy could not be determined.
  src/components/views/location/LocationPicker.tsx
Labels: T-Defect

#7384 Improve typing around LoggedInView
  src/CallHandler.tsx
  src/components/structures/LoggedInView.tsx
  src/components/structures/RoomStatusBar.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/messages/MImageBody.tsx
Labels: T-Task

#7395 Unit tests for parseGeoUri
  src/components/views/messages/MLocationBody.tsx
  test/components/views/messages/MLocationBody-test.tsx
Labels: T-Task

#7392 Fix alignment between ELS and Events in bubble layout
  res/css/views/rooms/_EventBubbleTile.scss
Labels: T-Defect

#7393 Fix bubble radius wrong when followed by a state event from same user
  src/components/structures/MessagePanel.tsx
Labels: T-Defect

#7394 Fix sizing of e2e shield in bubble layout
  res/css/views/rooms/_EventBubbleTile.scss
Labels: T-Defect

#7358 Have LocalEchoWrapper emit updates so the app can react faster
  src/settings/SettingsStore.ts
  src/settings/handlers/AccountSettingsHandler.ts
  src/settings/handlers/DeviceSettingsHandler.ts
  src/settings/handlers/LocalEchoWrapper.ts
  src/settings/handlers/RoomAccountSettingsHandler.ts
  src/settings/handlers/RoomDeviceSettingsHandler.ts
  src/settings/handlers/RoomSettingsHandler.ts
  src/settings/handlers/SettingsHandler.ts
Labels: T-Enhancement

#7356 Fix list of members in space preview
  src/components/structures/SpaceRoomView.tsx
Labels: T-Defect

#7250 Space preferences for whether or not you see DMs in a Space
  res/css/_components.scss
  res/css/structures/_SpacePanel.scss
  res/css/views/dialogs/_SettingsDialog.scss
  res/css/views/dialogs/_SpacePreferencesDialog.scss
  src/components/views/context_menus/SpaceContextMenu.tsx
  src/components/views/dialogs/SpacePreferencesDialog.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/rooms/NewRoomIntro.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/WatchManager.ts
  src/stores/room-list/SpaceWatcher.ts
  src/stores/room-list/filters/SpaceFilterCondition.ts
  src/stores/spaces/SpaceStore.ts
  src/stores/spaces/index.ts
  src/utils/arrays.ts
  src/utils/sets.ts
  src/utils/space.tsx
  test/stores/SpaceStore-test.ts
  test/test-utils.js
Labels: T-Enhancement

#7391 Increase gap between ELS and the subsequent event to prevent overlap
  res/css/views/rooms/_EventBubbleTile.scss
  src/components/views/elements/MemberEventListSummary.tsx
Labels: T-Defect

#7396 Avoid NaNs in parseGeoUri return
  src/components/views/messages/MLocationBody.tsx
  test/components/views/messages/MLocationBody-test.tsx
Labels: T-Task

#7399 Show error if could not load space hierarchy
  src/components/structures/SpaceHierarchy.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7400 Tests for getGeoUri
  src/components/views/location/LocationPicker.tsx
  test/components/views/location/LocationPicker-test.tsx
Labels: T-Task

#7401 Fix notification badge for All Rooms space
  src/components/structures/MatrixChat.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/stores/notifications/RoomNotificationStateStore.ts
Labels: T-Defect

#7402 Tidy location code
  src/components/views/location/LocationPicker.tsx
  src/components/views/messages/MLocationBody.tsx
  src/components/views/rooms/MessageComposer.tsx
  test/components/views/location/LocationPicker-test.tsx
Labels: T-Task

#7406 Fix inline code block nowrap issue
  res/css/views/rooms/_EventTile.scss
Labels: X-Release-Blocker, T-Defect

#7407 [Release] Fix inline code block nowrap issue
  res/css/views/rooms/_EventTile.scss
Labels: X-Release-Blocker, T-Defect

#7404 Space Panel use SettingsStore instead of SpaceStore as source of truth
  src/components/views/spaces/SpacePanel.tsx
  src/stores/spaces/SpaceStore.ts
Labels: T-Defect

#7353 Refactor `ContextMenu` to use `RovingTabIndex` (more consistent keyboard navigation accessibility)
  res/css/structures/_UserMenu.scss
  src/accessibility/RovingTabIndex.tsx
  src/accessibility/context_menu/MenuItem.tsx
  src/accessibility/context_menu/MenuItemCheckbox.tsx
  src/accessibility/context_menu/MenuItemRadio.tsx
  src/accessibility/context_menu/StyledMenuItemCheckbox.tsx
  src/accessibility/context_menu/StyledMenuItemRadio.tsx
  src/components/structures/ContextMenu.tsx
  src/components/structures/LoggedInView.tsx
  src/components/structures/UserMenu.tsx
  src/components/views/elements/StyledCheckbox.tsx
  src/components/views/elements/StyledRadioButton.tsx
  src/components/views/rooms/RoomSublist.tsx
  test/components/structures/__snapshots__/ThreadPanel-test.tsx.snap
Labels: T-Task

#7416 [Release] Fix HTML Export where the data-mx-theme is `Light` not `light`
  src/utils/exportUtils/exportCSS.ts
Labels: X-Release-Blocker

#7419 [Release] Fix useUserStatusMessage exploding on unknown user
  src/hooks/useUserStatusMessage.ts
Labels: X-Release-Blocker

#7420 Fix end-to-end tests (synapse setup)
  test/end-to-end-tests/element/install-webserver.sh
  test/end-to-end-tests/synapse/install.sh
Labels: T-Task

#7405 Add configuration to disable relative date markers in timeline
  src/components/views/messages/DateSeparator.tsx
  src/settings/Settings.tsx
  src/settings/UIFeature.ts
  test/components/views/messages/DateSeparator-test.tsx
  test/components/views/messages/__snapshots__/DateSeparator-test.tsx.snap
  test/skinned-sdk.js
Labels: T-Enhancement

#7408 Update location text fallback and test it
  src/components/views/location/LocationButton.tsx
  src/components/views/rooms/CollapsibleButton.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/i18n/strings/en_EN.json
  test/components/views/location/LocationButton-test.tsx
Labels: T-Task

#7422 Fix list formatting alternating on edit
  src/editor/deserialize.ts
  test/editor/deserialize-test.js
Labels: T-Defect

#7425 Fix legacy breadcrumbs wrongly showing up
  src/components/structures/LeftPanel.tsx
Labels: T-Defect

#7423 Remove the Forward and Share buttons for location messages only
  src/components/views/context_menus/MessageContextMenu.tsx
Labels: T-Enhancement

#7426 Fix invisible toggle space panel button
  res/css/structures/_SpacePanel.scss
Labels: T-Defect

#7427 Don't show `Testing small changes` without UIFeature.Feedback
  src/components/structures/MatrixChat.tsx
Labels: T-Defect

#7424 Display the user's avatar when they shared their location
  res/css/views/messages/_MLocationBody.scss
  res/img/location/pointer.svg
  src/components/views/messages/MLocationBody.tsx
Labels: T-Enhancement

#7432 Space panel should watch spaces for space name changes
  src/components/views/rooms/RoomListHeader.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  src/hooks/useEventEmitter.ts
Labels: T-Defect

#7428 Allow opening a map view in OpenStreetMap
  res/css/views/context_menus/_MessageContextMenu.scss
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/location/LocationButton.tsx
  src/components/views/messages/MLocationBody.tsx
  src/components/views/rooms/CollapsibleButton.tsx
  src/i18n/strings/en_EN.json
  test/components/views/messages/MLocationBody-test.tsx
Labels: T-Enhancement

#7429 Fix zIndex of peristent apps in miniMode
  src/components/views/elements/AppTile.tsx
Labels: T-Defect

#7433 Fix nulls leaking into geo urls
  src/components/views/location/LocationPicker.tsx
  test/components/views/location/LocationPicker-test.tsx
Labels: T-Defect

#7437 Prevent keyboard propagation out of context menus
  src/components/structures/ContextMenu.tsx
Labels: T-Defect

#7438 Don't disable username/password fields whilst doing wk-lookup
  src/components/views/auth/PasswordLogin.tsx
Labels: T-Defect

#7418 Fix being wrongly sent to Home space when creating/joining/leaving rooms
  src/stores/spaces/SpaceStore.ts
  src/utils/membership.ts
Labels: T-Defect

#7411 Fix width overflow in mini composer overflow menu
  res/css/views/rooms/_MessageComposer.scss
  src/components/views/rooms/MessageComposer.tsx
Labels: T-Defect

#7412 Disable quick reactions button when no permissions
  src/components/views/messages/ReactionsRow.tsx
  src/components/views/messages/ReactionsRowButton.tsx
Labels: T-Enhancement

#7410 Hide non-functional list options on Suggested sublist
  src/components/views/rooms/RoomSublist.tsx
Labels: T-Defect

#7446 Fix dialpad positioning
  src/components/views/voip/CallView/CallViewButtons.tsx
Labels: T-Defect

#7413 Move hideSender logic into state so it causes re-render
  src/components/structures/MessagePanel.tsx
Labels: T-Defect

#7325 Wrap status message
  res/css/views/right_panel/_UserInfo.scss
Labels: T-Defect
