Repository matrix-org/matrix-react-sdk, pull requests merged in 2021-11, with the labels that each got.

#7057 Silence some widgets for better screen reader presentation.
  src/components/views/avatars/BaseAvatar.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/ReadReceiptMarker.tsx
  src/components/views/rooms/WhoIsTypingTile.tsx
Labels: T-Enhancement

#7061 Add convenience inline links to README.md
  README.md
Labels: T-Task

#6119 Show a gray shield when encrypted by deleted session
  res/css/views/rooms/_EventTile.scss
  src/components/views/rooms/EventTile.tsx
Labels: T-Enhancement

#7001 Polls: Creation form & start event
  res/css/_common.scss
  res/css/_components.scss
  res/css/views/dialogs/_CompoundDialog.scss
  res/css/views/dialogs/_PollCreateDialog.scss
  res/css/views/elements/_AccessibleButton.scss
  res/css/views/elements/_Field.scss
  res/img/element-icons/x-8px.svg
  src/components/views/dialogs/ScrollableBaseModal.tsx
  src/components/views/elements/Field.tsx
  src/components/views/elements/PollCreateDialog.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/i18n/strings/en_EN.json
  src/polls/consts.ts
Labels: Sponsored, T-Enhancement

#6083 Improve the look of the spinner
  res/css/views/elements/_InlineSpinner.scss
  res/css/views/elements/_Spinner.scss
  res/img/spinner.svg
  res/img/spinner/spinner-background.svg
  res/img/spinner/spinner-foreground.svg
Labels: T-Enhancement

#7049 Improve the look of tooltips
  res/css/views/elements/_Tooltip.scss
  src/components/views/elements/AccessibleTooltipButton.tsx
Labels: T-Enhancement

#7065 Restore composer focus after event edit
  src/components/views/rooms/EditMessageComposer.tsx
Labels: T-Defect

#7055 Add a condition to only activate the resizer which belongs to the clicked handle
  src/resizer/resizer.ts
Labels: T-Defect

#7067 Null-guard for missing root event in thread panel
  src/components/structures/ThreadPanel.tsx
Labels: T-Task

#7070 Update allchange to 1.0.5
  package.json
  yarn.lock
Labels: T-Task

#7075 Fix documentation to make `yarn test` work out of the box (mk II)
  README.md
  scripts/fetchdep.sh
Labels: T-Task

#7053 Don't re-sort rooms on no-op RoomUpdateCause.PossibleTagChange
  src/stores/room-list/algorithms/Algorithm.ts
Labels: T-Defect

#7064 Make attachments uploadable to a thread
  res/css/structures/_UploadBar.scss
  src/ContentMessages.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadView.tsx
  src/components/structures/UploadBar.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/models/IUpload.ts
Labels: T-Task

#7078 Design thread list tiles according to mockups
  res/css/views/right_panel/_ThreadPanel.scss
  res/css/views/rooms/_EventTile.scss
  src/components/structures/ThreadPanel.tsx
  src/components/structures/ThreadView.tsx
  src/components/views/context_menus/ThreadListContextMenu.tsx
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/__snapshots__/ThreadPanel-test.tsx.snap
Labels: T-Task

#7079 Fix thread switching sometimes stuck
  src/components/structures/ThreadView.tsx
  src/components/views/messages/MessageActionBar.tsx
Labels: T-Task

#7081 Use device IDs for nameless devices in device list
  src/components/views/settings/DevicesPanelEntry.tsx
Labels: T-Defect

#6978 Do pre-submit availability check on username during registration
  src/components/structures/auth/Registration.tsx
  src/components/views/auth/RegistrationForm.tsx
  src/components/views/elements/Validation.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7080 Resolve thread from room Map rather than incorrect ref
  src/components/structures/ThreadView.tsx
Labels: T-Task

#7071 Fix possible infinite loop on widget start
  src/components/views/elements/AppTile.tsx
Labels: T-Defect

#7082 Fix TimeZone to be UTC in Jest tests
  package.json
  test/globalSetup.js
Labels: T-Task

#7083 Rename mx_RadioButton to mx_StyledRadioButton to match class name
  res/css/views/dialogs/_ExportDialog.scss
  res/css/views/dialogs/_FeedbackDialog.scss
  res/css/views/dialogs/_SpaceSettingsDialog.scss
  res/css/views/dialogs/security/_CreateSecretStorageDialog.scss
  res/css/views/elements/_StyledRadioButton.scss
  res/css/views/rooms/_RoomSublist.scss
  res/css/views/settings/_JoinRuleSettings.scss
  res/css/views/settings/_LayoutSwitcher.scss
  res/css/views/settings/_Notifications.scss
  res/css/views/settings/_ThemeChoicePanel.scss
  res/css/views/spaces/_SpaceChildrenPicker.scss
  res/themes/light-high-contrast/css/_light-high-contrast.scss
  src/components/views/elements/StyledRadioButton.tsx
  test/components/views/settings/__snapshots__/ThemeChoicePanel-test.tsx.snap
Labels: T-Task

#7084 Add Labs flag for maximised widgets
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Task

#7085 Fix MemberAvatar rendering and thread info color
  res/css/views/rooms/_EventTile.scss
  src/components/views/auth/PasswordLogin.tsx
  src/components/views/rooms/EventTile.tsx
Labels: T-Task

#7089 Update app slogan to match latest marketing
  src/components/structures/HomePage.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#7090 Update highlighted event line to prevent content jumping
  res/css/views/rooms/_EventTile.scss
Labels: T-Task

#7093 Forget member-list query when switching out of a room
  src/components/structures/RightPanel.tsx
  src/components/views/rooms/MemberList.tsx
Labels: T-Enhancement

#7091 Remove `sdk.getComponent()` where possible
  src/SecurityManager.ts
  src/components/structures/GroupFilterPanel.tsx
  src/components/structures/auth/CompleteSecurity.tsx
  src/components/structures/auth/ForgotPassword.tsx
  src/components/views/dialogs/InfoDialog.tsx
  src/components/views/dialogs/IntegrationsImpossibleDialog.tsx
  src/components/views/dialogs/LogoutDialog.tsx
  src/components/views/messages/MStickerBody.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/rooms/AppsDrawer.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/components/views/settings/CrossSigningPanel.tsx
  src/components/views/terms/InlineTermsAgreement.tsx
  src/components/views/verification/VerificationCancelled.tsx
  src/components/views/verification/VerificationComplete.tsx
Labels: T-Task

#7050 Color cleanup number six
  res/css/_common.scss
  res/css/structures/_RightPanel.scss
  res/css/structures/_TabbedView.scss
  res/css/views/auth/_AuthBody.scss
  res/css/views/auth/_CompleteSecurityBody.scss
  res/css/views/avatars/_BaseAvatar.scss
  res/css/views/avatars/_DecoratedRoomAvatar.scss
  res/css/views/dialogs/_ForwardDialog.scss
  res/css/views/dialogs/security/_AccessSecretStorageDialog.scss
  res/css/views/directory/_NetworkDropdown.scss
  res/css/views/elements/_AccessibleButton.scss
  res/css/views/elements/_DirectorySearchBox.scss
  res/css/views/elements/_Field.scss
  res/css/views/elements/_ProgressBar.scss
  res/css/views/elements/_ReplyChain.scss
  res/css/views/elements/_RichText.scss
  res/css/views/elements/_SSOButtons.scss
  res/css/views/elements/_Slider.scss
  res/css/views/elements/_ToggleSwitch.scss
  res/css/views/elements/_Validation.scss
  res/css/views/emojipicker/_EmojiPicker.scss
  res/css/views/rooms/_BasicMessageComposer.scss
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_LinkPreviewWidget.scss
  res/css/views/rooms/_MemberList.scss
  res/css/views/rooms/_MessageComposer.scss
  res/css/views/rooms/_Stickers.scss
  res/css/views/settings/_AvatarSetting.scss
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light-custom/css/_custom.scss
  res/themes/light-high-contrast/css/_light-high-contrast.scss
  res/themes/light/css/_light.scss
Labels: T-Task

#7092 Fix avatar disappearing when setting a room topic
  src/components/views/room_settings/RoomProfileSettings.tsx
Labels: T-Defect

#7096 Fix quote button
  src/components/views/context_menus/MessageContextMenu.tsx
Labels: T-Defect

#7099 Update powerlevel/role when the user changes in the user info panel
  src/components/views/right_panel/UserInfo.tsx
Labels: T-Defect

#7101 Fix space panel layout edge cases
  res/css/structures/_SpacePanel.scss
Labels: T-Defect

#7103 Remove all unreferenced images
  res/img/cancel-red.svg
  res/img/element-icons/message/corner-up-right.svg
  res/img/element-icons/message/link.svg
  res/img/element-icons/message/repeat.svg
  res/img/element-icons/message/share.svg
  res/img/element-icons/message/view-in-timeline.svg
  res/img/ems-logo.svg
  res/img/feather-customised/explore.svg
  res/img/feather-customised/group.svg
  res/img/feather-customised/home.svg
  res/img/feather-customised/life-buoy.svg
  res/img/feather-customised/message-circle.svg
  res/img/feather-customised/settings.svg
  res/img/feather-customised/sign-in.svg
  res/img/feather-customised/sign-out.svg
  res/img/fileicon.png
  res/img/icon-context-mute-mentions.svg
  res/img/icon-context-mute-off-copy.svg
  res/img/icon-context-mute-off.svg
  res/img/icon-context-mute.svg
  res/img/icon_context_fave.svg
  res/img/icon_context_fave_on.svg
  res/img/icon_context_low.svg
  res/img/icon_context_low_on.svg
  res/img/icon_context_person.svg
  res/img/icon_context_person_on.svg
  res/img/icons-directory.svg
  res/img/icons-people.svg
  res/img/matrix-org-bw-logo.svg
  res/img/notif-active.svg
  res/img/notif-slider.svg
  res/img/search-icon-vector.svg
  res/img/tick.svg
Labels: T-Task

#7087 Change radio button border colour to match design
  res/css/views/elements/_StyledRadioButton.scss
Labels: T-Task

#7094 Color cleanup number 7
  res/css/structures/_AutoHideScrollbar.scss
  res/css/views/dialogs/_KeyboardShortcutsDialog.scss
  res/css/views/elements/_AccessibleButton.scss
  res/css/views/elements/_ResizeHandle.scss
  res/css/views/messages/_DateSeparator.scss
  res/css/views/messages/_ReactionsRowButton.scss
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_RoomPreviewBar.scss
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light-custom/css/_custom.scss
  res/themes/light-high-contrast/css/_light-high-contrast.scss
  res/themes/light/css/_light.scss
Labels: T-Task

#7102 Do not shift buttons in high contrast theme
  res/themes/light-high-contrast/css/_light-high-contrast.scss
Labels: T-Task

#7111 Use en_GB spelling of maximise / minimise in labels
  src/components/structures/LeftPanelWidget.tsx
  src/components/views/dialogs/HostSignupDialog.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#7044 Add PassphraseConfirmField component for registration and password recovery screens
  src/components/views/auth/PassphraseConfirmField.tsx
  src/components/views/auth/RegistrationForm.tsx
Labels: T-Task

#7100 Fixes following threads design implementation review
  res/css/structures/_ContextualMenu.scss
  res/css/structures/_RightPanel.scss
  res/css/views/right_panel/_BaseCard.scss
  res/css/views/right_panel/_ThreadPanel.scss
  res/css/views/rooms/_EventTile.scss
  res/img/element-icons/message/overflow-large.svg
  src/components/structures/RightPanel.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/structures/ThreadView.tsx
  src/components/views/context_menus/ThreadListContextMenu.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/right_panel/BaseCard.tsx
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#7077 Implement more meta-spaces
  res/css/_components.scss
  res/css/structures/_SpacePanel.scss
  res/css/views/dialogs/_UserSettingsDialog.scss
  res/css/views/settings/tabs/user/_SidebarUserSettingsTab.scss
  res/img/element-icons/settings/sidebar.svg
  src/@types/global.d.ts
  src/Avatar.ts
  src/autocomplete/Autocompleter.ts
  src/autocomplete/RoomProvider.tsx
  src/components/structures/LeftPanel.tsx
  src/components/structures/LoggedInView.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomSearch.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/SpaceHierarchy.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/structures/UserMenu.tsx
  src/components/views/dialogs/AddExistingToSpaceDialog.tsx
  src/components/views/dialogs/ConfirmSpaceUserActionDialog.tsx
  src/components/views/dialogs/CreateRoomDialog.tsx
  src/components/views/dialogs/CreateSpaceFromCommunityDialog.tsx
  src/components/views/dialogs/CreateSubspaceDialog.tsx
  src/components/views/dialogs/ForwardDialog.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/dialogs/LeaveSpaceDialog.tsx
  src/components/views/dialogs/ManageRestrictedJoinRuleDialog.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/rooms/NewRoomIntro.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomListNumResults.tsx
  src/components/views/rooms/ThirdPartyMemberInfo.tsx
  src/components/views/settings/JoinRuleSettings.tsx
  src/components/views/settings/tabs/user/SidebarUserSettingsTab.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  src/createRoom.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/BreadcrumbsStore.ts
  src/stores/room-list/RoomListStore.ts
  src/stores/room-list/SpaceWatcher.ts
  src/stores/room-list/algorithms/Algorithm.ts
  src/stores/room-list/filters/SpaceFilterCondition.ts
  src/stores/room-list/filters/VisibilityProvider.ts
  src/stores/spaces/SpaceStore.ts
  src/stores/spaces/SpaceTreeLevelLayoutStore.ts
  src/stores/spaces/index.ts
  src/utils/RoomUpgrade.ts
  test/stores/SpaceStore-test.ts
  test/stores/enable-metaspaces-labs.ts
  test/stores/room-list/SpaceWatcher-test.ts
Labels: T-Enhancement

#7115 Implement empty design list
  res/css/views/right_panel/_ThreadPanel.scss
  src/components/structures/ThreadPanel.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#7118 Catch up MPollBody CSS with everything else that now uses just 'accent'
  res/css/views/messages/_MPollBody.scss
Labels: T-Task

#7117 Fix hover tile border
  res/css/views/right_panel/_ThreadPanel.scss
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#7120 Expose power level control for m.space.child
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7119 Fix missing spaces in threads copy
  src/components/structures/ThreadPanel.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7121 Build for pull requests targeting any branch
  .github/workflows/layered-build.yaml
Labels: T-Task

#7123 Guard around SpaceStore onAccountData handler prevEvent
  src/stores/spaces/SpaceStore.ts
Labels: T-Defect

#7113 In forgot password screen, show validation errors inline in the form, instead of in modals
  src/components/structures/auth/ForgotPassword.tsx
  src/components/views/auth/PassphraseField.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7126 Fix thread panel filtering
  src/components/structures/ThreadPanel.tsx
Labels: T-Task

#7125 Attach composer IRelation to slash commands content
  src/components/views/rooms/SendMessageComposer.tsx
Labels: T-Task

#7124 Fix message load in Thread list
  src/components/views/rooms/EventTile.tsx
Labels: T-Task

#7129 Don't keep spinning if joining space child failed
  src/components/structures/SpaceHierarchy.tsx
  src/components/structures/SpaceRoomView.tsx
Labels: T-Defect

#7131 Fix appearance settings crash
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#7133 Fix look of emoji verification
  res/css/views/right_panel/_UserInfo.scss
  res/css/views/verification/_VerificationShowSas.scss
  src/components/views/verification/VerificationShowSas.tsx
Labels: T-Defect

#7130 Reorganize theme files
  res/themes/dark/css/_dark.scss
  res/themes/light/css/_light.scss
Labels: T-Task

#7072 Unified room context menus
  res/css/_components.scss
  res/css/views/context_menus/_IconizedContextMenu.scss
  res/css/views/right_panel/_BaseCard.scss
  res/css/views/rooms/_RoomHeader.scss
  res/css/views/rooms/_RoomTile.scss
  res/css/views/settings/tabs/room/_NotificationSettingsTab.scss
  res/img/element-icons/export.svg
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light-custom/css/_custom.scss
  res/themes/light/css/_light.scss
  src/accessibility/context_menu/ContextMenuTooltipButton.tsx
  src/components/structures/RoomView.tsx
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/dialogs/RoomSettingsDialog.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomTile.tsx
  src/components/views/settings/tabs/room/NotificationSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/stores/local-echo/RoomEchoChamber.ts
  test/components/views/rooms/RoomHeader-test.tsx
Labels: T-Enhancement

#7136 Fixes element not remembering widget hidden state per room
  src/components/structures/RoomView.tsx
Labels: T-Defect

#7048 Improve VoIP UI/UX
  res/css/views/voip/CallView/_CallViewButtons.scss
  res/css/views/voip/_CallView.scss
  res/css/views/voip/_CallViewSidebar.scss
  res/css/views/voip/_VideoFeed.scss
  res/img/voip/call-view/cam-off.svg
  res/img/voip/call-view/cam-on.svg
  res/img/voip/call-view/dialpad.svg
  res/img/voip/call-view/hangup.svg
  res/img/voip/call-view/mic-off.svg
  res/img/voip/call-view/mic-on.svg
  res/img/voip/call-view/more.svg
  res/img/voip/call-view/screensharing.svg
  res/img/voip/call-view/sidebar-off.svg
  res/img/voip/call-view/sidebar-on.svg
  res/img/voip/dialpad.svg
  res/img/voip/hangup.svg
  res/img/voip/mic-off.svg
  res/img/voip/mic-on.svg
  res/img/voip/more.svg
  res/img/voip/screensharing-off.svg
  res/img/voip/screensharing-on.svg
  res/img/voip/sidebar-off.svg
  res/img/voip/sidebar-on.svg
  res/img/voip/vid-off.svg
  res/img/voip/vid-on.svg
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light/css/_light.scss
  src/components/views/voip/CallView/CallViewButtons.tsx
  src/components/views/voip/VideoFeed.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7097 Add root folder to zip file created by export chat feature
  src/utils/exportUtils/Exporter.ts
Labels: T-Enhancement

#7132 Color cleanup number 10
  res/css/structures/_GroupView.scss
  res/css/structures/_HeaderButtons.scss
  res/css/structures/_RightPanel.scss
  res/css/structures/_TabbedView.scss
  res/css/views/messages/_CreateEvent.scss
  res/css/views/messages/_MJitsiWidgetEvent.scss
  res/css/views/messages/_common_CryptoEvent.scss
  res/css/views/right_panel/_BaseCard.scss
  res/css/views/right_panel/_UserInfo.scss
  res/css/views/rooms/_E2EIcon.scss
  res/css/views/rooms/_EntityTile.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_MemberInfo.scss
  res/css/views/rooms/_MessageComposer.scss
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light-custom/css/_custom.scss
  res/themes/light/css/_light.scss
Labels: T-Task

#7143 Fix js-sdk import
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
Labels: X-Release-Blocker, T-Task

#7086 Add rainfall effect
  src/effects/index.ts
  src/effects/rainfall/index.ts
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7098 Add maximise widget functionality
  res/css/_common.scss
  res/css/structures/_LeftPanelWidget.scss
  res/css/structures/_MainSplit.scss
  res/css/structures/_RightPanel.scss
  res/css/views/dialogs/_HostSignupDialog.scss
  res/css/views/elements/_ResizeHandle.scss
  res/css/views/messages/_ViewSourceEvent.scss
  res/css/views/right_panel/_RoomSummaryCard.scss
  res/css/views/right_panel/_WidgetCard.scss
  res/css/views/rooms/_AppsDrawer.scss
  res/css/views/rooms/_EventTile.scss
  res/img/element-icons/maximise-expand.svg
  res/img/element-icons/minimise-collapse.svg
  res/img/feather-customised/maximise.svg
  res/img/feather-customised/minimise.svg
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light/css/_light.scss
  src/components/structures/RoomView.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/AppsDrawer.tsx
  src/i18n/strings/en_EN.json
  src/stores/widgets/WidgetLayoutStore.ts
  test/stores/WidgetLayoutStore-test.ts
Labels: T-Enhancement

#7140 Fix timeline text when sharing room layout
  src/TextForEvent.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7145 Don't reload the page when user hits enter when entering ban reason
  src/components/views/dialogs/ConfirmUserActionDialog.tsx
Labels: T-Defect

#7146 Fix maximised / pinned widget state being loaded correctly
  src/components/structures/RoomView.tsx
Labels: T-Defect

#7122 Fix bulk invite button getting a negative count
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
Labels: T-Defect

#7134 Adjust recovery key button sizes depending on text width
  res/css/views/dialogs/security/_CreateSecretStorageDialog.scss
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
Labels: T-Defect

#7144 Cleanup `E2ePadlock` code
  res/css/views/rooms/_EventTile.scss
  src/components/views/rooms/EventTile.tsx
Labels: T-Task

#7150 Fix `$menu-bg-color`
  res/themes/light/css/_light.scss
Labels: X-Release-Blocker, T-Defect

#7152 Fix maximise icon size in the pinned apps drawer
  res/css/views/rooms/_AppsDrawer.scss
Labels: T-Task

#7142 Make double-clicking the PiP take you to the call room
  res/css/views/voip/_CallView.scss
  src/components/views/voip/CallPreview.tsx
  src/components/views/voip/CallView/CallViewHeader.tsx
  src/components/views/voip/PictureInPictureDragger.tsx
Labels: T-Enhancement

#7138 Chat Effects & Commands in thread context
  src/SlashCommands.tsx
  src/autocomplete/AutocompleteProvider.tsx
  src/autocomplete/Autocompleter.ts
  src/autocomplete/CommandProvider.tsx
  src/autocomplete/CommunityProvider.tsx
  src/autocomplete/EmojiProvider.tsx
  src/autocomplete/NotifProvider.tsx
  src/autocomplete/QueryMatcher.ts
  src/autocomplete/RoomProvider.tsx
  src/autocomplete/UserProvider.tsx
  src/components/structures/RoomView.tsx
  src/components/views/rooms/Autocomplete.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/effects/utils.ts
  src/stores/widgets/StopGapWidgetDriver.ts
Labels: T-Task

#7159 Fix an edge case when trying to join an upgraded room
  src/components/views/rooms/MessageComposer.tsx
Labels: T-Defect

#7127 Hide MFileBody download link for threaded messages
  src/components/views/messages/MImageBody.tsx
Labels: T-Task

#7154 Room Context Menu should respond to tag changes
  src/components/views/context_menus/RoomContextMenu.tsx
Labels: T-Defect

#7160 Prevent custom power levels from breaking roles & permissions tab
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
Labels: T-Defect

#7153 Show space members when not invited even if summary didn't fail
  src/components/structures/SpaceRoomView.tsx
Labels: T-Defect

#7161 Disable op/deop commands where user has no permissions
  src/SlashCommands.tsx
Labels: T-Enhancement

#7137 Remove chevrons from RoomSummaryCard_Button
  res/css/views/right_panel/_BaseCard.scss
  res/css/views/right_panel/_RoomSummaryCard.scss
Labels: T-Enhancement

#7165 When we only show one compose button, show upload
  src/components/views/rooms/MessageComposer.tsx
Labels: T-Task

#7166 Limit the length of poll questions and answers to 340 characters
  src/components/views/elements/PollCreateDialog.tsx
Labels: T-Task

#7164 Make the Add option button look disabled when it is
  res/css/views/dialogs/_PollCreateDialog.scss
Labels: T-Task

#7167 Fix automatic composer focus, regressed by threads work
  src/components/structures/LoggedInView.tsx
  src/components/views/emojipicker/ReactionPicker.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/dispatcher/actions.ts
  src/dispatcher/payloads/FocusComposerPayload.ts
Labels: T-Defect

#7168 Iterate type definitions
  src/RoomNotifs.ts
  src/components/views/dialogs/IncomingSasDialog.tsx
Labels: T-Task

#7178 Iterate type definitions
  src/RoomNotifs.ts
  src/components/views/dialogs/IncomingSasDialog.tsx
Labels: T-Task

#7181 Fix composer focus after pasting
  src/components/structures/LoggedInView.tsx
  src/components/views/messages/MessageActionBar.tsx
Labels: T-Task

#7182 Disallow KeyVerificationRequest as thread root
  src/Notifier.ts
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/rooms/EventTile.tsx
Labels: T-Task

#7175 Remove leading slash from /addwidget Jitsi confs
  src/widgets/Jitsi.ts
Labels: T-Defect

#7183 Chat effects fixes for threads
  src/SlashCommands.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/stores/widgets/StopGapWidgetDriver.ts
Labels: T-Task

#7180 Disable typing notifications for threads
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/stores/TypingStore.ts
Labels: T-Task

#7162 Show room context details in forward dialog
  res/css/views/dialogs/_ForwardDialog.scss
  src/Rooms.ts
  src/components/views/dialogs/ForwardDialog.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7158 Display and send votes in polls
  res/css/views/messages/_MPollBody.scss
  src/components/views/messages/IBodyProps.ts
  src/components/views/messages/MPollBody.tsx
  src/components/views/messages/MessageEvent.tsx
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
  src/polls/consts.ts
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/messages/__snapshots__/MPollBody-test.tsx.snap
Labels: T-Task

#7187 Prevent text overlapping on poll options
  res/css/views/messages/_MPollBody.scss
  src/components/views/messages/MPollBody.tsx
  test/components/views/messages/__snapshots__/MPollBody-test.tsx.snap
Labels: T-Task

#7189 Show a spinner while waiting for a poll to be created
  res/css/views/dialogs/_PollCreateDialog.scss
  src/components/views/elements/PollCreateDialog.tsx
Labels: T-Task

#7184 Fix a couple relative date tests
  test/utils/DateUtils-test.ts
Labels: T-Task

#7191 Prevent programmatic scrolling within truncated room sublists
  res/css/views/rooms/_RoomSublist.scss
Labels: T-Defect

#7193 Basic tests for PollCreateDialog
  src/components/views/elements/PollCreateDialog.tsx
  test/components/views/elements/PollCreateDialog-test.tsx
  test/components/views/elements/__snapshots__/PollCreateDialog-test.tsx.snap
Labels: T-Task

#7194 Test for showing a spinner after submitting a new poll
  test/components/views/elements/PollCreateDialog-test.tsx
  test/components/views/elements/__snapshots__/PollCreateDialog-test.tsx.snap
Labels: T-Task

#7197 Fix wrongly showing unpin in pinned messages tile with no perms
  src/components/views/right_panel/PinnedMessagesCard.tsx
Labels: T-Defect

#7190 Group Labs flags
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/SettingsStore.ts
Labels: T-Enhancement

#7201 Show an error dialog if poll creation or voting fails
  src/components/views/elements/PollCreateDialog.tsx
  src/components/views/messages/MPollBody.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#7163 Maximised widgets always force a call to be shown in PIP mode
  src/CallHandler.tsx
  src/components/views/voip/CallPreview.tsx
Labels: T-Enhancement

#7202 Highlight my vote even if it was made on another device
  src/components/views/messages/MPollBody.tsx
  test/components/views/messages/MPollBody-test.tsx
Labels: T-Task

#7199 Add basic linkify-matrix tests
  test/linkify-matrix-test.ts
Labels: T-Task

#7207 re-enable Spaces e2e tests
  test/end-to-end-tests/src/scenario.js
Labels: T-Task

#7196 Spaces quick settings
  res/css/_components.scss
  res/css/structures/_QuickSettingsButton.scss
  res/css/structures/_SpacePanel.scss
  src/components/views/elements/Dropdown.tsx
  src/components/views/settings/ThemeChoicePanel.tsx
  src/components/views/settings/tabs/user/SidebarUserSettingsTab.tsx
  src/components/views/spaces/QuickSettingsButton.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/i18n/strings/en_EN.json
  src/theme.ts
Labels: T-Enhancement

#7208 Fix Manage Restricted Join Rule Dialog for Spaces
  src/components/views/dialogs/ManageRestrictedJoinRuleDialog.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7210 Fix multiline paragraph rendering as single line
  src/Markdown.ts
Labels: T-Defect

#7204 Improve right panel resize handle usability
  res/css/structures/_MainSplit.scss
  src/components/structures/MainSplit.tsx
Labels: T-Enhancement

#7209 Polish threads misalignments and UI diversion
  res/css/views/rooms/_EventTile.scss
  src/components/structures/TimelinePanel.tsx
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#7215 Hide server options hint when disable_custom_urls is true
  src/components/views/elements/ServerPicker.tsx
Labels: T-Enhancement

#7214 Fix RoomUpgradeWarningBar exploding
  src/components/views/rooms/RoomUpgradeWarningBar.tsx
Labels: T-Defect

#7216 Respect the home page as a context for the Home space
  src/stores/spaces/SpaceStore.ts
Labels: T-Defect

#7211 Task/colors 11
  res/css/_common.scss
  res/css/structures/_GroupView.scss
  res/css/structures/_LeftPanel.scss
  res/css/structures/_RoomSearch.scss
  res/css/structures/_RoomView.scss
  res/css/structures/_SpacePanel.scss
  res/css/views/context_menus/_StatusMessageContextMenu.scss
  res/css/views/dialogs/_ExportDialog.scss
  res/css/views/elements/_Dropdown.scss
  res/css/views/elements/_Field.scss
  res/css/views/elements/_RichText.scss
  res/css/views/elements/_RoomAliasField.scss
  res/css/views/messages/_MessageActionBar.scss
  res/css/views/right_panel/_PinnedMessagesCard.scss
  res/css/views/rooms/_LinkPreviewWidget.scss
  res/css/views/rooms/_MemberList.scss
  res/css/views/rooms/_MessageComposer.scss
  res/css/views/rooms/_MessageComposerFormatBar.scss
  res/css/views/rooms/_RoomList.scss
  res/css/views/rooms/_RoomSublist.scss
  res/css/views/rooms/_RoomUpgradeWarningBar.scss
  res/css/views/spaces/_SpaceCreateMenu.scss
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light-custom/css/_custom.scss
  res/themes/light-high-contrast/css/_light-high-contrast.scss
  res/themes/light/css/_light.scss
Labels: T-Task

#7188 Fix size of portrait images with the SIZE_NORMAL setting.
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MVideoBody.tsx
  src/settings/enums/ImageSize.ts
Labels: T-Task

#7112 Add right panel chat timeline
  res/css/_components.scss
  res/css/structures/_RightPanel.scss
  res/css/views/right_panel/_TimelineCard.scss
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/context_menus/ThreadListContextMenu.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/components/views/right_panel/TimelineCard.tsx
  src/i18n/strings/en_EN.json
  src/stores/RightPanelStorePhases.ts
Labels: T-Enhancement

#7222 Prevent duplicate avatars in Event List Summaries
  src/components/views/elements/EventListSummary.tsx
Labels: T-Defect

#7224 Improve room list message previews
  src/stores/room-list/previews/MessageEventPreview.ts
Labels: T-Defect

#7219 Allow filtering room list during treeview navigation
  src/accessibility/RovingTabIndex.tsx
  src/components/structures/LeftPanel.tsx
  src/components/structures/RoomSearch.tsx
  test/accessibility/RovingTabIndex-test.tsx
Labels: T-Enhancement

#7217 Improve ThreadPanel ctx menu accessibility
  res/css/structures/_ContextualMenu.scss
  res/css/views/right_panel/_ThreadPanel.scss
  src/components/structures/ContextMenu.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/views/avatars/MemberStatusMessageAvatar.tsx
  src/components/views/context_menus/CallContextMenu.tsx
  src/components/views/context_menus/DialpadContextMenu.tsx
  src/components/views/context_menus/IconizedContextMenu.tsx
  src/components/views/directory/NetworkDropdown.tsx
  src/components/views/elements/DNDTagTile.js
  src/components/views/groups/GroupInviteTile.js
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/messages/ReactionsRow.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/RoomSublist.tsx
  src/components/views/rooms/Stickerpicker.tsx
  src/components/views/spaces/QuickSettingsButton.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
  test/components/structures/ThreadPanel-test.tsx
  test/components/structures/__snapshots__/ThreadPanel-test.tsx.snap
Labels: T-Enhancement

#7114 Only show core navigation elements (call/chat/notification/info) when a widget is maximised
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadView.tsx
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/components/views/rooms/RoomHeader.tsx
Labels: T-Enhancement

#7213 Tweak bottom of space panel buttons in expanded state
  res/css/structures/_QuickSettingsButton.scss
  res/css/structures/_SpacePanel.scss
  src/components/views/spaces/QuickSettingsButton.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7156 Add unread indicator to the timelineCard header icon
  res/css/structures/_RightPanel.scss
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/components/views/rooms/RoomHeader.tsx
Labels: T-Enhancement

#7227 Fix newline on edit messages with quotes
  src/Markdown.ts
Labels: T-Defect

#7231 Fix room list treeview filtering not ignoring modifier keys
  src/components/structures/LeftPanel.tsx
Labels: X-Release-Blocker, T-Task

#7236 Fix left panel glow in Safari
  res/css/views/elements/_ResizeHandle.scss
Labels: T-Defect

#7238 Upgrade allchange to 1.0.6
  package.json
  yarn.lock
Labels: T-Task

#7052 Tweaks to informational architecture 1.1
  res/css/_common.scss
  res/css/_components.scss
  res/css/structures/_LeftPanel.scss
  res/css/structures/_RoomSearch.scss
  res/css/structures/_SpacePanel.scss
  res/css/structures/_ToastContainer.scss
  res/css/structures/_UserMenu.scss
  res/css/views/avatars/_MemberStatusMessageAvatar.scss
  res/css/views/context_menus/_IconizedContextMenu.scss
  res/css/views/context_menus/_StatusMessageContextMenu.scss
  res/css/views/dialogs/_FeedbackDialog.scss
  res/css/views/rooms/_MessageComposer.scss
  res/css/views/rooms/_RoomBreadcrumbs.scss
  res/css/views/rooms/_RoomList.scss
  res/css/views/rooms/_RoomListHeader.scss
  res/img/element-icons/flask.svg
  res/img/element-icons/roomlist/dnd-avatar-mask.svg
  res/img/element-icons/roomlist/dnd-cross.svg
  res/img/element-icons/roomlist/dnd.svg
  res/img/element-icons/roomlist/feedback.svg
  res/img/element-icons/roomlist/hash-plus.svg
  res/img/element-icons/roomlist/hash-search.svg
  res/img/element-icons/roomlist/hash.svg
  res/img/element-icons/roomlist/member-plus.svg
  res/img/element-icons/roomlist/search-clear.svg
  res/img/ia-design-changes.png
  src/components/structures/LeftPanel.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomSearch.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/structures/UserMenu.tsx
  src/components/views/avatars/MemberStatusMessageAvatar.tsx
  src/components/views/context_menus/IconizedContextMenu.tsx
  src/components/views/context_menus/SpaceContextMenu.tsx
  src/components/views/context_menus/StatusMessageContextMenu.tsx
  src/components/views/dialogs/FeedbackDialog.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomListHeader.tsx
  src/components/views/rooms/RoomListNumResults.tsx
  src/components/views/rooms/RoomSublist.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/i18n/strings/en_EN.json
  src/rageshake/submit-rageshake.ts
  src/settings/Settings.tsx
  src/stores/spaces/index.ts
  src/utils/space.tsx
  test/end-to-end-tests/src/scenarios/toast.js
  test/end-to-end-tests/src/usecases/create-space.js
Labels: X-Blocked, T-Enhancement

#7200 Fix links being parsed as markdown links improperly
  src/Markdown.ts
  test/Markdown-test.ts
  test/editor/deserialize-test.js
Labels: T-Defect

#6704 Make `CallHandler` more `EventEmitter`y
  src/CallHandler.tsx
  src/Lifecycle.ts
  src/SlashCommands.tsx
  src/VoipUserMapper.ts
  src/components/structures/CallEventGrouper.ts
  src/components/structures/LeftPanel.tsx
  src/components/structures/LoggedInView.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomView.tsx
  src/components/views/context_menus/CallContextMenu.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/voip/CallPreview.tsx
  src/components/views/voip/CallView.tsx
  src/components/views/voip/CallViewForRoom.tsx
  src/components/views/voip/DialPadModal.tsx
  src/dispatcher/actions.ts
  src/dispatcher/payloads/DialNumberPayload.ts
  src/dispatcher/payloads/TransferCallPayload.ts
  src/stores/room-list/filters/VisibilityProvider.ts
  src/toasts/IncomingCallToast.tsx
  test/CallHandler-test.ts
Labels: X-Blocked, T-Task
