Repository matrix-org/matrix-react-sdk, pull requests merged in 2021-08, with the labels that each got.

#6521 Fix symbol entry in the in-call dialpad
  res/css/views/voip/_DialPadContextMenu.scss
Labels: T-Defect

#6526 Fix broken call notification regression
  src/TextForEvent.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#6486 Show an avatar/a turned off microphone icon for muted users
  res/css/views/voip/_CallView.scss
  res/css/views/voip/_CallViewSidebar.scss
  res/css/views/voip/_VideoFeed.scss
  res/img/voip/mic-muted.svg
  res/img/voip/mic-unmuted.svg
  src/components/views/voip/VideoFeed.tsx
Labels: T-Enhancement

#6536 Update eslint plugin & fix silly indenting
  package.json
  src/IdentityAuthClient.js
  src/accessibility/KeyboardShortcuts.tsx
  src/components/views/dialogs/DevtoolsDialog.tsx
  src/components/views/dialogs/KeySignatureUploadFailedDialog.js
  src/components/views/right_panel/PinnedMessagesCard.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/NewRoomIntro.tsx
  src/components/views/rooms/ReadReceiptMarker.js
  test/components/views/elements/MemberEventListSummary-test.js
  test/notifications/ContentRules-test.js
  test/test-utils.js
  test/utils/ShieldUtils-test.js
  yarn.lock
Labels: T-Task

#6537 Switch to new changelog generator
  package.json
  release_config.yaml
  yarn.lock
Labels: T-Task

#6541 Fix indent in HTMLUtils
  src/HtmlUtils.tsx
Labels: T-Task

#6226 Re-pin Jitsi if the widget already exists
  src/CallHandler.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#6546 Add CODEOWNERS
  .github/CODEOWNERS
Labels: T-Task

#6545 Improve call event tile wording
  src/components/views/messages/CallEvent.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#6551 Fix wrong cursor being used in PiP
  res/css/views/voip/_CallContainer.scss
  res/css/views/voip/_CallView.scss
Labels: T-Defect

#6553 Fix worklet reference for new webpack pipeline
  package.json
  src/audio/VoiceRecording.ts
Labels: Sponsored, T-Task

#5510 Add surround with feature
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Enhancement

#6558 Null guard space inviter to prevent the app exploding
  src/components/structures/SpaceRoomView.tsx
Labels: T-Defect

#6538 Polish up more of the voice messages UI
  res/css/views/rooms/_VoiceRecordComposerTile.scss
  src/audio/Playback.ts
  src/components/views/audio_messages/LiveRecordingWaveform.tsx
  src/components/views/rooms/VoiceRecordComposerTile.tsx
  src/i18n/strings/en_EN.json
Labels: Sponsored, T-Task, X-Release-Blocker

#6530 Improve voice messages uploading state
  res/css/views/rooms/_VoiceRecordComposerTile.scss
  src/components/views/rooms/VoiceRecordComposerTile.tsx
  src/i18n/strings/en_EN.json
Labels: Sponsored, T-Enhancement, X-Release-Blocker

#6552 Fix in-call context menus when in PiP mode
  src/components/views/voip/CallView.tsx
Labels: T-Defect

#6561 Properly set style attribute on shared usercontent iframe
  src/utils/FileDownloader.ts
Labels: X-Release-Blocker, Sponsored, T-Defect

#6563 Stop voice messages that are playing when starting a recording
  src/components/views/rooms/VoiceRecordComposerTile.tsx
Labels: X-Release-Blocker, Sponsored, T-Defect

#6498 Fix sizing issues of the screen picker
  res/css/views/elements/_DesktopCapturerSourcePicker.scss
Labels: X-Release-Blocker, T-Defect

#6549 Use `flex-start` instead of `start`
  res/css/views/auth/_InteractiveAuthEntryComponents.scss
  res/css/views/rooms/_EventBubbleTile.scss
Labels: T-Task

#6550 Fix voice feed being cut-off
  res/css/views/voip/_CallView.scss
  res/css/views/voip/_CallViewSidebar.scss
  res/css/views/voip/_VideoFeed.scss
Labels: X-Release-Blocker, T-Defect

#6227 Make version copiable
  res/css/views/settings/tabs/user/_HelpUserSettingsTab.scss
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#6562 Fix disabled state for voice messages + send button tooltip
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/i18n/strings/en_EN.json
Labels: X-Release-Blocker, Sponsored, T-Defect

#6571 Fix clicking whitespaces on replies
  src/components/views/rooms/ReplyTile.tsx
Labels: T-Defect

#6567 Don't flash "Missed call" when accepting a call
  src/components/structures/CallEventGrouper.ts
Labels: T-Defect

#6568 allow customizing the bubble layout colors
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/light-custom/css/_custom.scss
Labels: T-Defect

#6566 Move LayoutSwitcher into a separate component
  res/css/_components.scss
  res/css/views/settings/_LayoutSwitcher.scss
  res/css/views/settings/tabs/user/_AppearanceUserSettingsTab.scss
  src/components/views/settings/LayoutSwitcher.tsx
  src/components/views/settings/tabs/user/AppearanceUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#6349 Group pinned message events with MELS
  src/components/structures/MessagePanel.tsx
  src/components/views/elements/EventListSummary.tsx
  src/components/views/elements/MemberEventListSummary.tsx
  src/i18n/strings/en_EN.json
  src/utils/FormattingUtils.ts
  src/utils/ReactUtils.tsx
Labels: T-Enhancement

#6390 Support for MSC2285 (hidden read receipts)
  src/components/structures/TimelinePanel.tsx
  src/components/views/settings/tabs/user/LabsUserSettingsTab.js
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Enhancement

#6565 Fix missing expand button on codeblocks
  src/components/views/messages/TextualBody.tsx
Labels: T-Defect

#6475 Refactor Calls components into smaller pieces for future Widgets work
  res/css/_components.scss
  res/css/views/voip/_CallView.scss
  res/css/views/voip/_CallViewHeader.scss
  src/components/views/voip/CallPreview.tsx
  src/components/views/voip/CallView.tsx
  src/components/views/voip/CallView/CallViewHeader.tsx
  src/components/views/voip/PictureInPictureDragger.tsx
Labels: T-Task

#6577 Fix Call View regressions
  res/css/_components.scss
  src/components/views/voip/CallView/CallViewHeader.tsx
  src/components/views/voip/PictureInPictureDragger.tsx
Labels: X-Release-Blocker, T-Task

#6579 Fix source picker sizing issues (again)
  res/css/views/elements/_DesktopCapturerSourcePicker.scss
Labels: X-Release-Blocker, T-Task

#6576 Export components by default
  src/components/views/voip/CallPreview.tsx
  src/components/views/voip/CallView.tsx
  src/components/views/voip/CallView/CallViewHeader.tsx
  src/components/views/voip/PictureInPictureDragger.tsx
Labels: T-Task

#6572 Move stop button to the left of the waveform
  res/css/views/rooms/_VoiceRecordComposerTile.scss
  src/components/views/rooms/VoiceRecordComposerTile.tsx
Labels: X-Release-Blocker, Sponsored, T-Task

#6581 Fade Call View Buttons after `componentDidMount`
  src/components/views/voip/CallView.tsx
Labels: T-Defect

#6580 Don't show a modal on call reject/user hangup
  src/CallHandler.tsx
Labels: T-Defect

#6574 Add changelog preview action
  .github/workflows/preview_changelog.yaml
Labels: T-Task

#6587 Fix create room dialog in spaces no longer adding to the space
  src/components/views/dialogs/CreateRoomDialog.tsx
Labels: T-Defect

#6586 Do the PR comment a different way
  .github/workflows/netflify.yaml
Labels: T-Task

#6589 Upscale thumbnails to the container size
  src/components/views/messages/MImageBody.tsx
Labels: T-Defect

#6353 Improve handling of pills in the composer
  res/css/views/rooms/_BasicMessageComposer.scss
  src/ActiveRoomObserver.ts
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/editor/autocomplete.ts
  src/editor/caret.ts
  src/editor/deserialize.ts
  src/editor/diff.ts
  src/editor/history.ts
  src/editor/offset.ts
  src/editor/operations.ts
  src/editor/parts.ts
  src/editor/position.ts
  src/editor/range.ts
  src/editor/render.ts
  src/editor/serialize.ts
Labels: X-Blocked, T-Defect

#6540 First cleanup of the theme files
  res/themes/dark/css/_dark.scss
  res/themes/light/css/_light.scss
Labels: X-Blocked, T-Task

#6578 Move Call View Buttons into a separate component
  res/css/_components.scss
  res/css/views/voip/CallView/_CallViewButtons.scss
  res/css/views/voip/_CallView.scss
  src/components/views/voip/CallView.tsx
  src/components/views/voip/CallView/CallViewButtons.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#6598 Don't call `showControls()` which was moved
  src/components/views/voip/CallView.tsx
Labels: T-Defect

#6596 Remove tiny scrollbar dot from code blocks
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#6599 Fix Netflify builds from fork PRs
  .github/workflows/layered-build.yaml
  .github/workflows/netflify.yaml
Labels: T-Task

#6600 Edit PR Description instead of commenting
  .github/workflows/netflify.yaml
Labels: T-Task

#6569 Accessibility improvements in and around Spaces
  res/css/structures/_SpaceRoomDirectory.scss
  src/accessibility/RovingTabIndex.tsx
  src/components/structures/AutoHideScrollbar.tsx
  src/components/structures/LeftPanel.tsx
  src/components/structures/SpaceRoomDirectory.tsx
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/elements/Dropdown.tsx
  src/components/views/spaces/SpaceBasicSettings.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#6603 Remove unnecessary composer code
  src/components/views/rooms/BasicMessageComposer.tsx
Labels: T-Defect

#6543 Offer a way to create a space based on existing community
  res/css/_components.scss
  res/css/structures/_GroupView.scss
  res/css/structures/_SpaceRoomView.scss
  res/css/views/context_menus/_TagTileContextMenu.scss
  res/css/views/dialogs/_CreateSpaceFromCommunityDialog.scss
  res/css/views/elements/_Field.scss
  res/css/views/settings/tabs/_SettingsTab.scss
  res/css/views/settings/tabs/user/_PreferencesUserSettingsTab.scss
  res/css/views/spaces/_SpaceCreateMenu.scss
  src/components/structures/GroupView.js
  src/components/structures/SpaceRoomView.tsx
  src/components/views/context_menus/TagTileContextMenu.js
  src/components/views/dialogs/CreateSpaceFromCommunityDialog.tsx
  src/components/views/dialogs/CreateSubspaceDialog.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
  src/i18n/strings/en_EN.json
  src/stores/GroupFilterOrderStore.js
  src/stores/GroupStore.js
  src/utils/space.tsx
Labels: T-Enhancement

#6590 Make loading encrypted images look snappier
  res/css/_animations.scss
  res/css/_common.scss
  res/css/views/messages/_MImageBody.scss
  src/components/views/messages/MImageBody.tsx
Labels: T-Enhancement

#6601 Use changelog generator from npm
  package.json
  yarn.lock
Labels: T-Task

#6607 [Release] Fix toast colors
  res/css/structures/_ToastContainer.scss
  res/css/views/voip/_CallView.scss
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light/css/_light.scss
Labels: X-Release-Blocker, T-Defect

#6593 Use the correct button component for the Call View sidebar button
  src/components/views/voip/CallView/CallViewButtons.tsx
Labels: X-Release-Blocker, T-Defect

#6602 [Release] Use the correct button component for the Call View sidebar button
  src/components/views/voip/CallView.tsx
Labels: X-Release-Blocker, T-Defect

#6606 Fix toast colors
  res/css/structures/_ToastContainer.scss
  res/css/views/voip/_CallView.scss
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light/css/_light.scss
Labels: X-Release-Blocker, T-Defect

#6520 Keep number field in focus when pressing dialpad buttons
  src/components/views/context_menus/DialpadContextMenu.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/elements/DialPadBackspaceButton.tsx
  src/components/views/voip/DialPad.tsx
  src/components/views/voip/DialPadModal.tsx
Labels: T-Enhancement

#6609 Left align call tiles
  res/css/views/messages/_CallEvent.scss
  src/components/views/rooms/EventTile.tsx
  src/utils/EventUtils.ts
Labels: T-Enhancement

#6610 Add new call tile states
  res/css/views/messages/_CallEvent.scss
  res/img/voip/declined-video.svg
  res/img/voip/declined-voice.svg
  src/components/views/messages/CallEvent.tsx
  src/i18n/strings/en_EN.json
Labels: X-Blocked, T-Enhancement

#5659 Rework composer autocomplete to be smarter and not trap tab
  src/KeyBindingsDefaults.ts
  src/KeyBindingsManager.ts
  src/autocomplete/AutocompleteProvider.tsx
  src/autocomplete/CommandProvider.tsx
  src/autocomplete/CommunityProvider.tsx
  src/autocomplete/DuckDuckGoProvider.tsx
  src/autocomplete/EmojiProvider.tsx
  src/autocomplete/NotifProvider.tsx
  src/autocomplete/RoomProvider.tsx
  src/autocomplete/UserProvider.tsx
  src/components/structures/LoggedInView.tsx
  src/components/views/rooms/Autocomplete.tsx
  src/components/views/rooms/BasicMessageComposer.tsx
  src/editor/autocomplete.ts
  src/editor/model.ts
Labels: T-Enhancement

#6323 Convert SearchResult, InteractiveAuth, PushProcessor and Scheduler to TS
  src/CallHandler.tsx
  src/components/structures/InteractiveAuth.js
  src/components/structures/InteractiveAuth.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/dialogs/DeactivateAccountDialog.tsx
  src/settings/controllers/NotificationControllers.ts
Labels: T-Task

#6611 Fix PiP of held calls
  res/css/views/voip/_CallView.scss
Labels: T-Defect

#6612 [Release] Fix PiP of held calls
  res/css/views/voip/_CallView.scss
Labels: X-Release-Blocker, T-Defect

#6613 Convert CrossSigningPanel to TS
  src/components/views/settings/CrossSigningPanel.tsx
Labels: T-Task

#6617 Fix long display names in call toasts
  res/css/views/toasts/_IncomingCallToast.scss
Labels: T-Defect

#6614 Fix glare related regressions
  src/components/views/voip/CallView.tsx
Labels: X-Release-Blocker, T-Defect

#6622 [Release] Fix glare related regressions
  src/components/views/voip/CallView.tsx
Labels: X-Release-Blocker, T-Defect

#6623 Update changelog generator
  package.json
  yarn.lock
Labels: T-Task

#6615 Properly handle media errors
  src/components/views/voip/AudioFeed.tsx
  src/components/views/voip/VideoFeed.tsx
Labels: T-Defect

#6616 Avoid access token overflow
  res/css/views/settings/tabs/user/_HelpUserSettingsTab.scss
Labels: T-Defect

#6618 Fix long display names in call tiles
  res/css/views/messages/_CallEvent.scss
  src/components/views/messages/CallEvent.tsx
Labels: T-Defect

#6621 Fix vertical call tile spacing issues
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#6624 Fix call tile buttons
  res/css/views/messages/_CallEvent.scss
Labels: T-Defect

#6631 Fix name of Netlify workflow
  .github/workflows/netlify.yaml
Labels: T-Task

#6630 Fix FilePanel pagination in E2EE rooms
  src/indexing/EventIndex.ts
Labels: T-Defect

#6597 Sentry rageshakes
  package.json
  src/components/structures/MatrixChat.tsx
  src/components/views/dialogs/BugReportDialog.tsx
  src/components/views/elements/ErrorBoundary.tsx
  src/components/views/messages/TileErrorBoundary.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/sentry.ts
  yarn.lock
Labels: T-Enhancement

#6627 Properly fix VoIP issues
  src/CallHandler.tsx
  src/components/structures/LoggedInView.tsx
  src/components/views/voip/AudioFeedArrayForCall.tsx
Labels: T-Task

#6635 Migrate PasswordReset.js to typescript
  src/PasswordReset.ts
Labels: T-Task

#6632 Fix jitsi widget sometimes being permanently stuck in the bottom-right corner
  src/components/views/elements/AppTile.js
Labels: T-Defect

#6638 Add missing types
  src/PasswordReset.ts
Labels: T-Task

#6645 Fix backdrop panel empty image
  src/components/structures/BackdropPanel.tsx
Labels: T-Task

#6640 Remember last `MemberList` search query per-room
  src/components/views/rooms/MemberList.tsx
Labels: T-Enhancement

#6626 Adjust colors in call tiles
  res/css/views/messages/_CallEvent.scss
Labels: T-Enhancement

#6647 Fix call tiles on the bubble layout
  res/css/views/rooms/_EventBubbleTile.scss
  src/components/views/rooms/EventTile.tsx
  src/utils/EventUtils.ts
Labels: T-Defect

#6641 Fix flex values after blur changes
  res/css/structures/_LeftPanel.scss
  res/css/structures/_MatrixChat.scss
  src/components/structures/LoggedInView.tsx
Labels: X-Release-Blocker, T-Task

#6620 Format autocomplete suggestions vertically
  res/css/views/rooms/_Autocomplete.scss
Labels: T-Enhancement

#6652 Fix space room view invalid css
  res/css/structures/_RoomView.scss
  src/components/structures/LoggedInView.tsx
Labels: T-Task

#6653 Fix content not being centered
  res/css/structures/_RoomView.scss
Labels: T-Task

#6651 Watch `RoomList.backgroundImage`
  src/components/structures/LoggedInView.tsx
Labels: T-Task

#6656 Move `CallPreview` CSS
  res/css/views/voip/_CallContainer.scss
  res/css/views/voip/_CallPreview.scss
Labels: T-Task

#6648 Fix modern layout
  src/components/structures/LoggedInView.tsx
Labels: T-Task

#6646 Show "Enable encryption in settings" only when the user can do that
  src/components/views/rooms/NewRoomIntro.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#6633 Fix cross signing setup from settings screen
  src/components/views/settings/CrossSigningPanel.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#6655 Fix autocomplete scrollbar and make the autocomplete a little smaller
  res/css/views/rooms/_Autocomplete.scss
Labels: X-Release-Blocker, T-Defect

#6650 Improve emoji in composer
  src/autocomplete/EmojiProvider.tsx
Labels: X-Release-Blocker, T-Enhancement

#6451 Fix replies on the bubble layout
  res/css/views/rooms/_EventBubbleTile.scss
Labels: T-Defect

#6629 Allow playback of replied-to voice message
  src/components/views/messages/MVoiceOrAudioBody.tsx
  src/components/views/rooms/ReplyTile.tsx
  src/utils/EventUtils.ts
Labels: T-Enhancement

#6657 Send the user to `/choose` to let them choose an issue type
  src/components/views/dialogs/BugReportDialog.tsx
  src/components/views/dialogs/FeedbackDialog.js
  src/components/views/elements/ErrorBoundary.tsx
Labels: T-Task

#6659 Optimize background image from avatar on left panel
  package.json
  res/css/structures/_BackdropPanel.scss
  res/css/structures/_GroupFilterPanel.scss
  res/css/structures/_LeftPanel.scss
  res/css/structures/_SpacePanel.scss
  res/themes/dark/css/_dark.scss
  res/themes/light/css/_light.scss
  src/components/structures/BackdropPanel.tsx
  src/components/structures/LeftPanel.tsx
  src/components/structures/LoggedInView.tsx
  src/resizer/resizer.ts
  src/stores/OwnProfileStore.ts
  yarn.lock
Labels: T-Task

#6507 Allow pagination of the space hierarchy and use new APIs
  res/css/_components.scss
  res/css/structures/_SpaceHierarchy.scss
  res/css/structures/_SpaceRoomView.scss
  src/components/structures/RoomDirectory.tsx
  src/components/structures/SpaceHierarchy.tsx
  src/components/structures/SpaceRoomDirectory.tsx
  src/components/structures/SpaceRoomView.tsx
  src/i18n/strings/en_EN.json
  src/stores/SpaceStore.tsx
  test/test-utils.js
Labels: T-Enhancement

#5698 Add a warning on E2EE rooms if you try to make them public
  res/css/_common.scss
  src/components/views/dialogs/CreateRoomDialog.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#6663 Honour user-selected background image from settings
  src/components/structures/LoggedInView.tsx
Labels: X-Release-Blocker, T-Task

#6661 Ensure blurhash is treated as optional
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MStickerBody.tsx
Labels: X-Release-Blocker, T-Defect

#6669 Fix remaining scrollbar/background blur regressions
  res/css/structures/_LeftPanel.scss
  src/resizer/resizer.ts
Labels: T-Task

#6665 Add padding to the Add button in the notification settings
  res/css/views/elements/_TagComposer.scss
Labels: T-Defect

#6670 Fix resizer for detaching
  src/resizer/resizer.ts
Labels: T-Task

#6671 Fix import breaking types in release mode
  src/sentry.ts
Labels: T-Task

#6383 Add CI script to switch the js-sdk into 'release mode'
  scripts/ci/js-sdk-to-release.sh
Labels: T-Task

#6644 Increase general app performance by optimizing layers
  res/css/structures/_BackdropPanel.scss
  res/css/structures/_LeftPanel.scss
  res/css/structures/_RoomView.scss
  res/css/structures/_ScrollPanel.scss
Labels: X-Release-Blocker, T-Enhancement

#6673 Remove advanced room logging setting
  src/components/views/rooms/RoomList.tsx
  src/components/views/settings/tabs/user/LabsUserSettingsTab.js
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/room-list/RoomListStore.ts
  src/stores/room-list/algorithms/Algorithm.ts
Labels: T-Task

#6662 Flag a couple features as having dependencies
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Task

#6639 Add active speaker indicators
  res/css/views/voip/_CallView.scss
  res/css/views/voip/_CallViewSidebar.scss
  res/css/views/voip/_VideoFeed.scss
  src/components/views/voip/VideoFeed.tsx
Labels: T-Enhancement

#6708 Filter members on `MemberList` load
  src/components/views/rooms/MemberList.tsx
Labels: T-Defect

#6712 Remove non-functional DuckDuckGo Autocomplete Provider
  src/SlashCommands.tsx
  src/autocomplete/Autocompleter.ts
  src/autocomplete/CommandProvider.tsx
  src/autocomplete/DuckDuckGoProvider.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#6698 Don't show a double stacked invite modals when inviting to Spaces
  src/components/views/spaces/SpacePublicShare.tsx
Labels: T-Defect

#6713 Fix membership updates to Spaces not applying in real-time
  src/stores/SpaceStore.tsx
Labels: T-Defect
