Repository matrix-org/matrix-react-sdk, pull requests merged in 2021-03, with the labels that each got.

#5738 Add tooltips to sent/sending receipts
  src/components/views/rooms/EventTile.js
  src/i18n/strings/en_EN.json
Labels: release-blocker

#5737 Fix sent markers disappearing for edits/reactions
  src/components/structures/MessagePanel.js
Labels: release-blocker

#5749 Properly gate SpaceRoomView behind labs
  src/components/structures/RoomView.tsx
Labels: release-blocker

#5750 [Release] Properly gate SpaceRoomView behind labs
  src/components/structures/RoomView.tsx
Labels: release-blocker

#5782 Fix CIDER formatting buttons on Safari
  docs/ciderEditor.md
  res/css/views/rooms/_MessageComposerFormatBar.scss
  src/components/views/rooms/MessageComposerFormatBar.js
Labels: bug

#5781 Fix redaction event list summaries breaking sender profiles
  src/components/structures/MessagePanel.js
Labels: release-blocker

#5784 Track next event [tile] over group boundaries
  src/components/structures/MessagePanel.js
Labels: release-blocker

#5807 Tweak cross-signing copy
  res/css/structures/_ToastContainer.scss
  src/components/structures/MatrixChat.tsx
  src/components/structures/auth/SetupEncryptionBody.js
  src/components/views/dialogs/VerificationRequestDialog.js
  src/components/views/right_panel/EncryptionInfo.tsx
  src/components/views/toasts/GenericToast.tsx
  src/components/views/toasts/VerificationRequestToast.tsx
  src/i18n/strings/en_EN.json
  src/toasts/BulkUnverifiedSessionsToast.ts
  src/toasts/UnverifiedSessionToast.ts
  test/end-to-end-tests/src/usecases/verify.js
Labels: X-Release-Blocker

#5803 Fix crash on login when using social login
  src/components/views/elements/SSOButtons.tsx
  src/customisations/Media.ts
Labels: X-Release-Blocker

#5808 [Release] Tweak cross-signing copy
  res/css/structures/_ToastContainer.scss
  src/components/structures/MatrixChat.tsx
  src/components/structures/auth/SetupEncryptionBody.js
  src/components/views/dialogs/VerificationRequestDialog.js
  src/components/views/right_panel/EncryptionInfo.tsx
  src/components/views/toasts/GenericToast.tsx
  src/components/views/toasts/VerificationRequestToast.tsx
  src/i18n/strings/en_EN.json
  src/toasts/BulkUnverifiedSessionsToast.ts
  src/toasts/UnverifiedSessionToast.ts
  test/end-to-end-tests/src/usecases/verify.js
Labels: X-Release-Blocker
