Repository matrix-org/matrix-react-sdk, pull requests merged in 2021-07, with the labels that each got.

#5099 Add support for blurhash (MSC2448)
  package.json
  res/css/views/messages/_MImageBody.scss
  src/ContentMessages.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/UploadBar.tsx
  src/components/views/elements/BlurhashPlaceholder.tsx
  src/components/views/messages/MImageBody.js
  src/components/views/messages/MStickerBody.js
  src/components/views/messages/MVideoBody.tsx
  yarn.lock
Labels: Z-Community-PR

#6357 Adjust recording waveform behaviour for voice messages
  src/utils/FixedRollingArray.ts
  src/voice/RecorderWorklet.ts
  src/voice/VoiceRecording.ts
  src/voice/consts.ts
  test/utils/FixedRollingArray-test.ts
Labels: Sponsored

#6359 Increase sample count in voice message thumbnail
  src/components/views/rooms/VoiceRecordComposerTile.tsx
  src/voice/Playback.ts
Labels: Sponsored

#6369 Use TileShape enum more universally
  src/components/views/elements/ReplyThread.js
  src/components/views/messages/MFileBody.js
  src/components/views/messages/MessageEvent.js
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/ReplyPreview.js
Labels: Sponsored

#6370 Fix voice messages in right panels
  res/css/views/audio_messages/_PlaybackContainer.scss
  src/components/views/audio_messages/RecordingPlayback.tsx
  src/components/views/messages/MVoiceMessageBody.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/PinnedEventTile.tsx
Labels: Sponsored

#6371 Send clear events to widgets when permitted
  src/stores/widgets/StopGapWidget.ts
  src/stores/widgets/StopGapWidgetDriver.ts
Labels: Sponsored

#6378 Exclude state events from widgets reading room events
  src/stores/widgets/StopGapWidgetDriver.ts
Labels: Sponsored

#6385 Fix EventIndex double handling events and erroring
  src/Notifier.ts
  src/Unread.ts
  src/components/structures/MessagePanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/TimelinePanel.tsx
  src/indexing/EventIndex.ts
  test/test-utils.js
Labels: T-Enhancement

#4399 Use URLSearchParams instead of transitive dependency `querystring`
  src/HtmlUtils.tsx
  src/Lifecycle.ts
  src/components/structures/MatrixChat.tsx
  src/utils/HostingLink.js
Labels: T-Task

#6352 Notification settings UI refresh
  res/css/_components.scss
  res/css/views/elements/_TagComposer.scss
  res/css/views/settings/_Notifications.scss
  res/img/subtract.svg
  src/components/views/elements/Spinner.js
  src/components/views/elements/Spinner.tsx
  src/components/views/elements/TagComposer.tsx
  src/components/views/rooms/RoomTile.tsx
  src/components/views/settings/Notifications.js
  src/components/views/settings/Notifications.tsx
  src/components/views/settings/tabs/user/NotificationUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/notifications/ContentRules.ts
  src/notifications/NotificationUtils.ts
  src/notifications/PushRuleVectorState.ts
  src/notifications/VectorPushRulesDefinitions.ts
  src/notifications/types.ts
Labels: Sponsored, T-Enhancement

#6392 Cleanup reply code
  res/css/views/elements/_ReplyThread.scss
  res/css/views/rooms/_ReplyPreview.scss
  res/css/views/rooms/_ReplyTile.scss
  src/ActiveRoomObserver.ts
  src/components/views/elements/ReplyThread.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/ReplyPreview.tsx
  src/components/views/voip/CallPreview.tsx
  src/stores/RoomViewStore.tsx
Labels: T-Task

#6394 Fix bug where 'other homeserver' would unfocus
  res/css/views/elements/_StyledRadioButton.scss
  src/components/views/dialogs/ServerPickerDialog.tsx
  src/components/views/elements/StyledRadioButton.tsx
Labels: T-Defect

#6403 Update eslint-plugin-matrix-org
  yarn.lock
Labels: T-Task

#6397 Respect compound emojis in default avatar initial generation
  src/Avatar.ts
Labels: T-Defect

#6347 Update Emojibase and Twemoji and switch to IamCal (Slack-style) shortcodes
  package.json
  res/fonts/Twemoji_Mozilla/TwemojiMozilla-colr.woff2
  res/fonts/Twemoji_Mozilla/TwemojiMozilla-sbix.woff2
  src/HtmlUtils.tsx
  src/autocomplete/EmojiProvider.tsx
  src/components/views/emojipicker/EmojiPicker.tsx
  src/components/views/emojipicker/Preview.tsx
  src/emoji.ts
  yarn.lock
Labels: T-Defect

#6415 Revert accidental renaming of dispatcherRef
  src/components/views/elements/PersistedElement.js
Labels: T-Defect

#6405 Remove hover effect from files in the files panel
  res/css/structures/_FilePanel.scss
Labels: Sponsored, T-Task

#6401 Fix grecaptcha throwing useless error sometimes
  src/@types/global.d.ts
  src/components/views/auth/CaptchaForm.tsx
Labels: T-Defect

#6417 Play only one audio file at a time
  src/components/views/messages/MAudioBody.tsx
  src/voice/ManagedPlayback.ts
  src/voice/Playback.ts
  src/voice/PlaybackClock.ts
  src/voice/PlaybackManager.ts
Labels: Sponsored, T-Enhancement

#6430 yarn upgrade
  src/stores/UIStore.ts
  src/utils/PasswordScorer.ts
  yarn.lock
Labels: T-Task

#6431 Restore 'use default' naming on room notifications
  src/components/views/rooms/RoomTile.tsx
  src/i18n/strings/en_EN.json
Labels: Sponsored, T-Task

#6355 Make diff colors in codeblocks more pleasant
  res/css/views/rooms/_EventTile.scss
  res/themes/dark/css/_dark.scss
Labels: T-Defect

#6432 Clean up visual style of files and voice messages
  res/css/_components.scss
  res/css/views/audio_messages/_AudioPlayer.scss
  res/css/views/audio_messages/_PlaybackContainer.scss
  res/css/views/messages/_MFileBody.scss
  res/css/views/messages/_MVoiceMessageBody.scss
  res/css/views/messages/_MediaBody.scss
  res/css/views/rooms/_SendMessageComposer.scss
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light/css/_light.scss
  src/components/views/messages/MFileBody.tsx
Labels: Sponsored, T-Task

#6433 Render error state for audio components
  src/components/views/audio_messages/AudioPlayer.tsx
  src/components/views/audio_messages/RecordingPlayback.tsx
  src/i18n/strings/en_EN.json
  src/voice/Playback.ts
Labels: Sponsored, T-Task

#6434 Handle upload errors in voice messages
  src/components/views/rooms/VoiceRecordComposerTile.tsx
  src/i18n/strings/en_EN.json
  src/voice/VoiceRecording.ts
Labels: Sponsored, T-Task

#6435 Fix duration placeholder parsing for audio files
  src/voice/PlaybackClock.ts
Labels: Sponsored, T-Defect

#6436 Use a MediaElementSourceAudioNode to process large audio files
  src/voice/Playback.ts
Labels: Sponsored, T-Defect

#6456 Fix display of image messages that lack thumbnails
  src/utils/MediaEventHelper.ts
Labels: T-Defect

#6462 Fix position of the space hierarchy spinner
  res/css/structures/_SpaceRoomView.scss
Labels: T-Defect

#6453 Clean up voice messages code
  src/audio/ManagedPlayback.ts
  src/audio/Playback.ts
  src/audio/PlaybackClock.ts
  src/audio/PlaybackManager.ts
  src/audio/RecorderWorklet.ts
  src/audio/VoiceRecording.ts
  src/audio/compat.ts
  src/audio/consts.ts
  src/components/views/audio_messages/AudioPlayer.tsx
  src/components/views/audio_messages/AudioPlayerBase.tsx
  src/components/views/audio_messages/DurationClock.tsx
  src/components/views/audio_messages/LiveRecordingClock.tsx
  src/components/views/audio_messages/LiveRecordingWaveform.tsx
  src/components/views/audio_messages/PlayPauseButton.tsx
  src/components/views/audio_messages/PlaybackClock.tsx
  src/components/views/audio_messages/PlaybackWaveform.tsx
  src/components/views/audio_messages/RecordingPlayback.tsx
  src/components/views/audio_messages/SeekBar.tsx
  src/components/views/messages/MAudioBody.tsx
  src/components/views/messages/MVoiceMessageBody.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/VoiceRecordComposerTile.tsx
  src/stores/VoiceRecordingStore.ts
Labels: Sponsored, T-Task

#6467 Fix blurhash rounded corners missing regression
  res/css/views/messages/_MImageBody.scss
  src/components/views/messages/MImageBody.tsx
Labels: T-Defect

#6478 Fix infinite pagination loop when offline
  src/components/structures/ScrollPanel.tsx
Labels: T-Defect

#6479 Fix timing of voice message recording UI appearing
  src/components/views/rooms/MessageComposer.tsx
Labels: Sponsored, T-Defect

#5992 Add support for screen sharing in 1:1 calls
  res/css/_components.scss
  res/css/views/elements/_DesktopCapturerSourcePicker.scss
  res/css/views/voip/_CallView.scss
  res/css/views/voip/_CallViewSidebar.scss
  res/css/views/voip/_VideoFeed.scss
  res/img/voip/screensharing-off.svg
  res/img/voip/screensharing-on.svg
  res/img/voip/sidebar-off.svg
  res/img/voip/sidebar-on.svg
  src/CallHandler.tsx
  src/components/views/elements/DesktopCapturerSourcePicker.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/voip/AudioFeed.tsx
  src/components/views/voip/CallView.tsx
  src/components/views/voip/CallViewSidebar.tsx
  src/components/views/voip/VideoFeed.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#6455 Add customisation point for declaring widget variables
  src/customisations/WidgetVariables.ts
  src/stores/widgets/StopGapWidget.ts
Labels: Sponsored, T-Enhancement

#6508 Fix clicking pills inside replies
  src/components/views/elements/Pill.js
Labels: T-Defect

#6424 Prompt user to leave rooms/subspaces in a space when leaving space
  res/css/_components.scss
  res/css/views/dialogs/_AddExistingToSpaceDialog.scss
  res/css/views/dialogs/_LeaveSpaceDialog.scss
  src/components/views/dialogs/LeaveSpaceDialog.tsx
  src/components/views/spaces/SpaceSettingsGeneralTab.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  src/i18n/strings/en_EN.json
  src/stores/SpaceStore.tsx
  src/utils/space.tsx
Labels: T-Enhancement

#6496 Fix DialPad and Call Menu buttons not working when a call is fullscreened.
  src/components/structures/ContextMenu.tsx
  src/components/views/voip/CallView.tsx
Labels: T-Defect

#6516 createRoom, only send join rule event if we have a join rule to put in it
  src/createRoom.ts
Labels: T-Defect

#6509 Improve download interactions
  res/css/views/messages/_MFileBody.scss
  src/components/views/messages/DownloadActionButton.tsx
  src/components/views/messages/MFileBody.tsx
  src/i18n/strings/en_EN.json
  src/utils/FileDownloader.ts
  src/utils/FileUtils.ts
Labels: Sponsored, T-Task, X-Release-Blocker

#6510 [Release] Improve download interactions
  res/css/views/messages/_MFileBody.scss
  src/components/views/messages/DownloadActionButton.tsx
  src/components/views/messages/MFileBody.tsx
  src/i18n/strings/en_EN.json
  src/utils/FileDownloader.ts
  src/utils/FileUtils.ts
Labels: Sponsored, T-Task, X-Release-Blocker
