Repository matrix-org/matrix-react-sdk, pull requests merged in 2021-10, with the labels that each got.

#6876 Fix pagination when filtering space hierarchy
  src/components/structures/SpaceHierarchy.tsx
Labels: T-Defect

#6868 Color clean-up #3 mk2
  res/css/structures/_ToastContainer.scss
  res/css/views/audio_messages/_PlaybackContainer.scss
  res/css/views/dialogs/_InviteDialog.scss
  res/css/views/dialogs/_SpaceSettingsDialog.scss
  res/css/views/messages/_MFileBody.scss
  res/css/views/messages/_MediaBody.scss
  res/css/views/right_panel/_VerificationPanel.scss
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light-custom/css/_custom.scss
  res/themes/light/css/_light.scss
Labels: T-Task

#6893 Handle newer voice message encrypted event format for chat export
  src/utils/exportUtils/Exporter.ts
Labels: T-Defect

#6892 Don't let click events propagate out of context menus
  src/components/structures/ContextMenu.tsx
Labels: T-Enhancement

#6891 Fix leaving space via other client leaving you in undefined-land
  src/stores/SpaceStore.ts
Labels: T-Defect

#6877 Add ability to properly edit messages in Threads.
  src/components/structures/MessagePanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadView.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/contexts/MatrixClientContext.ts
  src/contexts/MatrixClientContext.tsx
  src/contexts/RoomContext.ts
  src/dispatcher/actions.ts
  src/shouldHideEvent.ts
  src/utils/EventUtils.ts
  test/components/views/rooms/SendMessageComposer-test.tsx
Labels: T-Enhancement

#6894 Fix setTheme types
  src/theme.ts
Labels: T-Task

#6888 Pass replacingEventId for edits to appear in thread's view
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/EventTile.tsx
Labels: T-Task

#6900 Decrease profile button touch target
  res/css/views/settings/_ProfileSettings.scss
Labels: T-Enhancement

#6895 Use fallback avatar only for DMs with 2 people
  src/Avatar.ts
  test/components/views/rooms/RoomHeader-test.tsx
  test/test-utils.js
Labels: T-Defect

#6887 Add progress bar to Community to Space migration tool
  res/css/views/dialogs/_AddExistingToSpaceDialog.scss
  res/css/views/dialogs/_CreateSpaceFromCommunityDialog.scss
  src/RoomInvite.tsx
  src/components/views/dialogs/CreateSpaceFromCommunityDialog.tsx
  src/i18n/strings/en_EN.json
  src/utils/MultiInviter.ts
Labels: T-Enhancement

#6908 Fix space hierarchy pagination
  src/components/structures/SpaceHierarchy.tsx
Labels: T-Defect

#6912 Scalar messaging: No-op setBotPower if the current PL is greater than the requested PL.
  src/ScalarMessaging.ts
Labels: T-Task
