Repository matrix-org/matrix-react-sdk, pull requests merged in 2022-04, with the labels that each got.

#8209 Typescriptification - notification utils
  test/UserActivity-test.ts
  test/autocomplete/QueryMatcher-test.ts
  test/notifications/ContentRules-test.ts
  test/notifications/PushRuleVectorState-test.js
  test/notifications/PushRuleVectorState-test.ts
Labels: T-Task

#8207 Update video rooms to new design specs
  res/css/_components.scss
  res/css/structures/_RoomView.scss
  res/css/views/elements/_FacePile.scss
  res/css/views/rooms/_RoomList.scss
  res/css/views/rooms/_RoomListHeader.scss
  res/css/views/rooms/_RoomTile.scss
  res/css/views/voip/_VoiceChannelRadio.scss
  res/img/voip/voice-room.svg
  src/Lifecycle.ts
  src/components/structures/LeftPanel.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/dialogs/CreateRoomDialog.tsx
  src/components/views/elements/FacePile.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomListHeader.tsx
  src/components/views/rooms/RoomTile.tsx
  src/components/views/voip/VoiceChannelRadio.tsx
  src/createRoom.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/VideoChannelStore.ts
  src/stores/VoiceChannelStore.ts
  src/utils/VideoChannelUtils.ts
  src/utils/WidgetUtils.ts
  src/utils/space.tsx
  test/components/views/rooms/RoomTile-test.tsx
  test/components/views/voip/VoiceChannelRadio-test.tsx
  test/end-to-end-tests/src/usecases/create-room.ts
  test/stores/VideoChannelStore-test.ts
  test/stores/VoiceChannelStore-test.ts
  test/test-utils/index.ts
  test/test-utils/video.ts
  test/test-utils/voice.ts
Labels: T-Enhancement

#8192 Remove triage automation
  .github/workflows/triage-move-review-requests.yml
Labels: T-Task

#8221 Fix typo in key binding management docs
  docs/features/keyboardShortcuts.md
Labels: T-Task

#8129 Normalize call buttons
  res/css/_common.scss
  res/css/views/messages/_CallEvent.scss
  res/css/views/toasts/_IncomingCallToast.scss
Labels: T-Defect

#8218 Make "Jump to date" translatable
  src/components/views/messages/JumpToDatePicker.tsx
Labels: T-Defect

#8227 Fix URL previews being enabled when room first created
  src/components/structures/RoomView.tsx
Labels: T-Defect

#8222 More video rooms design updates
  res/css/structures/_RoomView.scss
  res/css/views/rooms/_AppsDrawer.scss
  res/css/views/rooms/_RoomList.scss
  res/css/views/rooms/_RoomListHeader.scss
  res/img/element-icons/roomlist/hash-video.svg
  src/components/structures/RoomView.tsx
Labels: T-Enhancement

#8081 Release threads as a beta feature
  res/css/structures/_RightPanel.scss
  res/css/structures/_RoomView.scss
  res/css/views/elements/_Tooltip.scss
  res/css/views/messages/_MessageActionBar.scss
  res/css/views/right_panel/_ThreadPanel.scss
  res/css/views/rooms/_EventTile.scss
  res/img/betas/threads.png
  res/themes/light/css/_light.scss
  src/components/structures/ThreadPanel.tsx
  src/components/views/beta/BetaCard.tsx
  src/components/views/dialogs/BetaFeedbackDialog.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Enhancement

#7795 Replace browser-encrypt-attachment with matrix-encrypt-attachment
  package.json
  src/@types/browser-encrypt-attachment.ts
  src/ContentMessages.ts
  src/utils/DecryptFile.ts
  yarn.lock
Labels: T-Task

#8151 Add default properties to link buttons and remove redundant settings
  res/css/structures/_ToastContainer.scss
  res/css/structures/_UserMenu.scss
  res/css/structures/auth/_Login.scss
  res/css/views/dialogs/_FeedbackDialog.scss
  res/css/views/dialogs/_GenericFeatureFeedbackDialog.scss
  res/css/views/dialogs/_SpaceSettingsDialog.scss
  res/css/views/dialogs/_SpotlightDialog.scss
  res/css/views/elements/_AccessibleButton.scss
  res/css/views/rooms/_NewRoomIntro.scss
  res/css/views/rooms/_PinnedEventTile.scss
  res/css/views/settings/_ProfileSettings.scss
  res/css/views/settings/tabs/room/_NotificationSettingsTab.scss
  res/css/views/settings/tabs/user/_PreferencesUserSettingsTab.scss
  res/css/views/spaces/_SpaceBasicSettings.scss
  res/css/views/spaces/_SpaceCreateMenu.scss
Labels: X-Blocked, T-Task

#8225 Live location sharing - extract location markers into generic Marker
  res/css/_components.scss
  res/css/components/views/location/_Marker.scss
  res/css/views/location/_LocationPicker.scss
  res/css/views/messages/_MLocationBody.scss
  src/components/views/location/LocationPicker.tsx
  src/components/views/location/Marker.tsx
  src/components/views/messages/MLocationBody.tsx
  test/components/views/location/LocationPicker-test.tsx
  test/components/views/location/Marker-test.tsx
  test/components/views/location/__snapshots__/Marker-test.tsx.snap
Labels: T-Task

#8250 Fix: Ensure links to events scroll the correct events into view
  src/components/structures/TimelinePanel.tsx
Labels: T-Defect

#8244 Make Jitsi widgets in video rooms immutable
  src/createRoom.ts
  test/createRoom-test.js
  test/createRoom-test.ts
  test/test-utils/test-utils.ts
Labels: T-Defect

#8249 Fix bubble layout in thread view
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#8256 Live location sharing - update beacon_info implementation to latest MSC
  src/components/views/beacon/RoomLiveShareWarning.tsx
  src/components/views/location/shareLocation.ts
  src/stores/OwnBeaconStore.ts
  src/utils/beacon/duration.ts
  test/components/views/beacon/RoomLiveShareWarning-test.tsx
  test/components/views/beacon/__snapshots__/RoomLiveShareWarning-test.tsx.snap
  test/components/views/location/LocationShareMenu-test.tsx
  test/stores/OwnBeaconStore-test.ts
  test/test-utils/beacon.ts
Labels: T-Task

#8257 Fix reporting events not working
  src/components/views/dialogs/ReportEventDialog.tsx
  src/utils/DialogOpener.ts
Labels: T-Defect

#8270 Add a test for URL previews being disabled in e2e rooms
  package.json
  test/TextForEvent-test.ts
  test/components/structures/RoomView-test.tsx
  yarn.lock
Labels: T-Task

#8263 Fix: Remove jittery timeline scrolling after jumping to an event
  src/components/structures/MessagePanel.tsx
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ScrollPanel.tsx
  src/components/structures/ThreadView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/right_panel/TimelineCard.tsx
  src/dispatcher/dispatch-actions/threads.ts
  src/dispatcher/payloads/ViewRoomPayload.ts
  src/stores/RoomViewStore.tsx
  src/stores/right-panel/RightPanelStoreIPanelState.ts
Labels: T-Defect

#6188 Add heart effect
  src/effects/hearts/index.ts
  src/effects/index.ts
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#8212 Fixes button labels being collapsed per a character in CJK languages
  res/css/views/elements/_AccessibleButton.scss
Labels: T-Defect

#8266 Live location sharing - set replaces relation when stopping beacon
  src/stores/OwnBeaconStore.ts
  test/stores/OwnBeaconStore-test.ts
Labels: T-Task

#8235 Live location sharing - extract zoom buttons into component
  __mocks__/maplibre-gl.js
  res/css/_components.scss
  res/css/components/views/location/_ZoomButtons.scss
  res/img/element-icons/minus-button.svg
  res/img/element-icons/plus-button.svg
  src/components/views/location/ZoomButtons.tsx
  test/components/views/location/ZoomButtons-test.tsx
  test/components/views/location/__snapshots__/ZoomButtons-test.tsx.snap
Labels: T-Task

#8265 Live location sharing - update beacon tile with latest location
  src/components/views/messages/IBodyProps.ts
  src/components/views/messages/MBeaconBody.tsx
  src/components/views/messages/MessageEvent.tsx
  src/stores/OwnBeaconStore.ts
  src/utils/beacon/index.ts
  src/utils/beacon/useBeacon.ts
  test/components/views/location/__snapshots__/SmartMarker-test.tsx.snap
  test/components/views/messages/MBeaconBody-test.tsx
  test/components/views/messages/__snapshots__/MBeaconBody-test.tsx.snap
Labels: T-Task

#8276 Use a consistent alignment for all text items in a list
  src/components/views/messages/DisambiguatedProfile.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/EntityTile.tsx
  src/components/views/rooms/RoomTile.tsx
Labels: T-Defect

#8280 Delete slate-formats.md
  docs/slate-formats.md
Labels: T-Task

#8236 Live location sharing - consolidate maps
  __mocks__/maplibre-gl.js
  res/css/views/dialogs/_LocationViewDialog.scss
  src/components/views/location/LocationPicker.tsx
  src/components/views/location/LocationViewDialog.tsx
  src/components/views/location/Map.tsx
  src/components/views/messages/MLocationBody.tsx
  src/i18n/strings/en_EN.json
  src/utils/location/useMap.ts
  test/components/views/location/LocationPicker-test.tsx
  test/components/views/location/LocationViewDialog-test.tsx
  test/components/views/location/Map-test.tsx
  test/components/views/location/__snapshots__/LocationViewDialog-test.tsx.snap
  test/components/views/location/__snapshots__/SmartMarker-test.tsx.snap
  test/components/views/location/__snapshots__/ZoomButtons-test.tsx.snap
  test/components/views/messages/MLocationBody-test.tsx
  test/components/views/messages/__snapshots__/MLocationBody-test.tsx.snap
Labels: T-Task

#8278 Add copy button to View Source screen
  res/css/structures/_ViewSource.scss
  src/components/structures/ViewSource.tsx
Labels: T-Enhancement

#8288 Fix: Avatar preview does not update when same file is selected repeatedly
  src/components/views/dialogs/security/AccessSecretStorageDialog.tsx
  src/components/views/elements/MiniAvatarUploader.tsx
  src/components/views/room_settings/RoomProfileSettings.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
  src/components/views/settings/ChangeAvatar.tsx
  src/components/views/settings/ProfileSettings.tsx
  src/components/views/settings/tabs/room/NotificationSettingsTab.tsx
  src/components/views/spaces/SpaceBasicSettings.tsx
  src/utils/BrowserWorkarounds.ts
Labels: T-Defect

#8293 add excluded style to components.scss
  res/css/_components.scss
Labels: T-Task

#8292 Handle thread bundled relationships coming from the server via MSC3666
  src/components/structures/RoomView.tsx
Labels: T-Defect

#8291 When selecting reply in thread on a thread response open existing thread
  src/components/views/messages/MessageActionBar.tsx
Labels: T-Defect

#8289 Prevent soft crash around room list header context menu when space changes
  src/components/views/rooms/RoomListHeader.tsx
  test/components/views/rooms/RoomListHeader-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Defect

#8294 Hide the reply in thread button in deployments where beta is forcibly disabled
  src/components/views/messages/MessageActionBar.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#8299 Fix space panel width change on hovering over space item
  res/css/structures/_SpacePanel.scss
Labels: T-Defect

#8301 Fix coverage diffs for PRs that aren't up to date, take 3
  .github/workflows/test_coverage.yml
Labels: T-Task

#8300 Send stable m.policy.rule.* events instead of mjolnir-prefixed unstable ones
  src/mjolnir/BanList.ts
Labels: T-Task

#8298 Fix threads rendering issue in Safari
  res/css/views/right_panel/_ThreadPanel.scss
Labels: T-Defect

#8285 Live location sharing - beacon in timeline happy path
  res/css/_components.scss
  res/css/components/views/beacon/_BeaconStatus.scss
  res/css/components/views/beacon/_RoomLiveShareWarning.scss
  res/css/components/views/beacon/_StyledLiveBeaconIcon.scss
  res/css/components/views/messages/_MBeaconBody.scss
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light/css/_light.scss
  src/components/views/beacon/BeaconStatus.tsx
  src/components/views/beacon/RoomLiveShareWarning.tsx
  src/components/views/beacon/StyledLiveBeaconIcon.tsx
  src/components/views/messages/MBeaconBody.tsx
  src/i18n/strings/en_EN.json
  src/utils/beacon/index.ts
  src/utils/beacon/useBeacon.ts
  src/utils/beacon/useOwnLiveBeacons.ts
  test/components/views/beacon/BeaconStatus-test.tsx
  test/components/views/beacon/RoomLiveShareWarning-test.tsx
  test/components/views/beacon/__snapshots__/BeaconStatus-test.tsx.snap
  test/components/views/beacon/__snapshots__/RoomLiveShareWarning-test.tsx.snap
  test/components/views/messages/MBeaconBody-test.tsx
Labels: T-Enhancement

#8305 Fix some issues with threads rendering
  res/css/views/right_panel/_ThreadPanel.scss
  res/css/views/rooms/_EventTile.scss
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light-custom/css/_custom.scss
  res/themes/light/css/_light.scss
Labels: T-Defect

#8308 Stop tracking threads if threads support is disabled
  src/components/structures/RoomView.tsx
  src/utils/EventUtils.ts
Labels: T-Defect

#8274 Don't show the prompt to enable desktop notifications immediately after registration
  src/Lifecycle.ts
  src/MatrixClientPeg.ts
  test/MatrixClientPeg-test.ts
  test/end-to-end-tests/src/scenarios/toast.ts
Labels: T-Defect

#8311 Introduce small delay to let redaction propagate for tests
  test/end-to-end-tests/src/usecases/threads.ts
Labels: T-Task

#8314 Replace deprecated String#substr with String#slice
  src/Avatar.ts
  src/autocomplete/CommandProvider.tsx
  src/components/views/dialogs/CreateRoomDialog.tsx
  src/components/views/elements/EffectsOverlay.tsx
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
  src/editor/deserialize.ts
  src/editor/diff.ts
  src/editor/operations.ts
  src/editor/parts.ts
  src/languageHandler.tsx
  src/stores/widgets/StopGapWidget.ts
  src/theme.ts
  test/PosthogAnalytics-test.ts
  test/components/views/rooms/MemberList-test.tsx
  test/end-to-end-tests/src/rest/session.ts
Labels: T-Task

#8306 Refactor SecurityRoomSettingsTab and remove unused state
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
Labels: T-Defect

#8295 Add a Cypress Test 🌲
  .eslintrc.js
  .github/workflows/element-build-and-test.yaml
  .github/workflows/layered-build.yaml
  .gitignore
  cypress.json
  cypress/integration/1-register/register.spec.ts
  cypress/plugins/index.ts
  cypress/plugins/synapsedocker/index.ts
  cypress/plugins/synapsedocker/templates/COPYME/README.md
  cypress/plugins/synapsedocker/templates/COPYME/homeserver.yaml
  cypress/plugins/synapsedocker/templates/COPYME/log.config
  cypress/plugins/synapsedocker/templates/consent/README.md
  cypress/plugins/synapsedocker/templates/consent/homeserver.yaml
  cypress/plugins/synapsedocker/templates/consent/log.config
  cypress/plugins/synapsedocker/templates/consent/res/templates/privacy/en/1.0.html
  cypress/plugins/synapsedocker/templates/consent/res/templates/privacy/en/success.html
  cypress/support/index.ts
  cypress/tsconfig.json
  package.json
  test/end-to-end-tests/src/scenario.ts
  test/end-to-end-tests/yarn.lock
  yarn.lock
Labels: T-Task

#8318 Improve Threads beta around degraded mode
  src/components/views/messages/MessageActionBar.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/SettingsStore.ts
  src/settings/controllers/SettingController.ts
  src/settings/controllers/ThreadBetaController.tsx
Labels: T-Enhancement

#8319 [Release] Fixes around threads beta in degraded mode
  src/components/structures/ThreadPanel.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/SettingsStore.ts
  src/settings/controllers/SettingController.ts
  src/settings/controllers/ThreadBetaController.tsx
Labels: T-Defect

#8296 Live location sharing - render users own beacons in timeline
  res/css/_components.scss
  res/css/components/views/beacon/_BeaconStatus.scss
  res/css/components/views/beacon/_OwnBeaconStatus.scss
  src/components/views/beacon/BeaconStatus.tsx
  src/components/views/beacon/OwnBeaconStatus.tsx
  src/components/views/messages/MBeaconBody.tsx
  src/i18n/strings/en_EN.json
  test/components/views/beacon/BeaconStatus-test.tsx
  test/components/views/beacon/OwnBeaconStatus-test.tsx
  test/components/views/beacon/__snapshots__/BeaconStatus-test.tsx.snap
  test/components/views/beacon/__snapshots__/OwnBeaconStatus-test.tsx.snap
Labels: T-Enhancement

#8310 Live location sharing - basic maximised beacon map
  res/css/_components.scss
  res/css/components/views/beacon/_BeaconViewDialog.scss
  res/css/components/views/messages/_MBeaconBody.scss
  src/components/views/beacon/BeaconMarker.tsx
  src/components/views/beacon/BeaconViewDialog.tsx
  src/components/views/location/LocationViewDialog.tsx
  src/components/views/location/SmartMarker.tsx
  src/components/views/messages/MBeaconBody.tsx
  src/utils/WellKnownUtils.ts
  src/utils/beacon/useLiveBeacons.ts
  test/components/views/beacon/BeaconMarker-test.tsx
  test/components/views/beacon/BeaconViewDialog-test.tsx
  test/components/views/beacon/__snapshots__/BeaconMarker-test.tsx.snap
  test/components/views/location/LocationViewDialog-test.tsx
  test/components/views/location/Map-test.tsx
  test/components/views/location/__snapshots__/LocationViewDialog-test.tsx.snap
  test/components/views/location/__snapshots__/SmartMarker-test.tsx.snap
  test/components/views/messages/MBeaconBody-test.tsx
  test/components/views/messages/MLocationBody-test.tsx
  test/components/views/messages/__snapshots__/MLocationBody-test.tsx.snap
Labels: T-Enhancement

#8326 Fix synapse logs directory in Cypress tests
  .github/workflows/element-build-and-test.yaml
Labels: T-Task

#8330 Fix netlify previews
  .github/workflows/netlify.yaml
Labels: T-Task

#8322 Fix image preview sizing for edge cases
  res/css/views/messages/_MImageBody.scss
  res/css/views/rooms/_EventBubbleTile.scss
  src/components/views/messages/MImageBody.tsx
Labels: T-Defect

#8096 Fixes call tiles overflow
  res/css/views/messages/_CallEvent.scss
Labels: T-Defect

#8205 Fix overlapping timestamps on empty messages
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#8086 Resolve emoji autocomplete not being temporally consistent
  src/autocomplete/EmojiProvider.tsx
  test/autocomplete/EmojiProvider-test.ts
Labels: T-Defect

#8230 Make ToastContainer compatible with RTL layout
  res/css/structures/_ToastContainer.scss
  src/components/structures/ToastContainer.tsx
Labels: T-Task

#8290 Move RequiresClient from MatrixCapabilities to ElementWidgetCapabilities
  src/components/views/elements/AppTile.tsx
  src/stores/widgets/ElementWidgetCapabilities.ts
  src/stores/widgets/StopGapWidgetDriver.ts
Labels: T-Task

#8333 Fix a soft crash with video rooms
  src/utils/VideoChannelUtils.ts
Labels: T-Defect

#8313 Avoid looking up settings during timeline rendering
  src/Unread.ts
  src/components/structures/MessagePanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/messages/TextualEvent.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/ReplyTile.tsx
  src/components/views/rooms/SearchResultTile.tsx
  src/contexts/RoomContext.ts
  src/events/EventTileFactory.tsx
  src/settings/Settings.tsx
  src/utils/EventRenderingUtils.ts
  src/utils/EventUtils.ts
  src/utils/exportUtils/HtmlExport.tsx
  src/utils/exportUtils/JSONExport.ts
  src/utils/exportUtils/PlainTextExport.ts
  test/components/structures/MessagePanel-test.js
  test/components/views/rooms/MessageComposerButtons-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
Labels: T-Defect

#8334 Fix rendering of hidden events
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#8297 Fix power selector not showing up in user info when state_default undefined
  src/components/views/right_panel/UserInfo.tsx
Labels: T-Defect

#5672 Add message right click context menu v2
  res/css/views/context_menus/_MessageContextMenu.scss
  src/BasePlatform.ts
  src/components/structures/ContextMenu.tsx
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/elements/AccessibleTooltipButton.tsx
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Enhancement

#8336 Enable the message right-click context menu in the browser
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/rooms/EventTile.tsx
  src/utils/EventUtils.ts
  src/utils/strings.ts
Labels: T-Enhancement

#8340 Fix beta indicator dot causing excessive CPU usage
  res/css/views/rooms/_EventTile.scss
Labels: X-Release-Blocker, T-Defect

#8348 Avoid a reflow when setting caret position on an empty composer
  src/editor/caret.ts
Labels: T-Enhancement

#8339 Put the right-click message context menu to the right
  src/components/structures/ContextMenu.tsx
  src/components/views/rooms/EventTile.tsx
Labels: T-Enhancement

#8347 Improve performance of switching to rooms with lots of servers and ACLs
  src/utils/permalinks/Permalinks.ts
Labels: T-Enhancement

#8321 Live location sharing - calculate geo bounds for multiple locations
  src/utils/beacon/bounds.ts
  test/utils/beacon/bounds-test.ts
Labels: T-Task

#8351 Cleanup `MessageContextMenu` code
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/messages/MessageEvent.tsx
  src/components/views/rooms/EventTile.tsx
  src/utils/EventUtils.ts
Labels: T-Task

#8349 Replace "Reply in thread" and "Leave the beta" with variables
  src/components/structures/ThreadPanel.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Task

#8181 Fix: "Code formatting button does not escape backticks"
  src/editor/deserialize.ts
  src/editor/operations.ts
  test/editor/operations-test.ts
Labels: T-Defect

#8243 RTL layout compatibility: bridges list on room settings page
  res/css/views/dialogs/_RoomSettingsDialogBridges.scss
  src/components/views/settings/BridgeTile.tsx
Labels: T-Task

#8356 fix: use fake timers and restore mocks in MatrixClientPeg test
  test/MatrixClientPeg-test.ts
Labels: T-Task

#8358 Settings toggle to disable Composer Markdown
  res/css/views/elements/_SettingsFlag.scss
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/editor/deserialize.ts
  src/editor/serialize.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/SettingsStore.ts
  test/editor/deserialize-test.ts
  test/editor/serialize-test.ts
Labels: T-Enhancement

#8364 Fix issue with ServerInfo crashing the modal
  src/components/views/dialogs/devtools/ServerInfo.tsx
Labels: T-Defect

#8365 Live location sharing: move test utils into utils
  test/components/views/beacon/BeaconMarker-test.tsx
  test/components/views/beacon/BeaconViewDialog-test.tsx
  test/components/views/messages/MBeaconBody-test.tsx
  test/test-utils/beacon.ts
  test/test-utils/room.ts
Labels: T-Task

#8367 Use -webkit-line-clamp for the room header topic overflow
  res/css/views/rooms/_RoomHeader.scss
Labels: T-Defect

#8346 Fix UnknownBody error message unalignment
  src/components/views/messages/UnknownBody.tsx
Labels: T-Defect

#8360 Live location sharing: maximised view sidebar container
  res/css/_common.scss
  res/css/_components.scss
  res/css/components/views/beacon/_BeaconViewDialog.scss
  res/css/components/views/beacon/_DialogSidebar.scss
  res/css/views/typography/_Heading.scss
  src/components/views/beacon/BeaconViewDialog.tsx
  src/components/views/beacon/DialogSidebar.tsx
  src/components/views/typography/Heading.tsx
  src/i18n/strings/en_EN.json
  test/components/views/beacon/BeaconViewDialog-test.tsx
  test/components/views/beacon/DialogSidebar-test.tsx
  test/components/views/beacon/__snapshots__/DialogSidebar-test.tsx.snap
  test/components/views/typography/Heading-test.tsx
  test/components/views/typography/__snapshots__/Heading-test.tsx.snap
Labels: T-Task

#8366 Cache localStorage objects for SettingsStore
  src/settings/handlers/AbstractLocalStorageSettingsHandler.ts
  src/settings/handlers/DeviceSettingsHandler.ts
  src/settings/handlers/RoomDeviceSettingsHandler.ts
Labels: T-Enhancement

#8370 Fix RightPanelStore handling first room on app launch wrong
  src/stores/right-panel/RightPanelStore.ts
Labels: T-Defect

#8245 fix rainbow breaks compound emojis
  src/utils/colour.ts
  test/utils/colour-test.ts
Labels: T-Defect

#8287 Show a lobby screen in video rooms
  res/css/_components.scss
  res/css/structures/_RoomView.scss
  res/css/structures/_VideoRoomView.scss
  res/css/views/elements/_FacePile.scss
  res/css/views/rooms/_RoomHeader.scss
  res/css/views/voip/_VideoLobby.scss
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light/css/_light.scss
  src/Lifecycle.ts
  src/components/structures/RoomView.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/structures/VideoRoomView.tsx
  src/components/views/elements/FacePile.tsx
  src/components/views/elements/RoomFacePile.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomTile.tsx
  src/components/views/voip/VideoLobby.tsx
  src/i18n/strings/en_EN.json
  src/stores/VideoChannelStore.ts
  src/stores/widgets/ElementWidgetActions.ts
  src/stores/widgets/WidgetMessagingStore.ts
  src/utils/VideoChannelUtils.ts
  test/components/structures/VideoRoomView-test.tsx
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/RoomTile-test.tsx
  test/components/views/voip/VideoLobby-test.tsx
  test/stores/VideoChannelStore-test.ts
  test/test-utils/video.ts
Labels: T-Enhancement

#8359 Fix race in Registration between server change and flows fetch
  src/components/structures/auth/Registration.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#8373 Remove float property to let the margin between events appear on bubble message layout
  res/css/views/rooms/_EventBubbleTile.scss
Labels: T-Defect

#8374 Live location sharing: own live beacon status on maximised view
  res/css/_components.scss
  res/css/components/views/beacon/_DialogOwnBeaconStatus.scss
  src/components/views/beacon/BeaconViewDialog.tsx
  src/components/views/beacon/DialogOwnBeaconStatus.tsx
  src/components/views/beacon/OwnBeaconStatus.tsx
  test/components/views/beacon/BeaconViewDialog-test.tsx
  test/components/views/beacon/__snapshots__/OwnBeaconStatus-test.tsx.snap
Labels: T-Enhancement

#8362 Upgrade dependencies
  src/HtmlUtils.tsx
  src/components/structures/auth/Login.tsx
  yarn.lock
Labels: T-Task

#8371 Improve text of account deactivation dialog
  res/css/views/dialogs/_DeactivateAccountDialog.scss
  src/components/views/dialogs/DeactivateAccountDialog.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#8329 Extract view/join room logic to room helper
  src/components/structures/RoomDirectory.tsx
  src/components/views/directory/NetworkDropdown.tsx
  src/i18n/strings/en_EN.json
  src/utils/DirectoryUtils.ts
  src/utils/error.ts
  src/utils/rooms.ts
Labels: T-Task

#8368 Add local echo of connected devices in video rooms
  src/components/views/rooms/RoomTile.tsx
  src/components/views/voip/VideoLobby.tsx
  src/utils/VideoChannelUtils.ts
  test/components/views/rooms/RoomTile-test.tsx
  test/components/views/voip/VideoLobby-test.tsx
  test/test-utils/test-utils.ts
  test/test-utils/video.ts
Labels: T-Enhancement

#8375 Forcefully disconnect from video rooms on logout and tab close
  src/components/structures/MatrixChat.tsx
  src/stores/VideoChannelStore.ts
Labels: T-Enhancement

#8372 Move more stuff from BK to GHA
  .editorconfig
  .github/workflows/element-build-and-test.yaml
  .github/workflows/end-to-end-tests.yaml
  .github/workflows/netlify.yaml
  .github/workflows/notify-element-web.yml
  .github/workflows/preview_changelog.yaml
  .github/workflows/static_analysis.yaml
  .github/workflows/tests.yml
  .github/workflows/typecheck.yaml
Labels: T-Task

#8383 Remove notify environment requirement
  .github/workflows/notify-element-web.yml
Labels: T-Task

#8376 Persist audio and video mute state in video rooms
  src/components/views/voip/VideoLobby.tsx
  src/stores/VideoChannelStore.ts
Labels: T-Enhancement

#8386 test functional EventUtils
  src/utils/EventUtils.ts
  test/stores/room-list/previews/PollStartEventPreview-test.ts
  test/test-utils/index.ts
  test/test-utils/poll.ts
  test/utils/EventUtils-test.ts
Labels: T-Task

#8385 Fix regression around the room list treeview keyboard a11y
  src/components/views/rooms/RoomList.tsx
Labels: T-Defect

#8387 LLS: fix jumpy maximised map
  src/components/views/beacon/BeaconViewDialog.tsx
  src/components/views/location/Map.tsx
  test/components/views/beacon/BeaconViewDialog-test.tsx
  test/components/views/location/Map-test.tsx
Labels: T-Enhancement

#8379 Fix regression around haveRendererForEvent for hidden events
  src/components/structures/MessagePanel.tsx
  src/events/EventTileFactory.tsx
  test/components/structures/MessagePanel-test.js
Labels: T-Defect

#8384 fix: "Mention highlight and cursor hover highlight has different corner radius"
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#8382 Fix issue with thread panel not updating when it loads on first render
  src/components/structures/ThreadPanel.tsx
  src/components/structures/TimelinePanel.tsx
Labels: T-Defect

#8390 LLS: Remove beacon info illegal replace relation
  src/events/EventTileFactory.tsx
  src/stores/OwnBeaconStore.ts
  src/utils/beacon/timeline.ts
  test/stores/OwnBeaconStore-test.ts
  test/utils/beacon/timeline-test.ts
Labels: T-Task

#8378 Live location sharing: only share to beacons created on device
  src/components/views/location/shareLocation.ts
  src/stores/OwnBeaconStore.ts
  src/utils/beacon/timeline.ts
  test/components/views/beacon/RoomLiveShareWarning-test.tsx
  test/components/views/location/LocationShareMenu-test.tsx
  test/stores/OwnBeaconStore-test.ts
  test/utils/beacon/timeline-test.ts
Labels: T-Task

#8353 Stick connected video rooms to the top of the room list
  src/stores/room-list/RoomListStore.ts
  src/stores/room-list/algorithms/Algorithm.ts
  test/stores/room-list/algorithms/Algorithm-test.ts
Labels: T-Enhancement

#8345 Changed font-weight to 400 to support light weight font
  res/css/_common.scss
  res/css/_components.scss
  res/css/structures/_CreateRoom.scss
Labels: T-Defect

#8259 Allow user to control if they are signed out of all devices when changing password
  src/PasswordReset.ts
  src/components/structures/auth/ForgotPassword.tsx
  src/components/views/settings/ChangePassword.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#8392 Fix issue with threads timelines with few events cropping events
  res/css/structures/_RoomView.scss
  src/components/structures/ScrollPanel.tsx
Labels: T-Defect

#8400 stop the bottom edge of buttons getting clipped in devtools
  res/css/views/dialogs/_DevtoolsDialog.scss
Labels: T-Defect

#8402 Tweak ReadReceiptGroup to better handle disambiguation
  src/components/views/rooms/ReadReceiptGroup.tsx
Labels: T-Defect

#8396 Fix infinite loop when pinning/unpinning persistent widgets
  src/components/views/elements/AppTile.tsx
  src/components/views/voip/PipView.tsx
  src/stores/ActiveWidgetStore.ts
  test/components/views/elements/AppTile-test.tsx
  test/stores/ActiveWidgetStore-test.ts
Labels: T-Defect

#8403 Disable download option on <video/> , preferring dedicated download button
  src/components/views/messages/MVideoBody.tsx
Labels: T-Defect

#8401 LLS: rename wireError
  src/components/views/beacon/LeftPanelLiveShareWarning.tsx
  src/components/views/beacon/OwnBeaconStatus.tsx
  src/components/views/beacon/RoomLiveShareWarning.tsx
  src/stores/OwnBeaconStore.ts
  src/utils/beacon/useOwnLiveBeacons.ts
  test/components/views/beacon/LeftPanelLiveShareWarning-test.tsx
  test/components/views/beacon/OwnBeaconStatus-test.tsx
  test/components/views/beacon/RoomLiveShareWarning-test.tsx
  test/components/views/beacon/__snapshots__/LeftPanelLiveShareWarning-test.tsx.snap
  test/components/views/beacon/__snapshots__/RoomLiveShareWarning-test.tsx.snap
  test/stores/OwnBeaconStore-test.ts
Labels: T-Task

#8404 Fix centering issue with sticker placeholder
  res/css/views/messages/_MStickerBody.scss
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MStickerBody.tsx
Labels: T-Defect

#8408 Don't form continuations on either side of a thread root
  src/components/structures/MessagePanel.tsx
  test/components/structures/MessagePanel-test.js
Labels: T-Defect

#8410 Make read receipts handle nullable roomMembers correctly
  src/components/views/avatars/MemberAvatar.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/ReadReceiptGroup.tsx
  src/components/views/rooms/ReadReceiptMarker.tsx
Labels: T-Defect

#8409 Add opt-in analytics to onboarding tasks
  package.json
  src/components/structures/HomePage.tsx
  src/components/structures/LeftPanel.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomListHeader.tsx
  yarn.lock
Labels: T-Enhancement

#8411 LLS: update location labs flag descriptions
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Task

#8414 Read Receipts "Fall from the Sky"
  src/components/views/avatars/MemberAvatar.tsx
  src/components/views/rooms/ReadReceiptMarker.tsx
Labels: T-Defect

#8418 Fix editing of non-html replies
  src/editor/deserialize.ts
  test/editor/deserialize-test.ts
Labels: T-Defect

#8421 Attempt to use deployments to signal Netlify builds instead
  .github/workflows/element-build-and-test.yaml
  .github/workflows/netlify.yaml
Labels: T-Task

#8424 Fix broken netlify ci
  .github/workflows/netlify.yaml
Labels: T-Task

#8427 Fix broken netlify ci
  .github/workflows/netlify.yaml
Labels: T-Task

#8428 Read Receipts: never show +1, if it’s just 4, show all of them
  src/components/views/rooms/ReadReceiptGroup.tsx
Labels: T-Enhancement

#8413 Fix baseline misalignment of thread panel summary by deduplication
  res/css/_components.scss
  res/css/views/right_panel/_ThreadPanel.scss
  res/css/views/right_panel/_TimelineCard.scss
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_IRCLayout.scss
  res/css/views/rooms/_ThreadSummary.scss
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/ThreadSummary.tsx
  test/end-to-end-tests/src/usecases/threads.ts
Labels: T-Defect

#8425 Fix source text boxes in View Source modal should have full width
  res/css/structures/_ViewSource.scss
Labels: T-Enhancement

#8432 Fix issue with underfilled timelines when barren of content
  src/components/structures/ScrollPanel.tsx
Labels: T-Defect

#8433 Unit test typescriptification - TextualBody
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
Labels: T-Task

#8412 Add new user signup event tracking in PostHog
  package.json
  src/MatrixClientPeg.ts
  src/PosthogAnalytics.ts
  src/components/views/auth/RegistrationForm.tsx
  src/components/views/elements/SSOButtons.tsx
  yarn.lock
Labels: T-Task

#8416 LLS: expose way to enable live sharing labs flag from location dialog
  res/css/_components.scss
  res/css/components/views/location/_EnableLiveShare.scss
  src/components/views/location/EnableLiveShare.tsx
  src/components/views/location/LocationShareMenu.tsx
  src/i18n/strings/en_EN.json
  test/components/views/location/LocationShareMenu-test.tsx
  test/components/views/location/__snapshots__/LocationShareMenu-test.tsx.snap
Labels: T-Enhancement

#8435 Unit test typescriptification - MKeyVerificationConclusion
  test/components/views/messages/MKeyVerificationConclusion-test.js
  test/components/views/messages/MKeyVerificationConclusion-test.tsx
Labels: T-Task

#8436 Record cypress runs to dashboard
  .github/workflows/element-build-and-test.yaml
  cypress.json
Labels: T-Task

#8406 LLS: error handling on stopping beacon
  src/components/views/beacon/LeftPanelLiveShareWarning.tsx
  src/components/views/beacon/RoomLiveShareWarning.tsx
  src/components/views/messages/MBeaconBody.tsx
  src/i18n/strings/en_EN.json
  src/stores/OwnBeaconStore.ts
  src/utils/beacon/useOwnLiveBeacons.ts
  test/components/views/beacon/LeftPanelLiveShareWarning-test.tsx
  test/stores/OwnBeaconStore-test.ts
Labels: T-Task

#8419 correctly align read receipts to state events in bubble layout
  res/css/views/rooms/_EventBubbleTile.scss
Labels: T-Defect

#8439 Live location sharing: increase geolocation timeout options
  src/utils/beacon/geolocation.ts
  test/utils/beacon/geolocation-test.ts
Labels: T-Task

#8429 Disable the message action bar when hovering over the 1px border between threads on the list
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#8391 Fix event text overflow on bubble message layout
  res/css/views/rooms/_EventBubbleTile.scss
Labels: T-Defect

#8417 Fix issue with thread notification state ignoring initial events
  src/components/views/rooms/EventTile.tsx
  src/stores/notifications/ThreadNotificationState.ts
Labels: T-Defect

#8443 Live location sharing: fix safari timestamps pt 2
  src/utils/beacon/geolocation.ts
  test/stores/OwnBeaconStore-test.ts
  test/utils/beacon/geolocation-test.ts
Labels: T-Defect

#8377 Patch: "Reloading the registration page should warn about data loss"
  src/components/structures/auth/Registration.tsx
Labels: T-Defect

#8430 Consolidate deployment management into more maintained action
  .github/workflows/element-build-and-test.yaml
  .github/workflows/end-to-end-tests.yaml
  .github/workflows/netlify.yaml
  .github/workflows/static_analysis.yaml
  .github/workflows/tests.yml
  scripts/fetchdep.sh
Labels: T-Task

#8337 Implement improved spacing for the thread list and timeline
  res/css/_common.scss
  res/css/views/right_panel/_ThreadPanel.scss
  res/css/views/right_panel/_TimelineCard.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_ThreadSummary.scss
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/ThreadSummary.tsx
Labels: T-Enhancement

#8423 LLS: display beacon tiles in timeline regardless of labs flag
  src/events/EventTileFactory.tsx
Labels: T-Task

#8451 Add pointer if you hover over location map
  res/css/views/messages/_MLocationBody.scss
Labels: T-Enhancement

#8350 Fixes "space panel kebab menu is rendered out of view on sub spaces"
  res/css/structures/_SpacePanel.scss
Labels: T-Defect
