Repository matrix-org/matrix-react-sdk, pull requests merged in 2022-03, with the labels that each got.

#7918 Fix positioning of the thread context menu
  src/components/structures/ContextMenu.tsx
  src/components/views/context_menus/ThreadListContextMenu.tsx
Labels: T-Defect

#7915 Ensure EventListSummary key does not change during backpagination
  src/components/structures/MessagePanel.tsx
  test/components/structures/MessagePanel-test.js
Labels: T-Defect

#7910 Fix changing space sometimes bouncing to the wrong space
  src/stores/room-list/SpaceWatcher.ts
  src/stores/spaces/SpaceStore.ts
  test/stores/SpaceStore-test.ts
  test/test-utils/test-utils.ts
Labels: T-Defect

#7916 Wrap all EventTiles with a TileErrorBoundary and guard parsePermalink
  src/components/structures/MessagePanel.tsx
  src/components/views/rooms/EventTile.tsx
  src/utils/permalinks/Permalinks.ts
Labels: T-Defect

#7917 fix color of location share caret
  res/css/views/location/_LocationPicker.scss
  res/css/views/messages/_MLocationBody.scss
  src/components/views/location/LocationPicker.tsx
  src/components/views/messages/MLocationBody.tsx
Labels: T-Defect

#7923 Fix right panel soft crashes due to missing room prop
  res/css/structures/_GroupView.scss
  src/components/structures/MatrixChat.tsx
  src/components/structures/RightPanel.tsx
  src/components/structures/ThreadView.tsx
  src/stores/right-panel/RightPanelStore.ts
  src/stores/right-panel/RightPanelStorePhases.ts
Labels: X-Release-Blocker, T-Defect

#7927 Fix right panel soft crashes due to missing room prop
  res/css/structures/_GroupView.scss
  src/components/structures/MatrixChat.tsx
  src/components/structures/RightPanel.tsx
  src/components/structures/ThreadView.tsx
  src/stores/right-panel/RightPanelStore.ts
  src/stores/right-panel/RightPanelStorePhases.ts
Labels: T-Defect

#7926 Add end-to-end test for the user view
  test/end-to-end-tests/src/scenario.ts
  test/end-to-end-tests/src/scenarios/user-view.ts
Labels: T-Task

#7931 Fix backspace not working in the invite dialog
  src/components/views/dialogs/InviteDialog.tsx
Labels: T-Defect

#7599 Expose redaction power level in room settings
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7905 Add support for redirecting to external pages after logout
  src/@types/global.d.ts
  src/Lifecycle.ts
  src/SdkConfig.ts
  test/end-to-end-tests/Windows.md
  test/end-to-end-tests/src/scenario.ts
  test/end-to-end-tests/src/scenarios/sso-customisations.ts
  test/end-to-end-tests/src/usecases/logout.ts
  test/end-to-end-tests/src/util.ts
  test/end-to-end-tests/start.ts
Labels: Sponsored, T-Enhancement

#7886 Add support for overriding strings in the app
  src/SdkConfig.ts
  src/languageHandler.tsx
  test/languageHandler-test.ts
Labels: Sponsored, T-Enhancement

#7933 Mandate use of js-sdk/src/matrix import over js-sdk/src
  .eslintrc.js
  src/AddThreepid.ts
  src/ContentMessages.tsx
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/structures/UploadBar.tsx
  src/components/views/context_menus/ThreadListContextMenu.tsx
  src/components/views/dialogs/ExportDialog.tsx
  src/components/views/messages/DownloadActionButton.tsx
  src/components/views/messages/MKeyVerificationRequest.tsx
  src/components/views/messages/UnknownBody.tsx
  src/components/views/messages/ViewSourceEvent.tsx
  src/components/views/rooms/RoomDetailList.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/settings/CrossSigningPanel.tsx
  src/index.ts
  src/indexing/BaseEventIndexManager.ts
  src/models/IUpload.ts
  src/sendTimePerformanceMetrics.ts
  src/stores/ActiveWidgetStore.ts
  src/stores/AutoRageshakeStore.ts
  src/utils/MediaEventHelper.ts
  test/CallHandler-test.ts
  test/DecryptionFailureTracker-test.js
  test/DeviceListener-test.ts
  test/Terms-test.js
  test/TextForEvent-test.ts
  test/components/structures/CallEventGrouper-test.ts
  test/components/structures/GroupView-test.js
  test/components/structures/MessagePanel-test.js
  test/components/structures/ThreadPanel-test.tsx
  test/components/views/context_menus/SpaceContextMenu-test.tsx
  test/components/views/dialogs/ExportDialog-test.tsx
  test/components/views/groups/GroupMemberList-test.js
  test/components/views/messages/MKeyVerificationConclusion-test.js
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/RoomList-test.js
  test/components/views/rooms/RoomPreviewBar-test.tsx
  test/components/views/settings/CryptographyPanel-test.tsx
  test/components/views/settings/Notifications-test.tsx
  test/components/views/spaces/SpacePanel-test.tsx
  test/components/views/spaces/SpaceSettingsVisibilityTab-test.tsx
  test/stores/VoiceRecordingStore-test.ts
  test/stores/WidgetLayoutStore-test.ts
  test/stores/room-list/previews/PollStartEventPreview-test.ts
  test/test-utils/test-utils.ts
  test/test-utils/threads.ts
  test/test-utils/wrappers.tsx
  test/utils/export-test.tsx
Labels: T-Defect

#7938 Fix js-sdk imports
  src/components/views/location/LocationShareMenu.tsx
  test/components/views/location/LocationShareMenu-test.tsx
Labels: T-Task

#7936 Fix ExportDialog title on export cancellation
  src/components/views/dialogs/ExportDialog.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7928 Load icons using @svgr
  docs/icons.md
  res/css/structures/_QuickSettingsButton.scss
  src/@types/svg.d.ts
  src/components/views/spaces/QuickSettingsButton.tsx
Labels: T-Task

#7940 remove code related to encrypted file download button in iframe
  res/css/views/messages/_MFileBody.scss
  src/components/views/messages/MFileBody.tsx
  src/i18n/strings/en_EN.json
  src/utils/FileDownloader.ts
Labels: T-Task

#7941 Jest mock for svgr icons
  __mocks__/svg.js
  package.json
Labels: T-Task

#7924 Location share type UI
  __mocks__/maplibre-gl.js
  res/css/_components.scss
  res/css/components/views/location/_ShareType.scss
  res/img/element-icons/location.svg
  res/img/location/live-location.svg
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light/css/_light.scss
  src/components/views/location/LocationShareMenu.tsx
  src/components/views/location/ShareType.tsx
  src/components/views/location/shareLocation.ts
  src/i18n/strings/en_EN.json
  test/components/views/location/LocationShareMenu-test.tsx
  test/components/views/location/__snapshots__/LocationShareMenu-test.tsx.snap
Labels: T-Enhancement

#7942 Prevent event tiles being shrunk/collapsed by flexbox
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#7944 Consider polls as message events for rendering redactions
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#7943 Fix sending locations into threads and fix i18n
  src/components/views/location/LocationButton.tsx
  src/components/views/location/LocationPicker.tsx
  src/components/views/location/LocationShareMenu.tsx
  src/components/views/location/shareLocation.ts
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7946 Fix react warnings
  src/components/views/avatars/MemberAvatar.tsx
  src/components/views/settings/CryptographyPanel.tsx
Labels: T-Task

#7947 Add logging to diagnose non-disappearing toasts
  src/DeviceListener.ts
Labels: T-Task

#7951 Make "Match system" on QuickThemeSwitcher.tsx translatable
  src/components/views/spaces/QuickThemeSwitcher.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7950 Autofocus correct composer after sending reaction
  src/components/structures/RoomView.tsx
  src/components/views/emojipicker/ReactionPicker.tsx
  src/dispatcher/actions.ts
  src/dispatcher/payloads/FocusComposerPayload.ts
Labels: T-Defect

#7949 Improve accessibility of the BetaPill
  res/css/views/beta/_BetaCard.scss
  src/components/views/beta/BetaCard.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7952 Fix duplicate EventListSummarys
  src/components/structures/MessagePanel.tsx
  test/components/structures/MessagePanel-test.js
Labels: T-Defect

#7920 Make pinned messages more reliably reflect edits
  src/components/views/right_panel/PinnedMessagesCard.tsx
Labels: T-Defect

#7937 Add a few more UIComponent flags, and ensure they are used in existing code
  src/SlashCommands.tsx
  src/components/structures/LeftPanel.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/NewRoomIntro.tsx
  src/components/views/rooms/RoomListHeader.tsx
  src/settings/UIFeature.ts
  src/utils/space.tsx
Labels: Sponsored, T-Enhancement

#7939 Fix room list being laggy while scrolling 🐌
  src/components/views/elements/Tooltip.tsx
  src/components/views/elements/TooltipTarget.tsx
  test/components/views/elements/TooltipTarget-test.tsx
  test/components/views/elements/__snapshots__/TooltipTarget-test.tsx.snap
Labels: T-Defect

#7965 use LocationAssetType
  res/css/views/messages/_MLocationBody.scss
  src/components/views/messages/MLocationBody.tsx
  test/components/views/messages/MLocationBody-test.tsx
Labels: T-Enhancement

#7958 Location sharing > back button
  res/css/_components.scss
  res/css/components/views/location/_ShareDialogButtons.scss
  res/css/views/location/_LocationPicker.scss
  res/img/element-icons/cancel-rounded.svg
  res/img/element-icons/caret-left.svg
  src/components/views/location/LocationPicker.tsx
  src/components/views/location/LocationShareMenu.tsx
  src/components/views/location/ShareDialogButtons.tsx
  test/components/views/location/LocationShareMenu-test.tsx
Labels: T-Enhancement

#7961 Avoid using .render() in forward dialog test
  test/components/views/dialogs/ForwardDialog-test.js
Labels: T-Task

#7921 Hide unpinnable pinned messages in more cases
  src/components/views/right_panel/PinnedMessagesCard.tsx
  test/components/views/right_panel/PinnedMessagesCard-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Defect

#7959 Improve end-to-end test logging by rendering JSHandles
  test/end-to-end-tests/src/session.ts
  test/end-to-end-tests/src/util.ts
  test/end-to-end-tests/start.ts
Labels: T-Task

#7969 Revert "replace all require(.svg) with esm import"
  .eslintrc.js
  src/SdkConfig.ts
  src/components/structures/FileDropTarget.tsx
  src/components/structures/GroupView.js
  src/components/structures/MyGroups.js
  src/components/structures/RoomStatusBar.tsx
  src/components/structures/UserMenu.tsx
  src/components/views/avatars/WidgetAvatar.tsx
  src/components/views/context_menus/GroupInviteTileContextMenu.js
  src/components/views/dialogs/AddExistingToSpaceDialog.tsx
  src/components/views/dialogs/CreateSpaceFromCommunityDialog.tsx
  src/components/views/dialogs/ForwardDialog.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/dialogs/ModalWidgetDialog.tsx
  src/components/views/dialogs/UploadConfirmDialog.tsx
  src/components/views/dialogs/security/SetupEncryptionDialog.tsx
  src/components/views/elements/AddressTile.tsx
  src/components/views/elements/AppWarning.tsx
  src/components/views/elements/SSOButtons.tsx
  src/components/views/groups/GroupMemberList.js
  src/components/views/groups/GroupRoomInfo.js
  src/components/views/groups/GroupRoomList.js
  src/components/views/messages/MAudioBody.tsx
  src/components/views/messages/MFileBody.tsx
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MStickerBody.tsx
  src/components/views/messages/MVideoBody.tsx
  src/components/views/messages/MVoiceMessageBody.tsx
  src/components/views/right_panel/EncryptionPanel.tsx
  src/components/views/rooms/EntityTile.tsx
  src/components/views/rooms/LinkPreviewGroup.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/ReplyPreview.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
Labels: T-Defect

#7971 Fix bug with some space selections not being applied
  src/stores/room-list/SpaceWatcher.ts
  src/stores/spaces/SpaceStore.ts
  test/stores/SpaceStore-test.ts
Labels: T-Defect

#7953 Fix account & room settings race condition
  src/settings/handlers/AccountSettingsHandler.ts
  src/settings/handlers/LocalEchoWrapper.ts
  src/settings/handlers/MatrixClientBackedSettingsHandler.ts
  src/settings/handlers/RoomAccountSettingsHandler.ts
  src/settings/handlers/RoomSettingsHandler.ts
  test/test-utils/test-utils.ts
Labels: T-Defect

#6711 Make trailing `:` into a setting
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/editor/parts.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/handlers/AccountSettingsHandler.ts
Labels: T-Enhancement

#7973 Fix wrongly asserting that PushRule::conditions is non-null
  src/RoomNotifs.ts
  test/RoomNotifs-test.ts
  test/test-utils/test-utils.ts
Labels: T-Defect

#7974 Fix location map attribution rendering over message action bar
  res/css/views/messages/_MLocationBody.scss
Labels: T-Defect

#7908 Document keyboard shortcuts
  docs/features/keyboardShortcuts.md
  src/KeyBindingsDefaults.ts
  src/accessibility/KeyboardShortcuts.ts
  src/components/views/settings/tabs/user/KeyboardUserSettingsTab.tsx
  test/accessibility/KeyboardShortcuts-test.ts
  test/components/views/settings/tabs/user/KeyboardUserSettingsTab-test.tsx
Labels: T-Task

#7977 Fix bad ternary statement in autocomplete user pill insertions
  src/editor/parts.ts
Labels: T-Defect

#7922 Allow pinning polls
  src/components/views/rooms/PinnedEventTile.tsx
  src/utils/PinningUtils.ts
Labels: T-Enhancement

#7981 Rename `MessageComposerInput.insertTrailingComma` to `MessageComposerInput.insertTrailingColon`
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/editor/parts.ts
  src/settings/Settings.tsx
  src/settings/handlers/AccountSettingsHandler.ts
Labels: T-Task

#7975 Hide composer and call buttons when the room is tombstoned
  src/components/structures/RoomView.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/contexts/RoomContext.ts
  test/components/structures/MessagePanel-test.js
  test/components/views/rooms/MessageComposer-test.tsx
  test/components/views/rooms/MessageComposerButtons-test.tsx
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Defect

#7986 Pass room to getRoomTombstone to avoid racing with setState
  src/components/structures/RoomView.tsx
Labels: X-Release-Blocker, T-Defect

#7972 Add unexposed account setting for hiding poll creation
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/views/rooms/MessageComposerButtons-test.tsx
Labels: Sponsored, T-Enhancement

#7988 More pinned messages tests
  test/components/views/right_panel/PinnedMessagesCard-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Task

#7989 Fix missing summary text for pinned message changes
  src/components/views/elements/EventListSummary.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7999 Fix room account settings
  src/settings/handlers/RoomAccountSettingsHandler.ts
Labels: T-Defect

#7984 Add another null guard for member
  src/components/views/messages/SenderProfile.tsx
Labels: T-Defect

#7990 Fix formatting not being applied after links
  src/Markdown.ts
  test/Markdown-test.ts
Labels: T-Defect

#7995 Normalized shortcut formatting for quote expansion control
  src/components/views/messages/MessageActionBar.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7945 Wrap EventTile rather than its children in an error boundary
  src/components/structures/MessagePanel.tsx
  src/components/views/rooms/EventTile.tsx
  test/components/structures/MessagePanel-test.js
Labels: T-Defect

#8007 Add lint for unused locals
  src/ActiveRoomObserver.ts
  src/Analytics.tsx
  src/CallHandler.tsx
  src/PasswordReset.ts
  src/audio/PlaybackQueue.ts
  src/components/structures/InteractiveAuth.tsx
  src/components/structures/LoggedInView.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomDirectory.tsx
  src/components/structures/RoomView.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/dialogs/LogoutDialog.tsx
  src/components/views/settings/Notifications.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/components/views/voip/CallViewForRoom.tsx
  src/notifications/VectorPushRulesDefinitions.ts
  src/stores/notifications/ListNotificationState.ts
  src/stores/notifications/RoomNotificationStateStore.ts
  src/stores/notifications/SpaceNotificationState.ts
  src/stores/room-list/RoomListStore.ts
  src/stores/spaces/SpaceStore.ts
  src/stores/widgets/StopGapWidget.ts
  tsconfig.json
Labels: T-Task

#8004 Fix a variety of issues with HTML → Markdown conversion
  src/editor/deserialize.ts
  test/editor/__snapshots__/deserialize-test.js.snap
  test/editor/deserialize-test.js
Labels: T-Defect

#8000 include test/test-utils in tsconfig
  test/test-utils/test-utils.ts
  test/test-utils/wrappers.tsx
  tsconfig.json
Labels: T-Task

#7979 Update m.render_in to is_falling_back (+ unstable field)
  src/@types/common.ts
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/utils/Reply.ts
Labels: T-Task

#7991 Fix room list scroll jumps
  res/css/views/rooms/_RoomSublist.scss
  src/components/views/rooms/RoomSublist.tsx
Labels: T-Defect

#8010 Fix button border color of LeaveSpaceDialog
  res/css/views/dialogs/_LeaveSpaceDialog.scss
  src/components/views/dialogs/LeaveSpaceDialog.tsx
Labels: T-Defect

#8015 Fix issues with thread summaries being wrong or stale
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/ThreadSummary.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#8009 Add test coverage reporting
  .github/codecov.yml
  .github/workflows/test_coverage.yml
  package.json
Labels: T-Task

#8017 Fix alignment of polls within threads
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#8014 Don't escape pasted text
  src/components/views/rooms/BasicMessageComposer.tsx
  src/editor/deserialize.ts
Labels: T-Defect

#8018 Fix issues with ThreadSummary in msc-enabled mode
  src/components/views/rooms/ThreadSummary.tsx
Labels: T-Defect

#8021 Attempt to disable the codecov patch behaviour
  .github/codecov.yml
Labels: T-Task

#8016 Fix incorrect usage of unstable variant of `is_falling_back`
  src/components/views/elements/ReplyChain.tsx
  src/utils/Reply.ts
Labels: T-Defect

#8022 update location event types
  src/Notifier.ts
  src/TextForEvent.tsx
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/location/shareLocation.ts
  src/components/views/messages/MLocationBody.tsx
  src/components/views/messages/MessageEvent.tsx
  src/utils/EventUtils.ts
  test/components/views/location/LocationShareMenu-test.tsx
  test/components/views/messages/MLocationBody-test.tsx
Labels: T-Task

#8025 Paginate responses to pinned polls
  src/components/views/rooms/PinnedEventTile.tsx
  test/components/views/right_panel/PinnedMessagesCard-test.tsx
Labels: T-Defect

#8024 include test/utils in tsconfig
  test/utils/export-test.tsx
  tsconfig.json
Labels: T-Task

#7982 fallback to event text in location body when map unavailable
  res/css/_components.scss
  res/css/components/views/location/_MapError.scss
  res/css/views/location/_LocationPicker.scss
  src/components/views/location/LocationPicker.tsx
  src/components/views/location/LocationShareErrors.ts
  src/components/views/location/MapError.tsx
  src/components/views/location/findMapStyleUrl.ts
  src/components/views/messages/MLocationBody.tsx
  src/i18n/strings/en_EN.json
  test/components/views/location/LocationPicker-test.tsx
  test/components/views/location/LocationShareMenu-test.tsx
  test/components/views/location/MapError-test.tsx
  test/components/views/location/__snapshots__/MapError-test.tsx.snap
  test/components/views/messages/MLocationBody-test.tsx
  test/components/views/messages/__snapshots__/MLocationBody-test.tsx.snap
Labels: T-Enhancement

#8031 Share shared history keys in the background
  src/utils/MultiInviter.ts
Labels: T-Defect

#7980 Tweak search dialog based on new designs
  res/css/views/dialogs/_SpotlightDialog.scss
  src/components/views/dialogs/SpotlightDialog.tsx
Labels: T-Enhancement

#8033 Include PR_NUMBER so codecov build can do branch matching
  .github/workflows/test_coverage.yml
Labels: T-Task

#8034 Add some doc to the github actions / CI scripts
  .github/workflows/end-to-end-tests.yaml
  .github/workflows/layered-build.yaml
  .github/workflows/netlify.yaml
  .github/workflows/test_coverage.yml
  .github/workflows/typecheck.yaml
  scripts/ci/Dockerfile
  scripts/ci/install-deps.sh
  scripts/ci/layered.sh
Labels: T-Task

#8035 Fix regression around replying to search results
  src/components/structures/RoomView.tsx
  src/stores/RoomViewStore.tsx
Labels: T-Defect

#8026 include /test/stores in tsconfig
  test/stores/SpaceStore-test.ts
  test/stores/notifications/RoomNotificationState-test.ts
  test/stores/room-list/SpaceWatcher-test.ts
  test/stores/room-list/filters/SpaceFilterCondition-test.ts
  test/stores/room-list/previews/PollStartEventPreview-test.ts
  test/test-utils/test-utils.ts
  tsconfig.json
Labels: T-Task

#8028 Fix logging in end-to-end tests
  test/end-to-end-tests/src/session.ts
  test/end-to-end-tests/src/util.ts
Labels: T-Task

#8038 Fix clicking on copy link to thread wrongly opening thread
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#8041 Fixed a minor typo
  src/Unread.ts
Labels: T-Task

#8036 Show displayname in non-narrow thread summeries
  res/css/views/rooms/_EventTile.scss
  res/img/compound/chevron-right-12px.svg
  src/components/views/rooms/ThreadSummary.tsx
Labels: T-Enhancement

#8047 Fix buttons alignment of Space list header
  res/css/structures/_SpaceHierarchy.scss
  src/components/structures/SpaceHierarchy.tsx
Labels: T-Defect

#8048 Fix the header of Space landing page
  res/css/structures/_SpaceRoomView.scss
  res/css/views/spaces/_SpaceCreateMenu.scss
  src/components/structures/SpaceRoomView.tsx
Labels: T-Defect

#7978 Reuse a common part of the translation
  src/components/views/elements/ErrorBoundary.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#8043 Support MSC3026 busy presence
  res/css/views/avatars/_DecoratedRoomAvatar.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light/css/_light.scss
  src/components/views/avatars/DecoratedRoomAvatar.tsx
  src/components/views/rooms/PresenceLabel.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#8050 Further attempt to prevent codecov posting failure messages
  .github/codecov.yml
  .github/workflows/test_coverage.yml
Labels: T-Task

#8042 Keybinding code unification #6
  src/KeyBindingsDefaults.ts
  src/accessibility/KeyboardShortcutUtils.ts
  src/accessibility/KeyboardShortcuts.ts
  src/components/views/settings/KeyboardShortcut.tsx
  src/components/views/settings/tabs/user/KeyboardUserSettingsTab.tsx
  test/accessibility/KeyboardShortcutUtils-test.ts
  test/components/views/settings/KeyboardShortcut-test.tsx
  test/components/views/settings/__snapshots__/KeyboardShortcut-test.tsx.snap
  test/components/views/settings/tabs/user/KeyboardUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/KeyboardUserSettingsTab-test.tsx.snap
Labels: T-Task

#8044 Remove left panel widgets
  res/css/_components.scss
  res/css/structures/_LeftPanelWidget.scss
  src/components/structures/LeftPanel.tsx
  src/components/structures/LeftPanelWidget.tsx
  src/settings/Settings.tsx
Labels: T-Task

#8053 fix more type issues in unit tests
  test/components/structures/CallEventGrouper-test.ts
  test/components/structures/auth/Login-test.tsx
  test/components/views/context_menus/ContextMenu-test.tsx
  tsconfig.json
Labels: T-Task

#8052 Don't assume that widget IDs are unique
  src/CallHandler.tsx
  src/components/views/context_menus/WidgetContextMenu.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/elements/PersistentApp.tsx
  src/components/views/rooms/Stickerpicker.tsx
  src/components/views/voip/PipView.tsx
  src/stores/ActiveWidgetStore.ts
  src/stores/ModalWidgetStore.ts
  src/stores/WidgetStore.ts
  src/stores/widgets/StopGapWidget.ts
  src/stores/widgets/WidgetMessagingStore.ts
  src/utils/WidgetUtils.ts
  test/components/views/elements/AppTile-test.tsx
Labels: T-Defect

#8058 Fix freeze/crash when 1:1 calling
  src/components/views/voip/AudioFeed.tsx
  src/components/views/voip/VideoFeed.tsx
Labels: T-Defect

#8059 Merge pull request from GHSA-qmf4-7w7j-vf23
  src/components/structures/ThreadPanel.tsx
  src/components/structures/ThreadView.tsx
  src/components/views/right_panel/TimelineCard.tsx
  src/contexts/RoomContext.ts
Labels: T-Defect

#8056 Enable the live location share button
  src/components/views/location/ShareType.tsx
  test/components/views/location/LocationShareMenu-test.tsx
  test/test-utils/utilities.ts
Labels: T-Task

#7104 Improve formatting features in the editor
  src/accessibility/KeyboardShortcuts.ts
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/rooms/MessageComposerFormatBar.tsx
  src/editor/operations.ts
  src/editor/range.ts
  src/i18n/strings/en_EN.json
  test/editor/operations-test.js
  test/editor/range-test.js
Labels: T-Enhancement

#8063 Make margin and padding of mx_InviteDialog_other consistent
  res/css/views/dialogs/_InviteDialog.scss
Labels: T-Defect

#8064 Add test utils for Beacons
  test/test-utils/beacon.ts
  test/test-utils/client.ts
Labels: T-Task

#8061 Live beacons: track users live beacons
  src/stores/OwnBeaconStore.ts
  test/stores/OwnBeaconStore-test.ts
  test/test-utils/index.ts
Labels: T-Task

#8066 Add simple live share warning
  res/css/_components.scss
  res/css/components/views/beacon/_LeftPanelLiveShareWarning.scss
  res/css/structures/_LeftPanel.scss
  res/css/structures/_MatrixChat.scss
  src/components/structures/LoggedInView.tsx
  src/components/views/beacon/LeftPanelLiveShareWarning.tsx
  src/i18n/strings/en_EN.json
  test/components/views/beacon/LeftPanelLiveShareWarning-test.tsx
  test/components/views/beacon/__snapshots__/LeftPanelLiveShareWarning-test.tsx.snap
Labels: T-Enhancement

#8068 enable geolocation behaviour in location picker for live share type
  res/css/components/views/location/_ShareType.scss
  res/css/views/location/_LocationPicker.scss
  src/components/views/location/LocationPicker.tsx
  src/components/views/location/ShareType.tsx
  test/components/views/location/LocationPicker-test.tsx
Labels: T-Enhancement

#8077 fix ts issues in SendMessageComposer-test
  src/components/views/rooms/SendMessageComposer.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  tsconfig.json
Labels: T-Task

#8075 kill beacons on expiry
  src/stores/OwnBeaconStore.ts
  test/stores/OwnBeaconStore-test.ts
Labels: T-Enhancement

#8062 Use & enforce snake_case naming convention on config.json settings
  docs/settings.md
  src/@types/common.ts
  src/@types/global.d.ts
  src/Analytics.tsx
  src/BasePlatform.ts
  src/CallHandler.tsx
  src/IConfigOptions.ts
  src/KeyBindingsDefaults.ts
  src/Livestream.ts
  src/PosthogAnalytics.ts
  src/ScalarAuthClient.ts
  src/SdkConfig.ts
  src/components/structures/HomePage.tsx
  src/components/structures/HostSignupAction.tsx
  src/components/structures/LoggedInView.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomDirectory.tsx
  src/components/structures/UserMenu.tsx
  src/components/structures/auth/Login.tsx
  src/components/views/auth/CountryDropdown.tsx
  src/components/views/auth/LanguageSelector.tsx
  src/components/views/auth/PassphraseField.tsx
  src/components/views/auth/Welcome.tsx
  src/components/views/dialogs/AnalyticsLearnMoreDialog.tsx
  src/components/views/dialogs/CommunityPrototypeInviteDialog.tsx
  src/components/views/dialogs/CreateRoomDialog.tsx
  src/components/views/dialogs/HostSignupDialog.tsx
  src/components/views/dialogs/HostSignupDialogTypes.ts
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/dialogs/ReportEventDialog.tsx
  src/components/views/dialogs/ServerPickerDialog.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/directory/NetworkDropdown.tsx
  src/components/views/elements/DesktopBuildsNotice.tsx
  src/components/views/elements/ServerPicker.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/components/views/settings/tabs/user/KeyboardUserSettingsTab.tsx
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
  src/editor/serialize.ts
  src/integrations/IntegrationManagers.ts
  src/sentry.ts
  src/settings/handlers/ConfigSettingsHandler.ts
  src/toasts/AnalyticsToast.tsx
  src/utils/AutoDiscoveryUtils.tsx
  src/utils/IdentityServerUtils.ts
  src/utils/SnakedObject.ts
  src/utils/pages.ts
  src/utils/permalinks/Permalinks.ts
  src/utils/presence.ts
  src/widgets/Jitsi.ts
  test/PosthogAnalytics-test.ts
  test/components/structures/auth/Login-test.tsx
  test/components/structures/auth/Registration-test.js
  test/utils/SnakedObject-test.ts
Labels: T-Task

#8076 Remove padding of InviteDialog & fix visual regression
  res/css/views/dialogs/_InviteDialog.scss
Labels: T-Defect

#8078 Fix tsc issues in right_panel and room component tests
  test/components/views/right_panel/PinnedMessagesCard-test.tsx
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/rooms/MemberList-test.tsx
  test/components/views/rooms/MessageComposer-test.tsx
  test/components/views/rooms/MessageComposerButtons-test.tsx
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/SearchResultTile-test.tsx
  test/test-utils/test-utils.ts
  tsconfig.json
Labels: T-Task

#8095 Triple the speed of E2E tests and stop them exploding if a circular datastructure is logged
  test/end-to-end-tests/README.md
  test/end-to-end-tests/src/logger.ts
  test/end-to-end-tests/src/session.ts
  test/end-to-end-tests/src/usecases/create-space.ts
  test/end-to-end-tests/src/usecases/rightpanel.ts
  test/end-to-end-tests/src/usecases/room-settings.ts
  test/end-to-end-tests/src/util.ts
Labels: T-Task

#8094 fix ugly warning from nesting div tags in p tags
  src/components/views/right_panel/UserInfo.tsx
Labels: T-Task

#8020 Allow sending files as replies as per MSC3676
  src/ContentMessages.ts
  src/components/views/rooms/SendMessageComposer.tsx
  src/i18n/strings/en_EN.json
  src/utils/Reply.ts
Labels: T-Enhancement

#8090 Don't restore MemberInfo from RightPanel history when viewing a room
  src/stores/right-panel/RightPanelStore.ts
Labels: T-Enhancement

#8105 Fix emoting with emoji or pills
  src/SlashCommands.tsx
  src/editor/serialize.ts
  test/components/views/rooms/SendMessageComposer-test.tsx
Labels: T-Defect

#8106 Revert "Pin end-to-end test Python dependencies"
  test/end-to-end-tests/element/install-webserver.sh
  test/end-to-end-tests/synapse/install.sh
Labels: T-Task

#8107 Revert "Use styled mxids in member list"
  res/css/_components.scss
  res/css/structures/_FilePanel.scss
  res/css/structures/_NotificationPanel.scss
  res/css/views/messages/_SenderProfile.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_GroupLayout.scss
  res/css/views/rooms/_IRCLayout.scss
  src/components/views/messages/DisambiguatedProfile.tsx
  src/components/views/messages/SenderProfile.tsx
  src/components/views/rooms/EntityTile.tsx
  src/components/views/rooms/MemberTile.tsx
  test/end-to-end-tests/src/usecases/timeline.ts
Labels: T-Task

#8111 Fix scroll behaviour in space panel
  res/css/structures/_LeftPanel.scss
Labels: X-Release-Blocker, T-Defect

#8101 add helpers for beacon duration calculations
  src/utils/beacon/duration.ts
  src/utils/beacon/index.ts
  test/stores/OwnBeaconStore-test.ts
  test/test-utils/beacon.ts
  test/utils/beacon/duration-test.ts
Labels: T-Task

#8108 fix quicktime video thumbnailing
  src/ContentMessages.ts
  src/components/views/messages/MVideoBody.tsx
Labels: T-Defect

#8100 Live location sharing: live share warning in room
  res/css/_components.scss
  res/css/components/views/beacon/_RoomLiveShareWarning.scss
  src/components/views/beacon/RoomLiveShareWarning.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/i18n/strings/en_EN.json
  src/stores/OwnBeaconStore.ts
  test/components/views/beacon/RoomLiveShareWarning-test.tsx
  test/components/views/beacon/StyledLiveBeaconIcon-test.tsx
  test/components/views/beacon/__snapshots__/RoomLiveShareWarning-test.tsx.snap
  test/stores/OwnBeaconStore-test.ts
  test/test-utils/beacon.ts
Labels: T-Enhancement

#8084 Voice rooms prototype
  res/css/_components.scss
  res/css/structures/_RoomView.scss
  res/css/views/elements/_FacePile.scss
  res/css/views/right_panel/_UserInfo.scss
  res/css/views/rooms/_MemberInfo.scss
  res/css/views/rooms/_RoomTile.scss
  res/css/views/voip/_VoiceChannelRadio.scss
  res/img/voip/signal-bars.svg
  res/img/voip/voice-room.svg
  src/CallHandler.tsx
  src/components/structures/LeftPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/views/dialogs/CreateRoomDialog.tsx
  src/components/views/elements/FacePile.tsx
  src/components/views/groups/GroupInviteTile.js
  src/components/views/rooms/ExtraTile.tsx
  src/components/views/rooms/RoomTile.tsx
  src/components/views/voip/VoiceChannelRadio.tsx
  src/contexts/RoomContext.ts
  src/createRoom.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/VoiceChannelStore.ts
  src/stores/widgets/ElementWidgetActions.ts
  src/utils/VoiceChannelUtils.ts
  src/utils/WidgetUtils.ts
  test/components/views/rooms/RoomTile-test.tsx
  test/components/views/voip/VoiceChannelRadio-test.tsx
  test/end-to-end-tests/src/usecases/accept-invite.ts
  test/end-to-end-tests/src/usecases/select-room.ts
  test/test-utils/test-utils.ts
Labels: X-Blocked, T-Enhancement

#8110 Use styled mxids in member list v2
  res/css/_components.scss
  res/css/structures/_FilePanel.scss
  res/css/structures/_NotificationPanel.scss
  res/css/views/messages/_DisambiguatedProfile.scss
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_GroupLayout.scss
  res/css/views/rooms/_IRCLayout.scss
  src/components/views/messages/DisambiguatedProfile.tsx
  src/components/views/messages/SenderProfile.tsx
  src/components/views/rooms/EntityTile.tsx
  src/components/views/rooms/MemberTile.tsx
  test/end-to-end-tests/src/usecases/timeline.ts
Labels: T-Enhancement

#8102 Make video sizing consistent with images
  res/css/views/messages/_MVideoBody.scss
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MVideoBody.tsx
  src/settings/enums/ImageSize.ts
  test/settings/enums/ImageSize-test.ts
Labels: T-Defect

#8121 Make sure to use `mx_DisambiguatedProfile` everywhere
  res/css/views/right_panel/_TimelineCard.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_ReplyTile.scss
Labels: T-Defect

#8116 Live location sharing - refresh beacon expiry in room
  src/components/views/beacon/RoomLiveShareWarning.tsx
  src/i18n/strings/en_EN.json
  test/components/views/beacon/RoomLiveShareWarning-test.tsx
  test/components/views/beacon/__snapshots__/RoomLiveShareWarning-test.tsx.snap
Labels: T-Enhancement

#8119 Include /test in tsc config, fix rest of issues
  src/PosthogAnalytics.ts
  test/CallHandler-test.ts
  test/PosthogAnalytics-test.ts
  test/RoomNotifs-test.ts
  test/accessibility/KeyboardShortcutUtils-test.ts
  test/accessibility/RovingTabIndex-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  tsconfig.json
Labels: T-Task

#8115 When showing thread, always auto-focus its composer
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/dispatcher/dispatch-actions/threads.ts
Labels: T-Enhancement

#8122 Remove unused component: SimpleRoomHeader
  res/css/views/rooms/_RoomHeader.scss
  src/components/views/rooms/SimpleRoomHeader.tsx
Labels: T-Task

#8113 Fix issue with falsey hrefs being sent in events
  src/HtmlUtils.tsx
  src/linkify-matrix.ts
Labels: T-Defect

#8074 Replace "Element" with a brand const
  src/components/views/dialogs/AnalyticsLearnMoreDialog.tsx
  src/components/views/elements/ServerPicker.tsx
  src/components/views/location/LocationPicker.tsx
  src/i18n/strings/en_EN.json
  src/toasts/MobileGuideToast.ts
Labels: T-Task

#7286 Upgrade `emojibase` and `twemoji`
  package.json
  res/fonts/Twemoji_Mozilla/TwemojiMozilla-colr.woff2
  res/fonts/Twemoji_Mozilla/TwemojiMozilla-sbix.woff2
  src/autocomplete/EmojiProvider.tsx
  src/components/views/emojipicker/EmojiPicker.tsx
  src/components/views/emojipicker/Preview.tsx
  src/components/views/emojipicker/QuickReactions.tsx
  src/emoji.ts
  yarn.lock
Labels: T-Task

#8126 Live location sharing: geolocation utilities
  src/components/views/location/LocationPicker.tsx
  src/utils/beacon/geolocation.ts
  src/utils/beacon/index.ts
  test/components/views/location/LocationPicker-test.tsx
  test/test-utils/beacon.ts
  test/utils/beacon/geolocation-test.ts
Labels: T-Task

#8091 Padding setting of link button & nesting structure of _AccessibleButton.scss
  res/css/structures/_SpaceHierarchy.scss
  res/css/structures/_ToastContainer.scss
  res/css/structures/_UserMenu.scss
  res/css/structures/auth/_Login.scss
  res/css/views/dialogs/_AddExistingToSpaceDialog.scss
  res/css/views/dialogs/_BugReportDialog.scss
  res/css/views/dialogs/_CreateSubspaceDialog.scss
  res/css/views/dialogs/_FeedbackDialog.scss
  res/css/views/dialogs/_GenericFeatureFeedbackDialog.scss
  res/css/views/dialogs/_InviteDialog.scss
  res/css/views/dialogs/_SpaceSettingsDialog.scss
  res/css/views/elements/_AccessibleButton.scss
  res/css/views/right_panel/_RoomSummaryCard.scss
  res/css/views/rooms/_NewRoomIntro.scss
  res/css/views/rooms/_PinnedEventTile.scss
  res/css/views/settings/_ProfileSettings.scss
  res/css/views/settings/tabs/room/_NotificationSettingsTab.scss
  res/css/views/settings/tabs/user/_PreferencesUserSettingsTab.scss
  res/css/views/spaces/_SpaceBasicSettings.scss
  res/css/views/spaces/_SpaceCreateMenu.scss
  src/components/views/dialogs/InviteDialog.tsx
Labels: T-Task

#8060 Responsive information bar on Space landing page
  res/css/structures/_SpaceRoomView.scss
  src/components/structures/SpaceRoomView.tsx
Labels: T-Task

#8131 Style lint: Disallow shorthand `&` selectors
  .stylelintrc.js
  res/css/structures/_SpaceRoomView.scss
  res/css/views/elements/_AccessibleButton.scss
Labels: T-Task

#8132 Fix stylelint on Windows
  package.json
Labels: T-Task

#8138 Delete empty "StatusMessageContextMenu"
  src/components/views/context_menus/StatusMessageContextMenu.tsx
Labels: T-Task

#8130 Improve typing around wrapInMatrixClientContext
  test/components/views/spaces/SpaceSettingsVisibilityTab-test.tsx
  test/components/views/voip/VoiceChannelRadio-test.tsx
  test/test-utils/wrappers.tsx
Labels: T-Task

#8089 Set max-width to user context menu
  res/css/structures/_UserMenu.scss
Labels: T-Defect

#8128 Fix 3pid member info for space member list
  src/components/structures/SpaceRoomView.tsx
Labels: T-Defect

#8139 Enable Codecov coverage offsets
  .github/codecov.yml
Labels: T-Task

#8140 Wire up file preview for video files
  src/components/views/dialogs/UploadConfirmDialog.tsx
  src/components/views/voip/VideoFeed.tsx
  src/utils/blobs.ts
Labels: T-Enhancement

#8141 Don't try (and fail) to show replies for redacted events
  src/utils/Reply.ts
  test/Reply-test.ts
  test/__snapshots__/Reply-test.ts.snap
Labels: T-Defect

#7929 Strip relations when forwarding
  src/components/views/dialogs/ForwardDialog.tsx
Labels: T-Defect

#8150 Live location sharing: geo.getCurrentPosition wrapper and some testing helpers
  src/utils/beacon/geolocation.ts
  test/test-utils/beacon.ts
  test/test-utils/utilities.ts
  test/utils/beacon/geolocation-test.ts
Labels: T-Task

#8152 Extract location utils from components
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/location/LocationPicker.tsx
  src/components/views/location/LocationViewDialog.tsx
  src/components/views/location/MapError.tsx
  src/components/views/messages/MLocationBody.tsx
  src/i18n/strings/en_EN.json
  src/utils/location/LocationShareErrors.ts
  src/utils/location/findMapStyleUrl.ts
  src/utils/location/index.ts
  src/utils/location/locationEventGeoUri.ts
  src/utils/location/map.ts
  src/utils/location/parseGeoUri.ts
  test/components/views/location/LocationPicker-test.tsx
  test/components/views/location/LocationShareMenu-test.tsx
  test/components/views/location/MapError-test.tsx
  test/components/views/messages/MLocationBody-test.tsx
  test/test-utils/location.ts
  test/utils/location/locationEventGeoUri-test.ts
  test/utils/location/map-test.ts
  test/utils/location/parseGeoUri-test.ts
Labels: T-Task

#8148 Remove unused step from e2e test docs for Windows
  test/end-to-end-tests/Windows.md
Labels: T-Task

#8147 Fix incorrect typing on SdkConfig defaults
  src/SdkConfig.ts
Labels: T-Task

#8157 Floor media dimensions to prevent blurhash errors
  src/settings/enums/ImageSize.ts
  test/settings/enums/ImageSize-test.ts
Labels: T-Defect

#8155 Unit test settings controllers pt 1
  test/settings/controllers/FontSizeController-test.ts
  test/settings/controllers/IncompatibleController-test.ts
  test/settings/controllers/SystemFontController-test.ts
  test/settings/controllers/ThemeController-test.ts
  test/settings/controllers/UseSystemFontController-test.ts
Labels: T-Task

#8159 Fix end-to-end tests for recent Synapse features
  test/end-to-end-tests/pick-synapse-log-file.js
  test/end-to-end-tests/run.sh
  test/end-to-end-tests/synapse/config-templates/consent/homeserver.yaml
  test/end-to-end-tests/synapse/start.sh
Labels: T-Task

#8166 Don't form continuations from thread roots
  src/components/structures/MessagePanel.tsx
  src/components/views/rooms/SearchResultTile.tsx
  src/utils/exportUtils/HtmlExport.tsx
  test/components/structures/MessagePanel-test.js
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#8168 Fix disambiguated profile in threads in bubble layout
  res/css/views/messages/_DisambiguatedProfile.scss
Labels: T-Defect
