Repository matrix-org/matrix-react-sdk, pull requests merged in 2022-09, with the labels that each got.

#9230 Fix plain text export saving
  src/utils/exportUtils/Exporter.ts
Labels: Z-Community-PR, T-Defect

#9220 Link contributing guide to Element Web
  CONTRIBUTING.md
  README.md
  code_style.md
Labels: T-Task

#9234 Remove e2e test exclude from tsconfig
  tsconfig.json
Labels: T-Task

#9235 Fix tooltip infinitely recursing
  src/components/views/elements/Tooltip.tsx
Labels: X-Release-Blocker, T-Defect

#9233 Require @typescript-eslint/eslint-plugin >= 5.35.1
  package.json
  yarn.lock
Labels: T-Task

#9236 Fix suggested rooms going missing
  src/components/views/rooms/RoomList.tsx
Labels: X-Release-Blocker, T-Defect

#9228 Device manager - hide unverified security recommendation when only current session is unverified (PSG-639)
  src/components/views/settings/devices/SecurityRecommendations.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  test/components/views/settings/devices/SecurityRecommendations-test.tsx
Labels: T-Enhancement

#9208 Fix voice messages with multiple composers
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/VoiceRecordComposerTile.tsx
  src/stores/VoiceRecordingStore.ts
Labels: Z-Community-PR, T-Defect

#9246 Fix the picture-in-picture component being off screen
  cypress/e2e/widgets/widget-pip-close.spec.ts
  res/css/views/right_panel/_TimelineCard.pcss
  res/css/views/rooms/_EventBubbleTile.pcss
  src/components/views/voip/PipView.tsx
Labels: X-Release-Blocker, T-Defect

#9231 Use room name as room intro
  src/components/views/rooms/NewRoomIntro.tsx
  test/components/views/rooms/NewRoomIntro-test.tsx
  tsc.txt
Labels: T-Defect

#9216 Simplify releases: move npm publishing to gha, consolidate scripts
  .github/workflows/release.yml
  post-release.sh
  release.sh
Labels: T-Task

#9244 Improve partial translation `or` to have usage context
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/views/dialogs/AppDownloadDialog.tsx
  src/components/views/dialogs/security/AccessSecretStorageDialog.tsx
  src/components/views/right_panel/VerificationPanel.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#9250 Add the clipboard read permission for widgets
  src/components/views/elements/AppTile.tsx
Labels: Z-Community-PR, T-Enhancement

#9243 Fix issue with quiet zone around QR code
  res/css/views/dialogs/_AppDownloadDialog.pcss
Labels: T-Defect, backport staging

#9010 Run Cypress in parallel
  .github/workflows/cypress.yaml
Labels: T-Task

#9258 Tweak backport labels
  .github/workflows/backport.yml
Labels: T-Task

#9237 Handle M_INVALID_USERNAME on /register/available
  cypress/e2e/register/register.spec.ts
  src/components/views/auth/RegistrationForm.tsx
Labels: T-Defect

#9259 Disable all types of autocorrect, -complete, -capitalize, etc on Spotlight's search field
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
Labels: T-Defect

#9262 Fix cypress status check
  .github/workflows/cypress.yaml
Labels: T-Task

#9241 remove the grey gradient on images in bubbles in the timeline
  res/css/views/rooms/_EventBubbleTile.pcss
Labels: T-Defect

#9252 Device manager - add verify current session button (PSG-527)
  src/components/views/settings/devices/CurrentDeviceSection.tsx
  src/components/views/settings/devices/DeviceVerificationStatusCard.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/CurrentDeviceSection-test.tsx
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Enhancement

#9263 Update commit status earlier in cypress workflow_run
  .github/workflows/cypress.yaml
Labels: T-Task

#9268 bugfix: fix a sliding sync bug which could cause rooms to loop
  src/stores/RoomViewStore.tsx
  test/stores/RoomViewStore-test.tsx
Labels: T-Defect

#9261 Upgrade @types
  package.json
  src/components/views/elements/AppTile.tsx
  src/components/views/elements/Dropdown.tsx
  src/components/views/elements/Field.tsx
  src/components/views/elements/ReplyChain.tsx
  src/components/views/rooms/RoomContextDetails.tsx
  yarn.lock
Labels: X-Release-Blocker, T-Task

#9251 Device manager - filter out nulled metadatas in device tile properly (PSG-703)
  src/components/views/settings/devices/DeviceTile.tsx
  test/components/views/settings/__snapshots__/DevicesPanel-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceTile-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/SelectableDeviceTile-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Defect

#9270 Fix tile crash around tooltipify links
  src/utils/tooltipify.tsx
Labels: T-Defect

#9266 Prevent sliding sync from showing a room under multiple sublists
  cypress/e2e/sliding-sync/sliding-sync.ts
  src/stores/room-list/SlidingRoomListStore.ts
Labels: T-Defect

#9272 Fix thumbnail generation when offscreen canvas fails
  src/utils/image-media.ts
Labels: T-Defect

#9273 Fix memory leak caused by unremoved listener
  src/components/structures/RoomView.tsx
Labels: T-Defect

#9274 Device manager - verify other devices (PSG-724)
  src/components/views/settings/devices/DeviceDetails.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/test-utils/client.ts
Labels: T-Enhancement

#9276 Fix invalid instanceof operand window.OffscreenCanvas
  src/utils/image-media.ts
Labels: X-Release-Blocker, T-Defect

#9275 Device manager - logout current session (PSG-743)
  res/css/components/views/settings/devices/_DeviceDetails.pcss
  res/css/views/elements/_AccessibleButton.pcss
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/settings/devices/CurrentDeviceSection.tsx
  src/components/views/settings/devices/DeviceDetails.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/CurrentDeviceSection-test.tsx
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceDetails-test.tsx.snap
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Enhancement

#9210 Implement MSC3869: Read event relations with the Widget API
  package.json
  src/stores/widgets/StopGapWidgetDriver.ts
  test/stores/widgets/StopGapWidgetDriver-test.ts
  yarn.lock
Labels: Z-Community-PR, T-Enhancement

#9280 Device manager - logout of other session (PSG-744)
  res/css/components/views/settings/devices/_DeviceDetails.pcss
  src/components/views/settings/devices/CurrentDeviceSection.tsx
  src/components/views/settings/devices/DeviceDetails.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  test/components/views/settings/devices/CurrentDeviceSection-test.tsx
  test/components/views/settings/devices/DeviceDetails-test.tsx
  test/components/views/settings/devices/FilteredDeviceList-test.tsx
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceDetails-test.tsx.snap
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Enhancement

#9283 Generic typography component - Caption
  res/css/_components.pcss
  res/css/components/views/typography/_Caption.pcss
  src/components/views/typography/Caption.tsx
  test/components/views/typography/Caption-test.tsx
  test/components/views/typography/__snapshots__/Caption-test.tsx.snap
Labels: T-Task

#9278 bugfix: fix in-reply-to previews not disappearing when swapping rooms
  cypress/e2e/sliding-sync/sliding-sync.ts
  src/stores/RoomViewStore.tsx
  test/stores/RoomViewStore-test.tsx
Labels: T-Defect

#9282 Device manager - rename session (PSG-528)
  res/css/_components.pcss
  res/css/components/views/settings/devices/_DeviceDetailHeading.pcss
  res/css/components/views/settings/devices/_DeviceDetails.pcss
  src/components/views/settings/devices/CurrentDeviceSection.tsx
  src/components/views/settings/devices/DeviceDetailHeading.tsx
  src/components/views/settings/devices/DeviceDetails.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/CurrentDeviceSection-test.tsx
  test/components/views/settings/devices/DeviceDetailHeading-test.tsx
  test/components/views/settings/devices/DeviceDetails-test.tsx
  test/components/views/settings/devices/FilteredDeviceList-test.tsx
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceDetailHeading-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceDetails-test.tsx.snap
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Enhancement

#9281 Fix soft crash around inviting invalid MXIDs in start DM on first message flow
  cypress/e2e/crypto/crypto.spec.ts
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/dialogs/ShareDialog.tsx
  src/utils/permalinks/Permalinks.ts
  test/components/views/dialogs/InviteDialog-test.tsx
  test/utils/permalinks/Permalinks-test.ts
Labels: T-Defect

#9279 Add Voice Broadcast labs setting and composer button
  res/css/views/rooms/_MessageComposer.pcss
  res/img/element-icons/live.svg
  src/Modal.tsx
  src/components/views/location/LocationButton.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
  src/components/views/rooms/ReplyPreview.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/views/rooms/MessageComposer-test.tsx
  test/components/views/rooms/MessageComposerButtons-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/test-utils/composer.ts
Labels: T-Task

#9289 Make autocomplete pop-up wider in thread view
  res/css/views/right_panel/_ThreadPanel.pcss
  src/components/structures/ThreadView.tsx
Labels: T-Defect

#9287 Wrap cypress set settings promise
  cypress/support/settings.ts
Labels: T-Task

#9285 Turn off tsc --strict annotations
  .github/workflows/static_analysis.yaml
Labels: T-Task

#9291 Fix SessionManagerTab-test
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Task

#9284 Add voice broadcast permissions
  src/components/structures/RoomView.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/contexts/RoomContext.ts
  src/i18n/strings/en_EN.json
  src/voice-broadcast/index.ts
  test/components/views/rooms/MessageComposer-test.tsx
  test/components/views/rooms/MessageComposerButtons-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/components/views/settings/tabs/room/RolesRoomSettingsTab-test.tsx
Labels: T-Task

#9290 Store refactor: make it easier to test stores
  src/components/structures/RoomView.tsx
  src/components/views/right_panel/TimelineCard.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/voip/PipView.tsx
  src/stores/RoomViewStore.tsx
  src/stores/room-list/RoomListStore.ts
  src/stores/room-list/SlidingRoomListStore.ts
  test/components/structures/RoomView-test.tsx
  test/stores/RoomViewStore-test.tsx
  test/test-utils/test-utils.ts
  test/test-utils/utilities.ts
Labels: T-Task

#9300 Fix tile soft crash in ReplyInThreadButton
  src/components/views/context_menus/MessageContextMenu.tsx
Labels: T-Defect

#9302 Fix spaces feedback prompt wrongly showing when feedback is disabled
  src/components/views/spaces/SpaceCreateMenu.tsx
Labels: T-Defect

#9301 Fix soft crash around unknown room pills
  src/editor/parts.ts
  test/editor/parts-test.ts
Labels: T-Defect

#9239 Read receipts for threads
  src/components/structures/MessagePanel.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/structures/ThreadView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/settings/Notifications.tsx
  test/components/structures/TimelinePanel-test.tsx
Labels: T-Enhancement

#9304 Generalise VoiceRecording
  src/audio/VoiceMessageRecording.ts
  src/audio/VoiceRecording.ts
  src/components/views/audio_messages/LiveRecordingClock.tsx
  src/components/views/audio_messages/LiveRecordingWaveform.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/VoiceRecordComposerTile.tsx
  src/stores/VoiceRecordingStore.ts
  test/audio/VoiceMessageRecording-test.ts
  test/components/views/rooms/VoiceRecordComposerTile-test.tsx
  test/stores/VoiceRecordingStore-test.ts
  test/test-utils/test-utils.ts
Labels: T-Task

#9306 Add array concat util
  src/audio/VoiceMessageRecording.ts
  src/utils/arrays.ts
  test/utils/arrays-test.ts
Labels: T-Task

#9295 Use display name instead of user ID when rendering power events (PSC-82)
  src/TextForEvent.tsx
  test/TextForEvent-test.ts
Labels: T-Enhancement

#9305 Don't show feedback prompts when that UIFeature is disabled
  src/components/structures/ThreadPanel.tsx
  src/components/views/beta/BetaCard.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
  src/components/views/user-onboarding/UserOnboardingFeedback.tsx
  src/utils/Feedback.ts
  test/components/structures/ThreadPanel-test.tsx
  test/components/structures/__snapshots__/ThreadPanel-test.tsx.snap
  test/components/views/beta/BetaCard-test.tsx
  test/components/views/dialogs/SpotlightDialog-test.tsx
  test/test-utils/test-utils.ts
  test/utils/Feedback-test.ts
Labels: T-Defect

#9309 Move @testing-library/react to devDeps
  package.json
Labels: T-Task

#9297 Make device ID copyable in device list
  src/components/views/settings/devices/DeviceTile.tsx
  test/components/views/settings/__snapshots__/DevicesPanel-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceTile-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/SelectableDeviceTile-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Enhancement

#9311 New group call experience: Room header call buttons
  package.json
  src/IConfigOptions.ts
  src/LegacyCallHandler.tsx
  src/SdkConfig.ts
  src/components/structures/RoomView.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/dispatcher/payloads/ViewRoomPayload.ts
  src/hooks/useEventEmitter.ts
  src/i18n/strings/en_EN.json
  src/models/Call.ts
  src/settings/Settings.tsx
  src/stores/RoomViewStore.tsx
  src/stores/WidgetEchoStore.ts
  test/components/views/rooms/RoomHeader-test.tsx
  yarn.lock
Labels: T-Enhancement

#9316 Add voice broadcast recording body
  package.json
  res/css/_components.pcss
  res/css/components/atoms/_Icon.pcss
  res/css/voice-broadcast/atoms/_LiveBadge.pcss
  res/css/voice-broadcast/molecules/_VoiceBroadcastRecordingBody.pcss
  res/themes/dark/css/_dark.pcss
  res/themes/legacy-dark/css/_legacy-dark.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light/css/_light.pcss
  src/components/atoms/Icon.tsx
  src/components/structures/MessagePanel.tsx
  src/components/views/messages/MessageEvent.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/events/EventTileFactory.tsx
  src/i18n/strings/en_EN.json
  src/voice-broadcast/components/VoiceBroadcastBody.tsx
  src/voice-broadcast/components/atoms/LiveBadge.tsx
  src/voice-broadcast/components/index.ts
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingBody.tsx
  src/voice-broadcast/index.ts
  src/voice-broadcast/utils/index.ts
  src/voice-broadcast/utils/shouldDisplayAsVoiceBroadcastTile.ts
  test/components/atoms/Icon-test.tsx
  test/components/atoms/__snapshots__/Icon-test.tsx.snap
  test/voice-broadcast/components/VoiceBroadcastBody-test.tsx
  test/voice-broadcast/components/atoms/LiveBadge-test.tsx
  test/voice-broadcast/components/atoms/__snapshots__/LiveBadge-test.tsx.snap
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingBody-test.tsx
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastRecordingBody-test.tsx.snap
  test/voice-broadcast/utils/shouldDisplayAsVoiceBroadcastTile-test.ts
  yarn.lock
Labels: T-Task

#9317 Don't render a 1px high room topic if the room topic is empty
  res/css/views/rooms/_RoomHeader.pcss
Labels: Z-Community-PR, T-Defect

#9308 Implement push notification toggle in device detail
  res/css/components/views/settings/devices/_DeviceDetails.pcss
  res/css/views/elements/_ToggleSwitch.pcss
  src/components/views/settings/devices/DeviceDetails.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/DevicesPanel-test.tsx
  test/components/views/settings/devices/CurrentDeviceSection-test.tsx
  test/components/views/settings/devices/DeviceDetails-test.tsx
  test/components/views/settings/devices/FilteredDeviceList-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#9324 Add device notifications enabled switch
  src/components/structures/MatrixChat.tsx
  src/components/views/elements/LabelledToggleSwitch.tsx
  src/components/views/settings/Notifications.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/utils/notifications.ts
  test/components/views/settings/Notifications-test.tsx
  test/components/views/settings/__snapshots__/Notifications-test.tsx.snap
  test/utils/notifications-test.ts
Labels: T-Enhancement

#9327 Display push toggle for web sessions (MSC3890)
  src/components/views/settings/devices/CurrentDeviceSection.tsx
  src/components/views/settings/devices/DeviceDetails.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  test/components/views/settings/devices/DeviceDetails-test.tsx
  test/components/views/settings/devices/FilteredDeviceList-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Enhancement

#9328 Inhibit local notifications when local notifications are silenced
  src/Notifier.ts
  src/utils/notifications.ts
  test/Notifier-test.ts
  test/utils/notifications-test.ts
Labels: T-Task

#9298 Fix quote shortcut for most keyboard layouts
  src/accessibility/KeyboardShortcuts.ts
  src/components/views/rooms/BasicMessageComposer.tsx
Labels: Z-Community-PR, T-Enhancement

#9331 Fixes to ensure account data values do not go stale
  src/components/structures/MatrixChat.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Task

#9322 Extract createVoiceMessageContent
  src/components/views/rooms/VoiceRecordComposerTile.tsx
  src/utils/createVoiceMessageContent.ts
  test/components/views/rooms/VoiceRecordComposerTile-test.tsx
  test/utils/__snapshots__/createVoiceMessageContent-test.ts.snap
  test/utils/createVoiceMessageContent-test.ts
Labels: T-Task

#9325 Device manager - sign out of multiple sessions
  res/css/components/views/settings/devices/_FilteredDeviceList.pcss
  res/css/components/views/settings/devices/_FilteredDeviceListHeader.pcss
  res/css/views/elements/_AccessibleButton.pcss
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/settings/devices/DeviceTile.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/SelectableDeviceTile.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/__snapshots__/DevicesPanel-test.tsx.snap
  test/components/views/settings/devices/FilteredDeviceList-test.tsx
  test/components/views/settings/devices/__snapshots__/SelectableDeviceTile-test.tsx.snap
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Enhancement

#9310 Reduce flakiness of spotlight tests
  cypress/e2e/spotlight/spotlight.spec.ts
Labels: T-Task

#9336 Fixes silenced notification preventing notification prompt to be shown
  src/Notifier.ts
  src/components/structures/MatrixChat.tsx
  src/components/views/settings/Notifications.tsx
  src/settings/Settings.tsx
  src/toasts/DesktopNotificationsToast.ts
  src/utils/notifications.ts
  test/utils/notifications-test.ts
Labels: T-Task

#9326 Consolidate js-sdk release mode typing CI
  .github/workflows/static_analysis.yaml
  scripts/ci/js-sdk-to-release.js
Labels: T-Task

#9321 Fix device selection in pre-join screen for Element Call video rooms
  src/MediaDeviceHandler.ts
  src/components/views/voip/CallView.tsx
  src/i18n/strings/en_EN.json
  src/models/Call.ts
  test/components/views/voip/CallView-test.tsx
  test/models/Call-test.ts
  test/test-utils/test-utils.ts
Labels: T-Defect

#9332 New group call experience: Call tiles
  res/css/_components.pcss
  res/css/views/elements/_FacePile.pcss
  res/css/views/messages/_CallEvent.pcss
  res/css/views/rooms/_EventBubbleTile.pcss
  res/css/views/rooms/_LiveContentSummary.pcss
  res/css/views/voip/_CallDuration.pcss
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/messages/CallEvent.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/LiveContentSummary.tsx
  src/components/views/rooms/RoomTileCallSummary.tsx
  src/components/views/voip/CallDuration.tsx
  src/createRoom.ts
  src/events/EventTileFactory.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/utils/EventRenderingUtils.ts
  test/components/views/messages/CallEvent-test.tsx
  test/test-utils/call.ts
Labels: T-Enhancement
