Repository matrix-org/matrix-react-sdk, pull requests merged in 2022-06, with the labels that each got.

#8731 Fix flakiness of cypress crypto tests
  cypress/integration/7-crypto/crypto.spec.ts
Labels: T-Task

#8470 Fix read avatars overflow from the right chat panel with a maximized widget on bubble message layout
  res/css/views/right_panel/_TimelineCard.scss
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_ReadReceiptGroup.scss
Labels: Z-Community-PR, T-Defect

#8732 Unit test MessageActionBar
  code_style.md
  package.json
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/emojipicker/ReactionPicker.tsx
  test/components/views/messages/MessageActionBar-test.tsx
  test/test-utils/client.ts
  test/test-utils/utilities.ts
  yarn.lock
Labels: T-Task

#8737 Improve _ShareType.scss
  res/css/components/views/location/_ShareType.scss
  src/components/views/location/ShareType.tsx
Labels: Z-Community-PR, T-Task

#8646 Prevent Invite and DevTools dialogs from being cut off
  res/css/views/dialogs/_DevtoolsDialog.scss
  res/css/views/dialogs/_InviteDialog.scss
  src/RoomInvite.tsx
  src/utils/DialogOpener.ts
Labels: T-Defect

#8721 Live location share - enable reply and react to tiles
  res/css/components/views/messages/_MBeaconBody.scss
  src/components/views/beacon/OwnBeaconStatus.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/utils/EventUtils.ts
  test/components/views/messages/MessageActionBar-test.tsx
  test/utils/EventUtils-test.ts
Labels: T-Enhancement

#8745 Adjust message timestamp position on TimelineCard in non-bubble layouts
  res/css/views/right_panel/_TimelineCard.scss
Labels: T-Enhancement

#8747 Make PiP motion smoother and react to window resizes correctly
  src/components/views/elements/AppTile.tsx
  src/components/views/elements/PersistedElement.tsx
  src/components/views/elements/PersistentApp.tsx
  src/components/views/voip/PictureInPictureDragger.tsx
  src/components/views/voip/PipView.tsx
Labels: T-Defect

#8748 Make sure MessageTimestamp is not hidden by EventTile_line on TimelineCard
  res/css/views/right_panel/_TimelineCard.scss
Labels: T-Defect

#8730 Use AccessibleButton for 'Reset All' link button on SetupEncryptionBody
  res/css/structures/auth/_SetupEncryptionBody.scss
  src/components/structures/auth/SetupEncryptionBody.tsx
Labels: Z-Community-PR, T-Enhancement

#8725 Move style rules of MatrixChat_useCompactLayout from _GroupLayout.scss to _EventTile.scss and _RoomView.scss
  res/css/structures/_RoomView.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_GroupLayout.scss
Labels: Z-Community-PR, T-Task

#8746 Hide live location option in threads composer
  src/components/views/location/LocationShareMenu.tsx
  test/components/views/location/LocationShareMenu-test.tsx
Labels: T-Defect

#8734 Improve widget buttons behaviour and layout
  res/css/views/rooms/_AppsDrawer.scss
  src/components/views/elements/AppTile.tsx
  src/i18n/strings/en_EN.json
  test/components/views/elements/AppTile-test.tsx
Labels: T-Enhancement

#8751 Revert "Move style rules of MatrixChat_useCompactLayout from _GroupLayout.scss to _EventTile.scss and _RoomView.scss"
  res/css/structures/_RoomView.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_GroupLayout.scss
Labels: Z-Community-PR, T-Task

#8750 Ensure the first device on a newly-registered account gets cross-signed properly
  cypress/integration/1-register/register.spec.ts
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/views/dialogs/security/CreateCrossSigningDialog.tsx
Labels: T-Defect

#8753 Followup type-check fixes for bootstrapCrossSigning callback
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/views/dialogs/security/CreateCrossSigningDialog.tsx
Labels: T-Task

#8755 Add ellipsis effect to hidden beacon status
  res/css/components/views/beacon/_BeaconStatus.scss
  src/components/views/beacon/BeaconStatus.tsx
  test/components/views/beacon/__snapshots__/BeaconStatus-test.tsx.snap
  test/components/views/beacon/__snapshots__/OwnBeaconStatus-test.tsx.snap
Labels: T-Defect

#8756 Prevent the banner text from being selected, replacing the spacing values with the variable
  res/css/views/messages/_MImageBody.scss
Labels: T-Defect

#8758 Make the pill on the basic message composer compatible with display name in RTL languages
  res/css/views/elements/_Pill.scss
  res/css/views/rooms/_BasicMessageComposer.scss
Labels: T-Defect

#8761 Remove unnecessary ButtonResetDefault from mx_LeftPanelLiveShareWarning
  res/css/components/views/beacon/_LeftPanelLiveShareWarning.scss
Labels: T-Task

#8762 Tidy up mx_InviteDialog_dialPad style rules
  res/css/views/dialogs/_InviteDialog.scss
Labels: T-Task

#8769 Remove ListResetDefault
  res/css/_common.scss
  res/css/components/views/beacon/_DialogSidebar.scss
Labels: T-Task

#8765 Makes the avatar of the user menu non-draggable
  res/css/structures/_UserMenu.scss
Labels: T-Enhancement

#8768 Improve Typescript in `BasePlatform`
  src/BasePlatform.ts
Labels: T-Task

#8770 Fix 'Logout' inline link on the splash screen
  src/components/structures/MatrixChat.tsx
Labels: T-Defect

#8736 Reduce gutter with the new read receipt UI
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#8754 Fix disappearing widget poput button when changing the widget layout
  src/components/views/elements/AppTile.tsx
  test/components/views/elements/AppTile-test.tsx
Labels: T-Defect

#8729 Switch to composite actions for pr_details and sonarqube
  .github/workflows/netlify.yaml
  .github/workflows/sonarqube.yml
Labels: T-Task

#8772 Add more debug logging to try and find out why ring and ringback sounds aren't playing
  src/CallHandler.tsx
Labels: T-Task

#8763 Slightly improve the look of the `Message edits` dialog
  res/css/views/dialogs/_MessageEditHistoryDialog.scss
Labels: T-Enhancement

#8578 Improve composer visiblity
  res/css/_components.scss
  res/css/structures/_RoomView.scss
  res/css/views/buttons/_Cancel.scss
  res/css/views/rooms/_MessageComposer.scss
  res/css/views/rooms/_ReplyPreview.scss
  res/css/views/rooms/_SendMessageComposer.scss
  res/img/cancel.svg
  res/img/element-icons/room/message-bar/reply.svg
  res/img/element-icons/room/room-summary.svg
  res/img/element-icons/x-8px.svg
  src/components/views/buttons/Cancel.tsx
  src/components/views/messages/DisambiguatedProfile.tsx
  src/components/views/messages/SenderProfile.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/ReplyPreview.tsx
  src/components/views/rooms/ReplyTile.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/MessageComposer-test.tsx
Labels: T-Enhancement

#8771 Remove outdated dangling underscore
  docs/scrolling.md
Labels: T-Task

#8691 Rework the Cypress & Percy CI
  .github/workflows/cypress.yaml
  .github/workflows/element-build-and-test.yaml
  .github/workflows/element-web.yaml
  .github/workflows/netlify.yaml
  .github/workflows/tests.yml
  docs/cypress.md
Labels: T-Task

#8773 Cypress: only pass -u arg to docker on *nix systems
  cypress/plugins/synapsedocker/index.ts
Labels: T-Task

#8774 Update matrix-org/github-action-benchmark
  .github/workflows/cypress.yaml
Labels: T-Task

#8752 Live location share - link to timeline tile from share warning (PSF-1078)
  res/css/components/views/beacon/_RoomLiveShareWarning.scss
  src/components/views/beacon/LeftPanelLiveShareWarning.tsx
  src/components/views/beacon/RoomLiveShareWarning.tsx
  test/components/views/beacon/LeftPanelLiveShareWarning-test.tsx
  test/components/views/beacon/RoomLiveShareWarning-test.tsx
  test/components/views/beacon/__snapshots__/RoomLiveShareWarning-test.tsx.snap
Labels: T-Enhancement

#8715 Use updates stable relations from js-sdk
  src/MatrixClientPeg.ts
  src/components/structures/MessagePanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/utils/EventUtils.ts
  test/components/views/messages/MessageActionBar-test.tsx
Labels: T-Task

#8215 Add support for MD / HTML in room topics
  res/css/_common.scss
  res/css/views/rooms/_RoomHeader.scss
  src/HtmlUtils.tsx
  src/SlashCommands.tsx
  src/components/views/elements/RoomTopic.tsx
  src/components/views/room_settings/RoomProfileSettings.tsx
  src/components/views/spaces/SpaceSettingsGeneralTab.tsx
  src/editor/serialize.ts
  src/hooks/room/useTopic.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/HtmlUtils-test.tsx
  test/SlashCommands-test.tsx
  test/editor/serialize-test.ts
  test/test-utils/test-utils.ts
  test/useTopic-test.tsx
Labels: T-Enhancement

#8672 Organize style rules of ThreadPanel header
  res/css/views/right_panel/_ThreadPanel.scss
Labels: Z-Community-PR, T-Task

#8760 Improve style of DialogSidebar (of live location map)
  res/css/components/views/beacon/_DialogSidebar.scss
Labels: Z-Community-PR, T-Task

#8781 Normalize the name of buttons on MessageActionBar
  res/css/views/messages/_MessageActionBar.scss
  src/components/views/rooms/EventTile.tsx
Labels: T-Task

#8779 Add CI to improve experience for community
  .github/workflows/pull_request.yaml
Labels: T-Task

#8757 Use MessageActionBar style declarations on pinned message card
  res/css/views/messages/_MessageActionBar.scss
  res/css/views/right_panel/_PinnedMessagesCard.scss
  src/components/views/right_panel/PinnedMessagesCard.tsx
Labels: T-Defect

#8785 Fix the incorrect nesting of download button on MessageActionBar
  res/css/views/messages/_MessageActionBar.scss
Labels: T-Defect

#8789 Pass missing ci secret
  .github/workflows/pull_request.yaml
Labels: T-Task

#8788 Fix scroll jump issue with the composer
  res/css/views/rooms/_SendMessageComposer.scss
Labels: T-Defect

#8790 Fix cypress checkout and use github actions environments
  .github/workflows/cypress.yaml
  .github/workflows/end-to-end-tests.yaml
  .github/workflows/netlify.yaml
Labels: T-Task

#8796 Enable cypress retries to counter the load flakiness
  cypress.json
Labels: T-Task

#8787 Move the user view tests from Puppeteer to Cypress
  cypress/integration/10-user-view/user-view.spec.ts
  cypress/support/app.ts
  cypress/support/index.ts
  cypress/support/percy.ts
  package.json
  src/components/views/right_panel/UserInfo.tsx
  test/end-to-end-tests/src/scenario.ts
  test/end-to-end-tests/src/scenarios/user-view.ts
  yarn.lock
Labels: T-Task, X-Needs-Percy

#8797 Fix cypress benchmark uploading
  .github/workflows/cypress.yaml
Labels: T-Task

#8801 Fix Cypress handling of multi-line commit messages
  .github/workflows/cypress.yaml
Labels: T-Task

#8689 Move style rules for EventTile on ThreadView from _ThreadPanel.scss to _EventTile.scss
  res/css/views/right_panel/_ThreadPanel.scss
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Task

#8046 Name lists on invite dialog
  res/css/views/dialogs/_InviteDialog.scss
  src/RoomInvite.tsx
  src/components/views/dialogs/InviteDialog.tsx
  test/end-to-end-tests/src/usecases/create-room.ts
  test/end-to-end-tests/src/usecases/invite.ts
Labels: Z-Community-PR, T-Defect

#8776 Expire video member events after 1 hour
  res/css/_components.scss
  res/css/views/rooms/_RoomTile.scss
  res/css/views/rooms/_VideoRoomSummary.scss
  src/components/views/rooms/RoomTile.tsx
  src/components/views/rooms/VideoRoomSummary.tsx
  src/i18n/strings/en_EN.json
  src/stores/VideoChannelStore.ts
  src/utils/VideoChannelUtils.ts
  test/components/structures/VideoRoomView-test.tsx
  test/components/views/rooms/RoomTile-test.tsx
  test/stores/VideoChannelStore-test.ts
  test/test-utils/video.ts
Labels: T-Defect

#8802 Fix #20026: send read marker as soon as we change it
  src/components/structures/TimelinePanel.tsx
  test/components/structures/TimelinePanel-test.tsx
Labels: T-Defect

#8804 Fix percy disabling logic being inverted
  .github/workflows/cypress.yaml
Labels: T-Task

#8803 Revert "Make widgets in video rooms mutable again to de-risk future upgrades"
  src/createRoom.ts
  test/createRoom-test.ts
Labels: T-Defect

#8431 Release video rooms as a beta feature
  res/css/views/beta/_BetaCard.scss
  res/css/views/rooms/_RoomHeader.scss
  res/css/views/rooms/_RoomPreviewCard.scss
  res/img/betas/video_rooms.png
  src/components/structures/SpaceRoomView.tsx
  src/components/views/beta/BetaCard.tsx
  src/components/views/context_menus/SpaceContextMenu.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomListHeader.tsx
  src/components/views/rooms/RoomPreviewCard.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Enhancement

#8805 Allow AppTiles to shrink as much as necessary
  res/css/views/rooms/_AppsDrawer.scss
Labels: T-Defect

#8806 Update the live timeline when the JS SDK resets it
  src/components/structures/RoomView.tsx
  test/components/structures/RoomView-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Defect

#8810 Use a fixed matrix-org/github-action-benchmark
  .github/workflows/cypress.yaml
Labels: T-Task

#8811 Keep draft in composer when a slash command syntax errors
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/editor/commands.tsx
Labels: T-Enhancement

#8767 Disable redacting reactions if we don't have sufficient permissions
  res/css/views/elements/_AccessibleButton.scss
  src/components/structures/RoomView.tsx
  src/components/views/emojipicker/Category.tsx
  src/components/views/emojipicker/Emoji.tsx
  src/components/views/emojipicker/EmojiPicker.tsx
  src/components/views/emojipicker/ReactionPicker.tsx
  src/components/views/messages/ReactionsRow.tsx
  src/components/views/messages/ReactionsRowButton.tsx
  src/contexts/RoomContext.ts
  test/components/views/rooms/MessageComposerButtons-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
Labels: T-Defect

#8798 Abstract electron settings properly to avoid boilerplate-hell
  src/BasePlatform.ts
  src/components/views/elements/SettingsFlag.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/dispatcher/payloads/CheckUpdatesPayload.ts
  src/i18n/strings/en_EN.json
  src/settings/SettingLevel.ts
  src/settings/Settings.tsx
  src/settings/SettingsStore.ts
  src/settings/handlers/PlatformSettingsHandler.ts
Labels: T-Task

#8817 Import React to appease IDE linter
  src/utils/exportUtils/PlainTextExport.ts
Labels: T-Task

#8820 Fix clickable area of advanced toggle on appearance user settings tab
  res/css/views/settings/tabs/user/_AppearanceUserSettingsTab.scss
  src/components/views/settings/tabs/user/AppearanceUserSettingsTab.tsx
Labels: Z-Community-PR, T-Defect

#8824 Tidy _AppearanceUserSettingsTab.scss
  res/css/views/settings/tabs/user/_AppearanceUserSettingsTab.scss
Labels: Z-Community-PR, T-Task

#8823 Use common subheading on sidebar user settings tab
  res/css/views/settings/tabs/user/_SidebarUserSettingsTab.scss
  src/components/views/settings/tabs/user/SidebarUserSettingsTab.tsx
Labels: Z-Community-PR, T-Defect

#8822 Use mx_SettingsTab_subsectionText for the text under the top header of appearance user settings tab
  res/css/views/settings/tabs/user/_AppearanceUserSettingsTab.scss
  src/components/views/settings/tabs/user/AppearanceUserSettingsTab.tsx
Labels: Z-Community-PR, T-Task

#8821 Prevent level order to be modified
  src/settings/SettingsStore.ts
  test/settings/SettingsStore-test.ts
Labels: T-Defect

#8743 Remove an obsolete style declaration of .mx_ReplyChain_show
  res/css/views/rooms/_EventBubbleTile.scss
Labels: Z-Community-PR, T-Task

#8728 Improve CSS rules of zoom buttons on live location
  res/css/components/views/location/_ZoomButtons.scss
Labels: Z-Community-PR, T-Task

#8829 Prevent new composer from overflowing from non-breakable text
  res/css/views/rooms/_MessageComposer.scss
Labels: X-Release-Blocker, T-Defect

#8830 Add try-catch around blurhash loading
  src/components/views/messages/MVideoBody.tsx
Labels: T-Defect

#8825 Fix keyboard shortcuts on settings tab being wrapped
  res/css/views/settings/_KeyboardShortcut.scss
  res/css/views/settings/tabs/user/_KeyboardUserSettingsTab.scss
Labels: Z-Community-PR, T-Defect

#8831 Remove _NotificationUserSettingsTab.scss
  res/css/_components.scss
  res/css/views/settings/tabs/user/_NotificationUserSettingsTab.scss
  src/components/views/settings/tabs/user/NotificationUserSettingsTab.tsx
Labels: Z-Community-PR, T-Task

#8832 Move room directory Puppeteer tests over to Cypress
  cypress/global.d.ts
  cypress/integration/11-room-directory/room-directory.spec.ts
  cypress/support/percy.ts
  cypress/support/settings.ts
  res/css/views/avatars/_BaseAvatar.scss
  test/end-to-end-tests/src/scenario.ts
  test/end-to-end-tests/src/scenarios/directory.ts
Labels: T-Task, X-Needs-Percy

#8828 Remove unique settings from labs user settings tab
  res/css/views/settings/tabs/_SettingsTab.scss
  res/css/views/settings/tabs/user/_LabsUserSettingsTab.scss
  res/css/views/settings/tabs/user/_PreferencesUserSettingsTab.scss
Labels: Z-Community-PR, T-Task

#8837 Skip running jobs on fork `develop` where they lack secrets
  .github/workflows/cypress.yaml
  .github/workflows/end-to-end-tests.yaml
  .github/workflows/notify-element-web.yml
Labels: T-Task

#8839 Remove obsolete style rules for "Show my Communities" which has been removed
  res/css/views/settings/tabs/user/_PreferencesUserSettingsTab.scss
Labels: Z-Community-PR, T-Task

#7283 Improve colors in settings
  res/css/views/settings/_AvatarSetting.scss
  res/css/views/settings/_DevicesPanel.scss
  res/css/views/settings/_FontScalingPanel.scss
  res/css/views/settings/_LayoutSwitcher.scss
  res/css/views/settings/_ProfileSettings.scss
  res/css/views/settings/_ThemeChoicePanel.scss
  res/css/views/settings/tabs/_SettingsTab.scss
  res/css/views/settings/tabs/room/_SecurityRoomSettingsTab.scss
  res/css/views/spaces/_SpaceBasicSettings.scss
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light-custom/css/_custom.scss
  res/themes/light/css/_light.scss
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
Labels: T-Enhancement

#8834 Remove unused sessionStorage layer
  cypress/global.d.ts
  cypress/support/bot.ts
  cypress/support/storage.ts
  src/utils/createMatrixClient.ts
  test/test-utils/test-utils.ts
Labels: T-Task

#8845 Add a bit of safety around timestamp handling for threads
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#8814 Remove Riot-era media query declarations of event tile on mobile UI
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Defect

#8849 Update the avatar mask so it doesn’t cut off spaces’ avatars anymore
  res/css/structures/_UserMenu.scss
  res/img/element-icons/roomlist/decorated-avatar-mask.svg
  res/img/element-icons/roomlist/dnd-avatar-mask.svg
Labels: T-Defect

#8848 Reload map on reconnect
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MLocationBody.tsx
  src/utils/connection.ts
  test/components/views/messages/MLocationBody-test.tsx
  test/components/views/messages/__snapshots__/MLocationBody-test.tsx.snap
  test/utils/connection-test.ts
Labels: T-Defect

#8584 Remove margin from E2E icon between avatar and hidden event
  res/css/views/rooms/_EventBubbleTile.scss
Labels: Z-Community-PR, T-Defect

#8711 Stop using mx_GroupLayout for styling
  res/css/views/right_panel/_ThreadPanel.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_GroupLayout.scss
  res/css/views/rooms/_IRCLayout.scss
Labels: Z-Community-PR, T-Task

#8808 Create a common header on right panel cards on BaseCard
  res/css/views/right_panel/_BaseCard.scss
  res/css/views/right_panel/_PinnedMessagesCard.scss
  res/css/views/right_panel/_RoomSummaryCard.scss
  res/css/views/right_panel/_ThreadPanel.scss
  res/css/views/right_panel/_TimelineCard.scss
  res/css/views/right_panel/_UserInfo.scss
  res/css/views/right_panel/_WidgetCard.scss
  src/components/structures/ThreadPanel.tsx
  src/components/structures/ThreadView.tsx
  src/components/views/context_menus/ThreadListContextMenu.tsx
  src/components/views/right_panel/PinnedMessagesCard.tsx
  src/components/views/right_panel/TimelineCard.tsx
  src/components/views/right_panel/WidgetCard.tsx
  test/components/structures/__snapshots__/ThreadPanel-test.tsx.snap
Labels: Z-Community-PR, T-Enhancement

#8792 Include mx_MessageActionBar_maskButton in mx_MessageActionBar
  res/css/views/messages/_MessageActionBar.scss
Labels: Z-Community-PR, T-Task

#8813 Fix reactions row overflow and gap between reactions
  res/css/views/messages/_ReactionsRowButton.scss
  res/css/views/right_panel/_TimelineCard.scss
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Defect

#8782 Allow integration managers to validate user identity after opening
  src/ScalarMessaging.ts
Labels: T-Enhancement

#8857 Fix temporary sync errors if there's weird settings stored in account data
  src/settings/SettingsStore.ts
Labels: T-Defect

#8816 Fix grid blowout on pinned event tiles
  res/css/views/rooms/_PinnedEventTile.scss
Labels: Z-Community-PR, T-Defect

#8819 Tidy _SettingsTab.scss
  res/css/views/settings/tabs/_SettingsTab.scss
Labels: Z-Community-PR, T-Task

#8856 Make cypress tests for spotlight less flaky
  cypress/integration/12-spotlight/spotlight.spec.ts
Labels: T-Task

#8860 Live location share - forward latest location (PSF-1044)
  __mocks__/maplibre-gl.js
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/dialogs/ForwardDialog.tsx
  src/events/forward/getForwardableBeacon.ts
  src/events/forward/getForwardableEvent.ts
  src/events/forward/types.ts
  src/utils/EventUtils.ts
  test/components/views/beacon/__snapshots__/BeaconMarker-test.tsx.snap
  test/components/views/beacon/__snapshots__/BeaconStatus-test.tsx.snap
  test/components/views/context_menus/MessageContextMenu-test.tsx
  test/components/views/dialogs/ForwardDialog-test.tsx
  test/utils/EventUtils-test.ts
Labels: T-Enhancement

#8850 Improve homeserver dropdown dialog styling
  res/css/structures/_GenericDropdownMenu.scss
  res/css/views/directory/_NetworkDropdown.scss
Labels: T-Defect

#8812 Show chat panel when opening a video room with unread messages
  src/components/structures/LoggedInView.tsx
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/views/right_panel/EncryptionPanel.tsx
  src/components/views/right_panel/HeaderButtons.tsx
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/stores/ReadyWatchingStore.ts
  src/stores/right-panel/RightPanelStore.ts
  test/components/structures/RightPanel-test.tsx
  test/components/structures/RoomView-test.tsx
  test/stores/right-panel/RightPanelStore-test.ts
Labels: T-Enhancement

#8766 Move EventTile style rules of compact modern layout, enabling it on the right panel as well
  res/css/_components.scss
  res/css/structures/_RoomView.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_GroupLayout.scss
Labels: T-Task

#8864 Remove inline start margin from display name in reply tile on the timeline with a maximized widget
  res/css/views/right_panel/_TimelineCard.scss
Labels: Z-Community-PR, T-Defect

#8865 Fix position of message action bar on the info tile on TimelineCard in message bubble layout
  res/css/views/right_panel/_BaseCard.scss
  res/css/views/right_panel/_TimelineCard.scss
Labels: Z-Community-PR, T-Defect

#8869 Improve _InviteDialog.scss by applying spacing variables
  res/css/views/dialogs/_InviteDialog.scss
Labels: Z-Community-PR, T-Task

#8871 Use spacing variables on _SpotlightDialog.scss
  res/css/views/dialogs/_SpotlightDialog.scss
Labels: Z-Community-PR, T-Task

#8870 Hide overflow of public room description on spotlight dialog result
  res/css/views/dialogs/_SpotlightDialog.scss
Labels: Z-Community-PR, T-Defect

#8744 Make the pill text single line
  res/css/views/elements/_Pill.scss
  res/css/views/elements/_ReplyChain.scss
  res/css/views/rooms/_BasicMessageComposer.scss
  src/components/views/elements/Pill.tsx
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
Labels: Z-Community-PR, T-Defect

#8872 Stop using absolute property to place beta pill on RoomPreviewCard
  res/css/views/rooms/_RoomPreviewCard.scss
  src/components/views/rooms/RoomPreviewCard.tsx
Labels: Z-Community-PR, T-Defect

#8873 Move the beta pill to the right side and display the pill on video room only
  res/css/views/rooms/_RoomPreviewCard.scss
  src/components/views/rooms/RoomPreviewCard.tsx
Labels: Z-Community-PR, T-Defect

#8874 Fix alignment of pill letter
  res/css/views/rooms/_BasicMessageComposer.scss
Labels: Z-Community-PR, T-Defect

#8867 Set 100% max-width to display name on reply tiles
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_IRCLayout.scss
Labels: Z-Community-PR, T-Defect

#8875 Remove references to mx_GroupLayout from scss files
  res/css/views/elements/_EventTilePreview.scss
  res/css/views/rooms/_ReadReceiptGroup.scss
  src/components/views/elements/EventTilePreview.tsx
  test/components/views/settings/__snapshots__/FontScalingPanel-test.tsx.snap
Labels: Z-Community-PR, T-Defect

#8866 Implement MSC3827: Filtering of `/publicRooms` by room type
  res/css/views/dialogs/_SpotlightDialog.scss
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
  src/components/views/spaces/SpaceSettingsVisibilityTab.tsx
  src/hooks/usePublicRoomDirectory.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Enhancement

#8890 Run 'yarn rethemendex'
  res/css/_components.scss
Labels: Z-Community-PR, T-Task

#8893 Disable option to `Quote` when we don't have sufficient permissions
  src/components/views/context_menus/MessageContextMenu.tsx
Labels: T-Defect

#8876 Remove mx_GroupLayout
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/structures/ThreadView.tsx
  src/components/views/dialogs/ForwardDialog.tsx
  src/components/views/right_panel/TimelineCard.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/utils/exportUtils/HtmlExport.tsx
Labels: Z-Community-PR, T-Task

#8888 Improve integration manager dialog style
  res/css/views/settings/_IntegrationManager.scss
  src/components/views/settings/IntegrationManager.tsx
Labels: Z-Community-PR, T-Enhancement

#8889 Display description of E2E advanced panel as subsection text
  res/css/_components.scss
  res/css/views/settings/_E2eAdvancedPanel.scss
  src/components/views/settings/E2eAdvancedPanel.tsx
Labels: Z-Community-PR, T-Defect

#8892 Remove inline margin from "From a thread" (ThreadSummaryIcon) on search result panel on IRC layout
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_IRCLayout.scss
Labels: Z-Community-PR, T-Defect

#8886 Stop using :not() pseudo class for mx_MImageBody to decrease the specificity of the rule for images on file panel
  res/css/structures/_FilePanel.scss
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Defect

#8887 Improve font scaling panel style
  res/css/views/elements/_EventTilePreview.scss
  res/css/views/settings/_FontScalingPanel.scss
  res/css/views/settings/tabs/user/_AppearanceUserSettingsTab.scss
  src/components/views/settings/FontScalingPanel.tsx
  test/components/views/settings/__snapshots__/FontScalingPanel-test.tsx.snap
Labels: Z-Community-PR, T-Task

#8880 Ensure the max width value of the tooltip is used only on settings tabs
  res/css/_common.scss
  res/css/views/settings/_SetIdServer.scss
  res/css/views/settings/tabs/_SettingsTab.scss
Labels: Z-Community-PR, T-Task

#8883 Improve view source dialog style
  res/css/structures/_ViewSource.scss
  src/components/structures/ViewSource.tsx
Labels: Z-Community-PR, T-Enhancement

#8891 Remove inline margin from reactions row on IRC layout
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_IRCLayout.scss
Labels: Z-Community-PR, T-Defect

#8894 Move mx_EventTile_avatar style rules out of ":not([data-layout=bubble])"
  res/css/views/right_panel/_TimelineCard.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_IRCLayout.scss
Labels: Z-Community-PR, T-Task

#8884 Clarify style rule structure of ProfileSettings to avoid unexpected regressions
  res/css/views/settings/_ProfileSettings.scss
  src/components/views/room_settings/RoomProfileSettings.tsx
  src/components/views/settings/ProfileSettings.tsx
Labels: Z-Community-PR, T-Task

#8895 Move mx_EventTile_e2eIcon style out of mx_EventTile:not([data-layout=bubble])
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_IRCLayout.scss
Labels: Z-Community-PR, T-Task

#8877 Use a variable to ensure the margin declaration is applied to components on mx_SettingsTab only
  res/css/_common.scss
  res/css/views/settings/_FontScalingPanel.scss
  res/css/views/settings/_ProfileSettings.scss
  res/css/views/settings/_SetIdServer.scss
  res/css/views/settings/_SpellCheckLanguages.scss
  res/css/views/settings/tabs/_SettingsTab.scss
  res/css/views/settings/tabs/user/_GeneralUserSettingsTab.scss
  res/css/views/settings/tabs/user/_MjolnirUserSettingsTab.scss
  res/css/views/settings/tabs/user/_PreferencesUserSettingsTab.scss
  res/css/views/settings/tabs/user/_VoiceUserSettingsTab.scss
Labels: Z-Community-PR, T-Task

#8896 rethemendex: use /usr/bin/env
  res/css/rethemendex.sh
Labels: Z-Community-PR, T-Task

#8900 Remove a special declaration about position of avatars on TimelineCard
  res/css/views/right_panel/_TimelineCard.scss
Labels: Z-Community-PR, T-Defect

#8878 Improve SetIntegrationManager
  res/css/views/elements/_ToggleSwitch.scss
  res/css/views/settings/_SetIntegrationManager.scss
  res/css/views/settings/tabs/_SettingsTab.scss
  src/components/views/settings/SetIdServer.tsx
  src/components/views/settings/SetIntegrationManager.tsx
Labels: Z-Community-PR, T-Task

#8901 Move styles on TimelineCard out of mx_EventTile:not([data-layout=bubble])
  res/css/views/right_panel/_TimelineCard.scss
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Task

#8863 Stop setting `auto_join` on space child events
  src/stores/spaces/SpaceStore.ts
Labels: T-Task

#8882 Tidy up styles on _EventTile.scss
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Task

#8840 Revert recent composer changes
  res/css/_components.scss
  res/css/structures/_RoomView.scss
  res/css/views/buttons/_Cancel.scss
  res/css/views/rooms/_MessageComposer.scss
  res/css/views/rooms/_ReplyPreview.scss
  res/css/views/rooms/_SendMessageComposer.scss
  res/img/cancel.svg
  res/img/element-icons/room/message-bar/reply.svg
  res/img/element-icons/room/room-summary.svg
  res/img/element-icons/x-8px.svg
  src/components/views/buttons/Cancel.tsx
  src/components/views/messages/DisambiguatedProfile.tsx
  src/components/views/messages/SenderProfile.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/ReplyPreview.tsx
  src/components/views/rooms/ReplyTile.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/MessageComposer-test.tsx
Labels: X-Release-Blocker, T-Task

#8905 Live location sharing - render message deleted tile for redacted beacons (PSF-1150)
  src/utils/beacon/timeline.ts
  test/utils/beacon/timeline-test.ts
Labels: T-Enhancement

#8904 Maximize width value of display name on TimelineCard with IRC/modern layout
  res/css/views/right_panel/_TimelineCard.scss
Labels: Z-Community-PR, T-Defect

#8908 Don't overlap tile bubbles with timestamps in modern layout
  res/css/views/messages/_EventTileBubble.scss
Labels: T-Defect

#8917 Keep clicks on pills within the app
  cypress/integration/13-regression-tests/pills-click-in-app.spec.ts
  res/css/views/elements/_Pill.scss
Labels: X-Release-Blocker, T-Defect

#8918 Disable pointer events for replies to locations
  res/css/components/views/messages/_MBeaconBody.scss
  res/css/views/messages/_MLocationBody.scss
Labels: T-Defect

#8919 Correct issue with tab order in new search experience
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
Labels: T-Defect

#8859 Move New Search Experience out of beta
  cypress/integration/12-spotlight/spotlight.spec.ts
  res/css/structures/_RoomSearch.scss
  res/css/views/dialogs/_SpotlightDialog.scss
  res/img/betas/new_search_experience.gif
  src/accessibility/KeyboardShortcuts.ts
  src/components/structures/LeftPanel.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomSearch.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Enhancement

#8713 Move style rules of GenericEventListSummary from _EventBubbleTile.scss to _GenericEventListSummary.scss
  res/css/views/elements/_GenericEventListSummary.scss
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_IRCLayout.scss
Labels: Z-Community-PR, T-Task

#8914 Update matrix-web-i18n
  package.json
  yarn.lock
Labels: T-Task

#8915 Improve timing safety of useLatestResult test
  test/hooks/useLatestResult-test.tsx
Labels: T-Task

#8910 Move mx_EventTile_line and mx_EventTile_reply out of mx_EventTile:not([data-layout=bubble])
  res/css/views/right_panel/_TimelineCard.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_IRCLayout.scss
Labels: Z-Community-PR, T-Task

#8928 Live location share - disallow message pinning (PSF-1084)
  src/components/views/context_menus/MessageContextMenu.tsx
  src/events/forward/getForwardableBeacon.ts
  src/utils/EventUtils.ts
  test/components/views/context_menus/MessageContextMenu-test.tsx
Labels: T-Enhancement

#8921 Correct new search input’s rounded corners
  res/css/views/dialogs/_SpotlightDialog.scss
Labels: T-Defect

#8924 Remove unpin from widget kebab menu
  src/components/views/context_menus/WidgetContextMenu.tsx
Labels: T-Enhancement

#8913 Reduce video rooms log spam
  src/stores/VideoChannelStore.ts
  src/stores/widgets/StopGapWidget.ts
  test/stores/VideoChannelStore-test.ts
Labels: T-Defect

#8936 Update MSC3827 implementation to not change the default behaviour
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/hooks/usePublicRoomDirectory.ts
Labels: T-Defect
