Repository matrix-org/matrix-react-sdk, pull requests merged in 2022-05, with the labels that each got.

#8247 Fix text link buttons on UserInfo panel
  res/css/views/right_panel/_UserInfo.scss
  src/components/views/right_panel/UserInfo.tsx
Labels: T-Defect

#8262 fix timeline search with empty text box should do nothing
  src/components/views/rooms/SearchBar.tsx
  test/components/views/rooms/SearchBar-test.tsx
Labels: T-Defect

#8460 Fix jump to bottom button being always displayed in non-overflowing timelines
  src/components/structures/RoomView.tsx
  src/components/structures/TimelinePanel.tsx
  src/contexts/RoomContext.ts
  test/components/views/rooms/MessageComposerButtons-test.tsx
Labels: X-Release-Blocker, T-Defect

#8454 Clear local storage settings handler cache on logout
  src/Lifecycle.ts
  src/settings/handlers/AbstractLocalStorageSettingsHandler.ts
Labels: T-Defect

#8327 Test typescriptification continued
  test/utils/MegolmExportEncryption-test.ts
  test/utils/ShieldUtils-test.ts
Labels: T-Task

#8459 Fix poll overflowing a reply tile on bubble message layout
  res/css/views/rooms/_EventBubbleTile.scss
Labels: T-Defect

#8438 read receipts: improve tooltips to show names of users
  src/components/views/rooms/ReadReceiptGroup.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/ReadReceiptGroup-test.tsx
Labels: T-Defect

#7859 Don't linkify code blocks
  src/linkify-matrix.ts
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
Labels: T-Defect

#8469 test typescriptification - ForwardDialog
  test/components/stub-component.js
  test/components/views/dialogs/ForwardDialog-test.tsx
Labels: T-Task

#8465 Live location sharing: remove geoUri logs
  src/components/views/location/Map.tsx
  test/components/views/location/Map-test.tsx
Labels: T-Task

#8468 Live location sharing: don't group beacon info with room creation summary
  src/components/structures/MessagePanel.tsx
  test/components/structures/MessagePanel-test.js
Labels: T-Defect

#8472 Iterate CI checks
  .github/workflows/preview_changelog.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/static_analysis.yaml
Labels: T-Task

#8415 Initial doc for cypress tests
  docs/cypress.md
Labels: T-Task

#8462 fix text and map indent in thread view
  res/css/views/rooms/_EventTile.scss
  src/components/views/messages/MLocationBody.tsx
  test/components/views/messages/__snapshots__/MLocationBody-test.tsx.snap
Labels: T-Defect

#8466 Location sharing: do not trackuserlocation in location picker
  src/components/views/location/LocationPicker.tsx
Labels: T-Defect

#8448 Fix race conditions around threads
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/structures/ThreadView.tsx
  src/components/views/rooms/EventTile.tsx
  src/stores/notifications/ThreadsRoomNotificationState.ts
  src/utils/EventUtils.ts
  test/test-utils/test-utils.ts
  test/test-utils/threads.ts
Labels: T-Defect

#8452 Specify position of DisambiguatedProfile inside a thread on bubble message layout
  res/css/views/rooms/_EventBubbleTile.scss
Labels: T-Defect

#8475 Tweak sonarqube run
  .github/workflows/sonarqube.yml
  sonar-project.properties
Labels: T-Task

#8476 Match MSC behaviour for threads when disabled (thread-aware mode)
  src/utils/Reply.ts
Labels: T-Defect

#8473 Fix issue with dispatch happening mid-dispatch due to js-sdk emit
  src/actions/MatrixActionCreators.ts
Labels: T-Defect

#8477 Prevent Netlify builds from different PRs stepping on each other
  .github/workflows/netlify.yaml
Labels: T-Task

#8480 Test typescriptification - Terms/ScalarAuthClient
  test/ScalarAuthClient-test.ts
  test/Terms-test.tsx
Labels: T-Task

#8479 Prune i18n files
  .github/workflows/static_analysis.yaml
  src/i18n/strings/cs.json
  src/i18n/strings/eo.json
  src/i18n/strings/es.json
  src/i18n/strings/et.json
  src/i18n/strings/fr.json
  src/i18n/strings/gl.json
  src/i18n/strings/hu.json
  src/i18n/strings/id.json
  src/i18n/strings/is.json
  src/i18n/strings/it.json
  src/i18n/strings/ja.json
  src/i18n/strings/nl.json
  src/i18n/strings/ru.json
  src/i18n/strings/sk.json
  src/i18n/strings/sv.json
  src/i18n/strings/uk.json
  src/i18n/strings/zh_Hant.json
Labels: T-Task

#8482 Fix forwarding UI papercuts
  res/css/views/dialogs/_ForwardDialog.scss
  src/components/views/dialogs/ForwardDialog.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#8458 Add README badges
  README.md
Labels: T-Task

#8484 Create manual action for upgrading dependencies after rc cut
  .github/workflows/upgrade_dependencies.yml
Labels: T-Task

#8487 Update upgrade_dependencies.yml
  .github/workflows/upgrade_dependencies.yml
Labels: T-Task

#8481 test typescriptification - Permalinks
  test/utils/permalinks/Permalinks-test.js
  test/utils/permalinks/Permalinks-test.ts
Labels: T-Task

#8492 Attempt to fix the cypress flake
  cypress/integration/1-register/register.spec.ts
  cypress/plugins/index.ts
  cypress/plugins/synapsedocker/index.ts
  cypress/support/index.ts
  cypress/support/synapse.ts
Labels: T-Task

#8494 Create more cypress tests and utilities
  cypress/integration/1-register/register.spec.ts
  cypress/integration/2-login/login.spec.ts
  cypress/integration/3-user-menu/user-menu.spec.ts
  cypress/plugins/synapsedocker/index.ts
  cypress/plugins/synapsedocker/templates/consent/homeserver.yaml
  cypress/support/index.ts
  cypress/support/login.ts
  cypress/support/synapse.ts
  docs/cypress.md
Labels: T-Task

#8493 test typescriptification - EventListSummary
  test/components/views/elements/EventListSummary-test.tsx
  test/components/views/right_panel/UserInfo-test.tsx
  test/test-utils/client.ts
Labels: T-Task

#8491 Fix reading of cached room device setting values
  src/settings/handlers/RoomDeviceSettingsHandler.ts
  test/settings/handlers/RoomDeviceSettingsHandler-test.ts
Labels: X-Release-Blocker, T-Defect

#8496 Fix soft crash around threads when room isn't yet in store
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#8498 Tweak sonar-project.properties
  scripts/fetchdep.sh
  sonar-project.properties
Labels: T-Task

#8499 Iterate video room designs in labs
  res/css/_components.scss
  res/css/structures/_SpaceRoomView.scss
  res/css/structures/_VideoRoomView.scss
  res/css/views/elements/_FacePile.scss
  res/css/views/rooms/_RoomInfoLine.scss
  res/css/views/rooms/_RoomPreviewCard.scss
  src/components/structures/RoomView.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/structures/VideoRoomView.tsx
  src/components/views/context_menus/SpaceContextMenu.tsx
  src/components/views/elements/FacePile.tsx
  src/components/views/rooms/RoomInfoLine.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomListHeader.tsx
  src/components/views/rooms/RoomPreviewCard.tsx
  src/createRoom.ts
  src/hooks/useRoomMembers.ts
  src/i18n/strings/en_EN.json
  test/components/structures/VideoRoomView-test.tsx
  test/createRoom-test.ts
Labels: T-Enhancement

#8500 Disconnect from video rooms when leaving
  src/stores/VideoChannelStore.ts
Labels: T-Defect

#8447 Add raw error to analytics E2E error event context
  src/DecryptionFailureTracker.ts
  test/DecryptionFailureTracker-test.js
Labels: T-Task

#8467 Grammar fix: by it's administrator -> by its administrator
  src/components/structures/RoomStatusBar.tsx
  src/components/structures/auth/Login.tsx
  src/components/structures/auth/Registration.tsx
  src/i18n/strings/en_EN.json
  src/toasts/ServerLimitToast.tsx
Labels: T-Task

#7672 Add a way to maximize/pin widget from the PiP view
  res/css/views/voip/_CallViewHeader.scss
  src/components/views/voip/CallView.tsx
  src/components/views/voip/CallView/CallViewHeader.tsx
  src/components/views/voip/PipView.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#6398 Improve pills
  res/css/_components.scss
  res/css/structures/_RoomDirectory.scss
  res/css/views/elements/_Pill.scss
  res/css/views/elements/_RichText.scss
  res/css/views/rooms/_BasicMessageComposer.scss
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light-custom/css/_custom.scss
  res/themes/light/css/_light.scss
  src/components/views/elements/Pill.tsx
  src/components/views/elements/ReplyChain.tsx
  src/components/views/settings/BridgeTile.tsx
  src/editor/parts.ts
  src/utils/pillify.tsx
Labels: T-Enhancement

#8444 Order new search dialog results by recency
  src/components/views/dialogs/SpotlightDialog.tsx
  src/stores/room-list/algorithms/tag-sorting/RecentAlgorithm.ts
  test/stores/room-list/algorithms/RecentAlgorithm-test.ts
Labels: T-Enhancement

#8506 Order receipts with the most recent on the right
  src/components/views/rooms/ReadReceiptGroup.tsx
  test/components/views/rooms/ReadReceiptGroup-test.tsx
Labels: T-Defect

#8505 Fix pills on bubble layout being cut-off
  res/css/views/elements/_Pill.scss
Labels: T-Defect

#8504 Fix inviting users with undisclosed profiles
  src/utils/MultiInviter.ts
  test/utils/MultiInviter-test.ts
Labels: T-Defect

#8509 Enlarge emoji again
  res/css/views/elements/_RichText.scss
Labels: T-Defect

#8497 test typescriptification - dialogs
  test/components/views/dialogs/AccessSecretStorageDialog-test.js
  test/components/views/dialogs/AccessSecretStorageDialog-test.tsx
  test/components/views/dialogs/InteractiveAuthDialog-test.js
  test/components/views/dialogs/InteractiveAuthDialog-test.tsx
Labels: T-Task

#8445 Remove experimental threads disclaimer
  src/components/structures/MatrixChat.tsx
  src/i18n/strings/en_EN.json
  test/end-to-end-tests/src/usecases/threads.ts
Labels: T-Task

#8511 Spaces: remove blue beta dot
  src/components/views/spaces/SpacePanel.tsx
Labels: T-Enhancement

#8514 Eslint - require copyright header rule
  .eslintrc.js
  package.json
  src/NodeAnimator.tsx
  src/components/views/elements/AppWarning.tsx
  src/components/views/elements/ResizeHandle.tsx
  src/usercontent/index.ts
  src/utils/useTooltip.tsx
  src/utils/validate/index.ts
  src/utils/validate/numberInRange.ts
  test/.eslintrc.js
  test/TextForEvent-test.ts
  test/components/views/elements/EventListSummary-test.tsx
  test/components/views/elements/TooltipTarget-test.tsx
  test/components/views/rooms/ReadReceiptGroup-test.tsx
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/RoomList-test.js
  test/components/views/settings/CryptographyPanel-test.tsx
  test/components/views/spaces/SpaceSettingsVisibilityTab-test.tsx
  test/components/views/typography/Heading-test.tsx
  test/globalSetup.js
  test/i18n-test/languageHandler-test.tsx
  test/setupTests.js
  test/test-utils/index.ts
  test/test-utils/test-utils.ts
  test/utils/validate/numberInRange-test.ts
  yarn.lock
Labels: T-Task

#8515 Live location sharing - refresh beacon timers on tab becoming active
  src/components/views/beacon/LeftPanelLiveShareWarning.tsx
  test/components/views/beacon/LeftPanelLiveShareWarning-test.tsx
Labels: T-Defect

#8513 Add a way to toggle `ScrollPanel` and `TimelinePanel` debug logs
  src/components/structures/ScrollPanel.tsx
  src/components/structures/TimelinePanel.tsx
  src/settings/Settings.tsx
Labels: T-Enhancement

#8520 Fix thread summary overflow on narrow message panel on bubble message layout
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#8516 Simplify ReplyPreview UI implementation
  res/css/views/rooms/_ReplyPreview.scss
  src/components/views/rooms/ReplyPreview.tsx
Labels: T-Defect

#8519 Set max-width for MLocationBody and MLocationBody_map by default
  res/css/views/messages/_MLocationBody.scss
Labels: T-Defect

#8521 Remove some labs features which don't get used or create maintenance burden: custom status, multiple integration managers, and do not disturb
  res/css/_components.scss
  res/css/views/dialogs/_TabbedIntegrationManagerDialog.scss
  src/Notifier.ts
  src/components/structures/UserMenu.tsx
  src/components/views/dialogs/TabbedIntegrationManagerDialog.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/MemberTile.tsx
  src/components/views/rooms/Stickerpicker.tsx
  src/dispatcher/actions.ts
  src/dispatcher/payloads/OpenTabbedIntegrationManagerDialogPayload.ts
  src/hooks/useUserStatusMessage.ts
  src/i18n/strings/en_EN.json
  src/integrations/IntegrationManagers.ts
  src/settings/Settings.tsx
  src/settings/controllers/CustomStatusController.ts
  src/stores/room-list/algorithms/tag-sorting/RecentAlgorithm.ts
  src/stores/widgets/StopGapWidget.ts
  src/utils/DialogOpener.ts
  src/utils/WidgetUtils.ts
Labels: T-Enhancement

#8522 Move widget screenshots labs flag to devtools
  src/components/views/context_menus/WidgetContextMenu.tsx
  src/components/views/dialogs/DevtoolsDialog.tsx
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
  src/utils/WidgetUtils.ts
Labels: T-Enhancement

#7993 Implement changes to MSC2285 (private read receipts)
  src/components/structures/MessagePanel.tsx
  src/components/structures/TimelinePanel.tsx
  src/utils/Receipt.ts
  src/utils/read-receipts.ts
Labels: T-Task

#8512 Remove duplicate tooltip from user pills
  src/components/views/elements/Pill.tsx
  src/utils/WidgetUtils.ts
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
Labels: T-Defect

#8453 Set the same margin to the right side of NewRoomIntro on TimelineCard
  res/css/views/right_panel/_TimelineCard.scss
Labels: T-Defect

#8485 Fix unexpected and inconsistent inheritance of line-height property for mx_TextualEvent
  res/css/views/messages/_TextualEvent.scss
Labels: T-Defect

#8464 Fix position of timestamp on the chat panel in IRC layout and message edits history modal window
  res/css/views/dialogs/_MessageEditHistoryDialog.scss
  res/css/views/messages/_MessageTimestamp.scss
  res/css/views/right_panel/_TimelineCard.scss
  res/css/views/rooms/_GroupLayout.scss
  res/css/views/rooms/_IRCLayout.scss
Labels: T-Defect

#8518 Replace message composer menu with IconizedContextMenu
  res/css/views/rooms/_MessageComposer.scss
  src/components/views/location/LocationButton.tsx
  src/components/views/rooms/CollapsibleButton.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
Labels: T-Defect

#8526 Create a mixin of cancel button
  res/css/_common.scss
  res/css/structures/auth/_CompleteSecurity.scss
  res/css/views/dialogs/_CompoundDialog.scss
  res/css/views/elements/_EditableItemList.scss
  res/css/views/right_panel/_VerificationPanel.scss
  res/css/views/voip/_DialPadContextMenu.scss
  res/css/views/voip/_DialPadModal.scss
Labels: T-Task

#8242 Converting selected text to MD link when pasting a URL
  src/components/views/rooms/BasicMessageComposer.tsx
  src/editor/operations.ts
Labels: T-Enhancement

#8527 Add a `Copy link` button to the right-click message context-menu labs feature
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#8529 Set line-height: 1 to RedactedBody inside GenericEventListSummary for IRC/modern layout
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_GroupLayout.scss
Labels: T-Defect

#8523 Add global spacing between display name and location body
  res/css/views/messages/_MLocationBody.scss
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#8397 Add box-shadow to the reply preview on the main (left) panel only
  res/css/views/rooms/_ReplyPreview.scss
Labels: T-Defect

#8399 Support Inter on custom themes
  res/css/views/beta/_BetaCard.scss
  res/themes/legacy-light/css/_fonts.scss
Labels: T-Enhancement

#8535 LLS - fix code smells
  src/components/views/beacon/LeftPanelLiveShareWarning.tsx
Labels: T-Task

#8537 Fix regression around pasting links
  src/components/views/rooms/BasicMessageComposer.tsx
  src/editor/dom.ts
  src/editor/operations.ts
  test/components/views/rooms/BasicMessageComposer-test.tsx
  test/editor/mock.ts
  test/editor/operations-test.ts
Labels: T-Defect

#8474 Improve welcome screen, add opt-out analytics
  src/components/structures/HomePage.tsx
  src/components/views/elements/MiniAvatarUploader.tsx
Labels: T-Enhancement

#8541 Handle Jitsi Meet crashes more gracefully
  src/stores/VideoChannelStore.ts
Labels: T-Defect

#8543 update matrix-analytics-events
  package.json
  yarn.lock
Labels: T-Defect

#8544 Add cypress badge
  README.md
Labels: T-Task

#8546 Don't leave button tooltips open when closing modals
  src/components/views/elements/AccessibleTooltipButton.tsx
Labels: T-Defect

#8524 Run a minor code quality checker over the repo
  src/BasePlatform.ts
  src/CallHandler.tsx
  src/HtmlUtils.tsx
  src/ImageUtils.ts
  src/Rooms.ts
  src/async-components/views/dialogs/security/CreateKeyBackupDialog.tsx
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/views/auth/CountryDropdown.tsx
  src/components/views/beacon/LeftPanelLiveShareWarning.tsx
  src/components/views/beacon/RoomLiveShareWarning.tsx
  src/components/views/dialogs/BulkRedactDialog.tsx
  src/components/views/dialogs/ExportDialog.tsx
  src/components/views/dialogs/KeySignatureUploadFailedDialog.tsx
  src/components/views/dialogs/ShareDialog.tsx
  src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/elements/ErrorBoundary.tsx
  src/components/views/elements/LanguageDropdown.tsx
  src/components/views/elements/ReplyChain.tsx
  src/components/views/elements/SpellCheckLanguagesDropdown.tsx
  src/components/views/elements/TruncatedList.tsx
  src/components/views/messages/MImageBody.tsx
  src/components/views/rooms/AppsDrawer.tsx
  src/components/views/rooms/AuxPanel.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/toasts/VerificationRequestToast.tsx
  src/dispatcher/payloads/ComposerInsertPayload.ts
  src/editor/dom.ts
  src/editor/operations.ts
  src/i18n/strings/en_EN.json
  src/indexing/BaseEventIndexManager.ts
  src/indexing/EventIndex.ts
  src/indexing/EventIndexPeg.ts
  src/integrations/IntegrationManagerInstance.ts
  src/notifications/VectorPushRulesDefinitions.ts
  src/settings/watchers/ThemeWatcher.ts
  src/stores/OwnBeaconStore.ts
  src/stores/RoomViewStore.tsx
  src/stores/WidgetEchoStore.ts
  src/stores/spaces/flattenSpaceHierarchy.ts
  src/stores/widgets/WidgetMessagingStore.ts
  src/utils/DMRoomMap.ts
  src/utils/ErrorUtils.tsx
  src/utils/FileUtils.ts
  src/utils/LazyValue.ts
  src/utils/Singleflight.ts
  src/utils/beacon/useBeacon.ts
  src/utils/direct-messages.ts
  src/utils/exportUtils/exportCustomCSS.css
  src/utils/permalinks/ElementPermalinkConstructor.ts
  src/utils/permalinks/Permalinks.ts
  test/components/views/beacon/LeftPanelLiveShareWarning-test.tsx
  test/components/views/beacon/RoomLiveShareWarning-test.tsx
  test/components/views/beacon/__snapshots__/LeftPanelLiveShareWarning-test.tsx.snap
  test/components/views/beacon/__snapshots__/RoomLiveShareWarning-test.tsx.snap
Labels: T-Task

#6899 Fix style of "search initialisation failed" message
  res/css/_components.scss
  res/css/views/elements/_SearchWarning.scss
  src/components/structures/FilePanel.tsx
  src/components/views/elements/SearchWarning.tsx
  src/components/views/rooms/SearchBar.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/SearchBar-test.tsx
Labels: T-Defect

#8547 Set color-scheme property in themes
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light/css/_light.scss
Labels: T-Defect

#8502 Log `TimelinePanel` debugging info when opening the bug report modal
  src/components/structures/TimelinePanel.tsx
  src/components/views/dialogs/BugReportDialog.tsx
  src/components/views/rooms/EventTile.tsx
  src/dispatcher/actions.ts
Labels: T-Enhancement

#8510 Document what all of our "Pegs" are (just singletons)
  src/MatrixClientPeg.ts
  src/PlatformPeg.ts
  src/indexing/EventIndexPeg.ts
Labels: T-Task

#8545 Fix the look of pills
  res/css/views/elements/_Pill.scss
Labels: T-Defect

#8549 Fix unresponsive notification toggles
  src/components/views/settings/Notifications.tsx
  src/settings/handlers/AbstractLocalStorageSettingsHandler.ts
  src/settings/handlers/DeviceSettingsHandler.ts
  test/components/views/settings/Notifications-test.tsx
Labels: T-Defect

#8552 [Release] Fix unresponsive notification toggles
  src/components/views/settings/Notifications.tsx
  src/settings/handlers/AbstractLocalStorageSettingsHandler.ts
  src/settings/handlers/DeviceSettingsHandler.ts
  test/components/views/settings/Notifications-test.tsx
Labels: X-Release-Blocker, T-Defect

#8551 use isLocationEvent util everywhere
  src/TextForEvent.tsx
  src/utils/EventRenderingUtils.ts
Labels: T-Task

#8553 Enable forwarding static locations
  src/components/views/dialogs/ForwardDialog.tsx
  src/utils/EventUtils.ts
  test/components/views/dialogs/ForwardDialog-test.tsx
  test/test-utils/location.ts
  test/utils/EventUtils-test.ts
Labels: T-Enhancement

#8548 Only jump to date after pressing the 'go' button
  src/components/views/elements/Field.tsx
  src/components/views/elements/NativeOnChangeInput.tsx
  src/components/views/messages/JumpToDatePicker.tsx
  src/hooks/useCombinedRefs.ts
Labels: T-Defect

#8388 Align thread summary button with bubble messages on the left side
  res/css/views/rooms/_EventBubbleTile.scss
Labels: T-Defect

#8501 Move threads e2e tests over to cypress
  cypress.json
  cypress/global.d.ts
  cypress/integration/2-login/consent.spec.ts
  cypress/integration/3-user-menu/user-menu.spec.ts
  cypress/integration/4-create-room/create-room.spec.ts
  cypress/integration/5-threads/threads.spec.ts
  cypress/plugins/synapsedocker/templates/default/README.md
  cypress/plugins/synapsedocker/templates/default/homeserver.yaml
  cypress/plugins/synapsedocker/templates/default/log.config
  cypress/support/bot.ts
  cypress/support/client.ts
  cypress/support/index.ts
  cypress/support/login.ts
  cypress/support/settings.ts
  cypress/support/synapse.ts
  docs/cypress.md
  package.json
  src/@types/global.d.ts
  src/Lifecycle.ts
  src/components/structures/TimelinePanel.tsx
  src/dispatcher/dispatcher.ts
  src/stores/RoomViewStore.tsx
  src/utils/StorageManager.ts
  test/end-to-end-tests/src/scenario.ts
  test/end-to-end-tests/src/scenarios/threads.ts
  test/end-to-end-tests/src/usecases/threads.ts
  yarn.lock
Labels: T-Task

#8556 Fix download button not working on events that were decrypted too late
  src/components/views/messages/MessageEvent.tsx
Labels: T-Defect

#8557 Fix pills in the composer having too much left padding
  res/css/views/elements/_Pill.scss
Labels: T-Defect

#8538 Hide recently_viewed dropdown when other modal opens
  res/css/views/elements/_InteractiveTooltip.scss
Labels: T-Defect

#8525 Hide the verification left stroke only on the thread list
  res/css/views/right_panel/_ThreadPanel.scss
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#8559 Remove redundant checkKey parameter
  src/stores/SetupEncryptionStore.ts
Labels: T-Task

#8320 Fix the width bounce of the clock on the AudioPlayer
  res/css/views/audio_messages/_AudioPlayer.scss
Labels: T-Defect

#8561 Fix effect of URL preview toggle not updating live
  src/components/structures/RoomView.tsx
  src/components/structures/TimelinePanel.tsx
  src/contexts/RoomContext.ts
  test/components/views/rooms/MessageComposerButtons-test.tsx
Labels: T-Defect

#8564 Update thread summary when latest event gets decrypted
  src/components/views/rooms/ThreadSummary.tsx
Labels: T-Defect

#8532 Write tests for message right-click context menu
  test/components/views/context_menus/MessageContextMenu-test.tsx
Labels: T-Task

#8565 Fix oblong avatars in video room lobbies
  res/css/views/avatars/_BaseAvatar.scss
Labels: T-Defect

#8555 Fix displaying hidden events on threads
  res/css/views/right_panel/_ThreadPanel.scss
  res/css/views/rooms/_EventTile.scss
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#8567 Tidy checkForPreJoinUISI and add some logging
  src/components/structures/TimelinePanel.tsx
Labels: T-Task

#7963 Standardise the margin for settings tabs
  res/css/views/settings/_ProfileSettings.scss
  res/css/views/settings/tabs/_SettingsTab.scss
  res/css/views/settings/tabs/user/_AppearanceUserSettingsTab.scss
  res/css/views/settings/tabs/user/_SecurityUserSettingsTab.scss
  res/css/views/settings/tabs/user/_SidebarUserSettingsTab.scss
Labels: T-Defect

#8483 Improve message editing UI
  res/css/views/rooms/_EditMessageComposer.scss
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_EventTile.scss
Labels: T-Enhancement

#8219 Improve tooltip positioning
  res/css/views/elements/_MiniAvatarUploader.scss
  res/css/views/elements/_Tooltip.scss
  res/css/views/rooms/_RoomSublist.scss
  src/components/structures/SpaceHierarchy.tsx
  src/components/views/beta/BetaCard.tsx
  src/components/views/dialogs/ForwardDialog.tsx
  src/components/views/elements/AccessibleTooltipButton.tsx
  src/components/views/elements/FacePile.tsx
  src/components/views/elements/Tooltip.tsx
  src/components/views/elements/TooltipTarget.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/ReadReceiptGroup.tsx
  src/components/views/voip/CallView/CallViewButtons.tsx
  test/components/views/elements/TooltipTarget-test.tsx
  test/components/views/elements/__snapshots__/TooltipTarget-test.tsx.snap
Labels: T-Defect

#8562 Fix button width and align 絵文字 (emoji) on the user panel
  res/css/views/right_panel/_VerificationPanel.scss
  src/components/views/right_panel/UserInfo.tsx
Labels: T-Defect

#8571 Change spaceroomfacepile tooltip if memberlist is shown
  src/components/structures/SpaceRoomView.tsx
  src/components/views/elements/RoomFacePile.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#8573 remove unused map util fn
  src/utils/location/map.ts
Labels: T-Task

#8517 Add dialog to navigate long room topics
  res/css/views/rooms/_RoomHeader.scss
  src/components/structures/SpaceRoomView.tsx
  src/components/views/elements/Linkify.tsx
  src/components/views/elements/RoomTopic.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomPreviewCard.tsx
  src/components/views/spaces/SpaceSettingsGeneralTab.tsx
  src/dispatcher/actions.ts
  src/hooks/room/useTopic.ts
  src/hooks/useHover.ts
  src/i18n/strings/en_EN.json
  test/components/views/elements/Linkify-test.tsx
  test/useTopic-test.tsx
Labels: T-Enhancement

#8581 Don't consider threads for breaking continuation until actually created
  src/components/structures/MessagePanel.tsx
  src/utils/EventUtils.ts
  test/components/structures/MessagePanel-test.js
Labels: T-Defect

#8582 Tweak video rooms copy
  src/components/structures/SpaceRoomView.tsx
  src/components/views/context_menus/SpaceContextMenu.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomListHeader.tsx
  src/components/views/rooms/RoomTile.tsx
  src/components/views/voip/VideoLobby.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/RoomTile-test.tsx
  test/components/views/voip/VideoLobby-test.tsx
Labels: T-Enhancement

#8568 Show full thread message in hover title on thread summary
  src/components/views/rooms/ThreadSummary.tsx
Labels: T-Enhancement

#7047 Iterate on search results for message bubbles
  res/css/views/rooms/_EventBubbleTile.scss
  src/components/views/rooms/EventTile.tsx
Labels: T-Enhancement

#8583 Increase composer line height to avoid cutting off emoji
  res/css/views/rooms/_SendMessageComposer.scss
Labels: T-Defect

#8585 Enable overflow of hidden events content
  res/css/views/messages/_ViewSourceEvent.scss
Labels: T-Defect

#8575 Center initial letter in pills
  res/css/views/elements/_Pill.scss
Labels: T-Defect

#8580 Make pull_request.yaml between the layers consistent and fix enforce labels
  .github/workflows/pull_request.yaml
Labels: T-Task

#8574 Fix padding of messages in threads
  res/css/views/right_panel/_BaseCard.scss
  res/css/views/right_panel/_ThreadPanel.scss
  res/css/views/right_panel/_TimelineCard.scss
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#8588 Fix js-sdk types
  src/RoomNotifs.ts
  test/RoomNotifs-test.ts
Labels: T-Task

#8589 Use reusable SonarCloud workflow
  .github/workflows/netlify.yaml
  .github/workflows/sonarqube.yml
Labels: T-Task

#8591 Fix MessageTimestamp position next to redacted messages on IRC/modern layout
  res/css/views/messages/_ViewSourceEvent.scss
  res/css/views/right_panel/_ThreadPanel.scss
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#6511 Show file name and size on images on hover
  res/css/views/elements/_ImageView.scss
  res/css/views/messages/_MImageBody.scss
  src/components/views/elements/ImageView.tsx
  src/components/views/messages/MFileBody.tsx
  src/components/views/messages/MImageBody.tsx
  src/i18n/strings/en_EN.json
  src/utils/FileUtils.ts
Labels: Sponsored, T-Enhancement

#8592 Fix avatar position of hidden event on ThreadView
  res/css/views/right_panel/_ThreadPanel.scss
Labels: T-Defect

#8593 Add right margin to pills
  res/css/views/elements/_Pill.scss
Labels: T-Defect

#8595 Stop spaces from displaying as rooms in new breadcrumbs
  res/css/views/avatars/_BaseAvatar.scss
Labels: T-Defect

#8594 Fix favourites metaspace not updating
  src/stores/spaces/SpaceStore.ts
Labels: T-Defect

#8596 Remove an obsolete declaration for DisambiguatedProfile of EventTile on modern layout
  res/css/views/right_panel/_TimelineCard.scss
Labels: T-Task

#8598 Fix not being able to open avatars in lightbox
  src/components/views/elements/ImageView.tsx
Labels: T-Defect

#8606 Don't show image metadata banner in replies
  res/css/views/messages/_MImageReplyBody.scss
Labels: T-Defect

#8576 Fix edge case thread summaries around events without a msgtype
  src/stores/room-list/MessagePreviewStore.ts
  src/stores/room-list/previews/IPreview.ts
  src/stores/room-list/previews/MessageEventPreview.ts
Labels: T-Defect

#8579 test typescriptification - fix ts issues in Registration-test
  test/components/structures/auth/Registration-test.tsx
Labels: T-Task

#8607 Don't show public indicator on spaces
  res/css/views/avatars/_BaseAvatar.scss
  src/components/views/rooms/RecentlyViewedButton.tsx
Labels: T-Defect

#8609 Fall back to untranslated string rather than showing missing translation error
  src/languageHandler.tsx
  test/components/views/settings/__snapshots__/KeyboardShortcut-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/KeyboardUserSettingsTab-test.tsx.snap
  test/i18n-test/languageHandler-test.tsx
Labels: T-Enhancement

#8587 Proactively fix stuck devices in video rooms
  src/Lifecycle.ts
  src/components/structures/VideoRoomView.tsx
  src/settings/Settings.tsx
  src/stores/VideoChannelStore.ts
  src/utils/VideoChannelUtils.ts
  test/components/structures/VideoRoomView-test.tsx
  test/stores/VideoChannelStore-test.ts
  test/test-utils/test-utils.ts
  test/test-utils/video.ts
Labels: T-Defect

#8614 Fix copy on video room creation button
  src/components/views/context_menus/SpaceContextMenu.tsx
Labels: T-Defect

#8615 Fix Netlify builds
  .github/workflows/netlify.yaml
Labels: T-Task

#8617 Use a default for `ignoreHover` when not supplied
  src/components/views/elements/TooltipTarget.tsx
Labels: T-Task

#8619 Fix 'continue' button not working after accepting identity server terms of service
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
Labels: T-Defect

#8618 Convert `setupNotificationListener` to an unbound function
  src/components/views/rooms/EventTile.tsx
Labels: T-Task

#8623 Tweak ReactionsRow to make saner use of its RoomContext
  src/components/views/messages/ReactionsRow.tsx
Labels: T-Task

#6442 Go to space landing page when clicking on a selected space
  src/components/views/spaces/SpaceTreeLevel.tsx
  test/components/views/spaces/SpaceTreeLevel-test.tsx
Labels: T-Enhancement

#8625 Add missing return values in Read Receipt animation code
  src/components/views/rooms/ReadReceiptMarker.tsx
Labels: T-Defect

#8627 Fix click behavior of notification badges on spaces
  src/components/views/spaces/SpaceTreeLevel.tsx
Labels: T-Defect

#8628 Add logs to try debug issue with thread view
  src/components/structures/ThreadView.tsx
  src/components/structures/TimelinePanel.tsx
Labels: T-Task

#8586 Add basic performance testing via Cypress
  .github/workflows/element-build-and-test.yaml
  .github/workflows/end-to-end-tests.yaml
  .gitignore
  cypress/global.d.ts
  cypress/integration/1-register/register.spec.ts
  cypress/integration/2-login/login.spec.ts
  cypress/integration/4-create-room/create-room.spec.ts
  cypress/plugins/index.ts
  cypress/plugins/performance.ts
  cypress/plugins/synapsedocker/index.ts
  cypress/support/bot.ts
  cypress/support/client.ts
  cypress/support/index.ts
  cypress/support/login.ts
  cypress/support/performance.ts
  cypress/support/synapse.ts
  src/performance/index.ts
Labels: T-Task

#8610 Add visual tests using Percy in Cypress
  .github/workflows/element-build-and-test.yaml
  .percy.yml
  README.md
  cypress/integration/1-register/register.spec.ts
  cypress/integration/2-login/login.spec.ts
  cypress/support/index.ts
  cypress/tsconfig.json
  docs/cypress.md
  package.json
  yarn.lock
Labels: T-Task

#8622 Sonarcloud check out upstream develop not fork develop
  .github/workflows/sonarqube.yml
Labels: T-Task

#8631 Adjust EditMessageComposer style declarations
  res/css/views/rooms/_EditMessageComposer.scss
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#8635 Revert "Sonarcloud check out upstream develop not fork develop"
  .github/workflows/sonarqube.yml
Labels: T-Task

#8642 If pasting a url atop another url, don't wrap one in the other
  src/components/views/rooms/BasicMessageComposer.tsx
Labels: T-Task

#8641 Hide image banner on stickers, they have a tooltip already
  res/css/views/messages/_MImageReplyBody.scss
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MImageReplyBody.tsx
  src/components/views/messages/MStickerBody.tsx
Labels: T-Defect
