Repository matrix-org/matrix-react-sdk, pull requests merged in 2022-12, with the labels that each got.

#9665 Fix flaky unit test: add alpha as second sorting condition for device list
  src/components/views/settings/devices/FilteredDeviceList.tsx
Labels: T-Task

#9642 Add more debugging for why audio ring/ringback might not be playing
  src/LegacyCallHandler.tsx
  src/settings/Settings.tsx
  test/LegacyCallHandler-test.ts
Labels: T-Task

#9655 test bulk unverified sessions toast behaviour
  test/DeviceListener-test.ts
Labels: T-Task

#9681 Fix power selector being wrongly disabled for admins themselves
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  test/components/views/settings/tabs/room/RolesRoomSettingsTab-test.tsx
Labels: T-Defect

#9664 bugfix: fix an issue where the Notifier would incorrectly fire for non-timeline events
  src/Notifier.ts
  test/Notifier-test.ts
Labels: T-Defect

#9692 Fix call splitbrains when switching between rooms
  src/models/Call.ts
  test/models/Call-test.ts
  test/test-utils/test-utils.ts
Labels: X-Release-Blocker, T-Defect, backport staging

#9644 Bump matrix-wysiwyg version to 0.8.0
  package.json
  yarn.lock
Labels: T-Task

#9672 Remove prop-types
  package.json
  src/components/views/context_menus/LegacyCallContextMenu.tsx
  src/components/views/settings/BridgeTile.tsx
Labels: T-Task

#9703 Update copy of 'Change layout' button to match Element Call
  src/components/views/rooms/RoomHeader.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#9704 Improve the visual balance of bubble layout
  res/css/views/rooms/_EventBubbleTile.pcss
  res/css/views/rooms/_EventTile.pcss
Labels: T-Enhancement

#9686 Do not resume voice broadcasts on seek
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.ts
Labels: T-Task

#9649 Update cypress.yaml GHA to not refer to workflow name.
  .github/workflows/cypress.yaml
Labels: T-Task

#9663 Improve MImageBody error handling
  src/components/views/messages/MImageBody.tsx
Labels: T-Task

#9707 Fix replies to emotes not showing as inline
  res/css/views/rooms/_ReplyTile.pcss
  src/components/views/rooms/ReplyTile.tsx
Labels: X-Release-Blocker, T-Defect

#9706 Snooze the bulk unverified sessions reminder on dismiss
  src/DeviceListener.ts
  src/toasts/BulkUnverifiedSessionsToast.ts
  src/utils/device/snoozeBulkUnverifiedDeviceReminder.ts
  test/DeviceListener-test.ts
  test/utils/device/snoozeBulkUnverifiedDeviceReminder-test.ts
Labels: T-Enhancement

#9662 Further password reset flow enhancements
  res/css/views/auth/_AuthBody.pcss
  res/css/views/dialogs/_VerifyEMailDialog.pcss
  src/Modal.tsx
  src/PasswordReset.ts
  src/components/structures/auth/ForgotPassword.tsx
  src/components/structures/auth/forgot-password/CheckEmail.tsx
  src/components/structures/auth/forgot-password/EnterEmail.tsx
  src/components/structures/auth/forgot-password/VerifyEmailModal.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/auth/ForgotPassword-test.tsx
Labels: T-Enhancement, X-Needs-Percy

#9709 Voice broadcast indicator in room list
  res/css/_components.pcss
  res/css/voice-broadcast/atoms/_VoiceBroadcastRoomSubtitle.pcss
  src/components/views/rooms/RoomTile.tsx
  src/voice-broadcast/components/atoms/VoiceBroadcastRoomSubtitle.tsx
  src/voice-broadcast/hooks/useHasRoomLiveVoiceBroadcast.ts
  src/voice-broadcast/index.ts
  test/components/views/rooms/RoomList-test.tsx
  test/components/views/rooms/RoomTile-test.tsx
  test/components/views/rooms/__snapshots__/RoomTile-test.tsx.snap
  test/test-utils/console.ts
Labels: T-Task

#9705 Add setting to hide bold notifications
  src/components/views/rooms/NotificationBadge/StatelessNotificationBadge.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/notifications/ListNotificationState.ts
  src/stores/notifications/NotificationState.ts
  src/stores/notifications/RoomNotificationState.ts
  src/stores/notifications/SpaceNotificationState.ts
  src/stores/notifications/StaticNotificationState.ts
  test/components/views/rooms/NotificationBadge/NotificationBadge-test.tsx
  test/components/views/spaces/QuickThemeSwitcher-test.tsx
  test/stores/TypingStore-test.ts
  test/utils/MultiInviter-test.ts
Labels: T-Enhancement

#9671 Move @types deps into devDeps
  package.json
Labels: T-Task

#9716 Remove unused Dockerfile
  scripts/ci/Dockerfile
Labels: T-Task

#9713 Tweak voice broadcast chunk decoding
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.ts
Labels: T-Task

#9715 Change formatting buttons behavior
  res/css/views/rooms/wysiwyg_composer/components/_FormattingButtons.pcss
  src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
  test/components/views/rooms/wysiwyg_composer/components/FormattingButtons-test.tsx
Labels: T-Defect

#9725 Stop Cypress running in parallel to avoid failures with non-matching environments
  .github/workflows/cypress.yaml
Labels: T-Task

#9596 add-privileged-users-in-room
  res/css/_components.pcss
  res/css/structures/_AutocompleteInput.pcss
  res/img/element-icons/roomlist/search.svg
  src/components/structures/AutocompleteInput.tsx
  src/components/views/elements/PowerSelector.tsx
  src/components/views/settings/AddPrivilegedUsers.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/AutocompleteInput-test.tsx
  test/components/views/settings/AddPrivilegedUsers-test.tsx
Labels: Z-Community-PR, T-Enhancement

#9726 Add voice broadcast device selection tooltip
  src/voice-broadcast/components/atoms/VoiceBroadcastHeader.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip.tsx
  test/voice-broadcast/components/atoms/__snapshots__/VoiceBroadcastHeader-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPlaybackBody-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPreRecordingPip-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastRecordingBody-test.tsx.snap
Labels: T-Task

#9626 Overlay virtual room call events into main timeline
  src/VoipUserMapper.ts
  src/components/structures/LegacyCallEventGrouper.ts
  src/components/structures/RoomView.tsx
  src/components/structures/TimelinePanel.tsx
  test/components/structures/RoomView-test.tsx
  test/components/structures/TimelinePanel-test.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
Labels: T-Enhancement

#9717 Device manage - handle sessions that don't support encryption
  cypress/e2e/settings/device-management.spec.ts
  src/components/views/settings/devices/DeviceSecurityCard.tsx
  src/components/views/settings/devices/DeviceSecurityLearnMore.tsx
  src/components/views/settings/devices/DeviceVerificationStatusCard.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/SecurityRecommendations.tsx
  src/components/views/settings/devices/filter.ts
  src/components/views/settings/devices/types.ts
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Defect

#9727 Add emoji handling for plain text mode
  src/components/views/rooms/wysiwyg_composer/components/Editor.tsx
  src/components/views/rooms/wysiwyg_composer/components/PlainTextComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useComposerFunctions.ts
  src/components/views/rooms/wysiwyg_composer/hooks/usePlainTextListeners.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useSelection.ts
  test/components/views/rooms/wysiwyg_composer/SendWysiwygComposer-test.tsx
Labels: T-Enhancement

#9720 Add inline code to rich text editor
  res/css/views/rooms/wysiwyg_composer/components/_FormattingButtons.pcss
  res/img/element-icons/room/composer/inline_code.svg
  src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/wysiwyg_composer/components/FormattingButtons-test.tsx
Labels: T-Enhancement

#9721 Simplify checks for cross-signing setup
  src/components/structures/MatrixChat.tsx
Labels: T-Task

#9731 Update eslint-plugin-matrix-org to 0.8.0
  .eslintrc.js
  package.json
  yarn.lock
Labels: T-Task

#9732 Use icon component instead of mask-image for formatting buttons
  res/css/views/rooms/wysiwyg_composer/components/_FormattingButtons.pcss
  res/img/element-icons/room/composer/bold.svg
  res/img/element-icons/room/composer/inline_code.svg
  res/img/element-icons/room/composer/italic.svg
  res/img/element-icons/room/composer/strikethrough.svg
  res/img/element-icons/room/composer/underline.svg
  src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
Labels: T-Task

#9741 Fix Prettier errors that slipped past CI
  src/utils/EventUtils.ts
  src/voice-broadcast/utils/shouldDisplayAsVoiceBroadcastStoppedText.ts
  src/voice-broadcast/utils/textForVoiceBroadcastStoppedEvent.tsx
  test/voice-broadcast/utils/textForVoiceBroadcastStoppedEvent-test.tsx
Labels: T-Task

#9742 Don't double-add events to threads in tests
  test/test-utils/threads.ts
Labels: T-Task

#9743 Remove async call to get virtual room from room load
  src/components/structures/RoomView.tsx
  src/components/structures/TimelinePanel.tsx
Labels: X-Release-Blocker, T-Defect

#9722 Link voice broadcast avatar and room name to room
  src/voice-broadcast/components/atoms/VoiceBroadcastHeader.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastPreRecordingPip.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody-test.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastPreRecordingPip-test.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip-test.tsx
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPlaybackBody-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPreRecordingPip-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastRecordingPip-test.tsx.snap
Labels: T-Task

#9746 Fix issue where thread panel did not update correctly
  src/components/structures/ThreadPanel.tsx
Labels: X-Release-Blocker, T-Defect

#9736 🧵 Enable threads by default
  cypress/e2e/polls/polls.spec.ts
  cypress/e2e/threads/threads.spec.ts
  res/css/views/messages/_MessageActionBar.pcss
  res/img/betas/threads.png
  src/MatrixClientPeg.ts
  src/components/structures/MessagePanel.tsx
  src/components/structures/RoomSearchView.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/SearchResultTile.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/components/views/rooms/wysiwyg_composer/utils/message.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/TypingStore.ts
  src/stores/right-panel/RightPanelStore.ts
  src/stores/widgets/StopGapWidgetDriver.ts
  src/utils/Reply.ts
  src/utils/exportUtils/HtmlExport.tsx
  test/components/structures/TimelinePanel-test.tsx
  test/components/views/messages/MessageActionBar-test.tsx
  test/components/views/right_panel/RoomHeaderButtons-test.tsx
  test/components/views/rooms/EventTile-test.tsx
  test/components/views/rooms/SearchResultTile-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/LabsUserSettingsTab-test.tsx.snap
  test/stores/TypingStore-test.ts
  test/utils/export-test.tsx
Labels: X-Release-Blocker, T-Enhancement

#9749 Use new thread labs feature name
  src/Unread.ts
Labels: T-Task, backport staging

#9734 Device manager - use deleteAccountData to prune device manager client information events
  src/utils/device/clientInformation.ts
  test/DeviceListener-test.ts
Labels: T-Enhancement

#9751 Honor font settings in Element Call
  src/models/Call.ts
  test/models/Call-test.ts
Labels: T-Enhancement

#9744 Prevent to start two broadcasts at the same time
  src/voice-broadcast/components/molecules/VoiceBroadcastPreRecordingPip.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastPreRecordingPip-test.tsx
Labels: T-Defect

#9758 `settings.md`: Fix formatting in an example
  docs/settings.md
Labels: T-Task

#9752 Regression test: switch between dm rooms without loader
  cypress/e2e/room/room.spec.ts
Labels: T-Task

#9755 Implement small broadcast PiP
  res/css/voice-broadcast/atoms/_LiveBadge.pcss
  res/css/voice-broadcast/atoms/_VoiceBroadcastControl.pcss
  res/css/voice-broadcast/atoms/_VoiceBroadcastHeader.pcss
  res/css/voice-broadcast/molecules/_VoiceBroadcastBody.pcss
  src/components/views/voip/PipView.tsx
  src/i18n/strings/en_EN.json
  src/voice-broadcast/components/atoms/VoiceBroadcastHeader.tsx
  src/voice-broadcast/components/atoms/VoiceBroadcastPlaybackControl.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastSmallPlaybackBody.tsx
  src/voice-broadcast/index.ts
  test/components/views/voip/PipView-test.tsx
  test/voice-broadcast/components/atoms/VoiceBroadcastPlaybackControl-test.tsx
  test/voice-broadcast/components/atoms/__snapshots__/VoiceBroadcastHeader-test.tsx.snap
  test/voice-broadcast/components/atoms/__snapshots__/VoiceBroadcastPlaybackControl-test.tsx.snap
  test/voice-broadcast/components/molecules/VoiceBroadcastSmallPlaybackBody-test.tsx
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPlaybackBody-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPreRecordingPip-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastRecordingBody-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastRecordingPip-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastSmallPlaybackBody-test.tsx.snap
Labels: T-Task

#9685 Report cypress test results into testrail.
  .github/workflows/cypress.yaml
  cypress-ci-reporter-config.json
  package.json
  yarn.lock
Labels: T-Task

#9544 Improve decryption error UI by consolidating error messages and providing instructions when possible
  cypress/e2e/crypto/decryption-failure.spec.ts
  cypress/support/bot.ts
  cypress/support/synapse.ts
  res/css/_components.pcss
  res/css/views/messages/_DecryptionFailureBody.pcss
  res/css/views/rooms/_DecryptionFailureBar.pcss
  res/css/views/rooms/_EventBubbleTile.pcss
  res/css/views/rooms/_EventTile.pcss
  res/img/e2e/decryption-failure.svg
  src/components/structures/RoomView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/messages/DecryptionFailureBody.tsx
  src/components/views/messages/MessageEvent.tsx
  src/components/views/rooms/DecryptionFailureBar.tsx
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/DecryptionFailureBar-test.tsx
  test/components/views/rooms/__snapshots__/DecryptionFailureBar-test.tsx.snap
Labels: T-Enhancement, X-Needs-Percy

#9777 Use full suite title when cypress tests contain nested describe()s.
  cypress-ci-reporter-config.json
Labels: T-Task

#9774 Display broadcast live state only depending on the recording
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  src/voice-broadcast/utils/determineVoiceBroadcastLiveness.ts
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.ts
  test/voice-broadcast/utils/determineVoiceBroadcastLiveness-test.ts
Labels: T-Task

#9762 Implement broadcast message preview
  src/TextForEvent.tsx
  src/i18n/strings/en_EN.json
  src/stores/room-list/MessagePreviewStore.ts
  src/stores/room-list/previews/MessageEventPreview.ts
  src/stores/room-list/previews/VoiceBroadcastPreview.ts
  src/utils/event/getSenderName.ts
  src/voice-broadcast/index.ts
  src/voice-broadcast/types.ts
  src/voice-broadcast/utils/textForVoiceBroadcastStoppedEvent.tsx
  src/voice-broadcast/utils/textForVoiceBroadcastStoppedEventWithoutLink.ts
  test/TextForEvent-test.ts
  test/stores/room-list/previews/MessageEventPreview-test.ts
  test/stores/room-list/previews/VoiceBroadcastPreview-test.ts
  test/test-utils/test-utils.ts
  test/voice-broadcast/utils/textForVoiceBroadcastStoppedEventWithoutLink-test.ts
Labels: T-Task

#9759 Add a config flag to enable the rust crypto-sdk
  src/IConfigOptions.ts
  src/MatrixClientPeg.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/controllers/RustCryptoSdkController.ts
  test/MatrixClientPeg-test.ts
Labels: T-Enhancement

#9786 Improve some voice broadcast tests
  test/events/RelationsHelper-test.ts
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.ts
  test/voice-broadcast/utils/VoiceBroadcastChunkEvents-test.ts
  test/voice-broadcast/utils/test-utils.ts
Labels: T-Task

#9764 Handle starting a call while listen to a broadcast
  src/LegacyCallHandler.tsx
  src/i18n/strings/en_EN.json
  src/stores/RoomViewStore.tsx
  src/voice-broadcast/utils/showCantStartACallDialog.tsx
  test/LegacyCallHandler-test.ts
  test/__snapshots__/LegacyCallHandler-test.ts.snap
  test/stores/RoomViewStore-test.ts
  test/stores/__snapshots__/RoomViewStore-test.ts.snap
Labels: T-Task

#9773 Change room list sorting to activity and unread first by default
  src/stores/room-list/RoomListStore.ts
  test/stores/room-list/RoomListStore-test.ts
Labels: T-Enhancement

#9781 Remove RoomList sorting settings
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/room-list/RoomListStore.ts
Labels: T-Task

#9787 Cypress: add a way to specify the prefix for userIDs
  cypress/e2e/crypto/crypto.spec.ts
  cypress/support/bot.ts
  cypress/support/login.ts
Labels: T-Task

#9792 Remove unused property from `IConfigOptions`
  src/IConfigOptions.ts
Labels: T-Task

#9795 When stopping a broadcast also stop the playback
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.ts
Labels: T-Defect

#9768 Device manager - design tweaks
  cypress/e2e/settings/device-management.spec.ts
  res/css/components/views/elements/_FilterDropdown.pcss
  res/css/components/views/settings/devices/_DeviceDetails.pcss
  res/css/components/views/settings/devices/_DeviceExpandDetailsButton.pcss
  res/css/components/views/settings/devices/_DeviceTypeIcon.pcss
  res/css/components/views/settings/shared/_SettingsSubsection.pcss
  src/components/views/settings/devices/CurrentDeviceSection.tsx
  src/components/views/settings/devices/DeviceDetailHeading.tsx
  src/components/views/settings/devices/FilteredDeviceListHeader.tsx
  src/components/views/settings/devices/SecurityRecommendations.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceDetailHeading-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceDetails-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/SecurityRecommendations-test.tsx.snap
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Enhancement

#9794 Use compound colours for verification badges
  res/css/structures/_ToastContainer.pcss
  res/css/views/messages/_common_CryptoEvent.pcss
  res/css/views/right_panel/_RoomSummaryCard.pcss
  res/css/views/rooms/_DecryptionFailureBar.pcss
  res/css/views/rooms/_E2EIcon.pcss
  res/css/views/rooms/_EventTile.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light/css/_light.pcss
Labels: T-Task

#9789 Ensure that events are correctly updated when they are edited.
  cypress/e2e/crypto/crypto.spec.ts
  cypress/support/bot.ts
  src/components/views/rooms/EventTile.tsx
  test/components/views/rooms/EventTile-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Defect

#9804 Load RTE component only when needed
  src/components/views/rooms/wysiwyg_composer/DynamicImportWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/EditWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/SendWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/index.ts
  test/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/SendWysiwygComposer-test.tsx
Labels: T-Defect, backport staging

#9754 Unify notifications panel event design
  res/css/_components.pcss
  res/css/structures/_NotificationPanel.pcss
  res/css/views/right_panel/_BaseCard.pcss
  res/css/views/rooms/_EventTile.pcss
  src/components/structures/NotificationPanel.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/EventTile/EventTileThreadToolbar.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/EventTile-test.tsx
Labels: T-Enhancement

#9811 Fix rte flaky test
  test/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx
Labels: T-Task

#9797 Snap in PiP widget when content changed
  src/components/views/voip/PictureInPictureDragger.tsx
  test/components/views/voip/PictureInPictureDragger-test.tsx
  test/components/views/voip/__snapshots__/PictureInPictureDragger-test.tsx.snap
Labels: T-Defect

#9810 Make threads disabled by default
  cypress/e2e/polls/polls.spec.ts
  cypress/e2e/threads/threads.spec.ts
  src/settings/Settings.tsx
Labels: T-Task, backport staging

#9803 Fix checkForPreJoinUISI for thread roots
  src/components/structures/TimelinePanel.tsx
  test/components/structures/TimelinePanel-test.tsx
Labels: T-Defect, backport staging

#9808 Make call tiles look less broken in the right panel
  res/css/views/elements/_FacePile.pcss
  res/css/views/messages/_CallEvent.pcss
  res/css/views/voip/_CallView.pcss
  res/img/element-icons/call/video-call.svg
  src/components/views/messages/CallEvent.tsx
Labels: T-Defect

#9809 Fix: Editing a poll will silently change it to a closed poll
  src/components/views/elements/PollCreateDialog.tsx
  test/components/views/elements/PollCreateDialog-test.tsx
Labels: T-Defect

#9801 Device manager - current device design and copy tweaks
  res/css/_components.pcss
  res/css/components/views/settings/devices/_CurrentDeviceSection.pcss
  res/css/components/views/settings/devices/_DeviceDetails.pcss
  res/css/components/views/settings/devices/_FilteredDeviceList.pcss
  src/components/views/settings/devices/CurrentDeviceSection.tsx
  src/components/views/settings/devices/DeviceDetails.tsx
  src/components/views/settings/devices/DeviceVerificationStatusCard.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/DeviceVerificationStatusCard-test.tsx
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceDetails-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceVerificationStatusCard-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Enhancement

#9637 Pass analyticsID to the elementCall iFrame
  src/PosthogAnalytics.ts
  src/models/Call.ts
  test/models/Call-test.ts
  test/test-utils/test-utils.ts
Labels: T-Task

#9798 Add mark as read option in room setting
  res/css/views/context_menus/_RoomGeneralContextMenu.pcss
  res/img/element-icons/roomlist/mark-as-read.svg
  src/components/views/context_menus/RoomGeneralContextMenu.tsx
  src/i18n/strings/en_EN.json
  src/utils/notifications.ts
  test/components/views/context_menus/RoomGeneralContextMenu-test.tsx
  test/components/views/context_menus/__snapshots__/RoomGeneralContextMenu-test.tsx.snap
  test/components/views/settings/Notifications-test.tsx
  test/utils/notifications-test.ts
Labels: T-Enhancement

#9796 Show initial broadcast position in seekbar
  src/components/views/audio_messages/SeekBar.tsx
  test/components/views/audio_messages/SeekBar-test.tsx
  test/components/views/audio_messages/__snapshots__/SeekBar-test.tsx.snap
Labels: T-Defect

#9784 sliding sync: Add test to verify we send `unsubscribe_rooms` for every room switch
  cypress/e2e/sliding-sync/sliding-sync.ts
Labels: T-Task

#9823 unit test ToastStore
  test/stores/ToastStore-test.ts
Labels: T-Task

#9822 Replace some enzyme tests by @testing-library/react
  test/HtmlUtils-test.tsx
  test/components/views/rooms/MessageComposerButtons-test.tsx
Labels: T-Task

#9820 Fix sign-in instead link on password reset page
  src/components/structures/auth/forgot-password/EnterEmail.tsx
Labels: T-Defect

#9806 Add labs setting to force small broadcast chunks
  src/components/views/dialogs/DevtoolsDialog.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/voice-broadcast/utils/getChunkLength.ts
  test/voice-broadcast/audio/VoiceBroadcastRecorder-test.ts
  test/voice-broadcast/utils/getChunkLength-test.ts
Labels: T-Task

#9737 When deleting a voice broadcast, also delete related events
  src/components/views/dialogs/ConfirmRedactDialog.tsx
  src/voice-broadcast/index.ts
  src/voice-broadcast/utils/isVoiceBroadcastStartedEvent.ts
  test/components/views/dialogs/ConfirmRedactDialog-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Task

#9821 Consider own broadcasts from other device as a playback
  src/voice-broadcast/utils/shouldDisplayAsVoiceBroadcastRecordingTile.ts
  test/voice-broadcast/utils/shouldDisplayAsVoiceBroadcastRecordingTile-test.ts
  test/voice-broadcast/utils/test-utils.ts
Labels: T-Enhancement

#9824 Replace broadcast instance with SDKContext
  src/components/structures/UserMenu.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/contexts/SDKContext.ts
  src/stores/widgets/StopGapWidget.ts
  src/voice-broadcast/components/VoiceBroadcastBody.tsx
  src/voice-broadcast/stores/VoiceBroadcastPlaybacksStore.ts
  src/voice-broadcast/stores/VoiceBroadcastRecordingsStore.ts
  test/components/structures/UserMenu-test.tsx
  test/components/views/spaces/SpacePanel-test.tsx
  test/stores/widgets/StopGapWidget-test.ts
  test/voice-broadcast/components/VoiceBroadcastBody-test.tsx
Labels: T-Task

#9825 Pause non-live broadcast from other room
  src/stores/RoomViewStore.tsx
  src/voice-broadcast/stores/VoiceBroadcastPlaybacksStore.ts
  src/voice-broadcast/utils/pauseNonLiveBroadcastFromOtherRoom.ts
  test/voice-broadcast/utils/pauseNonLiveBroadcastFromOtherRoom-test.ts
Labels: T-Enhancement

#9812 Handle voice broadcast last_chunk_sequence
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  src/voice-broadcast/utils/VoiceBroadcastChunkEvents.ts
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.ts
  test/voice-broadcast/utils/VoiceBroadcastChunkEvents-test.ts
  test/voice-broadcast/utils/test-utils.ts
Labels: T-Task

#9833 Migrate AccessibleButton-test to RTL
  test/components/views/elements/AccessibleButton-test.tsx
  test/components/views/elements/__snapshots__/AccessibleButton-test.tsx.snap
Labels: T-Task

#9829 Allow call and broadcast PiP at the same time
  res/css/views/voip/_LegacyCallPreview.pcss
  src/components/views/voip/PictureInPictureDragger.tsx
  src/components/views/voip/PipView.tsx
  test/components/views/voip/PictureInPictureDragger-test.tsx
  test/components/views/voip/PipView-test.tsx
  test/components/views/voip/__snapshots__/PictureInPictureDragger-test.tsx.snap
Labels: T-Task

#9834 Fix broadcast pre-recording check
  src/voice-broadcast/utils/setUpVoiceBroadcastPreRecording.ts
  test/voice-broadcast/utils/setUpVoiceBroadcastPreRecording-test.ts
Labels: T-Task

#9836 Convert enzyme to rtl: BeaconStatus
  test/components/views/beacon/BeaconStatus-test.tsx
  test/components/views/beacon/__snapshots__/BeaconStatus-test.tsx.snap
Labels: T-Task

#9832 Device manager - contextual menus
  src/components/views/settings/devices/CurrentDeviceSection.tsx
  src/components/views/settings/devices/OtherSessionsSectionHeading.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/CurrentDeviceSection-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Enhancement

#9837 Convert enzyme to rtl: RightPanel
  test/components/structures/RightPanel-test.tsx
Labels: T-Task

#9835 Show regular avatar for broadcasts
  src/utils/EventRenderingUtils.ts
  test/utils/EventRenderingUtils-test.ts
Labels: T-Task

#9843 Enzyme to rtl: QuickThemeSwitcher
  test/components/views/spaces/QuickThemeSwitcher-test.tsx
Labels: T-Task

#9842 Migrate Enzyme to RTL
  src/components/views/beacon/RoomLiveShareWarning.tsx
  test/components/views/beacon/RoomLiveShareWarning-test.tsx
  test/components/views/beacon/__snapshots__/RoomLiveShareWarning-test.tsx.snap
  test/components/views/location/Map-test.tsx
  test/components/views/location/Marker-test.tsx
  test/components/views/location/__snapshots__/Marker-test.tsx.snap
Labels: T-Task

#9845 Migrate TextualBody to RTL
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
Labels: T-Task

#9839 Convert enzyme to rtl: BasicMessageComposer
  test/components/views/rooms/BasicMessageComposer-test.tsx
  test/editor/mock.ts
  test/editor/model-test.ts
  test/editor/operations-test.ts
Labels: T-Task

#9848 Fixes empty content type during upload
  src/ContentMessages.ts
  test/ContentMessages-test.ts
Labels: Z-Community-PR, T-Defect

#9838 Migrate AppTile-Test to RTL
  test/components/views/elements/AppTile-test.tsx
Labels: T-Task
