Repository matrix-org/matrix-react-sdk, pull requests merged in 2022-01, with the labels that each got.

#7430 Associate room alias warning with public option in settings
  src/components/views/elements/StyledRadioGroup.tsx
  src/components/views/settings/JoinRuleSettings.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  test/components/views/elements/StyledRadioGroup-test.tsx
  test/components/views/elements/__snapshots__/StyledRadioGroup-test.tsx.snap
  test/components/views/settings/__snapshots__/ThemeChoicePanel-test.tsx.snap
Labels: T-Enhancement

#7434 Add jsx-a11y eslint plugin
  .eslintrc.js
  package.json
  src/components/structures/ScrollPanel.tsx
  src/components/views/context_menus/TagTileContextMenu.js
  src/components/views/messages/MFileBody.tsx
  src/components/views/messages/ViewSourceEvent.tsx
  src/i18n/strings/en_EN.json
  yarn.lock
Labels: T-Task

#7455 A11y fix role-has-required-aria-props
  .eslintrc.js
  src/autocomplete/Components.tsx
  src/components/views/elements/Dropdown.tsx
Labels: T-Task

#7447 Removed red shield in forwarding preview.
  res/css/views/dialogs/_ForwardDialog.scss
Labels: T-Defect

#7440 Fix offscreen canvas breaking with split-brained firefox support
  src/ContentMessages.tsx
Labels: T-Defect

#7439 Call view accessibility fixes
  res/css/views/voip/CallView/_CallViewButtons.scss
  res/css/views/voip/_CallView.scss
  src/components/views/elements/DialPadBackspaceButton.tsx
  src/components/views/voip/CallView.tsx
  src/components/views/voip/DialPad.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7107 Fix room alias address isn't checked for validity before being shown as added
  src/components/views/elements/RoomAliasField.tsx
  src/components/views/room_settings/AliasSettings.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7443 Fix handling incoming redactions in EventIndex
  src/indexing/EventIndex.ts
Labels: T-Defect

#7451 Add new line in settings label
  res/css/views/elements/_SettingsFlag.scss
  src/components/views/elements/SettingsFlag.tsx
Labels: T-Defect

#7456 add spacing variables
  res/css/_components.scss
  res/css/_spacing.scss
Labels: T-Task

#7448 Fix room_id check when adding user widgets
  src/ScalarMessaging.ts
Labels: T-Defect

#7463 Fix spotlight cmd-k wrongly expanding left panel
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomSearch.tsx
  src/components/structures/SearchBox.tsx
Labels: T-Defect

#7323 Attribute fallback i18n strings with lang attribute
  __mocks__/browser-request.js
  src/components/structures/HomePage.tsx
  src/components/views/elements/MiniAvatarUploader.tsx
  src/i18n/strings/en_EN.json
  src/languageHandler.tsx
  test/i18n-test/languageHandler-test.js
  test/i18n-test/languageHandler-test.tsx
Labels: T-Defect

#7313 Right panel store refactor
  src/@types/global.d.ts
  src/TextForEvent.tsx
  src/components/structures/FilePanel.tsx
  src/components/structures/GroupView.js
  src/components/structures/LoggedInView.tsx
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomStatusBar.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/structures/ThreadView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/structures/UserView.tsx
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/elements/MemberEventListSummary.tsx
  src/components/views/groups/GroupMemberList.js
  src/components/views/messages/MKeyVerificationRequest.tsx
  src/components/views/right_panel/BaseCard.tsx
  src/components/views/right_panel/EncryptionPanel.tsx
  src/components/views/right_panel/GroupHeaderButtons.tsx
  src/components/views/right_panel/HeaderButtons.tsx
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/right_panel/TimelineCard.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/right_panel/WidgetCard.tsx
  src/components/views/rooms/AppsDrawer.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomListHeader.tsx
  src/components/views/toasts/VerificationRequestToast.tsx
  src/dispatcher/actions.ts
  src/dispatcher/dispatch-actions/threads.ts
  src/dispatcher/payloads/AfterRightPanelPhaseChangePayload.ts
  src/dispatcher/payloads/SetRightPanelPhasePayload.ts
  src/dispatcher/payloads/ToggleRightPanelPayload.ts
  src/settings/Settings.tsx
  src/settings/handlers/DeviceSettingsHandler.ts
  src/stores/RightPanelStore.ts
  src/stores/right-panel/RightPanelStore.ts
  src/stores/right-panel/RightPanelStoreIPanelState.ts
  src/stores/right-panel/RightPanelStorePhases.ts
  src/verification.ts
Labels: T-Task

#7466 Fix quoting messages from the search view
  src/components/structures/RoomView.tsx
Labels: T-Defect

#7398 History based navigation with new right panel store
  src/components/structures/FilePanel.tsx
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadView.tsx
  src/components/views/avatars/MemberAvatar.tsx
  src/components/views/messages/MKeyVerificationRequest.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/right_panel/BaseCard.tsx
  src/components/views/right_panel/EncryptionPanel.tsx
  src/components/views/right_panel/GroupHeaderButtons.tsx
  src/components/views/right_panel/HeaderButtons.tsx
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/right_panel/WidgetCard.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/rooms/MemberTile.tsx
  src/components/views/toasts/VerificationRequestToast.tsx
  src/dispatcher/dispatch-actions/threads.ts
  src/i18n/strings/en_EN.json
  src/stores/right-panel/RightPanelStore.ts
  src/stores/right-panel/RightPanelStoreIPanelState.ts
  src/stores/right-panel/RightPanelStorePhases.ts
  src/verification.ts
Labels: T-Enhancement

#7468 unit test Notifications.tsx
  src/components/views/settings/Notifications.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/Notifications-test.tsx
  test/components/views/settings/__snapshots__/Notifications-test.tsx.snap
  test/test-utils.js
Labels: T-Task

#7350 Wrap inputs in fieldsets in Space visibility settings
  res/css/views/dialogs/_SpaceSettingsDialog.scss
  res/css/views/settings/_JoinRuleSettings.scss
  res/css/views/settings/_ProfileSettings.scss
  res/css/views/settings/tabs/_SettingsTab.scss
  src/components/views/room_settings/AliasSettings.tsx
  src/components/views/spaces/SpaceSettingsVisibilityTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/spaces/SpaceSettingsVisibilityTab-test.tsx
  test/components/views/spaces/__snapshots__/SpaceSettingsVisibilityTab-test.tsx.snap
  test/test-utils.js
Labels: T-Enhancement

#7471 a11y - wrap notification level radios in fieldsets
  res/css/views/settings/_Notifications.scss
  src/components/views/settings/Notifications.tsx
  test/components/views/settings/Notifications-test.tsx
Labels: T-Enhancement

#7476 update yarn.lock and i18n
  src/i18n/strings/en_EN.json
  yarn.lock
Labels: T-Defect

#7444 A11y - fix anchors-as-buttons
  .eslintrc.js
  res/css/_common.scss
  res/css/structures/auth/_SetupEncryptionBody.scss
  res/css/views/dialogs/_DevtoolsDialog.scss
  res/css/views/elements/_AccessibleButton.scss
  res/css/views/elements/_ReplyChain.scss
  res/css/views/messages/_ReactionsRow.scss
  res/css/views/messages/_ViewSourceEvent.scss
  res/css/views/rooms/_EventTile.scss
  src/TextForEvent.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/auth/ForgotPassword.tsx
  src/components/structures/auth/Login.tsx
  src/components/structures/auth/Registration.tsx
  src/components/structures/auth/SetupEncryptionBody.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/dialogs/AddressPickerDialog.tsx
  src/components/views/dialogs/DevtoolsDialog.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/dialogs/RoomUpgradeWarningDialog.tsx
  src/components/views/dialogs/StorageEvictedDialog.tsx
  src/components/views/dialogs/security/AccessSecretStorageDialog.tsx
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/elements/DesktopBuildsNotice.tsx
  src/components/views/elements/MemberEventListSummary.tsx
  src/components/views/elements/ReplyChain.tsx
  src/components/views/messages/MFileBody.tsx
  src/components/views/messages/MjolnirBody.tsx
  src/components/views/messages/ReactionsRow.tsx
  src/components/views/messages/TextualBody.tsx
  src/components/views/messages/TileErrorBoundary.tsx
  src/components/views/messages/ViewSourceEvent.tsx
  src/components/views/room_settings/UrlPreviewSettings.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/NewRoomIntro.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/SettingsFieldset-test.tsx
  test/components/views/settings/__snapshots__/SettingsFieldset-test.tsx.snap
Labels: T-Task

#7477 Don't send typing notification when restoring composer draft
  src/components/views/rooms/BasicMessageComposer.tsx
Labels: T-Defect

#7465 Open map in a dialog when it is clicked
  res/css/_common.scss
  res/css/_components.scss
  res/css/views/dialogs/_LocationViewDialog.scss
  res/themes/dark/css/_dark.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light/css/_light.scss
  src/components/views/location/LocationViewDialog.tsx
  src/components/views/messages/MLocationBody.tsx
Labels: T-Enhancement

#7472 Display a tooltip when you hover over a location
  src/components/views/elements/Tooltip.tsx
  src/components/views/elements/TooltipTarget.tsx
  src/components/views/messages/MLocationBody.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7480 fix fallback for pluralized strings
  __mocks__/browser-request.js
  src/languageHandler.tsx
  test/i18n-test/languageHandler-test.tsx
Labels: T-Defect

#7479 Fix right panel soft crashes chat rooms
  src/stores/right-panel/RightPanelStore.ts
Labels: T-Defect

#7490 Fix typing notification colors
  res/css/views/rooms/_WhoIsTypingTile.scss
Labels: T-Defect

#7489 Give secret key field an `id`
  src/components/views/dialogs/security/AccessSecretStorageDialog.tsx
Labels: T-Enhancement

#7481 Fix space ordering to match newer spec
  src/stores/spaces/SpaceStore.ts
Labels: T-Defect

#7488 Hide maximise button in the sticker picker
  src/components/views/elements/AppTile.tsx
  src/components/views/rooms/Stickerpicker.tsx
Labels: T-Defect

#7486 Remove the location type dropdown from the location picker
  res/css/views/location/_LocationPicker.scss
  src/components/views/location/LocationButton.tsx
  src/components/views/location/LocationPicker.tsx
  src/components/views/location/LocationShareType.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7482 Add zoom buttons to the location view
  res/css/views/dialogs/_LocationViewDialog.scss
  res/img/element-icons/minus-button.svg
  res/img/element-icons/plus-button.svg
  src/components/views/location/LocationViewDialog.tsx
  src/components/views/messages/MLocationBody.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7485 Remove the Description from the location picker
  res/css/views/location/_LocationPicker.scss
  src/components/views/location/LocationButton.tsx
  src/components/views/location/LocationPicker.tsx
  src/components/views/location/LocationShareType.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7494 Fix jump to bottom button working when on a permalink
  src/components/structures/RoomView.tsx
Labels: T-Defect

#7491 Fix avatar container overlapping give feedback cta
  res/css/structures/_SpaceHierarchy.scss
  res/css/structures/_SpaceRoomView.scss
Labels: T-Defect

#7493 null-guard dataset mxTheme to prevent html exports from exploding
  src/utils/exportUtils/exportCSS.ts
Labels: X-Release-Blocker, T-Defect

#7492 Add permission dropdown for sending reactions
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7441 Disable "Publish this room" option in invite only rooms
  src/components/views/room_settings/RoomPublishSetting.tsx
  test/end-to-end-tests/src/usecases/room-settings.ts
Labels: T-Enhancement

#7459 Remove bubble from around location events
  res/css/views/rooms/_EventBubbleTile.scss
  src/components/views/rooms/EventTile.tsx
  src/utils/EventUtils.ts
Labels: T-Enhancement

#7461 Consider continuations when resolving whether a tile is last in section
  src/components/structures/MessagePanel.tsx
Labels: T-Defect

#7484 Fix spacing errors
  package.json
  src/CountlyAnalytics.ts
  src/Markdown.ts
  src/components/structures/EmbeddedPage.tsx
  src/components/structures/auth/Registration.tsx
  src/components/views/dialogs/ModalWidgetDialog.tsx
  src/components/views/elements/FacePile.tsx
  src/components/views/messages/MPollBody.tsx
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/settings/ThemeChoicePanel.tsx
  src/components/views/settings/account/EmailAddresses.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/utils/FormattingUtils.ts
  src/verification.ts
  test/PosthogAnalytics-test.ts
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/end-to-end-tests/has-custom-app.js
  test/end-to-end-tests/src/session.ts
  test/stores/WidgetLayoutStore-test.ts
  yarn.lock
Labels: T-Task

#7495 fallback properly with pluralized strings
  src/languageHandler.tsx
  test/i18n-test/languageHandler-test.tsx
Labels: T-Defect

#7503 Properly maintain aspect ratio of inline images
  res/css/views/rooms/_EventTile.scss
  src/HtmlUtils.tsx
  test/components/structures/GroupView-test.js
Labels: T-Enhancement

#7504 Prevent mutations of js-sdk owned objects as it breaks accountData
  src/Rooms.ts
  src/components/structures/MatrixChat.tsx
  src/stores/room-list/RoomListStore.ts
  src/utils/DMRoomMap.ts
Labels: T-Defect

#7505 Use `flex-end` rather than `end`
  res/css/views/dialogs/_UntrustedDeviceDialog.scss
Labels: T-Defect

#7497 Fix layout of message bubble preview in settings
  res/css/views/settings/_LayoutSwitcher.scss
Labels: T-Defect

#7435 Fix active Jitsi calls (and other active widgets) not being visible on screen, by showing them in PiP if they are not visible in any other container
  src/components/views/elements/PersistentApp.tsx
  src/components/views/rooms/Stickerpicker.tsx
  src/components/views/voip/CallPreview.tsx
  src/dispatcher/actions.ts
Labels: T-Defect

#7506 Set header buttons to no phase when right panel is closed
  src/components/views/right_panel/HeaderButtons.tsx
Labels: T-Defect

#7507 Fix wrongly wrapping code blocks, breaking line numbers
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#7509 Ship maximised widgets and remove feature flag
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Enhancement

#7483 Allow cancelling events whilst they are encrypting
  src/components/views/context_menus/MessageContextMenu.tsx
Labels: T-Enhancement

#7457 Make files & voice memos in bubble layout match colouring
  res/css/views/rooms/_EventBubbleTile.scss
Labels: T-Enhancement

#7514 Update default Jitsi URLs to meet.element.io
  src/SdkConfig.ts
  src/stores/widgets/StopGapWidget.ts
  src/widgets/Jitsi.ts
Labels: T-Task

#7515 Yarn upgrade
  yarn.lock
Labels: T-Task

#7458 Limit max-width for bubble layout to 1200px
  res/css/views/rooms/_EventBubbleTile.scss
  src/components/structures/RoomView.tsx
Labels: T-Enhancement

#7478 Allow bubble layout in Thread View
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_EventTile.scss
  src/components/structures/ThreadView.tsx
  src/components/views/rooms/EventTile.tsx
Labels: T-Enhancement

#7516 Make LocationPicker appearance cleaner
  res/css/_common.scss
  res/css/views/location/_LocationPicker.scss
  src/components/views/location/LocationPicker.tsx
Labels: T-Enhancement

#7513 Allow using room pills in slash commands
  src/SlashCommands.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/editor/commands.tsx
  src/editor/serialize.ts
  src/i18n/strings/en_EN.json
  src/languageHandler.tsx
Labels: T-Defect

#7523 Update test snapshots to reflect new field in Room
  test/components/views/elements/__snapshots__/PollCreateDialog-test.tsx.snap
Labels: T-Task

#7524 Set the default zoom level for location to 15, matching iOS and Android
  src/components/views/location/LocationPicker.tsx
  src/components/views/messages/MLocationBody.tsx
Labels: T-Task

#7522 Prevent enter to send edit weirdness when no change has been made
  src/components/views/rooms/EditMessageComposer.tsx
Labels: T-Defect

#7512 Fix RoomViewStore forgetting some details of a view room call
  src/components/structures/RoomView.tsx
  src/components/structures/SpaceHierarchy.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/context_menus/SpaceContextMenu.tsx
  src/components/views/dialogs/CreateSpaceFromCommunityDialog.tsx
  src/components/views/dialogs/ForwardDialog.tsx
  src/components/views/dialogs/SpotlightDialog.tsx
  src/components/views/rooms/RecentlyViewedButton.tsx
  src/components/views/rooms/RoomBreadcrumbs.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomListHeader.tsx
  src/components/views/rooms/RoomSublist.tsx
  src/components/views/rooms/RoomTile.tsx
  src/components/views/settings/JoinRuleSettings.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/linkify-matrix.ts
  src/stores/RoomViewStore.tsx
  src/stores/right-panel/RightPanelStore.ts
  src/stores/spaces/SpaceStore.ts
  test/stores/SpaceStore-test.ts
Labels: T-Task

#7532 Fix translation for the "Add room" tooltip
  src/components/views/rooms/RoomList.tsx
Labels: T-Defect

#7530 Use published matrix-web-i18n
  package.json
  yarn.lock
Labels: T-Task

#7462 Render events as extensible events (behind labs)
  package.json
  scripts/fetchdep.sh
  src/TextForEvent.tsx
  src/components/views/messages/TextualBody.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  yarn.lock
Labels: T-Enhancement

#7538 truncate room name on pip header
  res/css/views/voip/_CallViewHeader.scss
  src/components/views/voip/CallView/CallViewHeader.tsx
Labels: T-Defect

#7541 Set initial zoom level to 1 to make zooming to location faster
  src/components/views/location/LocationPicker.tsx
Labels: T-Defect

#7539 Refresh ThreadView after React state has been updated
  src/components/structures/ThreadView.tsx
Labels: T-Defect

#7469 Replace `kick` terminology with `Remove from chat`
  src/SlashCommands.tsx
  src/TextForEvent.tsx
  src/components/views/elements/MemberEventListSummary.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/widgets/CapabilityText.tsx
  test/components/views/elements/MemberEventListSummary-test.js
  test/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
Labels: X-Blocked, T-Enhancement

#7543 Support deserialising HR tags for editing
  src/components/views/rooms/EditMessageComposer.tsx
  src/editor/deserialize.ts
Labels: T-Defect

#7544 Always show right panel after setting a card
  src/stores/right-panel/RightPanelStore.ts
Labels: T-Defect

#7537 Add a developer mode 'view source' button to crashed event tiles
  src/components/views/messages/TileErrorBoundary.tsx
Labels: T-Enhancement

#7547 Add setting for enabling location sharing
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Enhancement

#7553 Make widgets and calls span across the whole room width when using bubble layout
  res/css/views/rooms/_EventBubbleTile.scss
Labels: T-Defect

#7198 Make the `Keyboard Shortcuts` dialog into a settings tab
  res/css/_components.scss
  res/css/views/dialogs/_UserSettingsDialog.scss
  res/css/views/settings/tabs/user/_KeyboardUserSettingsTab.scss
  res/img/element-icons/settings/keyboard.svg
  src/KeyBindingsDefaults.ts
  src/KeyBindingsManager.ts
  src/accessibility/KeyboardShortcuts.ts
  src/components/structures/LoggedInView.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/components/views/settings/tabs/user/KeyboardUserSettingsTab.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7556 Wait for initial profile load before displaying widget
  src/components/views/elements/AppTile.tsx
  src/stores/OwnProfileStore.ts
Labels: T-Defect

#7555 Improve QueryMatcher TypeScript definition
  src/@types/common.ts
  src/autocomplete/QueryMatcher.ts
Labels: T-Task

#7517 Move all polls processing to events-sdk & prep for stable polls
  package.json
  src/TextForEvent.tsx
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/dialogs/EndPollDialog.tsx
  src/components/views/elements/PollCreateDialog.tsx
  src/components/views/messages/MPollBody.tsx
  src/components/views/messages/MessageEvent.tsx
  src/components/views/messages/TextualBody.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/stores/room-list/MessagePreviewStore.ts
  src/stores/room-list/previews/PollStartEventPreview.ts
  src/utils/EventUtils.ts
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/messages/__snapshots__/MPollBody-test.tsx.snap
  test/stores/room-list/previews/PollStartEventPreview-test.ts
  yarn.lock
Labels: T-Task

#7557 Start a conference in a room with 2 people + invitee rather than a 1:1 call
  src/CallHandler.tsx
  test/CallHandler-test.ts
Labels: T-Defect

#7529 Fix timeline jumping issues related to bubble layout
  res/css/views/rooms/_EventBubbleTile.scss
  src/components/structures/ScrollPanel.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/messages/MImageBody.tsx
Labels: T-Defect

#7564 Differentiate between hover and roving focus in spotlight dialog
  res/css/views/dialogs/_SpotlightDialog.scss
Labels: T-Defect

#7561 Use PR number directly in netlify github action
  .github/workflows/layered-build.yaml
  .github/workflows/netlify.yaml
Labels: T-Task

#7568 Ensure maps show up in replies and threads, by creating unique IDs
  src/components/views/messages/MLocationBody.tsx
Labels: T-Defect

#7571 Replace home icon with new one
  res/css/structures/_SpacePanel.scss
  res/css/structures/_UserMenu.scss
  res/img/element-icons/home.svg
  res/img/element-icons/roomlist/home.svg
  src/components/views/context_menus/SpaceContextMenu.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7572 Update sidebar icon from Compound
  res/img/element-icons/settings/sidebar.svg
Labels: T-Enhancement

#7563 Fix `/jumptodate` using wrong MSC feature flag
  src/SlashCommands.tsx
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
Labels: T-Defect

#7282 Upgrade linkify to v3.0
  package.json
  src/linkify-matrix.ts
  test/linkify-matrix-test.ts
  yarn.lock
Labels: T-Enhancement

#7570 Fix wrong icon being used for appearance tab in space preferences dialog
  res/css/views/dialogs/_SpacePreferencesDialog.scss
  src/components/views/dialogs/SpacePreferencesDialog.tsx
Labels: T-Defect

#7552 Improve/add notifications for location and poll events
  src/Notifier.ts
  src/TextForEvent.tsx
  src/i18n/strings/en_EN.json
  test/TextForEvent-test.ts
Labels: T-Enhancement

#7569 Fix MAB overlapping or overflowing in bubbles layout and threads regressions
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#7551 Fix left positioned tooltips being wrong and offset by fixed value
  res/css/views/elements/_Tooltip.scss
  res/css/views/rooms/_EventTile.scss
  src/components/views/elements/Tooltip.tsx
  src/components/views/rooms/EventTile.tsx
  test/components/views/elements/__snapshots__/TooltipTarget-test.tsx.snap
Labels: T-Defect

#7574 Display general marker on non-self location shares
  res/css/views/messages/_MLocationBody.scss
  res/img/element-icons/location.svg
  res/themes/legacy-light/css/_legacy-light.scss
  res/themes/light/css/_light.scss
  src/components/views/messages/MLocationBody.tsx
  test/components/views/messages/MLocationBody-test.tsx
Labels: T-Enhancement

#7582 Fix alignment of unread badge in thread list
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#7583 Cancel pending events in virtual room when call placed
  src/CallHandler.tsx
  src/Resend.ts
Labels: T-Defect

#7581 Enable the polls feature
  src/components/views/messages/MessageEvent.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/room-list/MessagePreviewStore.ts
Labels: T-Enhancement

#5887 Show a tile at beginning of visible history
  res/css/_components.scss
  res/css/views/rooms/_HistoryTile.scss
  src/components/structures/MessagePanel.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/rooms/HistoryTile.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7453 Parse matrix-schemed URIs
  package.json
  src/HtmlUtils.tsx
  src/components/views/elements/Pill.js
  src/linkify-matrix.ts
  src/utils/permalinks/MatrixSchemePermalinkConstructor.ts
  src/utils/permalinks/MatrixToPermalinkConstructor.ts
  src/utils/permalinks/Permalinks.ts
  src/utils/pillify.tsx
  test/components/views/messages/TextualBody-test.js
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/linkify-matrix-test.ts
  yarn.lock
Labels: T-Enhancement

#7591 add more tests to TextForEvent
  test/TextForEvent-test.ts
Labels: T-Task

#7502 Allow downloads from widgets
  src/components/views/elements/AppTile.tsx
Labels: T-Enhancement

#7588 Switch to github: URL to be consistent with other deps
  package.json
  yarn.lock
Labels: T-Task

#7592 Add tooltips to emoji in messages
  res/css/views/rooms/_EventTile.scss
  src/HtmlUtils.tsx
Labels: T-Enhancement

#7590 Disable location sharing button on Desktop
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
Labels: T-Defect

#7597 Make the close button of the location share dialog visible in high-contrast theme
  res/themes/light-high-contrast/css/_light-high-contrast.scss
Labels: T-Defect

#7609 Fix space member list not opening
  src/components/structures/SpaceRoomView.tsx
Labels: T-Defect

#7562 Improve the look of the keyboard settings tab
  res/css/views/settings/tabs/user/_KeyboardUserSettingsTab.scss
  src/accessibility/KeyboardShortcuts.ts
  src/components/views/settings/tabs/user/KeyboardUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/accessibility/KeyboardShortcuts-test.ts
  test/components/views/settings/tabs/user/KeyboardUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/KeyboardUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#7600 Make room ID copyable
  res/css/_components.scss
  res/css/views/elements/_CopyableText.scss
  res/css/views/settings/tabs/user/_HelpUserSettingsTab.scss
  src/components/views/elements/CopyableText.tsx
  src/components/views/settings/tabs/room/AdvancedRoomSettingsTab.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7601 Unhide display names when switching back to modern layout
  src/components/structures/MessagePanel.tsx
Labels: T-Defect

#7603 Fix translation of "powerText"
  src/components/views/rooms/EntityTile.tsx
Labels: T-Defect

#7606 Prevent pills from being split by formatting actions
  res/css/views/rooms/_BasicMessageComposer.scss
Labels: T-Defect

#7605 Fix excessive padding on inline images
  res/css/views/rooms/_EventTile.scss
  src/HtmlUtils.tsx
Labels: T-Defect

#7607 Make pills more natural to navigate around
  res/css/views/rooms/_BasicMessageComposer.scss
Labels: T-Defect

#7596 Re-renable Share option for location messages
  src/components/views/context_menus/MessageContextMenu.tsx
Labels: T-Enhancement

#7155 Add ability to switch between voice & video in calls
  res/css/views/voip/_CallViewHeader.scss
  src/components/views/voip/CallView.tsx
  src/components/views/voip/CallView/CallViewHeader.tsx
  src/components/views/voip/PipView.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7602 Enlarge emoji in composer
  res/css/views/elements/_RichText.scss
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_SendMessageComposer.scss
  src/HtmlUtils.tsx
  src/components/views/rooms/BasicMessageComposer.tsx
  src/editor/autocomplete.ts
  src/editor/caret.ts
  src/editor/deserialize.ts
  src/editor/parts.ts
  src/editor/render.ts
  src/editor/serialize.ts
Labels: T-Defect

#7573 Don't render a bubble around emotes in bubble layout
  res/css/views/rooms/_EventBubbleTile.scss
  src/components/views/rooms/EventTile.tsx
  src/utils/EventUtils.ts
Labels: T-Enhancement

#7614 a11y - fix iframes without title
  .eslintrc.js
  src/components/views/dialogs/HostSignupDialog.tsx
  src/components/views/dialogs/ModalWidgetDialog.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/messages/MFileBody.tsx
  src/components/views/settings/IntegrationManager.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#7611 Always emit a space filter update when the space is actually changed
  src/stores/room-list/filters/SpaceFilterCondition.ts
Labels: T-Defect

#7575 Make widgets not reload (persistent) between center and top container
  src/components/views/elements/AppTile.tsx
  src/components/views/rooms/AppsDrawer.tsx
  src/components/views/voip/PipView.tsx
  src/stores/right-panel/RightPanelStore.ts
  src/stores/widgets/StopGapWidget.ts
  src/stores/widgets/WidgetLayoutStore.ts
Labels: T-Enhancement

#7616 Fall back to legacy analytics for guest users
  src/components/structures/MatrixChat.tsx
Labels: T-Defect

#7617 Fix space member list right panel state
  src/stores/right-panel/RightPanelStore.ts
Labels: T-Defect

#7578 Tweak copy for the Sidebar tab in User Settings
  src/components/views/settings/tabs/user/SidebarUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7618 Add labs flag for default open right panel
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/right-panel/RightPanelStore.ts
Labels: T-Enhancement

#7604 Avoid double dialog after clicking to remove a public room
  src/components/structures/RoomDirectory.tsx
Labels: T-Defect

#7585 Wrapping component to show/hide UI based on UIFeature setting
  src/components/views/settings/UiFeatureSettingWrapper.tsx
  test/components/views/settings/UiFeatureSettingWrapper-test.tsx
  test/components/views/settings/__snapshots__/UiFeatureSettingWrapper-test.tsx.snap
Labels: T-Task

#7595 Add customisation point for mxid display
  res/css/views/settings/_ProfileSettings.scss
  src/TextForEvent.tsx
  src/autocomplete/UserProvider.tsx
  src/components/structures/UserMenu.tsx
  src/components/views/avatars/MemberAvatar.tsx
  src/components/views/dialogs/ConfirmSpaceUserActionDialog.tsx
  src/components/views/dialogs/ConfirmUserActionDialog.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/messages/SenderProfile.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/MemberTile.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/components/views/settings/ProfileSettings.tsx
  src/customisations/UserIdentifier.ts
  test/TextForEvent-test.ts
Labels: T-Enhancement

#7612 De-labs Message Bubbles layout
  src/components/views/settings/LayoutSwitcher.tsx
  src/components/views/settings/tabs/user/AppearanceUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/controllers/NewLayoutSwitcherController.ts
Labels: X-Release-Blocker, T-Enhancement

#7621 Improve taken username warning in registration for when request fails
  src/components/views/auth/RegistrationForm.tsx
  src/components/views/elements/Validation.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7613 De-labs Metaspaces
  res/css/views/settings/tabs/user/_SidebarUserSettingsTab.scss
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/stores/SpaceStore-test.ts
  test/stores/enable-metaspaces-labs.ts
  test/stores/room-list/SpaceWatcher-test.ts
Labels: X-Release-Blocker, T-Enhancement

#7622 Show bubble tile timestamps for bubble layout inside the bubble
  res/css/views/messages/_CallEvent.scss
  res/css/views/messages/_EventTileBubble.scss
  res/css/views/rooms/_EventBubbleTile.scss
  src/components/views/messages/CallEvent.tsx
  src/components/views/messages/EncryptionEvent.tsx
  src/components/views/messages/EventTileBubble.tsx
  src/components/views/messages/MJitsiWidgetEvent.tsx
  src/components/views/messages/MKeyVerificationConclusion.tsx
  src/components/views/messages/MKeyVerificationRequest.tsx
  src/components/views/messages/RoomCreate.tsx
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#7626 Tweak light hover & active color for bubble layout
  res/themes/light/css/_light.scss
Labels: T-Enhancement

#7628 Upgrade linkifyjs to fix schemes as domain prefixes
  package.json
  src/linkify-matrix.ts
  test/linkify-matrix-test.ts
  yarn.lock
Labels: T-Defect

#7577 Tweak room list header menu for when space is active
  res/css/views/rooms/_RoomListHeader.scss
  src/components/views/rooms/RoomListHeader.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7629 Fix issue with the new composer EmojiPart which caused infinite loops
  src/editor/parts.ts
Labels: T-Defect

#7631 Changed MacOS hotkey for GoToHome view.
  src/KeyBindingsDefaults.ts
  src/accessibility/KeyboardShortcuts.ts
Labels: T-Defect

#7625 Fix unfocused paste handling and focus return for file uploads
  src/ContentMessages.tsx
  src/components/structures/LoggedInView.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
Labels: X-Release-Blocker, T-Defect

#7633 Translate keyboard shortcut alternate key names
  src/components/structures/RoomSearch.tsx
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/spaces/SpacePanel.tsx
Labels: T-Defect

#7632 Prevent infinite loops by dropping the input instead of crashing browser
  src/editor/model.ts
Labels: T-Task

#7634 runAllTimers -> runOnlyPendingTimers in SpaceStore-test
  test/stores/SpaceStore-test.ts
Labels: T-Task

#7640 Fix React unique key errors
  src/components/views/messages/MessageActionBar.tsx
Labels: T-Task

#7635 Correctly handle Room.timeline events which have a nullable `Room`
  src/actions/MatrixActionCreators.ts
  src/autocomplete/UserProvider.tsx
  src/components/structures/FilePanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/avatars/DecoratedRoomAvatar.tsx
  src/components/views/rooms/WhoIsTypingTile.tsx
  src/indexing/EventIndex.ts
  src/stores/notifications/RoomNotificationState.ts
  src/stores/room-list/RoomListStore.ts
Labels: T-Defect

#7641 Revert "Start a conference in a room with 2 people + invitee rather than a 1:1 call"
  src/CallHandler.tsx
  test/CallHandler-test.ts
Labels: T-Defect

#7642 Fix RightPanelStore assuming isViewingRoom is false on load
  src/stores/right-panel/RightPanelStore.ts
Labels: X-Release-Blocker, T-Defect

#7645 Fix soft-crash when hanging up Jitsi via PIP
  src/components/views/voip/CallView/CallViewHeader.tsx
  src/components/views/voip/PipView.tsx
Labels: X-Release-Blocker, T-Defect

#7643 Load light theme prior to HTML export to ensure it is present
  src/utils/exportUtils/exportCSS.ts
Labels: X-Release-Blocker, T-Defect

#7584 Add a keyboard shortcut to toggle hidden event visibility when labs are enabled
  src/KeyBindingsDefaults.ts
  src/KeyBindingsManager.ts
  src/accessibility/KeyboardShortcuts.ts
  src/components/structures/LoggedInView.tsx
  src/components/views/settings/tabs/user/KeyboardUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7649 Add grouper for hidden events
  src/components/structures/MessagePanel.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7648 Fix search results view for layouts other than Group/Modern
  res/css/structures/_RoomView.scss
  src/components/structures/MessagePanel.tsx
  src/components/structures/RoomView.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/ReadReceiptMarker.tsx
  src/components/views/rooms/SearchResultTile.tsx
Labels: T-Defect

#7644 Fix space panel edge gradient not applying on load
  src/components/structures/IndicatorScrollbar.tsx
  src/components/views/spaces/SpacePanel.tsx
Labels: T-Defect

#7637 Fix emojis getting cropped in irc & bubble layouts by anti-zalgo
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_IRCLayout.scss
Labels: T-Defect

#7623 Look up tile server info in homeserver's .well-known area
  src/components/views/location/LocationPicker.tsx
  src/components/views/location/LocationViewDialog.tsx
  src/components/views/messages/MLocationBody.tsx
  src/utils/WellKnownUtils.ts
Labels: T-Enhancement
