Repository matrix-org/matrix-react-sdk, pull requests merged in 2022-10, with the labels that each got.

#9341 Check for the spec version when determining private read receipt support
  src/components/structures/TimelinePanel.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
Labels: T-Task

#9314 Device manager - record device client information on app start (PSG-633)
  src/DeviceListener.ts
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/utils/device/clientInformation.ts
  test/DeviceListener-test.ts
  test/utils/device/clientInformation-test.ts
Labels: T-Task

#9330 Device manager - select all devices
  res/css/components/views/settings/devices/_FilteredDeviceList.pcss
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/FilteredDeviceListHeader.tsx
  test/components/views/settings/devices/FilteredDeviceListHeader-test.tsx
  test/components/views/settings/devices/__snapshots__/FilteredDeviceListHeader-test.tsx.snap
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Enhancement

#9315 Device manager - display client information in device details (PSG-682)
  src/components/views/settings/devices/DeviceDetails.tsx
  src/components/views/settings/devices/types.ts
  src/components/views/settings/devices/useOwnDevices.ts
  src/i18n/strings/en_EN.json
  src/utils/device/clientInformation.ts
  test/DeviceListener-test.ts
  test/components/views/settings/devices/DeviceDetails-test.tsx
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceDetails-test.tsx.snap
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/utils/device/clientInformation-test.ts
Labels: T-Enhancement

#9349 Remove unspecced `original_event` field from the `readEventRelations` response
  src/stores/widgets/StopGapWidgetDriver.ts
  test/stores/widgets/StopGapWidgetDriver-test.ts
Labels: Z-Community-PR, T-Task

#9350 Convert inputs on Export/Import Room Key dialogs to be real Fields
  src/@types/common.ts
  src/async-components/views/dialogs/security/ExportE2eKeysDialog.tsx
  src/async-components/views/dialogs/security/ImportE2eKeysDialog.tsx
Labels: T-Task

#9344 Device manager - add foundation for extended device info
  res/css/_components.pcss
  res/css/components/views/settings/devices/_DeviceTypeIcon.pcss
  res/css/views/settings/_DevicesPanel.pcss
  src/components/views/settings/DevicesPanelEntry.tsx
  src/components/views/settings/devices/CurrentDeviceSection.tsx
  src/components/views/settings/devices/DeviceDetailHeading.tsx
  src/components/views/settings/devices/DeviceDetails.tsx
  src/components/views/settings/devices/DeviceTile.tsx
  src/components/views/settings/devices/DeviceTypeIcon.tsx
  src/components/views/settings/devices/DeviceVerificationStatusCard.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/SecurityRecommendations.tsx
  src/components/views/settings/devices/filter.ts
  src/components/views/settings/devices/types.ts
  src/components/views/settings/devices/useOwnDevices.ts
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/utils/device/parseUserAgent.ts
  test/components/views/settings/__snapshots__/DevicesPanel-test.tsx.snap
  test/components/views/settings/devices/CurrentDeviceSection-test.tsx
  test/components/views/settings/devices/DeviceDetailHeading-test.tsx
  test/components/views/settings/devices/DeviceDetails-test.tsx
  test/components/views/settings/devices/DeviceTile-test.tsx
  test/components/views/settings/devices/DeviceTypeIcon-test.tsx
  test/components/views/settings/devices/FilteredDeviceList-test.tsx
  test/components/views/settings/devices/SelectableDeviceTile-test.tsx
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceTile-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceType-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceTypeIcon-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/SelectableDeviceTile-test.tsx.snap
  test/components/views/settings/devices/filter-test.ts
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
  test/utils/device/parseUserAgent-test.ts
Labels: T-Task

#9357 Delete the remainder of groups
  src/IConfigOptions.ts
  src/PageTypes.ts
  src/PosthogTrackers.ts
  src/SdkConfig.ts
  src/components/structures/LegacyGroupView.tsx
  src/components/structures/LoggedInView.tsx
  src/components/structures/MatrixChat.tsx
  src/group_helpers.tsx
  src/i18n/strings/en_EN.json
  src/linkify-matrix.ts
  src/utils/permalinks/ElementPermalinkConstructor.ts
  src/utils/permalinks/MatrixSchemePermalinkConstructor.ts
  src/utils/permalinks/MatrixToPermalinkConstructor.ts
  src/utils/permalinks/PermalinkConstructor.ts
  src/utils/permalinks/Permalinks.ts
Labels: T-Enhancement

#9339 Fix applying programmatically set height for "top" room layout
  cypress/e2e/widgets/layout.spec.ts
  src/components/views/rooms/AppsDrawer.tsx
Labels: Z-Community-PR, T-Defect

#9352 Device manager - parse user agent for device information
  package.json
  src/utils/device/parseUserAgent.ts
  test/utils/device/parseUserAgent-test.ts
  yarn.lock
Labels: T-Task

#9355 Device manager - device type icon
  res/css/components/views/settings/devices/_DeviceTypeIcon.pcss
  res/img/element-icons/settings/desktop.svg
  res/img/element-icons/settings/mobile.svg
  res/img/element-icons/settings/web.svg
  src/components/views/settings/devices/DeviceTypeIcon.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/__snapshots__/DevicesPanel-test.tsx.snap
  test/components/views/settings/devices/DeviceTypeIcon-test.tsx
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceTile-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceTypeIcon-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/SelectableDeviceTile-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Enhancement

#9363 cypress - maybe improve "should close spotlight after starting a DM" stability
  cypress/e2e/spotlight/spotlight.spec.ts
Labels: T-Task

#9364 cypress - avoid autojoin latency in "should be usable for a conversation"
  cypress/e2e/threads/threads.spec.ts
Labels: T-Task

#9346 Pass language to Jitsi Widget
  src/utils/WidgetUtils.ts
  test/utils/WidgetUtils-test.ts
Labels: Z-Community-PR, T-Enhancement

#9351 New group call experience: Room header and PiP designs
  cypress/e2e/lazy-loading/lazy-loading.spec.ts
  res/css/_common.pcss
  res/css/structures/_HeaderButtons.pcss
  res/css/views/elements/_Tooltip.pcss
  res/css/views/rooms/_JumpToBottomButton.pcss
  res/css/views/rooms/_RoomHeader.pcss
  res/css/views/rooms/_TopUnreadMessagesBar.pcss
  res/css/views/voip/_LegacyCallViewHeader.pcss
  res/img/cancel.svg
  res/img/element-icons/call/freedom.svg
  res/img/element-icons/call/spotlight.svg
  res/img/element-icons/reduce.svg
  res/img/feather-customised/cancel.svg
  res/img/feather-customised/chevron-down-thin.svg
  src/components/structures/RoomView.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/elements/Tooltip.tsx
  src/components/views/right_panel/HeaderButton.tsx
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/components/views/rooms/E2EIcon.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomTile.tsx
  src/components/views/voip/LegacyCallView/LegacyCallViewHeader.tsx
  src/components/views/voip/PictureInPictureDragger.tsx
  src/components/views/voip/PipView.tsx
  src/contexts/RoomContext.ts
  src/hooks/useCall.ts
  src/i18n/strings/en_EN.json
  src/models/Call.ts
  src/stores/CallStore.ts
  src/stores/RoomViewStore.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/elements/__snapshots__/TooltipTarget-test.tsx.snap
  test/components/views/messages/CallEvent-test.tsx
  test/components/views/rooms/MessageComposerButtons-test.tsx
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/RoomTile-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/components/views/voip/CallView-test.tsx
  test/components/views/voip/PipView-test.tsx
  test/models/Call-test.ts
  test/stores/room-list/algorithms/Algorithm-test.ts
  test/toasts/IncomingCallToast-test.tsx
Labels: T-Enhancement

#9320 Fix dark and white theme switch in Chrome
  src/theme.ts
  test/theme-test.ts
Labels: T-Defect

#9369 Fix flaky polls test
  cypress/e2e/polls/polls.spec.ts
Labels: T-Task

#9360 Device manager - render extended device information
  src/components/views/settings/devices/DeviceDetails.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/DeviceDetails-test.tsx
  test/components/views/settings/devices/__snapshots__/DeviceDetails-test.tsx.snap
Labels: T-Enhancement

#9370 Increase timout waiting for home screen after login in cypress test
  cypress/e2e/login/login.spec.ts
Labels: T-Task

#9361 Cypress - increase initial app load timeout to 30s
  cypress/support/login.ts
Labels: T-Task

#9371 Increase timeout in Cypress register test
  cypress/e2e/register/register.spec.ts
Labels: T-Task

#9373 Cypress - stabilise "creating a DM should work" test
  cypress/e2e/crypto/crypto.spec.ts
  cypress/support/bot.ts
Labels: T-Task

#9367 Always allow enabling sending read receipts
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  test/components/views/settings/tabs/user/PreferencesUserSettingsTab-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Defect

#9375 Close incoming Element call toast when viewing the call lobby
  src/toasts/IncomingCallToast.tsx
  test/toasts/IncomingCallToast-test.tsx
Labels: T-Defect

#9347 Add Element Call room settings
  res/css/views/dialogs/_RoomSettingsDialog.pcss
  src/IConfigOptions.ts
  src/SdkConfig.ts
  src/components/views/dialogs/RoomSettingsDialog.tsx
  src/components/views/elements/AccessibleTooltipButton.tsx
  src/components/views/elements/LabelledToggleSwitch.tsx
  src/components/views/elements/SettingsFlag.tsx
  src/components/views/elements/ToggleSwitch.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/settings/devices/DeviceDetails.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/components/views/settings/tabs/room/VoipRoomSettingsTab.tsx
  src/createRoom.ts
  src/i18n/strings/en_EN.json
  test/components/views/location/__snapshots__/LocationShareMenu-test.tsx.snap
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/settings/__snapshots__/Notifications-test.tsx.snap
  test/components/views/settings/tabs/room/RolesRoomSettingsTab-test.tsx
  test/components/views/settings/tabs/room/VoipRoomSettingsTab-test.tsx
  test/createRoom-test.ts
  test/utils/device/clientInformation-test.ts
Labels: T-Enhancement

#9376 Handle missing Element Call `brand`
  src/IConfigOptions.ts
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/components/views/settings/tabs/room/VoipRoomSettingsTab.tsx
  src/models/Call.ts
  src/stores/widgets/StopGapWidgetDriver.ts
Labels: T-Defect

#9358 Add Element Call participant limit
  src/IConfigOptions.ts
  src/SdkConfig.ts
  src/components/views/messages/CallEvent.tsx
  src/components/views/voip/CallView.tsx
  src/hooks/useCall.ts
  src/i18n/strings/en_EN.json
  src/toasts/IncomingCallToast.tsx
  test/components/views/voip/CallView-test.tsx
Labels: T-Enhancement

#9381 Pin back Synapse used in Cypress to alleviate test failures
  cypress/plugins/synapsedocker/index.ts
Labels: T-Task

#9353 Device manager - eagerly create `m.local_notification_settings` events
  src/Notifier.ts
  src/utils/notifications.ts
  test/Notifier-test.ts
  test/utils/notifications-test.ts
Labels: T-Defect

#9384 Device manager - remove client information events when disabling setting
  src/DeviceListener.ts
  src/utils/device/clientInformation.ts
  test/DeviceListener-test.ts
Labels: T-Enhancement

#9382 Device manager - UA parsing tweaks
  src/utils/device/parseUserAgent.ts
  test/utils/device/parseUserAgent-test.ts
Labels: T-Task, T-Enhancement

#9374 First step of matrix-wysiwyg integration
  package.json
  res/css/_components.pcss
  res/css/views/rooms/wysiwyg_composer/_WysiwygComposer.pcss
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/wysiwyg_composer/WysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/message.ts
  src/contexts/MatrixClientContext.tsx
  src/contexts/RoomContext.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/views/rooms/MessageComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/WysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/message-test.ts
  yarn.lock
Labels: T-Enhancement

#9380 Device manager - promote to beta
  src/actions/handlers/viewUserDeviceSettings.ts
  src/components/structures/MatrixChat.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/dispatcher/actions.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/toasts/BulkUnverifiedSessionsToast.ts
  src/toasts/UnverifiedSessionToast.ts
  test/actions/handlers/viewUserDeviceSettings-test.ts
  test/components/views/settings/tabs/user/LabsUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/SecurityUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/LabsUserSettingsTab-test.tsx.snap
  test/test-utils/client.ts
Labels: T-Task

#9388 use correct default for notification silencing
  src/utils/notifications.ts
  test/utils/notifications-test.ts
Labels: T-Defect, backport staging

#9307 Implement Voice Broadcast recording
  src/IConfigOptions.ts
  src/SdkConfig.ts
  src/audio/VoiceRecording.ts
  src/voice-broadcast/audio/VoiceBroadcastRecorder.ts
  src/voice-broadcast/components/VoiceBroadcastBody.tsx
  src/voice-broadcast/components/index.ts
  src/voice-broadcast/index.ts
  src/voice-broadcast/models/VoiceBroadcastRecording.ts
  src/voice-broadcast/models/index.ts
  src/voice-broadcast/stores/VoiceBroadcastRecordingsStore.ts
  src/voice-broadcast/stores/index.ts
  src/voice-broadcast/utils/index.ts
  src/voice-broadcast/utils/startNewVoiceBroadcastRecording.ts
  test/SdkConfig-test.ts
  test/voice-broadcast/audio/VoiceBroadcastRecorder-test.ts
  test/voice-broadcast/components/VoiceBroadcastBody-test.tsx
  test/voice-broadcast/models/VoiceBroadcastRecording-test.ts
  test/voice-broadcast/stores/VoiceBroadcastRecordingsStore-test.ts
  test/voice-broadcast/utils/startNewVoiceBroadcastRecording-test.ts
Labels: T-Task

#9394 Include device_id in voice broadcast info events
  src/voice-broadcast/index.ts
  src/voice-broadcast/models/VoiceBroadcastRecording.ts
  src/voice-broadcast/utils/startNewVoiceBroadcastRecording.ts
  test/voice-broadcast/models/VoiceBroadcastRecording-test.ts
  test/voice-broadcast/utils/startNewVoiceBroadcastRecording-test.ts
Labels: T-Task

#9393 Extract voice broadcast header
  res/css/_components.pcss
  res/css/components/atoms/_Icon.pcss
  res/css/voice-broadcast/atoms/_VoiceBroadcastHeader.pcss
  src/components/atoms/Icon.tsx
  src/i18n/strings/en_EN.json
  src/voice-broadcast/components/VoiceBroadcastBody.tsx
  src/voice-broadcast/components/atoms/VoiceBroadcastHeader.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingBody.tsx
  src/voice-broadcast/index.ts
  test/voice-broadcast/components/VoiceBroadcastBody-test.tsx
  test/voice-broadcast/components/atoms/VoiceBroadcastHeader-test.tsx
  test/voice-broadcast/components/atoms/__snapshots__/VoiceBroadcastHeader-test.tsx.snap
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingBody-test.tsx
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastRecordingBody-test.tsx.snap
Labels: T-Task

#9396 Make bash scripts exit on error rather than continue
  scripts/ci/layered.sh
Labels: T-Task

#9401 Fix voice broadcast "live" icon
  res/css/components/atoms/_Icon.pcss
  src/components/atoms/Icon.tsx
Labels: T-Task

#9402 Use a more correct subset of users in `/remakeolm` developer command
  src/SlashCommands.tsx
Labels: T-Defect

#9399 Add MessageEvent voice broadcast setting watch
  src/components/views/messages/MessageEvent.tsx
  test/components/views/messages/MessageEvent-test.tsx
Labels: T-Task

#9395 Update the documentation for the show_labs_settings parameter
  docs/settings.md
Labels: Z-Community-PR, T-Task

#9345 Move from `browser-request` to `fetch`
  __mocks__/browser-request.js
  cypress/e2e/spotlight/spotlight.spec.ts
  cypress/e2e/timeline/timeline.spec.ts
  cypress/support/bot.ts
  cypress/support/client.ts
  package.json
  src/AddThreepid.ts
  src/ContentMessages.ts
  src/Lifecycle.ts
  src/Login.ts
  src/ScalarAuthClient.ts
  src/components/structures/EmbeddedPage.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/structures/UploadBar.tsx
  src/components/structures/auth/Login.tsx
  src/components/views/dialogs/ChangelogDialog.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/dialogs/SlidingSyncOptionsDialog.tsx
  src/components/views/elements/MiniAvatarUploader.tsx
  src/components/views/room_settings/RoomProfileSettings.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/components/views/settings/ChangeAvatar.tsx
  src/components/views/settings/ProfileSettings.tsx
  src/createRoom.ts
  src/customisations/Media.ts
  src/customisations/models/IMediaEventContent.ts
  src/dispatcher/payloads/UploadPayload.ts
  src/i18n/strings/en_EN.json
  src/languageHandler.tsx
  src/models/IUpload.ts
  src/models/RoomUpload.ts
  src/utils/MultiInviter.ts
  src/voice-broadcast/models/VoiceBroadcastRecording.ts
  test/ContentMessages-test.ts
  test/ScalarAuthClient-test.ts
  test/audio/VoiceMessageRecording-test.ts
  test/components/views/context_menus/EmbeddedPage-test.tsx
  test/components/views/context_menus/__snapshots__/EmbeddedPage-test.tsx.snap
  test/components/views/dialogs/ChangelogDialog-test.tsx
  test/components/views/dialogs/InviteDialog-test.tsx
  test/components/views/dialogs/__snapshots__/ChangelogDialog-test.tsx.snap
  test/components/views/rooms/RoomPreviewBar-test.tsx
  test/createRoom-test.ts
  test/i18n-test/languageHandler-test.tsx
  test/setup/setupLanguage.ts
  test/setup/setupManualMocks.ts
  test/setupTests.js
  test/test-utils/test-utils.ts
  test/utils/MultiInviter-test.ts
  yarn.lock
Labels: T-Task

#9386 Device manager - current session context menu
  res/css/_components.pcss
  res/css/components/views/context_menus/_KebabContextMenu.pcss
  res/css/views/context_menus/_IconizedContextMenu.pcss
  src/components/structures/ContextMenu.tsx
  src/components/views/context_menus/IconizedContextMenu.tsx
  src/components/views/context_menus/KebabContextMenu.tsx
  src/components/views/settings/devices/CurrentDeviceSection.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/shared/SettingsSubsectionHeading-test.tsx
  test/components/views/settings/shared/__snapshots__/SettingsSubsectionHeading-test.tsx.snap
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Enhancement

#9392 Device manager - test coverage for Notifier
  src/Notifier.ts
  test/Notifier-test.ts
Labels: T-Task

#9398 Device manager - cypress test
  cypress/e2e/settings/device-management.spec.ts
  cypress/support/login.ts
Labels: T-Task

#9406 Extract useVoiceBroadcastRecording hook
  src/voice-broadcast/components/VoiceBroadcastBody.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingBody.tsx
  src/voice-broadcast/hooks/useVoiceBroadcastRecording.ts
  src/voice-broadcast/index.ts
  src/voice-broadcast/stores/VoiceBroadcastRecordingsStore.ts
  test/voice-broadcast/components/VoiceBroadcastBody-test.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingBody-test.tsx
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastRecordingBody-test.tsx.snap
  test/voice-broadcast/stores/VoiceBroadcastRecordingsStore-test.ts
Labels: T-Task

#9407 Do not create account data event for guests
  src/utils/notifications.ts
  test/utils/notifications-test.ts
Labels: T-Task

#9411 Fix flakiness of kick.spec.ts due to `cy.get(...).contains(...).should(...);` anti-pattern
  cypress/e2e/integration-manager/kick.spec.ts
Labels: T-Task

#9405 Migrate KeyboardShortcut tests from Enzyme to RTL
  test/components/views/settings/KeyboardShortcut-test.tsx
  test/components/views/settings/__snapshots__/KeyboardShortcut-test.tsx.snap
  test/components/views/settings/tabs/user/KeyboardUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/KeyboardUserSettingsTab-test.tsx.snap
  test/i18n-test/languageHandler-test.tsx
Labels: T-Task

#9413 Enable Cypress retries to combat flakiness
  .percy.yml
  cypress.config.ts
  package.json
  yarn.lock
Labels: T-Task, X-Needs-Percy

#9408 Cypress - fix device manager test
  cypress/e2e/settings/device-management.spec.ts
Labels: T-Task

#9362 Voice Broadcast playback UI
  res/css/_components.pcss
  res/css/voice-broadcast/atoms/_PlaybackControlButton.pcss
  res/css/voice-broadcast/molecules/_VoiceBroadcastPlaybackBody.pcss
  src/components/atoms/Icon.tsx
  src/components/views/messages/MessageEvent.tsx
  src/i18n/strings/en_EN.json
  src/voice-broadcast/components/VoiceBroadcastBody.tsx
  src/voice-broadcast/components/atoms/PlaybackControlButton.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody.tsx
  src/voice-broadcast/hooks/useVoiceBroadcastPlayback.ts
  src/voice-broadcast/index.ts
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  src/voice-broadcast/stores/VoiceBroadcastPlaybacksStore.ts
  src/voice-broadcast/utils/shouldDisplayAsVoiceBroadcastRecordingTile.ts
  test/voice-broadcast/components/VoiceBroadcastBody-test.tsx
  test/voice-broadcast/components/atoms/PlaybackControlButton-test.tsx
  test/voice-broadcast/components/atoms/__snapshots__/PlaybackControlButton-test.tsx.snap
  test/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody-test.tsx
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPlaybackBody-test.tsx.snap
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.ts
  test/voice-broadcast/stores/VoiceBroadcastPlaybacksStore-test.ts
  test/voice-broadcast/utils/shouldDisplayAsVoiceBroadcastRecordingTile-test.ts
Labels: T-Task

#9416 Fix check for whether a pickle is stored
  src/Lifecycle.ts
Labels: T-Task

#9415 Update voice broadcast header to new design
  res/css/voice-broadcast/atoms/_PlaybackControlButton.pcss
  res/css/voice-broadcast/atoms/_VoiceBroadcastHeader.pcss
  src/components/atoms/Icon.tsx
  src/voice-broadcast/components/atoms/VoiceBroadcastHeader.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingBody.tsx
  src/voice-broadcast/hooks/useVoiceBroadcastPlayback.ts
  src/voice-broadcast/hooks/useVoiceBroadcastRecording.ts
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  test/voice-broadcast/components/atoms/VoiceBroadcastHeader-test.tsx
  test/voice-broadcast/components/atoms/__snapshots__/VoiceBroadcastHeader-test.tsx.snap
  test/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody-test.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingBody-test.tsx
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPlaybackBody-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastRecordingBody-test.tsx.snap
Labels: T-Task

#9410 Add formatting buttons to the WysiwygComposer
  package.json
  res/css/_components.pcss
  res/css/views/rooms/_MessageComposer.pcss
  res/css/views/rooms/wysiwyg_composer/_FormattingButtons.pcss
  res/img/element-icons/room/composer/bold.svg
  res/img/element-icons/room/composer/italic.svg
  res/img/element-icons/room/composer/strikethrough.svg
  res/img/element-icons/room/composer/underline.svg
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/wysiwyg_composer/Editor.tsx
  src/components/views/rooms/wysiwyg_composer/FormattingButtons.tsx
  src/components/views/rooms/wysiwyg_composer/WysiwygComposer.tsx
  src/components/views/settings/KeyboardShortcut.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/views/rooms/MessageComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/FormattingButtons-test.tsx
  test/components/views/rooms/wysiwyg_composer/WysiwygComposer-test.tsx
  yarn.lock
Labels: T-Enhancement

#9409 Device manager - device tile main click target
  cypress/e2e/settings/device-management.spec.ts
  res/css/components/views/settings/devices/_DeviceTile.pcss
  res/css/components/views/settings/devices/_SelectableDeviceTile.pcss
  src/components/views/settings/DevicesPanelEntry.tsx
  src/components/views/settings/devices/CurrentDeviceSection.tsx
  src/components/views/settings/devices/DeviceTile.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/SelectableDeviceTile.tsx
  test/components/views/settings/devices/CurrentDeviceSection-test.tsx
  test/components/views/settings/devices/DeviceTile-test.tsx
  test/components/views/settings/devices/SelectableDeviceTile-test.tsx
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/SelectableDeviceTile-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Enhancement

#9417 Inhibit clicking on sender avatar in threads list
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#9379 Disconnect other connected devices (of the same user) when joining an Element call
  src/components/views/messages/CallEvent.tsx
  src/components/views/voip/CallView.tsx
  src/hooks/useCall.ts
  src/i18n/strings/en_EN.json
  src/models/Call.ts
  src/toasts/IncomingCallToast.tsx
  test/models/Call-test.ts
Labels: T-Enhancement

#9372 Voice Broadcast playback
  src/events/getReferenceRelationsForEvent.ts
  src/events/index.ts
  src/voice-broadcast/components/VoiceBroadcastBody.tsx
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  src/voice-broadcast/stores/VoiceBroadcastPlaybacksStore.ts
  test/test-utils/audio.ts
  test/voice-broadcast/components/VoiceBroadcastBody-test.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody-test.tsx
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.ts
  test/voice-broadcast/stores/VoiceBroadcastPlaybacksStore-test.ts
Labels: T-Task

#9421 Update overly sensitive snapshot
  test/components/views/beacon/__snapshots__/BeaconMarker-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Task

#9423 Hide screen-sharing button in Element Call on desktop
  src/models/Call.ts
Labels: T-Enhancement

#9424 Hide virtual widgets from the room info panel
  src/components/views/right_panel/RoomSummaryCard.tsx
Labels: T-Defect

#9385 Voice Broadcast recording pip
  res/css/_components.pcss
  res/css/voice-broadcast/molecules/_VoiceBroadcastRecordingPip.pcss
  res/img/element-icons/Stop.svg
  src/SdkConfig.ts
  src/components/atoms/Icon.tsx
  src/components/views/voip/PipView.tsx
  src/i18n/strings/en_EN.json
  src/voice-broadcast/components/atoms/StopButton.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip.tsx
  src/voice-broadcast/index.ts
  test/voice-broadcast/components/atoms/StopButton-test.tsx
  test/voice-broadcast/components/atoms/__snapshots__/StopButton-test.tsx.snap
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip-test.tsx
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastRecordingPip-test.tsx.snap
Labels: T-Task

#9426 Better accommodate long room names in call toasts
  res/css/views/toasts/_IncomingCallToast.pcss
Labels: T-Defect

#9425 Voice broadcast call handling
  src/stores/widgets/StopGapWidget.ts
  src/voice-broadcast/models/VoiceBroadcastRecording.ts
  test/stores/widgets/StopGapWidget-test.ts
  test/voice-broadcast/models/VoiceBroadcastRecording-test.ts
Labels: T-Task

#9427 Pass the current language to Element Call
  src/models/Call.ts
Labels: T-Enhancement

#9429 Pass the homeserver's base URL to Element Call
  src/models/Call.ts
Labels: T-Defect

#9428 Improve the tooltips on the call lobby join button
  src/components/views/voip/CallView.tsx
Labels: T-Defect

#9420 Device manager - silence call ringers when local notifications are silenced
  src/LegacyCallHandler.tsx
  src/i18n/strings/en_EN.json
  src/toasts/IncomingLegacyCallToast.tsx
  test/LegacyCallHandler-test.ts
  test/components/views/settings/DevicesPanel-test.tsx
  test/test-utils/client.ts
  test/toasts/IncomingLegacyCallToast-test.tsx
  test/toasts/__snapshots__/IncomingLegacyCallToast-test.tsx.snap
Labels: T-Enhancement

#9431 Remove deprecated `m.room.aliases` references
  src/SlashCommands.tsx
  src/Unread.ts
  test/Unread-test.ts
Labels: T-Task

#9430 Revert "Pin back Synapse used in Cypress to alleviate test failures"
  cypress/plugins/synapsedocker/index.ts
Labels: T-Task

#9412 Automatically focus the WYSIWYG composer when you enter a room
  src/components/views/rooms/wysiwyg_composer/WysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/useWysiwygActionHandler.ts
  test/components/views/rooms/wysiwyg_composer/WysiwygComposer-test.tsx
Labels: T-Defect

#9432 Voice Broadcast live state / extract `RelationsHelper`
  src/events/RelationsHelper.ts
  src/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody.tsx
  src/voice-broadcast/hooks/useVoiceBroadcastPlayback.ts
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  test/events/RelationsHelper-test.ts
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPlaybackBody-test.tsx.snap
Labels: T-Task

#9434 Start playback for ongoing broadcast with the last chunk
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.ts
Labels: T-Task

#9436 Disable stopping a voice broadcast recording by click on the tile
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingBody.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingBody-test.tsx
Labels: T-Task

#9433 Device manager - spinners while devices are signing out
  res/css/components/views/settings/devices/_FilteredDeviceList.pcss
  res/css/views/elements/_AccessibleButton.pcss
  src/components/views/settings/devices/FilteredDeviceList.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Enhancement

#9437 Improve Voice Broadcast header layout
  res/css/voice-broadcast/atoms/_VoiceBroadcastHeader.pcss
  src/voice-broadcast/components/atoms/VoiceBroadcastHeader.tsx
  test/voice-broadcast/components/atoms/__snapshots__/VoiceBroadcastHeader-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPlaybackBody-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastRecordingBody-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastRecordingPip-test.tsx.snap
Labels: T-Task

#9418 Prevent useContextMenu isOpen from being true if the button ref goes away
  src/components/structures/ContextMenu.tsx
  src/components/views/location/LocationButton.tsx
  src/components/views/rooms/ReadReceiptGroup.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  test/components/views/spaces/SpacePanel-test.tsx
Labels: T-Defect

#9378 Room call banner
  res/css/_components.pcss
  res/css/views/rooms/_RoomCallBanner.pcss
  src/components/views/beacon/RoomCallBanner.tsx
  src/components/views/beacon/RoomLiveShareWarning.tsx
  src/components/views/rooms/RoomHeader.tsx
  test/components/views/beacon/RoomCallBanner-test.tsx
  test/test-utils/call.ts
Labels: T-Task, T-Defect, T-Enhancement

#9439 Implement VoiceBroadcastBody update
  src/voice-broadcast/components/VoiceBroadcastBody.tsx
  test/voice-broadcast/components/VoiceBroadcastBody-test.tsx
Labels: T-Task

#9441 Don't show call banners in video rooms
  src/components/views/rooms/RoomHeader.tsx
Labels: X-Release-Blocker, T-Defect

#9442 Add confirm end voice broadcast dialog
  src/i18n/strings/en_EN.json
  src/voice-broadcast/hooks/useVoiceBroadcastRecording.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip-test.tsx
Labels: T-Task

#9449 Fix usages of useContextMenu which never pass the ref to the element
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
Labels: X-Release-Blocker, T-Task, backport staging

#9438 Listen for and update the notification state when they change
  src/stores/notifications/RoomNotificationState.ts
Labels: T-Defect

#9447 Device manager - put client/browser device metadata in correct section (PSG-901)
  src/components/views/settings/devices/DeviceDetails.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/__snapshots__/DeviceDetails-test.tsx.snap
Labels: T-Defect

#9446 Stabilise Cypress login tests
  cypress/e2e/create-room/create-room.spec.ts
  cypress/e2e/editing/editing.spec.ts
  cypress/e2e/login/consent.spec.ts
  cypress/e2e/login/login.spec.ts
  cypress/e2e/polls/polls.spec.ts
  cypress/e2e/room-directory/room-directory.spec.ts
  cypress/e2e/sliding-sync/sliding-sync.ts
  cypress/e2e/spaces/spaces.spec.ts
  cypress/e2e/threads/threads.spec.ts
  cypress/e2e/timeline/timeline.spec.ts
  cypress/e2e/toasts/analytics-toast.ts
  cypress/support/login.ts
  cypress/support/settings.ts
  src/Lifecycle.ts
Labels: T-Task

#9253 Set relations helper when creating event tile context menu
  cypress/e2e/polls/polls.spec.ts
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#9451 Allow pressing Enter to send messages in new composer
  cypress/e2e/composer/composer.spec.ts
  package.json
  src/components/views/rooms/wysiwyg_composer/WysiwygComposer.tsx
  test/components/views/rooms/wysiwyg_composer/WysiwygComposer-test.tsx
  yarn.lock
Labels: T-Enhancement

#9293 Store refactor: use non-global stores in components
  src/ContentMessages.ts
  src/Notifier.ts
  src/ScalarMessaging.ts
  src/SlashCommands.tsx
  src/audio/PlaybackQueue.ts
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/SpaceHierarchy.tsx
  src/components/structures/ThreadView.tsx
  src/components/views/beacon/RoomCallBanner.tsx
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/right_panel/TimelineCard.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomTile.tsx
  src/components/views/spaces/QuickSettingsButton.tsx
  src/components/views/voip/PipView.tsx
  src/contexts/SDKContext.ts
  src/stores/RoomViewStore.tsx
  src/stores/right-panel/RightPanelStore.ts
  src/stores/room-list/RoomListStore.ts
  src/stores/room-list/SlidingRoomListStore.ts
  src/stores/spaces/SpaceStore.ts
  src/stores/widgets/StopGapWidget.ts
  src/stores/widgets/StopGapWidgetDriver.ts
  src/utils/DialogOpener.ts
  src/utils/leave-behaviour.ts
  src/utils/space.tsx
  test/SlashCommands-test.tsx
  test/TestStores.ts
  test/components/structures/RoomView-test.tsx
  test/components/views/beacon/RoomCallBanner-test.tsx
  test/stores/RoomViewStore-test.ts
  test/stores/widgets/StopGapWidgetDriver-test.ts
Labels: T-Task

#9403 Support for login + E2EE set up with QR
  res/css/_components.pcss
  res/css/views/auth/_LoginWithQR.pcss
  res/img/element-icons/back.svg
  res/img/element-icons/devices.svg
  res/img/element-icons/qrcode.svg
  src/components/views/auth/LoginWithQR.tsx
  src/components/views/dialogs/InteractiveAuthDialog.tsx
  src/components/views/settings/DevicesPanel.tsx
  src/components/views/settings/devices/LoginWithQRSection.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/utils/UserInteractiveAuth.ts
  test/components/views/settings/DevicesPanel-test.tsx
  test/components/views/settings/devices/LoginWithQR-test.tsx
  test/components/views/settings/devices/LoginWithQRSection-test.tsx
  test/components/views/settings/devices/__snapshots__/LoginWithQR-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/LoginWithQRSection-test.tsx.snap
  test/components/views/settings/tabs/user/SecurityUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/test-utils/client.ts
Labels: T-Enhancement

#9453 Display info dialogs if unable to start voice broadcasts
  src/components/structures/RoomView.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/contexts/RoomContext.ts
  src/i18n/strings/en_EN.json
  src/voice-broadcast/index.ts
  src/voice-broadcast/utils/hasRoomLiveVoiceBroadcast.ts
  src/voice-broadcast/utils/startNewVoiceBroadcastRecording.ts
  src/voice-broadcast/utils/startNewVoiceBroadcastRecording.tsx
  test/components/views/rooms/MessageComposer-test.tsx
  test/components/views/rooms/MessageComposerButtons-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/WysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/message-test.ts
  test/voice-broadcast/utils/__snapshots__/startNewVoiceBroadcastRecording-test.ts.snap
  test/voice-broadcast/utils/hasRoomLiveVoiceBroadcast-test.ts
  test/voice-broadcast/utils/startNewVoiceBroadcastRecording-test.ts
  test/voice-broadcast/utils/test-utils.ts
Labels: T-Task

#9454 Stores refactor: convert TypingStore; rename TestStores to TestSdkContext
  src/Lifecycle.ts
  src/components/views/rooms/BasicMessageComposer.tsx
  src/contexts/SDKContext.ts
  src/stores/TypingStore.ts
  test/TestSdkContext.ts
  test/stores/RoomViewStore-test.ts
  test/stores/TypingStore-test.ts
Labels: T-Task

#9457 Prevent starting another voice broadcast
  src/voice-broadcast/utils/startNewVoiceBroadcastRecording.tsx
  test/voice-broadcast/utils/__snapshots__/startNewVoiceBroadcastRecording-test.ts.snap
  test/voice-broadcast/utils/startNewVoiceBroadcastRecording-test.ts
Labels: T-Task

#9461 Backport: Prevent starting another voice broadcast #9457
  src/voice-broadcast/utils/startNewVoiceBroadcastRecording.tsx
  test/voice-broadcast/utils/__snapshots__/startNewVoiceBroadcastRecording-test.ts.snap
  test/voice-broadcast/utils/startNewVoiceBroadcastRecording-test.ts
Labels: T-Task

#9456 Test display of qr code login section
  src/components/views/auth/LoginWithQR.tsx
  test/components/views/settings/devices/__snapshots__/LoginWithQR-test.tsx.snap
  test/components/views/settings/tabs/user/SecurityUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Task

#9455 Stop voice broadcast recording on redaction
  src/voice-broadcast/hooks/useVoiceBroadcastRecording.tsx
  src/voice-broadcast/models/VoiceBroadcastRecording.ts
  src/voice-broadcast/stores/VoiceBroadcastRecordingsStore.ts
  test/voice-broadcast/models/VoiceBroadcastRecording-test.ts
  test/voice-broadcast/stores/VoiceBroadcastRecordingsStore-test.ts
Labels: T-Task

#9460 Align video call icon with banner text
  res/css/views/rooms/_RoomCallBanner.pcss
Labels: T-Defect

#9468 Fix slightly noisy warning when switching spaces
  src/components/views/rooms/RoomListHeader.tsx
Labels: T-Task

#9467 Remove performance metrics from cypress
  .github/workflows/cypress.yaml
  cypress/e2e/create-room/create-room.spec.ts
  cypress/e2e/login/login.spec.ts
  cypress/e2e/register/register.spec.ts
  cypress/plugins/index.ts
  cypress/plugins/performance.ts
  cypress/support/e2e.ts
  cypress/support/performance.ts
Labels: T-Task

#9470 Fix displaying already stopped broadcasts in the timeline
  src/voice-broadcast/components/VoiceBroadcastBody.tsx
  test/voice-broadcast/components/VoiceBroadcastBody-test.tsx
  test/voice-broadcast/utils/test-utils.ts
Labels: T-Task

#9472 Cypress - stabilise polls cypress test
  cypress/e2e/polls/polls.spec.ts
Labels: T-Task

#9471 Set voice broadcast defaults
  src/SdkConfig.ts
  src/voice-broadcast/audio/VoiceBroadcastRecorder.ts
  src/voice-broadcast/index.ts
  src/voice-broadcast/utils/getChunkLength.ts
  src/voice-broadcast/utils/startNewVoiceBroadcastRecording.tsx
  test/voice-broadcast/models/VoiceBroadcastRecording-test.ts
  test/voice-broadcast/utils/getChunkLength-test.ts
  test/voice-broadcast/utils/startNewVoiceBroadcastRecording-test.ts
Labels: T-Task

#9475 Resume voice broadcast on load
  src/components/structures/MatrixChat.tsx
  src/voice-broadcast/index.ts
  src/voice-broadcast/models/VoiceBroadcastRecording.ts
  src/voice-broadcast/utils/VoiceBroadcastResumer.ts
  src/voice-broadcast/utils/findRoomLiveVoiceBroadcastFromUserAndDevice.ts
  src/voice-broadcast/utils/resumeVoiceBroadcastInRoom.ts
  test/voice-broadcast/components/VoiceBroadcastBody-test.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingBody-test.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip-test.tsx
  test/voice-broadcast/stores/VoiceBroadcastRecordingsStore-test.ts
  test/voice-broadcast/utils/VoiceBroadcastResumer-test.ts
  test/voice-broadcast/utils/findRoomLiveVoiceBroadcastFromUserAndDevice-test.ts
  test/voice-broadcast/utils/hasRoomLiveVoiceBroadcast-test.ts
  test/voice-broadcast/utils/resumeVoiceBroadcastInRoom-test.ts
  test/voice-broadcast/utils/startNewVoiceBroadcastRecording-test.ts
  test/voice-broadcast/utils/test-utils.ts
Labels: T-Task

#9474 Improve typing
  .node-version
  src/components/structures/LoggedInView.tsx
  src/components/structures/MatrixChat.tsx
  src/utils/ErrorUtils.tsx
Labels: T-Task

#9479 Only show mini avatar uploader in room intro when no avatar yet exists
  src/components/views/rooms/NewRoomIntro.tsx
Labels: T-Defect

#9478 Fix voice broadcast recording limit
  src/audio/VoiceRecording.ts
  src/voice-broadcast/audio/VoiceBroadcastRecorder.ts
  test/audio/VoiceRecording-test.ts
  test/voice-broadcast/audio/VoiceBroadcastRecorder-test.ts
Labels: T-Task

#9400 Add thread notification with server assistance (MSC3773)
  cypress/e2e/sliding-sync/sliding-sync.ts
  res/css/views/rooms/_EventTile.pcss
  src/RoomNotifs.ts
  src/Unread.ts
  src/components/structures/RoomStatusBar.tsx
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/NotificationBadge.tsx
  src/components/views/rooms/NotificationBadge/StatelessNotificationBadge.tsx
  src/components/views/rooms/NotificationBadge/UnreadNotificationBadge.tsx
  src/hooks/useUnreadNotifications.ts
  src/stores/notifications/RoomNotificationState.ts
  src/stores/notifications/RoomNotificationStateStore.ts
  test/RoomNotifs-test.ts
  test/components/structures/RoomStatusBar-test.tsx
  test/components/views/right_panel/RoomHeaderButtons-test.tsx
  test/components/views/rooms/EventTile-test.tsx
  test/components/views/rooms/NotificationBadge/NotificationBadge-test.tsx
  test/components/views/rooms/NotificationBadge/UnreadNotificationBadge-test.tsx
  test/stores/notifications/RoomNotificationState-test.ts
  test/stores/notifications/RoomNotificationStateStore-test.ts
  test/test-utils/threads.ts
Labels: T-Enhancement

#9480 Ensure spaces in the spotlight dialog have rounded square avatars
  src/components/views/avatars/RoomAvatar.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/stores/ThreepidInviteStore.ts
  test/Avatar-test.ts
  test/components/views/dialogs/InviteDialog-test.tsx
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/rooms/RoomPreviewBar-test.tsx
  test/stores/room-list/filters/VisibilityProvider-test.ts
  test/test-utils/test-utils.ts
Labels: T-Defect

#9486 Fix joining calls without audio or video inputs
  src/components/views/voip/CallView.tsx
Labels: T-Defect

#9489 When start listening to a broadcast, pause the others
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  src/voice-broadcast/stores/VoiceBroadcastPlaybacksStore.ts
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.ts
  test/voice-broadcast/stores/VoiceBroadcastPlaybacksStore-test.ts
Labels: T-Task

#9490 Send Content-Type: application/json header for integration manager /register API
  src/ScalarAuthClient.ts
Labels: T-Defect, backport staging

#9492 Auto-approve rageshake event capabilities for virtual Element Call widgets
  src/stores/widgets/StopGapWidgetDriver.ts
  test/stores/widgets/StopGapWidgetDriver-test.ts
Labels: T-Enhancement

#9485 Fix embedded Element Call screen sharing
  src/models/Call.ts
  src/stores/widgets/ElementWidgetActions.ts
  test/models/Call-test.ts
Labels: T-Defect

#9487 Device manager - confirm sign out of other sessions (PSG-921)
  cypress/e2e/settings/device-management.spec.ts
  src/components/views/elements/DialogButtons.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/AccessSecretStorageDialog-test.tsx
  test/components/views/dialogs/ExportDialog-test.tsx
  test/components/views/dialogs/__snapshots__/ChangelogDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ExportDialog-test.tsx.snap
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Enhancement

#9495 Show thread notification if thread timeline is closed
  src/Notifier.ts
  src/components/structures/ThreadView.tsx
  src/dispatcher/actions.ts
  src/dispatcher/payloads/ThreadPayload.ts
  src/stores/RoomViewStore.tsx
  test/Notifier-test.ts
  test/components/structures/ThreadView-test.tsx
Labels: T-Enhancement

#9498 Add type assertions where we know an event is a room event (has room_id)
  src/stores/widgets/StopGapWidget.ts
  src/stores/widgets/StopGapWidgetDriver.ts
  test/stores/widgets/__snapshots__/StopGapWidgetDriver-test.ts.snap
  test/utils/location/isSelfLocation-test.ts
Labels: T-Task

#9499 Fully move auth types to js-sdk
  src/Login.ts
  src/components/structures/auth/Login.tsx
  src/components/structures/auth/Registration.tsx
  src/components/structures/auth/SoftLogout.tsx
  src/components/views/elements/SSOButtons.tsx
Labels: T-Task

#9500 Use flex-start instead of start in several places
  res/css/views/dialogs/_SpotlightDialog.pcss
  res/css/views/elements/_UseCaseSelection.pcss
  res/css/views/rooms/wysiwyg_composer/components/_FormattingButtons.pcss
Labels: T-Task

#9497 Device manager - add learn more popups to filtered sessions section
  res/css/_components.pcss
  res/css/components/views/elements/_LearnMore.pcss
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/elements/LearnMore.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/i18n/strings/en_EN.json
  test/components/views/elements/LearnMore-test.tsx
  test/components/views/elements/__snapshots__/LearnMore-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/FilteredDeviceList-test.tsx.snap
Labels: T-Enhancement

#9494 Reinstate timeline/redaction callbacks when updating notification state
  src/stores/notifications/RoomNotificationState.ts
Labels: T-Defect

#9504 Unify voice broadcast css
  res/css/_components.pcss
  res/css/voice-broadcast/molecules/_VoiceBroadcastBody.pcss
  res/css/voice-broadcast/molecules/_VoiceBroadcastPlaybackBody.pcss
  res/css/voice-broadcast/molecules/_VoiceBroadcastRecordingBody.pcss
  src/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingBody.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip.tsx
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPlaybackBody-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastRecordingBody-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastRecordingPip-test.tsx.snap
Labels: T-Task

#9506 Add extra cypress worker to improve test runtime
  .github/workflows/cypress.yaml
Labels: T-Task

#9505 Add cypress test for the composer emoji picker
  cypress/e2e/composer/composer.spec.ts
Labels: T-Task

#9507 Fix getReadReceiptsForEvent for unknown threads
  src/components/structures/MessagePanel.tsx
Labels: T-Task

#9511 Improve fetch mock setup
  test/setup/setupLanguage.ts
  test/setup/setupManualMocks.ts
Labels: T-Task

#9508 Reset custom power selector when blurred on empty
  src/Roles.ts
  src/components/views/elements/PowerSelector.tsx
  test/components/views/elements/PowerSelector-test.tsx
Labels: T-Defect

#9509 Stop voice broadcast from save device on resume
  src/voice-broadcast/index.ts
  src/voice-broadcast/utils/VoiceBroadcastResumer.ts
  src/voice-broadcast/utils/resumeVoiceBroadcastInRoom.ts
  test/test-utils/test-utils.ts
  test/voice-broadcast/utils/VoiceBroadcastResumer-test.ts
  test/voice-broadcast/utils/resumeVoiceBroadcastInRoom-test.ts
Labels: T-Task

#9503 Feat/add plain text mode
  res/css/views/rooms/_MessageComposer.pcss
  res/img/element-icons/room/composer/plain_text.svg
  res/img/element-icons/room/composer/rich_text.svg
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
  src/components/views/rooms/wysiwyg_composer/SendWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/components/PlainTextComposer.tsx
  src/components/views/rooms/wysiwyg_composer/components/WysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useComposerFunctions.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useInputEventProcessor.ts
  src/components/views/rooms/wysiwyg_composer/hooks/usePlainTextInitialization.ts
  src/components/views/rooms/wysiwyg_composer/hooks/usePlainTextListeners.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useSetCursorPosition.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useWysiwygSendActionHandler.ts
  src/components/views/rooms/wysiwyg_composer/hooks/utils.ts
  src/components/views/rooms/wysiwyg_composer/types.ts
  src/components/views/rooms/wysiwyg_composer/utils/createMessageContent.ts
  src/components/views/rooms/wysiwyg_composer/utils/message.ts
  src/i18n/strings/en_EN.json
  src/utils/room/htmlToPlaintext.ts
  test/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/SendWysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/PlainTextComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/utils/createMessageContent-test.ts
  test/components/views/rooms/wysiwyg_composer/utils/message-test.ts
Labels: T-Enhancement

#9501 Device manager - add extra details to device security and renaming (PSG-863)
  src/components/views/elements/LearnMore.tsx
  src/components/views/settings/devices/DeviceDetailHeading.tsx
  src/components/views/settings/devices/DeviceSecurityLearnMore.tsx
  src/components/views/settings/devices/DeviceVerificationStatusCard.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/SecurityRecommendations.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceDetailHeading-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceDetails-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/SecurityRecommendations-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Enhancement

#9510 Make thread replies trigger a room list re-ordering
  src/stores/room-list/algorithms/tag-sorting/RecentAlgorithm.ts
  test/stores/room-list/algorithms/RecentAlgorithm-test.ts
Labels: T-Enhancement

#9513 Implement voice broadcast `last_chunk_sequence`
  src/voice-broadcast/index.ts
  src/voice-broadcast/models/VoiceBroadcastRecording.ts
  test/voice-broadcast/models/VoiceBroadcastRecording-test.ts
Labels: T-Task

#9515 Fix room list sorted by recent on app startup
  src/stores/room-list/algorithms/tag-sorting/RecentAlgorithm.ts
Labels: T-Defect

#9356 Loading threads with server-side assistance
  src/components/structures/ThreadView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/ThreadSummary.tsx
  src/stores/widgets/StopGapWidgetDriver.ts
  src/utils/EventUtils.ts
  test/components/views/rooms/EventTile-test.tsx
  test/test-utils/test-utils.ts
  test/test-utils/threads.ts
  test/utils/EventUtils-test.ts
Labels: T-Enhancement

#9522 Fix NotificationBadge unsent color
  src/components/views/rooms/NotificationBadge/StatelessNotificationBadge.tsx
  test/components/views/rooms/NotificationBadge/StatelessNotificationBadge-test.tsx
Labels: T-Defect

#9517 Display voice broadcast total length
  res/css/voice-broadcast/molecules/_VoiceBroadcastBody.pcss
  src/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody.tsx
  src/voice-broadcast/hooks/useVoiceBroadcastPlayback.ts
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  src/voice-broadcast/utils/VoiceBroadcastChunkEvents.ts
  test/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody-test.tsx
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPlaybackBody-test.tsx.snap
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.ts
  test/voice-broadcast/utils/VoiceBroadcastChunkEvents-test.ts
  test/voice-broadcast/utils/test-utils.ts
Labels: T-Task

#9496 Allow the docker tag for the sliding sync proxy to be specified in env
  cypress.config.ts
  cypress/plugins/sliding-sync/index.ts
Labels: T-Task
