Repository matrix-org/matrix-react-sdk, pull requests merged in 2022-02, with the labels that each got.

#7652 Irc full name overlap
  res/css/views/rooms/_IRCLayout.scss
Labels: T-Defect

#7661 Make polls fill column width in bubbles layout
  res/css/views/rooms/_EventBubbleTile.scss
Labels: T-Defect

#7685 Use a more correct test for emoji
  src/HtmlUtils.tsx
  src/editor/parts.ts
Labels: T-Defect

#7687 Ensure UserInfo can be rendered without a room
  src/components/views/right_panel/UserInfo.tsx
Labels: T-Defect

#7691 Prevent MemberAvatar soft-crashing when rendered with null member prop
  src/components/views/avatars/MemberAvatar.tsx
Labels: T-Defect

#7690 Fix publishing address wrongly demanding the alias be available
  src/components/views/elements/RoomAliasField.tsx
  src/components/views/room_settings/AliasSettings.tsx
  src/components/views/settings/JoinRuleSettings.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7692 Fix the sticker picker
  src/components/views/elements/AppTile.tsx
Labels: T-Defect

#7694 Ensure UserInfo can be rendered without a room (#7687)
  src/components/views/right_panel/UserInfo.tsx
Labels: T-Defect

#7693 Fix publishing address wrongly demanding the alias be available (#7690)
  src/components/views/elements/RoomAliasField.tsx
  src/components/views/room_settings/AliasSettings.tsx
  src/components/views/settings/JoinRuleSettings.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7695 Fix the sticker picker (#7692)
  src/components/views/elements/AppTile.tsx
Labels: T-Defect

#7684 Fix vertical spacing in `compact` `<ContextMenu>`
  res/css/views/context_menus/_IconizedContextMenu.scss
  res/css/views/messages/_JumpToDatePicker.scss
  src/components/views/context_menus/IconizedContextMenu.tsx
  src/components/views/messages/DateSeparator.tsx
Labels: T-Defect

#7673 Add a warning to the console to discourage attacks and encourage contributing
  src/components/structures/MatrixChat.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7697 Fix incorrect sizing of DecoratedRoomAvatar in RoomHeader
  res/css/views/avatars/_DecoratedRoomAvatar.scss
Labels: T-Defect

#7678 Simplify Composer buttons
  res/css/structures/_ContextualMenu.scss
  res/css/views/rooms/_MessageComposer.scss
  src/components/views/location/LocationButton.tsx
  src/components/views/rooms/CollapsibleButton.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/MessageComposerButtons-test.tsx
Labels: T-Enhancement

#7698 Make Spotlight Dialog roving reset more stable
  src/components/views/dialogs/SpotlightDialog.tsx
Labels: T-Defect

#7704 Fix leaks in Login unit tests
  test/components/structures/auth/Login-test.tsx
Labels: T-Task

#7705 Fit location into the width of the container
  res/css/views/messages/_MLocationBody.scss
Labels: T-Defect

#7703 Enable location sharing
  src/TextForEvent.tsx
  src/components/views/messages/MessageEvent.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Enhancement

#7701 Reuse CopyableText component in all places it can be
  res/css/views/dialogs/_InviteDialog.scss
  res/css/views/dialogs/_ShareDialog.scss
  res/css/views/elements/_CopyableText.scss
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/dialogs/ShareDialog.tsx
Labels: T-Defect

#7708 Fix relative link handling in Element Desktop
  src/linkify-matrix.ts
  src/utils/permalinks/Permalinks.ts
Labels: T-Defect

#7709 Open native room when clicking notification from a virtual room
  src/Notifier.ts
Labels: T-Defect

#7711 Fix creating polls outside of threads
  src/components/views/rooms/MessageComposerButtons.tsx
Labels: T-Defect

#7712 Update PollCreateDialog-test to snapshot the html and not react tree
  test/components/views/elements/PollCreateDialog-test.tsx
  test/components/views/elements/__snapshots__/PollCreateDialog-test.tsx.snap
Labels: T-Defect

#7715 Fix `JumpToLatestMessage`
  src/accessibility/KeyboardShortcuts.ts
Labels: T-Defect

#7719 Hide composer buttons if we can't send events
  src/components/views/rooms/MessageComposer.tsx
Labels: T-Defect

#7717 Bypass rageshake when warning about devtools
  src/components/structures/MatrixChat.tsx
  src/rageshake/rageshake.ts
Labels: T-Defect

#7721 Add logging to diagnose no-video bug
  src/CallHandler.tsx
  src/components/views/voip/VideoFeed.tsx
Labels: T-Task

#7677 Switch back to upstream Linkify
  package.json
  src/linkify-matrix.ts
  yarn.lock
Labels: T-Task

#7720 Remove IA 1.1 feedback toast
  res/img/ia-design-changes.png
  src/components/structures/MatrixChat.tsx
  src/i18n/strings/en_EN.json
  test/end-to-end-tests/src/scenarios/toast.ts
Labels: X-Release-Blocker, T-Task

#7729 Null guard space hierarchy
  src/components/structures/SpaceHierarchy.tsx
Labels: T-Defect

#7696 Add unread badges and avatar decorations to spotlight search
  res/css/views/dialogs/_SpotlightDialog.scss
  src/components/views/dialogs/SpotlightDialog.tsx
Labels: T-Enhancement

#7724 Properly handle persistent widgets when room is left
  src/components/views/elements/AppTile.tsx
  src/components/views/elements/PersistentApp.tsx
  src/components/views/voip/PipView.tsx
  src/stores/widgets/StopGapWidget.ts
Labels: T-Defect

#7337 Auto select "Other homeserver" when user press "Edit" in homeserver field
  src/components/views/dialogs/ServerPickerDialog.tsx
Labels: T-Enhancement

#6271 Remove weird padding on stickers
  res/css/views/messages/_MStickerBody.scss
Labels: T-Defect

#7738 Capitalize "Privacy" in UserMenu
  src/components/structures/UserMenu.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7730 Fix instances of decorated room avatar wrongly having their own tabIndex
  src/components/views/rooms/RecentlyViewedButton.tsx
  src/components/views/rooms/RoomBreadcrumbs.tsx
Labels: T-Defect

#7735 Tune aria-live regions around clocks/timers
  src/components/views/audio_messages/Clock.tsx
  src/components/views/audio_messages/LiveRecordingClock.tsx
  src/components/views/audio_messages/PlaybackClock.tsx
  src/components/views/messages/CallEvent.tsx
Labels: T-Defect

#7740 unit test basic paths in UserInfo
  src/components/views/right_panel/BaseCard.tsx
  src/components/views/right_panel/EncryptionInfo.tsx
  src/components/views/right_panel/EncryptionPanel.tsx
  src/components/views/right_panel/UserInfo.tsx
  test/components/views/right_panel/UserInfo-test.tsx
Labels: T-Task

#7742 Ensure location bodies have a width in bubbles
  res/css/views/messages/_MLocationBody.scss
Labels: X-Release-Blocker, T-Defect

#7743 Tweak timeline card layout
  res/css/views/right_panel/_TimelineCard.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_WhoIsTypingTile.scss
Labels: T-Defect

#7736 Improve responsiveness of the layout switcher
  res/css/views/settings/_LayoutSwitcher.scss
Labels: T-Defect

#7718 Move new search experience to a Beta
  res/css/structures/_RoomSearch.scss
  res/css/views/beta/_BetaCard.scss
  res/css/views/dialogs/_SpotlightDialog.scss
  res/css/views/dialogs/_UserSettingsDialog.scss
  res/img/betas/new_search_experience.gif
  res/img/element-icons/settings/flask.svg
  res/img/element-icons/settings/lab-flags.svg
  src/Rooms.ts
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomSearch.tsx
  src/components/views/beta/BetaCard.tsx
  src/components/views/dialogs/GenericFeatureFeedbackDialog.tsx
  src/components/views/dialogs/SpotlightDialog.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/spaces/SpaceStore.ts
Labels: X-Release-Blocker, T-Enhancement

#7744 Null-guard ELS from null summaryMembers
  src/components/views/elements/EventListSummary.tsx
Labels: X-Release-Blocker, T-Defect

#7755 [Release] Fix space member list not opening
  src/components/structures/SpaceRoomView.tsx
Labels: X-Release-Blocker, T-Defect

#7749 Add unread notification dot to timeline card button
  res/css/structures/_RightPanel.scss
  src/components/views/right_panel/RoomHeaderButtons.tsx
Labels: T-Defect

#7752 Inhibit Room List keyboard pass-thru when the search beta is enabled
  src/components/structures/LeftPanel.tsx
  src/components/structures/RoomSearch.tsx
Labels: X-Release-Blocker, T-Defect

#7754 [Release] Inhibit Room List keyboard pass-thru when the search beta is enabled
  src/components/structures/LeftPanel.tsx
  src/components/structures/RoomSearch.tsx
Labels: X-Release-Blocker, T-Defect

#7761 Improve new search dialog context text for exactly 2 parent spaces
  src/Rooms.ts
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7750 Yarn upgrade
  yarn.lock
Labels: T-Task

#7751 Fix add existing space not showing any spaces
  src/components/views/dialogs/AddExistingToSpaceDialog.tsx
Labels: X-Release-Blocker, T-Defect

#7759 Fix view source and devtools showing hljs warnings
  src/components/structures/ViewSource.tsx
  src/components/views/dialogs/DevtoolsDialog.tsx
  src/components/views/elements/SyntaxHighlight.tsx
  src/rageshake/rageshake.ts
  src/utils/JSON.ts
Labels: T-Task

#7760 Fix widget and mjolnir state events showing with mxid not name
  src/TextForEvent.tsx
Labels: T-Defect

#7716 Add way to track posthog user properties and send numSpaces
  package.json
  src/PosthogAnalytics.ts
  src/actions/MatrixActionCreators.ts
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomView.tsx
  src/stores/LifecycleStore.ts
  src/stores/spaces/SpaceStore.ts
  yarn.lock
Labels: T-Task

#7756 [Release] Fix add existing space not showing any spaces
  src/components/views/dialogs/AddExistingToSpaceDialog.tsx
Labels: X-Release-Blocker, T-Defect

#7757 Basic script to create react component with test and style files
  package.json
  scripts/make-react-component.js
Labels: T-Task

#7764 Fix theme selector dropdown overflow
  res/css/structures/_QuickSettingsButton.scss
Labels: T-Defect

#7734 Unify widget header actions with those in right panel
  res/css/views/right_panel/_RoomSummaryCard.scss
  res/css/views/rooms/_AppsDrawer.scss
  src/components/views/elements/AppTile.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/Stickerpicker.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7739 Consolidate RedactionGrouper and HiddenEventGrouper into MELS
  res/css/_components.scss
  res/css/views/elements/_GenericEventListSummary.scss
  res/css/views/right_panel/_ThreadPanel.scss
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_IRCLayout.scss
  src/components/structures/MessagePanel.tsx
  src/components/views/elements/EventListSummary.tsx
  src/components/views/elements/GenericEventListSummary.tsx
  src/components/views/elements/MemberEventListSummary.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/MessagePanel-test.js
  test/components/views/elements/EventListSummary-test.js
Labels: T-Enhancement

#7765 Fix all settings button opening sidebar settings tab
  src/components/views/spaces/QuickSettingsButton.tsx
Labels: T-Defect

#7707 Wire up bunch of interaction events into Posthog
  src/PosthogTrackers.ts
  src/SlashCommands.tsx
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/right_panel/BaseCard.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/RoomTile.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/components/views/settings/tabs/room/GeneralRoomSettingsTab.tsx
Labels: T-Task

#7767 Event List Summary guard against missing event senders
  src/components/views/elements/EventListSummary.tsx
Labels: T-Defect

#7768 Fix state events being wrongly hidden when redacted
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#7758 Fix translation for keyboard shortcut displaynames
  src/components/views/settings/tabs/user/KeyboardUserSettingsTab.tsx
  test/components/views/settings/tabs/user/__snapshots__/KeyboardUserSettingsTab-test.tsx.snap
Labels: T-Defect

#7773 Fix space member list opening with back button
  src/stores/right-panel/RightPanelStore.ts
Labels: T-Defect

#7772 Send how many favorited rooms a user has to Posthog
  package.json
  src/PosthogTrackers.ts
  src/components/structures/HomePage.tsx
  src/components/structures/RoomDirectory.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/views/context_menus/SpaceContextMenu.tsx
  src/components/views/dialogs/AddExistingToSpaceDialog.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomListHeader.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/stores/notifications/RoomNotificationStateStore.ts
  src/utils/space.tsx
  yarn.lock
Labels: T-Task

#7775 Properly recurse subspaces for leave space dialog options
  src/components/views/dialogs/LeaveSpaceDialog.tsx
Labels: T-Defect

#7778 Fix bad pluralisation on event list summary hidden message handling
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7763 Wire up more posthog properties and interactions
  src/PosthogTrackers.ts
  src/components/structures/UserMenu.tsx
  src/components/views/settings/ThemeChoicePanel.tsx
  src/components/views/settings/tabs/user/SidebarUserSettingsTab.tsx
  src/components/views/spaces/QuickSettingsButton.tsx
  src/stores/spaces/SpaceStore.ts
Labels: T-Task

#7777 Switch to web-specific screens and $pageview event
  package.json
  src/PosthogAnalytics.ts
  src/PosthogTrackers.ts
  src/components/views/dialogs/UserSettingsDialog.tsx
  yarn.lock
Labels: T-Task

#7780 Fix desktop notifications for invites showing user IDs instead of displaynames
  src/TextForEvent.tsx
Labels: T-Defect

#7782 Switch to IPC channel for `getDesktopCapturerSources`
  src/@types/global.d.ts
  src/BasePlatform.ts
  src/components/views/elements/DesktopCapturerSourcePicker.tsx
  src/components/views/voip/CallView.tsx
Labels: T-Task

#7786 Fix electron type conflict
  src/@types/global.d.ts
Labels: T-Task

#7785 [Release] Fix cutout misalignment on some decorated room avatars
  res/css/views/dialogs/_SpotlightDialog.scss
  res/css/views/rooms/_RecentlyViewedButton.scss
Labels: X-Release-Blocker, T-Defect

#7784 Fix cutout misalignment on some decorated room avatars
  res/css/views/dialogs/_SpotlightDialog.scss
  res/css/views/rooms/_RecentlyViewedButton.scss
Labels: T-Defect

#7788 Fix electron typing again again
  src/@types/global.d.ts
Labels: T-Task

#7774 Use the shared secret registration API directly
  test/end-to-end-tests/package.json
  test/end-to-end-tests/run.sh
  test/end-to-end-tests/src/rest/creator.ts
  test/end-to-end-tests/start.ts
  test/end-to-end-tests/synapse/getcfg.sh
  test/end-to-end-tests/yarn.lock
Labels: T-Task

#7800 Add `jest-mock` to dependencies
  package.json
Labels: T-Task

#7793 Don't scroll to bottom when executing non-message slash commands
  src/components/views/rooms/SendMessageComposer.tsx
Labels: T-Defect

#7794 Improve styling of edge case devtools state keys
  res/css/views/dialogs/_DevtoolsDialog.scss
  src/components/views/dialogs/DevtoolsDialog.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7798 Hide `Clear room list filter field` shortcut if new search enabled
  src/accessibility/KeyboardShortcuts.ts
Labels: T-Task

#7799 Consolidate, simplify and improve copied tooltips
  res/css/views/dialogs/security/_CreateSecretStorageDialog.scss
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/views/context_menus/GenericTextContextMenu.tsx
  src/components/views/elements/AccessibleTooltipButton.tsx
  src/components/views/elements/CopyableText.tsx
  src/components/views/messages/TextualBody.tsx
Labels: T-Enhancement

#7797 Fix edge cases around event list summaries with hidden events and redactions
  src/components/structures/MessagePanel.tsx
  src/components/views/elements/EventListSummary.tsx
  src/utils/EventUtils.ts
Labels: T-Defect

#7796 Use the resize observer polyfill consistently
  src/components/views/elements/PersistedElement.tsx
  src/components/views/messages/CallEvent.tsx
  src/stores/UIStore.ts
Labels: T-Enhancement

#7789 Display '(edited)' next to edited polls
  res/css/views/messages/_MPollBody.scss
  src/components/views/messages/MPollBody.tsx
  src/i18n/strings/en_EN.json
  test/components/views/messages/MPollBody-test.tsx
Labels: T-Enhancement

#7733 Add an end-to-end test for stickers
  src/components/views/auth/PasswordLogin.tsx
  test/end-to-end-tests/src/rest/session.ts
  test/end-to-end-tests/src/scenario.ts
  test/end-to-end-tests/src/scenarios/sticker.ts
  test/end-to-end-tests/src/session.ts
  test/end-to-end-tests/src/usecases/login.ts
  test/end-to-end-tests/src/usecases/select-room.ts
  test/end-to-end-tests/src/usecases/send-sticker.ts
Labels: T-Task

#7805 Triage PRs that need design or product
  .github/workflows/triage-move-review-requests.yml
Labels: T-Task

#7804 Abstract spotlight to allow non-room results too
  res/css/views/dialogs/_SpotlightDialog.scss
  src/components/views/dialogs/SpotlightDialog.tsx
Labels: T-Enhancement

#7801 Fix add existing space not showing any spaces
  src/components/structures/SpaceRoomView.tsx
Labels: T-Defect

#7813 Fix delayed badge update for mentions in encrypted rooms
  src/stores/notifications/RoomNotificationState.ts
Labels: T-Defect

#7802 Support refresh tokens
  package.json
  src/Lifecycle.ts
  src/Login.ts
  src/MatrixClientPeg.ts
  src/TokenLifecycle.ts
  src/components/structures/auth/Registration.tsx
  src/components/structures/auth/SoftLogout.tsx
  src/utils/StorageManager.ts
  yarn.lock
Labels: T-Enhancement

#7810 Fix room create tile not showing up with hidden events shown
  src/RoomNotifs.ts
  src/VoipUserMapper.ts
  src/components/structures/MessagePanel.tsx
  src/components/structures/RoomView.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/stores/room-list/RoomListStore.ts
Labels: T-Defect

#7812 set mask-size for icons
  res/css/views/context_menus/_IconizedContextMenu.scss
Labels: T-Defect

#7811 Fix right panel data flow
  src/MatrixClientPeg.ts
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/views/right_panel/EncryptionPanel.tsx
  src/components/views/right_panel/HeaderButtons.tsx
  src/components/views/right_panel/WidgetCard.tsx
  src/stores/ReadyWatchingStore.ts
  src/stores/right-panel/RightPanelStore.ts
  test/TextForEvent-test.ts
  test/components/structures/RightPanel-test.tsx
  test/minimal-sdk.js
  test/stores/RoomViewStore-test.js
  test/test-utils.js
Labels: T-Defect

#7818 Don't change `KEYBOARD_SHORTCUTS` and do some refactoring
  src/accessibility/KeyboardShortcuts.ts
  test/accessibility/KeyboardShortcuts-test.ts
Labels: T-Task

#7821 Revert "Support refresh tokens"
  package.json
  src/Lifecycle.ts
  src/Login.ts
  src/MatrixClientPeg.ts
  src/TokenLifecycle.ts
  src/components/structures/auth/Registration.tsx
  src/components/structures/auth/SoftLogout.tsx
  src/utils/StorageManager.ts
  yarn.lock
Labels: T-Task

#7814 Fix left panel widgets causing app crashes (again)
  src/components/views/elements/AppTile.tsx
  src/stores/widgets/WidgetLayoutStore.ts
Labels: X-Release-Blocker, T-Defect

#7806 Allow editing polls
  src/components/views/elements/PollCreateDialog.tsx
  src/components/views/messages/MPollBody.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/i18n/strings/en_EN.json
  src/utils/EventUtils.ts
  test/components/views/elements/PollCreateDialog-test.tsx
  test/components/views/elements/__snapshots__/PollCreateDialog-test.tsx.snap
  test/components/views/messages/MPollBody-test.tsx
Labels: T-Enhancement

#7820 Add test for RoomNotificationState
  test/stores/notifications/RoomNotificationState-test.ts
Labels: T-Task

#7822 Fix icon size bug in space people context menu
  res/css/views/context_menus/_IconizedContextMenu.scss
  res/css/views/rooms/_RoomList.scss
Labels: T-Task

#7725 set icon-button-color to be configurable
  res/themes/light-custom/css/_custom.scss
Labels: T-Enhancement

#7825 Fix import in test
  test/stores/notifications/RoomNotificationState-test.ts
Labels: T-Task

#7824 Fix layout inconsistencies with the room search minimized button
  res/css/structures/_RoomSearch.scss
  src/components/structures/RoomSearch.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7829 Fixes React.js console errors
  res/css/views/elements/_GenericEventListSummary.scss
  src/components/views/elements/GenericEventListSummary.tsx
  src/components/views/rooms/EventTile.tsx
Labels: T-Task

#7833 Tear down AppTile using lifecycle tracking
  src/components/views/elements/AppTile.tsx
  src/components/views/elements/Tooltip.tsx
  src/components/views/voip/PipView.tsx
  src/stores/right-panel/RightPanelStore.ts
  src/stores/widgets/WidgetLayoutStore.ts
  test/components/structures/RightPanel-test.tsx
  test/components/views/elements/AppTile-test.tsx
  test/test-utils.js
Labels: T-Defect

#7723 Don't aggregate rooms and users in SpaceStore
  src/stores/spaces/SpaceStore.ts
  src/stores/spaces/flattenSpaceHierarchy.ts
  test/stores/SpaceStore-test.ts
  test/stores/room-list/filters/SpaceFilterCondition-test.ts
Labels: T-Task

#7783 Add `#/dm` command to be used as a link in custom `home.html`
  src/components/structures/MatrixChat.tsx
Labels: T-Enhancement

#7844 Remove ResizeObserver Polyfill
  package.json
  src/components/views/elements/PersistedElement.tsx
  src/components/views/messages/CallEvent.tsx
  src/stores/UIStore.ts
  test/setupTests.js
  yarn.lock
Labels: T-Task

#7840 Keep unsent voice messages in memory until they are deleted or sent
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/VoiceRecordComposerTile.tsx
  src/stores/VoiceRecordingStore.ts
Labels: Sponsored, T-Enhancement

#7836 Move `editEvent()` to `EventUtils`
  src/components/views/messages/MPollBody.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
  src/utils/EventUtils.ts
Labels: T-Task

#7846 Fix `editEvent()` call
  src/components/views/messages/MessageActionBar.tsx
Labels: T-Task

#7847 Focus trap in poll creation dialog
  src/components/views/elements/PollCreateDialog.tsx
  test/components/views/elements/PollCreateDialog-test.tsx
  test/components/views/elements/__snapshots__/PollCreateDialog-test.tsx.snap
Labels: T-Enhancement

#7852 Remove `autoplayGifsAndVideos` workaround
  src/settings/handlers/AccountSettingsHandler.ts
Labels: T-Task

#7853 Remove `layout` workaround
  src/settings/handlers/DeviceSettingsHandler.ts
Labels: T-Task

#7842 Support "closed" polls whose votes are not visible until they are ended
  res/css/views/dialogs/_PollCreateDialog.scss
  src/components/views/elements/PollCreateDialog.tsx
  src/components/views/messages/MPollBody.tsx
  src/i18n/strings/en_EN.json
  test/components/views/elements/PollCreateDialog-test.tsx
  test/components/views/elements/__snapshots__/PollCreateDialog-test.tsx.snap
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/messages/__snapshots__/MPollBody-test.tsx.snap
Labels: T-Enhancement

#7848 Fix virtual / native room mapping on call transfers
  src/CallHandler.tsx
  test/CallHandler-test.ts
Labels: T-Defect

#7854 Inhibit tooltip on timeline pill avatars, the whole pill has its own
  res/css/views/elements/_RichText.scss
Labels: T-Defect

#7856 Fix accessibility around the room list treeview and new search beta
  res/css/views/dialogs/_SpotlightDialog.scss
  src/accessibility/KeyboardShortcuts.ts
  src/components/structures/RoomSearch.tsx
  src/components/views/dialogs/BaseDialog.tsx
  src/components/views/dialogs/SpotlightDialog.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7857 Clean up some unit test logs
  test/Terms-test.js
  test/components/structures/MessagePanel-test.js
  test/components/structures/RightPanel-test.tsx
  test/components/structures/auth/Login-test.tsx
  test/components/structures/auth/Registration-test.js
  test/components/views/elements/AppTile-test.tsx
  test/components/views/messages/TextualBody-test.js
  test/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
  test/editor/model-test.js
  test/editor/operations-test.js
  test/setupTests.js
  test/utils/arrays-test.ts
  test/utils/test-utils.ts
Labels: T-Task

#7858 Bump react-focus-lock
  package.json
  test/components/views/dialogs/AccessSecretStorageDialog-test.js
  test/components/views/dialogs/__snapshots__/ExportDialog-test.tsx.snap
  test/components/views/elements/PollCreateDialog-test.tsx
  test/components/views/elements/__snapshots__/PollCreateDialog-test.tsx.snap
  test/utils/test-utils.ts
  yarn.lock
Labels: T-Task

#7855 Fix non-customizable keybindings not working as expected
  src/KeyBindingsDefaults.ts
Labels: T-Defect

#7865 Fix misalignment with Event List Summaries
  res/css/views/messages/_ViewSourceEvent.scss
  res/css/views/rooms/_EventTile.scss
  src/components/views/elements/GenericEventListSummary.tsx
Labels: T-Defect

#7867 Fix edge case around event list summary layout
  res/css/views/messages/_ViewSourceEvent.scss
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#7866 Wire up CallEventGroupers for Search Results
  src/components/structures/CallEventGrouper.ts
  src/components/structures/TimelinePanel.tsx
  src/components/views/rooms/SearchResultTile.tsx
  test/components/views/rooms/SearchResultTile-test.tsx
Labels: T-Defect

#7861 Don't pillify code blocks
  src/utils/pillify.tsx
  test/components/views/messages/TextualBody-test.js
  test/components/views/messages/__snapshots__/TextualBody-test.js.snap
Labels: T-Defect

#7837 Bump matrix-events-sdk to 0.0.1-beta.7
  package.json
  yarn.lock
Labels: T-Task

#7875 Only show joined/invited in search dialog
  src/components/views/dialogs/SpotlightDialog.tsx
Labels: T-Defect

#7876 Throttle RoomState.members handlers
  src/components/structures/MessagePanel.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
Labels: T-Defect

#7850 Keybinding code unification #3
  src/BasePlatform.ts
  src/KeyBindingsDefaults.ts
  src/KeyBindingsManager.ts
  src/accessibility/KeyboardShortcuts.ts
  src/components/structures/LoggedInView.tsx
  src/components/views/voip/CallView.tsx
  src/i18n/strings/en_EN.json
  test/accessibility/KeyboardShortcuts-test.ts
  test/components/views/rooms/SendMessageComposer-test.tsx
Labels: T-Task

#7864 Fix missing padding on server picker
  res/css/views/elements/_ServerPicker.scss
Labels: T-Defect

#7881 Thread test utilities
  test/test-utils/test-utils.ts
  test/test-utils/threads.ts
Labels: T-Task

#7879 Support social login & password on soft logout page
  src/components/structures/auth/SoftLogout.tsx
  src/i18n/strings/en_EN.json
Labels: Sponsored, T-Defect

#7883 Remove log line to try to fix freeze on answering VoIP call
  src/components/views/voip/VideoFeed.tsx
Labels: T-Defect

#7884 Fix freeze on room switch
  src/utils/permalinks/Permalinks.ts
  test/utils/permalinks/Permalinks-test.js
Labels: T-Defect

#7882 Fix 'my threads' filtering to include participated threads
  src/components/structures/ThreadPanel.tsx
  test/components/structures/ThreadPanel-test.tsx
  test/test-utils/threads.ts
Labels: T-Defect

#7809 Check 'useSystemTheme' in quick settings theme switcher
  res/css/_components.scss
  res/css/components/views/spaces/_QuickThemeSwitcher.scss
  res/css/structures/_QuickSettingsButton.scss
  src/components/views/spaces/QuickSettingsButton.tsx
  src/components/views/spaces/QuickThemeSwitcher.tsx
  src/i18n/strings/en_EN.json
  test/components/views/spaces/QuickThemeSwitcher-test.tsx
  test/setupTests.js
Labels: T-Defect

#7872 Tidy up timelineRenderingType to be passed over context
  src/components/structures/MessagePanel.tsx
  src/components/structures/RoomView.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/SearchResultTile.tsx
  src/contexts/RoomContext.ts
Labels: T-Task

#7887 Fix vanishing recently viewed menu
  src/components/views/elements/InteractiveTooltip.tsx
Labels: T-Defect

#7890 Fix event list summary 1 hidden message pluralisation
  src/i18n/strings/en_EN.json
Labels: T-Defect

#7892 [Release] Fix edge case around event list summary layout
  res/css/views/rooms/_EventTile.scss
Labels: X-Release-Blocker, T-Defect

#7891 Fix edge case around event list summary layout
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#7878 Prefer RoomStateEvent.Update where possible as it fires far less
  src/DeviceListener.ts
  src/autocomplete/UserProvider.tsx
  src/components/structures/GroupFilterPanel.tsx
  src/components/structures/LoggedInView.tsx
  src/components/structures/MessagePanel.tsx
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/SpaceHierarchy.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/views/avatars/BaseAvatar.tsx
  src/components/views/avatars/RoomAvatar.tsx
  src/components/views/dialogs/DevtoolsDialog.tsx
  src/components/views/elements/RoomName.tsx
  src/components/views/elements/RoomTopic.tsx
  src/components/views/messages/SenderProfile.tsx
  src/components/views/right_panel/EncryptionPanel.tsx
  src/components/views/right_panel/PinnedMessagesCard.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/AuxPanel.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomListHeader.tsx
  src/components/views/rooms/RoomUpgradeWarningBar.tsx
  src/components/views/rooms/ThirdPartyMemberInfo.tsx
  src/components/views/settings/ChangeAvatar.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/dispatcher/payloads/AfterLeaveRoomPayload.ts
  src/dispatcher/payloads/JoinRoomErrorPayload.ts
  src/dispatcher/payloads/ViewRoomErrorPayload.ts
  src/dispatcher/payloads/ViewStartChatOrReusePayload.ts
  src/hooks/useAccountData.ts
  src/hooks/useEventEmitter.ts
  src/hooks/useIsEncrypted.ts
  src/hooks/useRoomMembers.ts
  src/hooks/useRoomState.ts
  src/hooks/useUserStatusMessage.ts
  src/stores/OwnProfileStore.ts
  src/utils/WidgetUtils.ts
Labels: T-Task

#7889 eslint to 8.9.0
  package.json
  src/components/structures/GroupView.js
  src/components/views/groups/GroupRoomTile.js
  src/components/views/rooms/RoomList.tsx
  yarn.lock
Labels: T-Task

#7863 Try harder to keep context menus inside the window
  src/components/structures/ContextMenu.tsx
  test/components/views/context_menus/ContextMenu-test.tsx
Labels: T-Defect

#7895 Fix emoji insertion in thread composer going to the main composer
  src/components/structures/RoomView.tsx
Labels: T-Defect

#7894 Fix upload button & shortcut not working for narrow composer mode
  src/components/views/rooms/MessageComposerButtons.tsx
Labels: T-Defect

#7896 manage voicerecording state when deleting or sending a voice message
  src/stores/VoiceRecordingStore.ts
  test/stores/VoiceRecordingStore-test.ts
Labels: T-Defect

#7893 Fix bug with useRoomHierarchy tight-looping loadMore on error
  src/components/structures/SpaceHierarchy.tsx
Labels: T-Defect

#7898 Fix composer format buttons on WebKit
  res/css/views/rooms/_MessageComposerFormatBar.scss
  src/components/views/rooms/MessageComposerFormatBar.tsx
Labels: T-Defect

#7839 Add slash command to switch to a room's virtual room
  src/SlashCommands.tsx
  src/VoipUserMapper.ts
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#7899 Fix edge case in context menu chevron positioning
  src/components/structures/ContextMenu.tsx
  test/components/views/context_menus/ContextMenu-test.tsx
Labels: T-Defect
