Repository matrix-org/matrix-react-sdk, pull requests merged in 2022-11, with the labels that each got.

#9514 sliding-sync: spider all rooms on the user's account for search
  src/MatrixClientPeg.ts
  src/SlidingSyncManager.ts
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  test/SlidingSyncManager-test.ts
Labels: T-Task

#9518 Change ListNotificationState to store room ids
  src/stores/notifications/ListNotificationState.ts
Labels: Z-Community-PR, T-Defect

#9526 Extract PlaybackInterface
  src/audio/Playback.ts
  src/components/views/audio_messages/AudioPlayer.tsx
  src/components/views/audio_messages/RecordingPlayback.tsx
  src/components/views/audio_messages/SeekBar.tsx
  test/audio/Playback-test.ts
  test/components/views/audio_messages/SeekBar-test.tsx
  test/components/views/audio_messages/__snapshots__/SeekBar-test.tsx.snap
  test/test-utils/audio.ts
Labels: T-Task

#9525 Refactor + improve test coverage for QR login
  src/components/views/auth/LoginWithQR.tsx
  src/components/views/auth/LoginWithQRFlow.tsx
  src/components/views/settings/devices/LoginWithQRSection.tsx
  test/components/views/elements/QRCode-test.tsx
  test/components/views/elements/__snapshots__/QRCode-test.tsx.snap
  test/components/views/settings/devices/LoginWithQR-test.tsx
  test/components/views/settings/devices/LoginWithQRFlow-test.tsx
  test/components/views/settings/devices/LoginWithQRSection-test.tsx
  test/components/views/settings/devices/__snapshots__/LoginWithQR-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/LoginWithQRFlow-test.tsx.snap
Labels: T-Task

#9527 Add eslint rule unicorn/no-instanceof-array
  package.json
  src/utils/DirectoryUtils.ts
  yarn.lock
Labels: T-Task

#9536 Fix /myroomavatar slash command
  src/SlashCommands.tsx
Labels: T-Defect, backport staging

#5949 Enable user to zoom beyond image size
  src/components/views/elements/ImageView.tsx
Labels: Z-Community-PR, T-Enhancement

#9528 Update types to match js-sdk --strict mode
  src/components/structures/InteractiveAuth.tsx
  src/components/structures/auth/Registration.tsx
  src/components/views/dialogs/DeactivateAccountDialog.tsx
  test/toasts/IncomingLegacyCallToast-test.tsx
Labels: T-Task

#9535 Fix: Move "Leave Space" option to the bottom of space context menu
  src/components/views/context_menus/SpaceContextMenu.tsx
Labels: Z-Community-PR, T-Enhancement

#9541 Enable tsc --strict CI to prevent gaining more errors
  .github/workflows/static_analysis.yaml
Labels: T-Task

#9538 Update to @casualbot/jest-sonar-reporter
  package.json
  sonar-project.properties
  yarn.lock
Labels: T-Task

#9482 Send layout analytics as WebLayout
  package.json
  src/PosthogAnalytics.ts
  test/PosthogAnalytics-test.ts
  yarn.lock
Labels: T-Task

#9542 Optimise Jest run in CI
  .github/workflows/tests.yml
  package.json
  test/ContentMessages-test.ts
  test/HtmlUtils-test.tsx
  test/Notifier-test.ts
  test/__snapshots__/Reply-test.ts.snap
  test/audio/VoiceMessageRecording-test.ts
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/beacon/LeftPanelLiveShareWarning-test.tsx
  test/components/views/beacon/__snapshots__/BeaconMarker-test.tsx.snap
  test/components/views/beacon/__snapshots__/BeaconStatus-test.tsx.snap
  test/components/views/beacon/__snapshots__/BeaconViewDialog-test.tsx.snap
  test/components/views/beacon/__snapshots__/RoomLiveShareWarning-test.tsx.snap
  test/components/views/context_menus/__snapshots__/SpaceContextMenu-test.tsx.snap
  test/components/views/dialogs/ForwardDialog-test.tsx
  test/components/views/dialogs/UserSettingsDialog-test.tsx
  test/components/views/dialogs/__snapshots__/ExportDialog-test.tsx.snap
  test/components/views/elements/__snapshots__/PollCreateDialog-test.tsx.snap
  test/components/views/location/LocationShareMenu-test.tsx
  test/components/views/location/__snapshots__/LocationViewDialog-test.tsx.snap
  test/components/views/location/__snapshots__/SmartMarker-test.tsx.snap
  test/components/views/location/__snapshots__/ZoomButtons-test.tsx.snap
  test/components/views/location/shareLocation-test.ts
  test/components/views/messages/DateSeparator-test.tsx
  test/components/views/messages/MKeyVerificationConclusion-test.tsx
  test/components/views/messages/__snapshots__/MLocationBody-test.tsx.snap
  test/components/views/messages/__snapshots__/MPollBody-test.tsx.snap
  test/components/views/messages/__snapshots__/MVideoBody-test.tsx.snap
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/components/views/right_panel/PinnedMessagesCard-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/components/views/rooms/VoiceRecordComposerTile-test.tsx
  test/components/views/settings/__snapshots__/FontScalingPanel-test.tsx.snap
  test/components/views/settings/__snapshots__/ThemeChoicePanel-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceDetailHeading-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceExpandDetailsButton-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/deleteDevices-test.tsx.snap
  test/components/views/settings/shared/__snapshots__/SettingsSubsectionHeading-test.tsx.snap
  test/components/views/typography/__snapshots__/Caption-test.tsx.snap
  test/editor/__snapshots__/deserialize-test.ts.snap
  test/models/Call-test.ts
  test/stores/widgets/__snapshots__/StopGapWidgetDriver-test.ts.snap
  test/test-utils/client.ts
  test/test-utils/platform.ts
  test/utils/MegolmExportEncryption-test.ts
  test/utils/__snapshots__/createVoiceMessageContent-test.ts.snap
  test/utils/exportUtils/HTMLExport-test.ts
  test/utils/exportUtils/JSONExport-test.ts
  test/utils/exportUtils/PlainTextExport-test.ts
  test/utils/notifications-test.ts
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.ts
  test/voice-broadcast/models/VoiceBroadcastRecording-test.ts
  test/voice-broadcast/utils/__snapshots__/startNewVoiceBroadcastRecording-test.ts.snap
  test/voice-broadcast/utils/startNewVoiceBroadcastRecording-test.ts
  yarn.lock
Labels: T-Task

#9540 Handle deletion of `m.call` events
  src/models/Call.ts
Labels: T-Defect

#9546 Fix notif panel exception around accessing roomId of undefined
  src/components/structures/TimelinePanel.tsx
Labels: T-Task

#9549 Fix regressions around media uploads failing and causing soft crashes
  src/Notifier.ts
  src/components/views/settings/ChangeAvatar.tsx
  src/components/views/settings/tabs/room/NotificationSettingsTab.tsx
  src/components/views/spaces/SpaceSettingsGeneralTab.tsx
  src/i18n/strings/en_EN.json
  test/Notifier-test.ts
Labels: X-Release-Blocker, T-Defect, backport staging

#9545 Make SonarCloud happier
  src/HtmlUtils.tsx
  src/Login.ts
  src/NodeAnimator.tsx
  src/Notifier.ts
  src/Searching.ts
  src/SlashCommands.tsx
  src/WhoIsTyping.ts
  src/components/structures/ContextMenu.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/SpaceHierarchy.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/auth/PasswordLogin.tsx
  src/components/views/auth/RegistrationForm.tsx
  src/components/views/avatars/DecoratedRoomAvatar.tsx
  src/components/views/dialogs/AddExistingToSpaceDialog.tsx
  src/components/views/dialogs/CreateRoomDialog.tsx
  src/components/views/dialogs/KeySignatureUploadFailedDialog.tsx
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/elements/EditableText.tsx
  src/components/views/elements/EventListSummary.tsx
  src/components/views/messages/MBeaconBody.tsx
  src/components/views/messages/MFileBody.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/rooms/RoomSublist.tsx
  src/components/views/settings/ChangePassword.tsx
  src/components/views/terms/InlineTermsAgreement.tsx
  src/i18n/strings/en_EN.json
  test/SlashCommands-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Task

#9547 Fix `ThreadView` tests not using thread flag
  test/Notifier-test.ts
  test/components/structures/ThreadView-test.tsx
Labels: T-Defect

#9552 Fix LegacyCallHandler-test
  test/test-utils/test-utils.ts
Labels: T-Task

#9524 Always use current profile on thread events
  src/components/views/avatars/MemberAvatar.tsx
  src/components/views/messages/DisambiguatedProfile.tsx
  src/components/views/messages/SenderProfile.tsx
  src/components/views/rooms/EventTile.tsx
  src/hooks/room/useRoomMemberProfile.ts
  test/components/views/beacon/__snapshots__/BeaconMarker-test.tsx.snap
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
Labels: T-Defect

#9553 Fix TimelineReset handling when no room associated
  src/indexing/EventIndex.ts
Labels: T-Defect

#9557 Update matrix-events-sdk to 0.0.1 and develop ref to matrix-js-sdk
  package.json
  yarn.lock
Labels: T-Task

#9559 Add way to create a user notice via config.json
  src/IConfigOptions.ts
  src/components/structures/MatrixChat.tsx
Labels: T-Enhancement

#9560 Close context menu when a modal is opened to prevent user getting stuck
  src/Modal.tsx
  src/components/structures/ContextMenu.tsx
  test/components/views/context_menus/ContextMenu-test.tsx
  test/components/views/location/LocationShareMenu-test.tsx
Labels: T-Defect

#8759 Advanced audio processing settings
  src/MediaDeviceHandler.ts
  src/components/views/settings/tabs/user/VoiceUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/MediaDeviceHandler-test.ts
  test/components/views/settings/tabs/user/VoiceUserSettingsTab-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#9548 Add voice broadcast pre-recording PiP
  res/css/voice-broadcast/molecules/_VoiceBroadcastBody.pcss
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/voip/PictureInPictureDragger.tsx
  src/components/views/voip/PipView.tsx
  src/contexts/SDKContext.ts
  src/i18n/strings/en_EN.json
  src/voice-broadcast/components/atoms/VoiceBroadcastHeader.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastPreRecordingPip.tsx
  src/voice-broadcast/hooks/useCurrentVoiceBroadcastPreRecording.ts
  src/voice-broadcast/hooks/useCurrentVoiceBroadcastRecording.ts
  src/voice-broadcast/index.ts
  src/voice-broadcast/models/VoiceBroadcastPreRecording.ts
  src/voice-broadcast/stores/VoiceBroadcastPreRecordingStore.ts
  src/voice-broadcast/utils/checkVoiceBroadcastPreConditions.tsx
  src/voice-broadcast/utils/setUpVoiceBroadcastPreRecording.ts
  src/voice-broadcast/utils/startNewVoiceBroadcastRecording.ts
  test/TestSdkContext.ts
  test/components/views/voip/PipView-test.tsx
  test/contexts/SdkContext-test.ts
  test/stores/OwnBeaconStore-test.ts
  test/test-utils/test-utils.ts
  test/test-utils/wrappers.tsx
  test/utils/MultiInviter-test.ts
  test/voice-broadcast/models/VoiceBroadcastPreRecording-test.ts
  test/voice-broadcast/stores/VoiceBroadcastPreRecordingStore-test.ts
  test/voice-broadcast/utils/setUpVoiceBroadcastPreRecording-test.ts
Labels: T-Task

#9562 Differentiate download and decryption errors when showing images
  package.json
  src/components/views/messages/MImageBody.tsx
  src/i18n/strings/en_EN.json
  src/utils/DecryptFile.ts
  src/utils/LazyValue.ts
  test/components/views/messages/MImageBody-test.tsx
  yarn.lock
Labels: T-Defect

#9564 Add voice broadcast max length
  res/img/element-icons/Timer.svg
  src/DateUtils.ts
  src/IConfigOptions.ts
  src/SdkConfig.ts
  src/components/views/audio_messages/Clock.tsx
  src/i18n/strings/en_EN.json
  src/voice-broadcast/audio/VoiceBroadcastRecorder.ts
  src/voice-broadcast/components/atoms/VoiceBroadcastHeader.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip.tsx
  src/voice-broadcast/hooks/useVoiceBroadcastRecording.tsx
  src/voice-broadcast/index.ts
  src/voice-broadcast/models/VoiceBroadcastRecording.ts
  src/voice-broadcast/utils/VoiceBroadcastChunkEvents.ts
  src/voice-broadcast/utils/getMaxBroadcastLength.ts
  test/SdkConfig-test.ts
  test/test-utils/test-utils.ts
  test/utils/DateUtils-test.ts
  test/voice-broadcast/audio/VoiceBroadcastRecorder-test.ts
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip-test.tsx
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastRecordingPip-test.tsx.snap
  test/voice-broadcast/models/VoiceBroadcastRecording-test.ts
  test/voice-broadcast/utils/getMaxBroadcastLength-test.ts
Labels: T-Task

#9477 Don't switch to the home page needlessly after leaving a room
  src/utils/leave-behaviour.ts
  test/utils/leave-behaviour-test.ts
Labels: T-Defect

#9565 Resilience fix for homeserver without thread notification support
  src/components/views/right_panel/RoomHeaderButtons.tsx
  test/components/views/right_panel/RoomHeaderButtons-test.tsx
Labels: T-Defect

#9569 Fix sliding sync cypress spec
  cypress/e2e/sliding-sync/sliding-sync.ts
Labels: T-Task

#9568 Extract requestMediaPermissions
  src/components/views/settings/tabs/user/VoiceUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/utils/media/requestMediaPermissions.tsx
  test/components/views/messages/CallEvent-test.tsx
  test/components/views/rooms/RoomTile-test.tsx
  test/components/views/voip/CallView-test.tsx
  test/components/views/voip/PipView-test.tsx
  test/setup/setupManualMocks.ts
  test/stores/room-list/algorithms/Algorithm-test.ts
  test/toasts/IncomingCallToast-test.tsx
  test/utils/media/requestMediaPermissions-test.tsx
Labels: T-Task

#9567 fix read receipts trickling down correctly
  src/components/views/avatars/MemberAvatar.tsx
  src/components/views/rooms/ReadReceiptMarker.tsx
Labels: T-Defect

#9563 Fix missing avatar for show current profiles
  src/components/views/avatars/BaseAvatar.tsx
  src/components/views/avatars/MemberAvatar.tsx
  src/hooks/room/useRoomMemberProfile.ts
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/avatars/MemberAvatar-test.tsx
  test/components/views/beacon/__snapshots__/BeaconMarker-test.tsx.snap
  test/components/views/beacon/__snapshots__/DialogSidebar-test.tsx.snap
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
Labels: T-Defect

#9571 fix wrong error message in registration when phone number threepid is in use.
  src/components/structures/auth/Registration.tsx
  src/i18n/strings/en_EN.json
Labels: Z-Community-PR, T-Defect

#9543 Fix: inline links selecting radio button
  src/components/views/settings/tabs/room/NotificationSettingsTab.tsx
  test/components/views/settings/tabs/room/NotificationSettingsTab-test.tsx
Labels: Z-Community-PR, T-Defect

#9570 Fix links being mangled by markdown processing
  src/Markdown.ts
  test/Markdown-test.ts
Labels: T-Defect

#9573 Update @matrix-org/matrix-wysiwyg dependency
  package.json
  src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
  src/components/views/rooms/wysiwyg_composer/components/WysiwygComposer.tsx
  test/components/views/rooms/MessageComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/SendWysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/FormattingButtons-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
  yarn.lock
Labels: T-Task

#9577 Add CI to run rethemendex.sh
  .github/workflows/static_analysis.yaml
  res/css/_common.pcss
  res/css/_components.pcss
  res/css/views/rooms/_EmojiButton.pcss
  res/css/views/rooms/_MessageComposer.pcss
  res/css/views/rooms/_MessageComposerButton.pcss
Labels: T-Task

#9572 Add voice broadcast pre recording device selection
  res/css/compound/_Icon.pcss
  res/css/voice-broadcast/atoms/_VoiceBroadcastHeader.pcss
  src/MediaDeviceHandler.ts
  src/components/structures/ContextMenu.tsx
  src/components/views/context_menus/IconizedContextMenu.tsx
  src/components/views/settings/tabs/user/VoiceUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/voice-broadcast/components/atoms/VoiceBroadcastHeader.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastPreRecordingPip.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingBody.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip.tsx
  test/components/structures/ContextMenu-test.ts
  test/voice-broadcast/components/atoms/VoiceBroadcastHeader-test.tsx
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastRecordingPip-test.tsx.snap
Labels: T-Task

#9579 Deduplicate string compare utility
  src/components/views/rooms/WhoIsTypingTile.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/integrations/IntegrationManagers.ts
  src/stores/room-list/algorithms/tag-sorting/AlphabeticAlgorithm.ts
  src/stores/widgets/WidgetLayoutStore.ts
  src/theme.ts
  src/utils/SortMembers.ts
  src/utils/strings.ts
  test/components/views/rooms/MemberList-test.tsx
Labels: T-Task

#9575 Make clear notifications work with threads
  src/components/views/settings/Notifications.tsx
  src/utils/notifications.ts
  test/components/views/settings/Notifications-test.tsx
  test/components/views/settings/__snapshots__/Notifications-test.tsx.snap
  test/utils/notifications-test.ts
Labels: T-Enhancement

#9580 Migrate useTopic test to RTL
  test/useTopic-test.tsx
Labels: T-Task

#9578 Remove useWysiwyg mock
  test/components/views/rooms/MessageComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/SendWysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
  test/setup/setupManualMocks.ts
Labels: T-Task

#9587 Update cypress.md
  docs/cypress.md
Labels: T-Task

#9591 Use react-testing-library instead of enzyme for useDebouncedCallback
  package.json
  test/hooks/useDebouncedCallback-test.tsx
  yarn.lock
Labels: T-Task

#9589 Device manager - update verified device learn more copy
  src/components/views/settings/devices/DeviceSecurityLearnMore.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#9590 Add live voice broadcast indicator to user menu
  res/css/compound/_Icon.pcss
  res/css/structures/_UserMenu.pcss
  src/components/structures/UserMenu.tsx
  src/voice-broadcast/stores/VoiceBroadcastRecordingsStore.ts
  test/components/structures/UserMenu-test.tsx
  test/components/structures/__snapshots__/UserMenu-test.tsx.snap
  test/voice-broadcast/stores/VoiceBroadcastRecordingsStore-test.ts
Labels: T-Task

#9584 Migrate some tests to React Testing Library
  src/components/structures/SearchBox.tsx
  test/components/views/dialogs/ForwardDialog-test.tsx
  test/components/views/messages/MVideoBody-test.tsx
  test/components/views/messages/__snapshots__/MVideoBody-test.tsx.snap
  test/components/views/rooms/SearchBar-test.tsx
  test/components/views/rooms/SearchResultTile-test.tsx
  test/components/views/settings/FontScalingPanel-test.tsx
  test/components/views/settings/ThemeChoicePanel-test.tsx
  test/components/views/settings/UiFeatureSettingWrapper-test.tsx
  test/components/views/settings/__snapshots__/FontScalingPanel-test.tsx.snap
  test/components/views/settings/__snapshots__/ThemeChoicePanel-test.tsx.snap
  test/components/views/settings/__snapshots__/UiFeatureSettingWrapper-test.tsx.snap
Labels: T-Task

#9365 Limit formatting bar offset to top of composer
  src/components/views/rooms/MessageComposerFormatBar.tsx
Labels: Z-Community-PR, T-Enhancement

#9597 Fix branch matching for the strict tsc CI
  .github/workflows/static_analysis.yaml
Labels: T-Task

#9530 sliding sync: add lazy-loading member support
  src/SlidingSyncManager.ts
  src/components/views/rooms/MemberList.tsx
  src/contexts/SDKContext.ts
  src/stores/MemberListStore.ts
  test/SlidingSyncManager-test.ts
  test/components/structures/RightPanel-test.tsx
  test/components/views/rooms/MemberList-test.tsx
  test/stores/MemberListStore-test.ts
Labels: T-Enhancement

#9594 Device manager - add tooltip to device details toggle
  cypress/e2e/settings/device-management.spec.ts
  src/components/views/settings/devices/CurrentDeviceSection.tsx
  src/components/views/settings/devices/DeviceExpandDetailsButton.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/DeviceExpandDetailsButton-test.tsx
  test/components/views/settings/devices/FilteredDeviceList-test.tsx
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceExpandDetailsButton-test.tsx.snap
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Enhancement

#9601 Add --noImplicitAny to strict CI check
  .github/workflows/static_analysis.yaml
Labels: T-Task

#9600 Enable tsc alwaysStrict, strictBindCallApply, noImplicitThis
  package.json
  src/@types/common.ts
  src/@types/commonmark.ts
  src/@types/diff-dom.d.ts
  src/@types/png-chunks-extract.d.ts
  src/@types/sanitize-html.d.ts
  src/Markdown.ts
  src/Notifier.ts
  src/SlashCommands.tsx
  src/autocomplete/QueryMatcher.ts
  src/components/views/elements/Draggable.tsx
  src/components/views/elements/IRCTimelineProfileResizer.tsx
  src/components/views/elements/Validation.tsx
  src/utils/Image.ts
  src/utils/MegolmExportEncryption.ts
  test/ContentMessages-test.ts
  test/Notifier-test.ts
  test/SlashCommands-test.tsx
  test/__snapshots__/SlashCommands-test.tsx.snap
  test/components/views/Validation-test.ts
  test/test-utils/audio.ts
  tsconfig.json
  yarn.lock
Labels: T-Task

#9598 Fix form tooltip positioning
  res/css/views/elements/_Field.pcss
  res/css/views/elements/_Tooltip.pcss
Labels: T-Defect, X-Needs-Percy

#9558 Fix `getRelationsForEvent` under TypeScript `strict` mode
  src/components/structures/MessagePanel.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/dialogs/EndPollDialog.tsx
  src/components/views/elements/ReplyChain.tsx
  src/components/views/emojipicker/ReactionPicker.tsx
  src/components/views/messages/IBodyProps.ts
  src/components/views/messages/MBeaconBody.tsx
  src/components/views/messages/MPollBody.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/messages/MessageEvent.tsx
  src/components/views/messages/ReactionsRow.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/ReplyTile.tsx
  test/components/views/messages/MPollBody-test.tsx
Labels: T-Task

#9604 Refactor PipView + fix strict errors
  src/components/views/voip/PictureInPictureDragger.tsx
  src/components/views/voip/PipView.tsx
  test/components/views/voip/PipView-test.tsx
Labels: T-Task

#9602 Fix SpaceTreeLevel enzyme test
  test/components/views/spaces/SpaceTreeLevel-test.tsx
Labels: T-Task

#9609 Wire up Netlify deployments for update notifications
  .github/workflows/element-web.yaml
Labels: T-Task

#9605 Consolidate public room search experience
  cypress/e2e/room-directory/room-directory.spec.ts
  res/css/_components.pcss
  res/css/structures/_RoomDirectory.pcss
  res/css/views/elements/_DirectorySearchBox.pcss
  src/Rooms.ts
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomDirectory.tsx
  src/components/structures/SpaceHierarchy.tsx
  src/components/views/dialogs/spotlight/PublicRoomResultDetails.tsx
  src/components/views/elements/DirectorySearchBox.tsx
  src/components/views/rooms/PublicRoomTile.tsx
  src/customisations/Alias.ts
  src/i18n/strings/en_EN.json
  src/utils/DirectoryUtils.ts
  src/utils/rooms.ts
  test/components/structures/SpaceHierarchy-test.tsx
  test/components/views/dialogs/spotlight/PublicRoomResultDetails-test.tsx
  test/components/views/dialogs/spotlight/__snapshots__/PublicRoomResultDetails-test.tsx.snap
Labels: T-Enhancement, X-Needs-Percy

#9603 Add voice broadcast playback pip
  src/components/views/voip/PipView.tsx
  src/contexts/SDKContext.ts
  src/stores/RoomViewStore.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody.tsx
  src/voice-broadcast/hooks/useCurrentVoiceBroadcastPlayback.ts
  src/voice-broadcast/index.ts
  src/voice-broadcast/stores/VoiceBroadcastPlaybacksStore.ts
  src/voice-broadcast/utils/doClearCurrentVoiceBroadcastPlaybackIfStopped.ts
  src/voice-broadcast/utils/doMaybeSetCurrentVoiceBroadcastPlayback.ts
  src/voice-broadcast/utils/hasRoomLiveVoiceBroadcast.ts
  test/TestSdkContext.ts
  test/components/views/voip/PipView-test.tsx
  test/voice-broadcast/utils/hasRoomLiveVoiceBroadcast-test.ts
Labels: T-Task

#9608 Fix regression with TimelinePanel props updates not taking effect
  src/components/structures/TimelinePanel.tsx
  test/components/structures/TimelinePanel-test.tsx
Labels: T-Defect

#9613 Add placeholder for rich text editor
  res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/wysiwyg_composer/SendWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/components/Editor.tsx
  src/components/views/rooms/wysiwyg_composer/components/PlainTextComposer.tsx
  src/components/views/rooms/wysiwyg_composer/components/WysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/usePlainTextListeners.ts
  test/components/views/rooms/wysiwyg_composer/SendWysiwygComposer-test.tsx
Labels: T-Enhancement

#9599 Add slow jest reporter
  .github/workflows/tests.yml
  test/slowReporter.js
Labels: T-Task

#9617 Fix voice broadcast recording after pause
  src/voice-broadcast/audio/VoiceBroadcastRecorder.ts
  test/voice-broadcast/audio/VoiceBroadcastRecorder-test.ts
Labels: T-Task

#9611 Fix login screen style
  res/css/views/auth/_AuthBody.pcss
  res/css/views/dialogs/_VerifyEMailDialog.pcss
  src/components/structures/auth/ForgotPassword.tsx
  src/components/views/auth/AuthBody.tsx
Labels: T-Defect, X-Needs-Percy

#9606 Fix thread list jumping back down while scrolling
  src/components/structures/MessagePanel.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/structures/TimelinePanel.tsx
  test/components/structures/TimelinePanel-test.tsx
Labels: T-Defect

#9621 Update @typescript-eslint/parser
  yarn.lock
Labels: T-Task

#9623 Pause voice broadcast on calls
  src/stores/widgets/StopGapWidget.ts
  src/voice-broadcast/models/VoiceBroadcastRecording.ts
  test/stores/widgets/StopGapWidget-test.ts
  test/voice-broadcast/models/VoiceBroadcastRecording-test.ts
Labels: T-Task

#9622 Tweak voice broadcast play icon
  res/css/voice-broadcast/atoms/_VoiceBroadcastControl.pcss
  src/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody.tsx
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPlaybackBody-test.tsx.snap
Labels: T-Task

#9620 Add input device selection during voice broadcast
  res/css/compound/_Icon.pcss
  res/img/element-icons/Mic.svg
  src/components/views/audio_messages/DevicesContextMenu.tsx
  src/hooks/useAudioDeviceSelection.ts
  src/i18n/strings/en_EN.json
  src/voice-broadcast/components/molecules/VoiceBroadcastPreRecordingPip.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip.tsx
  src/voice-broadcast/hooks/useVoiceBroadcastRecording.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastPreRecordingPip-test.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip-test.tsx
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPreRecordingPip-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastRecordingPip-test.tsx.snap
Labels: T-Task

#9615 Fix edit a reply in rich text editor
  src/components/views/rooms/wysiwyg_composer/EditWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useEditing.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useInitialContent.ts
  test/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx
Labels: T-Defect

#9634 Fix seekbar in voice broadcast pip
  src/components/views/audio_messages/SeekBar.tsx
Labels: T-Task

#9632 Add helper for thread root id in view source
  src/components/structures/ViewSource.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#9629 Stop voice broadcast on delete
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.ts
Labels: T-Task

#9625 Use native js-sdk group call support
  src/components/views/beacon/RoomCallBanner.tsx
  src/components/views/messages/CallEvent.tsx
  src/components/views/rooms/LiveContentSummary.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomTileCallSummary.tsx
  src/components/views/voip/CallDuration.tsx
  src/components/views/voip/CallView.tsx
  src/hooks/useCall.ts
  src/i18n/strings/en_EN.json
  src/models/Call.ts
  src/stores/CallStore.ts
  src/toasts/IncomingCallToast.tsx
  test/components/views/messages/CallEvent-test.tsx
  test/components/views/rooms/RoomTile-test.tsx
  test/components/views/voip/CallView-test.tsx
  test/createRoom-test.ts
  test/models/Call-test.ts
  test/test-utils/call.ts
  test/test-utils/test-utils.ts
  test/toasts/IncomingCallToast-test.tsx
Labels: T-Enhancement

#9638 Fix the size of the 'Private space' icon
  res/css/views/rooms/_RoomInfoLine.pcss
Labels: T-Defect

#9640 Fix the background color flashing when joining a call
  res/css/views/voip/_CallView.pcss
Labels: T-Defect

#6396 Further improve replies
  res/css/views/elements/_ReplyChain.pcss
  res/css/views/rooms/_ReplyTile.pcss
  src/components/views/messages/MImageReplyBody.tsx
  src/components/views/rooms/ReplyTile.tsx
Labels: T-Enhancement

#9612 Fix screensharing in 1:1 calls
  src/components/views/voip/LegacyCallView.tsx
Labels: X-Release-Blocker, T-Defect

#9635 Fix search not being cleared when clicking on a result
  src/components/structures/RoomView.tsx
  test/components/structures/RoomSearchView-test.tsx
Labels: X-Release-Blocker, T-Defect

#9631 Pass a client into `RoomNotifs.getRoomNotifsState`
  src/RoomNotifs.ts
  src/hooks/useUnreadNotifications.ts
  src/stores/local-echo/RoomEchoChamber.ts
  src/stores/notifications/RoomNotificationState.ts
  test/RoomNotifs-test.ts
Labels: T-Task

#9639 Minor code quality updates for ScrollPanel
  src/components/structures/MessagePanel.tsx
  src/components/structures/ScrollPanel.tsx
Labels: T-Task

#9645 Fix issues around up arrow event edit shortcut
  src/components/structures/RoomView.tsx
  src/utils/EventUtils.ts
  test/utils/EventUtils-test.ts
Labels: T-Defect

#9647 Add a required tsc strict check for --noImplicitAny
  .github/workflows/static_analysis.yaml
Labels: T-Task

#9641 Show day counts in call durations
  src/DateUtils.ts
  src/components/structures/LegacyCallEventGrouper.ts
  src/components/views/messages/LegacyCallEvent.tsx
  src/components/views/voip/CallDuration.tsx
  src/i18n/strings/en_EN.json
  test/utils/DateUtils-test.ts
Labels: T-Defect

#9654 Update CODEOWNERS
  .github/CODEOWNERS
Labels: T-Task

#9646 Update voice broadcast time display
  res/css/voice-broadcast/molecules/_VoiceBroadcastBody.pcss
  src/DateUtils.ts
  src/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody.tsx
  src/voice-broadcast/hooks/useVoiceBroadcastPlayback.ts
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  test/utils/DateUtils-test.ts
  test/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody-test.tsx
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPlaybackBody-test.tsx.snap
Labels: T-Task

#9651 Pin @types/react* packages
  package.json
  yarn.lock
Labels: T-Task

#9630 Start voice broadcast recording while listening
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/voip/PipView.tsx
  src/voice-broadcast/models/VoiceBroadcastPreRecording.ts
  src/voice-broadcast/utils/setUpVoiceBroadcastPreRecording.ts
  src/voice-broadcast/utils/startNewVoiceBroadcastRecording.ts
  test/components/views/voip/PipView-test.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastPreRecordingPip-test.tsx
  test/voice-broadcast/models/VoiceBroadcastPreRecording-test.ts
  test/voice-broadcast/stores/VoiceBroadcastPreRecordingStore-test.ts
  test/voice-broadcast/utils/setUpVoiceBroadcastPreRecording-test.ts
  test/voice-broadcast/utils/startNewVoiceBroadcastRecording-test.ts
Labels: T-Task

#9643 Update Voice Broadcast buffering style
  res/css/voice-broadcast/atoms/_VoiceBroadcastHeader.pcss
  src/i18n/strings/en_EN.json
  src/voice-broadcast/components/atoms/VoiceBroadcastHeader.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody.tsx
  src/voice-broadcast/hooks/useVoiceBroadcastPlayback.ts
  test/voice-broadcast/components/atoms/VoiceBroadcastHeader-test.tsx
  test/voice-broadcast/components/atoms/__snapshots__/VoiceBroadcastHeader-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPlaybackBody-test.tsx.snap
Labels: T-Task

#9652 Stub out calls to vector.im and matrix.org in Cypress
  cypress/e2e/login/login.spec.ts
  cypress/e2e/register/register.spec.ts
  cypress/fixtures/matrix-org-client-login.json
  cypress/fixtures/matrix-org-client-versions.json
  cypress/fixtures/matrix-org-client-well-known.json
  cypress/fixtures/vector-im-identity-v1.json
  cypress/support/network.ts
Labels: T-Task, X-Needs-Percy

#9658 Typescript updates
  package.json
  src/@types/global.d.ts
  src/DecryptionFailureTracker.ts
  src/LegacyCallHandler.tsx
  src/Lifecycle.ts
  src/NodeAnimator.tsx
  src/PasswordReset.ts
  src/audio/PlaybackClock.ts
  src/autocomplete/Autocompleter.ts
  src/autocomplete/EmojiProvider.tsx
  src/components/structures/InteractiveAuth.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/ScrollPanel.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/dialogs/SlidingSyncOptionsDialog.tsx
  src/components/views/dialogs/devtools/VerificationExplorer.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/elements/DesktopCapturerSourcePicker.tsx
  src/components/views/elements/UseCaseSelection.tsx
  src/components/views/emojipicker/EmojiPicker.tsx
  src/components/views/emojipicker/Search.tsx
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/TextualBody.tsx
  src/components/views/rooms/Autocomplete.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/RoomBreadcrumbs.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useIsFocused.ts
  src/components/views/rooms/wysiwyg_composer/hooks/utils.ts
  src/components/views/settings/ThemeChoicePanel.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/components/views/toasts/VerificationRequestToast.tsx
  src/components/views/user-onboarding/UserOnboardingPage.tsx
  src/components/views/voip/CallDuration.tsx
  src/dispatcher/dispatcher.ts
  src/hooks/spotlight/useDebouncedCallback.ts
  src/hooks/useTimeout.ts
  src/hooks/useTimeoutToggle.ts
  src/hooks/useUserOnboardingContext.ts
  src/models/Call.ts
  src/rageshake/rageshake.ts
  src/stores/OwnBeaconStore.ts
  src/stores/room-list/RoomListStore.ts
  src/theme.ts
  src/utils/MultiInviter.ts
  src/utils/Timer.ts
  src/utils/WidgetUtils.ts
  src/utils/exportUtils/exportJS.js
  src/utils/image-media.ts
  src/utils/local-room.ts
  src/utils/membership.ts
  src/utils/promise.ts
  test/ContentMessages-test.ts
  test/components/views/location/LocationShareMenu-test.tsx
  test/components/views/settings/Notifications-test.tsx
  test/setup/setupManualMocks.ts
  test/test-utils/beacon.ts
  test/test-utils/utilities.ts
  test/voice-broadcast/utils/startNewVoiceBroadcastRecording-test.ts
  yarn.lock
Labels: T-Task

#9619 Add a test for verifying without existing DM
  cypress/e2e/crypto/crypto.spec.ts
  cypress/support/bot.ts
  cypress/support/login.ts
Labels: T-Task

#9653 Remove unused Element Call capabilities
  src/stores/widgets/StopGapWidgetDriver.ts
  test/stores/widgets/StopGapWidgetDriver-test.ts
Labels: T-Task

#8969 Separate labs and betas more clearly
  res/css/views/beta/_BetaCard.pcss
  res/css/views/elements/_SettingsFlag.pcss
  src/components/views/elements/SettingsFlag.tsx
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/SettingsStore.ts
  src/settings/controllers/SettingController.ts
Labels: T-Enhancement
