Repository matrix-org/matrix-react-sdk, pull requests merged in 2022-08, with the labels that each got.

#9006 Apply inline start padding to selected lines on modern layout only
  cypress/e2e/14-timeline/timeline.spec.ts
  res/css/views/rooms/_EventTile.pcss
Labels: Z-Community-PR, T-Defect

#9118 Add unit test for UserSettingsDialog
  src/components/structures/TabbedView.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  test/components/views/dialogs/UserSettingsDialog-test.tsx
  test/components/views/dialogs/__snapshots__/UserSettingsDialog-test.tsx.snap
  test/test-utils/client.ts
Labels: T-Task

#9090 The Welcome Home Screen: "Submit Feedback" pane
  res/css/_components.pcss
  res/css/views/user-onboarding/_UserOnboardingFeedback.pcss
  src/components/views/user-onboarding/UserOnboardingFeedback.tsx
  src/components/views/user-onboarding/UserOnboardingList.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#9124 Exclude functional members from DM detection
  src/CallHandler.tsx
  src/utils/dm/findDMForUser.ts
  src/utils/room/getFunctionalMembers.ts
  src/utils/room/getJoinedNonFunctionalMembers.ts
  test/CallHandler-test.ts
  test/utils/dm/findDMForUser-test.ts
  test/utils/room/getJoinedNonFunctionalMembers-test.ts
  test/utils/room/getRoomFunctionalMembers-test.ts
Labels: T-Defect

#9123 Don't enumerate Cypress tests
  cypress/e2e/create-room/create-room.spec.ts
  cypress/e2e/crypto/crypto.spec.ts
  cypress/e2e/location/location.spec.ts
  cypress/e2e/login/consent.spec.ts
  cypress/e2e/login/login.spec.ts
  cypress/e2e/polls/polls.spec.ts
  cypress/e2e/register/register.spec.ts
  cypress/e2e/regression-tests/pills-click-in-app.spec.ts
  cypress/e2e/room-directory/room-directory.spec.ts
  cypress/e2e/spaces/spaces.spec.ts
  cypress/e2e/spotlight/spotlight.spec.ts
  cypress/e2e/threads/threads.spec.ts
  cypress/e2e/timeline/timeline.spec.ts
  cypress/e2e/update/update.spec.ts
  cypress/e2e/user-menu/user-menu.spec.ts
  cypress/e2e/user-view/user-view.spec.ts
  cypress/e2e/widgets/stickers.spec.ts
Labels: T-Task

#9109 Fix dismissing edit composer when change was undone
  cypress/e2e/editing/editing.spec.ts
  src/components/views/rooms/EditMessageComposer.tsx
Labels: T-Defect

#9129 Remove "Add Space" button from RoomListHeader when user cannot create spaces
  src/components/views/rooms/RoomListHeader.tsx
  test/components/views/rooms/RoomListHeader-test.tsx
Labels: T-Enhancement

#8612 Start DM on first message
  cypress/e2e/crypto/crypto.spec.ts
  cypress/e2e/spotlight/spotlight.spec.ts
  res/css/_components.pcss
  res/css/structures/_LargeLoader.pcss
  res/css/structures/_RoomView.pcss
  src/components/structures/LargeLoader.tsx
  src/components/structures/RoomView.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/LargeLoader-test.tsx
  test/components/structures/RoomView-test.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/dialogs/SpotlightDialog-test.tsx
Labels: T-Enhancement

#9052 Add GHA for Dead Code Analysis
  .github/workflows/static_analysis.yaml
  src/hooks/useEventEmitter.ts
Labels: T-Task

#9126 Fix highlights not being applied to plaintext messages
  cypress/e2e/timeline/timeline.spec.ts
  src/HtmlUtils.tsx
Labels: T-Defect, X-Needs-Percy

#9137 Fix composer padding
  res/css/structures/_RoomView.pcss
Labels: T-Defect, X-Needs-Percy

#8629 Add option to stop sending read receipts (delabs MSC2285: private read receipts)
  src/components/structures/MessagePanel.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/elements/SettingsFlag.tsx
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/utils/read-receipts.ts
  test/components/structures/TimelinePanel-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Task

#9122 Device manager - New device tile info design
  res/css/_components.pcss
  res/css/components/views/settings/devices/_DeviceTile.pcss
  res/css/rethemendex.sh
  src/components/views/settings/DevicesPanelEntry.tsx
  src/components/views/settings/devices/DeviceTile.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/DeviceTile-test.tsx
  test/components/views/settings/devices/__snapshots__/DeviceTile-test.tsx.snap
Labels: T-Enhancement

#9135 Move pin drop out of labs (PSG-664)
  cypress/e2e/location/location.spec.ts
  src/components/views/location/LocationShareMenu.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/views/location/LocationShareMenu-test.tsx
Labels: T-Enhancement

#9132 Make percy snapshots for user onboarding more reliable
  cypress/e2e/lazy-loading/lazy-loading.spec.ts
  cypress/e2e/user-onboarding/user-onboarding-new.ts
  res/css/views/dialogs/_AppDownloadDialog.pcss
  src/components/views/dialogs/AppDownloadDialog.tsx
Labels: T-Task, X-Needs-Percy

#9133 Increase max length of voice messages to 15m (PSG-661)
  src/audio/VoiceRecording.ts
Labels: T-Enhancement

#9138 Make Spaces cypress tests less flaky
  cypress/e2e/spaces/spaces.spec.ts
Labels: T-Task

#9148 Live location sharing: share location at most every 5 seconds (PSG-655)
  src/stores/OwnBeaconStore.ts
Labels: T-Enhancement

#9141 Migrate the hidden read receipts flag to new "send read receipts" option
  cypress/e2e/settings/hidden-rr-migration.spec.ts
  cypress/support/login.ts
  cypress/support/settings.ts
  src/Lifecycle.ts
  src/settings/SettingsStore.ts
  src/settings/handlers/DeviceSettingsHandler.ts
Labels: X-Release-Blocker, T-Enhancement

#9149 Some small tidying up
  package.json
  src/components/structures/MatrixChat.tsx
  src/linkify-matrix.ts
  yarn.lock
Labels: T-Task

#9153 Device manager - selectable device tile wrapper (PSG-637)
  res/css/_components.pcss
  res/css/components/views/settings/devices/_SelectableDeviceTile.pcss
  res/css/views/settings/_DevicesPanel.pcss
  src/components/views/elements/StyledCheckbox.tsx
  src/components/views/settings/DevicesPanelEntry.tsx
  src/components/views/settings/devices/DeviceTile.tsx
  src/components/views/settings/devices/SelectableDeviceTile.tsx
  test/components/views/elements/__snapshots__/LabelledCheckbox-test.tsx.snap
  test/components/views/settings/devices/SelectableDeviceTile-test.tsx
  test/components/views/settings/devices/__snapshots__/SelectableDeviceTile-test.tsx.snap
Labels: T-Task

#9154 cypress: log stdout/stderr when docker exec fails
  cypress/plugins/docker/index.ts
Labels: T-Task

#9152 Fix pillification sometimes doubling up
  src/utils/pillify.tsx
  test/utils/pillify-test.tsx
Labels: T-Defect

#9139 Fixes around URL tooltips and in-app matrix.to link handling
  cypress/e2e/regression-tests/pills-click-in-app.spec.ts
  src/components/views/messages/TextualBody.tsx
  src/utils/tooltipify.tsx
  test/utils/tooltipify-test.tsx
Labels: X-Release-Blocker, T-Task

#9150 Define interface for RLS to ease wiring in Sliding Sync
  src/@types/global.d.ts
  src/components/views/rooms/RoomSublist.tsx
  src/stores/room-list/Interface.ts
  src/stores/room-list/RoomListStore.ts
  test/components/views/rooms/RoomList-test.tsx
Labels: T-Task

#9131 Implement GroupCallUtils
  src/utils/GroupCallUtils.ts
  test/utils/GroupCallUtils-test.ts
Labels: T-Task

#9161 Override the disambiguated profile colour in percy tests
  res/css/views/messages/_DisambiguatedProfile.pcss
Labels: T-Task

#9156 Cypress test stability improvements
  cypress/e2e/timeline/timeline.spec.ts
  cypress/support/settings.ts
Labels: T-Task

#9164 Fix inverted logic for showing UserWelcomeTop component
  src/components/structures/HomePage.tsx
Labels: T-Defect

#9157 Space panel accessibility improvements
  res/css/structures/_SpacePanel.pcss
  src/components/structures/AutoHideScrollbar.tsx
  src/components/structures/IndicatorScrollbar.tsx
  src/components/views/dialogs/AddExistingToSpaceDialog.tsx
  src/components/views/emojipicker/EmojiPicker.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
Labels: T-Defect

#8885 Implement MSC3819: Allowing widgets to send/receive to-device messages
  package.json
  src/stores/widgets/StopGapWidget.ts
  src/stores/widgets/StopGapWidgetDriver.ts
  src/widgets/CapabilityText.tsx
  test/stores/widgets/StopGapWidget-test.ts
  test/stores/widgets/StopGapWidgetDriver-test.ts
  test/stores/widgets/__snapshots__/StopGapWidgetDriver-test.ts.snap
  test/test-utils/test-utils.ts
  yarn.lock
Labels: T-Enhancement

#9061 Implement MSC3846: Allowing widgets to access TURN servers
  src/stores/widgets/StopGapWidgetDriver.ts
  test/stores/widgets/StopGapWidgetDriver-test.ts
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#9162 Fix invisible power levels tile when showing hidden events
  src/TextForEvent.tsx
  src/events/EventTileFactory.tsx
  test/events/EventTileFactory-test.ts
Labels: T-Defect

#9165 Upgrade deps
  yarn.lock
Labels: Dependencies, T-Task

#9167 Fix space panel subspace indentation going missing
  cypress/e2e/spaces/spaces.spec.ts
  res/css/structures/_HomePage.pcss
  res/css/structures/_SpacePanel.pcss
  src/components/structures/HomePage.tsx
Labels: T-Defect, X-Needs-Percy

#9151 Device manager - data fetching (PSG-637)
  src/components/views/settings/DevicesPanelEntry.tsx
  src/components/views/settings/devices/DeviceTile.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/components/views/settings/shared/SettingsSubsection.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/DeviceTile-test.tsx
  test/components/views/settings/devices/SelectableDeviceTile-test.tsx
  test/components/views/settings/devices/__snapshots__/DeviceTile-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/SelectableDeviceTile-test.tsx.snap
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Task

#9168 Device manager - extract device deletion logic into util
  src/components/views/settings/DevicesPanel.tsx
  src/components/views/settings/devices/deleteDevices.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/DevicesPanel-test.tsx
  test/components/views/settings/__snapshots__/DevicesPanel-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/deleteDevices-test.tsx.snap
  test/components/views/settings/devices/deleteDevices-test.tsx
Labels: T-Task

#9171 Update test snapshots for code landed on develop
  test/components/views/settings/__snapshots__/DevicesPanel-test.tsx.snap
Labels: T-Task

#9170 General cleanup of SettingController class
  src/settings/controllers/SettingController.ts
Labels: T-Task

#9172 Fix race condition in `AccountSettingsHandler` local echo
  src/settings/handlers/AccountSettingsHandler.ts
Labels: T-Task

#9163 Convert some Enzyme tests to RTL
  test/accessibility/RovingTabIndex-test.tsx
  test/utils/tooltipify-test.tsx
Labels: T-Task

#9173 Set Synapse log level to `DEBUG` for cypress tests temporarily
  cypress/plugins/synapsedocker/templates/consent/log.config
  cypress/plugins/synapsedocker/templates/default/log.config
Labels: T-Task

#9169 Device manager - device details section
  res/css/_components.pcss
  res/css/components/views/settings/devices/_DeviceDetails.pcss
  src/components/views/settings/DevicesPanelEntry.tsx
  src/components/views/settings/devices/DeviceDetails.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/DeviceDetails-test.tsx
  test/components/views/settings/devices/__snapshots__/DeviceDetails-test.tsx.snap
Labels: T-Task

#9155 Device manager - other sessions list (PSG-637)
  res/css/_components.pcss
  res/css/components/views/settings/devices/_FilteredDeviceList.pcss
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/FilteredDeviceList-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Enhancement

#9158 Device manager - device security recommendation card (PSG-637)
  res/css/_components.pcss
  res/css/components/views/settings/devices/_DeviceSecurityCard.pcss
  res/img/e2e/verified-deprecated.svg
  res/img/e2e/verified.svg
  res/img/e2e/warning-deprecated.svg
  res/img/e2e/warning.svg
  res/img/element-icons/settings/inactive.svg
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light/css/_light.pcss
  src/components/views/dialogs/security/SetupEncryptionDialog.tsx
  src/components/views/right_panel/EncryptionPanel.tsx
  src/components/views/settings/devices/DeviceSecurityCard.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/DeviceSecurityCard-test.tsx
  test/components/views/settings/devices/__snapshots__/DeviceSecurityCard-test.tsx.snap
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Task

#9174 Hide sticker picker for local rooms
  src/components/views/rooms/MessageComposer.tsx
  test/components/views/rooms/MessageComposer-test.tsx
Labels: T-Defect

#9176 Add even more stability to view source test case
  cypress/e2e/timeline/timeline.spec.ts
Labels: T-Task

#9175 Device manager - label devices as inactive (PSG-638)
  res/css/components/views/settings/devices/_DeviceTile.pcss
  src/components/views/settings/devices/DeviceSecurityCard.tsx
  src/components/views/settings/devices/DeviceTile.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/filter.ts
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/DeviceSecurityCard-test.tsx
  test/components/views/settings/devices/DeviceTile-test.tsx
  test/components/views/settings/devices/filter-test.ts
Labels: T-Enhancement

#9177 Add safety to the spotlight search dialog
  cypress/e2e/spotlight/spotlight.spec.ts
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
Labels: T-Defect

#9180 Hide sticker picker for local rooms (backport)
  src/components/views/rooms/MessageComposer.tsx
  test/components/views/rooms/MessageComposer-test.tsx
Labels: T-Defect

#9089 The Welcome Home Screen: Return Button
  cypress/e2e/user-onboarding/user-onboarding-new.ts
  cypress/e2e/user-onboarding/user-onboarding-old.ts
  res/css/_components.pcss
  res/css/views/user-onboarding/_UserOnboardingButton.pcss
  src/components/structures/LeftPanel.tsx
  src/components/structures/LoggedInView.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/components/views/user-onboarding/UserOnboardingButton.tsx
  src/components/views/user-onboarding/UserOnboardingPage.tsx
  src/hooks/useUserOnboardingContext.ts
  src/hooks/useUserOnboardingTasks.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Enhancement

#9179 Device manager - security recommendations section (PSG-639)
  res/css/_components.pcss
  res/css/components/views/settings/devices/_SecurityRecommendations.pcss
  src/components/views/settings/devices/DeviceSecurityCard.tsx
  src/components/views/settings/devices/DeviceTile.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/SecurityRecommendations.tsx
  src/components/views/settings/devices/filter.ts
  src/components/views/settings/devices/types.ts
  src/components/views/settings/devices/useOwnDevices.ts
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/DeviceSecurityCard-test.tsx
  test/components/views/settings/devices/SecurityRecommendations-test.tsx
  test/components/views/settings/devices/__snapshots__/SecurityRecommendations-test.tsx.snap
  test/components/views/settings/devices/filter-test.ts
Labels: T-Enhancement

#9185 Device manager - current session expandable details (PSG-644)
  res/css/_components.pcss
  res/css/components/views/settings/devices/_DeviceDetails.pcss
  res/css/components/views/settings/devices/_DeviceExpandDetailsButton.pcss
  res/css/views/elements/_AccessibleButton.pcss
  res/img/feather-customised/dropdown-arrow.svg
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/settings/devices/CurrentDeviceSection.tsx
  src/components/views/settings/devices/DeviceExpandDetailsButton.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/CurrentDeviceSection-test.tsx
  test/components/views/settings/devices/DeviceExpandDetailsButton-test.tsx
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceExpandDetailsButton-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Enhancement

#9186 Unit tests: make beacon events more specific
  test/components/views/beacon/BeaconStatus-test.tsx
  test/components/views/beacon/__snapshots__/BeaconStatus-test.tsx.snap
Labels: T-Task

#9190 Fix soft crash around room view store metrics
  src/stores/RoomViewStore.tsx
Labels: T-Defect

#9187 Device manager - add verification details to session details (PSG-644)
  res/css/components/views/settings/devices/_DeviceSecurityCard.pcss
  src/components/views/settings/devices/CurrentDeviceSection.tsx
  src/components/views/settings/devices/DeviceDetails.tsx
  src/components/views/settings/devices/DeviceVerificationStatusCard.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/DeviceDetails-test.tsx
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceDetails-test.tsx.snap
Labels: T-Enhancement

#9192 Disable some slash commands in LocalRoom
  src/SlashCommands.tsx
  test/SlashCommands-test.tsx
Labels: T-Defect

#9181 Device manager - device list filtering (PSG-648)
  res/css/components/views/settings/devices/_DeviceSecurityCard.pcss
  res/css/components/views/settings/devices/_FilteredDeviceList.pcss
  src/components/views/settings/devices/DeviceTile.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/SecurityRecommendations.tsx
  src/components/views/settings/devices/filter.ts
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/DevicesPanel-test.tsx
  test/components/views/settings/devices/FilteredDeviceList-test.tsx
  test/components/views/settings/devices/__snapshots__/FilteredDeviceList-test.tsx.snap
Labels: T-Enhancement

#9193 Backport Disable some slash commands in LocalRoom
  src/SlashCommands.tsx
  test/SlashCommands-test.tsx
Labels: T-Defect

#9191 Fix soft crash around space hierarchy changing between spaces
  src/components/structures/SpaceHierarchy.tsx
Labels: T-Defect

#9188 Device manager - expandable session details in device list (PSG-644)
  res/css/components/views/settings/devices/_DeviceDetails.pcss
  res/css/components/views/settings/devices/_FilteredDeviceList.pcss
  src/components/views/settings/devices/DeviceDetails.tsx
  src/components/views/settings/devices/DeviceExpandDetailsButton.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/FilteredDeviceList-test.tsx
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceDetails-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceExpandDetailsButton-test.tsx.snap
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Enhancement

#9195 Add gap between checkbox and text in report dialog
  res/css/views/elements/_LabelledCheckbox.pcss
Labels: Z-Community-PR, T-Defect

#9196 Attempt to fix `Failed to execute 'removeChild' on 'Node'`
  src/HtmlUtils.tsx
  src/components/views/elements/Tooltip.tsx
  test/components/views/elements/TooltipTarget-test.tsx
  test/components/views/elements/__snapshots__/TooltipTarget-test.tsx.snap
Labels: T-Defect

#9201 Wrap long space names
  res/css/structures/_SpacePanel.pcss
  res/css/structures/_SpaceRoomView.pcss
Labels: T-Defect

#9189 Fix url preview AXE and layout issue & add percy test
  cypress/e2e/timeline/timeline.spec.ts
  res/css/views/rooms/_LinkPreviewWidget.pcss
  src/components/views/rooms/LinkPreviewWidget.tsx
Labels: T-Defect, X-Needs-Percy

#9200 Fix context menu being opened when clicking message action bar buttons
  src/components/structures/ContextMenu.tsx
  src/components/views/emojipicker/EmojiPicker.tsx
  src/components/views/emojipicker/ReactionPicker.tsx
  src/components/views/messages/MessageActionBar.tsx
  test/components/views/context_menus/__snapshots__/SpaceContextMenu-test.tsx.snap
  test/components/views/messages/MessageActionBar-test.tsx
Labels: T-Defect

#8613 Release message right-click context menu out of labs
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Enhancement

#6518 Ignore unreads in low priority rooms in the space panel
  src/stores/notifications/SpaceNotificationState.ts
Labels: T-Enhancement

#9206 Avoid hardcoding branding in user onboarding
  cypress/e2e/spotlight/spotlight.spec.ts
  src/components/views/user-onboarding/UserOnboardingFeedback.tsx
  src/components/views/user-onboarding/UserOnboardingList.tsx
  src/components/views/user-onboarding/UserOnboardingTask.tsx
  src/hooks/useUserOnboardingTasks.ts
  src/i18n/strings/en_EN.json
Labels: X-Release-Blocker, T-Defect

#9194 Reduce amount of requests done by the onboarding task list
  cypress/e2e/user-onboarding/user-onboarding-new.ts
  src/components/views/user-onboarding/UserOnboardingButton.tsx
  src/hooks/useUserOnboardingContext.ts
  src/hooks/useUserOnboardingTasks.ts
Labels: T-Defect

#9212 Add static analysis for tsc --strict
  .github/workflows/static_analysis.yaml
  tsconfig.json
Labels: T-Task

#9214 Add backport automation
  .github/workflows/backport.yml
Labels: T-Task

#9217 Improve Cypress & Percy stability
  cypress/e2e/crypto/crypto.spec.ts
  cypress/e2e/register/register.spec.ts
Labels: T-Task, X-Needs-Percy

#9218 Reuse empty string & space string logic for event types in devtools
  src/components/views/dialogs/devtools/RoomState.tsx
Labels: T-Defect

#9219 Fix progress bar regression throughout the app
  src/components/structures/UploadBar.tsx
  src/components/views/elements/ProgressBar.tsx
  src/dispatcher/payloads/UploadPayload.ts
  src/hooks/useSmoothAnimation.ts
  test/components/views/elements/ProgressBar-test.tsx
Labels: X-Release-Blocker, T-Defect, backport staging

#9178 Add a larger buffer to useLatestResult's test
  test/hooks/useLatestResult-test.tsx
Labels: T-Task

#9222 Add missing space in SecurityRoomSettingsTab
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: Z-Community-PR, T-Defect

#9209 Make use of js-sdk roomNameGenerator to handle i18n for generated room names
  src/MatrixClientPeg.ts
  src/i18n/strings/en_EN.json
Labels: T-Defect

#9197 Device manager - device type and verification icons on device tile (PSG-637)
  res/css/_components.pcss
  res/css/components/views/settings/devices/_DeviceSecurityCard.pcss
  res/css/components/views/settings/devices/_DeviceType.pcss
  res/css/views/settings/_DevicesPanel.pcss
  res/img/element-icons/settings/unknown-device.svg
  src/components/views/settings/devices/DeviceSecurityCard.tsx
  src/components/views/settings/devices/DeviceTile.tsx
  src/components/views/settings/devices/DeviceType.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/__snapshots__/DevicesPanel-test.tsx.snap
  test/components/views/settings/devices/DeviceType-test.tsx
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceSecurityCard-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceTile-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/DeviceType-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/SecurityRecommendations-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/SelectableDeviceTile-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Enhancement

#9226 Device manager - updated dropdown style in filtered device list (PSG-689)
  res/css/_components.pcss
  res/css/components/views/elements/_FilterDropdown.pcss
  res/img/element-icons/roomlist/checkmark.svg
  src/components/views/elements/Dropdown.tsx
  src/components/views/elements/FilterDropdown.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/i18n/strings/en_EN.json
  test/components/views/elements/FilterDropdown-test.tsx
  test/components/views/elements/__snapshots__/FilterDropdown-test.tsx.snap
  test/components/views/settings/devices/FilteredDeviceList-test.tsx
Labels: T-Enhancement

#9227 Device manager - scroll to filtered list from security recommendations (PSG-640)
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/SecurityRecommendations.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  test/components/views/settings/devices/FilteredDeviceList-test.tsx
  test/components/views/settings/devices/SecurityRecommendations-test.tsx
  test/components/views/settings/devices/__snapshots__/SecurityRecommendations-test.tsx.snap
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
Labels: T-Enhancement
