Repository matrix-org/matrix-react-sdk, pull requests merged in 2022-07, with the labels that each got.

#8949 Location (live) share replies now provide a fallback content
  src/utils/Reply.ts
  test/Reply-test.ts
  test/__snapshots__/Reply-test.ts.snap
Labels: T-Defect

#8960 Include mx_EventTile_bubbleContainer in mx_EventTile
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Task

#8958 Move mx_EventTile_body out of mx_EventTile:not([data-layout=bubble])
  res/css/views/elements/_ReplyChain.scss
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Defect

#8955 Apply padding values to event tiles on MessageEditHistoryDialog with variables
  res/css/views/dialogs/_MessageEditHistoryDialog.scss
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Defect

#8961 Hopefully improve Cypress test reliability by increasing the default timeout
  cypress.json
Labels: T-Task

#8959 Enable ReplyChain text to be expanded on IRC layout
  res/css/views/rooms/_IRCLayout.scss
Labels: Z-Community-PR, T-Defect

#8931 Fix calls on homeservers without the unstable thirdparty endpoints
  src/CallHandler.tsx
  test/CallHandler-test.ts
Labels: Z-Community-PR, T-Defect

#8956 Apply mx_EventTile_isEditing .mx_MessageTimestamp globally
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Enhancement

#8939 Render HTML topics in rooms on space home
  src/components/structures/SpaceHierarchy.tsx
Labels: T-Enhancement

#8968 Consider cascading order of style rules on _EventTile.scss
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Task

#8971 Fix read receipts group position on TimelineCard in compact modern/group layout
  res/css/views/right_panel/_TimelineCard.scss
Labels: Z-Community-PR, T-Defect

#8881 Improve LinkPreviewWidget
  res/css/views/rooms/_LinkPreviewWidget.scss
  src/components/views/rooms/LinkPreviewWidget.tsx
Labels: Z-Community-PR, T-Enhancement

#8953 Tidy up _FilePanel.scss
  res/css/structures/_FilePanel.scss
Labels: Z-Community-PR, T-Task

#8977 Add top padding to EventTilePreview loader
  res/css/views/elements/_EventTilePreview.scss
  res/css/views/settings/_FontScalingPanel.scss
Labels: Z-Community-PR, T-Defect

#8974 Move mx_EventTile_contextual out of mx_EventTile:not([data-layout=bubble])
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Defect

#8967 Dismiss the search dialogue when starting a DM
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
Labels: T-Defect

#8970 Link to cypress tests rather than the old E2E tests
  README.md
Labels: T-Task

#8966 Fix resizing room topic
  res/css/views/settings/_ProfileSettings.scss
Labels: T-Defect

#8979 Fix clickable area of general event list summary toggle
  res/css/views/elements/_GenericEventListSummary.scss
  src/components/views/elements/GenericEventListSummary.tsx
Labels: Z-Community-PR, T-Defect

#8868 Improve style rules for thread summary
  res/css/_common.scss
  res/css/views/right_panel/_ThreadPanel.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_ThreadSummary.scss
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/ThreadSummary.tsx
Labels: Z-Community-PR, T-Task

#8764 Delabs `Show current avatar and name for users in message history`
  cypress/global.d.ts
  cypress/integration/14-timeline/timeline.spec.ts
  cypress/support/client.ts
  cypress/support/settings.ts
  src/components/views/avatars/MemberAvatar.tsx
  src/components/views/messages/SenderProfile.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/settings/Settings.tsx
Labels: T-Enhancement

#8973 Move mx_EventTile_msgOption out of mx_EventTile:not([data-layout=bubble])
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_IRCLayout.scss
Labels: Z-Community-PR, T-Task

#8964 Attempt to set the language when setting up Cypress tests
  cypress/support/login.ts
Labels: T-Task

#8965 Improve mx_MatrixChat_useCompactLayout on _EventTile.scss
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Defect

#8941 Move mx_EventTile_continuation out of mx_EventTile:not([data-layout=bubble])
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Task

#8985 Add bidirectonal isolation for pills
  src/components/views/elements/Pill.tsx
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
Labels: Z-Community-PR, T-Enhancement

#8844 Improve security room settings tab style rules
  res/css/views/settings/tabs/room/_SecurityRoomSettingsTab.scss
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
Labels: Z-Community-PR, T-Defect

#8950 Fix font size of MessageTimestamp on TimelineCard
  res/css/views/right_panel/_TimelineCard.scss
Labels: Z-Community-PR, T-Defect

#8987 Fix the size of the clickable area of images
  res/css/views/rooms/_EventTile.scss
Labels: T-Defect

#8989 Adjust encryption copy when creating a video room
  src/components/views/dialogs/CreateRoomDialog.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#8992 Remove 100% min-width hack from mx_GenericEventListSummary[data-layout=bubble][data-expanded=false]
  res/css/views/elements/_GenericEventListSummary.scss
  res/css/views/rooms/_EventBubbleTile.scss
Labels: Z-Community-PR, T-Defect

#8944 Stop using :not() pseudo class for mx_GenericEventListSummary
  res/css/views/right_panel/_TimelineCard.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_IRCLayout.scss
Labels: Z-Community-PR, T-Defect

#8976 Move mx_MessageTimestamp out of mx_EventTile:not([data-layout=bubble])
  res/css/structures/_FilePanel.scss
  res/css/views/dialogs/_MessageEditHistoryDialog.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_IRCLayout.scss
Labels: Z-Community-PR, T-Defect

#8826 Fix headings margin on security user settings tab
  res/css/views/settings/tabs/_SettingsTab.scss
  res/css/views/settings/tabs/user/_SecurityUserSettingsTab.scss
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
Labels: Z-Community-PR, T-Defect

#8963 Task - replace img icons with svg components
  res/css/_components.scss
  res/css/components/views/messages/shared/_MediaProcessingError.scss
  src/components/structures/BackdropPanel.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/dialogs/UploadConfirmDialog.tsx
  src/components/views/messages/MAudioBody.tsx
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MVideoBody.tsx
  src/components/views/messages/MVoiceMessageBody.tsx
  src/components/views/messages/shared/MediaProcessingError.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  test/components/views/messages/shared/MediaProcessingError-test.tsx
  test/components/views/messages/shared/__snapshots__/MediaProcessingError-test.tsx.snap
Labels: T-Task

#8978 Don't show the same user twice in Spotlight
  cypress/integration/12-spotlight/spotlight.spec.ts
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
Labels: T-Defect

#8962 Live location share - tiles without tile server (PSG-591)
  res/css/components/views/beacon/_OwnBeaconStatus.scss
  res/css/components/views/location/_MapError.scss
  res/css/components/views/messages/_MBeaconBody.scss
  src/components/views/beacon/BeaconViewDialog.tsx
  src/components/views/location/MapError.tsx
  src/components/views/location/MapFallback.tsx
  src/components/views/messages/MBeaconBody.tsx
  test/components/views/location/LocationPicker-test.tsx
  test/components/views/location/MapError-test.tsx
  test/components/views/location/__snapshots__/MapError-test.tsx.snap
  test/components/views/messages/MBeaconBody-test.tsx
  test/components/views/messages/__snapshots__/MBeaconBody-test.tsx.snap
Labels: T-Enhancement

#9000 Ensure timestamp on generic event list summary is not hidden from TimelineCard
  res/css/views/right_panel/_TimelineCard.scss
Labels: Z-Community-PR, T-Defect

#8997 Move style rules of EventTile on hover out of mx_EventTile:not([data-layout=bubble])
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_IRCLayout.scss
Labels: Z-Community-PR, T-Task

#8999 Remove dead AddressSelector code
  res/css/_components.scss
  res/css/views/elements/_AddressSelector.scss
  res/css/views/elements/_AddressTile.scss
  res/themes/legacy-dark/css/_legacy-dark.scss
  res/themes/legacy-light/css/_legacy-light.scss
  src/components/views/elements/AddressSelector.tsx
  src/components/views/elements/AddressTile.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#9001 Specify spacing around EventTileBubble for each layout
  res/css/views/messages/_EventTileBubble.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_IRCLayout.scss
Labels: Z-Community-PR, T-Defect

#9005 Improve _GenericEventListSummary.scss
  res/css/views/elements/_GenericEventListSummary.scss
Labels: Z-Community-PR, T-Enhancement

#9009 Fix lost padding of event tile info line
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Defect

#9018 Replace MSC3244 support with in-client room version checking
  src/components/views/dialogs/CreateRoomDialog.tsx
  src/components/views/dialogs/CreateSubspaceDialog.tsx
  src/components/views/settings/JoinRuleSettings.tsx
  src/createRoom.ts
  src/stores/spaces/SpaceStore.ts
  src/utils/PreferredRoomVersions.ts
  test/PreferredRoomVersions-test.ts
Labels: T-Task

#9019 Remove padding from event info line for hidden events on ThreadView
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Defect

#9014 Fix Shortcut prompt for Search showing in minimized Roomlist
  res/css/structures/_LeftPanel.scss
  res/css/structures/_RoomSearch.scss
  src/components/structures/LeftPanel.tsx
  src/components/structures/RoomSearch.tsx
Labels: T-Defect

#9015 Re-add margin to tiles based on EventTileBubble
  res/css/views/messages/_CreateEvent.scss
  res/css/views/messages/_EventTileBubble.scss
  res/css/views/messages/_MJitsiWidgetEvent.scss
  res/css/views/messages/_common_CryptoEvent.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_HistoryTile.scss
Labels: Z-Community-PR, T-Defect

#9007 Update cypress github action
  .github/workflows/cypress.yaml
Labels: T-Task

#9020 Move style declarations out of :not([data-layout=bubble]) in ThreadView
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Task

#9022 Unbreak URL preview for formatted links with tooltips
  src/components/views/messages/TextualBody.tsx
Labels: T-Defect

#9027 Added trim to ignore whitespaces in email check
  src/components/views/auth/RegistrationForm.tsx
Labels: T-Enhancement

#9032 Enable search strings highlight on bubble layout
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Defect

#9023 Add LocalRoom model / utils
  src/models/LocalRoom.ts
  src/stores/room-list/filters/VisibilityProvider.ts
  src/utils/local-room.ts
  test/models/LocalRoom-test.ts
  test/stores/room-list/filters/VisibilityProvider-test.ts
  test/utils/local-room-test.ts
Labels: T-Task

#8975 Remove obsolete opacity value for E2E icons
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Task

#9035 Remove dead code
  src/HtmlUtils.tsx
  src/Keyboard.ts
  src/RoomNotifs.ts
  src/Rooms.ts
  src/ScalarMessaging.ts
  src/UserAddress.ts
  src/components/structures/ContextMenu.tsx
  src/components/views/dialogs/AnalyticsLearnMoreDialog.tsx
  src/components/views/location/shareLocation.ts
  src/components/views/rooms/CollapsibleButton.tsx
  src/components/views/settings/KeyboardShortcut.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  src/effects/ICanvasEffect.ts
  src/events/forward/types.ts
  src/events/types.ts
  src/linkify-matrix.ts
  src/notifications/ContentRules.ts
  src/settings/SettingsStore.ts
  src/stores/room-list/previews/utils.ts
  src/utils/Receipt.ts
  src/utils/drawable.ts
  src/utils/iterables.ts
  src/utils/maps.ts
  src/utils/units.ts
  test/components/views/location/LocationButton-test.tsx
  test/test-utils/threads.ts
  test/utils/iterables-test.ts
  test/utils/maps-test.ts
Labels: T-Task

#9034 Remove `mock` from `KeyboardShortcuts.ts`
  src/accessibility/KeyboardShortcuts.ts
  test/accessibility/KeyboardShortcutUtils-test.ts
Labels: T-Task

#9024 Add additional metadata to feedback submitted through spotlight dialog
  src/components/views/dialogs/FeedbackDialog.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
Labels: T-Task

#9039 Update cypress.md with new Cypress 10 paths
  docs/cypress.md
Labels: T-Task

#9003 Correct accessibility labels for unread rooms in spotlight
  src/components/views/dialogs/ForwardDialog.tsx
  src/components/views/dialogs/spotlight/PublicRoomResultDetails.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/rooms/RecentlyViewedButton.tsx
  src/components/views/rooms/RoomContextDetails.tsx
  src/i18n/strings/en_EN.json
  src/utils/i18n-helpers.ts
Labels: T-Defect

#9012 add spaces to TileErrorBoundary
  src/components/views/messages/TileErrorBoundary.tsx
Labels: Z-Community-PR, T-Enhancement

#9041 Fix event list summaries including invalid events
  src/components/structures/MessagePanel.tsx
  src/utils/permalinks/Permalinks.ts
Labels: T-Defect

#9028 Fix URL previews causing messages to become unrenderable
  src/components/views/rooms/LinkPreviewWidget.tsx
Labels: X-Release-Blocker, T-Defect

#9043 Don't unnecessarily persist the host signup dialog
  res/css/views/dialogs/_HostSignupDialog.scss
  src/components/views/dialogs/HostSignupDialog.tsx
Labels: T-Defect

#9046 Add a basic PR checklist for all PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: T-Task

#9030 Add space for the stroke on message editor on IRC layout
  res/css/views/rooms/_EditMessageComposer.scss
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Defect

#9042 Fix pinned messages not re-linkifying on edit
  src/HtmlUtils.tsx
  src/components/structures/RightPanel.tsx
  src/components/views/messages/IBodyProps.ts
  src/components/views/messages/MessageEvent.tsx
  src/components/views/messages/TextualBody.tsx
  src/components/views/right_panel/PinnedMessagesCard.tsx
  src/components/views/rooms/PinnedEventTile.tsx
  src/events/EventTileFactory.tsx
  test/components/views/right_panel/PinnedMessagesCard-test.tsx
Labels: T-Defect

#9045 Hide screenshare button in video rooms on Desktop
  src/BasePlatform.ts
  src/utils/WidgetUtils.ts
  test/createRoom-test.ts
Labels: T-Enhancement

#8907 Improve spotlight accessibility by adding context menus
  res/css/_components.scss
  res/css/views/context_menus/_RoomGeneralContextMenu.scss
  res/css/views/context_menus/_RoomNotificationContextMenu.scss
  res/css/views/dialogs/_SpotlightDialog.scss
  src/components/views/context_menus/RoomGeneralContextMenu.tsx
  src/components/views/context_menus/RoomNotificationContextMenu.tsx
  src/components/views/dialogs/spotlight/Option.tsx
  src/components/views/dialogs/spotlight/RoomResultContextMenus.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/rooms/RoomTile.tsx
  src/hooks/useRoomNotificationState.ts
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#8994 Move mx_EventTile_info out of mx_EventTile:not([data-layout=bubble])
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_IRCLayout.scss
Labels: Z-Community-PR, T-Task

#8993 Manage style rules of ReadReceiptGroup position on one file
  res/css/views/right_panel/_TimelineCard.scss
  res/css/views/rooms/_EventBubbleTile.scss
  res/css/views/rooms/_EventTile.scss
  res/css/views/rooms/_IRCLayout.scss
  res/css/views/rooms/_ReadReceiptGroup.scss
Labels: Z-Community-PR, T-Task

#9021 Remove :not() pseudo class from mx_EventTile_line:hover of ThreadsList
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Task

#9050 Fix warning about 'start' value usage
  res/css/views/dialogs/_SpotlightDialog.scss
Labels: Z-Community-PR, T-Task

#8980 Move &.mx_EventTile_isEditing and &.mx_EventTile_selected out of mx_EventTile:not([data-layout=bubble])
  res/css/views/rooms/_EventTile.scss
Labels: Z-Community-PR, T-Task

#9031 Improve _FilePanel.scss
  res/css/structures/_FilePanel.scss
Labels: Z-Community-PR, T-Enhancement

#9038 Use doMaybeLocalRoomAction
  src/ContentMessages.ts
  src/components/views/elements/PollCreateDialog.tsx
  src/components/views/location/shareLocation.ts
  src/components/views/rooms/SendMessageComposer.tsx
  src/components/views/rooms/VoiceRecordComposerTile.tsx
  src/stores/OwnBeaconStore.ts
  test/ContentMessages-test.ts
  test/MatrixClientPeg-test.ts
  test/components/views/location/shareLocation-test.ts
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/components/views/rooms/VoiceRecordComposerTile-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Task

#9048 Live location share - labels update: "stop sharing" -> "stop" (PSG-618)
  src/components/views/beacon/RoomLiveShareWarning.tsx
  src/i18n/strings/en_EN.json
  test/components/views/beacon/__snapshots__/RoomLiveShareWarning-test.tsx.snap
Labels: T-Task

#9047 Live location share - handle insufficient permissions in location sharing (PSG-610)
  src/components/views/dialogs/QuestionDialog.tsx
  src/components/views/location/shareLocation.ts
  src/i18n/strings/en_EN.json
  test/components/views/location/LocationShareMenu-test.tsx
Labels: T-Enhancement

#8984 Implement Use Case Selection screen
  cypress/e2e/1-register/register.spec.ts
  cypress/e2e/12-spotlight/spotlight.spec.ts
  package.json
  res/css/_components.scss
  res/css/structures/_SplashPage.scss
  res/css/views/elements/_UseCaseSelection.scss
  res/css/views/elements/_UseCaseSelectionButton.scss
  res/img/element-icons/chat-bubble.svg
  res/img/element-icons/group-members.svg
  res/img/element-icons/view-community.svg
  res/img/globe.svg
  res/img/noise.png
  res/themes/dark/css/_dark.scss
  src/PosthogTrackers.ts
  src/Views.ts
  src/components/structures/MatrixChat.tsx
  src/components/structures/SplashPage.tsx
  src/components/views/elements/UseCaseSelection.tsx
  src/components/views/elements/UseCaseSelectionButton.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/enums/UseCase.tsx
  test/end-to-end-tests/src/usecases/signup.ts
  yarn.lock
Labels: T-Enhancement

#9055 Prefer using the canonical alias in spotlight search
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/dispatcher/payloads/ViewRoomPayload.ts
Labels: T-Defect

#9059 Prefer using the canonical alias in spotlight search
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/dispatcher/payloads/ViewRoomPayload.ts
Labels: T-Defect

#8842 Starred_Messages_Feature/Outreachy
  res/css/views/messages/_MessageActionBar.pcss
  res/img/element-icons/room/message-bar/star.svg
  src/components/views/messages/MessageActionBar.tsx
  src/hooks/useFavouriteMessages.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/views/messages/MessageActionBar-test.tsx
Labels: T-Enhancement

#9037 Improve clickability of "collapse" link button on bubble layout
  cypress/e2e/14-timeline/timeline.spec.ts
  res/css/views/messages/_MessageActionBar.pcss
Labels: Z-Community-PR, T-Enhancement

#9063 Re-add inline start padding to EventTile_line of GenericEventListSummary
  cypress/e2e/14-timeline/timeline.spec.ts
  res/css/views/rooms/_EventTile.pcss
Labels: Z-Community-PR, T-Defect

#9068 Improve clickability of view source event toggle button
  cypress/e2e/14-timeline/timeline.spec.ts
  res/css/views/messages/_MessageActionBar.pcss
  res/css/views/messages/_ViewSourceEvent.pcss
Labels: Z-Community-PR, T-Enhancement

#9051 Live location share - focus on user location on list item click (PSG-609)
  res/css/components/views/beacon/_BeaconListItem.pcss
  src/components/views/beacon/BeaconListItem.tsx
  src/components/views/beacon/BeaconViewDialog.tsx
  src/components/views/beacon/DialogSidebar.tsx
  src/components/views/beacon/OwnBeaconStatus.tsx
  src/components/views/location/Map.tsx
  src/components/views/messages/MBeaconBody.tsx
  src/utils/NativeEventUtils.ts
  src/utils/location/useMap.ts
  test/components/views/beacon/BeaconListItem-test.tsx
  test/components/views/beacon/BeaconViewDialog-test.tsx
  test/components/views/beacon/DialogSidebar-test.tsx
  test/components/views/beacon/__snapshots__/BeaconListItem-test.tsx.snap
  test/components/views/beacon/__snapshots__/DialogSidebar-test.tsx.snap
  test/test-utils/beacon.ts
  test/test-utils/utilities.ts
Labels: T-Enhancement

#8982 Move Lazy Loading tests from Puppeteer to Cypress
  cypress/e2e/lazy-loading/lazy-loading.spec.ts
  cypress/support/bot.ts
  cypress/support/client.ts
  cypress/support/e2e.ts
  cypress/support/network.ts
  cypress/support/timeline.ts
  package.json
  test/end-to-end-tests/src/rest/consent.ts
  test/end-to-end-tests/src/rest/creator.ts
  test/end-to-end-tests/src/rest/multi.ts
  test/end-to-end-tests/src/rest/room.ts
  test/end-to-end-tests/src/rest/session.ts
  test/end-to-end-tests/src/scenario.ts
  test/end-to-end-tests/src/scenarios/lazy-loading.ts
  test/end-to-end-tests/src/session.ts
  test/end-to-end-tests/src/usecases/memberlist.ts
  test/end-to-end-tests/src/usecases/timeline.ts
  test/end-to-end-tests/src/util.ts
  test/end-to-end-tests/start.ts
  yarn.lock
Labels: T-Task

#9071 Live location sharing - don't trigger unread counts for beacon location events
  src/Unread.ts
  test/Unread-test.ts
Labels: T-Enhancement

#9074 Update lockfile per yarn's decision
  yarn.lock
Labels: T-Task

#9076 Update matrix-org/pr-details-actio to 1.2
  .github/workflows/cypress.yaml
  .github/workflows/netlify.yaml
Labels: T-Task

#9077 Remove obsolete crypto e2e test scenario
  test/end-to-end-tests/src/scenario.ts
  test/end-to-end-tests/src/scenarios/e2e-encryption.ts
Labels: T-Task

#9078 Wire local room logic
  src/Avatar.ts
  src/components/structures/MatrixChat.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/messages/EncryptionEvent.tsx
  src/i18n/strings/en_EN.json
  src/stores/TypingStore.ts
  src/stores/room-list/filters/VisibilityProvider.ts
  src/utils/localRoom/isLocalRoom.ts
  test/Avatar-test.ts
  test/components/views/dialogs/SpotlightDialog-test.tsx
  test/components/views/messages/EncryptionEvent-test.tsx
  test/stores/TypingStore-test.ts
  test/test-utils/test-utils.ts
  test/utils/localRoom/isLocalRoom-test.ts
Labels: T-Task

#9062 Fix wrong buttons being used when exploring public rooms
  cypress/e2e/12-spotlight/spotlight.spec.ts
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
Labels: T-Defect

#9080 Extract RoomStatusBarUnsentMessages
  res/css/structures/_RoomStatusBar.pcss
  src/components/structures/RoomStatusBar.tsx
  src/components/structures/RoomStatusBarUnsentMessages.tsx
  test/components/structures/RoomStatusBarUnsentMessages-test.tsx
Labels: T-Task

#8998 Use "frequently used emojis" for autocompletion in composer
  src/autocomplete/EmojiProvider.tsx
  test/autocomplete/EmojiProvider-test.ts
Labels: Z-Community-PR, T-Enhancement

#9086 Starred_Messages_Feature_Contd_II/Outreachy
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomSublist.tsx
  src/i18n/strings/en_EN.json
  src/stores/room-list/models.ts
Labels: T-Enhancement

#9075 Prevent email verification from overriding existing sessions
  src/components/structures/auth/Registration.tsx
Labels: T-Defect

#9079 Error resistant data dump from `TimelinePanel`
  src/components/structures/TimelinePanel.tsx
Labels: T-Task

#9081 Add e2e tests for pin drop location share
  cypress/e2e/16-location/location.spec.ts
Labels: T-Task

#9084 Prepare utils for local rooms
  src/CallHandler.tsx
  src/VoipUserMapper.ts
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/createRoom.ts
  src/utils/direct-messages.ts
  src/utils/dm/createDmLocalRoom.ts
  src/utils/dm/findDMForUser.ts
  src/utils/dm/findDMRoom.ts
  src/utils/dm/startDm.ts
  src/utils/local-room.ts
  src/utils/localRoom/isRoomReady.ts
  src/verification.ts
  test/utils/direct-messages-test.ts
  test/utils/dm/createDmLocalRoom-test.ts
  test/utils/dm/findDMForUser-test.ts
  test/utils/dm/findDMRoom-test.ts
  test/utils/local-room-test.ts
  test/utils/localRoom/isRoomReady-test.ts
Labels: T-Task

#9058 Align the right edge of info tile lines with normal ones on IRC layout
  cypress/e2e/14-timeline/timeline.spec.ts
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/_IRCLayout.pcss
Labels: Z-Community-PR, T-Defect

#9094 Use `flex-end` instead of `end`
  res/css/views/elements/_UseCaseSelection.pcss
Labels: T-Task

#9088 Replace mask-images with svg components in MessageActionBar
  res/css/structures/_MatrixChat.pcss
  res/css/views/messages/_MessageActionBar.pcss
  res/css/views/right_panel/_PinnedMessagesCard.pcss
  res/css/views/rooms/_RoomSublist.pcss
  res/img/download.svg
  res/img/element-icons/collapse-message.svg
  res/img/element-icons/context-menu.svg
  res/img/element-icons/expand-message.svg
  res/img/element-icons/link.svg
  res/img/element-icons/message/thread.svg
  res/img/element-icons/retry.svg
  res/img/element-icons/room/message-bar/edit.svg
  res/img/element-icons/room/message-bar/emoji.svg
  res/img/element-icons/room/message-bar/reply.svg
  res/img/element-icons/room/message-bar/star.svg
  res/img/element-icons/trashcan.svg
  res/img/element-icons/view-in-room.svg
  src/components/views/messages/DownloadActionButton.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/right_panel/PinnedMessagesCard.tsx
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#9095 Show a back button when viewing a space member
  cypress/e2e/6-spaces/spaces.spec.ts
  cypress/e2e/right-panel/right-panel.spec.ts
  cypress/support/views.ts
  src/components/structures/SpaceRoomView.tsx
Labels: T-Defect

#9097 Support for sending voice messages as replies and in threads
  cypress/e2e/14-timeline/timeline.spec.ts
  cypress/e2e/5-threads/threads.spec.ts
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/VoiceRecordComposerTile.tsx
Labels: T-Enhancement

#9087 Unbreak in-app permalink tooltips
  src/utils/tooltipify.tsx
  test/utils/tooltipify-test.tsx
Labels: T-Defect

#9100 Unbreak in-app permalink tooltips
  src/utils/tooltipify.tsx
  test/utils/tooltipify-test.tsx
Labels: T-Defect

#9102 Fix avatars in percy not having the right border radius
  res/css/views/avatars/_BaseAvatar.pcss
Labels: T-Task, X-Needs-Percy

#9105 Skip flaky e2e test
  cypress/e2e/14-timeline/timeline.spec.ts
Labels: T-Task

#9101 Fix replying using chat effect commands
  src/SlashCommands.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/editor/commands.tsx
Labels: T-Defect

#9110 Use default styling on nested numbered lists due to MD being sensitive
  res/css/views/rooms/_EventTile.pcss
Labels: T-Defect

#9098 Live location share: leave maximised map open when beacons expire (PSF-615)
  res/css/components/views/beacon/_DialogSidebar.pcss
  src/components/views/beacon/BeaconViewDialog.tsx
  src/components/views/beacon/DialogOwnBeaconStatus.tsx
  src/components/views/beacon/DialogSidebar.tsx
  test/components/views/beacon/BeaconViewDialog-test.tsx
  test/components/views/beacon/__snapshots__/BeaconViewDialog-test.tsx.snap
  test/components/views/beacon/__snapshots__/DialogSidebar-test.tsx.snap
Labels: T-Enhancement

#9092 Use stable prefixes MSC3827
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
  src/components/views/spaces/SpaceSettingsVisibilityTab.tsx
  src/hooks/usePublicRoomDirectory.ts
Labels: T-Task

#8604 Add support for disabling spell checking
  res/css/views/settings/tabs/_SettingsTab.pcss
  res/css/views/settings/tabs/user/_GeneralUserSettingsTab.pcss
  src/BasePlatform.ts
  src/components/views/elements/Dropdown.tsx
  src/components/views/elements/SpellCheckLanguagesDropdown.tsx
  src/components/views/elements/ToggleSwitch.tsx
  src/components/views/settings/SpellCheckSettings.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#9060 Add support for `EventTarget` to `useEventEmitter()`
  src/hooks/useEventEmitter.ts
  test/test-utils/test-utils.ts
Labels: T-Task

#9114 Make sonar happier
  src/IdentityAuthClient.tsx
  src/SlashCommands.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/dialogs/devtools/VerificationExplorer.tsx
  src/components/views/elements/UseCaseSelection.tsx
  src/utils/IdentityServerUtils.ts
Labels: T-Task

#9104 Port remaining Puppeteer tests over to Cypress
  .github/workflows/end-to-end-tests.yaml
  cypress/e2e/toasts/analytics-toast.ts
  package.json
  scripts/ci/prepare-end-to-end-tests.sh
  scripts/ci/run-end-to-end-tests.sh
  src/Lifecycle.ts
  src/components/structures/MatrixChat.tsx
  test/end-to-end-tests/.gitignore
  test/end-to-end-tests/README.md
  test/end-to-end-tests/TODO.md
  test/end-to-end-tests/Windows.md
  test/end-to-end-tests/element/.gitignore
  test/end-to-end-tests/element/config-template/config.json
  test/end-to-end-tests/element/install-webserver.sh
  test/end-to-end-tests/element/install.sh
  test/end-to-end-tests/element/start.sh
  test/end-to-end-tests/element/stop.sh
  test/end-to-end-tests/has-custom-app.js
  test/end-to-end-tests/install.sh
  test/end-to-end-tests/package.json
  test/end-to-end-tests/pick-synapse-log-file.js
  test/end-to-end-tests/run.sh
  test/end-to-end-tests/src/@types/global.d.ts
  test/end-to-end-tests/src/logbuffer.ts
  test/end-to-end-tests/src/logger.ts
  test/end-to-end-tests/src/scenario.ts
  test/end-to-end-tests/src/scenarios/README.md
  test/end-to-end-tests/src/scenarios/toast.ts
  test/end-to-end-tests/src/session.ts
  test/end-to-end-tests/src/usecases/README.md
  test/end-to-end-tests/src/usecases/accept-invite.ts
  test/end-to-end-tests/src/usecases/create-room.ts
  test/end-to-end-tests/src/usecases/dialog.ts
  test/end-to-end-tests/src/usecases/invite.ts
  test/end-to-end-tests/src/usecases/join.ts
  test/end-to-end-tests/src/usecases/login.ts
  test/end-to-end-tests/src/usecases/memberlist.ts
  test/end-to-end-tests/src/usecases/rightpanel.ts
  test/end-to-end-tests/src/usecases/room-settings.ts
  test/end-to-end-tests/src/usecases/security.ts
  test/end-to-end-tests/src/usecases/select-room.ts
  test/end-to-end-tests/src/usecases/send-message.ts
  test/end-to-end-tests/src/usecases/send-sticker.ts
  test/end-to-end-tests/src/usecases/settings.ts
  test/end-to-end-tests/src/usecases/signup.ts
  test/end-to-end-tests/src/usecases/timeline.ts
  test/end-to-end-tests/src/usecases/toasts.ts
  test/end-to-end-tests/src/usecases/verify.ts
  test/end-to-end-tests/src/util.ts
  test/end-to-end-tests/start.ts
  test/end-to-end-tests/synapse/.gitignore
  test/end-to-end-tests/synapse/config-templates/consent/homeserver.yaml
  test/end-to-end-tests/synapse/config-templates/consent/res/templates/privacy/en/1.0.html
  test/end-to-end-tests/synapse/config-templates/consent/res/templates/privacy/en/success.html
  test/end-to-end-tests/synapse/getcfg.sh
  test/end-to-end-tests/synapse/install.sh
  test/end-to-end-tests/synapse/start.sh
  test/end-to-end-tests/synapse/stop.sh
  test/end-to-end-tests/tsconfig.json
  test/end-to-end-tests/yarn.lock
Labels: T-Task

#9115 Peek into world-readable rooms from spotlight
  cypress/e2e/12-spotlight/spotlight.spec.ts
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
Labels: T-Defect
