Repository matrix-org/matrix-react-sdk, pull requests merged in 2023-04, with the labels that each got.

#10364 Show room create icon if "UIComponent.roomCreation" is enabled
  src/components/views/rooms/RoomList.tsx
  test/components/views/rooms/RoomList-test.tsx
Labels: Z-Community-PR, T-Enhancement

#10486 Properly generate mentions when editing a reply with MSC3952
  src/components/views/rooms/EditMessageComposer.tsx
  test/components/views/rooms/EditMessageComposer-test.tsx
  test/test-utils/room.ts
Labels: T-Defect

#10480 Use Cypress Testing Library - `editing.spec.ts`
  cypress/e2e/editing/editing.spec.ts
Labels: Z-Community-PR, T-Task

#10455 Apply `strictNullChecks` to `src/utils/*!exportUtils` (#10455
  src/components/structures/InteractiveAuth.tsx
  src/components/views/dialogs/InteractiveAuthDialog.tsx
  src/utils/AutoDiscoveryUtils.tsx
  src/utils/DMRoomMap.ts
  src/utils/IdentityServerUtils.ts
  src/utils/MediaEventHelper.ts
  src/utils/TypeUtils.ts
  src/utils/UserInteractiveAuth.ts
  src/utils/WidgetUtils.ts
  src/utils/leave-behaviour.ts
  src/utils/location/map.ts
  src/utils/location/parseGeoUri.ts
  src/utils/stringOrderField.ts
  src/utils/threepids.ts
  test/test-utils/test-utils.ts
  test/utils/DMRoomMap-test.ts
  test/utils/location/map-test.ts
  test/utils/location/parseGeoUri-test.ts
Labels: T-Task

#10482 Check kiwi_enable value for '1'-ness, not presence
  .github/workflows/cypress.yaml
Labels: T-Task

#10479 Added auto focus to Github URL on opening of debug logs modal
  src/components/views/dialogs/BugReportDialog.tsx
Labels: Z-Community-PR, T-Defect

#10448 Style mentions as pills in rich text editor
  res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
Labels: T-Enhancement

#10491 Restore `createRoom.canEncryptToAllUsers` behaviour
  src/createRoom.ts
  test/createRoom-test.ts
Labels: T-Task

#10429 Fix a FilePanel test to have Percy take a snapshot of file tiles on the panel
  cypress/e2e/right-panel/file-panel.spec.ts
Labels: Z-Community-PR, T-Task, X-Needs-Percy

#10500 Remove orphaned `GenericError` class
  src/utils/error.ts
Labels: T-Task

#10471 Use Cypress Testing Library - `timeline.spec.ts`
  cypress/e2e/timeline/timeline.spec.ts
Labels: Z-Community-PR, T-Task

#10451 Remove an obsolete style block related to highlighting from `_IRCLayout.pcss`
  res/css/views/rooms/_IRCLayout.pcss
Labels: Z-Community-PR, T-Task

#10504 Conform more of the codebase to `strictNullChecks` (#10504
  src/LegacyCallHandler.tsx
  src/components/views/dialogs/AddExistingToSpaceDialog.tsx
  src/components/views/dialogs/ConfirmAndWaitRedactDialog.tsx
  src/components/views/dialogs/ExportDialog.tsx
  src/components/views/dialogs/IncomingSasDialog.tsx
  src/components/views/dialogs/LeaveSpaceDialog.tsx
  src/components/views/dialogs/security/CreateCrossSigningDialog.tsx
  src/components/views/messages/MPollBody.tsx
  src/components/views/right_panel/PinnedMessagesCard.tsx
  src/components/views/rooms/MemberList.tsx
  src/stores/right-panel/RightPanelStoreIPanelState.ts
  src/utils/beacon/useBeacon.ts
  src/utils/permalinks/Permalinks.ts
  src/voice-broadcast/hooks/useHasRoomLiveVoiceBroadcast.ts
  test/LegacyCallHandler-test.ts
  test/components/views/settings/tabs/room/NotificationSettingsTab-test.tsx
  test/stores/widgets/StopGapWidgetDriver-test.ts
  test/utils/DMRoomMap-test.ts
Labels: T-Task

#10499 Allow editing with RTE to overflow for autocomplete visibility
  res/css/views/rooms/_EventTile.pcss
Labels: T-Defect

#10503 Update rte autocomplete styling
  res/css/views/rooms/wysiwyg_composer/_SendWysiwygComposer.pcss
  res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
  src/components/views/rooms/wysiwyg_composer/components/WysiwygAutocomplete.tsx
Labels: T-Enhancement

#10427 Quick settings: Change the copy / labels on the options
  cypress/e2e/sliding-sync/sliding-sync.ts
  src/components/views/context_menus/RoomNotificationContextMenu.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#10501 Unit test `AutoDiscoveryUtils.buildValidatedConfigFromDiscovery`
  test/utils/AutoDiscoveryUtils-test.tsx
Labels: T-Task

#10502 Highlight event when any version triggered a highlight
  res/css/views/rooms/_EventTile.pcss
  src/components/views/rooms/EventTile.tsx
  test/components/views/rooms/EventTile-test.tsx
Labels: T-Defect

#10232 Fix spacing of headings of integration manager on General settings tab
  cypress/e2e/settings/set-integration-manager.spec.ts
  res/css/views/settings/_SetIntegrationManager.pcss
Labels: Z-Community-PR, T-Defect, X-Needs-Percy

#10511 Use Cypress Testing Library - `composer.spec.ts`
  cypress/e2e/composer/composer.spec.ts
Labels: Z-Community-PR, T-Task

#10472 Check profiles before starting a DM
  src/components/views/dialogs/AskInviteAnywayDialog.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/i18n/strings/en_EN.json
  src/stores/UserProfilesStore.ts
  src/utils/MultiInviter.ts
  test/components/views/dialogs/InviteDialog-test.tsx
  test/stores/UserProfilesStore-test.ts
Labels: T-Enhancement

#10506 Remove feedback buttons from onboarding, search, and spaces
  res/css/_components.pcss
  res/css/structures/_SpaceRoomView.pcss
  res/css/views/dialogs/_SpotlightDialog.pcss
  res/css/views/spaces/_SpaceCreateMenu.pcss
  res/css/views/user-onboarding/_UserOnboardingFeedback.pcss
  res/css/views/user-onboarding/_UserOnboardingList.pcss
  src/components/structures/SpaceRoomView.tsx
  src/components/structures/UserMenu.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
  src/components/views/user-onboarding/UserOnboardingFeedback.tsx
  src/components/views/user-onboarding/UserOnboardingList.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/SpotlightDialog-test.tsx
  test/components/views/user-onboarding/UserOnboardingList-test.tsx
Labels: T-Task

#10519 Tweak Percy cron trigger to not run on weekends (#10519
  .github/workflows/element-web.yaml
Labels: T-Task

#10443 Support for MSC3882 revision 1
  src/components/views/settings/devices/LoginWithQRSection.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  test/components/views/settings/devices/LoginWithQR-test.tsx
  test/components/views/settings/devices/LoginWithQRSection-test.tsx
  test/components/views/settings/devices/__snapshots__/LoginWithQRSection-test.tsx.snap
  test/components/views/settings/tabs/user/SecurityUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Enhancement

#10497 Add room and user avatars to rte
  package.json
  res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
  src/components/views/rooms/wysiwyg_composer/components/WysiwygAutocomplete.tsx
  src/components/views/rooms/wysiwyg_composer/utils/autocomplete.ts
  test/components/views/rooms/wysiwyg_composer/utils/autocomplete-test.ts
  yarn.lock
Labels: T-Enhancement

#10441 Add E2E test of audio player
  cypress/e2e/audio-player/audio-player.spec.ts
  cypress/fixtures/1sec-long-name-audio-file.ogg
  cypress/fixtures/upload-first.ogg
  cypress/fixtures/upload-second.ogg
  cypress/fixtures/upload-third.ogg
  src/components/views/settings/ThemeChoicePanel.tsx
  test/components/views/settings/__snapshots__/ThemeChoicePanel-test.tsx.snap
Labels: Z-Community-PR, T-Task

#10518 Conform more of the codebase to `strictNullChecks` (#10518
  src/Lifecycle.ts
  src/MatrixClientPeg.ts
  src/components/views/messages/EditHistoryMessage.tsx
  src/components/views/messages/ReactionsRowButton.tsx
  src/components/views/settings/account/PhoneNumbers.tsx
  src/createRoom.ts
  src/stores/AsyncStoreWithClient.ts
  src/stores/AutoRageshakeStore.ts
  src/stores/BreadcrumbsStore.ts
  src/stores/CallStore.ts
  src/stores/OwnBeaconStore.ts
  src/stores/OwnProfileStore.ts
  src/stores/WidgetStore.ts
  src/stores/local-echo/RoomEchoChamber.ts
  src/stores/notifications/RoomNotificationStateStore.ts
  src/stores/notifications/SpaceNotificationState.ts
  src/stores/room-list/MessagePreviewStore.ts
  src/stores/room-list/RoomListStore.ts
  src/stores/room-list/SlidingRoomListStore.ts
  src/stores/spaces/SpaceStore.ts
  test/components/views/beacon/RoomLiveShareWarning-test.tsx
  test/components/views/settings/tabs/room/NotificationSettingsTab-test.tsx
  test/stores/OwnBeaconStore-test.ts
Labels: T-Task

#10534 Fix send two join requests when joining a room from spotlight search
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  test/components/views/dialogs/SpotlightDialog-test.tsx
Labels: T-Defect

#10513 Use Cypress Testing Library - `decryption-failure.spec.ts`
  cypress/e2e/crypto/decryption-failure.spec.ts
Labels: Z-Community-PR, T-Task

#10537 Update `audio-player.spec.ts` to reflect the latest status
  cypress/e2e/audio-player/audio-player.spec.ts
Labels: Z-Community-PR, T-Task

#10521 Handle command completions in RTE
  src/components/views/rooms/wysiwyg_composer/DynamicImportWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/components/WysiwygAutocomplete.tsx
  src/components/views/rooms/wysiwyg_composer/components/WysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useEditing.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useWysiwygSendActionHandler.ts
  src/components/views/rooms/wysiwyg_composer/utils/autocomplete.ts
  src/components/views/rooms/wysiwyg_composer/utils/message.ts
  test/components/views/rooms/wysiwyg_composer/components/WysiwygAutocomplete-test.tsx
  test/components/views/rooms/wysiwyg_composer/utils/autocomplete-test.ts
  test/components/views/rooms/wysiwyg_composer/utils/message-test.ts
Labels: T-Enhancement

#10551 fix spelling for test case in consent.spec.ts
  cypress/e2e/login/consent.spec.ts
  cypress/plugins/synapsedocker/templates/consent/res/templates/privacy/en/success.html
Labels: Z-Community-PR, T-Defect

#10538 Update `composer.spec.ts` to use `findBy*` type queries
  cypress/e2e/composer/composer.spec.ts
Labels: Z-Community-PR, T-Task

#10541 Update `decryption-failure.spec.ts`
  cypress/e2e/crypto/decryption-failure.spec.ts
Labels: Z-Community-PR, T-Task

#10542 Update `create-room.spec.ts` - deprecate custom commands
  cypress/e2e/create-room/create-room.spec.ts
Labels: Z-Community-PR, T-Task

#10546 fix resizer only work with left mouse click
  src/resizer/resizer.ts
Labels: Z-Community-PR, T-Defect

#10514 Use Cypress Testing Library - `consent.spec.ts`
  cypress/e2e/login/consent.spec.ts
Labels: Z-Community-PR, T-Task

#10509 Add unread fallback logging
  src/Unread.ts
  test/Unread-test.ts
Labels: T-Task

#10559 Fix avatar text issue in rte
  src/components/views/rooms/wysiwyg_composer/utils/autocomplete.ts
  test/components/views/rooms/wysiwyg_composer/utils/autocomplete-test.ts
Labels: T-Defect

#10558 Handle /me in rte
  src/components/views/rooms/wysiwyg_composer/utils/createMessageContent.ts
  src/components/views/rooms/wysiwyg_composer/utils/message.ts
  test/components/views/rooms/wysiwyg_composer/utils/createMessageContent-test.ts
Labels: T-Enhancement

#10535 Use Capabilities type from js-sdk
  src/components/views/settings/devices/LoginWithQRSection.tsx
Labels: T-Task

#10540 Update `timeline.spec.ts`
  cypress/e2e/timeline/timeline.spec.ts
Labels: Z-Community-PR, T-Task

#10561 fix file size display from kB to KB
  src/components/structures/UploadBar.tsx
  src/components/views/dialogs/UploadConfirmDialog.tsx
  src/components/views/dialogs/UploadFailureDialog.tsx
  src/components/views/messages/MFileBody.tsx
  src/utils/FileUtils.ts
Labels: Z-Community-PR, T-Enhancement

#10544 Remove `cypress/support/find.ts` and custom commands on Cypress Testing Library
  cypress/support/e2e.ts
  cypress/support/find.ts
  docs/cypress.md
Labels: Z-Community-PR, T-Task

#10569 Improve output in github actions for jest tests
  .github/workflows/tests.yml
  jest.config.ts
  package.json
  yarn.lock
Labels: T-Task

#10568 Update tests to ensure file size unit has been fixed
  cypress/e2e/right-panel/file-panel.spec.ts
  cypress/e2e/timeline/timeline.spec.ts
Labels: Z-Community-PR, T-Task

#10576 Fix read receipts falling from sky
  src/components/structures/MessagePanel.tsx
Labels: T-Defect

#10579 Fix issues with inhibited accessible focus outlines
  res/css/_common.pcss
  res/css/structures/auth/_Login.pcss
  res/css/views/dialogs/_CreateRoomDialog.pcss
  res/css/views/rooms/_RoomHeader.pcss
  res/themes/dark/css/_dark.pcss
  res/themes/legacy-dark/css/_legacy-dark.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light-high-contrast/css/_light-high-contrast.pcss
  res/themes/light/css/_light.pcss
Labels: T-Defect

#10572 Update `one-to-one-chat.spec.ts` - use Cypress Testing Library
  cypress/e2e/one-to-one-chat/one-to-one-chat.spec.ts
Labels: Z-Community-PR, T-Task

#10583 Make composer format bar an aria toolbar
  src/accessibility/Toolbar.tsx
  src/components/views/rooms/MessageComposerFormatBar.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
Labels: T-Enhancement

#10584 Exclude message timestamps from aria live region
  src/components/views/messages/MessageTimestamp.tsx
  src/components/views/rooms/EventTile.tsx
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
Labels: T-Enhancement

#10483 Show a tile for an unloaded predecessor room if it has via_servers
  src/components/views/messages/RoomPredecessorTile.tsx
  src/components/views/settings/tabs/room/AdvancedRoomSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/utils/permalinks/Permalinks.ts
  test/components/views/messages/RoomPredecessorTile-test.tsx
  test/components/views/messages/__snapshots__/RoomPredecessorTile-test.tsx.snap
  test/components/views/settings/tabs/room/AdvancedRoomSettingsTab-test.tsx
  test/utils/permalinks/MatrixToPermalinkConstructor-test.ts
Labels: T-Enhancement

#10577 Update `user-view.spec.ts` - use Cypress Testing Library
  cypress/e2e/user-view/user-view.spec.ts
Labels: Z-Community-PR, T-Task

#10585 Update `device-management.spec.ts` - use Cypress Testing Library
  cypress/e2e/settings/device-management.spec.ts
Labels: Z-Community-PR, T-Task

#10571 Fix: Images no longer reserve their space in the timeline correctly
  src/components/views/messages/MImageBody.tsx
  test/components/views/messages/MImageBody-test.tsx
  test/components/views/messages/__snapshots__/MImageBody-test.tsx.snap
Labels: T-Defect

#10508 Use `AccessibleButton` for "Accept" on AuthPage
  res/css/views/auth/_InteractiveAuthEntryComponents.pcss
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
Labels: Z-Community-PR, T-Task

#10586 Update `get-openid-token.spec.ts` - use Cypress Testing Library
  cypress/e2e/integration-manager/get-openid-token.spec.ts
Labels: Z-Community-PR, T-Task

#10563 Fix no identity server in help & about settings
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
Labels: T-Defect

#10573 Conform more of the codebase to `strictNullChecks`
  src/ImageUtils.ts
  src/components/structures/AutoHideScrollbar.tsx
  src/components/structures/IndicatorScrollbar.tsx
  src/components/structures/LeftPanel.tsx
  src/components/structures/LegacyCallEventGrouper.ts
  src/components/structures/MatrixChat.tsx
  src/components/structures/MessagePanel.tsx
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ScrollPanel.tsx
  src/components/structures/auth/Registration.tsx
  src/components/views/dialogs/ConfirmSpaceUserActionDialog.tsx
  src/components/views/dialogs/CreateSubspaceDialog.tsx
  src/components/views/dialogs/ManageRestrictedJoinRuleDialog.tsx
  src/components/views/dialogs/RegistrationEmailPromptDialog.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/elements/GenericEventListSummary.tsx
  src/components/views/rooms/AppsDrawer.tsx
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/LinkPreviewWidget.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
  src/components/views/rooms/RecentlyViewedButton.tsx
  src/components/views/rooms/ReplyPreview.tsx
  src/components/views/settings/SetIdServer.tsx
  src/components/views/settings/tabs/room/VoipRoomSettingsTab.tsx
  src/components/views/spaces/SpaceBasicSettings.tsx
  src/editor/autocomplete.ts
  src/editor/model.ts
  src/editor/parts.ts
  src/hooks/useRoomState.ts
  src/stores/RoomScrollStateStore.ts
  src/utils/UrlUtils.ts
Labels: T-Task

#10600 Update setting description to match reality
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Defect

#10560 Handle more completion types in rte autocomplete
  src/components/views/rooms/wysiwyg_composer/components/WysiwygAutocomplete.tsx
  src/components/views/rooms/wysiwyg_composer/utils/autocomplete.ts
  test/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/utils/autocomplete-test.ts
Labels: T-Enhancement

#10593 Remove dependency on `org.matrix.e2e_cross_signing` unstable feature
  src/DeviceListener.ts
  src/rageshake/submit-rageshake.ts
  src/sentry.ts
  test/DeviceListener-test.ts
Labels: T-Defect

#10603 Add support for Cypress tests with Podman
  cypress/plugins/docker/index.ts
Labels: T-Task

#10597 Update `login.spec.ts` - use Cypress Testing Library
  cypress/e2e/login/login.spec.ts
Labels: Z-Community-PR, T-Task

#10598 Fix incorrect avatar background colour when using a custom theme
  src/Avatar.ts
Labels: Z-Community-PR, T-Defect

#10605 Fix overflow on auth pages
  res/css/views/auth/_AuthPage.pcss
Labels: T-Defect

#10432 Properly translate errors in `AddThreepid.ts`
  src/AddThreepid.ts
  src/components/views/dialogs/ErrorDialog.tsx
  src/components/views/dialogs/SetEmailDialog.tsx
  src/components/views/settings/account/EmailAddresses.tsx
  src/components/views/settings/account/PhoneNumbers.tsx
  src/components/views/settings/discovery/EmailAddresses.tsx
  src/components/views/settings/discovery/PhoneNumbers.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/discovery/EmailAddresses-test.tsx
Labels: T-Defect

#10522 Relate field validation tooltip via aria-describedby
  src/components/views/elements/Field.tsx
Labels: T-Enhancement

#10582 Update `pills-click-in-app.spec.ts` - use Cypress Testing Library
  cypress/e2e/regression-tests/pills-click-in-app.spec.ts
Labels: Z-Community-PR, T-Task

#10589 #21451 Fix WebGL disabled error message
  src/components/views/location/LocationPicker.tsx
  src/i18n/strings/en_EN.json
  src/utils/location/LocationShareErrors.ts
  src/utils/location/map.ts
  test/components/views/location/LocationPicker-test.tsx
Labels: Z-Community-PR, T-Defect

#10622 Update `stickers.spec.ts` - use Cypress Testing Library
  cypress/e2e/widgets/stickers.spec.ts
Labels: Z-Community-PR, T-Task

#10602 Conform more of the codebase to `strictNullChecks`
  src/autocomplete/Autocompleter.ts
  src/components/structures/LoggedInView.tsx
  src/components/views/avatars/RoomAvatar.tsx
  src/components/views/dialogs/CreateSubspaceDialog.tsx
  src/components/views/dialogs/ExportDialog.tsx
  src/components/views/dialogs/RegistrationEmailPromptDialog.tsx
  src/components/views/dialogs/ReportEventDialog.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/elements/MiniAvatarUploader.tsx
  src/components/views/elements/RoomTopic.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/AuxPanel.tsx
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/LinkPreviewWidget.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
  src/components/views/rooms/ReadReceiptGroup.tsx
  src/components/views/rooms/ReadReceiptMarker.tsx
  src/components/views/rooms/RecentlyViewedButton.tsx
  src/components/views/rooms/ReplyTile.tsx
  src/components/views/spaces/SpaceBasicSettings.tsx
  src/customisations/Media.ts
  src/resizer/resizer.ts
  test/components/structures/AutocompleteInput-test.tsx
  test/components/views/rooms/wysiwyg_composer/utils/autocomplete-test.ts
  test/components/views/settings/AddPrivilegedUsers-test.tsx
Labels: T-Task

#10608 Update `room.spec.ts` - use Cypress Testing Library
  cypress/e2e/room/room.spec.ts
Labels: Z-Community-PR, T-Task

#10619 Update Cypress test files under `support/` directory - use Cypress Testing Library
  cypress/support/composer.ts
  cypress/support/settings.ts
  cypress/support/views.ts
Labels: Z-Community-PR, T-Task

#10623 Apply strictNullChecks to src/Markdown.ts
  src/Markdown.ts
Labels: Z-Community-PR, T-Task

#10611 Update `pollHistory.spec.ts` - use Cypress Testing Library
  cypress/e2e/polls/pollHistory.spec.ts
Labels: Z-Community-PR, T-Task

#10613 Update `send_event.spec.ts` - use Cypress Testing Library
  cypress/e2e/integration-manager/send_event.spec.ts
Labels: Z-Community-PR, T-Task

#10539 Use Cypress Testing Library - `right-panel.spec.ts`
  cypress/e2e/right-panel/right-panel.spec.ts
Labels: Z-Community-PR, T-Task

#10604 Replace hardcoded strings with MsgType constants
  src/components/structures/FilePanel.tsx
  src/components/views/elements/EventTilePreview.tsx
  src/components/views/messages/EditHistoryMessage.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/utils/exportUtils/HtmlExport.tsx
Labels: Z-Community-PR, T-Task

#10596 Update `room-directory.spec.ts` - use Cypress Testing Library
  cypress/e2e/room-directory/room-directory.spec.ts
Labels: Z-Community-PR, T-Task

#10630 Make SonarCloud happier about our code quality
  src/SlashCommands.tsx
  src/components/structures/LegacyCallEventGrouper.ts
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/location/Map.tsx
Labels: T-Task

#10621 Update `spotlight.spec.ts` - use Cypress Testing Library
  cypress/e2e/spotlight/spotlight.spec.ts
Labels: Z-Community-PR, T-Task

#10591 Update `lazy-loading.spec.ts` - use Cypress Testing Library
  cypress/e2e/lazy-loading/lazy-loading.spec.ts
Labels: Z-Community-PR, T-Task

#10626 Fix view source from edit history dialog always showing latest event
  src/components/structures/ViewSource.tsx
  src/components/views/messages/EditHistoryMessage.tsx
Labels: T-Defect

#10606 Fix multiple accessibility defects identified by AXE
  res/css/components/views/settings/devices/_SelectableDeviceTile.pcss
  src/components/views/elements/EffectsOverlay.tsx
  src/components/views/elements/ImageView.tsx
  src/components/views/elements/SettingsFlag.tsx
  src/components/views/elements/Slider.tsx
  src/components/views/messages/DateSeparator.tsx
  src/components/views/settings/FontScalingPanel.tsx
  src/components/views/settings/devices/SelectableDeviceTile.tsx
  src/components/views/settings/tabs/room/NotificationSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/__snapshots__/MessagePanel-test.tsx.snap
  test/components/views/dialogs/__snapshots__/MessageEditHistoryDialog-test.tsx.snap
  test/components/views/messages/__snapshots__/DateSeparator-test.tsx.snap
  test/components/views/settings/__snapshots__/DevicesPanel-test.tsx.snap
  test/components/views/settings/__snapshots__/FontScalingPanel-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/SelectableDeviceTile-test.tsx.snap
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
Labels: T-Defect

#10609 Update `polls.spec.ts` - use Cypress Testing Library
  cypress/e2e/polls/polls.spec.ts
Labels: Z-Community-PR, T-Task

#10629 Add missing rel noreferrer noopener attributes
  src/components/structures/RoomStatusBar.tsx
Labels: T-Task

#10633 Specify hashes for github actions
  .github/workflows/cypress.yaml
Labels: T-Task

#10627 Pick sensible default option for phone country dropdown
  src/components/views/auth/CountryDropdown.tsx
  test/components/views/auth/CountryDropdown-test.tsx
Labels: T-Enhancement

#10632 Deflake `threads` cypress test
  cypress/e2e/threads/threads.spec.ts
  cypress/support/client.ts
  cypress/support/homeserver.ts
Labels: T-Task

#10467 Implement new toast UI
  res/css/_font-weights.pcss
  res/css/compound/_Icon.pcss
  res/css/structures/_ToastContainer.pcss
  res/css/views/toasts/_IncomingLegacyCallToast.pcss
  res/img/compound/encryption-24px.svg
  src/components/structures/MatrixChat.tsx
  src/components/structures/ToastContainer.tsx
  src/components/views/toasts/GenericToast.tsx
  src/components/views/typography/Caption.tsx
  src/stores/ToastStore.ts
  src/toasts/IncomingLegacyCallToast.tsx
  test/components/views/toasts/GenericToast-test.tsx
  test/components/views/toasts/__snapshots__/GenericToast-test.tsx.snap
  test/toasts/__snapshots__/UnverifiedSessionToast-test.tsx.snap
Labels: T-Enhancement, X-Needs-Percy

#10652 Fix create subspace dialog not working
  src/components/views/dialogs/CreateSubspaceDialog.tsx
Labels: X-Release-Blocker, T-Defect, backport staging

#10661 Remove old debug logging in AsyncWrapper
  src/AsyncWrapper.tsx
  test/components/structures/auth/ForgotPassword-test.tsx
  test/components/views/dialogs/InviteDialog-test.tsx
  test/components/views/rooms/MessageComposer-test.tsx
  test/toasts/UnverifiedSessionToast-test.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip-test.tsx
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.tsx
Labels: T-Task

#10635 Add developer tools option to room list context menu
  res/css/views/context_menus/_IconizedContextMenu.pcss
  res/css/views/rooms/_RoomTile.pcss
  src/components/views/context_menus/DeveloperToolsOption.tsx
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/context_menus/RoomGeneralContextMenu.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  test/components/views/context_menus/RoomContextMenu-test.tsx
  test/components/views/context_menus/RoomGeneralContextMenu-test.tsx
Labels: T-Task

#10496 Remove obsolete CSS declarations from `_RoomHeader.pcss`
  res/css/views/rooms/_RoomHeader.pcss
Labels: Z-Community-PR, T-Task

#10667 Fix wrong room topic tooltip position
  src/components/views/elements/RoomTopic.tsx
  src/components/views/elements/TooltipTarget.tsx
  test/PosthogAnalytics-test.ts
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/utils/MegolmExportEncryption-test.ts
Labels: T-Defect

#10590 Update `events.spec.ts` - use Cypress Testing Library
  cypress/e2e/widgets/events.spec.ts
Labels: Z-Community-PR, T-Task

#10668 Add Cypress tests for the "complete security" phase
  cypress/e2e/crypto/complete-security.spec.ts
  cypress/e2e/crypto/crypto.spec.ts
  cypress/e2e/crypto/utils.ts
Labels: T-Task

#10676 Translate credits in help about section
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#10678 Fix typing tile duplicating users
  src/components/views/rooms/WhoIsTypingTile.tsx
Labels: T-Defect

#10674 ARIA Accessibility improvements
  res/css/views/dialogs/_SpotlightDialog.pcss
  res/css/views/right_panel/_BaseCard.pcss
  res/css/views/right_panel/_RoomSummaryCard.pcss
  res/css/views/settings/tabs/user/_KeyboardUserSettingsTab.pcss
  src/components/views/auth/CountryDropdown.tsx
  src/components/views/dialogs/spotlight/Option.tsx
  src/components/views/elements/Dropdown.tsx
  src/components/views/right_panel/BaseCard.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/SearchBar.tsx
  src/components/views/settings/account/EmailAddresses.tsx
  src/components/views/settings/account/PhoneNumbers.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/components/views/settings/tabs/user/AppearanceUserSettingsTab.tsx
  src/components/views/settings/tabs/user/KeyboardUserSettingsTab.tsx
  src/components/views/spaces/QuickSettingsButton.tsx
  src/components/views/spaces/SpaceSettingsVisibilityTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/SpotlightDialog-test.tsx
  test/components/views/elements/__snapshots__/FilterDropdown-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/settings/tabs/user/AppearanceUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/KeyboardUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#10620 Update `spaces.spec.ts` - use Cypress Testing Library
  cypress/e2e/spaces/spaces.spec.ts
Labels: Z-Community-PR, T-Task

#10660 Fix warnings from unfaked timers and clearAllModals
  test/test-utils/utilities.ts
Labels: T-Task

#10618 Update `sliding-sync.spec.ts` - use Cypress Testing Library
  cypress/e2e/sliding-sync/sliding-sync.ts
Labels: Z-Community-PR, T-Task

#10680 Update `threads.spec.ts` - use Cypress Testing Library
  cypress/e2e/threads/threads.spec.ts
Labels: Z-Community-PR, T-Task

#10675 ARIA Accessibility improvements
  res/css/structures/_SpaceRoomView.pcss
  res/css/views/settings/_CrossSigningPanel.pcss
  res/css/views/settings/_CryptographyPanel.pcss
  res/css/views/settings/_SecureBackupPanel.pcss
  src/components/structures/SpaceRoomView.tsx
  src/components/views/elements/EventTilePreview.tsx
  src/components/views/elements/LabelledToggleSwitch.tsx
  src/components/views/elements/ToggleSwitch.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/settings/CrossSigningPanel.tsx
  src/components/views/settings/CryptographyPanel.tsx
  src/components/views/settings/SecureBackupPanel.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
  src/components/views/spaces/SpacePublicShare.tsx
  test/components/structures/SpaceHierarchy-test.tsx
  test/components/views/location/LocationShareMenu-test.tsx
  test/components/views/location/__snapshots__/LocationShareMenu-test.tsx.snap
  test/components/views/settings/Notifications-test.tsx
  test/components/views/settings/__snapshots__/Notifications-test.tsx.snap
  test/components/views/spaces/SpaceSettingsVisibilityTab-test.tsx
  test/components/views/spaces/__snapshots__/SpaceSettingsVisibilityTab-test.tsx.snap
Labels: T-Enhancement

#10672 Conform more of the codebase to strictNullChecks
  src/Avatar.ts
  src/Searching.ts
  src/actions/RoomListActions.ts
  src/components/structures/MessagePanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ScrollPanel.tsx
  src/components/structures/UserView.tsx
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/context_menus/RoomGeneralContextMenu.tsx
  src/components/views/dialogs/ReportEventDialog.tsx
  src/components/views/dialogs/security/AccessSecretStorageDialog.tsx
  src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/components/views/rooms/SearchResultTile.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/components/views/settings/tabs/room/AdvancedRoomSettingsTab.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/components/views/voip/AudioFeed.tsx
  src/components/views/voip/LegacyCallView.tsx
  src/components/views/voip/VideoFeed.tsx
  src/indexing/EventIndex.ts
  src/models/Call.ts
  src/resizer/sizer.ts
  src/stores/BreadcrumbsStore.ts
  src/stores/OwnBeaconStore.ts
  src/stores/local-echo/RoomEchoChamber.ts
  src/stores/spaces/SpaceStore.ts
  src/stores/widgets/StopGapWidgetDriver.ts
  src/stores/widgets/WidgetLayoutStore.ts
  src/stores/widgets/WidgetPermissionStore.ts
  src/utils/SortMembers.ts
  src/utils/notifications.ts
  test/components/views/dialogs/MessageEditHistoryDialog-test.tsx
Labels: T-Task

#10664 Fix lack of screen reader indication when triggering auto complete
  src/components/views/rooms/BasicMessageComposer.tsx
Labels: T-Defect

#10687 Remove obsolete `mx_InviteDialog_transferButton` class
  src/components/views/dialogs/InviteDialog.tsx
Labels: Z-Community-PR, T-Task

#10686 Deprecate the `$spacing-` variables
  res/css/_font-sizes.pcss
  res/css/_spacing.pcss
Labels: T-Task

#10689 Remove a redundant snapshot - `'Manage integrations' on General settings tab`
  cypress/e2e/settings/set-integration-manager.spec.ts
Labels: Z-Community-PR, T-Task

#10677 More tests for UserInfo
  test/components/views/right_panel/UserInfo-test.tsx
  test/test-utils/utilities.ts
Labels: T-Task

#10681 Fix a crash when a call ends while you're in it
  src/models/Call.ts
  test/models/Call-test.ts
Labels: T-Defect

#10189 Tidy up IRCLayout.pcss
  res/css/views/rooms/_IRCLayout.pcss
Labels: Z-Community-PR, T-Task, X-Needs-Percy

#10691 Improve types to match reality
  src/BasePlatform.ts
  src/utils/AutoDiscoveryUtils.tsx
Labels: T-Task

#10698 Merge `set-integration-manager.spec.ts` with `general-user-settings-tab.spec.ts`
  cypress/e2e/settings/general-user-settings-tab.spec.ts
  cypress/e2e/settings/set-integration-manager.spec.ts
Labels: Z-Community-PR, T-Task

#10615 Properly translate errors in `ChangePassword.tsx` so they show up translated to the user but not in our logs
  src/components/views/settings/ChangePassword.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#10548 Remove some obsolete button styles from `_common.pcss`
  res/css/_common.pcss
Labels: Z-Community-PR, T-Task

#10699 Fix default content in devtools event sender
  src/components/views/dialogs/devtools/Event.tsx
Labels: Z-Community-PR, T-Defect

#10688 Cypress use the simulated merge commit for the source of tests
  .github/workflows/cypress.yaml
  .github/workflows/element-web.yaml
Labels: T-Task

#10651 Honour feature toggles in guest mode
  src/settings/handlers/DeviceSettingsHandler.ts
  test/settings/handlers/DeviceSettingsHandler-test.ts
Labels: T-Defect

#10663 Replace uses of `checkDeviceTrust` with `getDeviceVerificationStatus`
  src/DeviceListener.ts
  src/SlashCommands.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/MemberTile.tsx
  src/components/views/settings/DevicesPanel.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/i18n/strings/en_EN.json
  src/stores/SetupEncryptionStore.ts
  src/toasts/UnverifiedSessionToast.tsx
  src/utils/ShieldUtils.ts
  src/utils/arrays.ts
  src/utils/device/isDeviceVerified.ts
  test/DeviceListener-test.ts
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/rooms/EventTile-test.tsx
  test/components/views/settings/DevicesPanel-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/test-utils/test-utils.ts
  test/toasts/UnverifiedSessionToast-test.tsx
  test/utils/ShieldUtils-test.ts
  test/utils/arrays-test.ts
Labels: T-Task

#10673 Element-R: Starting a DMs with a user
  src/createRoom.ts
  test/createRoom-test.ts
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#10703 Conform more of the codebase with `strictNullChecks`
  src/IdentityAuthClient.tsx
  src/LegacyCallHandler.tsx
  src/Lifecycle.ts
  src/ScalarAuthClient.ts
  src/components/views/auth/CountryDropdown.tsx
  src/components/views/dialogs/ServerPickerDialog.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/elements/CopyableText.tsx
  src/components/views/emojipicker/EmojiPicker.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomTile.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/usePlainTextListeners.ts
  src/components/views/settings/SecureBackupPanel.tsx
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
  src/components/views/spaces/QuickSettingsButton.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  src/components/views/toasts/VerificationRequestToast.tsx
  src/customisations/Security.ts
  src/integrations/IntegrationManagers.ts
  src/linkify-matrix.ts
  src/stores/RoomViewStore.tsx
  src/stores/ThreepidInviteStore.ts
  src/stores/spaces/SpaceStore.ts
Labels: T-Task

#10708 Update roles cypress is looking for
  cypress/e2e/integration-manager/send_event.spec.ts
  cypress/e2e/lazy-loading/lazy-loading.spec.ts
  cypress/e2e/polls/pollHistory.spec.ts
  cypress/e2e/right-panel/file-panel.spec.ts
  cypress/e2e/sliding-sync/sliding-sync.ts
  cypress/e2e/threads/threads.spec.ts
Labels: T-Task

#10709 Make cypress happy about spec files all containing tests
  cypress.config.ts
  cypress/e2e/toasts/analytics-toast.spec.ts
  cypress/e2e/user-onboarding/user-onboarding-new.spec.ts
  cypress/e2e/user-onboarding/user-onboarding-old.spec.ts
Labels: T-Task

#10682 Unit test list ordering algorithms
  test/stores/room-list/algorithms/list-ordering/ImportanceAlgorithm-test.ts
  test/stores/room-list/algorithms/list-ordering/NaturalAlgorithm-test.ts
Labels: T-Task

#10550 Remove obsolete style rules - mx_DialogDesignChanges_wrapper
  res/css/_common.pcss
Labels: Z-Community-PR, T-Task

#10685 Fix condition of logging possible room list corruption
  src/stores/room-list/algorithms/list-ordering/ImportanceAlgorithm.ts
Labels: T-Task

#10702 Posthog properly handle Analytics ID changing from under us
  src/PosthogAnalytics.ts
  test/PosthogAnalytics-test.ts
Labels: T-Defect

#10671 Element-R: Populate device list for right-panel
  src/components/views/dialogs/ManualDeviceKeyVerificationDialog.tsx
  src/components/views/dialogs/UntrustedDeviceDialog.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/verification.ts
  test/components/views/dialogs/ManualDeviceKeyVerificationDialog-test.tsx
  test/components/views/dialogs/__snapshots__/ManualDeviceKeyVerificationDialog-test.tsx.snap
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#10715 Fix cypress tests exploding due to CSP
  .github/workflows/cypress.yaml
Labels: T-Task

#10705 Include cypress tests in previewbuild bundle
  .github/workflows/cypress.yaml
  .github/workflows/element-web.yaml
Labels: T-Task

#10625 Fix all rooms search generating permalinks to wrong room id
  src/components/structures/RoomSearchView.tsx
  src/components/structures/RoomView.tsx
  test/components/structures/RoomSearchView-test.tsx
Labels: T-Defect

#10712 add push rules test utility
  test/test-utils/pushRules.ts
Labels: T-Task

#10662 Bail out of `RoomSettingsDialog` when room is not found
  src/components/views/dialogs/RoomSettingsDialog.tsx
  src/components/views/dialogs/SpaceSettingsDialog.tsx
  src/components/views/settings/tabs/room/AdvancedRoomSettingsTab.tsx
  src/components/views/settings/tabs/room/BridgeSettingsTab.tsx
  src/components/views/settings/tabs/room/GeneralRoomSettingsTab.tsx
  src/components/views/settings/tabs/room/NotificationSettingsTab.tsx
  src/components/views/settings/tabs/room/PollHistoryTab.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/components/views/settings/tabs/room/VoipRoomSettingsTab.tsx
  test/components/views/dialogs/RoomSettingsDialog-test.tsx
  test/components/views/settings/tabs/room/AdvancedRoomSettingsTab-test.tsx
  test/components/views/settings/tabs/room/BridgeSettingsTab-test.tsx
  test/components/views/settings/tabs/room/RolesRoomSettingsTab-test.tsx
  test/components/views/settings/tabs/room/SecurityRoomSettingsTab-test.tsx
  test/components/views/settings/tabs/room/VoipRoomSettingsTab-test.tsx
  test/components/views/settings/tabs/room/__snapshots__/BridgeSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/RolesRoomSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/SecurityRoomSettingsTab-test.tsx.snap
Labels: T-Enhancement

#10670 Allow 16 lines of text in the rich text editors
  res/css/views/rooms/wysiwyg_composer/_SendWysiwygComposer.pcss
Labels: T-Enhancement

#10722 Consolidate login errors
  src/Lifecycle.ts
  src/components/structures/auth/Login.tsx
  src/components/structures/auth/Registration.tsx
  src/i18n/strings/en_EN.json
  src/utils/ErrorUtils.tsx
  test/utils/ErrorUtils-test.ts
  test/utils/__snapshots__/ErrorUtils-test.ts.snap
Labels: T-Defect

#10567 Commands for plain text editor
  cypress/e2e/composer/composer.spec.ts
  src/components/views/rooms/wysiwyg_composer/components/PlainTextComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useInputEventProcessor.ts
  src/components/views/rooms/wysiwyg_composer/hooks/usePlainTextListeners.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
  src/components/views/rooms/wysiwyg_composer/hooks/utils.ts
  test/components/views/rooms/wysiwyg_composer/components/PlainTextComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/hooks/useSuggestion-test.tsx
Labels: T-Enhancement

#9223 Offload some more waveform processing onto a worker
  cypress/e2e/audio-player/audio-player.spec.ts
  src/BlurhashEncoder.ts
  src/WorkerManager.ts
  src/audio/ManagedPlayback.ts
  src/audio/Playback.ts
  src/audio/PlaybackManager.ts
  src/audio/consts.ts
  src/components/views/audio_messages/PlaybackWaveform.tsx
  src/utils/arrays.ts
  src/workers/blurhash.worker.ts
  src/workers/playback.worker.ts
  src/workers/worker.ts
  test/WorkerManager-test.ts
  test/audio/Playback-test.ts
  test/components/views/audio_messages/RecordingPlayback-test.tsx
Labels: T-Defect

#10707 Fix warning about being unable to pass ref to function component
  src/components/views/messages/DecryptionFailureBody.tsx
Labels: T-Task

#10723 Let cypress find the sliding sync e2e tests
  cypress/e2e/sliding-sync/sliding-sync.spec.ts
Labels: T-Task

#10719 Update `read_events.spec.ts` - use Cypress Testing Library
  cypress/e2e/integration-manager/read_events.spec.ts
Labels: Z-Community-PR, T-Task

#10726 Use generics to better type TabbedView
  src/TextForEvent.tsx
  src/components/structures/TabbedView.tsx
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/dialogs/RoomSettingsDialog.tsx
  src/components/views/dialogs/SpacePreferencesDialog.tsx
  src/components/views/dialogs/SpaceSettingsDialog.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/elements/DesktopCapturerSourcePicker.tsx
  src/components/views/rooms/NewRoomIntro.tsx
  src/components/views/settings/JoinRuleSettings.tsx
  test/components/structures/TabbedView-test.tsx
Labels: T-Task

#10714 Memoize field validation results
  package.json
  src/components/views/auth/PassphraseField.tsx
  src/components/views/directory/NetworkDropdown.tsx
  src/components/views/elements/Validation.tsx
Labels: T-Enhancement

#9033 Remove `mx_EventTile:not([data-layout="bubble"])` selector
  res/css/structures/_FilePanel.pcss
  res/css/views/dialogs/_MessageEditHistoryDialog.pcss
  res/css/views/rooms/_EventBubbleTile.pcss
  res/css/views/rooms/_EventTile.pcss
Labels: Z-Community-PR, T-Task

#10728 Update tests related to user onboarding - use Cypress Testing Library
  cypress/e2e/user-onboarding/user-onboarding-new.spec.ts
  cypress/e2e/user-onboarding/user-onboarding-old.spec.ts
Labels: Z-Community-PR, T-Task

#10701 Enable Jest and Percy snapshots for `PreferencesUserSettingsTab`
  cypress/e2e/settings/preferences-user-settings-tab.spec.ts
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  test/components/views/settings/tabs/user/PreferencesUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/PreferencesUserSettingsTab-test.tsx.snap
Labels: Z-Community-PR, T-Task

#10727 Add UIFeature.locationSharing to hide location sharing
  src/components/views/rooms/MessageComposer.tsx
  src/settings/Settings.tsx
  src/settings/UIFeature.ts
Labels: T-Enhancement

#10733 Archaeological investigation - `_RoomView.pcss`
  res/css/structures/_RoomView.pcss
Labels: Z-Community-PR, T-Task
