Repository matrix-org/matrix-react-sdk, pull requests merged in 2023-09, with the labels that each got.

#11506 Fix avatars of knock members for people tab of room settings
  res/css/views/settings/tabs/room/_PeopleRoomSettingsTab.pcss
  src/components/views/settings/tabs/room/PeopleRoomSettingsTab.tsx
  test/components/views/settings/tabs/room/__snapshots__/PeopleRoomSettingsTab-test.tsx.snap
Labels: Z-Community-PR, T-Defect

#11496 Remove green "verified" bar for encrypted events
  cypress/e2e/crypto/crypto.spec.ts
  res/css/structures/_FilePanel.pcss
  res/css/views/rooms/_EventTile.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light/css/_light.pcss
  src/components/views/rooms/EventTile.tsx
  test/components/views/rooms/EventTile-test.tsx
Labels: T-Enhancement

#11507 Room header UI updates
  res/css/_common.pcss
  res/css/views/right_panel/_RoomSummaryCard.pcss
  res/css/views/rooms/_RoomHeader.pcss
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/views/avatars/BaseAvatar.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/hooks/useRoomMembers.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/structures/__snapshots__/SpaceHierarchy-test.tsx.snap
  test/components/structures/__snapshots__/UserMenu-test.tsx.snap
  test/components/views/avatars/__snapshots__/RoomAvatar-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ManageRestrictedJoinRuleDialog-test.tsx.snap
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/components/views/elements/__snapshots__/FacePile-test.tsx.snap
  test/components/views/elements/__snapshots__/Pill-test.tsx.snap
  test/components/views/elements/__snapshots__/RoomFacePile-test.tsx.snap
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/__snapshots__/PinnedEventTile-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomTile-test.tsx.snap
  test/components/views/spaces/__snapshots__/AddExistingToSpaceDialog-test.tsx.snap
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
  yarn.lock
Labels: T-Enhancement

#11087 Render custom images in reactions
  res/css/views/messages/_ReactionsRowButton.pcss
  src/components/views/messages/ReactionsRow.tsx
  src/components/views/messages/ReactionsRowButton.tsx
  src/components/views/messages/ReactionsRowButtonTooltip.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/views/messages/ReactionsRowButton-test.tsx
  test/components/views/messages/__snapshots__/ReactionsRowButton-test.tsx.snap
Labels: Z-Community-PR, T-Enhancement

#11511 Use Intl.RelativeTimeFormat for "last week" and "last month"
  src/components/views/messages/DateSeparator.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#11513 Only display RoomKnocksBar when feature flag is enabled
  src/components/views/rooms/LegacyRoomHeader.tsx
Labels: T-Defect

#11512 Migrate more strings to translation keys
  src/components/structures/ViewSource.tsx
  src/components/views/dialogs/DevtoolsDialog.tsx
  src/hooks/useUserOnboardingTasks.ts
  src/i18n/strings/ar.json
  src/i18n/strings/bg.json
  src/i18n/strings/ca.json
  src/i18n/strings/cs.json
  src/i18n/strings/da.json
  src/i18n/strings/de_DE.json
  src/i18n/strings/el.json
  src/i18n/strings/en_EN.json
  src/i18n/strings/eo.json
  src/i18n/strings/es.json
  src/i18n/strings/et.json
  src/i18n/strings/eu.json
  src/i18n/strings/fa.json
  src/i18n/strings/fi.json
  src/i18n/strings/fr.json
  src/i18n/strings/ga.json
  src/i18n/strings/gl.json
  src/i18n/strings/he.json
  src/i18n/strings/hu.json
  src/i18n/strings/id.json
  src/i18n/strings/is.json
  src/i18n/strings/it.json
  src/i18n/strings/ja.json
  src/i18n/strings/kab.json
  src/i18n/strings/ko.json
  src/i18n/strings/lo.json
  src/i18n/strings/lt.json
  src/i18n/strings/lv.json
  src/i18n/strings/nb_NO.json
  src/i18n/strings/nl.json
  src/i18n/strings/nn.json
  src/i18n/strings/oc.json
  src/i18n/strings/pl.json
  src/i18n/strings/pt.json
  src/i18n/strings/pt_BR.json
  src/i18n/strings/ru.json
  src/i18n/strings/sk.json
  src/i18n/strings/sq.json
  src/i18n/strings/sr.json
  src/i18n/strings/sv.json
  src/i18n/strings/tr.json
  src/i18n/strings/uk.json
  src/i18n/strings/vi.json
  src/i18n/strings/vls.json
  src/i18n/strings/zh_Hans.json
  src/i18n/strings/zh_Hant.json
  src/utils/humanize.ts
Labels: T-Task

#11519 [WIP] cypress segments
  .github/workflows/cypress.yaml
Labels: T-Task

#11523 Re-add --parallel flag for Percy
  .github/workflows/cypress.yaml
Labels: T-Task

#11515 Prevent event propagation when clicking icon buttons
  src/components/views/elements/FacePile.tsx
  src/components/views/rooms/RoomHeader.tsx
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
Labels: T-Defect

#11501 Add a 'm.relates_to' to edits in receipt tests and disable failing tests
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11481 Allow creating public knock rooms
  res/css/views/dialogs/_CreateRoomDialog.pcss
  src/components/views/dialogs/CreateRoomDialog.tsx
  src/components/views/elements/LabelledCheckbox.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/CreateRoomDialog-test.tsx
  test/components/views/elements/LabelledCheckbox-test.tsx
Labels: Z-Community-PR, T-Enhancement

#11478 Collect `console.debug` logs during cypress tests
  cypress/support/e2e.ts
Labels: T-Task

#11524 Only show Search button in RoomSummaryCard if new room UI enabled
  src/components/views/right_panel/RoomSummaryCard.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
Labels: X-Release-Blocker, T-Task

#11530 Migrate more strings to translation keys
  src/SlashCommands.tsx
  src/TextForEvent.tsx
  src/WhoIsTyping.ts
  src/components/views/avatars/DecoratedRoomAvatar.tsx
  src/components/views/elements/DialPadBackspaceButton.tsx
  src/components/views/messages/RedactedBody.tsx
  src/components/views/rooms/PresenceLabel.tsx
  src/i18n/strings/ar.json
  src/i18n/strings/az.json
  src/i18n/strings/bg.json
  src/i18n/strings/ca.json
  src/i18n/strings/cs.json
  src/i18n/strings/da.json
  src/i18n/strings/de_DE.json
  src/i18n/strings/el.json
  src/i18n/strings/en_EN.json
  src/i18n/strings/en_US.json
  src/i18n/strings/eo.json
  src/i18n/strings/es.json
  src/i18n/strings/et.json
  src/i18n/strings/eu.json
  src/i18n/strings/fa.json
  src/i18n/strings/fi.json
  src/i18n/strings/fr.json
  src/i18n/strings/ga.json
  src/i18n/strings/gl.json
  src/i18n/strings/he.json
  src/i18n/strings/hi.json
  src/i18n/strings/hu.json
  src/i18n/strings/id.json
  src/i18n/strings/is.json
  src/i18n/strings/it.json
  src/i18n/strings/ja.json
  src/i18n/strings/jbo.json
  src/i18n/strings/kab.json
  src/i18n/strings/ko.json
  src/i18n/strings/lo.json
  src/i18n/strings/lt.json
  src/i18n/strings/lv.json
  src/i18n/strings/nb_NO.json
  src/i18n/strings/nl.json
  src/i18n/strings/nn.json
  src/i18n/strings/oc.json
  src/i18n/strings/pl.json
  src/i18n/strings/pt.json
  src/i18n/strings/pt_BR.json
  src/i18n/strings/ru.json
  src/i18n/strings/sk.json
  src/i18n/strings/sq.json
  src/i18n/strings/sr.json
  src/i18n/strings/sv.json
  src/i18n/strings/te.json
  src/i18n/strings/th.json
  src/i18n/strings/tr.json
  src/i18n/strings/uk.json
  src/i18n/strings/vi.json
  src/i18n/strings/vls.json
  src/i18n/strings/zh_Hans.json
  src/i18n/strings/zh_Hant.json
Labels: T-Task

#11527 Fix regression around FacePile with overflow
  res/css/views/elements/_FacePile.pcss
  src/components/views/elements/FacePile.tsx
Labels: X-Release-Blocker, T-Task

#11516 Use RoomStateEvent.Update for knocks
  src/components/views/rooms/RoomKnocksBar.tsx
  src/components/views/settings/tabs/room/PeopleRoomSettingsTab.tsx
  test/components/views/rooms/RoomKnocksBar-test.tsx
  test/components/views/settings/tabs/room/PeopleRoomSettingsTab-test.tsx
Labels: Z-Community-PR, T-Defect

#11525 Cypress tests for event shields
  cypress/e2e/crypto/crypto.spec.ts
  cypress/e2e/crypto/utils.ts
Labels: T-Task

#11531 Document how to match the CI config for Cypress
  README.md
  docs/cypress.md
Labels: T-Task

#11558 Fix EventTile avatars being rendered with a size of 0 instead of hidden
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect, backport staging

#11480 Notify users about denied access on ask-to-join rooms
  src/components/structures/RoomView.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/RoomPreviewBar-test.tsx
  test/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
Labels: Z-Community-PR, T-Enhancement

#11534 Add a (failing for unrelated reasons) test for reading a thread root
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11529 Allow setting knock room directory visibility
  res/css/views/settings/_JoinRuleSettings.pcss
  src/components/views/settings/JoinRuleSettings.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/JoinRuleSettings-test.tsx
Labels: Z-Community-PR, T-Enhancement

#11581 Document that you should keep Synapse up-to-date
  docs/cypress.md
Labels: T-Task

#11580 Fix avatars in public room & space search being flex shrunk
  res/css/views/dialogs/_SpotlightDialog.pcss
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
Labels: X-Release-Blocker, T-Defect, backport staging

#11582 Fix vertical alignment of default avatar font
  res/css/views/avatars/_BaseAvatar.pcss
  res/css/views/right_panel/_UserInfo.pcss
Labels: X-Release-Blocker, T-Defect, backport staging

#11590 Add waits in Spotlight Cypress tests, hoping this unflakes them
  cypress/e2e/spotlight/spotlight.spec.ts
Labels: T-Defect

#11587 Tests for redactions in the main timeline
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11586 Tests for reacting to thread roots
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11517 Avoid using markAsRead where we don't need it
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11502 Expand a thread reply test to be more explicit
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11593 Fix avatar in right panel not using the correct font
  res/css/views/avatars/_BaseAvatar.pcss
  res/css/views/right_panel/_UserInfo.pcss
Labels: T-Defect

#11596 Use knock rooms sync to reflect the knock state
  src/components/structures/RoomView.tsx
  src/contexts/RoomContext.ts
  src/stores/RoomViewStore.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/stores/RoomViewStore-test.ts
  test/test-utils/room.ts
Labels: Z-Community-PR, T-Defect

#11588 Tests for thread roots and reading history
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11600 Re-enable parallelisation via Cypress Cloud now that the cycle has renewed
  .github/workflows/cypress.yaml
Labels: T-Task

#11504 Assert that the thread is unread after an edit
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11486 Fix docker entrypoint for Dendrite image
  cypress/plugins/dendritedocker/index.ts
Labels: T-Task

#11604 Update Compound to fix Firefox-specific avatar regression
  package.json
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
  yarn.lock
Labels: X-Release-Blocker, T-Defect

#11602 Default intentional mentions
  src/components/views/rooms/SendMessageComposer.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/ContentMessages-test.ts
  test/components/structures/ThreadView-test.tsx
  test/components/views/rooms/EditMessageComposer-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/components/views/rooms/VoiceRecordComposerTile-test.tsx
  test/components/views/settings/tabs/user/LabsUserSettingsTab-test.tsx
Labels: T-Enhancement

#11606 Migrate more strings to translation keys
  src/components/views/auth/AuthFooter.tsx
  src/components/views/auth/Welcome.tsx
  src/components/views/dialogs/CreateRoomDialog.tsx
  src/components/views/dialogs/CreateSubspaceDialog.tsx
  src/components/views/rooms/HistoryTile.tsx
  src/i18n/strings/ar.json
  src/i18n/strings/az.json
  src/i18n/strings/be.json
  src/i18n/strings/bg.json
  src/i18n/strings/ca.json
  src/i18n/strings/cs.json
  src/i18n/strings/da.json
  src/i18n/strings/de_DE.json
  src/i18n/strings/el.json
  src/i18n/strings/en_EN.json
  src/i18n/strings/en_US.json
  src/i18n/strings/eo.json
  src/i18n/strings/es.json
  src/i18n/strings/et.json
  src/i18n/strings/eu.json
  src/i18n/strings/fa.json
  src/i18n/strings/fi.json
  src/i18n/strings/fr.json
  src/i18n/strings/gl.json
  src/i18n/strings/he.json
  src/i18n/strings/hi.json
  src/i18n/strings/hu.json
  src/i18n/strings/id.json
  src/i18n/strings/is.json
  src/i18n/strings/it.json
  src/i18n/strings/ja.json
  src/i18n/strings/kab.json
  src/i18n/strings/ko.json
  src/i18n/strings/lo.json
  src/i18n/strings/lt.json
  src/i18n/strings/lv.json
  src/i18n/strings/ml.json
  src/i18n/strings/nb_NO.json
  src/i18n/strings/nl.json
  src/i18n/strings/nn.json
  src/i18n/strings/pl.json
  src/i18n/strings/pt.json
  src/i18n/strings/pt_BR.json
  src/i18n/strings/ru.json
  src/i18n/strings/sk.json
  src/i18n/strings/sl.json
  src/i18n/strings/sq.json
  src/i18n/strings/sr.json
  src/i18n/strings/sr_Latn.json
  src/i18n/strings/sv.json
  src/i18n/strings/ta.json
  src/i18n/strings/th.json
  src/i18n/strings/tr.json
  src/i18n/strings/uk.json
  src/i18n/strings/vi.json
  src/i18n/strings/vls.json
  src/i18n/strings/zh_Hans.json
  src/i18n/strings/zh_Hant.json
  src/widgets/CapabilityText.tsx
Labels: T-Task

#11495 Move ViewUser action callback to RoomView
  src/components/structures/RoomView.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/views/right_panel/HeaderButtons.tsx
  src/components/views/right_panel/LegacyRoomHeaderButtons.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/stores/right-panel/RightPanelStore.ts
Labels: T-Defect

#11508 Move notifications bell back in labs
  cypress/e2e/right-panel/notification-panel.spec.ts
  cypress/e2e/room/room-header.spec.ts
  src/components/views/right_panel/HeaderButtons.tsx
  src/components/views/right_panel/LegacyRoomHeaderButtons.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/views/right_panel/__snapshots__/LegacyRoomHeaderButtons-test.tsx.snap
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
Labels: T-Task

#11505 More assertions about threads being read
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11528 Replace event verification logic with new code in js-sdk
  cypress/e2e/crypto/crypto.spec.ts
  res/css/views/rooms/_EventTile.pcss
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/EventTile-test.tsx
Labels: T-Task

#11589 Enable cypress tests for shields with rust crypto
  cypress/e2e/crypto/crypto.spec.ts
  src/components/views/rooms/EventTile.tsx
Labels: T-Task

#11249 OIDC: persist refresh token
  src/Lifecycle.ts
  src/MatrixClientPeg.ts
  src/utils/oidc/authorize.ts
  test/Lifecycle-test.ts
  test/utils/oidc/authorize-test.ts
Labels: T-Enhancement

#11607 Escape placeholder before injecting it into the style
  src/components/views/rooms/BasicMessageComposer.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/rooms/BasicMessageComposer-test.tsx
Labels: T-Defect

#11576 Make video & voice call buttons pin conference widget if unpinned
  src/components/views/rooms/RoomHeader.tsx
  src/hooks/room/useRoomCall.ts
  src/hooks/room/useRoomCallStatus.ts
  src/hooks/useRoomState.ts
  src/i18n/strings/en_EN.json
  src/stores/WidgetStore.ts
  src/utils/WidgetUtils.ts
  src/utils/room/placeCall.ts
  src/widgets/ManagedHybrid.ts
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
Labels: X-Release-Blocker, T-Enhancement

#11573 Show knock rooms in the list
  res/css/views/rooms/_NotificationBadge.pcss
  res/css/views/rooms/_RoomTile.pcss
  src/RoomNotifs.ts
  src/components/views/rooms/NotificationBadge.tsx
  src/components/views/rooms/NotificationBadge/StatelessNotificationBadge.tsx
  src/components/views/rooms/RoomTile.tsx
  src/stores/notifications/NotificationState.ts
  src/stores/notifications/RoomNotificationState.ts
  src/stores/room-list/RoomListStore.ts
  src/stores/room-list/algorithms/Algorithm.ts
  src/utils/membership.ts
  test/RoomNotifs-test.ts
  test/components/views/rooms/NotificationBadge/StatelessNotificationBadge-test.tsx
  test/components/views/rooms/RoomTile-test.tsx
  test/test-utils/test-utils.ts
  test/utils/membership-test.ts
Labels: Z-Community-PR, T-Enhancement

#11612 More tests for reactions to messages in threads
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11611 Switch from zxcvbn to @zxcvbn-ts
  package.json
  src/components/views/auth/PassphraseField.tsx
  src/i18n/strings/ar.json
  src/i18n/strings/bg.json
  src/i18n/strings/ca.json
  src/i18n/strings/cs.json
  src/i18n/strings/da.json
  src/i18n/strings/de_DE.json
  src/i18n/strings/el.json
  src/i18n/strings/en_EN.json
  src/i18n/strings/eo.json
  src/i18n/strings/es.json
  src/i18n/strings/et.json
  src/i18n/strings/eu.json
  src/i18n/strings/fa.json
  src/i18n/strings/fi.json
  src/i18n/strings/fr.json
  src/i18n/strings/ga.json
  src/i18n/strings/gl.json
  src/i18n/strings/he.json
  src/i18n/strings/hi.json
  src/i18n/strings/hu.json
  src/i18n/strings/id.json
  src/i18n/strings/is.json
  src/i18n/strings/it.json
  src/i18n/strings/ja.json
  src/i18n/strings/kab.json
  src/i18n/strings/ko.json
  src/i18n/strings/lo.json
  src/i18n/strings/lt.json
  src/i18n/strings/lv.json
  src/i18n/strings/nb_NO.json
  src/i18n/strings/nl.json
  src/i18n/strings/nn.json
  src/i18n/strings/pl.json
  src/i18n/strings/pt_BR.json
  src/i18n/strings/ru.json
  src/i18n/strings/sk.json
  src/i18n/strings/sq.json
  src/i18n/strings/sv.json
  src/i18n/strings/tr.json
  src/i18n/strings/uk.json
  src/i18n/strings/vi.json
  src/i18n/strings/vls.json
  src/i18n/strings/zh_Hans.json
  src/i18n/strings/zh_Hant.json
  src/utils/PasswordScorer.ts
  yarn.lock
Labels: T-Task

#11629 Cypress tests for redacted messages in threads and thread roots
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11614 DeviceListener: Remove usage of deprecated keybackup API
  src/DeviceListener.ts
  test/DeviceListener-test.ts
Labels: T-Task

#11630 Undo Localazy key clobber
  src/components/structures/auth/Registration.tsx
  src/i18n/strings/bg.json
  src/i18n/strings/cs.json
  src/i18n/strings/de_DE.json
  src/i18n/strings/el.json
  src/i18n/strings/en_EN.json
  src/i18n/strings/eo.json
  src/i18n/strings/es.json
  src/i18n/strings/et.json
  src/i18n/strings/fa.json
  src/i18n/strings/fi.json
  src/i18n/strings/fr.json
  src/i18n/strings/ga.json
  src/i18n/strings/gl.json
  src/i18n/strings/he.json
  src/i18n/strings/hu.json
  src/i18n/strings/id.json
  src/i18n/strings/is.json
  src/i18n/strings/it.json
  src/i18n/strings/ja.json
  src/i18n/strings/kab.json
  src/i18n/strings/lo.json
  src/i18n/strings/lt.json
  src/i18n/strings/lv.json
  src/i18n/strings/nb_NO.json
  src/i18n/strings/nl.json
  src/i18n/strings/pl.json
  src/i18n/strings/pt.json
  src/i18n/strings/pt_BR.json
  src/i18n/strings/ru.json
  src/i18n/strings/sk.json
  src/i18n/strings/sq.json
  src/i18n/strings/sv.json
  src/i18n/strings/uk.json
  src/i18n/strings/vi.json
  src/i18n/strings/zh_Hans.json
  src/i18n/strings/zh_Hant.json
Labels: T-Task

#11631 Linkify room topic
  src/components/views/rooms/RoomHeader.tsx
  src/hooks/room/useTopic.ts
  test/components/views/rooms/RoomHeader-test.tsx
Labels: T-Enhancement

#11636 Fix cypress test for events from unsigned devices
  cypress/e2e/crypto/crypto.spec.ts
Labels: T-Task

#11632 Render space pills with square corners to match new avatar
  res/css/views/elements/_Pill.pcss
  src/components/views/elements/Pill.tsx
Labels: T-Enhancement

#11641 fix avatar styling in lightbox
  src/components/views/elements/ImageView.tsx
Labels: T-Defect

#11643 Fix add to space avatar text centering
  res/css/views/dialogs/_AddExistingToSpaceDialog.pcss
Labels: T-Defect

#11640 Don't start key backups when opening settings
  src/components/views/settings/SecureBackupPanel.tsx
  test/components/views/settings/SecureBackupPanel-test.tsx
  test/components/views/settings/__snapshots__/SecureBackupPanel-test.tsx.snap
  test/components/views/settings/tabs/user/SecurityUserSettingsTab-test.tsx
  test/test-utils/client.ts
Labels: T-Defect

#11645 LogoutDialog: Remove usage of deprecated keybackup API
  src/components/views/dialogs/LogoutDialog.tsx
  test/components/views/dialogs/LogoutDialog-test.tsx
  test/components/views/dialogs/__snapshots__/LogoutDialog-test.tsx.snap
Labels: T-Task

#11311 Implement MSC4039: Add an MSC for a new Widget API action to upload files into the media repository
  package.json
  src/components/views/dialogs/ModalWidgetDialog.tsx
  src/stores/widgets/StopGapWidget.ts
  src/stores/widgets/StopGapWidgetDriver.ts
  test/stores/widgets/StopGapWidget-test.ts
  test/stores/widgets/StopGapWidgetDriver-test.ts
  test/test-utils/test-utils.ts
  yarn.lock
Labels: T-Enhancement, A-Timesheet-1

#11647 Fix: onFinished added which closes the menu
  src/components/views/spaces/SpacePanel.tsx
Labels: Z-Community-PR, T-Defect

#11633 Tests for paging up to find old messages
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11653 Revert "Update browser-actions/setup-chrome digest to 905ab04"
  .github/workflows/cypress.yaml
Labels: T-Task

#11635 `CreateSecretStorageDialog`: stop using deprecated APIs
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  test/components/views/dialogs/security/CreateSecretStorageDialog-test.tsx
  test/components/views/dialogs/security/__snapshots__/CreateSecretStorageDialog-test.tsx.snap
  test/test-utils/client.ts
  test/test-utils/test-utils.ts
Labels: T-Task

#11649 Split the read-receipt tests into logical units
  cypress/e2e/read-receipts/editing-messages.spec.ts
  cypress/e2e/read-receipts/high-level.spec.ts
  cypress/e2e/read-receipts/missing-referents.spec.ts
  cypress/e2e/read-receipts/new-messages.spec.ts
  cypress/e2e/read-receipts/reactions.spec.ts
  cypress/e2e/read-receipts/read-receipts-utils.ts
  cypress/e2e/read-receipts/readme.md
  cypress/e2e/read-receipts/redactions.spec.ts
Labels: T-Task

#10170 Message layout will update according to the selected style
  src/components/views/settings/FontScalingPanel.tsx
Labels: Z-Community-PR, T-Enhancement

#11660 Consolidate conjugation i18n strings
  cypress/tsconfig.json
  src/MatrixClientPeg.ts
  src/components/views/elements/EventListSummary.tsx
  src/components/views/messages/MPollBody.tsx
  src/components/views/messages/ReactionsRowButton.tsx
  src/components/views/messages/ReactionsRowButtonTooltip.tsx
  src/components/views/rooms/RoomKnocksBar.tsx
  src/i18n/strings/bg.json
  src/i18n/strings/ca.json
  src/i18n/strings/cs.json
  src/i18n/strings/da.json
  src/i18n/strings/de_DE.json
  src/i18n/strings/el.json
  src/i18n/strings/en_EN.json
  src/i18n/strings/eo.json
  src/i18n/strings/es.json
  src/i18n/strings/et.json
  src/i18n/strings/eu.json
  src/i18n/strings/fa.json
  src/i18n/strings/fi.json
  src/i18n/strings/fr.json
  src/i18n/strings/gl.json
  src/i18n/strings/he.json
  src/i18n/strings/hu.json
  src/i18n/strings/id.json
  src/i18n/strings/is.json
  src/i18n/strings/it.json
  src/i18n/strings/ja.json
  src/i18n/strings/kab.json
  src/i18n/strings/ko.json
  src/i18n/strings/lo.json
  src/i18n/strings/lt.json
  src/i18n/strings/lv.json
  src/i18n/strings/nb_NO.json
  src/i18n/strings/nl.json
  src/i18n/strings/nn.json
  src/i18n/strings/pl.json
  src/i18n/strings/pt_BR.json
  src/i18n/strings/ru.json
  src/i18n/strings/sk.json
  src/i18n/strings/sq.json
  src/i18n/strings/sr.json
  src/i18n/strings/sv.json
  src/i18n/strings/tr.json
  src/i18n/strings/uk.json
  src/i18n/strings/vi.json
  src/i18n/strings/vls.json
  src/i18n/strings/zh_Hans.json
  src/i18n/strings/zh_Hant.json
  src/utils/FormattingUtils.ts
  src/utils/i18n-helpers.ts
  test/components/views/elements/EventListSummary-test.tsx
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/rooms/RoomKnocksBar-test.tsx
  test/utils/FormattingUtils-test.ts
  test/utils/FormattingUtils-test.tsx
  test/utils/__snapshots__/FormattingUtils-test.tsx.snap
  test/utils/i18n-helpers-test.ts
  tsconfig.json
Labels: T-Task

#11652 Fix flaky tests around editing messages
  cypress/e2e/read-receipts/editing-messages.spec.ts
Labels: T-Task

#11654 Fix flake in high-level tests by not using markAsRead
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11668 Switch to sorry-cypress
  .github/workflows/cypress.yaml
  cypress.config.ts
  cypress/plugins/index.ts
  cypress/support/e2e.ts
  package.json
  yarn.lock
Labels: T-Task

#11634 Revert "Fix regression around FacePile with overflow (#11527)"
  res/css/views/elements/_FacePile.pcss
  src/components/views/elements/FacePile.tsx
  test/components/structures/__snapshots__/MessagePanel-test.tsx.snap
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/structures/__snapshots__/SpaceHierarchy-test.tsx.snap
  test/components/structures/__snapshots__/UserMenu-test.tsx.snap
  test/components/views/avatars/__snapshots__/RoomAvatar-test.tsx.snap
  test/components/views/beacon/__snapshots__/BeaconMarker-test.tsx.snap
  test/components/views/beacon/__snapshots__/BeaconViewDialog-test.tsx.snap
  test/components/views/beacon/__snapshots__/DialogSidebar-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ConfirmUserActionDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ManageRestrictedJoinRuleDialog-test.tsx.snap
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/components/views/elements/__snapshots__/FacePile-test.tsx.snap
  test/components/views/elements/__snapshots__/Pill-test.tsx.snap
  test/components/views/elements/__snapshots__/RoomFacePile-test.tsx.snap
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/MLocationBody-test.tsx.snap
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/components/views/rooms/__snapshots__/PinnedEventTile-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomTile-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/PeopleRoomSettingsTab-test.tsx.snap
  test/components/views/spaces/__snapshots__/AddExistingToSpaceDialog-test.tsx.snap
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
  yarn.lock
Labels: T-Defect, backport staging

#11670 Backport #11634 to staging
  res/css/views/elements/_FacePile.pcss
  src/components/views/elements/FacePile.tsx
  test/components/structures/__snapshots__/MessagePanel-test.tsx.snap
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/structures/__snapshots__/SpaceHierarchy-test.tsx.snap
  test/components/structures/__snapshots__/UserMenu-test.tsx.snap
  test/components/views/avatars/__snapshots__/RoomAvatar-test.tsx.snap
  test/components/views/beacon/__snapshots__/BeaconMarker-test.tsx.snap
  test/components/views/beacon/__snapshots__/BeaconViewDialog-test.tsx.snap
  test/components/views/beacon/__snapshots__/DialogSidebar-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ConfirmUserActionDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ManageRestrictedJoinRuleDialog-test.tsx.snap
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/components/views/elements/__snapshots__/FacePile-test.tsx.snap
  test/components/views/elements/__snapshots__/Pill-test.tsx.snap
  test/components/views/elements/__snapshots__/RoomFacePile-test.tsx.snap
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/MLocationBody-test.tsx.snap
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/components/views/rooms/__snapshots__/PinnedEventTile-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomTile-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/PeopleRoomSettingsTab-test.tsx.snap
  test/components/views/spaces/__snapshots__/AddExistingToSpaceDialog-test.tsx.snap
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
  yarn.lock
Labels: T-Defect

#11667 Fix: sync intentional mentions push rules with legacy rules
  src/notifications/VectorPushRulesDefinitions.ts
  src/utils/pushRules/monitorSyncedPushRules.ts
  test/components/structures/LoggedInView-test.tsx
Labels: T-Defect

#11658 Fix: Unread notification dot aligned
  res/css/views/rooms/_TopUnreadMessagesBar.pcss
Labels: Z-Community-PR, T-Defect

#11673 Fix Emoji font on Safari 17
  src/utils/FontManager.ts
Labels: T-Defect

#11250 OIDC: retrieve `refreshToken` from storage
  src/Lifecycle.ts
  test/Lifecycle-test.ts
Labels: T-Task

#11675 Localazy: Convert more strings
  src/async-components/views/dialogs/security/CreateKeyBackupDialog.tsx
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/async-components/views/dialogs/security/ExportE2eKeysDialog.tsx
  src/async-components/views/dialogs/security/ImportE2eKeysDialog.tsx
  src/async-components/views/dialogs/security/NewRecoveryMethodDialog.tsx
  src/async-components/views/dialogs/security/RecoveryMethodRemovedDialog.tsx
  src/components/structures/auth/SessionLockStolenView.tsx
  src/components/structures/auth/SetupEncryptionBody.tsx
  src/components/structures/auth/SoftLogout.tsx
  src/components/structures/auth/forgot-password/EnterEmail.tsx
  src/i18n/strings/az.json
  src/i18n/strings/bg.json
  src/i18n/strings/ca.json
  src/i18n/strings/cs.json
  src/i18n/strings/da.json
  src/i18n/strings/de_DE.json
  src/i18n/strings/el.json
  src/i18n/strings/en_EN.json
  src/i18n/strings/en_US.json
  src/i18n/strings/eo.json
  src/i18n/strings/es.json
  src/i18n/strings/et.json
  src/i18n/strings/eu.json
  src/i18n/strings/fa.json
  src/i18n/strings/fi.json
  src/i18n/strings/fr.json
  src/i18n/strings/ga.json
  src/i18n/strings/gl.json
  src/i18n/strings/he.json
  src/i18n/strings/hu.json
  src/i18n/strings/id.json
  src/i18n/strings/is.json
  src/i18n/strings/it.json
  src/i18n/strings/ja.json
  src/i18n/strings/jbo.json
  src/i18n/strings/kab.json
  src/i18n/strings/ko.json
  src/i18n/strings/lo.json
  src/i18n/strings/lt.json
  src/i18n/strings/lv.json
  src/i18n/strings/nb_NO.json
  src/i18n/strings/nl.json
  src/i18n/strings/nn.json
  src/i18n/strings/oc.json
  src/i18n/strings/pl.json
  src/i18n/strings/pt.json
  src/i18n/strings/pt_BR.json
  src/i18n/strings/ru.json
  src/i18n/strings/sk.json
  src/i18n/strings/sq.json
  src/i18n/strings/sr.json
  src/i18n/strings/sv.json
  src/i18n/strings/th.json
  src/i18n/strings/tr.json
  src/i18n/strings/uk.json
  src/i18n/strings/vi.json
  src/i18n/strings/vls.json
  src/i18n/strings/zh_Hans.json
  src/i18n/strings/zh_Hant.json
  src/languageHandler.tsx
Labels: T-Task

#11655 Use .well-known to discover a default rendezvous server for use with Sign in with QR
  src/components/views/auth/LoginWithQR.tsx
  src/components/views/settings/devices/LoginWithQRSection.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  test/components/views/settings/devices/LoginWithQR-test.tsx
  test/components/views/settings/devices/LoginWithQRSection-test.tsx
  test/components/views/settings/devices/__snapshots__/LoginWithQRSection-test.tsx.snap
Labels: T-Enhancement

#11676 Fix: Theme selector radio button not aligned in center with the text
  res/css/views/settings/_ThemeChoicePanel.pcss
Labels: Z-Community-PR, T-Defect

#11677 Remove focus-visible polyfill
  package.json
  res/css/_common.pcss
  res/css/views/dialogs/_CreateRoomDialog.pcss
  res/css/views/elements/_Slider.pcss
  res/css/views/elements/_StyledCheckbox.pcss
  res/css/views/elements/_StyledRadioButton.pcss
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/_LinkPreviewGroup.pcss
  src/components/structures/MatrixChat.tsx
  test/components/structures/ThreadPanel-test.tsx
  test/components/structures/__snapshots__/MatrixChat-test.tsx.snap
  test/components/structures/__snapshots__/ThreadPanel-test.tsx.snap
  test/components/views/context_menus/SpaceContextMenu-test.tsx
  test/components/views/context_menus/__snapshots__/SpaceContextMenu-test.tsx.snap
  yarn.lock
Labels: T-Task

#11662 Target specific thread name to unflake redaction tests
  cypress/e2e/read-receipts/read-receipts-utils.ts
Labels: T-Task

#11661 Fix flaky receipt and redaction tests by pausing between message sends
  cypress/e2e/read-receipts/read-receipts-utils.ts
Labels: T-Task

#11650 Tests for paging up to find old messages
  cypress/e2e/read-receipts/high-level.spec.ts
  cypress/e2e/read-receipts/new-messages.spec.ts
  cypress/e2e/read-receipts/read-receipts-utils.ts
Labels: T-Task
