Repository matrix-org/matrix-react-sdk, pull requests merged in 2023-06, with the labels that each got.

#11020 Fix: server picker validates unselected option
  src/components/views/dialogs/ServerPickerDialog.tsx
  test/components/views/dialogs/ServerPickerDialog-test.tsx
Labels: T-Defect

#10980 Remove STIXGeneral from the font stack
  .github/workflows/cypress.yaml
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light/css/_light.pcss
Labels: T-Defect

#10631 Include thread replies in message previews
  res/css/views/rooms/_RoomTile.pcss
  res/img/compound/thread-16px.svg
  src/components/views/rooms/RoomTile.tsx
  src/components/views/rooms/RoomTileSubtitle.tsx
  src/stores/room-list/MessagePreviewStore.ts
  test/components/views/rooms/EventTile-test.tsx
  test/components/views/rooms/RoomTile-test.tsx
  test/components/views/rooms/__snapshots__/RoomTile-test.tsx.snap
  test/stores/room-list/MessagePreviewStore-test.ts
  test/test-utils/test-utils.ts
  test/test-utils/threads.ts
Labels: T-Enhancement, X-Needs-Percy

#11011 When joining room in sub-space join the parents too
  src/components/structures/SpaceHierarchy.tsx
  test/components/structures/SpaceHierarchy-test.tsx
  test/components/structures/__snapshots__/SpaceHierarchy-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#10984 Pass around MatrixClients instead of using MatrixClientPeg
  src/DeviceListener.ts
  src/IdentityAuthClient.tsx
  src/Lifecycle.ts
  src/Livestream.ts
  src/PosthogAnalytics.ts
  src/RoomNotifs.ts
  src/Rooms.ts
  src/ScalarAuthClient.ts
  src/ScalarMessaging.ts
  src/Terms.ts
  src/components/structures/RoomView.tsx
  src/components/views/context_menus/WidgetContextMenu.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/createRoom.ts
  src/rageshake/submit-rageshake.ts
  src/stores/local-echo/RoomEchoChamber.ts
  src/stores/right-panel/RightPanelStore.ts
  src/verification.ts
  test/DeviceListener-test.ts
  test/Rooms-test.ts
  test/Terms-test.tsx
  test/components/views/right_panel/UserInfo-test.tsx
Labels: T-Task

#10894 Extract style rules specific to `ThreadsList` to prevent a visual regression
  res/css/views/rooms/_EventTile.pcss
Labels: Z-Community-PR, T-Task

#10970 Fix placement of `Loading…` with the spinner on pinned widgets being reloaded
  res/css/views/rooms/_AppsDrawer.pcss
  src/components/views/elements/AppTile.tsx
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
Labels: Z-Community-PR, T-Defect

#11043 Disable sliding sync tests in failure
  cypress/e2e/sliding-sync/sliding-sync.spec.ts
Labels: T-Task

#10721 Update `timeline.spec.ts` - use Cypress Testing Library
  cypress/e2e/timeline/timeline.spec.ts
Labels: Z-Community-PR, T-Task

#11040 Create `left-panel.spec.ts`
  cypress/e2e/left-panel/left-panel.spec.ts
Labels: Z-Community-PR, T-Task

#11037 Switch from grapheme-splitter to graphemer
  package.json
  src/HtmlUtils.tsx
  src/editor/parts.ts
  src/utils/strings.ts
  yarn.lock
Labels: T-Task

#11027 Removed `DecryptionFailureBar.tsx`
  cypress/e2e/crypto/decryption-failure.spec.ts
  src/components/structures/RoomView.tsx
  src/components/views/rooms/DecryptionFailureBar.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/DecryptionFailureBar-test.tsx
  test/components/views/rooms/__snapshots__/DecryptionFailureBar-test.tsx.snap
Labels: T-Enhancement

#11010 Take a Percy snapshot of `Invite your teammates` Space dialog correctly
  cypress/e2e/spaces/spaces.spec.ts
Labels: Z-Community-PR, T-Task

#11046 Disable verification test for Element-R
  cypress/e2e/crypto/crypto.spec.ts
Labels: T-Task

#11025 Inhibit interactions on forward dialog message previews
  src/components/views/dialogs/ForwardDialog.tsx
  src/components/views/messages/IBodyProps.ts
  src/components/views/messages/MVideoBody.tsx
  src/components/views/messages/MessageEvent.tsx
  src/events/EventTileFactory.tsx
Labels: T-Enhancement

#11013 Inline `VerificationRequest.{invalid,ready,started,done,cancelled}`
  src/components/views/messages/MKeyVerificationConclusion.tsx
  src/components/views/messages/MKeyVerificationRequest.tsx
  src/components/views/right_panel/EncryptionPanel.tsx
  src/stores/SetupEncryptionStore.ts
  test/components/views/messages/MKeyVerificationConclusion-test.tsx
  test/components/views/messages/MKeyVerificationRequest-test.tsx
  test/components/views/right_panel/UserInfo-test.tsx
Labels: T-Task

#11039 Replace Sass variables specific to each CSS file with CSS custom properties
  res/css/structures/_LeftPanel.pcss
  res/css/structures/_SpacePanel.pcss
  res/css/structures/_SpaceRoomView.pcss
  res/css/views/spaces/_SpaceCreateMenu.pcss
Labels: Z-Community-PR, T-Task

#10695 Remove `TODO` comments about spacing variables
  res/css/structures/_RoomView.pcss
  res/css/views/beta/_BetaCard.pcss
  res/css/views/dialogs/_InviteDialog.pcss
  res/css/views/dialogs/_SpotlightDialog.pcss
  res/css/views/dialogs/security/_AccessSecretStorageDialog.pcss
  res/css/views/elements/_GenericEventListSummary.pcss
  res/css/views/elements/_ReplyChain.pcss
  res/css/views/messages/_EventTileBubble.pcss
  res/css/views/messages/_ViewSourceEvent.pcss
  res/css/views/right_panel/_BaseCard.pcss
  res/css/views/right_panel/_ThreadPanel.pcss
  res/css/views/right_panel/_UserInfo.pcss
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/_IRCLayout.pcss
  res/css/views/settings/_FontScalingPanel.pcss
  res/css/views/settings/_ProfileSettings.pcss
  res/css/views/settings/tabs/_SettingsSection.pcss
  res/css/views/settings/tabs/_SettingsTab.pcss
Labels: Z-Community-PR, T-Task

#11044 Add config to skip widget_build_url for DM rooms
  src/IConfigOptions.ts
  src/LegacyCallHandler.tsx
  src/utils/WellKnownUtils.ts
  src/widgets/ManagedHybrid.ts
  test/widgets/ManagedHybrid-test.ts
Labels: T-Enhancement

#11048 Remove deprecated `intentionalMentions` client start option
  src/MatrixClientPeg.ts
Labels: T-Task

#11015 Use `getShowSasCallbacks()` and `getReciprocateQrCodeCallbacks()`
  src/components/views/right_panel/VerificationPanel.tsx
  test/components/views/right_panel/VerificationPanel-test.tsx
Labels: T-Task

#11014 Update voice broadcast redaction to use MSC3912 `with_rel_type` instead of `with_relations`
  src/components/views/dialogs/ConfirmRedactDialog.tsx
  test/components/views/dialogs/ConfirmRedactDialog-test.tsx
Labels: T-Enhancement

#11007 OIDC: add config flag
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Task

#10810 Fix translucent `TextualEvent` on search results panel
  cypress/e2e/timeline/timeline.spec.ts
  res/css/views/messages/_TextualEvent.pcss
Labels: Z-Community-PR, T-Defect

#11059 Fix: "manually verify by text" does nothing
  src/components/views/dialogs/ManualDeviceKeyVerificationDialog.tsx
Labels: T-Defect

#11060 Matrix matrix scheme permalink constructor not stripping query params
  src/utils/permalinks/MatrixSchemePermalinkConstructor.ts
  test/utils/permalinks/MatrixSchemePermalinkConstructor-test.ts
Labels: T-Defect

#11049 Allow image pasting in rich text mode in RTE
  package.json
  src/components/views/rooms/wysiwyg_composer/SendWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/components/PlainTextComposer.tsx
  src/components/views/rooms/wysiwyg_composer/components/WysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useInputEventProcessor.ts
  test/components/views/rooms/wysiwyg_composer/hooks/useInputEventProcessor-test.tsx
  yarn.lock
Labels: T-Enhancement

#10365 Show room options menu if "UIComponent.roomOptionsMenu" is enabled
  src/components/views/dialogs/spotlight/RoomResultContextMenus.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomTile.tsx
  src/settings/UIFeature.ts
  test/components/views/dialogs/spotlight/RoomResultContextMenus-test.tsx
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/RoomTile-test.tsx
Labels: Z-Community-PR, T-Enhancement, A-Timesheet-1

#10996 Remove references to `VerificationBase`
  src/components/views/dialogs/IncomingSasDialog.tsx
  test/components/views/dialogs/IncomingSasDialog-test.tsx
  test/components/views/right_panel/VerificationPanel-test.tsx
Labels: T-Task

#11056 Allow image pasting in plain mode in RTE
  src/components/views/rooms/wysiwyg_composer/components/PlainTextComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useInputEventProcessor.ts
  src/components/views/rooms/wysiwyg_composer/hooks/usePlainTextListeners.ts
  src/components/views/rooms/wysiwyg_composer/hooks/utils.ts
  test/components/views/rooms/wysiwyg_composer/components/PlainTextComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/hooks/utils-test.tsx
Labels: T-Enhancement

#11052 Use new api `CryptoApi.getCrossSigningStatus` in `CrossSigningPanel`
  src/components/views/settings/CrossSigningPanel.tsx
  test/components/views/settings/CrossSigningPanel-test.tsx
  test/test-utils/client.ts
Labels: T-Task

#11053 OIDC: add delegatedauthentication to validated server config
  src/utils/AutoDiscoveryUtils.tsx
  src/utils/ValidatedServerConfig.ts
  test/utils/AutoDiscoveryUtils-test.tsx
Labels: T-Enhancement

#11073 OIDC: test coverage for error cases in `Login.tsx`
  test/components/structures/auth/Login-test.tsx
Labels: T-Task

#11069 GHA: require kiwi creds in cypress.yaml
  .github/workflows/cypress.yaml
Labels: T-Task

#11042 Conform to the naming policy - AppsContainer resizer
  cypress/e2e/widgets/layout.spec.ts
  res/css/views/rooms/_AppsDrawer.pcss
  src/components/views/rooms/AppsDrawer.tsx
  test/components/views/elements/AppTile-test.tsx
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
Labels: Z-Community-PR, T-Task

#11070 Allow specifying help URLs in config.json
  src/IConfigOptions.ts
  src/SdkConfig.ts
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  test/components/structures/MatrixChat-test.tsx
Labels: T-Enhancement

#11086 Cypress: improve secure key backup test
  cypress/e2e/crypto/crypto.spec.ts
Labels: T-Task

#11071 Don't warn about the effects of redacting state events when redacting non-state-events
  src/components/views/dialogs/ConfirmAndWaitRedactDialog.tsx
  src/components/views/dialogs/ConfirmRedactDialog.tsx
  src/components/views/messages/EditHistoryMessage.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#11080 Use `crypto.isCrossSigningReady` in `CrossSigningPanel`
  src/components/views/settings/CrossSigningPanel.tsx
  test/components/views/settings/CrossSigningPanel-test.tsx
  test/test-utils/client.ts
Labels: T-Task

#10954 Fix visual regressions around widget permissions
  res/css/_components.pcss
  res/css/components/views/elements/_AppPermission.pcss
  res/css/components/views/elements/_AppWarning.pcss
  res/css/views/rooms/_AppsDrawer.pcss
  res/img/feather-customised/help-circle.svg
  src/components/views/elements/AppPermission.tsx
  test/components/views/elements/AppTile-test.tsx
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
Labels: Z-Community-PR, T-Enhancement

#10986 Prefer MatrixClientContext over MatrixClientPeg
  src/components/structures/UserView.tsx
  src/components/views/messages/EditHistoryMessage.tsx
  src/components/views/right_panel/EncryptionPanel.tsx
  src/components/views/settings/tabs/room/BridgeSettingsTab.tsx
  src/components/views/settings/tabs/room/NotificationSettingsTab.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/components/views/settings/tabs/room/VoipRoomSettingsTab.tsx
  src/components/views/settings/tabs/user/AppearanceUserSettingsTab.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/components/views/settings/tabs/user/VoiceUserSettingsTab.tsx
  src/hooks/useIsInitialSyncComplete.ts
  src/hooks/useUserOnboardingContext.ts
  src/voice-broadcast/components/VoiceBroadcastBody.tsx
  test/components/views/settings/tabs/room/BridgeSettingsTab-test.tsx
  test/components/views/settings/tabs/room/RolesRoomSettingsTab-test.tsx
  test/components/views/settings/tabs/user/AppearanceUserSettingsTab-test.tsx
  test/components/views/user-onboarding/UserOnboardingPage-test.tsx
  test/test-utils/wrappers.tsx
  test/voice-broadcast/components/VoiceBroadcastBody-test.tsx
Labels: T-Task

#11090 Fix slash commands not being enabled in certain cases
  src/SlashCommands.tsx
  src/autocomplete/CommandProvider.tsx
  src/components/views/dialogs/SlashCommandHelpDialog.tsx
  src/components/views/rooms/BasicMessageComposer.tsx
Labels: T-Defect

#11050 Remove references to `VerificationRequest`
  cypress/e2e/crypto/complete-security.spec.ts
  cypress/e2e/crypto/crypto.spec.ts
  cypress/e2e/crypto/utils.ts
  src/components/structures/auth/SetupEncryptionBody.tsx
  src/components/views/dialogs/VerificationRequestDialog.tsx
  src/components/views/dialogs/devtools/VerificationExplorer.tsx
  src/components/views/messages/MKeyVerificationConclusion.tsx
  src/components/views/messages/MKeyVerificationRequest.tsx
  src/components/views/right_panel/EncryptionPanel.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/right_panel/VerificationPanel.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/components/views/toasts/VerificationRequestToast.tsx
  src/stores/SetupEncryptionStore.ts
  src/stores/right-panel/RightPanelStoreIPanelState.ts
  src/verification.ts
  test/components/views/messages/MKeyVerificationRequest-test.tsx
  test/components/views/right_panel/VerificationPanel-test.tsx
  test/components/views/toasts/VerificationRequestToast-test.tsx
  test/components/views/toasts/__snapshots__/VerificationRequestToast-test.tsx.snap
Labels: T-Task

#9143 Reduce volume of ring sounds to normalised levels
  res/media/callend.mp3
  res/media/callend.ogg
  res/media/message.mp3
  res/media/message.ogg
  res/media/ring.mp3
  res/media/ring.ogg
  res/media/ringback.mp3
  res/media/ringback.ogg
Labels: Z-Community-PR, T-Defect

#11064 Allow maintaining a different right panel width for thread panels
  src/components/structures/MainSplit.tsx
  src/components/structures/RoomView.tsx
  src/contexts/RoomContext.ts
  test/components/structures/MainSplit-test.tsx
  test/components/structures/RoomView-test.tsx
  test/components/structures/__snapshots__/MainSplit-test.tsx.snap
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/test-utils/room.ts
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#11092 Use new accessors for `VerificationRequest`
  src/components/structures/auth/SetupEncryptionBody.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/stores/SetupEncryptionStore.ts
  src/verification.ts
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Task

#11076 `CreateKeyBackupDialog.tsx`: Remove logic for servers which are not supporting cross-signing
  src/async-components/views/dialogs/security/CreateKeyBackupDialog.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/security/CreateKeyBackupDialog-test.tsx
  test/components/views/dialogs/security/__snapshots__/CreateKeyBackupDialog-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Task

#11002 Conform class names of `mx_AppTileBody` for a widget and PiP widget to our naming policy
  res/css/views/rooms/_AppsDrawer.pcss
  src/components/views/elements/AppTile.tsx
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
Labels: Z-Community-PR, T-Task

#11089 Implement new model, hooks and reconcilation code for new GYU notification settings
  src/hooks/useAsyncRefreshMemo.ts
  src/hooks/useNotificationSettings.tsx
  src/hooks/usePushers.ts
  src/hooks/useThreepids.ts
  src/models/notificationsettings/NotificationSettings.ts
  src/models/notificationsettings/PushRuleDiff.ts
  src/models/notificationsettings/PushRuleMap.ts
  src/models/notificationsettings/reconcileNotificationSettings.ts
  src/models/notificationsettings/toNotificationSettings.ts
  src/notifications/NotificationUtils.ts
  test/hooks/useNotificationSettings-test.tsx
  test/models/notificationsettings/NotificationSettings-test.ts
  test/models/notificationsettings/pushrules_default.json
  test/models/notificationsettings/pushrules_default_new.json
  test/models/notificationsettings/pushrules_sample.json
Labels: T-Enhancement

#11098 Update rich text editor dependency and associated changes
  package.json
  src/components/views/rooms/wysiwyg_composer/components/PlainTextComposer.tsx
  src/components/views/rooms/wysiwyg_composer/components/WysiwygAutocomplete.tsx
  src/components/views/rooms/wysiwyg_composer/components/WysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/usePlainTextListeners.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
  src/components/views/rooms/wysiwyg_composer/utils/autocomplete.ts
  test/components/views/rooms/wysiwyg_composer/components/WysiwygAutocomplete-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/hooks/useSuggestion-test.tsx
  test/components/views/rooms/wysiwyg_composer/utils/autocomplete-test.ts
  yarn.lock
Labels: T-Enhancement

#11102 Fix style inconsistencies on SecureBackupPanel
  src/components/views/settings/SecureBackupPanel.tsx
Labels: Z-Community-PR, T-Defect

#11104 Remove new room breadcrumbs
  res/css/_components.pcss
  res/css/views/rooms/_RecentlyViewedButton.pcss
  src/components/structures/LeftPanel.tsx
  src/components/views/rooms/RecentlyViewedButton.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/BreadcrumbsStore.ts
  test/components/views/settings/tabs/user/__snapshots__/PreferencesUserSettingsTab-test.tsx.snap
  test/stores/BreadcrumbsStore-test.ts
Labels: T-Enhancement

#11110 Speed up `waitForMember` if user already in room
  src/utils/membership.ts
  test/utils/membership-test.ts
Labels: T-Task

#11099 Fix RoomView ignoring alias lookup errors due to them not knowing the roomId
  src/components/structures/RoomView.tsx
  test/components/structures/RoomView-test.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
Labels: T-Defect

#11107 Fix access to deprecated methods in `SetupEncryptionStore`
  src/stores/SetupEncryptionStore.ts
  test/stores/SetupEncryptionStore-test.ts
  test/test-utils/test-utils.ts
Labels: T-Task

#11118 Mark debug logging with distinct letter
  src/rageshake/rageshake.ts
Labels: T-Task

#11106 Add at room avatar for RTE
  src/components/views/rooms/wysiwyg_composer/utils/autocomplete.ts
  test/components/views/rooms/wysiwyg_composer/utils/autocomplete-test.ts
Labels: T-Enhancement

#11111 Increase RTE resilience
  src/components/views/rooms/wysiwyg_composer/DynamicImportWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/SendWysiwygComposer.tsx
Labels: T-Defect

#11124 Improve message body output from plain text editor
  src/components/views/rooms/wysiwyg_composer/utils/createMessageContent.ts
  test/components/views/rooms/wysiwyg_composer/utils/createMessageContent-test.ts
Labels: T-Enhancement

#11117 Consider the unthreaded read receipt for Unread dot state
  src/Unread.ts
  test/Unread-test.ts
Labels: T-Defect

#11115 Handle permalinks in room topic
  src/components/views/elements/RoomTopic.tsx
  test/components/views/elements/RoomTopic-test.tsx
Labels: T-Enhancement

#11120 Add .well-known config option to force disable encryption on room creation
  src/components/views/dialogs/CreateRoomDialog.tsx
  src/createRoom.ts
  src/utils/WellKnownUtils.ts
  src/utils/room/shouldForceDisableEncryption.ts
  src/utils/rooms.ts
  test/components/views/dialogs/CreateRoomDialog-test.tsx
  test/createRoom-test.ts
  test/utils/room/shouldForceDisableEncryption-test.ts
  test/utils/rooms-test.ts
Labels: T-Enhancement

#11122 Disable encryption toggle in room settings when force disabled
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/tabs/room/SecurityRoomSettingsTab-test.tsx
Labels: T-Enhancement

#11123 Cypress test for incoming verification requests
  cypress/e2e/crypto/complete-security.spec.ts
  cypress/e2e/crypto/crypto.spec.ts
  cypress/e2e/crypto/utils.ts
  cypress/e2e/crypto/verification.spec.ts
  cypress/support/toasts.ts
  cypress/support/util.ts
Labels: T-Task

#11088 OIDC: Check static client registration and add login flow
  src/IConfigOptions.ts
  src/Login.ts
  src/components/structures/auth/Login.tsx
  src/utils/AutoDiscoveryUtils.tsx
  src/utils/ValidatedServerConfig.ts
  src/utils/oidc/error.ts
  src/utils/oidc/registerClient.ts
  test/components/structures/auth/Login-test.tsx
  test/test-utils/test-utils.ts
  test/utils/oidc/registerClient-test.ts
Labels: T-Enhancement

#11100 Conform more of the codebase to `strictNullChecks`
  src/HtmlUtils.tsx
  src/ScalarMessaging.ts
  src/async-components/views/dialogs/security/CreateKeyBackupDialog.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ScrollPanel.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/structures/UserView.tsx
  src/components/views/context_menus/WidgetContextMenu.tsx
  src/components/views/dialogs/BugReportDialog.tsx
  src/components/views/dialogs/ConfirmAndWaitRedactDialog.tsx
  src/components/views/messages/MKeyVerificationRequest.tsx
  src/components/views/room_settings/UrlPreviewSettings.tsx
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/settings/ProfileSettings.tsx
  test/settings/handlers/DeviceSettingsHandler-test.ts
  test/stores/room-list/MessagePreviewStore-test.ts
Labels: T-Task

#11127 Fix server picker not allowing you to switch from custom to default
  src/components/views/dialogs/ServerPickerDialog.tsx
  test/components/views/dialogs/ServerPickerDialog-test.tsx
Labels: T-Defect

#11126 Unit test post-login security setup flows in `MatrixChat`
  test/components/structures/MatrixChat-test.tsx
Labels: T-Task

#11074 OIDC: attempt dynamic client registration
  src/components/structures/auth/Login.tsx
  src/utils/oidc/error.ts
  src/utils/oidc/registerClient.ts
  test/components/structures/auth/Login-test.tsx
  test/utils/oidc/registerClient-test.ts
Labels: T-Enhancement

#11129 VerificationPanel: avoid use of `getStoredDevice`
  src/components/views/right_panel/VerificationPanel.tsx
  src/components/views/verification/VerificationShowSas.tsx
  test/components/views/right_panel/VerificationPanel-test.tsx
Labels: T-Task

#11128 Fix caret jump when backspacing into empty line at beginning of editor
  src/editor/caret.ts
  test/editor/caret-test.ts
Labels: T-Defect

#11142 Fix cypress tests
  .github/workflows/cypress.yaml
Labels: T-Task

#11144 Temporarily skip broken cypress analytics toast tests
  cypress/e2e/settings/security-user-settings-tab.spec.ts
  cypress/e2e/toasts/analytics-toast.spec.ts
Labels: T-Task

#11114 Prevent auto-translation within composer
  src/components/views/rooms/BasicMessageComposer.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
Labels: T-Defect

#11133 Fix spurious notifications on non-live events
  src/Notifier.ts
  test/Notifier-test.ts
Labels: T-Defect

#11125 Don't setup keys on login when encryption is force disabled
  src/components/structures/MatrixChat.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/createRoom.ts
  src/utils/crypto/shouldForceDisableEncryption.ts
  src/utils/crypto/shouldSkipSetupEncryption.ts
  src/utils/rooms.ts
  test/components/structures/MatrixChat-test.tsx
  test/utils/crypto/shouldForceDisableEncryption-test.ts
Labels: X-Release-Blocker, T-Enhancement

#11132 Update linkify to 4.1.1
  package.json
  src/linkify-matrix.ts
  test/linkify-matrix-test.ts
  yarn.lock
Labels: T-Defect

#11134 Conform more of the codebase to strictNullChecks
  src/MatrixClientPeg.ts
  src/Searching.ts
  src/components/structures/RoomView.tsx
  src/components/structures/ScrollPanel.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/messages/MjolnirBody.tsx
  src/components/views/rooms/RoomListHeader.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/stores/ModalWidgetStore.ts
  src/stores/right-panel/RightPanelStore.ts
  src/utils/AutoDiscoveryUtils.tsx
  src/utils/DecryptFile.ts
  src/utils/StorageManager.ts
  src/utils/promise.ts
  test/utils/media/requestMediaPermissions-test.tsx
Labels: T-Task

#11130 Cypress test: can't switch back to default homeserver
  cypress/e2e/login/login.spec.ts
Labels: T-Task

#11143 Unit test token login flow in `MatrixChat`
  src/Lifecycle.ts
  test/components/structures/MatrixChat-test.tsx
Labels: T-Task

#11135 Conform more of the codebase to strictNullChecks
  src/AddThreepid.ts
  src/stores/right-panel/RightPanelStore.ts
Labels: T-Task

#11140 Only trap escape key for cancel reply if there is a reply
  src/components/views/rooms/SendMessageComposer.tsx
Labels: T-Defect

#11141 Use new `CryptoEvent.VerificationRequestReceived` event
  src/components/structures/MatrixChat.tsx
  src/components/views/dialogs/devtools/VerificationExplorer.tsx
  src/stores/SetupEncryptionStore.ts
  src/stores/right-panel/RightPanelStore.ts
Labels: T-Task

#11155 Consider the empty push rule actions array equiv to deprecated dont_notify
  src/RoomNotifs.ts
  test/RoomNotifs-test.ts
  test/test-utils/test-utils.ts
Labels: T-Defect

#10517 Apply `strictNullChecks` to `src/components/views/spaces/*`
  src/components/views/spaces/QuickSettingsButton.tsx
  src/components/views/spaces/SpacePublicShare.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  src/settings/Settings.tsx
  src/theme.ts
  test/components/views/spaces/QuickSettingsButton-test.tsx
  test/theme-test.ts
Labels: T-Task

#11153 Fix: cypress `toasts/analytics-toast.spec.ts` failures
  cypress/e2e/settings/security-user-settings-tab.spec.ts
  cypress/e2e/toasts/analytics-toast.spec.ts
  cypress/support/login.ts
Labels: T-Task

#11096 OIDC: navigate to authorization endpoint
  res/css/structures/auth/_Login.pcss
  src/components/structures/auth/Login.tsx
  src/utils/oidc/authorize.ts
  src/utils/oidc/registerClient.ts
  test/components/structures/auth/Login-test.tsx
  test/utils/oidc/authorize-test.ts
Labels: T-Enhancement

#11157 Fix spurious error sending receipt in thread errors
  src/components/structures/TimelinePanel.tsx
Labels: T-Defect

#11161 Strictify Search.ts
  src/Searching.ts
Labels: T-Task

#11162 Conform more of the codebase to strict types
  src/AddThreepid.ts
  src/Modal.tsx
  src/NodeAnimator.tsx
  src/SecurityManager.ts
  src/SlashCommands.tsx
  src/autocomplete/EmojiProvider.tsx
  src/emoji.ts
  src/mjolnir/Mjolnir.ts
  src/stores/right-panel/RightPanelStore.ts
Labels: T-Task

#11008 GYU: Account Notification Settings
  res/css/_components.pcss
  res/css/views/settings/_NotificationPusherSettings.pcss
  res/css/views/settings/_NotificationSettings2.pcss
  res/css/views/settings/tabs/_SettingsBanner.pcss
  res/css/views/settings/tabs/_SettingsIndent.pcss
  res/img/element-icons/new-and-improved.svg
  src/components/views/elements/Tag.tsx
  src/components/views/elements/TagComposer.tsx
  src/components/views/settings/notifications/NotificationPusherSettings.tsx
  src/components/views/settings/notifications/NotificationSettings2.tsx
  src/components/views/settings/shared/SettingsBanner.tsx
  src/components/views/settings/shared/SettingsIndent.tsx
  src/components/views/settings/shared/SettingsSection.tsx
  src/components/views/settings/tabs/user/NotificationUserSettingsTab.tsx
  src/hooks/useNotificationSettings.tsx
  src/i18n/strings/en_EN.json
  src/models/notificationsettings/reconcileNotificationSettings.ts
  src/models/notificationsettings/toNotificationSettings.ts
  src/settings/Settings.tsx
  test/components/views/settings/notifications/Notifications2-test.tsx
  test/components/views/settings/notifications/__snapshots__/Notifications2-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/LabsUserSettingsTab-test.tsx.snap
  test/models/notificationsettings/NotificationSettings-test.ts
  test/models/notificationsettings/pushrules_bug_botnotices.json
  test/predictableRandom.ts
Labels: T-Enhancement

#11154 OIDC: extract success/failure handlers from token login function
  src/Lifecycle.ts
  src/components/structures/MatrixChat.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#11165 Strictify Timeline Panel
  src/components/structures/TimelinePanel.tsx
Labels: T-Task

#11167 Replace `beginKeyVerification` with `startVerification`
  src/components/views/right_panel/VerificationPanel.tsx
Labels: T-Task
