Repository matrix-org/matrix-react-sdk, pull requests merged in 2023-11, with the labels that each got.

#11824 Switch to updating presence via /sync calls instead of PUT /presence
  src/Presence.ts
Labels: T-Defect

#11799 Allow adding extra icons to the room header
  package.json
  src/components/structures/RoomView.tsx
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/contexts/RoomContext.ts
  src/dispatcher/actions.ts
  src/stores/RoomViewStore.tsx
  test/components/structures/RoomView-test.tsx
  test/components/views/rooms/LegacyRoomHeader-test.tsx
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/stores/RoomViewStore-test.ts
  test/test-utils/room.ts
  yarn.lock
Labels: Z-Community-PR, T-Enhancement

#11826 Fix a test that would otherwise be broken by matrix-js-sdk#3817
  test/components/structures/TimelinePanel-test.tsx
Labels: T-Task

#11828 Run Cypress on Rust crypto
  .github/workflows/cypress.yaml
Labels: T-Task

#11831 Fix rightpanel hiding scrollbar
  res/css/views/right_panel/_BaseCard.pcss
Labels: X-Release-Blocker, T-Defect, backport staging

#11829 Make video rooms compatible with matrix RTC
  src/models/Call.ts
  src/stores/WidgetStore.ts
  test/models/Call-test.ts
Labels: T-Task

#11833 Remove Kiwi upload
  .github/workflows/cypress.yaml
Labels: T-Task

#11803 Add e2e tests for the knocking feature
  cypress/e2e/create-room/create-room.spec.ts
  cypress/e2e/knock/create-knock-room.spec.ts
  cypress/e2e/knock/knock-into-room.spec.ts
  cypress/e2e/knock/manage-knocks.spec.ts
  cypress/e2e/spotlight/spotlight.spec.ts
  cypress/e2e/utils.ts
  cypress/e2e/widgets/events.spec.ts
  cypress/support/settings.ts
Labels: T-Task

#11830 Fill cypress test `high-level.spec.ts` > `A receipt for the last unimportant event makes the room read, even if all are unimportant`
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11838 Revert back to poor-man's parallelization for Cypress tests
  .github/workflows/cypress.yaml
Labels: T-Task

#11840 Remove cypress cloud from dependencies
  .github/workflows/cypress.yaml
  cypress/plugins/index.ts
  cypress/support/e2e.ts
  package.json
  yarn.lock
Labels: T-Task

#11843 Use command prefix in cypress.yaml
  .github/workflows/cypress.yaml
Labels: T-Task

#11835 Adapt the rendering of extra icons in the room header
  package.json
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/components/views/rooms/RoomHeader.tsx
  test/components/views/rooms/LegacyRoomHeader-test.tsx
  test/components/views/rooms/RoomHeader-test.tsx
  yarn.lock
Labels: Z-Community-PR, T-Enhancement

#11781 Enable tests fixed by https://github.com/matrix-org/matrix-js-sdk/pull/3817
  cypress/e2e/read-receipts/editing-messages.spec.ts
  cypress/e2e/read-receipts/high-level.spec.ts
  cypress/e2e/read-receipts/redactions.spec.ts
Labels: T-Task

#11839 Test for adding and removing a reaction in a thread
  cypress/e2e/read-receipts/reactions.spec.ts
Labels: T-Task

#11848 Disable test 'Paging up to find old threads' on Rust due to flakes
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11837 Add feature flag for disabling encryption in Element Call
  src/i18n/strings/en_EN.json
  src/models/Call.ts
  src/settings/Settings.tsx
  test/models/Call-test.ts
Labels: T-Enhancement

#11825 New release automations
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release-gitflow.yml
  .github/workflows/release.yml
Labels: T-Task

#11852 Disable Percy
  .github/workflows/cypress.yaml
  .github/workflows/element-web.yaml
  README.md
  docs/cypress.md
Labels: T-Task

#11849 Disable 'A room with an edit ... restart' because flaking
  cypress/e2e/read-receipts/editing-messages.spec.ts
Labels: T-Task

#11854 Disable 'Looking in thread view to find old threads...' because of flakes
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11823 Update room summary card header
  cypress/e2e/crypto/crypto.spec.ts
  res/css/views/right_panel/_RoomSummaryCard.pcss
  src/components/views/right_panel/RoomSummaryCard.tsx
  test/components/views/right_panel/RoomSummaryCard-test.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
Labels: T-Enhancement

#11847 Fix a test that was expecting an edit to be considered unread
  cypress/e2e/read-receipts/editing-messages.spec.ts
Labels: T-Task

#11834 Report crypto sdk in posthog
  src/PosthogAnalytics.ts
  test/PosthogAnalytics-test.ts
Labels: T-Task

#11862 fix broken warning icon
  res/img/feather-customised/warning-triangle.svg
Labels: T-Defect

#11859 Use the correct video call icon variant
  src/components/views/rooms/RoomHeader.tsx
Labels: T-Defect

#11861 New right panel: fix button alignment in memberlist
  res/css/views/right_panel/_BaseCard.pcss
  res/css/views/right_panel/_RoomSummaryCard.pcss
  src/components/views/right_panel/BaseCard.tsx
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
Labels: T-Defect

#11866 Room header: do not collapse avatar or facepile
  res/css/structures/_RightPanel.pcss
  res/css/views/rooms/_RoomHeader.pcss
Labels: T-Defect

#11865 Fix: Emoji cause topics being cut off in new room header
  res/css/views/rooms/_RoomHeader.pcss
  src/components/views/rooms/RoomHeader.tsx
Labels: T-Defect

#11764 Enable tests fixed by https://github.com/matrix-org/matrix-js-sdk/pull/3800
  cypress/e2e/read-receipts/redactions.spec.ts
Labels: T-Task

#11885 Track threads button interaction with Posthog from new room header
  src/components/views/rooms/RoomHeader.tsx
Labels: T-Task

#11812 Update RoomSummaryCard navigation links
  cypress/e2e/crypto/crypto.spec.ts
  cypress/e2e/invite/invite-dialog.spec.ts
  cypress/e2e/lazy-loading/lazy-loading.spec.ts
  cypress/e2e/polls/pollHistory.spec.ts
  cypress/e2e/right-panel/file-panel.spec.ts
  cypress/e2e/right-panel/right-panel.spec.ts
  package.json
  res/css/views/right_panel/_BaseCard.pcss
  res/css/views/right_panel/_RoomSummaryCard.pcss
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/i18n/strings/en_EN.json
  src/utils/room/canInviteTo.ts
  src/utils/room/inviteToRoom.ts
  src/utils/room/tagRoom.ts
  test/components/structures/RightPanel-test.tsx
  test/components/views/right_panel/RoomSummaryCard-test.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/rooms/LegacyRoomHeader-test.tsx
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
  test/utils/room/canInviteTo-test.ts
  test/utils/room/inviteToRoom-test.ts
  test/utils/room/tagRoom-test.ts
  yarn.lock
Labels: T-Enhancement

#11858 Run Localazy Download on a schedule 3 times a week instead of during release process
  .github/workflows/localazy_download.yaml
Labels: T-Task

#11890 Disable flaky test 'Reading a thread after a reaction to a redacted message marks the thread as read'
  cypress/e2e/read-receipts/redactions.spec.ts
Labels: T-Task

#11850 Remove unused dependencies and add transitive deps
  package.json
  yarn.lock
Labels: T-Task

#11888 Fix call encryption settings flag update not having effect on running…
  src/models/Call.ts
Labels: T-Defect

#11863 Use knapsack pro to speed up cypress tests
  .github/workflows/cypress.yaml
  README.md
  package.json
  yarn.lock
Labels: T-Task

#11894 Fix broken cypress tests
  .github/workflows/cypress.yaml
Labels: T-Task

#11892 Bump matrix-wysiwyg to 2.17.0
  package.json
  yarn.lock
Labels: T-Task

#11904 EditWysiwygComposer-test: wait for the wasm to load in beforeAll
  test/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx
Labels: T-Task

#11909 Disable axe check which only fails in Chrome
  cypress/e2e/spaces/spaces.spec.ts
Labels: T-Task

#11869 Load web workers and worklets in a way that Webpack 5 can bundle them
  __mocks__/workerFactoryMock.js
  __mocks__/workerMock.js
  cypress/tsconfig.json
  jest.config.ts
  src/BlurhashEncoder.ts
  src/WorkerManager.ts
  src/audio/Playback.ts
  src/audio/VoiceRecording.ts
  src/audio/recorderWorkletFactory.ts
  src/utils/createMatrixClient.ts
  src/workers/blurhashWorkerFactory.ts
  src/workers/indexeddbWorkerFactory.ts
  src/workers/playbackWorkerFactory.ts
  test/WorkerManager-test.ts
  tsconfig.json
Labels: T-Task

#11898 Reduce amount of log spam
  src/MatrixClientPeg.ts
  src/indexing/EventIndex.ts
  src/stores/CallStore.ts
  src/utils/exportUtils/Exporter.ts
Labels: T-Task

#11900 Remove workaround for rust-SDK bug
  cypress/support/bot.ts
Labels: T-Task

#11895 Fix ended polls overlapping event bubbles
  res/css/views/rooms/_EventBubbleTile.pcss
  src/components/views/messages/MPollEndBody.tsx
  test/components/views/messages/__snapshots__/MPollEndBody-test.tsx.snap
Labels: T-Defect

#11893 Fix: set disabled state on invite to room button in memberlist
  src/components/views/rooms/MemberList.tsx
  test/components/views/rooms/MemberList-test.tsx
Labels: T-Defect

#11896 Knapsack Pro: Provide proper commit hash
  .github/workflows/cypress.yaml
Labels: T-Task

#11899 Fix "not attempting encryption" warning
  src/utils/tokens/tokens.ts
Labels: T-Defect

#11870 Add ringing for matrixRTC
  src/Notifier.ts
  src/models/Call.ts
  src/toasts/IncomingCallToast.tsx
  test/Notifier-test.ts
  test/createRoom-test.ts
  test/models/Call-test.ts
  test/toasts/IncomingCallToast-test.tsx
Labels: T-Enhancement

#11912 Add Playwright end to end testing
  .eslintrc.js
  .github/workflows/end-to-end-tests.yaml
  package.json
  playwright.config.ts
  playwright/.gitignore
  playwright/e2e/launch.spec.ts
  playwright/tsconfig.json
  yarn.lock
Labels: T-Task

#11911 Fix: Video Room Chat Header Button Removed
  package.json
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomHeader/VideoRoomChatButton.tsx
  test/components/views/rooms/RoomHeader/VideoRoomChatButton-test.tsx
  test/components/views/rooms/RoomHeader/__snapshots__/VideoRoomChatButton-test.tsx.snap
  yarn.lock
Labels: T-Defect

#11914 Remove Quote from MessageContextMenu as it is unsupported by WYSIWYG
  src/components/views/context_menus/MessageContextMenu.tsx
  src/dispatcher/payloads/ComposerInsertPayload.ts
Labels: T-Deprecation

#11910 Add menu for legacy and element call in 1:1 rooms
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/LegacyRoomHeader-test.tsx
Labels: T-Enhancement

#11916 Update open in other tab message
  src/components/structures/auth/SessionLockStolenView.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/MatrixChat-test.tsx
  test/components/structures/__snapshots__/MatrixChat-test.tsx.snap
Labels: T-Enhancement

#11913 Add a login test against Synapse to Playwright
  cypress/e2e/login/login.spec.ts
  cypress/e2e/login/soft_logout.spec.ts
  package.json
  playwright/.gitignore
  playwright/e2e/launch.spec.ts
  playwright/e2e/login/login.spec.ts
  playwright/element-web-test.ts
  playwright/plugins/docker/index.ts
  playwright/plugins/synapse/index.ts
  playwright/plugins/synapse/templates/COPYME/README.md
  playwright/plugins/synapse/templates/COPYME/homeserver.yaml
  playwright/plugins/synapse/templates/COPYME/log.config
  playwright/plugins/synapse/templates/consent/README.md
  playwright/plugins/synapse/templates/consent/homeserver.yaml
  playwright/plugins/synapse/templates/consent/log.config
  playwright/plugins/synapse/templates/consent/res/templates/privacy/en/1.0.html
  playwright/plugins/synapse/templates/consent/res/templates/privacy/en/success.html
  playwright/plugins/synapse/templates/default/README.md
  playwright/plugins/synapse/templates/default/homeserver.yaml
  playwright/plugins/synapse/templates/default/log.config
  playwright/plugins/synapse/templates/email/README.md
  playwright/plugins/synapse/templates/email/homeserver.yaml
  playwright/plugins/synapse/templates/email/log.config
  playwright/plugins/utils/homeserver.ts
  playwright/plugins/utils/port.ts
  yarn.lock
Labels: T-Task

#11918 Fix misunderstanding of functional members
  src/models/Call.ts
  src/utils/room/getJoinedNonFunctionalMembers.ts
  test/models/Call-test.ts
Labels: T-Defect

#11919 Run both legacy & rust crypto tests in Playwright
  playwright.config.ts
  playwright/element-web-test.ts
Labels: T-Task

#11921 Set up CI to lint workflows with action-validator
  .github/workflows/static_analysis.yaml
  package.json
  yarn.lock
Labels: T-Task

#11924 Simplify Netlify workflow
  .github/workflows/netlify.yaml
Labels: T-Task

#11920 Migrate email.spec.ts from Cypress to Playwright
  cypress/e2e/register/email.spec.ts
  cypress/plugins/index.ts
  cypress/support/e2e.ts
  package.json
  playwright/e2e/login/login.spec.ts
  playwright/e2e/register/email.spec.ts
  playwright/element-web-test.ts
  playwright/plugins/mailhog/index.ts
  playwright/tsconfig.json
  yarn.lock
Labels: T-Task

#11917 Port remaining login.spec.ts & soft_logout.spec.ts tests from Cypress to Playwright
  cypress/e2e/login/login.spec.ts
  cypress/e2e/login/soft_logout.spec.ts
  cypress/e2e/login/utils.ts
  cypress/plugins/index.ts
  cypress/plugins/oauth_server/index.ts
  package.json
  playwright/e2e/login/login.spec.ts
  playwright/e2e/login/soft_logout.spec.ts
  playwright/e2e/login/utils.ts
  playwright/element-web-test.ts
  playwright/plugins/oauth_server/README.md
  playwright/plugins/oauth_server/index.ts
  playwright/plugins/oauth_server/res/oauth/auth.html
  playwright/plugins/utils/homeserver.ts
  playwright/tsconfig.json
  yarn.lock
Labels: T-Task

#11925 Default to system emoji font
  res/css/views/verification/_VerificationShowSas.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light/css/_light.pcss
  src/components/views/settings/tabs/user/AppearanceUserSettingsTab.tsx
  src/dispatcher/payloads/UpdateSystemFontPayload.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/controllers/SystemFontController.ts
  src/settings/controllers/UseSystemFontController.ts
  src/settings/watchers/FontWatcher.ts
  test/settings/controllers/SystemFontController-test.ts
  test/settings/controllers/UseSystemFontController-test.ts
  test/settings/watchers/FontWatcher-test.tsx
Labels: T-Enhancement

#11928 Fix js-sdk types for TImestampToEventResponse
  test/components/views/messages/DateSeparator-test.tsx
Labels: X-Release-Blocker, T-Task

#11930 Adapt to renaming of release-action workflow
  .github/workflows/release.yml
Labels: T-Task

#11902 Keep device language when it has been previosuly set, after a successful delegated authentication flow that clears localStorage
  src/Lifecycle.ts
  test/components/structures/MatrixChat-test.tsx
Labels: Z-Community-PR, T-Defect

#11935 Default bundled emoji font to on
  cypress/e2e/settings/appearance-user-settings-tab.spec.ts
  src/settings/Settings.tsx
  test/components/structures/__snapshots__/MatrixChat-test.tsx.snap
  test/settings/watchers/FontWatcher-test.tsx
Labels: X-Release-Blocker, T-Task

#11939 Migrate analytics-toast.spec.ts from Cypress to Playwright
  cypress/e2e/toasts/analytics-toast.spec.ts
  playwright/e2e/toasts/analytics-toast.spec.ts
  playwright/element-web-test.ts
  playwright/pages/toasts.ts
Labels: T-Task

#11940 Migrate user-menu.spec.ts from Cypress to Playwright
  cypress/e2e/user-menu/user-menu.spec.ts
  playwright/e2e/user-menu/user-menu.spec.ts
Labels: T-Task

#11937 Migrate update.spec.ts from Cypress to Playwright
  cypress/e2e/update/update.spec.ts
  playwright/e2e/update/update.spec.ts
Labels: T-Task

#11943 Implement dendrite & pinecone support in Playwright
  playwright/e2e/login/login.spec.ts
  playwright/e2e/login/soft_logout.spec.ts
  playwright/e2e/login/utils.ts
  playwright/e2e/register/email.spec.ts
  playwright/element-web-test.ts
  playwright/plugins/homeserver/dendrite/index.ts
  playwright/plugins/homeserver/dendrite/templates/default/dendrite.yaml
  playwright/plugins/homeserver/index.ts
  playwright/plugins/homeserver/synapse/index.ts
  playwright/plugins/homeserver/synapse/templates/COPYME/README.md
  playwright/plugins/homeserver/synapse/templates/COPYME/homeserver.yaml
  playwright/plugins/homeserver/synapse/templates/COPYME/log.config
  playwright/plugins/homeserver/synapse/templates/consent/README.md
  playwright/plugins/homeserver/synapse/templates/consent/homeserver.yaml
  playwright/plugins/homeserver/synapse/templates/consent/log.config
  playwright/plugins/homeserver/synapse/templates/consent/res/templates/privacy/en/1.0.html
  playwright/plugins/homeserver/synapse/templates/consent/res/templates/privacy/en/success.html
  playwright/plugins/homeserver/synapse/templates/default/README.md
  playwright/plugins/homeserver/synapse/templates/default/homeserver.yaml
  playwright/plugins/homeserver/synapse/templates/default/log.config
  playwright/plugins/homeserver/synapse/templates/email/README.md
  playwright/plugins/homeserver/synapse/templates/email/homeserver.yaml
  playwright/plugins/homeserver/synapse/templates/email/log.config
  playwright/plugins/mailhog/index.ts
  playwright/plugins/utils/rand.ts
Labels: T-Task

#11934 Right panel: view third party invite info without clearing history
  src/components/structures/RoomView.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/rooms/ThirdPartyMemberInfo.tsx
  src/dispatcher/actions.ts
  src/stores/right-panel/action-handlers/View3pidInvite.ts
  src/stores/right-panel/action-handlers/index.ts
  test/stores/right-panel/action-handlers/View3pidInvite-test.ts
Labels: T-Enhancement

#11945 Migrate location.spec.ts from Cypress to Playwright
  cypress/e2e/location/location.spec.ts
  playwright/e2e/location/location.spec.ts
  playwright/pages/ElementAppPage.ts
Labels: T-Task

#11953 Migrate one-to-one-chat.spec.ts from Cypress to Playwright
  cypress/e2e/one-to-one-chat/one-to-one-chat.spec.ts
  playwright/e2e/one-to-one-chat/one-to-one-chat.spec.ts
  playwright/element-web-test.ts
  playwright/plugins/homeserver/index.ts
  playwright/plugins/homeserver/synapse/index.ts
Labels: T-Task

#11946 Re-enable Cypress test creating a DM on Rust
  cypress/e2e/crypto/crypto.spec.ts
Labels: T-Task

#11942 Migrate register.spec.ts from Cypress to Playwright
  cypress/e2e/register/register.spec.ts
  playwright.config.ts
  playwright/e2e/register/register.spec.ts
  playwright/element-web-test.ts
  playwright/pages/crypto.ts
  playwright/snapshots/register/register.spec.ts/email-prompt-linux.png
  playwright/snapshots/register/register.spec.ts/registration-linux.png
  playwright/snapshots/register/register.spec.ts/server-picker-linux.png
  playwright/snapshots/register/register.spec.ts/terms-prompt-linux.png
  playwright/snapshots/register/register.spec.ts/use-case-selection-linux.png
Labels: T-Task

#11948 Always allow call.member events on new rooms
  src/createRoom.ts
  test/createRoom-test.ts
Labels: T-Enhancement

#11947 Migrate most of editing.spec.ts from Cypress to Playwright
  cypress/e2e/editing/editing.spec.ts
  playwright/e2e/editing/editing.spec.ts
  playwright/element-web-test.ts
  playwright/global.d.ts
  playwright/pages/ElementAppPage.ts
  playwright/snapshots/editing/editing.spec.ts/message-edit-history-dialog-linux.png
Labels: T-Task

#11956 Update tests in anticipation of matrix-js-sdk#3901
  test/Unread-test.ts
  test/components/views/right_panel/LegacyRoomHeaderButtons-test.tsx
Labels: T-Task

#11951 Room header: make room details toggle accessible by keyboard
  res/css/views/rooms/_RoomHeader.pcss
  src/components/views/rooms/RoomHeader.tsx
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
Labels: T-Defect

#11973 Allow passing knapsack token as secret in workflow
  .github/workflows/cypress.yaml
Labels: T-Task

#11933 Fix: Space scope header overflow
  cypress/e2e/right-panel/right-panel.spec.ts
  res/css/_components.pcss
  res/css/structures/_RightPanel.pcss
  res/css/views/rooms/_MemberInfo.pcss
  res/css/views/rooms/_MemberList.pcss
  res/css/views/rooms/_SpaceScopeHeader.pcss
  res/css/views/rooms/_ThirdPartyMemberInfo.pcss
  src/components/structures/RightPanel.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/rooms/SpaceScopeHeader.tsx
  src/components/views/rooms/ThirdPartyMemberInfo.tsx
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/components/views/rooms/__snapshots__/ThirdPartyMemberInfo-test.tsx.snap
Labels: T-Defect

#11975 Prevent flaky Jest test by pre-loading WASM
  test/components/views/rooms/wysiwyg_composer/utils/createMessageContent-test.ts
Labels: T-Task

#11959 Allow for running playwright tests upstream
  .github/workflows/end-to-end-tests.yaml
Labels: T-Task

#11903 Rewrite doesRoomOrThreadHaveUnreadMessages to use the receipt rewrite from js-sdk
  cypress/e2e/read-receipts/editing-messages.spec.ts
  cypress/e2e/read-receipts/high-level.spec.ts
  cypress/e2e/read-receipts/new-messages.spec.ts
  src/RoomNotifs.ts
  src/Unread.ts
  test/Unread-test.ts
  test/components/views/right_panel/LegacyRoomHeaderButtons-test.tsx
  test/components/views/rooms/EventTile-test.tsx
  test/components/views/rooms/RoomTile-test.tsx
  test/components/views/rooms/__snapshots__/RoomTile-test.tsx.snap
  test/test-utils/threads.ts
Labels: T-Defect

#11949 Migrate settings/* from Cypress to Playwright
  cypress/e2e/settings/appearance-user-settings-tab.spec.ts
  cypress/e2e/settings/device-management.spec.ts
  cypress/e2e/settings/general-room-settings-tab.spec.ts
  cypress/e2e/settings/general-user-settings-tab.spec.ts
  cypress/e2e/settings/preferences-user-settings-tab.spec.ts
  cypress/e2e/settings/security-user-settings-tab.spec.ts
  playwright/docker-entrypoint.sh
  playwright/e2e/editing/editing.spec.ts
  playwright/e2e/settings/appearance-user-settings-tab.spec.ts
  playwright/e2e/settings/device-management.spec.ts
  playwright/e2e/settings/general-room-settings-tab.spec.ts
  playwright/e2e/settings/general-user-settings-tab.spec.ts
  playwright/e2e/settings/preferences-user-settings-tab.spec.ts
  playwright/e2e/settings/security-user-settings-tab.spec.ts
  playwright/e2e/user-onboarding/user-onboarding-new.spec.ts
  playwright/e2e/user-onboarding/user-onboarding-old.spec.ts
  playwright/element-web-test.ts
  playwright/pages/ElementAppPage.ts
  playwright/pages/settings.ts
  playwright/plugins/homeserver/index.ts
  playwright/plugins/homeserver/synapse/index.ts
  playwright/sample-files/riot.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/Appearance-user-settings-tab-should-be-rendered-properly-1-darwin.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/Appearance-user-settings-tab-should-be-rendered-properly-1-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/font-slider-11-darwin.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/font-slider-11-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/font-slider-21-darwin.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/font-slider-21-linux.png
  playwright/snapshots/settings/general-room-settings-tab.spec.ts/General-room-settings-tab-should-be-rendered-properly-1-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-linux.png
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
  playwright/snapshots/settings/security-user-settings-tab.spec.ts/Security-user-settings-tab-with-posthog-enable-b5d89-csLearnMoreDialog-should-be-rendered-properly-1-linux.png
Labels: T-Task

#11971 Playwright - retain video on failure
  playwright.config.ts
Labels: T-Task

#11977 Fix invisible avatar on home page
  src/components/structures/HomePage.tsx
Labels: T-Defect

#11944 Migrate user-view.spec.ts from Cypress to Playwright
  cypress/e2e/user-view/user-view.spec.ts
  playwright/.gitignore
  playwright/e2e/user-view/user-view.spec.ts
  playwright/element-web-test.ts
  playwright/global.d.ts
  playwright/pages/bot.ts
  playwright/snapshots/user-view/user-view.spec.ts/UserView-should-render-the-user-view-as-expected-1-linux.png
  playwright/snapshots/user-view/user-view.spec.ts/user-info-linux.png
Labels: T-Task

#11979 Enable disabled cypress test
  cypress/e2e/crypto/crypto.spec.ts
Labels: T-Task

#11960 Remove call notify limit condition.
  src/models/Call.ts
Labels: T-Task

#11952 Migrate complete-security.spec.ts from Cypress to Playwright
  cypress/e2e/crypto/complete-security.spec.ts
  playwright/e2e/crypto/complete-security.spec.ts
  playwright/e2e/crypto/utils.ts
  playwright/element-web-test.ts
Labels: T-Task

#11343 Deprecate lab experiment 'feature_state_counters'
  res/css/views/rooms/_AuxPanel.pcss
  src/components/views/rooms/AuxPanel.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Task

#11978 Retry flaky tests in Playwright twice (half Cypress)
  playwright.config.ts
Labels: T-Task

#11931 Simplify display of verification requests in timeline
  src/components/views/messages/MKeyVerificationRequest.tsx
  src/events/EventTileFactory.tsx
  src/i18n/strings/en_EN.json
  test/components/views/messages/MKeyVerificationRequest-test.tsx
Labels: T-Defect
