Repository matrix-org/matrix-react-sdk, pull requests merged in 2023-03, with the labels that each got.

#10262 Downgrade matrix-events-sdk, update yarn.lock, remove stub package
  package.json
  src/components/structures/SpaceHierarchy.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  src/components/views/voip/LegacyCallView/LegacyCallViewButtons.tsx
  yarn.lock
Labels: T-Task

#10155 Fix buttons on the room header being compressed due to long room name
  cypress/e2e/create-room/create-room.spec.ts
  res/css/structures/_RightPanel.pcss
  res/css/views/rooms/_RoomHeader.pcss
Labels: Z-Community-PR, T-Defect

#10259 New verification request toast button labels
  src/components/views/toasts/VerificationRequestToast.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#10266 Fix the hidden view source toggle on IRC layout
  cypress/e2e/timeline/timeline.spec.ts
  res/css/views/rooms/_IRCLayout.pcss
Labels: Z-Community-PR, T-Defect

#10261 Add ESLint Jest
  .eslintrc.js
  cypress/e2e/sliding-sync/sliding-sync.ts
  cypress/e2e/spotlight/spotlight.spec.ts
  package.json
  test/ContentMessages-test.ts
  test/DecryptionFailureTracker-test.js
  test/Notifier-test.ts
  test/PosthogAnalytics-test.ts
  test/RoomNotifs-test.ts
  test/ScalarAuthClient-test.ts
  test/SlidingSyncManager-test.ts
  test/Terms-test.tsx
  test/TextForEvent-test.ts
  test/accessibility/KeyboardShortcutUtils-test.ts
  test/components/structures/MessagePanel-test.tsx
  test/components/structures/ThreadView-test.tsx
  test/components/views/auth/RegistrationToken-test.tsx
  test/components/views/dialogs/InteractiveAuthDialog-test.tsx
  test/components/views/dialogs/MessageEditHistoryDialog-test.tsx
  test/components/views/dialogs/__snapshots__/MessageEditHistoryDialog-test.tsx.snap
  test/components/views/dialogs/polls/PollHistoryDialog-test.tsx
  test/components/views/dialogs/polls/__snapshots__/PollHistoryDialog-test.tsx.snap
  test/components/views/elements/EventListSummary-test.tsx
  test/components/views/messages/MBeaconBody-test.tsx
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/messages/MessageActionBar-test.tsx
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/rooms/MemberList-test.tsx
  test/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/LinkModal-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/PlainTextComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/utils/message-test.ts
  test/components/views/settings/devices/DeviceDetailHeading-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/editor/deserialize-test.ts
  test/events/RelationsHelper-test.ts
  test/i18n-test/languageHandler-test.tsx
  test/stores/AutoRageshakeStore-test.ts
  test/stores/SpaceStore-test.ts
  test/stores/room-list/SlidingRoomListStore-test.ts
  test/stores/widgets/StopGapWidgetDriver-test.ts
  test/theme-test.ts
  test/utils/connection-test.ts
  test/utils/device/parseUserAgent-test.ts
  test/utils/export-test.tsx
  test/utils/exportUtils/HTMLExport-test.ts
  test/utils/local-room-test.ts
  test/utils/localRoom/isRoomReady-test.ts
  test/utils/membership-test.ts
  test/utils/notifications-test.ts
  test/voice-broadcast/models/VoiceBroadcastRecording-test.ts
  test/voice-broadcast/stores/VoiceBroadcastRecordingsStore-test.ts
  test/voice-broadcast/utils/setUpVoiceBroadcastPreRecording-test.ts
  yarn.lock
Labels: T-Task

#10263 Polls push rules: synchronise poll rules with message rules
  src/components/views/settings/Notifications.tsx
  src/notifications/VectorPushRulesDefinitions.ts
  test/components/views/settings/Notifications-test.tsx
Labels: T-Enhancement

#10256 Find DMs with pending third-paty invites
  src/utils/dm/findDMForUser.ts
  test/test-utils/test-utils.ts
  test/utils/dm/findDMForUser-test.ts
Labels: T-Enhancement

#10272 apply strictnullchecks to src/components/views/beacon/*
  src/components/views/beacon/BeaconListItem.tsx
  src/components/views/beacon/BeaconStatusTooltip.tsx
  src/components/views/beacon/BeaconViewDialog.tsx
  src/components/views/beacon/DialogOwnBeaconStatus.tsx
  src/components/views/beacon/LeftPanelLiveShareWarning.tsx
  src/components/views/beacon/LiveTimeRemaining.tsx
  src/components/views/beacon/OwnBeaconStatus.tsx
  src/components/views/beacon/ShareLatestLocation.tsx
  src/components/views/beacon/displayStatus.ts
  src/utils/beacon/useOwnLiveBeacons.ts
  test/components/views/beacon/OwnBeaconStatus-test.tsx
Labels: T-Task

#10267 Directly convert Matrix and room Ids to pills
  src/components/views/messages/TextualBody.tsx
  test/components/views/messages/TextualBody-test.tsx
Labels: T-Defect

#10165 Support for v2 of MSC3903
  src/components/views/auth/LoginWithQR.tsx
Labels: T-Enhancement

#10265 Edit a test to check timestamp color's value on timeline and thread panel
  cypress/e2e/threads/threads.spec.ts
  res/css/views/messages/_MessageTimestamp.pcss
  res/css/views/right_panel/_ThreadPanel.pcss
Labels: Z-Community-PR, T-Task

#10270 Remove hosting link provider from Element
  res/css/_components.pcss
  res/css/structures/_UserMenu.pcss
  res/css/views/dialogs/_HostSignupDialog.pcss
  src/IConfigOptions.ts
  src/components/structures/HostSignupAction.tsx
  src/components/structures/LoggedInView.tsx
  src/components/structures/UserMenu.tsx
  src/components/views/dialogs/HostSignupDialog.tsx
  src/components/views/dialogs/HostSignupDialogTypes.ts
  src/components/views/host_signup/HostSignupContainer.tsx
  src/components/views/settings/ProfileSettings.tsx
  src/i18n/strings/en_EN.json
  src/stores/HostSignupStore.ts
  src/utils/HostingLink.ts
Labels: T-Task

#8861 Fix blowout of waveform of the voice message player on narrow UI
  res/css/views/audio_messages/_PlaybackContainer.pcss
Labels: Z-Community-PR, T-Defect

#10197 Align info EventTile and normal EventTile on IRC layout
  cypress/e2e/timeline/timeline.spec.ts
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/_IRCLayout.pcss
Labels: Z-Community-PR, T-Defect, X-Needs-Percy

#10124 Use cache for jest
  .github/workflows/tests.yml
Labels: T-Task

#10278 Fix start DM via right panel
  src/components/views/right_panel/UserInfo.tsx
  test/components/views/right_panel/UserInfo-test.tsx
Labels: X-Release-Blocker, T-Defect

#10276 Fix some features not being configurable via `features`
  src/MatrixClientPeg.ts
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
  src/settings/Settings.tsx
  src/settings/SettingsStore.ts
  src/settings/WatchManager.ts
  src/settings/controllers/MatrixClientBackedController.ts
  src/settings/controllers/ServerSupportUnstableFeatureController.ts
  test/MatrixClientPeg-test.ts
  test/components/views/settings/tabs/user/LabsUserSettingsTab-test.tsx
  test/settings/controllers/ServerSupportUnstableFeatureController-test.ts
  test/setup/setupManualMocks.ts
  test/test-utils/test-utils.ts
Labels: T-Defect

#10281 Remove items incorrectly included in changelog for 3.67.0
  CHANGELOG.md
Labels: T-Task

#8972 Reduce bottom margin of ReplyChain on compact modern layout
  res/css/views/elements/_ReplyChain.pcss
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/_IRCLayout.pcss
Labels: Z-Community-PR, T-Enhancement

#10284 Add a test to check whether ReadReceiptGroup exists on ThreadView in the bubble layout
  cypress/e2e/threads/threads.spec.ts
Labels: T-Task

#10283 Reduce height of toggle on expanded view source event
  cypress/e2e/timeline/timeline.spec.ts
  res/css/views/messages/_ViewSourceEvent.pcss
Labels: T-Defect

#10277 Pillify http and non-prefixed matrix.to links
  src/utils/permalinks/MatrixToPermalinkConstructor.ts
  src/utils/permalinks/PermalinkConstructor.ts
  src/utils/permalinks/Permalinks.ts
  test/utils/permalinks/MatrixToPermalinkConstructor-test.ts
  test/utils/permalinks/Permalinks-test.ts
Labels: T-Defect

#10289 Remove Enzyme tests in favour of React testing-library
  scripts/make-react-component.js
  src/components/views/dialogs/ExportDialog.tsx
  test/components/structures/RoomView-test.tsx
  test/components/structures/TimelinePanel-test.tsx
  test/components/views/context_menus/ContextMenu-test.tsx
  test/components/views/context_menus/MessageContextMenu-test.tsx
  test/components/views/dialogs/ExportDialog-test.tsx
  test/components/views/dialogs/__snapshots__/ExportDialog-test.tsx.snap
  test/components/views/right_panel/PinnedMessagesCard-test.tsx
  test/test-utils/wrappers.tsx
Labels: T-Task

#10290 Await start DM from user profile (right panel)
  src/components/views/right_panel/UserInfo.tsx
  test/components/views/right_panel/UserInfo-test.tsx
Labels: T-Defect

#10255 Kill off enzyme in preference of react testing library
  package.json
  src/components/views/emojipicker/EmojiPicker.tsx
  src/components/views/messages/MLocationBody.tsx
  test/components/views/messages/MLocationBody-test.tsx
  test/components/views/messages/__snapshots__/MLocationBody-test.tsx.snap
  test/setupTests.js
  yarn.lock
Labels: T-Task

#10291 Use spacing variables on _BetaCard.pcss
  res/css/views/beta/_BetaCard.pcss
Labels: Z-Community-PR, T-Task

#10293 Fix space settings dialog having rogue title tooltip
  src/components/views/dialogs/SpaceSettingsDialog.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#10296 Fix incorrect copy in space creation flow
  src/components/structures/SpaceRoomView.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#10299 Apply `strictNullChecks` to `src/components/views/auth/*` (#10299
  src/@types/common.ts
  src/SdkConfig.ts
  src/components/structures/InteractiveAuth.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/auth/Registration.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/auth/LanguageSelector.tsx
  src/components/views/auth/PassphraseConfirmField.tsx
  src/components/views/auth/PassphraseField.tsx
  src/components/views/auth/RegistrationForm.tsx
  src/components/views/auth/Welcome.tsx
  src/components/views/dialogs/DeactivateAccountDialog.tsx
  src/components/views/dialogs/InteractiveAuthDialog.tsx
  src/components/views/dialogs/RegistrationEmailPromptDialog.tsx
  src/components/views/elements/Validation.tsx
  src/utils/ErrorUtils.tsx
Labels: T-Task

#10286 Remove obsolete mx_BetaDot style rules introduced for Space release
  res/css/structures/_SpacePanel.pcss
  res/css/views/beta/_BetaCard.pcss
Labels: Z-Community-PR, T-Task

#10298 Apply `strictNullChecks` to src/components/views/emojipicker/*
  src/components/views/emojipicker/EmojiPicker.tsx
  src/components/views/emojipicker/Header.tsx
  src/components/views/emojipicker/ReactionPicker.tsx
  src/components/views/rooms/EmojiButton.tsx
Labels: T-Task

#10294 Add a test for ReplyChain
  cypress/e2e/timeline/timeline.spec.ts
Labels: Z-Community-PR, T-Task

#10285 Fix --name-width value on _IRCLayout.pcss
  res/css/views/rooms/_IRCLayout.pcss
Labels: Z-Community-PR, T-Task

#10307 Fix jest/no-conditional-expect lint and enable it
  .eslintrc.js
  test/SlidingSyncManager-test.ts
  test/components/views/rooms/MessageComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
  test/editor/model-test.ts
  test/editor/operations-test.ts
  test/utils/FixedRollingArray-test.ts
  test/utils/Singleflight-test.ts
Labels: T-Task

#10257 Fixes user authentication when registering via the module API
  src/Lifecycle.ts
  src/modules/ProxiedModuleApi.ts
  test/modules/ProxiedModuleApi-test.ts
Labels: Z-Community-PR, T-Defect

#10308 Allow parsing png files to fail if thumbnailing is successful
  src/ContentMessages.ts
  test/ContentMessages-test.ts
Labels: T-Defect

#10322 Remove unused code
  src/components/views/settings/UiFeatureSettingWrapper.tsx
  test/components/views/settings/UiFeatureSettingWrapper-test.tsx
  test/components/views/settings/__snapshots__/UiFeatureSettingWrapper-test.tsx.snap
Labels: T-Task

#10292 Use compound icons
  docs/icons.md
  res/css/compound/_Icon.pcss
  res/css/views/auth/_AuthBody.pcss
  res/img/compound/back-30s-24px.svg
  res/img/compound/checkbox-32px.svg
  res/img/compound/close-16px.svg
  res/img/compound/close-8px.svg
  res/img/compound/error-16px.svg
  res/img/compound/forward-30s-24px.svg
  res/img/compound/live-16px.svg
  res/img/compound/live-8px.svg
  res/img/compound/mic-16px.svg
  res/img/compound/padlock-32px.svg
  res/img/compound/pause-12.svg
  res/img/compound/play-16.svg
  res/img/compound/record-10px.svg
  res/img/compound/retry-16px.svg
  res/img/compound/stop-16.svg
  res/img/compound/timer-16px.svg
  res/img/element-icons/Back30s.svg
  res/img/element-icons/Forward30s.svg
  res/img/element-icons/Timer.svg
  src/components/structures/ErrorMessage.tsx
  src/components/structures/UserMenu.tsx
  src/components/structures/auth/ForgotPassword.tsx
  src/components/structures/auth/forgot-password/CheckEmail.tsx
  src/components/structures/auth/forgot-password/VerifyEmailModal.tsx
  src/voice-broadcast/components/atoms/LiveBadge.tsx
  src/voice-broadcast/components/atoms/VoiceBroadcastControl.tsx
  src/voice-broadcast/components/atoms/VoiceBroadcastError.tsx
  src/voice-broadcast/components/atoms/VoiceBroadcastHeader.tsx
  src/voice-broadcast/components/atoms/VoiceBroadcastPlaybackControl.tsx
  src/voice-broadcast/components/atoms/VoiceBroadcastRecordingConnectionError.tsx
  src/voice-broadcast/components/atoms/VoiceBroadcastRoomSubtitle.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastPreRecordingPip.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastSmallPlaybackBody.tsx
  test/voice-broadcast/components/atoms/VoiceBroadcastControl-test.tsx
  test/voice-broadcast/components/atoms/__snapshots__/VoiceBroadcastPlaybackControl-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPlaybackBody-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastRecordingPip-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastSmallPlaybackBody-test.tsx.snap
Labels: T-Task

#9016 Display redacted body on ThreadView in the same way as normal messages
  cypress/e2e/polls/polls.spec.ts
  cypress/e2e/threads/threads.spec.ts
  res/css/views/rooms/_EventTile.pcss
Labels: Z-Community-PR, T-Defect

#10324 Apply `strictNullChecks` to src/stores/widgets/*
  src/LegacyCallHandler.tsx
  src/components/views/context_menus/WidgetContextMenu.tsx
  src/components/views/elements/AppTile.tsx
  src/integrations/IntegrationManagerInstance.ts
  src/stores/ActiveWidgetStore.ts
  src/stores/widgets/StopGapWidget.ts
  src/stores/widgets/StopGapWidgetDriver.ts
  src/stores/widgets/WidgetLayoutStore.ts
  src/stores/widgets/WidgetMessagingStore.ts
  src/utils/WidgetUtils.ts
  test/components/views/rooms/RoomHeader-test.tsx
Labels: T-Task

#10304 Refactor pill and add tests
  src/components/views/elements/Pill.tsx
  src/components/views/elements/ReplyChain.tsx
  src/components/views/settings/BridgeTile.tsx
  src/hooks/usePermalink.tsx
  src/utils/pillify.tsx
  test/components/views/elements/Pill-test.tsx
  test/components/views/elements/__snapshots__/Pill-test.tsx.snap
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Task

#10312 Explicitly specify all `children` props
  src/AsyncWrapper.tsx
  src/components/structures/AutoHideScrollbar.tsx
  src/components/structures/ContextMenu.tsx
  src/components/structures/MainSplit.tsx
  src/components/structures/ScrollPanel.tsx
  src/components/structures/SpaceHierarchy.tsx
  src/components/structures/UserMenu.tsx
  src/components/views/auth/AuthPage.tsx
  src/components/views/auth/CompleteSecurityBody.tsx
  src/components/views/avatars/MemberAvatar.tsx
  src/components/views/context_menus/IconizedContextMenu.tsx
  src/components/views/context_menus/WidgetContextMenu.tsx
  src/components/views/dialogs/GenericFeatureFeedbackDialog.tsx
  src/components/views/dialogs/devtools/BaseTool.tsx
  src/components/views/elements/DialogButtons.tsx
  src/components/views/elements/ErrorBoundary.tsx
  src/components/views/elements/InfoTooltip.tsx
  src/components/views/elements/MiniAvatarUploader.tsx
  src/components/views/elements/PersistedElement.tsx
  src/components/views/elements/TruncatedList.tsx
  src/components/views/messages/TileErrorBoundary.tsx
  src/components/views/polls/PollOption.tsx
  src/components/views/right_panel/BaseCard.tsx
  src/components/views/right_panel/HeaderButton.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/AuxPanel.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/LinkPreviewWidget.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
  src/components/views/rooms/NotificationBadge/StatelessNotificationBadge.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
  test/components/views/context_menus/ContextMenu-test.tsx
Labels: T-Task

#10297 Support dynamic room predecessors in RoomNotificationStateStore
  src/stores/notifications/RoomNotificationStateStore.ts
  test/components/structures/RoomView-test.tsx
  test/components/views/dialogs/SpotlightDialog-test.tsx
  test/stores/RoomNotificationStateStore-test.ts
Labels: T-Enhancement

#10325 Remove deprecated stylelint rules which are handled by prettier
  .stylelintrc.js
  package.json
  yarn.lock
Labels: T-Task

#10313 Remove flux dependency
  package.json
  src/components/views/rooms/RoomSublist.tsx
  src/dispatcher/dispatcher.ts
  src/hooks/useDispatcher.ts
  src/stores/AsyncStore.ts
  src/stores/AsyncStoreWithClient.ts
  src/stores/LifecycleStore.ts
  src/stores/ReadyWatchingStore.ts
  test/dispatcher/dispatcher-test.ts
  yarn.lock
Labels: T-Task

#10295 Support dynamic room predecessors in BreadcrumbsStore
  src/stores/BreadcrumbsStore.ts
  test/stores/BreadcrumbsStore-test.ts
Labels: T-Enhancement

#10279 Handle more edge cases in ACL updates
  src/utils/permalinks/Permalinks.ts
Labels: T-Defect

#10287 Sync polls push rules on changes to account_data
  src/components/structures/LoggedInView.tsx
  src/components/views/settings/Notifications.tsx
  src/utils/pushRules/monitorSyncedPushRules.ts
  src/utils/pushRules/updatePushRuleActions.ts
  test/components/structures/LoggedInView-test.tsx
Labels: T-Enhancement

#10332 Support dynamic room predecessors in SpaceStore
  src/stores/spaces/SpaceStore.ts
  test/stores/SpaceStore-test.ts
Labels: T-Enhancement

#10326 Support dynamic room predecessors in WidgetLayoutStore
  src/stores/widgets/WidgetLayoutStore.ts
  test/stores/WidgetLayoutStore-test.ts
Labels: T-Enhancement

#10328 Extract avatars from permalink hook
  src/components/views/elements/Pill.tsx
  src/hooks/usePermalink.ts
  test/components/views/elements/Pill-test.tsx
  test/components/views/elements/__snapshots__/Pill-test.tsx.snap
Labels: T-Task

#10331 Add tests for createEditContent which mirror tests for createMessageContent.
  src/components/views/rooms/EditMessageComposer.tsx
  test/components/views/rooms/EditMessageComposer-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
Labels: T-Task

#10342 Support dynamic room predecessors in AddExistingToSpaceDialog
  src/components/views/dialogs/AddExistingToSpaceDialog.tsx
  test/components/views/spaces/AddExistingToSpaceDialog-test.tsx
  test/components/views/spaces/__snapshots__/AddExistingToSpaceDialog-test.tsx.snap
Labels: T-Enhancement

#10336 Poll history: cypress test
  cypress/e2e/polls/pollHistory.spec.ts
Labels: T-Task

#10339 Support dynamic room predecessors in OwnBeaconStore
  src/stores/OwnBeaconStore.ts
  test/components/views/beacon/RoomLiveShareWarning-test.tsx
  test/stores/OwnBeaconStore-test.ts
Labels: T-Enhancement

#10341 Support dynamic room predecessors in SpaceHierarchy
  src/components/structures/SpaceHierarchy.tsx
  test/components/structures/SpaceHierarchy-test.tsx
Labels: T-Enhancement

#10344 Support dynamic room predecessors in ForwardDialog
  src/components/views/dialogs/ForwardDialog.tsx
  test/components/views/dialogs/ForwardDialog-test.tsx
Labels: T-Enhancement

#10346 Support dynamic room predecessors for RoomProvider
  src/autocomplete/RoomProvider.tsx
  test/autocomplete/RoomProvider-test.ts
Labels: T-Enhancement

#10343 Fix long display name overflowing reply tile on IRC layout
  cypress/e2e/timeline/timeline.spec.ts
  res/css/views/rooms/_IRCLayout.pcss
Labels: Z-Community-PR, T-Defect

#10351 Pin versions of third-party github actions
  .github/workflows/backport.yml
  .github/workflows/cypress.yaml
  .github/workflows/i18n_check.yml
  .github/workflows/netlify.yaml
  .github/workflows/notify-element-web.yml
  .github/workflows/static_analysis.yaml
  .github/workflows/tests.yml
Labels: T-Task

#10131 Improve performance of rendering a room with many hidden events
  src/components/structures/MessagePanel.tsx
  test/components/structures/MessagePanel-test.tsx
  test/components/structures/__snapshots__/MessagePanel-test.tsx.snap
Labels: T-Defect

#10347 Fix start DM with pending third party invite
  src/utils/dm/findDMForUser.ts
  test/utils/dm/findDMForUser-test.ts
Labels: X-Release-Blocker, T-Defect, backport staging

#10350 Conform more of the codebase to `strictNullChecks` (#10350
  src/@types/common.ts
  src/AddThreepid.ts
  src/accessibility/context_menu/ContextMenuButton.tsx
  src/accessibility/context_menu/ContextMenuTooltipButton.tsx
  src/actions/RoomListActions.ts
  src/audio/PlaybackQueue.ts
  src/boundThreepids.ts
  src/components/structures/AutoHideScrollbar.tsx
  src/components/structures/FilePanel.tsx
  src/components/structures/GenericDropdownMenu.tsx
  src/components/structures/IndicatorScrollbar.tsx
  src/components/structures/LeftPanel.tsx
  src/components/structures/LegacyCallEventGrouper.ts
  src/components/structures/LoggedInView.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/MessagePanel.tsx
  src/components/structures/ScrollPanel.tsx
  src/components/structures/TabbedView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/structures/UserMenu.tsx
  src/components/structures/ViewSource.tsx
  src/components/structures/auth/ForgotPassword.tsx
  src/components/structures/auth/Login.tsx
  src/components/structures/auth/SetupEncryptionBody.tsx
  src/components/structures/auth/SoftLogout.tsx
  src/components/structures/auth/header/AuthHeaderDisplay.tsx
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/dialogs/AddExistingToSpaceDialog.tsx
  src/components/views/dialogs/BaseDialog.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/dialogs/RoomSettingsDialog.tsx
  src/components/views/dialogs/SpacePreferencesDialog.tsx
  src/components/views/dialogs/SpaceSettingsDialog.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/elements/DesktopCapturerSourcePicker.tsx
  src/components/views/elements/PowerSelector.tsx
  src/components/views/elements/QRCode.tsx
  src/components/views/elements/ReplyChain.tsx
  src/components/views/elements/Slider.tsx
  src/components/views/elements/TruncatedList.tsx
  src/components/views/right_panel/PinnedMessagesCard.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/E2EIcon.tsx
  src/components/views/rooms/EntityTile.tsx
  src/components/views/rooms/PresenceLabel.tsx
  src/components/views/settings/account/PhoneNumbers.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/stores/WidgetStore.ts
  src/utils/localRoom/isLocalRoom.ts
  test/components/structures/TabbedView-test.tsx
  test/components/structures/__snapshots__/TabbedView-test.tsx.snap
  test/components/views/dialogs/polls/__snapshots__/PollHistoryDialog-test.tsx.snap
  test/stores/BreadcrumbsStore-test.ts
Labels: T-Task

#10349 Poll history - make poll history independent from dialogs
  res/css/_common.pcss
  res/css/_components.pcss
  res/css/views/polls/pollHistory/_PollHistory.pcss
  res/css/views/polls/pollHistory/_PollHistoryList.pcss
  src/components/views/dialogs/BaseDialog.tsx
  src/components/views/dialogs/PollHistoryDialog.tsx
  src/components/views/polls/pollHistory/PollDetail.tsx
  src/components/views/polls/pollHistory/PollDetailHeader.tsx
  src/components/views/polls/pollHistory/PollHistory.tsx
  src/components/views/polls/pollHistory/PollHistoryList.tsx
  src/components/views/polls/pollHistory/PollListItem.tsx
  src/components/views/polls/pollHistory/PollListItemEnded.tsx
  src/components/views/polls/pollHistory/fetchPastPolls.ts
  src/components/views/polls/pollHistory/types.ts
  src/components/views/polls/pollHistory/usePollHistory.ts
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/polls/__snapshots__/PollHistoryDialog-test.tsx.snap
  test/components/views/polls/pollHistory/PollHistory-test.tsx
  test/components/views/polls/pollHistory/PollListItem-test.tsx
  test/components/views/polls/pollHistory/PollListItemEnded-test.tsx
  test/components/views/polls/pollHistory/__snapshots__/PollHistory-test.tsx.snap
  test/components/views/polls/pollHistory/__snapshots__/PollListItem-test.tsx.snap
  test/components/views/polls/pollHistory/__snapshots__/PollListItemEnded-test.tsx.snap
  test/components/views/right_panel/RoomSummaryCard-test.tsx
Labels: T-Task

#10359 Fix user pill click
  src/hooks/usePermalink.ts
  test/components/views/elements/Pill-test.tsx
  test/components/views/elements/__snapshots__/Pill-test.tsx.snap
Labels: T-Defect

#10337 Apply `strictNullChecks` to `src/utils/beacon/*`
  src/utils/beacon/bounds.ts
  src/utils/beacon/duration.ts
  src/utils/beacon/geolocation.ts
  src/utils/beacon/useLiveBeacons.ts
  test/utils/beacon/duration-test.ts
Labels: T-Task

#10288 Notifications: inline error message on notifications saving error
  res/css/components/views/typography/_Caption.pcss
  res/css/views/settings/_Notifications.pcss
  src/components/views/settings/Notifications.tsx
  src/components/views/typography/Caption.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/Notifications-test.tsx
  test/components/views/typography/Caption-test.tsx
  test/components/views/typography/__snapshots__/Caption-test.tsx.snap
Labels: T-Enhancement

#10356 Poll history - access poll history from room settings
  res/css/views/dialogs/_RoomSettingsDialog.pcss
  src/components/views/dialogs/RoomSettingsDialog.tsx
  src/components/views/settings/tabs/room/PollHistoryTab.tsx
  test/components/views/dialogs/RoomSettingsDialog-test.tsx
  test/components/views/dialogs/__snapshots__/RoomSettingsDialog-test.tsx.snap
Labels: T-Enhancement

#10367 Apply `strictNullChecks` to `src/components/views/context_menus/*`
  src/components/views/context_menus/DeviceContextMenu.tsx
  src/components/views/context_menus/KebabContextMenu.tsx
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/context_menus/ThreadListContextMenu.tsx
  src/components/views/context_menus/WidgetContextMenu.tsx
Labels: T-Task

#10370 Roll back MXID and room pillification
  src/components/views/messages/TextualBody.tsx
  test/components/views/messages/TextualBody-test.tsx
Labels: X-Release-Blocker, T-Task, backport staging

#10368 Conform more code to `strictNullChecks` (#10368
  src/Modal.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/SpaceHierarchy.tsx
  src/components/views/dialogs/BugReportDialog.tsx
  src/components/views/dialogs/CreateRoomDialog.tsx
  src/components/views/dialogs/CreateSubspaceDialog.tsx
  src/components/views/dialogs/ExportDialog.tsx
  src/components/views/dialogs/LogoutDialog.tsx
  src/components/views/dialogs/ModalWidgetDialog.tsx
  src/components/views/dialogs/ReportEventDialog.tsx
  src/components/views/dialogs/RoomUpgradeWarningDialog.tsx
  src/components/views/dialogs/SlidingSyncOptionsDialog.tsx
  src/components/views/dialogs/TextInputDialog.tsx
  src/components/views/dialogs/UploadConfirmDialog.tsx
  src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/spaces/SpaceBasicSettings.tsx
  src/customisations/ChatExport.ts
  src/i18n/strings/en_EN.json
  src/rageshake/submit-rageshake.ts
  src/sentry.ts
  src/utils/pillify.tsx
  test/components/views/right_panel/UserInfo-test.tsx
Labels: T-Task

#10372 Roll back pillify everything (#10370)
  src/components/views/messages/TextualBody.tsx
  test/components/views/messages/TextualBody-test.tsx
Labels: T-Defect

#10188 Initialize line-height for room name on IRC layout
  cypress/e2e/timeline/timeline.spec.ts
  res/css/views/rooms/_IRCLayout.pcss
Labels: Z-Community-PR, T-Defect

#10371 Fix UIFeature.Registration not applying to all paths
  src/Registration.tsx
  src/components/structures/UserMenu.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#10361 Enable "jsx-a11y/alt-text" and "jsx-a11y/label-has-associated-control" lint rules
  .eslintrc.js
  src/components/views/elements/DesktopCapturerSourcePicker.tsx
  src/components/views/elements/SearchWarning.tsx
  src/components/views/messages/MStickerBody.tsx
  src/components/views/room_settings/UrlPreviewSettings.tsx
  src/components/views/rooms/EntityTile.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#10366 Apply `strictNullChecks` to `src/components/views/room_settings/*` (#10366
  src/components/views/elements/EditableItemList.tsx
  src/components/views/room_settings/AliasSettings.tsx
  src/components/views/room_settings/RoomProfileSettings.tsx
  src/components/views/room_settings/RoomPublishSetting.tsx
Labels: T-Task

#10375 Fix import e2e key dialog staying disabled after paste
  src/async-components/views/dialogs/security/ImportE2eKeysDialog.tsx
  test/components/views/dialogs/security/ImportE2eKeysDialog-test.tsx
  test/components/views/dialogs/security/__snapshots__/ImportE2eKeysDialog-test.tsx.snap
Labels: T-Defect

#10385 Fix pinned messages card saying nothing pinned while loading
  src/components/views/right_panel/PinnedMessagesCard.tsx
  test/components/views/right_panel/PinnedMessagesCard-test.tsx
Labels: T-Defect

#10376 Add API params to mute audio and/or video in Jitsi calls by default
  docs/jitsi.md
  src/utils/WidgetUtils.ts
  test/utils/WidgetUtils-test.ts
Labels: Z-Community-PR, T-Enhancement

#10384 Fix sanitise html warning about unsafe tags
  src/utils/Reply.ts
Labels: T-Task

#10386 Clear electron data when logging out
  src/BasePlatform.ts
  src/Lifecycle.ts
Labels: T-Task

#10390 Fix `[object Object]` in feedback metadata
  src/components/views/dialogs/GenericFeatureFeedbackDialog.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
  src/rageshake/submit-rageshake.ts
Labels: T-Defect

#10389 Stricitfy rageshake
  src/rageshake/rageshake.ts
  src/rageshake/submit-rageshake.ts
Labels: T-Task

#10378 Apply `strictNullChecks` to `src/resizer/*`
  src/resizer/distributors/collapse.ts
  src/resizer/distributors/percentage.ts
  src/resizer/item.ts
Labels: T-Task

#10357 Poll history - remove active development labs flag
  cypress/e2e/polls/pollHistory.spec.ts
  src/components/views/dialogs/RoomSettingsDialog.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/views/dialogs/RoomSettingsDialog-test.tsx
  test/components/views/dialogs/__snapshots__/RoomSettingsDialog-test.tsx.snap
  test/components/views/right_panel/RoomSummaryCard-test.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
Labels: T-Task

#10394 Fix wrong E2E icon in room header for unencrypted local room
  src/components/structures/RoomView.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
Labels: T-Defect

#10393 Strictify voice-broadcast
  src/voice-broadcast/components/atoms/VoiceBroadcastPlaybackControl.tsx
  src/voice-broadcast/hooks/useVoiceBroadcastPlayback.ts
  src/voice-broadcast/hooks/useVoiceBroadcastRecording.tsx
  src/voice-broadcast/stores/VoiceBroadcastRecordingsStore.ts
  test/voice-broadcast/components/atoms/VoiceBroadcastPlaybackControl-test.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody-test.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingBody-test.tsx
Labels: T-Task

#10383 Conform more code to `strictNullChecks` (#10383
  package.json
  src/components/structures/LoggedInView.tsx
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/SpaceRoomView.tsx
  src/hooks/usePublicRoomDirectory.ts
  src/utils/DMRoomMap.ts
  src/utils/MultiInviter.ts
  src/utils/UrlUtils.ts
  src/utils/WidgetUtils.ts
  src/utils/dm/findDMRoom.ts
  src/utils/exportUtils/Exporter.ts
  src/utils/exportUtils/JSONExport.ts
  src/utils/leave-behaviour.ts
  src/utils/location/map.ts
  src/utils/permalinks/Permalinks.ts
  src/utils/space.tsx
  yarn.lock
Labels: T-Task

#10374 Conform more code to `strictNullChecks`
  src/KeyBindingsManager.ts
  src/MatrixClientPeg.ts
  src/Searching.ts
  src/components/views/dialogs/CreateRoomDialog.tsx
  src/components/views/dialogs/ModalWidgetDialog.tsx
  src/components/views/elements/ImageView.tsx
  src/components/views/elements/LazyRenderList.tsx
  src/components/views/messages/EncryptionEvent.tsx
  src/components/views/messages/MBeaconBody.tsx
  src/components/views/right_panel/TimelineCard.tsx
  src/components/views/right_panel/VerificationPanel.tsx
  src/components/views/right_panel/WidgetCard.tsx
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/NewRoomIntro.tsx
  src/components/views/rooms/RoomListHeader.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/components/views/settings/KeyboardShortcut.tsx
  src/components/views/settings/Notifications.tsx
  src/components/views/settings/SetIdServer.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/components/views/settings/tabs/user/VoiceUserSettingsTab.tsx
  src/components/views/toasts/VerificationRequestToast.tsx
  src/components/views/voip/CallView.tsx
  src/dispatcher/payloads/ViewRoomErrorPayload.ts
  src/editor/history.ts
  src/editor/model.ts
  src/stores/AutoRageshakeStore.ts
  src/stores/ModalWidgetStore.ts
  src/stores/RoomScrollStateStore.ts
  src/stores/RoomViewStore.tsx
  src/stores/right-panel/RightPanelStore.ts
  src/stores/spaces/SpaceStore.ts
  src/voice-broadcast/components/molecules/ConfirmListenBroadcastStopCurrent.tsx
  src/voice-broadcast/hooks/useVoiceBroadcastPlayback.ts
  src/voice-broadcast/hooks/useVoiceBroadcastRecording.tsx
  src/voice-broadcast/index.ts
  test/components/structures/MessagePanel-test.tsx
  test/components/structures/RightPanel-test.tsx
  test/components/views/elements/AppTile-test.tsx
  test/components/views/settings/tabs/user/PreferencesUserSettingsTab-test.tsx
Labels: T-Task

#10373 Respect user cancelling upload flow by dismissing spinner
  src/ContentMessages.ts
Labels: T-Defect

#10380 Add fallback for replies to Polls
  src/utils/Reply.ts
  test/Reply-test.ts
  test/__snapshots__/Reply-test.ts.snap
Labels: T-Enhancement

#10391 Apply `strictNullChecks` to `src/components/views/dialogs/devtools/*`
  src/components/views/dialogs/devtools/AccountData.tsx
  src/components/views/dialogs/devtools/BaseTool.tsx
  src/components/views/dialogs/devtools/Event.tsx
  src/components/views/dialogs/devtools/FilteredList.tsx
  src/components/views/dialogs/devtools/RoomState.tsx
  src/components/views/dialogs/devtools/ServersInRoom.tsx
  src/components/views/dialogs/devtools/SettingExplorer.tsx
  src/components/views/dialogs/devtools/VerificationExplorer.tsx
  src/components/views/dialogs/devtools/WidgetExplorer.tsx
Labels: T-Task

#10306 Add a basic E2E test for event tiles
  cypress/e2e/timeline/timeline.spec.ts
Labels: Z-Community-PR, T-Task

#6084 Increase space panel collapse clickable area
  res/css/structures/_SpacePanel.pcss
Labels: Z-Community-PR, T-Enhancement

#10397 MSC3030 jump to date is supported in stable `v1.6` version
  src/settings/Settings.tsx
Labels: T-Task

#10398 Add stable unstable version for jump to date before `v1.6` is fully supported on a homeserver
  src/settings/Settings.tsx
  src/settings/controllers/ServerSupportUnstableFeatureController.ts
  test/settings/controllers/ServerSupportUnstableFeatureController-test.ts
Labels: T-Task

#10353 Further improve performance with lots of hidden events
  src/components/structures/MessagePanel.tsx
  test/components/structures/MessagePanel-test.tsx
  test/components/structures/__snapshots__/MessagePanel-test.tsx.snap
Labels: T-Defect

#10280 Handle more edge cases in Space Hierarchy
  src/components/structures/SpaceHierarchy.tsx
Labels: T-Defect

#10403 Refactor custom logic to use the shared `canResetTimeline()` function
  src/components/structures/TimelinePanel.tsx
Labels: T-Task

#10402 Remove unreadable alt attribute from the room status bar warning icon (nonsense to screenreaders)
  src/components/structures/RoomStatusBar.tsx
Labels: T-Defect

#10411 Fix failing develop with mis-matched snapshots
  test/components/structures/__snapshots__/MessagePanel-test.tsx.snap
Labels: T-Task

#10381 Show search,dial,explore in filterContainer if "UIComponent.filterContainer" is enabled
  res/css/structures/_LeftPanel.pcss
  src/components/structures/LeftPanel.tsx
  src/settings/UIFeature.ts
  test/components/structures/LeftPanel-test.tsx
Labels: Z-Community-PR, T-Enhancement, A-MyHours-PSP-3754

#10410 Strictify audio-messages
  src/components/views/audio_messages/AudioPlayer.tsx
  src/components/views/audio_messages/Clock.tsx
  src/components/views/audio_messages/DevicesContextMenu.tsx
  src/components/views/audio_messages/PlaybackClock.tsx
Labels: T-Task

#10396 Fix profile resizer to make first character of a line selectable in IRC layout
  cypress/e2e/timeline/timeline.spec.ts
  res/css/_common.pcss
  res/css/structures/_RoomView.pcss
  res/css/views/rooms/_IRCLayout.pcss
Labels: Z-Community-PR, T-Defect

#10392 Pillify event permalinks
  cypress/e2e/regression-tests/pills-click-in-app.spec.ts
  res/css/views/elements/_Pill.pcss
  res/img/compound/user.svg
  res/themes/legacy-dark/css/_legacy-dark.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light/css/_light.pcss
  src/components/views/elements/Pill.tsx
  src/hooks/usePermalink.ts
  src/hooks/usePermalinkEvent.ts
  src/hooks/usePermalinkMember.ts
  src/hooks/usePermalinkTargetRoom.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/utils/pillify.tsx
  test/components/views/elements/Pill-test.tsx
  test/components/views/elements/__snapshots__/Pill-test.tsx.snap
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#10409 Update matrix-widget-api
  package.json
  yarn.lock
Labels: X-Release-Blocker, T-Task

#10269 Implement MSC3973: Search users in the user directory with the Widget API
  src/stores/widgets/StopGapWidgetDriver.ts
  test/stores/widgets/StopGapWidgetDriver-test.ts
  test/test-utils/test-utils.ts
  yarn.lock
Labels: Z-Community-PR, T-Enhancement

#10412 Fix block/inline Element descendants error noise in `NewRoomIntro.tsx`
  src/components/views/rooms/NewRoomIntro.tsx
Labels: T-Defect

#10413 Disable the "Polls Composer" Percy test since it is flaky
  cypress/e2e/polls/polls.spec.ts
Labels: T-Task

#10416 Disable Percy snapshots that are flaky due to focus issues
  cypress/e2e/room-directory/room-directory.spec.ts
  cypress/e2e/timeline/timeline.spec.ts
Labels: T-Task

#10415 Improve strictNullChecks support in right_panel
  src/components/structures/TimelinePanel.tsx
  src/components/views/right_panel/EncryptionPanel.tsx
  src/components/views/right_panel/HeaderButtons.tsx
  src/components/views/right_panel/PinnedMessagesCard.tsx
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/right_panel/TimelineCard.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/right_panel/VerificationPanel.tsx
  src/components/views/right_panel/WidgetCard.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/components/views/rooms/VoiceRecordComposerTile.tsx
  src/stores/right-panel/RightPanelStorePhases.ts
  src/utils/Reply.ts
Labels: T-Task

#10420 Ensure Percy take snapshots of a whole viewport
  cypress/e2e/timeline/timeline.spec.ts
Labels: Z-Community-PR, T-Task

#10417 Tweak pill UI
  res/css/views/elements/_Pill.pcss
  src/components/views/elements/Pill.tsx
  src/hooks/usePermalink.ts
  src/i18n/strings/en_EN.json
  test/components/views/elements/__snapshots__/Pill-test.tsx.snap
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Task, X-Needs-Percy

#10419 Prevent future date selection in jump to date
  src/DateUtils.ts
  src/components/views/messages/JumpToDatePicker.tsx
  test/components/views/messages/JumpToDatePicker-test.tsx
  test/components/views/messages/__snapshots__/JumpToDatePicker-test.tsx.snap
  test/utils/DateUtils-test.ts
Labels: T-Defect

#10431 Prep for matrix-js-sdk supporting intentional mentions
  test/test-utils/test-utils.ts
Labels: T-Task

#10430 Hide seek bar of audio player to fix a flaky Percy test temporarily
  cypress/e2e/right-panel/file-panel.spec.ts
Labels: Z-Community-PR, T-Task

#9983 Implement MSC3952: intentional mentions
  src/ContentMessages.ts
  src/MatrixClientPeg.ts
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/components/views/rooms/VoiceRecordComposerTile.tsx
  src/components/views/rooms/wysiwyg_composer/utils/createMessageContent.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/ContentMessages-test.ts
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/components/views/rooms/VoiceRecordComposerTile-test.tsx
Labels: T-Enhancement

#10428 Fix strict `strictNullChecks` to `src/editor/*` (#10428
  src/components/views/rooms/BasicMessageComposer.tsx
  src/editor/autocomplete.ts
  src/editor/commands.tsx
  src/editor/deserialize.ts
  src/editor/dom.ts
  src/editor/history.ts
  src/editor/model.ts
  src/editor/operations.ts
  src/editor/parts.ts
  src/editor/range.ts
  test/editor/history-test.ts
Labels: T-Task

#10438 Disable flaky Percy tests that relate to focus
  cypress/e2e/timeline/timeline.spec.ts
Labels: T-Task

#10211 Set expected value of line-height to expanded generic event list summary (GELS) spacer on IRC layout
  cypress/e2e/timeline/timeline.spec.ts
  res/css/views/elements/_GenericEventListSummary.pcss
  res/css/views/rooms/_IRCLayout.pcss
  src/components/views/elements/GenericEventListSummary.tsx
Labels: Z-Community-PR, T-Defect, X-Needs-Percy

#10405 Better error handling in jump to date
  src/Modal.tsx
  src/components/views/messages/DateSeparator.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/auth/ForgotPassword-test.tsx
  test/components/views/messages/DateSeparator-test.tsx
  test/components/views/messages/__snapshots__/DateSeparator-test.tsx.snap
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/rooms/MessageComposer-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/test-utils/utilities.ts
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.tsx
Labels: T-Enhancement

#10436 Add `m.direct` filter / validation
  src/utils/DMRoomMap.ts
  src/utils/dm/filterValidMDirect.ts
  test/utils/DMRoomMap-test.ts
  test/utils/dm/filterValidMDirect-test.ts
Labels: T-Defect

#10444 Conform more code to `strictNullChecks` (#10444
  src/components/structures/MessagePanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/dialogs/BetaFeedbackDialog.tsx
  src/components/views/dialogs/BulkRedactDialog.tsx
  src/components/views/dialogs/DevtoolsDialog.tsx
  src/components/views/dialogs/ForwardDialog.tsx
  src/components/views/dialogs/RegistrationEmailPromptDialog.tsx
  src/components/views/dialogs/ServerPickerDialog.tsx
  src/components/views/dialogs/TermsDialog.tsx
  src/components/views/dialogs/TextInputDialog.tsx
  src/components/views/dialogs/spotlight/RoomResultContextMenus.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/elements/EditableText.tsx
  src/components/views/elements/EventListSummary.tsx
  src/components/views/elements/ReplyChain.tsx
  src/components/views/messages/EditHistoryMessage.tsx
  src/components/views/right_panel/PinnedMessagesCard.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/EmojiButton.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
  src/hooks/usePermalinkEvent.ts
  src/hooks/usePermalinkTargetRoom.ts
  src/toasts/AnalyticsToast.tsx
  src/utils/SortMembers.ts
  test/components/structures/MessagePanel-test.tsx
  test/components/views/dialogs/ForwardDialog-test.tsx
  test/components/views/right_panel/UserInfo-test.tsx
Labels: T-Task

#10442 Update docs about Percy now they run nightly
  docs/cypress.md
Labels: T-Task

#10437 Fix joining public rooms without aliases in search dialog
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  test/components/views/dialogs/SpotlightDialog-test.tsx
Labels: T-Defect

#10425 Add `UserProfilesStore`, `LruCache` and cache for user permalink profiles
  src/components/structures/MatrixChat.tsx
  src/contexts/SDKContext.ts
  src/hooks/usePermalinkMember.ts
  src/stores/UserProfilesStore.ts
  src/utils/LruCache.ts
  test/components/views/elements/Pill-test.tsx
  test/components/views/elements/__snapshots__/Pill-test.tsx.snap
  test/contexts/SdkContext-test.ts
  test/stores/UserProfilesStore-test.ts
  test/utils/LruCache-test.ts
Labels: T-Enhancement

#10445 Fix "show read receipts sent by other users" not applying to threads
  src/components/structures/ThreadView.tsx
Labels: T-Defect

#10458 Revert "Mentions as links rte (#10422)"
  package.json
  res/css/views/rooms/wysiwyg_composer/_SendWysiwygComposer.pcss
  res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
  src/components/views/rooms/wysiwyg_composer/components/WysiwygAutocomplete.tsx
  src/components/views/rooms/wysiwyg_composer/components/WysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useInputEventProcessor.ts
  test/components/views/rooms/wysiwyg_composer/SendWysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/WysiwygAutocomplete-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/utils.ts
  yarn.lock
Labels: T-Defect

#10453 Hide `TopUnreadMessagesBar` for now on Percy because flaky
  cypress/e2e/timeline/timeline.spec.ts
Labels: Z-Community-PR, T-Task

#10450 Fix flaky Percy tests of `ReplyChain`
  cypress/e2e/timeline/timeline.spec.ts
  res/css/_common.pcss
  res/css/views/avatars/_BaseAvatar.pcss
  res/css/views/elements/_ReplyChain.pcss
  res/css/views/messages/_DisambiguatedProfile.pcss
  res/css/views/rooms/_ReplyTile.pcss
Labels: Z-Community-PR, T-Task, X-Needs-Percy

#10460 Conform `src/hooks/*` code to `strictNullChecks`
  src/hooks/useAudioDeviceSelection.ts
  src/hooks/usePublicRoomDirectory.ts
Labels: T-Task

#10418 Enable running cypress tests with dendrite & pinecone
  cypress/plugins/dendritedocker/index.ts
  cypress/plugins/dendritedocker/templates/default/dendrite.yaml
Labels: T-Task

#10457 Use unique keys for voice broadcast pips
  src/components/structures/PipContainer.tsx
Labels: T-Defect

#10452 Improve Percy snapshot stability more - await inline spinners to vanish
  cypress/support/percy.ts
Labels: Z-Community-PR, T-Task

#10399 Display relative timestamp for threads on the same calendar day
  src/DateUtils.ts
  test/utils/DateUtils-test.ts
Labels: T-Defect

#10456 Apply `strictNullChecks` to `src/utils/pillify.tsx`
  src/components/views/elements/Pill.tsx
  src/utils/permalinks/Permalinks.ts
  src/utils/pillify.tsx
Labels: T-Task

#10449 Change the category of a test from `message displaying` to `configure room`
  cypress/e2e/timeline/timeline.spec.ts
Labels: Z-Community-PR, T-Task

#10465 Handle group call redaction
  src/components/views/messages/CallEvent.tsx
  src/toasts/IncomingCallToast.tsx
  test/components/views/messages/CallEvent-test.tsx
  test/toasts/IncomingCallToast-test.tsx
Labels: T-Defect

#10454 replace `Polls history` strings with `Poll history`
  cypress/e2e/polls/pollHistory.spec.ts
  src/components/views/dialogs/RoomSettingsDialog.tsx
  src/components/views/polls/pollHistory/PollHistory.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/RoomSettingsDialog-test.tsx
  test/components/views/dialogs/__snapshots__/RoomSettingsDialog-test.tsx.snap
  test/components/views/polls/pollHistory/PollHistory-test.tsx
  test/components/views/polls/pollHistory/__snapshots__/PollHistory-test.tsx.snap
  test/components/views/right_panel/RoomSummaryCard-test.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
Labels: T-Task

#10446 Add Cypress Testing Library
  cypress/e2e/create-room/create-room.spec.ts
  cypress/support/e2e.ts
  cypress/support/find.ts
  cypress/tsconfig.json
  docs/cypress.md
  package.json
  yarn.lock
Labels: T-Task

#10461 Conform `src/components/views/messages/*` code to `strictNullChecks`
  src/components/views/messages/DownloadActionButton.tsx
  src/components/views/messages/EditHistoryMessage.tsx
  src/components/views/messages/MAudioBody.tsx
  src/components/views/messages/MBeaconBody.tsx
  src/components/views/messages/MFileBody.tsx
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MImageReplyBody.tsx
  src/components/views/messages/MJitsiWidgetEvent.tsx
  src/components/views/messages/MKeyVerificationConclusion.tsx
  src/components/views/messages/MKeyVerificationRequest.tsx
  src/components/views/messages/MPollBody.tsx
  src/components/views/messages/MVideoBody.tsx
  src/components/views/messages/MessageEvent.tsx
  src/components/views/messages/ReactionsRow.tsx
  src/components/views/messages/ReactionsRowButton.tsx
  src/components/views/messages/ReactionsRowButtonTooltip.tsx
  src/components/views/messages/RedactedBody.tsx
  src/components/views/messages/RoomAvatarEvent.tsx
  src/components/views/messages/TextualBody.tsx
  src/settings/enums/ImageSize.ts
  src/utils/FileDownloader.ts
Labels: T-Task

#10462 Apply `strictNullChecks` to `src/components/views/elements/*` (#10462
  src/HtmlUtils.tsx
  src/components/views/auth/CountryDropdown.tsx
  src/components/views/dialogs/AddExistingToSpaceDialog.tsx
  src/components/views/elements/AppPermission.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/elements/DesktopCapturerSourcePicker.tsx
  src/components/views/elements/Dropdown.tsx
  src/components/views/elements/EditableText.tsx
  src/components/views/elements/EffectsOverlay.tsx
  src/components/views/elements/EventListSummary.tsx
  src/components/views/elements/Field.tsx
  src/components/views/elements/FilterDropdown.tsx
  src/components/views/elements/ImageView.tsx
  src/components/views/elements/InteractiveTooltip.tsx
  src/components/views/elements/JoinRuleDropdown.tsx
  src/components/views/elements/LanguageDropdown.tsx
  src/components/views/elements/MiniAvatarUploader.tsx
  src/components/views/elements/ReplyChain.tsx
  src/components/views/elements/RoomTopic.tsx
  src/components/views/elements/SpellCheckLanguagesDropdown.tsx
  src/components/views/location/LiveDurationDropdown.tsx
  src/components/views/spaces/QuickThemeSwitcher.tsx
  test/components/views/elements/EventListSummary-test.tsx
  test/components/views/elements/__snapshots__/FilterDropdown-test.tsx.snap
Labels: T-Task

#10475 Apply `strictNullChecks` to `src/components/structures/Space*`
  src/components/structures/SpaceHierarchy.tsx
  src/components/structures/SpaceRoomView.tsx
  src/stores/spaces/SpaceStore.ts
Labels: T-Task

#10474 Strictify `stores/room-list`
  src/stores/room-list/MessagePreviewStore.ts
  src/stores/room-list/RoomListStore.ts
  src/stores/room-list/algorithms/Algorithm.ts
  src/stores/room-list/algorithms/list-ordering/ImportanceAlgorithm.ts
  src/stores/room-list/algorithms/list-ordering/OrderingAlgorithm.ts
  src/stores/room-list/previews/MessageEventPreview.ts
  src/stores/room-list/previews/utils.ts
  src/utils/membership.ts
Labels: T-Task

#10478 Strictify `components/structures/Thread*`
  src/components/structures/ThreadPanel.tsx
  src/components/structures/ThreadView.tsx
Labels: T-Task

#10468 Update changelog for v3.69.0 now the security issue is public
  CHANGELOG.md
Labels: T-Task

#10360 Fix decryption failure bar covering the timeline
  cypress/e2e/crypto/decryption-failure.spec.ts
  res/css/_common.pcss
  res/css/views/rooms/_DecryptionFailureBar.pcss
  src/components/views/rooms/DecryptionFailureBar.tsx
  test/components/views/rooms/__snapshots__/DecryptionFailureBar-test.tsx.snap
Labels: Z-Community-PR, T-Defect, X-Needs-Percy

#10477 Update test interface to add call object
  test/LegacyCallHandler-test.ts
Labels: T-Task

#10476 Add aria labels to message search bar to improve accessibility
  src/components/views/rooms/SearchBar.tsx
Labels: T-Defect

#10440 Replace `newTranslatableError` with `UserFriendlyError` (#10440
  package.json
  src/@types/global.d.ts
  src/SlashCommands.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/editor/commands.tsx
  src/i18n/strings/en_EN.json
  src/languageHandler.tsx
  src/utils/AutoDiscoveryUtils.tsx
  test/languageHandler-test.ts
  yarn.lock
Labels: T-Task
