Repository matrix-org/matrix-react-sdk, pull requests merged in 2023-01, with the labels that each got.

#9841 Show room broadcast when ending a recording
  src/stores/RoomViewStore.tsx
  src/voice-broadcast/stores/VoiceBroadcastRecordingsStore.ts
  test/stores/RoomViewStore-test.ts
  test/voice-broadcast/stores/VoiceBroadcastRecordingsStore-test.ts
Labels: T-Task

#9831 Confirm listen to a broadcast while recording
  src/contexts/SDKContext.ts
  src/i18n/strings/en_EN.json
  src/voice-broadcast/components/molecules/ConfirmListeBroadcastStopCurrent.tsx
  src/voice-broadcast/index.ts
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  src/voice-broadcast/stores/VoiceBroadcastPlaybacksStore.ts
  test/LegacyCallHandler-test.ts
  test/components/views/voip/PipView-test.tsx
  test/stores/RoomViewStore-test.ts
  test/voice-broadcast/components/VoiceBroadcastBody-test.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody-test.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastPreRecordingPip-test.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastSmallPlaybackBody-test.tsx
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.tsx
  test/voice-broadcast/models/VoiceBroadcastPreRecording-test.ts
  test/voice-broadcast/stores/VoiceBroadcastPlaybacksStore-test.ts
  test/voice-broadcast/stores/VoiceBroadcastPreRecordingStore-test.ts
  test/voice-broadcast/utils/pauseNonLiveBroadcastFromOtherRoom-test.ts
  test/voice-broadcast/utils/setUpVoiceBroadcastPreRecording-test.ts
  test/voice-broadcast/utils/startNewVoiceBroadcastRecording-test.ts
Labels: T-Task

#9849 Use compound Mic icons everywhere
  res/css/views/rooms/_MessageComposer.pcss
  res/css/views/voip/LegacyCallView/_LegacyCallViewButtons.pcss
  res/css/views/voip/_CallView.pcss
  res/css/views/voip/_VideoFeed.pcss
  res/img/element-icons/Mic-off.svg
  res/img/element-icons/mic.svg
  res/img/voip/call-view/mic-off.svg
  res/img/voip/call-view/mic-on.svg
  res/img/voip/mic-muted.svg
  res/img/voip/mic-on-mask.svg
  res/img/voip/mic-unmuted.svg
  src/voice-broadcast/components/atoms/VoiceBroadcastHeader.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip.tsx
Labels: T-Task

#9799 static-user-onboarding-steps
  src/components/views/user-onboarding/UserOnboardingFeedback.tsx
  src/components/views/user-onboarding/UserOnboardingList.tsx
  src/components/views/user-onboarding/UserOnboardingPage.tsx
  src/components/views/user-onboarding/UserOnboardingTask.tsx
  src/hooks/useUserOnboardingContext.ts
  src/hooks/useUserOnboardingTasks.ts
  test/components/views/user-onboarding/UserOnboardingList-test.tsx
  test/components/views/user-onboarding/UserOnboardingPage-test.tsx
  test/hooks/useUserOnboardingTasks-test.tsx
Labels: Z-Community-PR, T-Enhancement

#9851 Fix export with attachments on formats txt and json
  src/utils/exportUtils/Exporter.ts
Labels: Z-Community-PR, T-Defect

#9818 Use Identity Server v2 API instead of v1
  cypress/fixtures/vector-im-identity-v2.json
  cypress/support/network.ts
  src/components/views/settings/SetIdServer.tsx
Labels: T-Task

#9826 Update netlify.yaml GHA to not refer to workflow name
  .github/workflows/netlify.yaml
Labels: T-Task

#9827 Fix emoji in RTE editing
  src/components/views/rooms/wysiwyg_composer/EditWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/components/Emoji.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useWysiwygEditActionHandler.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useWysiwygSendActionHandler.ts
  test/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/SendWysiwygComposer-test.tsx
Labels: T-Defect

#9800 Redesign the picture-in-picture window
  cypress/e2e/widgets/widget-pip-close.spec.ts
  res/css/_components.pcss
  res/css/components/views/pips/_WidgetPip.pcss
  res/css/views/messages/_LegacyCallEvent.pcss
  res/css/views/rooms/_AppsDrawer.pcss
  res/css/views/voip/LegacyCallView/_LegacyCallViewButtons.pcss
  res/css/views/voip/_CallView.pcss
  res/css/views/voip/_LegacyCallPreview.pcss
  res/css/views/voip/_PiPContainer.pcss
  res/img/element-icons/call/hangup.svg
  res/img/voip/call-view/hangup.svg
  res/img/voip/declined-voice.svg
  res/themes/dark/css/_dark.pcss
  res/themes/legacy-dark/css/_legacy-dark.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light/css/_light.pcss
  src/components/structures/LoggedInView.tsx
  src/components/structures/PictureInPictureDragger.tsx
  src/components/structures/PipContainer.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/elements/PersistedElement.tsx
  src/components/views/elements/PersistentApp.tsx
  src/components/views/pips/WidgetPip.tsx
  src/components/views/voip/PipContainer.tsx
  src/hooks/useCall.ts
  test/components/structures/PictureInPictureDragger-test.tsx
  test/components/structures/PipContainer-test.tsx
  test/components/structures/__snapshots__/PictureInPictureDragger-test.tsx.snap
Labels: T-Enhancement

#9840 Convert enzyme to rtl: BeaconMarker
  src/components/views/beacon/BeaconMarker.tsx
  test/components/views/beacon/BeaconMarker-test.tsx
  test/components/views/beacon/__snapshots__/BeaconMarker-test.tsx.snap
Labels: T-Task

#9776 Improve switching between rich and plain editing modes
  package.json
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/wysiwyg_composer/DynamicImportWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/usePlainTextListeners.ts
  src/components/views/rooms/wysiwyg_composer/index.ts
  src/components/views/rooms/wysiwyg_composer/utils/createMessageContent.ts
  src/components/views/rooms/wysiwyg_composer/utils/message.ts
  src/utils/room/htmlToPlaintext.ts
  test/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/PlainTextComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/utils/createMessageContent-test.ts
  test/components/views/rooms/wysiwyg_composer/utils/message-test.ts
  yarn.lock
Labels: T-Enhancement

#9862 Make calls automatically disconnect if the widget disappears
  src/models/Call.ts
  test/models/Call-test.ts
Labels: T-Defect

#9854 Fix space lock icon size
  cypress/e2e/spaces/spaces.spec.ts
  res/css/structures/_SpaceRoomView.pcss
  res/css/views/dialogs/_JoinRuleDropdown.pcss
  res/css/views/spaces/_SpaceCreateMenu.pcss
Labels: T-Defect, X-Needs-Percy

#9860 Disable bubbles for broadcasts
  src/utils/EventRenderingUtils.ts
  test/utils/EventRenderingUtils-test.ts
Labels: T-Enhancement

#9850 Use the same avatar colour when creating 1:1 DM rooms
  src/components/views/avatars/RoomAvatar.tsx
  test/components/structures/auth/ForgotPassword-test.tsx
  test/components/views/avatars/RoomAvatar-test.tsx
  test/components/views/avatars/__snapshots__/RoomAvatar-test.tsx.snap
  test/components/views/rooms/RoomTile-test.tsx
  test/components/views/user-onboarding/UserOnboardingPage-test.tsx
  test/test-utils/console.ts
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip-test.tsx
Labels: T-Defect

#9863 Remove unused function/file
  src/events/getReferenceRelationsForEvent.ts
  src/events/index.ts
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.tsx
Labels: T-Task

#9852 Mute notifications for broadcast chunks
  src/Notifier.ts
  test/Notifier-test.ts
  test/test-utils/client.ts
Labels: T-Task

#9711 Don't prefer STIXGeneral over the default font
  .github/workflows/cypress.yaml
  cypress/e2e/polls/polls.spec.ts
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light/css/_light.pcss
Labels: T-Defect, X-Needs-Percy

#9867 Change clear notifications to have more readable copy
  src/components/views/settings/Notifications.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#9865 Do not fail cypress GHA workflow; if testrail upload fails on some files.
  .github/workflows/cypress.yaml
Labels: T-Task

#9870 Enable sent receipt for poll start events (PSG-962)
  src/components/views/rooms/EventTile.tsx
Labels: T-Enhancement

#9869 Improve icon doc
  docs/icons.md
Labels: T-Task

#9858 Fix broadcast last sequence number
  src/voice-broadcast/models/VoiceBroadcastRecording.ts
  test/voice-broadcast/models/VoiceBroadcastRecording-test.ts
Labels: T-Task

#9874 Device manager - prune client information events after remote sign out
  src/components/views/settings/devices/useOwnDevices.ts
  src/utils/device/clientInformation.ts
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Enhancement

#9861 Change RTE mode icons
  res/img/element-icons/room/composer/plain_text.svg
  src/components/views/rooms/MessageComposerButtons.tsx
Labels: T-Enhancement

#9883 Remove unused/disabled room list drag&drop tests
  test/components/views/rooms/RoomList-test.tsx
Labels: T-Task

#9882 Factor out `MessageEvent.from()` usage
  cypress/e2e/editing/editing.spec.ts
  cypress/e2e/timeline/timeline.spec.ts
  test/components/structures/TimelinePanel-test.tsx
  test/components/views/context_menus/MessageContextMenu-test.tsx
  test/test-utils/events.ts
Labels: T-Task

#9881 Remove extensible events v1 experimental rendering
  src/TextForEvent.tsx
  src/components/views/messages/TextualBody.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Enhancement

#9864 Add edit and remove actions to link in RTE
  package.json
  res/css/views/rooms/wysiwyg_composer/components/_LinkModal.pcss
  src/components/views/elements/Field.tsx
  src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
  src/components/views/rooms/wysiwyg_composer/components/LinkModal.tsx
  src/i18n/strings/en_EN.json
  test/components/views/elements/Field-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/LinkModal-test.tsx
  yarn.lock
Labels: T-Enhancement

#9846 Convert enzyme to rtl: UserInfo
  src/components/views/right_panel/BaseCard.tsx
  src/components/views/right_panel/UserInfo.tsx
  test/components/views/right_panel/UserInfo-test.tsx
Labels: T-Task

#9887 Fix mock client missing user functions
  test/components/views/settings/Notifications-test.tsx
Labels: T-Task

#9875 Fix misaligned timestamps for thread roots which are emotes
  res/css/views/rooms/_EventTile.pcss
Labels: T-Defect

#9889 Fix unexpected composer growing
  package.json
  src/components/views/rooms/wysiwyg_composer/hooks/useInputEventProcessor.ts
  yarn.lock
Labels: T-Defect

#9892 Rewrite `cy.all` implementation
  cypress/support/util.ts
Labels: T-Task

#9523 Fix accessing room prop which is optional
  src/components/views/rooms/RoomPreviewBar.tsx
Labels: T-Task

#9886 Add a Cypress test for displaying edited events
  cypress/e2e/editing/editing.spec.ts
Labels: T-Task

#9872 Fix issue where thread dropdown would not show up correctly
  src/components/structures/ThreadPanel.tsx
  test/components/structures/ThreadPanel-test.tsx
Labels: T-Defect

#9890 [Release] Switch threads on for everyone
  cypress/e2e/polls/polls.spec.ts
  cypress/e2e/threads/threads.spec.ts
  src/MatrixClientPeg.ts
  src/components/structures/MessagePanel.tsx
  src/components/structures/RoomSearchView.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/SearchResultTile.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/components/views/rooms/wysiwyg_composer/utils/message.ts
  src/settings/Settings.tsx
  src/stores/TypingStore.ts
  src/stores/right-panel/RightPanelStore.ts
  src/stores/widgets/StopGapWidgetDriver.ts
  src/utils/Reply.ts
  src/utils/exportUtils/HtmlExport.tsx
  test/components/structures/TimelinePanel-test.tsx
  test/components/views/messages/MessageActionBar-test.tsx
  test/components/views/right_panel/RoomHeaderButtons-test.tsx
  test/components/views/rooms/EventTile-test.tsx
Labels: X-Release-Blocker, T-Enhancement

#9900 Bump analytics-events to 0.4.0 (allowing FavouriteMessages view)
  package.json
  yarn.lock
Labels: T-Task

#9895 Fix reply action in message context menu notif & file panels
  src/stores/RoomViewStore.tsx
  test/stores/RoomViewStore-test.ts
Labels: T-Defect

#9902 Parallelise Cypress runs once more
  .github/workflows/cypress.yaml
Labels: T-Task

#9908 Deflake new edited-event test
  cypress/e2e/editing/editing.spec.ts
Labels: T-Task

#9871 Add list functionality to rich text editor
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
  res/img/element-icons/room/composer/bulleted_list.svg
  res/img/element-icons/room/composer/numbered_list.svg
  src/components/views/rooms/wysiwyg_composer/components/Editor.tsx
  src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/wysiwyg_composer/components/FormattingButtons-test.tsx
Labels: T-Enhancement

#9904 Use js-sdk imports for poll event types instead of events-sdk
  cypress/e2e/polls/polls.spec.ts
  src/TextForEvent.tsx
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/dialogs/EndPollDialog.tsx
  src/components/views/elements/PollCreateDialog.tsx
  src/components/views/messages/MPollBody.tsx
  src/components/views/messages/MessageEvent.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
  src/components/views/rooms/PinnedEventTile.tsx
  src/events/EventTileFactory.tsx
  src/events/forward/getForwardableEvent.ts
  src/stores/room-list/MessagePreviewStore.ts
  src/stores/room-list/previews/PollStartEventPreview.ts
  src/utils/EventRenderingUtils.ts
  src/utils/EventUtils.ts
  src/utils/PinningUtils.ts
  test/components/views/context_menus/MessageContextMenu-test.tsx
  test/components/views/dialogs/ForwardDialog-test.tsx
  test/components/views/elements/PollCreateDialog-test.tsx
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/right_panel/PinnedMessagesCard-test.tsx
  test/test-utils/poll.ts
  test/utils/location/isSelfLocation-test.ts
Labels: T-Task

#9914 Fix error when viewing source of redacted events
  src/components/structures/ViewSource.tsx
  src/components/views/elements/SyntaxHighlight.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/ViewSource-test.tsx
  test/components/views/elements/SyntaxHighlight-test.tsx
  test/components/views/elements/__snapshots__/SyntaxHighlight-test.tsx.snap
Labels: Z-Community-PR, T-Defect

#9905 Device manager - tweak settings display
  res/css/views/dialogs/_UserSettingsDialog.pcss
  res/img/element-icons/settings/devices.svg
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
Labels: T-Enhancement

#9906 convert MPollBody tests into rtl
  src/components/views/messages/MPollBody.tsx
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/messages/__snapshots__/MPollBody-test.tsx.snap
Labels: T-Task

#9911 Clear isLogin theme override when user is no longer viewing login screens
  src/components/structures/MatrixChat.tsx
Labels: T-Defect

#9912 Replace outdated css attribute
  res/css/views/rooms/_EventTile.pcss
Labels: T-Defect

#9802 State event updates are not forwarded to the widget from invitation room
  cypress/e2e/widgets/events.spec.ts
  src/stores/widgets/StopGapWidget.ts
Labels: Z-Community-PR, T-Defect

#9885 Error handling if broadcast events could not be sent
  res/css/_components.pcss
  res/css/voice-broadcast/atoms/_VoiceBroadcastRecordingConnectionError.pcss
  src/i18n/strings/en_EN.json
  src/utils/createVoiceMessageContent.ts
  src/voice-broadcast/components/atoms/VoiceBroadcastRecordingConnectionError.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingBody.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip.tsx
  src/voice-broadcast/hooks/useVoiceBroadcastRecording.tsx
  src/voice-broadcast/index.ts
  src/voice-broadcast/models/VoiceBroadcastRecording.ts
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip-test.tsx
  test/voice-broadcast/models/VoiceBroadcastRecording-test.ts
Labels: T-Task

#9901 Only notify for first broadcast chunk
  src/Notifier.ts
  src/i18n/strings/en_EN.json
  test/Notifier-test.ts
Labels: T-Task

#9924 Fix: Poll replies overflow when not enough space
  res/css/views/rooms/_ReplyTile.pcss
Labels: T-Defect

#9925 Fix logout devices when resetting the password
  src/PasswordReset.ts
  src/components/structures/auth/ForgotPassword.tsx
  test/components/structures/auth/ForgotPassword-test.tsx
Labels: T-Defect

#9920 Fix cypress RTE flaky test
  cypress/e2e/composer/composer.spec.ts
  package.json
  test/components/views/rooms/wysiwyg_composer/components/FormattingButtons-test.tsx
  yarn.lock
Labels: T-Task

#9928 More tests :rocket:
  src/stores/widgets/WidgetLayoutStore.ts
  test/settings/handlers/RoomDeviceSettingsHandler-test.ts
  test/stores/AutoRageshakeStore-test.ts
  test/stores/WidgetLayoutStore-test.ts
Labels: T-Task

#9922 Fix broken threads list timestamp layout
  res/css/views/rooms/_EventTile.pcss
  src/components/views/messages/DisambiguatedProfile.tsx
  src/components/views/messages/SenderProfile.tsx
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#9933 replace .at() with array.length-1
  src/Unread.ts
Labels: X-Release-Blocker, T-Defect, backport staging

#9935 replace .at() with array.length-1
  src/Unread.ts
Labels: T-Defect

#9926 Fix the problem that the password reset email has to be confirmed twice
  src/components/structures/auth/ForgotPassword.tsx
  test/components/structures/auth/ForgotPassword-test.tsx
Labels: T-Defect

#9927 Fix {enter} press in RTE
  src/components/views/rooms/wysiwyg_composer/hooks/useInputEventProcessor.ts
  test/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
Labels: T-Defect

#9930 Add disabled button state to rich text editor
  res/css/views/rooms/wysiwyg_composer/components/_FormattingButtons.pcss
  src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
  test/components/views/rooms/wysiwyg_composer/components/FormattingButtons-test.tsx
Labels: T-Enhancement

#9936 Add new style for inline code
  res/css/_spacing.pcss
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
  res/themes/dark/css/_dark.pcss
  res/themes/legacy-dark/css/_legacy-dark.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light/css/_light.pcss
Labels: T-Enhancement

#9919 Add credentials when calling bootstrapCrossSigning in Cypress tests
  cypress/e2e/crypto/crypto.spec.ts
  cypress/e2e/crypto/decryption-failure.spec.ts
  cypress/support/bot.ts
  cypress/support/client.ts
  cypress/support/homeserver.ts
Labels: T-Task

#9921 Add code blocks to rich text editor
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
  res/img/element-icons/room/composer/code_block.svg
  src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
  test/components/views/rooms/wysiwyg_composer/components/FormattingButtons-test.tsx
Labels: T-Enhancement

#9948 Clear the RTE before sending a message
  src/components/views/rooms/MessageComposer.tsx
Labels: T-Defect

#9932 Quotes for rte
  package.json
  res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
  res/img/element-icons/room/composer/quote.svg
  src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
  test/components/views/rooms/wysiwyg_composer/components/FormattingButtons-test.tsx
  yarn.lock
Labels: T-Enhancement

#9947 Do not show a broadcast as live immediately after the recording has stopped
  src/hooks/useEventEmitter.ts
  src/voice-broadcast/hooks/useCurrentVoiceBroadcastPlayback.ts
  src/voice-broadcast/hooks/useCurrentVoiceBroadcastPreRecording.ts
  src/voice-broadcast/hooks/useCurrentVoiceBroadcastRecording.ts
  src/voice-broadcast/hooks/useVoiceBroadcastPlayback.ts
  src/voice-broadcast/hooks/useVoiceBroadcastRecording.tsx
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
Labels: T-Defect

#9943 Tweak call lobby buttons to more closely match designs
  res/css/views/voip/_CallView.pcss
  src/components/views/voip/CallView.tsx
Labels: T-Defect

#9942 Show the room name in the room header during calls
  res/css/views/rooms/_RoomHeader.pcss
  src/components/views/rooms/RoomHeader.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#9944 Prevent call durations from breaking onto multiple lines
  res/css/views/voip/_CallDuration.pcss
Labels: T-Defect

#9945 Only highlight focused menu item if focus is supposed to be visible
  res/css/views/context_menus/_IconizedContextMenu.pcss
Labels: T-Defect

#9934 refactor: sliding sync: convert to lists-as-keys rather than indexes
  cypress.config.ts
  cypress/e2e/sliding-sync/sliding-sync.ts
  cypress/plugins/sliding-sync/index.ts
  src/SlidingSyncManager.ts
  src/components/views/rooms/RoomSublist.tsx
  src/hooks/useSlidingSyncRoomSearch.ts
  src/stores/room-list/SlidingRoomListStore.ts
  test/SlidingSyncManager-test.ts
  test/hooks/useSlidingSyncRoomSearch-test.tsx
  test/stores/room-list/SlidingRoomListStore-test.ts
Labels: T-Task

#9949 Fix seekbar position for zero length audio
  src/utils/numbers.ts
  test/components/views/audio_messages/SeekBar-test.tsx
  test/components/views/audio_messages/__snapshots__/SeekBar-test.tsx.snap
  test/test-utils/audio.ts
  test/utils/numbers-test.ts
Labels: T-Defect

#9968 Stabilise seeking in broadcast
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.tsx
Labels: T-Task

#9971 #22204 Issue: Centered File info in lightbox
  res/css/views/elements/_ImageView.pcss
Labels: Z-Community-PR, T-Defect

#9969 Fix RTE focus behaviour in threads
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useWysiwygSendActionHandler.ts
  test/components/views/rooms/wysiwyg_composer/SendWysiwygComposer-test.tsx
Labels: T-Defect

#9970 Handle broadcast chunk errors
  src/i18n/strings/en_EN.json
  src/voice-broadcast/components/atoms/VoiceBroadcastError.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody.tsx
  src/voice-broadcast/index.ts
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  test/voice-broadcast/components/atoms/__snapshots__/VoiceBroadcastPlaybackControl-test.tsx.snap
  test/voice-broadcast/components/molecules/VoiceBroadcastPlaybackBody-test.tsx
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPlaybackBody-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastSmallPlaybackBody-test.tsx.snap
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.tsx
Labels: X-Release-Blocker, T-Task

#9974 Fix ongoing broadcast recording after connection error
  src/voice-broadcast/audio/VoiceBroadcastRecorder.ts
  src/voice-broadcast/models/VoiceBroadcastRecording.ts
  test/voice-broadcast/audio/VoiceBroadcastRecorder-test.ts
Labels: X-Release-Blocker, T-Task

#9978 Stop broadcasts on logout
  src/components/structures/MatrixChat.tsx
  src/voice-broadcast/index.ts
  src/voice-broadcast/utils/cleanUpBroadcasts.ts
  test/voice-broadcast/utils/cleanUpBroadcasts-test.ts
  test/voice-broadcast/utils/test-utils.ts
Labels: X-Release-Blocker, T-Task

#7275 Support registration tokens
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/i18n/strings/en_EN.json
  test/components/views/auth/RegistrationToken-test.tsx
Labels: Z-Community-PR, T-Enhancement

#9977 #23396 Issue Fix: Misaligned reply preview in thread composer
  res/css/views/rooms/_ReplyPreview.pcss
Labels: Z-Community-PR, T-Defect, X-Needs-Percy

#9988 Fix failing userAgentParser tests
  test/utils/device/parseUserAgent-test.ts
Labels: Z-Community-PR, T-Task

#9986 Fix link creation with backward selection
  cypress/e2e/composer/composer.spec.ts
  src/components/views/rooms/wysiwyg_composer/ComposerContext.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useComposerFunctions.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useSelection.ts
  src/components/views/rooms/wysiwyg_composer/types.ts
  src/components/views/rooms/wysiwyg_composer/utils/selection.ts
  test/components/views/rooms/wysiwyg_composer/SendWysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/LinkModal-test.tsx
Labels: T-Defect

#9985 Improve avatar settings accessibility
  src/components/views/settings/AvatarSetting.tsx
  test/components/views/settings/AvatarSetting-test.tsx
Labels: Z-Community-PR, T-Enhancement

#9994 Tests for AdvancedRoomSettingsTab
  test/components/views/settings/tabs/room/AdvancedRoomSettingsTab-test.tsx
  test/components/views/settings/tabs/room/__snapshots__/AdvancedRoomSettingsTab-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Task

#8681 Implementation of MSC3824 to make the client OIDC-aware
  src/BasePlatform.ts
  src/Lifecycle.ts
  src/Login.ts
  src/components/structures/auth/Login.tsx
  src/components/structures/auth/Registration.tsx
  src/components/structures/auth/SoftLogout.tsx
  src/components/views/elements/SSOButtons.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/auth/Login-test.tsx
  test/components/views/settings/tabs/user/GeneralUserSettingsTab-test.tsx
Labels: T-Enhancement

#9995 Implement MSC3946 for AdvancedRoomSettingsTab
  src/components/views/settings/tabs/room/AdvancedRoomSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/views/settings/tabs/room/AdvancedRoomSettingsTab-test.tsx
Labels: T-Enhancement

#9997 Tests for RoomCreate
  src/components/views/messages/RoomCreate.tsx
  test/components/views/messages/RoomCreate-test.tsx
  test/components/views/messages/__snapshots__/RoomCreate-test.tsx.snap
Labels: T-Task

#10016 changing the color of message time stamp
  res/css/views/right_panel/_ThreadPanel.pcss
Labels: Z-Community-PR, T-Defect

#9990 Member avatars without canvas
  res/css/views/rooms/_BasicMessageComposer.pcss
  src/Avatar.ts
  src/components/views/avatars/BaseAvatar.tsx
  src/components/views/avatars/MemberAvatar.tsx
  src/components/views/avatars/RoomAvatar.tsx
  src/dispatcher/payloads/ViewUserPayload.ts
  src/editor/parts.ts
  test/Avatar-test.ts
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/structures/__snapshots__/UserMenu-test.tsx.snap
  test/components/views/avatars/BaseAvatar-test.tsx
  test/components/views/avatars/MemberAvatar-test.tsx
  test/components/views/avatars/RoomAvatar-test.tsx
  test/components/views/avatars/__snapshots__/BaseAvatar-test.tsx.snap
  test/components/views/avatars/__snapshots__/MemberAvatar-test.tsx.snap
  test/components/views/avatars/__snapshots__/RoomAvatar-test.tsx.snap
  test/components/views/beacon/__snapshots__/BeaconMarker-test.tsx.snap
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomTile-test.tsx.snap
  test/editor/__snapshots__/parts-test.ts.snap
  test/editor/parts-test.ts
Labels: Z-Community-PR, T-Defect, X-Needs-Percy

#9880 Should open new 1:1 chat room after leaving the old one
  cypress/e2e/one-to-one-chat/one-to-one-chat.spec.ts
  src/components/structures/MatrixChat.tsx
Labels: Z-Community-PR, T-Defect

#9999 Change RoomCreate to a functional component
  src/components/views/messages/RoomCreate.tsx
  src/events/EventTileFactory.tsx
  test/components/views/messages/RoomCreate-test.tsx
Labels: T-Task

#9907 Update to supportsThreads
  src/MatrixClientPeg.ts
  src/utils/EventUtils.ts
  test/Notifier-test.ts
  test/Unread-test.ts
  test/components/structures/RoomSearchView-test.tsx
  test/components/structures/ThreadPanel-test.tsx
  test/components/structures/ThreadView-test.tsx
  test/components/structures/TimelinePanel-test.tsx
  test/components/views/right_panel/RoomHeaderButtons-test.tsx
  test/components/views/rooms/EventTile-test.tsx
  test/components/views/rooms/NotificationBadge/UnreadNotificationBadge-test.tsx
  test/components/views/settings/Notifications-test.tsx
  test/stores/RoomViewStore-test.ts
  test/test-utils/test-utils.ts
  test/utils/EventUtils-test.ts
Labels: T-Task

#9975 Fix "[object Promise]" appearing in HTML exports
  src/DateUtils.ts
  src/components/structures/MessagePanel.tsx
  src/components/views/dialogs/MessageEditHistoryDialog.tsx
  src/components/views/rooms/SearchResultTile.tsx
  src/utils/exportUtils/HtmlExport.tsx
  src/utils/exportUtils/exportCSS.ts
  test/components/views/dialogs/MessageEditHistoryDialog-test.tsx
  test/components/views/dialogs/__snapshots__/MessageEditHistoryDialog-test.tsx.snap
  test/components/views/rooms/SearchResultTile-test.tsx
  test/test-utils/test-utils.ts
  test/utils/exportUtils/HTMLExport-test.ts
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
  test/utils/exportUtils/exportCSS-test.ts
Labels: Z-Community-PR, T-Defect

#10022 Fix new tests introduced by html export tweaks
  test/utils/exportUtils/HTMLExport-test.ts
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
Labels: T-Task

#9993 Use CopyableText in devtools
  src/components/views/dialogs/DevtoolsDialog.tsx
  test/components/views/dialogs/DevtoolsDialog-test.tsx
  test/components/views/dialogs/__snapshots__/DevtoolsDialog-test.tsx.snap
Labels: T-Task

#10006 Implement more robust broadcast chunk header detection
  src/voice-broadcast/audio/VoiceBroadcastRecorder.ts
  test/voice-broadcast/audio/VoiceBroadcastRecorder-test.ts
Labels: T-Task

#6116 Add ignore user confirmation dialog
  src/components/views/right_panel/UserInfo.tsx
  src/i18n/strings/en_EN.json
  test/components/views/right_panel/UserInfo-test.tsx
Labels: T-Enhancement

#10008 Paragraph integration for rich text editor
  package.json
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
  yarn.lock
Labels: T-Enhancement

#9923 Migrate highlight.js API call in TextualBody
  src/components/views/messages/TextualBody.tsx
Labels: Z-Community-PR, T-Task

#10018 Fix MessageEditHistoryDialog crashing on complex input
  src/utils/MessageDiffUtils.tsx
  test/utils/MessageDiffUtils-test.tsx
  test/utils/__snapshots__/MessageDiffUtils-test.tsx.snap
Labels: Z-Community-PR, T-Defect

#9941 Unify unread notification state determination
  src/RoomNotifs.ts
  src/hooks/useUnreadNotifications.ts
  src/stores/local-echo/RoomEchoChamber.ts
  src/stores/notifications/RoomNotificationState.ts
  test/RoomNotifs-test.ts
  test/components/views/rooms/NotificationBadge/UnreadNotificationBadge-test.tsx
  test/hooks/useUnreadNotifications-test.ts
  test/stores/notifications/RoomNotificationState-test.ts
  test/test-utils/test-utils.ts
Labels: Z-Community-PR, T-Defect

#10030 Fix useUnreadNotifications exploding with falsey room, like in notif panel
  src/RoomNotifs.ts
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/NotificationBadge/UnreadNotificationBadge.tsx
  src/hooks/useUnreadNotifications.ts
Labels: T-Defect

#9294 fix regional emojis converted to flags
  cypress/e2e/timeline/timeline.spec.ts
  src/HtmlUtils.tsx
  src/editor/parts.ts
  test/editor/model-test.ts
Labels: Z-Community-PR, T-Defect

#10031 Fix layout and visual regressions around default avatars
  cypress/e2e/spaces/spaces.spec.ts
  res/css/structures/_SpacePanel.pcss
  res/css/structures/_UserMenu.pcss
  src/components/views/avatars/BaseAvatar.tsx
  test/components/views/avatars/__snapshots__/MemberAvatar-test.tsx.snap
Labels: X-Release-Blocker, T-Defect, X-Needs-Percy

#10028 resolved emoji description text overflowing issue
  res/css/views/emojipicker/_EmojiPicker.pcss
Labels: Z-Community-PR, T-Defect

#10023 Cleanup pre MSC3773 thread unread notif logic
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/components/views/rooms/EventTile.tsx
  src/stores/notifications/RoomNotificationState.ts
  src/stores/notifications/RoomNotificationStateStore.ts
  src/stores/notifications/ThreadNotificationState.ts
  src/stores/notifications/ThreadsRoomNotificationState.ts
  test/components/views/right_panel/RoomHeaderButtons-test.tsx
  test/stores/notifications/RoomNotificationStateStore-test.ts
Labels: T-Task

#10034 Add indentation increasing/decreasing to RTE
  package.json
  res/img/element-icons/room/composer/indent_decrease.svg
  res/img/element-icons/room/composer/indent_increase.svg
  src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/wysiwyg_composer/components/FormattingButtons-test.tsx
  yarn.lock
Labels: T-Enhancement
