Repository matrix-org/matrix-react-sdk, pull requests merged in 2023-02, with the labels that each got.

#10035 Replace list, code block and quote icons by new icons
  res/img/element-icons/room/composer/bulleted_list.svg
  res/img/element-icons/room/composer/code_block.svg
  res/img/element-icons/room/composer/numbered_list.svg
  res/img/element-icons/room/composer/quote.svg
Labels: T-Defect

#10038 Remove threads beta feedback button
  src/components/structures/ThreadPanel.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/ThreadPanel-test.tsx
Labels: T-Task

#9980 Add RTE keyboard navigation in editing
  src/components/views/rooms/wysiwyg_composer/ComposerContext.ts
  src/components/views/rooms/wysiwyg_composer/EditWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/components/WysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useInputEventProcessor.ts
  src/components/views/rooms/wysiwyg_composer/hooks/usePlainTextListeners.ts
  src/components/views/rooms/wysiwyg_composer/utils/event.ts
  src/components/views/rooms/wysiwyg_composer/utils/selection.ts
  test/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
Labels: T-Enhancement

#10021 Implement broadcast UTD handling
  src/events/EventTileFactory.tsx
  src/i18n/strings/en_EN.json
  src/voice-broadcast/index.ts
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  src/voice-broadcast/utils/isRelatedToVoiceBroadcast.ts
  test/events/EventTileFactory-test.ts
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.tsx
  test/voice-broadcast/utils/isRelatedToVoiceBroadcast-test.ts
Labels: T-Task

#10040 Add PiP move threshold
  src/components/structures/PictureInPictureDragger.tsx
  test/components/structures/PictureInPictureDragger-test.tsx
Labels: T-Enhancement

#10012 Use Room.findPredecessor when rendering RoomCreate tiles
  src/components/views/messages/RoomCreate.tsx
  test/components/views/messages/RoomCreate-test.tsx
Labels: T-Task

#9894 Include percy in branch protection conditionally
  .github/workflows/cypress.yaml
Labels: T-Task

#10039 Poll history - setup labs setting
  res/css/views/right_panel/_RoomSummaryCard.pcss
  src/components/views/dialogs/polls/PollHistoryDialog.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/views/right_panel/RoomSummaryCard-test.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
Labels: T-Task

#10043 Change ul list style to disc when editing message
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
Labels: T-Enhancement

#10057 Revert "Member avatars without canvas" (#10057
  cypress/e2e/spaces/spaces.spec.ts
  res/css/structures/_SpacePanel.pcss
  res/css/views/avatars/_BaseAvatar.pcss
  res/css/views/rooms/_BasicMessageComposer.pcss
  src/Avatar.ts
  src/components/views/avatars/BaseAvatar.tsx
  src/components/views/avatars/MemberAvatar.tsx
  src/components/views/avatars/RoomAvatar.tsx
  src/dispatcher/payloads/ViewUserPayload.ts
  src/editor/parts.ts
  test/Avatar-test.ts
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/structures/__snapshots__/UserMenu-test.tsx.snap
  test/components/views/avatars/BaseAvatar-test.tsx
  test/components/views/avatars/MemberAvatar-test.tsx
  test/components/views/avatars/RoomAvatar-test.tsx
  test/components/views/avatars/__snapshots__/BaseAvatar-test.tsx.snap
  test/components/views/avatars/__snapshots__/MemberAvatar-test.tsx.snap
  test/components/views/avatars/__snapshots__/RoomAvatar-test.tsx.snap
  test/components/views/beacon/__snapshots__/BeaconMarker-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomTile-test.tsx.snap
  test/editor/__snapshots__/parts-test.ts.snap
  test/editor/parts-test.ts
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
Labels: T-Task

#10058 Update labs flag description for RTE
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Enhancement

#10046 Tests for RoomListStore's predecessor handling
  src/stores/room-list/RoomListStore.ts
  test/stores/room-list/RoomListStore-test.ts
Labels: T-Task

#10041 Support MSC3946 in the RoomCreate tile
  src/components/views/messages/RoomCreate.tsx
  test/components/views/messages/RoomCreate-test.tsx
Labels: T-Enhancement

#10061 Enable spaces cypress tests again
  cypress/e2e/spaces/spaces.spec.ts
Labels: T-Task

#10062 Fix new line for inline code
  res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
Labels: T-Defect

#10049 Exclude devtools view from coverage checks
  sonar-project.properties
Labels: T-Task

#10010 Ensure room is actually in space hierarchy when resolving its latest version
  src/components/structures/SpaceHierarchy.tsx
  test/components/structures/SpaceHierarchy-test.tsx
  test/components/structures/__snapshots__/SpaceHierarchy-test.tsx.snap
Labels: T-Defect

#9877 use Poll model with relations API in poll rendering
  res/css/views/messages/_MPollBody.pcss
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/dialogs/EndPollDialog.tsx
  src/components/views/messages/MPollBody.tsx
  src/components/views/right_panel/PinnedMessagesCard.tsx
  src/components/views/rooms/PinnedEventTile.tsx
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/messages/__snapshots__/MPollBody-test.tsx.snap
  test/components/views/right_panel/PinnedMessagesCard-test.tsx
Labels: T-Enhancement

#10055 Poll history - read only list of polls in current timeline
  res/css/_components.pcss
  res/css/components/views/dialogs/polls/_PollListItem.pcss
  res/css/views/dialogs/polls/_PollHistoryDialog.pcss
  res/css/views/dialogs/polls/_PollHistoryList.pcss
  src/DateUtils.ts
  src/components/views/dialogs/polls/PollHistoryDialog.tsx
  src/components/views/dialogs/polls/PollHistoryList.tsx
  src/components/views/dialogs/polls/PollListItem.tsx
  src/components/views/dialogs/polls/usePollHistory.ts
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/polls/PollHistoryDialog-test.tsx
  test/components/views/dialogs/polls/PollListItem-test.tsx
  test/components/views/dialogs/polls/__snapshots__/PollHistoryDialog-test.tsx.snap
  test/components/views/dialogs/polls/__snapshots__/PollListItem-test.tsx.snap
  test/components/views/right_panel/RoomSummaryCard-test.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/test-utils/date.ts
  test/test-utils/poll.ts
  test/utils/DateUtils-test.ts
Labels: T-Task

#10048 Autofocus security key field
  src/components/views/dialogs/security/AccessSecretStorageDialog.tsx
  test/components/views/dialogs/AccessSecretStorageDialog-test.tsx
Labels: T-Enhancement

#10060 Switch to linkify-react for element Linkification as it handles React subtrees without exploding (#10060
  cypress/e2e/spaces/spaces.spec.ts
  package.json
  src/HtmlUtils.tsx
  src/SlashCommands.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/SpaceHierarchy.tsx
  src/components/views/elements/Linkify.tsx
  src/components/views/elements/RoomTopic.tsx
  src/components/views/messages/TextualBody.tsx
  src/components/views/rooms/LinkPreviewWidget.tsx
  src/components/views/rooms/RoomInfoLine.tsx
  src/linkify-matrix.ts
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/elements/Linkify-test.tsx
  yarn.lock
Labels: X-Release-Blocker, T-Defect

#10054 Support MSC3946 in RoomListStore
  src/stores/room-list/RoomListStore.ts
  test/stores/room-list/RoomListStore-test.ts
Labels: T-Enhancement

#10064 Fix cursor position when new line is created by pressing enter (RTE)
  src/components/views/rooms/wysiwyg_composer/hooks/useInputEventProcessor.ts
  test/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
Labels: T-Defect

#10067 Use findPredecessor in RoomNotifs#getUnreadNotificationCount
  src/RoomNotifs.ts
  test/RoomNotifs-test.ts
Labels: T-Task

#10070 Cut off broadcast time left at 0 seconds
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.tsx
Labels: T-Defect

#10071 fix issue 24419: paragraph display in timeline
  res/css/views/rooms/_EventTile.pcss
Labels: T-Defect

#10068 Hide superseded rooms from the room list using dynamic room predecessors
  src/stores/room-list/RoomListStore.ts
  test/stores/room-list/RoomListStore-test.ts
Labels: T-Enhancement

#10076 Migrate SpotlightDialog for dynamic room predecessors
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  test/components/views/dialogs/SpotlightDialog-test.tsx
Labels: T-Task

#10073 Improve typescript null checking in places (#10073 (#10073
  src/Avatar.ts
  src/BasePlatform.ts
  src/ContentMessages.ts
  src/DecryptionFailureTracker.ts
  src/DeviceListener.ts
  src/ImageUtils.ts
  src/accessibility/KeyboardShortcutUtils.ts
  src/accessibility/RovingTabIndex.tsx
  src/actions/MatrixActionCreators.ts
  src/audio/PlaybackQueue.ts
  src/autocomplete/AutocompleteProvider.tsx
  src/autocomplete/Autocompleter.ts
  src/autocomplete/CommandProvider.tsx
  src/autocomplete/RoomProvider.tsx
  src/components/structures/MatrixChat.tsx
  src/components/views/messages/MKeyVerificationConclusion.tsx
  src/createRoom.ts
  src/customisations/Media.ts
  src/customisations/Security.ts
  src/customisations/models/IMediaEventContent.ts
  src/editor/caret.ts
  src/editor/deserialize.ts
  src/editor/history.ts
  src/editor/model.ts
  src/editor/parts.ts
  src/editor/position.ts
  src/editor/render.ts
  src/stores/OwnProfileStore.ts
  src/stores/ReadyWatchingStore.ts
  src/stores/UIStore.ts
  src/stores/spaces/flattenSpaceHierarchy.ts
  src/toasts/UpdateToast.tsx
  src/utils/DialogOpener.ts
  src/utils/RoomUpgrade.ts
  src/utils/ShieldUtils.ts
  src/utils/StorageManager.ts
  src/utils/Timer.ts
  src/utils/UrlUtils.ts
  src/utils/arrays.ts
  src/utils/leave-behaviour.ts
  src/utils/permalinks/Permalinks.ts
  src/utils/space.tsx
  src/utils/tooltipify.tsx
Labels: T-Task

#10075 Gitter sunsetting: Use findPredecessor in EventTileFactory
  cypress/e2e/timeline/timeline.spec.ts
  src/events/EventTileFactory.tsx
  test/components/structures/MessagePanel-test.tsx
  test/events/EventTileFactory-test.ts
Labels: T-Task

#10079 Open message in editing mode when keyboard up is pressed (RTE)
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/wysiwyg_composer/ComposerContext.ts
  src/components/views/rooms/wysiwyg_composer/SendWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useInitialContent.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useInputEventProcessor.ts
  src/components/views/rooms/wysiwyg_composer/utils/event.ts
  src/components/views/rooms/wysiwyg_composer/utils/selection.ts
  test/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/SendWysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/utils.ts
Labels: T-Enhancement

#10047 Rename RoomPredecessorTile
  src/components/views/messages/RoomPredecessorTile.tsx
  src/events/EventTileFactory.tsx
  test/components/views/messages/RoomPredecessorTile-test.tsx
  test/components/views/messages/__snapshots__/RoomPredecessorTile-test.tsx.snap
Labels: T-Task

#9205 Add border to 'reject' button on room preview card
  src/components/views/rooms/RoomPreviewCard.tsx
Labels: Z-Community-PR, T-Defect

#10081 Element-R: fix rageshages
  src/rageshake/submit-rageshake.ts
  src/sentry.ts
Labels: T-Defect

#10072 Fix broadcast pip seekbar
  src/components/structures/PipContainer.tsx
Labels: T-Defect

#10092 Fix flaky test crypto/decryption-failure.spec.ts "Decryption Failure Bar"
  cypress/e2e/crypto/decryption-failure.spec.ts
  cypress/support/bot.ts
Labels: T-Task

#10097 Add a whitespace character after 'broadcast?'
  src/i18n/strings/en_EN.json
  src/voice-broadcast/hooks/useVoiceBroadcastRecording.tsx
Labels: Z-Community-PR, T-Defect

#10033 Show buffering while waiting for broadcast chunk
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.tsx
Labels: X-Release-Blocker, T-Task

#10093 Fix scrollbar colliding with checkbox in add to space section
  res/css/views/dialogs/_AddExistingToSpaceDialog.pcss
Labels: Z-Community-PR, T-Defect

#10091 Add @typescript-eslint/no-base-to-string
  .eslintrc.js
  package.json
  src/components/views/dialogs/ServerOfflineDialog.tsx
  src/components/views/settings/ProfileSettings.tsx
  src/rageshake/submit-rageshake.ts
  src/stores/widgets/StopGapWidget.ts
  src/utils/FileUtils.ts
  src/utils/Whenable.ts
  src/utils/exportUtils/HtmlExport.tsx
  yarn.lock
Labels: T-Task

#10087 Fix wrongly grouping 3pid invites into a single repeated transition
  src/components/views/elements/EventListSummary.tsx
  test/components/views/elements/EventListSummary-test.tsx
Labels: T-Defect

#10096 Indicate unread messages in tab title
  src/components/structures/MatrixChat.tsx
Labels: Z-Community-PR, T-Enhancement

#10099 Fix a crash when removing persistent widgets (updated)
  src/components/structures/PipContainer.tsx
Labels: X-Release-Blocker, T-Defect

#10027 Render poll end events in timeline
  res/css/_components.pcss
  res/css/views/messages/_MPollEndBody.pcss
  res/img/element-icons/room/composer/poll.svg
  src/components/views/messages/MPollEndBody.tsx
  src/components/views/messages/MessageEvent.tsx
  src/events/EventTileFactory.tsx
  src/events/forward/getForwardableEvent.ts
  src/utils/EventRenderingUtils.ts
  src/utils/EventUtils.ts
  test/components/views/dialogs/polls/PollHistoryDialog-test.tsx
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/messages/MPollEndBody-test.tsx
  test/components/views/messages/__snapshots__/MPollEndBody-test.tsx.snap
  test/test-utils/poll.ts
Labels: T-Enhancement

#10104 Migrate `ZoomButtons-test` to react-testing-library
  src/components/views/location/ZoomButtons.tsx
  test/components/views/location/ZoomButtons-test.tsx
  test/components/views/location/__snapshots__/LocationViewDialog-test.tsx.snap
  test/components/views/location/__snapshots__/ZoomButtons-test.tsx.snap
Labels: T-Task

#10111 Make TS strict the effects folder
  src/effects/confetti/index.ts
  src/effects/fireworks/index.ts
  src/effects/hearts/index.ts
  src/effects/rainfall/index.ts
  src/effects/snowfall/index.ts
  src/effects/spaceinvaders/index.ts
Labels: T-Task

#10112 Checkout PR head for strict error checker
  .github/workflows/static_analysis.yaml
Labels: T-Task

#10108 Correctly Identify emoticons
  src/components/views/rooms/BasicMessageComposer.tsx
  test/components/views/rooms/BasicMessageComposer-test.tsx
Labels: Z-Community-PR, T-Defect

#10114 Fix some inconsistencies in error messages
  src/PasswordReset.ts
  src/components/views/settings/devices/DeviceSecurityLearnMore.tsx
  src/i18n/strings/en_EN.json
Labels: Z-Community-PR, T-Task

#10078 Improve types of sticky rooms
  src/stores/room-list/algorithms/Algorithm.ts
Labels: T-Task

#10120 Migrate SpaceContextMenu-test.tsx to react-testing-library
  src/components/views/context_menus/SpaceContextMenu.tsx
  test/components/views/context_menus/SpaceContextMenu-test.tsx
  test/components/views/context_menus/__snapshots__/SpaceContextMenu-test.tsx.snap
Labels: T-Task

#10115 Migrate LabelledCheckbox-test to react-testing-library
  test/components/views/elements/LabelledCheckbox-test.tsx
  test/components/views/elements/__snapshots__/LabelledCheckbox-test.tsx.snap
Labels: T-Task

#10122 Fix test failures: provide isIntialSyncComplete on mock client
  test/stores/RoomViewStore-test.ts
Labels: T-Task

#10123 Fix predecessor tests broken
  test/RoomNotifs-test.ts
  test/components/views/settings/Notifications-test.tsx
  test/stores/RoomViewStore-test.ts
Labels: T-Task

#10088 Migrate RoomView to support MSC3946
  src/components/structures/RoomView.tsx
  src/contexts/RoomContext.ts
  test/components/structures/RoomView-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/test-utils/room.ts
Labels: T-Task

#10129 Remove a redundant white space
  src/components/views/settings/SecureBackupPanel.tsx
  src/i18n/strings/en_EN.json
Labels: Z-Community-PR, T-Defect

#10128 Fix Selectable Text on 'Delete All' and 'Retry All' Buttons
  res/css/structures/_RoomStatusBar.pcss
Labels: Z-Community-PR, T-Defect

#10134 Migrate InteractiveAuthDialog-test.tsx to react-testing-library
  test/components/views/dialogs/InteractiveAuthDialog-test.tsx
Labels: T-Task

#10133 Migrate OwnBeaconStatus-test.tsx to react-testing-library
  test/components/views/beacon/OwnBeaconStatus-test.tsx
  test/components/views/beacon/__snapshots__/OwnBeaconStatus-test.tsx.snap
Labels: T-Task

#10130 Remove white space characters before the horizontal ellipsis
  src/components/views/messages/MKeyVerificationRequest.tsx
  src/i18n/strings/en_EN.json
Labels: Z-Community-PR, T-Defect

#10138 TypeScript strict fixes
  src/UserActivity.ts
  src/VoipUserMapper.ts
  src/WhoIsTyping.ts
  src/verification.ts
Labels: T-Task

#10098 Poll history - filter by active or ended
  res/css/_components.pcss
  res/css/components/views/elements/_FilterTabGroup.pcss
  src/components/views/dialogs/polls/PollHistoryDialog.tsx
  src/components/views/dialogs/polls/PollHistoryList.tsx
  src/components/views/dialogs/polls/types.ts
  src/components/views/dialogs/polls/usePollHistory.ts
  src/components/views/elements/FilterTabGroup.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/polls/PollHistoryDialog-test.tsx
  test/components/views/dialogs/polls/__snapshots__/PollHistoryDialog-test.tsx.snap
  test/components/views/elements/FilterTabGroup-test.tsx
  test/components/views/elements/__snapshots__/FilterTabGroup-test.tsx.snap
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/messages/MPollEndBody-test.tsx
  test/test-utils/poll.ts
Labels: T-Task

#10107 Poll history - extract poll option display components
  cypress/e2e/polls/polls.spec.ts
  res/css/_components.pcss
  res/css/components/views/polls/_PollOption.pcss
  res/css/views/messages/_MPollBody.pcss
  res/img/element-icons/trophy.svg
  src/components/views/messages/MPollBody.tsx
  src/components/views/polls/PollOption.tsx
  src/i18n/strings/en_EN.json
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/messages/__snapshots__/MPollBody-test.tsx.snap
  test/components/views/messages/__snapshots__/MPollEndBody-test.tsx.snap
  test/components/views/right_panel/PinnedMessagesCard-test.tsx
  test/components/views/settings/devices/FilteredDeviceList-test.tsx
Labels: T-Task

#10127 Examine all m.direct rooms to find a DM as fallback
  src/utils/DMRoomMap.ts
  src/utils/dm/findDMForUser.ts
  src/utils/dm/findDMRoom.ts
  test/LegacyCallHandler-test.ts
  test/utils/DMRoomMap-test.ts
  test/utils/dm/findDMForUser-test.ts
  test/utils/dm/findDMRoom-test.ts
Labels: T-Defect

#10143 Use '_t' for caption to have strings localized
  src/settings/Settings.tsx
Labels: Z-Community-PR, T-Defect

#10141 Remove ineffective white space characters from VerifyEmailModal.tsx
  src/components/structures/auth/forgot-password/VerifyEmailModal.tsx
  src/i18n/strings/en_EN.json
Labels: Z-Community-PR, T-Task

#10139 Remove duplicate translated string
  src/SlashCommands.tsx
  src/async-components/views/dialogs/security/CreateKeyBackupDialog.tsx
  src/components/structures/auth/SoftLogout.tsx
  src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx
  src/components/views/rooms/RoomUpgradeWarningBar.tsx
  src/components/views/settings/tabs/room/AdvancedRoomSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: Z-Community-PR, T-Task

#10140 Improve localization experience on Weblate
  src/components/views/auth/LoginWithQRFlow.tsx
  src/components/views/dialogs/IntegrationsDisabledDialog.tsx
  src/components/views/settings/tabs/user/MjolnirUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: Z-Community-PR, T-Task

#10083 Add option to find own location in map views
  src/components/views/beacon/BeaconViewDialog.tsx
  src/components/views/location/LocationPicker.tsx
  src/components/views/location/LocationViewDialog.tsx
  src/components/views/location/Map.tsx
  src/i18n/strings/en_EN.json
  src/utils/location/index.ts
  src/utils/location/map.ts
  src/utils/location/positionFailureMessage.ts
  src/utils/location/useMap.ts
  test/components/views/location/Map-test.tsx
  test/components/views/location/__snapshots__/LocationViewDialog-test.tsx.snap
  test/components/views/messages/MBeaconBody-test.tsx
  test/utils/location/positionFailureMessage-test.ts
Labels: T-Enhancement

#10146 add Ended poll text to ended poll reply formatted body
  src/utils/Reply.ts
  test/Reply-test.ts
  test/__snapshots__/Reply-test.ts.snap
Labels: T-Task

#10151 Migrate LiveDurationDropdown-test.tsx to react-testing-library
  test/components/views/location/LiveDurationDropdown-test.tsx
Labels: T-Task

#10152 Remove duplicate white space characters from translation keys
  src/components/views/dialogs/ReportEventDialog.tsx
  src/i18n/strings/en_EN.json
Labels: Z-Community-PR, T-Defect

#10144 Fix 'Failed check: Ellipsis' on Weblate
  src/async-components/views/dialogs/security/CreateKeyBackupDialog.tsx
  src/components/structures/SpaceHierarchy.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/structures/auth/Login.tsx
  src/components/views/auth/LoginWithQRFlow.tsx
  src/components/views/auth/PassphraseField.tsx
  src/components/views/beacon/BeaconStatus.tsx
  src/components/views/dialogs/CreateSubspaceDialog.tsx
  src/components/views/dialogs/DeactivateAccountDialog.tsx
  src/components/views/dialogs/ExportDialog.tsx
  src/components/views/dialogs/IncomingSasDialog.tsx
  src/components/views/dialogs/SlidingSyncOptionsDialog.tsx
  src/components/views/dialogs/TextInputDialog.tsx
  src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/elements/InlineSpinner.tsx
  src/components/views/elements/PollCreateDialog.tsx
  src/components/views/elements/Spinner.tsx
  src/components/views/rooms/DecryptionFailureBar.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/components/views/settings/IntegrationManager.tsx
  src/components/views/settings/SecureBackupPanel.tsx
  src/components/views/settings/UpdateCheckButton.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
  src/components/views/spaces/SpaceSettingsGeneralTab.tsx
  src/i18n/strings/en_EN.json
  src/utils/ErrorUtils.tsx
  src/utils/exportUtils/HtmlExport.tsx
  src/utils/exportUtils/PlainTextExport.ts
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/structures/auth/Login-test.tsx
  test/components/structures/auth/Registration-test.tsx
  test/components/views/beacon/__snapshots__/BeaconStatus-test.tsx.snap
  test/components/views/beacon/__snapshots__/OwnBeaconStatus-test.tsx.snap
  test/components/views/elements/__snapshots__/PollCreateDialog-test.tsx.snap
  test/components/views/messages/MBeaconBody-test.tsx
  test/components/views/messages/__snapshots__/MPollBody-test.tsx.snap
  test/components/views/messages/__snapshots__/MPollEndBody-test.tsx.snap
  test/components/views/rooms/RoomPreviewBar-test.tsx
  test/components/views/rooms/__snapshots__/DecryptionFailureBar-test.tsx.snap
  test/components/views/settings/__snapshots__/FontScalingPanel-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/LoginWithQRFlow-test.tsx.snap
  test/modules/__snapshots__/ModuleComponents-test.tsx.snap
  test/voice-broadcast/components/atoms/__snapshots__/VoiceBroadcastHeader-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPlaybackBody-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastSmallPlaybackBody-test.tsx.snap
Labels: Z-Community-PR, T-Task

#10149 Hide indent button in rte
  package.json
  src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
  test/components/views/rooms/wysiwyg_composer/components/FormattingButtons-test.tsx
  yarn.lock
Labels: T-Enhancement

#10150 Fix email lookup in invite dialog
  src/components/views/dialogs/InviteDialog.tsx
  test/components/views/dialogs/InviteDialog-test.tsx
Labels: T-Defect

#10162 Convert usePublicRoomDirectory
  test/hooks/usePublicRoomDirectory-test.tsx
Labels: T-Task

#10161 Convert useSlidingSyncRoomSearch from enzyme to RTL
  test/hooks/useSlidingSyncRoomSearch-test.tsx
Labels: T-Task

#10160 Convert useUserDirectory to RTL
  test/hooks/useUserDirectory-test.tsx
Labels: T-Task

#10168 Disable poll response loading test
  test/components/views/messages/MPollBody-test.tsx
Labels: T-Defect

#10066 Release Sign in with QR out of labs
  src/components/views/settings/devices/LoginWithQRSection.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/views/settings/devices/LoginWithQRSection-test.tsx
  test/components/views/settings/devices/__snapshots__/LoginWithQRSection-test.tsx.snap
  test/components/views/settings/tabs/user/SecurityUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Enhancement

#10173 Revert "Run Percy for all Cypress runs"
  .github/workflows/cypress.yaml
Labels: T-Task

#10176 Revert "Release Sign in with QR out of labs (#10066)"
  src/components/views/settings/devices/LoginWithQRSection.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/views/settings/devices/LoginWithQRSection-test.tsx
  test/components/views/settings/devices/__snapshots__/LoginWithQRSection-test.tsx.snap
  test/components/views/settings/tabs/user/SecurityUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Task

#10164 Try to resolve emails before creating a DM
  src/components/views/dialogs/InviteDialog.tsx
  src/utils/direct-messages.ts
  src/utils/threepids.ts
  test/test-utils/test-utils.ts
  test/utils/direct-messages-test.ts
  test/utils/threepids-test.ts
Labels: T-Defect

#10166 Convert remaining hook tests to RTL
  test/hooks/useLatestResult-test.tsx
  test/hooks/useProfileInfo-test.tsx
Labels: T-Task

#10178 Fix accidentally inverted condition for room ordering
  src/stores/room-list/algorithms/list-ordering/ImportanceAlgorithm.ts
Labels: T-Defect

#10171 Polls: fix broken test
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/messages/__snapshots__/MPollBody-test.tsx.snap
Labels: T-Task

#10182 Release Sign in with QR out of labs
  src/components/views/settings/devices/LoginWithQRSection.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/views/settings/devices/LoginWithQRSection-test.tsx
  test/components/views/settings/devices/__snapshots__/LoginWithQRSection-test.tsx.snap
  test/components/views/settings/tabs/user/SecurityUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Enhancement

#10177 Show a success dialog after setting up the key backup
  cypress/e2e/crypto/crypto.spec.ts
  cypress/e2e/crypto/decryption-failure.spec.ts
  res/css/_components.pcss
  res/css/compound/_Icon.pcss
  res/css/compound/_SuccessDialog.pcss
  res/css/views/dialogs/security/_CreateSecretStorageDialog.pcss
  res/img/element-icons/check.svg
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/views/dialogs/BaseDialog.tsx
  src/components/views/dialogs/InfoDialog.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#10135 Bump @types/katex to 0.16.0
  package.json
  yarn.lock
Labels: T-Task

#10136 Bump @types/node to 18.18.12
  yarn.lock
Labels: T-Task

#10174 Make workflows reusable for downstream testing
  .github/workflows/tests.yml
  scripts/ci/install-deps.sh
  scripts/ci/layered.sh
Labels: T-Task

#9878 Remove threads labs flag and the ability to disable threads
  cypress/e2e/polls/polls.spec.ts
  cypress/e2e/threads/threads.spec.ts
  src/DateUtils.ts
  src/MatrixClientPeg.ts
  src/Unread.ts
  src/components/structures/MessagePanel.tsx
  src/components/structures/RoomSearchView.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/right_panel/RoomHeaderButtons.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/SearchResultTile.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/components/views/rooms/wysiwyg_composer/utils/message.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/controllers/ThreadBetaController.tsx
  src/stores/TypingStore.ts
  src/stores/right-panel/RightPanelStore.ts
  src/stores/widgets/StopGapWidgetDriver.ts
  src/utils/Reply.ts
  src/utils/exportUtils/HtmlExport.tsx
  test/components/structures/MessagePanel-test.tsx
  test/components/structures/ThreadPanel-test.tsx
  test/components/structures/TimelinePanel-test.tsx
  test/components/views/messages/MessageActionBar-test.tsx
  test/components/views/right_panel/RoomHeaderButtons-test.tsx
  test/components/views/rooms/EventTile-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/LabsUserSettingsTab-test.tsx.snap
  test/stores/widgets/StopGapWidgetDriver-test.ts
  test/test-utils/test-utils.ts
Labels: X-Release-Blocker, T-Enhancement

#10119 Poll history - ended polls list items
  res/css/_components.pcss
  res/css/components/views/dialogs/polls/_PollListItemEnded.pcss
  res/css/components/views/polls/_PollOption.pcss
  res/css/views/dialogs/polls/_PollHistoryList.pcss
  res/css/views/messages/_MPollBody.pcss
  src/components/views/dialogs/polls/PollHistoryDialog.tsx
  src/components/views/dialogs/polls/PollHistoryList.tsx
  src/components/views/dialogs/polls/PollListItem.tsx
  src/components/views/dialogs/polls/PollListItemEnded.tsx
  src/components/views/messages/MPollBody.tsx
  test/components/views/dialogs/polls/PollListItem-test.tsx
  test/components/views/dialogs/polls/PollListItemEnded-test.tsx
  test/components/views/dialogs/polls/__snapshots__/PollHistoryDialog-test.tsx.snap
  test/components/views/dialogs/polls/__snapshots__/PollListItemEnded-test.tsx.snap
  test/test-utils/poll.ts
Labels: T-Enhancement

#10181 Port location unit tests from enzyme to react-testing-library
  cypress/e2e/location/location.spec.ts
  src/components/views/location/EnableLiveShare.tsx
  src/components/views/location/LiveDurationDropdown.tsx
  src/components/views/location/LocationPicker.tsx
  src/components/views/location/MapError.tsx
  src/components/views/location/ShareDialogButtons.tsx
  test/components/views/location/LocationPicker-test.tsx
  test/components/views/location/LocationShareMenu-test.tsx
  test/components/views/location/LocationViewDialog-test.tsx
  test/components/views/location/SmartMarker-test.tsx
  test/components/views/location/__snapshots__/LocationPicker-test.tsx.snap
  test/components/views/location/__snapshots__/LocationShareMenu-test.tsx.snap
  test/components/views/location/__snapshots__/LocationViewDialog-test.tsx.snap
  test/components/views/location/__snapshots__/MapError-test.tsx.snap
  test/components/views/location/__snapshots__/SmartMarker-test.tsx.snap
  test/components/views/messages/__snapshots__/MBeaconBody-test.tsx.snap
Labels: T-Task

#10157 Poll history: fetch last 30 days of polls
  res/css/views/dialogs/polls/_PollHistoryList.pcss
  src/components/views/dialogs/polls/PollHistoryDialog.tsx
  src/components/views/dialogs/polls/PollHistoryList.tsx
  src/components/views/dialogs/polls/fetchPastPolls.ts
  src/components/views/dialogs/polls/usePollHistory.ts
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/polls/PollHistoryDialog-test.tsx
  test/components/views/dialogs/polls/__snapshots__/PollHistoryDialog-test.tsx.snap
Labels: T-Enhancement

#10194 port SpotlightDialog unit test to rtl
  test/components/views/dialogs/SpotlightDialog-test.tsx
Labels: T-Task

#10198 Allow disabling coverage for downstream testing
  .github/workflows/tests.yml
Labels: T-Task

#10069 Stop access token overflowing the box
  res/css/views/elements/_CopyableText.pcss
  res/css/views/settings/tabs/user/_HelpUserSettingsTab.pcss
Labels: Z-Community-PR, T-Defect

#10180 port BeaconViewDialog unit test to rtl
  src/components/views/beacon/BeaconViewDialog.tsx
  test/components/views/beacon/BeaconViewDialog-test.tsx
  test/components/views/beacon/__snapshots__/BeaconViewDialog-test.tsx.snap
Labels: T-Task

#10196 Filter NSFW content in room directory
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/hooks/usePublicRoomDirectory.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/views/dialogs/SpotlightDialog-test.tsx
Labels: T-Enhancement

#10190 Add link to next file in the export
  src/utils/exportUtils/HtmlExport.tsx
  test/utils/exportUtils/HTMLExport-test.ts
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
Labels: Z-Community-PR, T-Defect

#10202 Display "The sender has blocked you from receiving this message" error message instead of "Unable to decrypt message"
  src/components/views/messages/DecryptionFailureBody.tsx
  src/components/views/messages/MessageEvent.tsx
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
  test/components/views/messages/DecryptionFailureBody-test.tsx
  test/components/views/messages/__snapshots__/DecryptionFailureBody-test.tsx.snap
Labels: T-Enhancement

#10179 Polls: show warning about undecryptable relations
  src/components/views/messages/MPollBody.tsx
  src/i18n/strings/en_EN.json
  test/components/views/messages/MPollBody-test.tsx
Labels: T-Enhancement

#10203 Update usages of test utilities preferring RTL
  package.json
  src/components/views/room_settings/AliasSettings.tsx
  src/components/views/spaces/SpaceSettingsVisibilityTab.tsx
  test/TextForEvent-test.ts
  test/components/structures/MessagePanel-test.tsx
  test/components/structures/TabbedView-test.tsx
  test/components/structures/ThreadView-test.tsx
  test/components/views/beacon/BeaconListItem-test.tsx
  test/components/views/beacon/BeaconMarker-test.tsx
  test/components/views/beacon/DialogSidebar-test.tsx
  test/components/views/beacon/LeftPanelLiveShareWarning-test.tsx
  test/components/views/beacon/RoomCallBanner-test.tsx
  test/components/views/beacon/RoomLiveShareWarning-test.tsx
  test/components/views/dialogs/ForwardDialog-test.tsx
  test/components/views/elements/ExternalLink-test.tsx
  test/components/views/elements/TooltipTarget-test.tsx
  test/components/views/elements/__snapshots__/ExternalLink-test.tsx.snap
  test/components/views/location/LocationPicker-test.tsx
  test/components/views/location/LocationShareMenu-test.tsx
  test/components/views/location/Map-test.tsx
  test/components/views/messages/MKeyVerificationConclusion-test.tsx
  test/components/views/rooms/RoomListHeader-test.tsx
  test/components/views/settings/CryptographyPanel-test.tsx
  test/components/views/settings/DevicesPanel-test.tsx
  test/components/views/settings/Notifications-test.tsx
  test/components/views/settings/SettingsFieldset-test.tsx
  test/components/views/settings/__snapshots__/SettingsFieldset-test.tsx.snap
  test/components/views/settings/devices/CurrentDeviceSection-test.tsx
  test/components/views/settings/devices/SelectableDeviceTile-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/components/views/spaces/SpaceSettingsVisibilityTab-test.tsx
  test/components/views/spaces/__snapshots__/SpaceSettingsVisibilityTab-test.tsx.snap
  test/components/views/typography/Heading-test.tsx
  test/components/views/typography/__snapshots__/Heading-test.tsx.snap
  test/useTopic-test.tsx
  test/voice-broadcast/components/atoms/VoiceBroadcastHeader-test.tsx
  yarn.lock
Labels: T-Task

#10193 Ended poll tiles: add ended the poll message
  src/components/views/messages/MPollEndBody.tsx
  src/i18n/strings/en_EN.json
  test/components/views/messages/__snapshots__/MPollEndBody-test.tsx.snap
Labels: T-Defect

#10159 Make localization keys compatible with agglutinative and/or SOV type languages
  src/components/views/dialogs/devtools/RoomNotifications.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/devtools/__snapshots__/RoomNotifications-test.tsx.snap
Labels: Z-Community-PR, T-Defect

#10183 Prevent multiple Jitsi calls started at the same time
  src/components/structures/RoomView.tsx
  test/components/structures/RoomView-test.tsx
Labels: T-Defect

#10223 Fix calls showing as 'connecting' after hangup
  src/components/structures/LegacyCallEventGrouper.ts
Labels: T-Defect

#10207 Improve Percy stability by better scoping snapshots
  .github/workflows/cypress.yaml
  cypress/e2e/crypto/decryption-failure.spec.ts
  cypress/e2e/timeline/timeline.spec.ts
  cypress/support/percy.ts
Labels: T-Task, X-Needs-Percy

#10208 Do not prompt for a password when doing a „reset all“ after login
  src/components/structures/MatrixChat.tsx
  src/contexts/SDKContext.ts
  src/stores/AccountPasswordStore.ts
  src/stores/SetupEncryptionStore.ts
  test/stores/AccountPasswordStore-test.ts
  test/stores/SetupEncryptionStore-test.ts
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#10200 Update „new device“ toast texts and buttons
  src/components/views/settings/DevicesPanel.tsx
  src/components/views/settings/devices/DeviceMetaData.tsx
  src/components/views/settings/devices/DeviceTile.tsx
  src/i18n/strings/en_EN.json
  src/toasts/UnverifiedSessionToast.tsx
  src/utils/device/isDeviceVerified.ts
  test/test-utils/test-utils.ts
  test/toasts/UnverifiedSessionToast-test.tsx
  test/toasts/__snapshots__/UnverifiedSessionToast-test.tsx.snap
Labels: T-Enhancement, X-Needs-Percy

#10154 Support joining non-peekable rooms via the module API
  src/components/structures/RoomView.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  test/components/views/rooms/RoomPreviewBar-test.tsx
Labels: Z-Community-PR, T-Enhancement

#10220 Manually finalize Percy builds
  .editorconfig
  .github/workflows/cypress.yaml
Labels: T-Task

#10191 Refactor ExtraTile to use functional components
  src/components/views/rooms/ExtraTile.tsx
  src/components/views/rooms/RoomSublist.tsx
  test/components/views/rooms/ExtraTile-test.tsx
  test/components/views/rooms/__snapshots__/ExtraTile-test.tsx.snap
Labels: T-Task

#10121 Widget permissions customizations using module api
  cypress/e2e/widgets/stickers.spec.ts
  package.json
  src/components/views/context_menus/WidgetContextMenu.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/right_panel/WidgetCard.tsx
  src/stores/widgets/StopGapWidgetDriver.ts
  test/components/views/context_menus/WidgetContextMenu-test.tsx
  test/components/views/elements/AppTile-test.tsx
  test/stores/widgets/StopGapWidgetDriver-test.ts
  yarn.lock
Labels: Z-Community-PR, T-Enhancement

#10230 Allow percy branch protection when X-Needs-Percy is passed
  .github/workflows/cypress.yaml
Labels: T-Task

#10224 Say when a call was answered from a different device
  res/css/views/messages/_LegacyCallEvent.pcss
  src/components/structures/LegacyCallEventGrouper.ts
  src/components/views/messages/LegacyCallEvent.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#6048 Provide a more detailed error message than "No known servers"
  src/i18n/strings/en_EN.json
  src/stores/RoomViewStore.tsx
  test/stores/RoomViewStore-test.ts
  test/stores/__snapshots__/RoomViewStore-test.ts.snap
Labels: Z-Community-PR, T-Enhancement

#10240 Fix double translation issue (#10240
  cypress/e2e/crypto/decryption-failure.spec.ts
  src/AddThreepid.ts
  src/LegacyCallHandler.tsx
  src/async-components/views/dialogs/eventindex/ManageEventIndexDialog.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/structures/auth/Login.tsx
  src/components/views/auth/CaptchaForm.tsx
  src/components/views/dialogs/StorageEvictedDialog.tsx
  src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx
  src/components/views/location/LocationPicker.tsx
  src/components/views/rooms/NewRoomIntro.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/components/views/settings/EventIndexPanel.tsx
  src/components/views/settings/SecureBackupPanel.tsx
  src/components/views/settings/SetIdServer.tsx
  src/components/views/settings/account/EmailAddresses.tsx
  src/components/views/settings/discovery/EmailAddresses.tsx
  src/utils/leave-behaviour.ts
  src/utils/location/findMapStyleUrl.ts
  src/utils/location/map.ts
  test/components/views/elements/EventListSummary-test.tsx
Labels: T-Defect

#10239 Improve percy snapshot stability
  cypress/e2e/polls/polls.spec.ts
  cypress/e2e/timeline/timeline.spec.ts
  cypress/support/percy.ts
Labels: T-Task, X-Needs-Percy

#10231 Use the room avatar as a placeholder in calls
  src/components/views/voip/LegacyCallView.tsx
  src/components/views/voip/VideoFeed.tsx
  test/components/views/voip/VideoFeed-test.tsx
Labels: T-Defect

#10243 Add EventTileThreadToolbar tests
  test/components/views/rooms/EventTile/EventTileThreadToolbar-test.tsx
  test/components/views/rooms/EventTile/__snapshots__/EventTileThreadToolbar-test.tsx.snap
Labels: T-Task

#10212 Sort short/exact emoji matches before longer incomplete matches
  src/autocomplete/EmojiProvider.tsx
  src/components/views/emojipicker/EmojiPicker.tsx
  test/autocomplete/EmojiProvider-test.ts
  test/components/views/emojipicker/EmojiPicker-test.tsx
Labels: Z-Community-PR, T-Enhancement

#10248 Remove tests of non-spec-compliant behaviour
  test/components/views/elements/ReplyChain-test.tsx
Labels: T-Task

#10235 Poll history: fetch more poll history
  res/css/views/dialogs/polls/_PollHistoryList.pcss
  src/components/views/dialogs/polls/PollHistoryDialog.tsx
  src/components/views/dialogs/polls/PollHistoryList.tsx
  src/components/views/dialogs/polls/fetchPastPolls.ts
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/polls/PollHistoryDialog-test.tsx
  test/components/views/dialogs/polls/__snapshots__/PollHistoryDialog-test.tsx.snap
Labels: T-Enhancement

#10249 Apply strictNullChecks to src/components/views/location/* (#10249
  src/components/structures/UserMenu.tsx
  src/components/views/avatars/BaseAvatar.tsx
  src/components/views/location/LocationButton.tsx
  src/components/views/location/LocationPicker.tsx
  src/components/views/location/LocationShareMenu.tsx
  src/components/views/location/LocationViewDialog.tsx
  src/components/views/location/Map.tsx
  src/components/views/location/ShareType.tsx
  src/components/views/location/SmartMarker.tsx
  src/components/views/location/shareLocation.ts
  test/components/views/location/LocationShareMenu-test.tsx
  test/components/views/spaces/SpacePanel-test.tsx
Labels: T-Task

#10247 Update tests to prefer RTL over Enzyme (#10247
  src/components/views/audio_messages/PlayPauseButton.tsx
  test/components/views/audio_messages/RecordingPlayback-test.tsx
  test/components/views/auth/RegistrationToken-test.tsx
  test/components/views/beacon/BeaconViewDialog-test.tsx
  test/components/views/dialogs/ExportDialog-test.tsx
  test/components/views/elements/EventListSummary-test.tsx
  test/components/views/elements/PollCreateDialog-test.tsx
  test/components/views/elements/__snapshots__/PollCreateDialog-test.tsx.snap
  test/components/views/messages/MBeaconBody-test.tsx
  test/components/views/messages/MLocationBody-test.tsx
  test/components/views/messages/__snapshots__/MBeaconBody-test.tsx.snap
  test/components/views/rooms/MemberList-test.tsx
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/VoiceRecordComposerTile-test.tsx
  test/components/views/spaces/SpaceSettingsVisibilityTab-test.tsx
  test/test-utils/composer.ts
  test/test-utils/test-utils.ts
  test/test-utils/utilities.ts
  test/utils/DMRoomMap-test.ts
  test/utils/export-test.tsx
Labels: T-Task

#10246 Fix block code styling in rich text editor
  res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
Labels: T-Enhancement

#10254 Apply strictNullChecks to src/components/views/avatars/*
  src/Avatar.ts
  src/components/views/avatars/BaseAvatar.tsx
  src/components/views/avatars/DecoratedRoomAvatar.tsx
  src/components/views/avatars/MemberAvatar.tsx
  src/components/views/avatars/RoomAvatar.tsx
  src/components/views/avatars/WidgetAvatar.tsx
  src/customisations/UserIdentifier.ts
Labels: T-Task

#10251 Apply strictNullChecks to src/async-components/* (#10251
  src/async-components/views/dialogs/eventindex/ManageEventIndexDialog.tsx
  src/async-components/views/dialogs/security/CreateKeyBackupDialog.tsx
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/async-components/views/dialogs/security/ExportE2eKeysDialog.tsx
  src/async-components/views/dialogs/security/ImportE2eKeysDialog.tsx
  src/async-components/views/dialogs/security/RecoveryMethodRemovedDialog.tsx
  src/utils/strings.ts
Labels: T-Task
