Repository matrix-org/matrix-react-sdk, pull requests merged in 2023-12, with the labels that each got.

#11932 Stop displaying verification done messages in timeline
  src/components/views/messages/MKeyVerificationConclusion.tsx
  src/events/EventTileFactory.tsx
  src/i18n/strings/en_EN.json
  test/components/views/messages/MKeyVerificationConclusion-test.tsx
Labels: T-Defect

#11957 `shieldStatusForRoom`: guard against client shutdown
  src/utils/ShieldUtils.ts
Labels: T-Task

#11936 Disable sliding sync proxy check for native support mode
  src/components/views/dialogs/SlidingSyncOptionsDialog.tsx
Labels: T-Defect

#11981 Attempt to deflake a read-receipts test
  cypress/e2e/read-receipts/new-messages.spec.ts
Labels: T-Task

#11954 Migrate right-panel/* from Cypress to Playwright
  cypress/e2e/right-panel/file-panel.spec.ts
  cypress/e2e/right-panel/notification-panel.spec.ts
  cypress/e2e/right-panel/right-panel.spec.ts
  playwright/e2e/login/consent.spec.ts
  playwright/e2e/right-panel/file-panel.spec.ts
  playwright/e2e/right-panel/notification-panel.spec.ts
  playwright/e2e/right-panel/right-panel.spec.ts
  playwright/e2e/right-panel/utils.ts
  playwright/e2e/settings/appearance-user-settings-tab.spec.ts
  playwright/pages/ElementAppPage.ts
  playwright/pages/client.ts
  playwright/pages/labs.ts
  playwright/snapshots/right-panel/file-panel.spec.ts/empty-linux.png
  playwright/snapshots/right-panel/file-panel.spec.ts/file-tiles-list-linux.png
  playwright/snapshots/right-panel/notification-panel.spec.ts/empty-linux.png
  playwright/snapshots/right-panel/right-panel.spec.ts/with-name-and-address-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/Appearance-user-settings-tab-should-be-rendered-properly-1-darwin.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/Appearance-user-settings-tab-should-be-rendered-properly-1-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  res/css/views/avatars/_BaseAvatar.pcss
Labels: T-Task

#11980 Fix rejoin of knock rooms
  cypress/e2e/knock/knock-into-room.spec.ts
  src/components/structures/RoomView.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  test/components/views/rooms/RoomPreviewBar-test.tsx
  test/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
Labels: Z-Community-PR, T-Defect

#11983 Improve stability of Playwright screenshot tests
  playwright/e2e/editing/editing.spec.ts
  playwright/e2e/login/soft_logout.spec.ts
  playwright/e2e/register/email.spec.ts
  playwright/e2e/register/register.spec.ts
  playwright/e2e/right-panel/file-panel.spec.ts
  playwright/e2e/right-panel/notification-panel.spec.ts
  playwright/e2e/right-panel/right-panel.spec.ts
  playwright/e2e/settings/appearance-user-settings-tab.spec.ts
  playwright/e2e/settings/general-room-settings-tab.spec.ts
  playwright/e2e/settings/general-user-settings-tab.spec.ts
  playwright/e2e/settings/preferences-user-settings-tab.spec.ts
  playwright/e2e/settings/security-user-settings-tab.spec.ts
  playwright/e2e/user-onboarding/user-onboarding-new.spec.ts
  playwright/e2e/user-view/user-view.spec.ts
  playwright/element-web-test.ts
  playwright/snapshots/right-panel/file-panel.spec.ts/file-tiles-list-linux.png
  playwright/snapshots/right-panel/right-panel.spec.ts/with-name-and-address-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  playwright/snapshots/user-view/user-view.spec.ts/user-info-linux.png
  res/css/_common.pcss
  res/css/views/avatars/_BaseAvatar.pcss
  res/css/views/elements/_ReplyChain.pcss
  res/css/views/messages/_DisambiguatedProfile.pcss
Labels: T-Task

#11991 Double the number of Playwright runners
  .github/workflows/end-to-end-tests.yaml
Labels: T-Task

#11984 Migrate pills-click-in-app.spec.ts from Cypress to Playwright
  cypress/e2e/regression-tests/pills-click-in-app.spec.ts
  playwright/e2e/regression-tests/pills-click-in-app.spec.ts
Labels: T-Task

#11996 Hide react button in search results as it doesn't work properly
  src/components/views/messages/MessageActionBar.tsx
Labels: T-Defect

#11958 Fix up and enable a cypress test that uses key backup
  cypress/e2e/crypto/crypto.spec.ts
  cypress/e2e/crypto/utils.ts
Labels: T-Task

#11994 Migrate most read-receipts tests from Cypress to Playwright
  cypress/e2e/read-receipts/editing-messages.spec.ts
  cypress/e2e/read-receipts/high-level.spec.ts
  cypress/e2e/read-receipts/missing-referents.spec.ts
  cypress/e2e/read-receipts/new-messages.spec.ts
  cypress/e2e/read-receipts/reactions.spec.ts
  cypress/e2e/read-receipts/read-receipts-utils.ts
  cypress/e2e/read-receipts/redactions.spec.ts
  playwright/e2e/read-receipts/editing-messages.spec.ts
  playwright/e2e/read-receipts/high-level.spec.ts
  playwright/e2e/read-receipts/index.ts
  playwright/e2e/read-receipts/missing-referents.spec.ts
  playwright/e2e/read-receipts/new-messages.spec.ts
  playwright/e2e/read-receipts/reactions.spec.ts
  playwright/e2e/read-receipts/readme.md
  playwright/e2e/read-receipts/redactions.spec.ts
  playwright/pages/client.ts
Labels: T-Task

#11998 Re-enable previously-flaky cypress test
  cypress/e2e/crypto/verification.spec.ts
Labels: T-Task

#11995 Migrate read-receipts.spec.ts from Cypress to Playwright
  cypress/e2e/read-receipts/read-receipts.spec.ts
  cypress/support/client.ts
  playwright/e2e/read-receipts/read-receipts.spec.ts
  playwright/pages/client.ts
Labels: T-Task

#11997 Migrate room-directory.spec.ts from Cypress to Playwright
  cypress/e2e/room-directory/room-directory.spec.ts
  playwright/e2e/room-directory/room-directory.spec.ts
  playwright/pages/client.ts
  playwright/snapshots/room-directory/room-directory.spec.ts/filtered-no-results-linux.png
  playwright/snapshots/room-directory/room-directory.spec.ts/filtered-one-result-linux.png
Labels: T-Task

#12000 Playwright: enable skipped test in `editing-messages.spec.ts`
  playwright/e2e/read-receipts/editing-messages.spec.ts
Labels: T-Task

#11999 Improve usage of Playwright and documentation
  .github/workflows/end-to-end-tests.yaml
  docs/cypress.md
  docs/playwright.md
  package.json
  playwright/README.md
Labels: T-Task

#12003 Keep more recent rageshake logs
  src/rageshake/rageshake.ts
Labels: T-Enhancement

#12006 Move two runners from Cypress to Playwright to rebalance runtime
  .github/workflows/cypress.yaml
  .github/workflows/end-to-end-tests.yaml
Labels: T-Task

#11990 Migrate invite-dialog.spec.ts from Cypress to Playwright
  cypress/e2e/invite/invite-dialog.spec.ts
  playwright/e2e/invite/invite-dialog.spec.ts
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-dm-with-user-pill-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-dm-without-user-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-room-with-user-pill-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-room-without-user-linux.png
Labels: T-Task

#12005 Set up key backup using non-deprecated APIs
  playwright/e2e/crypto/backups.spec.ts
  playwright/element-web-test.ts
  playwright/pages/ElementAppPage.ts
  src/SecurityManager.ts
  src/async-components/views/dialogs/security/CreateKeyBackupDialog.tsx
  test/SecurityManager-test.ts
  test/components/views/dialogs/security/CreateKeyBackupDialog-test.tsx
  test/components/views/dialogs/security/__snapshots__/CreateKeyBackupDialog-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Defect

#12001 Playwright: Enable more tests in `editing-messages.spec.ts`
  playwright/e2e/read-receipts/editing-messages.spec.ts
Labels: T-Task

#12009 Improve stability of Playwright screenshots
  playwright/e2e/invite/invite-dialog.spec.ts
  playwright/e2e/right-panel/file-panel.spec.ts
  playwright/e2e/settings/general-user-settings-tab.spec.ts
  playwright/element-web-test.ts
  playwright/pages/bot.ts
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-dm-with-user-pill-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-dm-without-user-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-room-with-user-pill-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-room-without-user-linux.png
  playwright/snapshots/right-panel/file-panel.spec.ts/file-tiles-list-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-linux.png
Labels: T-Task

#12010 Fix playwright result reporting for js-sdk upstream tests
  .github/workflows/end-to-end-tests.yaml
Labels: T-Task

#12012 Playwright: Fix `assertUnreadLessThan` and `assertUnreadGreaterThan`
  playwright/e2e/read-receipts/index.ts
Labels: T-Task

#12002 Fix bug which prevented correct clean up of rageshake store
  src/rageshake/rageshake.ts
Labels: T-Defect

#12018 Fix cypress bot logger causing test to fail with `TypeError: logger.getChild is not a function`
  cypress/support/bot.ts
Labels: T-Task

#12013 Playwright: Enable & fix skipped tests in `new-messages.spec.ts`
  playwright/e2e/read-receipts/new-messages.spec.ts
Labels: T-Task

#12019 Playwright: Enable skipped tests in `reactions.spec.ts`
  playwright/e2e/read-receipts/reactions.spec.ts
Labels: T-Task

#12020 Fix the ordering in rageshakes
  src/rageshake/rageshake.ts
Labels: T-Task

#12017 Playwright: Enable skipped tests in `high-level.spec.ts`
  playwright/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#12021 Migrate remaining crypto tests from Cypress to Playwright
  cypress/e2e/crypto/crypto.spec.ts
  cypress/e2e/crypto/utils.ts
  cypress/e2e/crypto/verification.spec.ts
  cypress/support/client.ts
  playwright.config.ts
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/crypto/utils.ts
  playwright/e2e/crypto/verification.spec.ts
  playwright/element-web-test.ts
  playwright/pages/ElementAppPage.ts
  playwright/pages/bot.ts
  playwright/pages/client.ts
  playwright/snapshots/crypto/crypto.spec.ts/RoomSummaryCard-with-verified-e2ee-linux.png
Labels: T-Task

#12004 Migrate permalinks.spec.ts from Cypress to Playwright
  cypress/e2e/permalinks/permalinks.spec.ts
  playwright/e2e/permalinks/permalinks.spec.ts
  playwright/pages/client.ts
  playwright/plugins/homeserver/synapse/templates/default/homeserver.yaml
  playwright/snapshots/permalinks/permalinks.spec.ts/permalink-rendering-linux.png
Labels: T-Task

#12022 Migrate presence.spec.ts from Cypress to Playwright
  cypress/e2e/presence/presence.spec.ts
  playwright/e2e/presence/presence.spec.ts
Labels: T-Task

#12026 Playwright: Fix more tests in `redactions.spec.ts`
  playwright/e2e/read-receipts/redactions.spec.ts
Labels: T-Task

#12029 Playwright: Remove skipped for rust crypto in `high-level.spec.ts`
  playwright/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#12030 Migrate knock/* from Cypress to Playwright
  cypress/e2e/knock/create-knock-room.spec.ts
  cypress/e2e/knock/knock-into-room.spec.ts
  cypress/e2e/knock/manage-knocks.spec.ts
  playwright/e2e/knock/create-knock-room.spec.ts
  playwright/e2e/knock/knock-into-room.spec.ts
  playwright/e2e/knock/manage-knocks.spec.ts
  playwright/e2e/utils.ts
  playwright/element-web-test.ts
  playwright/pages/ElementAppPage.ts
  playwright/pages/Spotlight.ts
  playwright/pages/client.ts
Labels: T-Task

#12034 Move 2 runners from Cypress to Playwright
  .github/workflows/cypress.yaml
  .github/workflows/end-to-end-tests.yaml
Labels: T-Task

#12032 Migrate widgets/* from Cypress to Playwright
  cypress/e2e/integration-manager/get-openid-token.spec.ts
  cypress/e2e/integration-manager/kick.spec.ts
  cypress/e2e/integration-manager/read_events.spec.ts
  cypress/e2e/integration-manager/send_event.spec.ts
  cypress/e2e/widgets/events.spec.ts
  cypress/e2e/widgets/layout.spec.ts
  cypress/e2e/widgets/widget-pip-close.spec.ts
  playwright/e2e/integration-manager/get-openid-token.spec.ts
  playwright/e2e/integration-manager/kick.spec.ts
  playwright/e2e/integration-manager/read_events.spec.ts
  playwright/e2e/integration-manager/send_event.spec.ts
  playwright/e2e/integration-manager/utils.ts
  playwright/e2e/widgets/events.spec.ts
  playwright/e2e/widgets/layout.spec.ts
  playwright/e2e/widgets/stickers.spec.ts
  playwright/e2e/widgets/widget-pip-close.spec.ts
  playwright/global.d.ts
  playwright/pages/client.ts
  playwright/plugins/webserver/index.ts
  playwright/snapshots/widgets/layout.spec.ts/apps-drawer-linux.png
Labels: T-Task

#12025 Migrate timeline.spec.ts from Cypress to Playwright
  cypress/e2e/timeline/timeline.spec.ts
  cypress/fixtures/element.png
  playwright.config.ts
  playwright/e2e/timeline/timeline.spec.ts
  playwright/element-web-test.ts
  playwright/pages/ElementAppPage.ts
  playwright/pages/client.ts
  playwright/snapshots/timeline/timeline.spec.ts/collapsed-gels-and-messages-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/collapsed-gels-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/configured-room-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-line-inline-start-margin-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tile-reply-chains-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tile-reply-chains-compact-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tile-reply-chains-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tile-reply-chains-irc-modern-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-compact-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-and-messages-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-emote-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-redaction-placeholder-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/hidden-event-line-padding-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/hidden-event-line-zero-padding-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/highlighted-search-results-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/hovered-hidden-event-line-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/long-strings-with-reply-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/long-strings-with-reply-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/long-strings-with-reply-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/search-bar-on-timeline-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/search-results-with-TextualEvent-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/url-preview-linux.png
Labels: T-Task

#12016 Fix position of thumbnail in room timeline
  res/css/views/messages/_RoomAvatarEvent.pcss
Labels: Z-Community-PR, T-Defect, X-Needs-Percy

#12027 Attach synapse logs to failed Playwright test runs
  playwright/element-web-test.ts
  playwright/plugins/homeserver/dendrite/index.ts
  playwright/plugins/homeserver/index.ts
  playwright/plugins/homeserver/synapse/index.ts
Labels: T-Task

#12053 Prevent Cypress typechecking react-sdk components without strict mode
  cypress/global.d.ts
  cypress/support/settings.ts
Labels: T-Task

#12028 Log unhandled promise rejections in the rageshake
  src/rageshake/rageshake.ts
Labels: T-Task

#12051 Retry jest tests to avoid flakes slowing down PRs
  test/setupTests.ts
Labels: T-Task

#12060 Fix playwright screenshot update command on linux
  package.json
  playwright/plugins/homeserver/synapse/index.ts
  yarn.lock
Labels: T-Task

#12059 Element-R: fix repeated requests to enter 4S key during cross-signing reset
  playwright/e2e/crypto/crypto.spec.ts
  src/SecurityManager.ts
  src/components/views/settings/CrossSigningPanel.tsx
  test/components/views/settings/CrossSigningPanel-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SecurityUserSettingsTab-test.tsx.snap
Labels: T-Defect

#11989 Playwright: Convert sliding-sync test to playwright
  cypress/e2e/sliding-sync/sliding-sync.spec.ts
  cypress/plugins/index.ts
  cypress/plugins/sliding-sync/index.ts
  cypress/support/e2e.ts
  cypress/support/proxy.ts
  playwright/e2e/right-panel/notification-panel.spec.ts
  playwright/e2e/room/room-header.spec.ts
  playwright/e2e/sliding-sync/sliding-sync.spec.ts
  playwright/element-web-test.ts
  playwright/pages/ElementAppPage.ts
  playwright/pages/client.ts
  playwright/pages/labs.ts
  playwright/plugins/homeserver/dendrite/index.ts
  playwright/plugins/homeserver/index.ts
  playwright/plugins/homeserver/synapse/index.ts
  playwright/plugins/sliding-sync-proxy/index.ts
Labels: T-Task

#12033 Convert spotlight tests to playwright
  cypress/e2e/spotlight/spotlight.spec.ts
  playwright/e2e/spotlight/spotlight.spec.ts
  playwright/pages/Spotlight.ts
Labels: T-Task

#12070 Fix threaded reply playwright tests
  playwright/e2e/read-receipts/index.ts
  playwright/e2e/read-receipts/redactions.spec.ts
Labels: T-Defect

#11988 Playwright: Convert lazy-loading test to playwright
  cypress/e2e/lazy-loading/lazy-loading.spec.ts
  cypress/support/e2e.ts
  cypress/support/network.ts
  cypress/support/timeline.ts
  playwright/e2e/lazy-loading/lazy-loading.spec.ts
  playwright/e2e/sliding-sync/sliding-sync.spec.ts
  playwright/e2e/timeline/timeline.spec.ts
  playwright/pages/ElementAppPage.ts
  playwright/pages/client.ts
  playwright/pages/network.ts
  playwright/pages/timeline.ts
Labels: T-Task

#12067 Playwright: Fix thread root skipped tests
  playwright/e2e/read-receipts/index.ts
  playwright/e2e/read-receipts/redactions.spec.ts
Labels: T-Task

#12055 Fix timeline position when moving to a room and coming back
  playwright/e2e/room/room.spec.ts
  src/components/structures/RoomView.tsx
  src/dispatcher/actions.ts
  src/stores/RoomViewStore.tsx
  test/components/structures/RoomView-test.tsx
  test/stores/RoomViewStore-test.ts
Labels: T-Defect

#12063 Use forwardRef in Avatar components to allow use with Compound Tooltips
  src/components/views/avatars/BaseAvatar.tsx
  src/components/views/avatars/MemberAvatar.tsx
  src/components/views/rooms/ReadReceiptMarker.tsx
Labels: T-Task

#12052 Use Compound tooltips instead of homegrown in TextWithTooltip & InfoTooltip
  res/css/_common.pcss
  src/components/views/avatars/DecoratedRoomAvatar.tsx
  src/components/views/dialogs/ServerPickerDialog.tsx
  src/components/views/elements/AppPermission.tsx
  src/components/views/elements/InfoTooltip.tsx
  src/components/views/elements/ServerPicker.tsx
  src/components/views/elements/TextWithTooltip.tsx
  src/components/views/rooms/RoomList.tsx
  src/toasts/IncomingCallToast.tsx
  test/components/structures/__snapshots__/SpaceHierarchy-test.tsx.snap
  test/components/views/avatars/DecoratedRoomAvatar-test.tsx
  test/components/views/avatars/__snapshots__/DecoratedRoomAvatar-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ServerPickerDialog-test.tsx.snap
  test/components/views/elements/InfoTooltip-test.tsx
  test/components/views/elements/__snapshots__/InfoTooltip-test.tsx.snap
Labels: T-Enhancement

#12072 Prepare for switching AccessibleButton and derivatives to forwardRef
  src/components/structures/InteractiveAuth.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/dialogs/AddExistingToSpaceDialog.tsx
  src/components/views/dialogs/DeactivateAccountDialog.tsx
  src/components/views/dialogs/InteractiveAuthDialog.tsx
  src/components/views/dialogs/ModalWidgetDialog.tsx
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/elements/AccessibleTooltipButton.tsx
  src/components/views/messages/CallEvent.tsx
  src/components/views/rooms/ReadReceiptGroup.tsx
  src/components/views/rooms/ReadReceiptMarker.tsx
  src/components/views/settings/ChangePassword.tsx
Labels: T-Task

#12056 Update element call embedding UI
  res/css/views/rooms/_AppsDrawer.pcss
  res/css/views/voip/_CallView.pcss
  src/components/views/elements/AppTile.tsx
Labels: T-Enhancement

#12075 Improve AccessibleButton & related types
  src/@types/react.d.ts
  src/accessibility/context_menu/ContextMenuButton.tsx
  src/accessibility/context_menu/ContextMenuTooltipButton.tsx
  src/accessibility/roving/RovingAccessibleButton.tsx
  src/accessibility/roving/RovingAccessibleTooltipButton.tsx
  src/components/views/audio_messages/PlayPauseButton.tsx
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/elements/AccessibleTooltipButton.tsx
  src/components/views/elements/LearnMore.tsx
  src/components/views/messages/CallEvent.tsx
  src/components/views/rooms/ExtraTile.tsx
  src/components/views/rooms/wysiwyg_composer/components/WysiwygAutocomplete.tsx
  src/components/views/settings/devices/DeviceExpandDetailsButton.tsx
  src/components/views/settings/devices/DeviceSecurityLearnMore.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  src/components/views/voip/LegacyCallView/LegacyCallViewButtons.tsx
  src/contexts/MatrixClientContext.tsx
Labels: T-Task

#12064 Iterate landmarks around the app in order to improve a11y
  playwright/e2e/user-view/user-view.spec.ts
  playwright/pages/settings.ts
  playwright/snapshots/register/email.spec.ts/registration-check-your-email-linux.png
  playwright/snapshots/register/register.spec.ts/email-prompt-linux.png
  playwright/snapshots/register/register.spec.ts/registration-linux.png
  playwright/snapshots/register/register.spec.ts/terms-prompt-linux.png
  playwright/snapshots/register/register.spec.ts/use-case-selection-linux.png
  src/components/structures/LeftPanel.tsx
  src/components/structures/LoggedInView.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/views/emojipicker/EmojiPicker.tsx
  src/components/views/rooms/AppsDrawer.tsx
  src/components/views/rooms/AuxPanel.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomListHeader.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/components/views/voip/CallView.tsx
  src/i18n/strings/en_EN.json
  src/utils/exportUtils/HtmlExport.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
Labels: T-Enhancement

#12054 Switch AccessibleButton and derivatives to using `forwardRef`
  src/accessibility/context_menu/ContextMenuButton.tsx
  src/accessibility/context_menu/ContextMenuTooltipButton.tsx
  src/accessibility/roving/RovingAccessibleButton.tsx
  src/accessibility/roving/RovingAccessibleTooltipButton.tsx
  src/components/structures/GenericDropdownMenu.tsx
  src/components/structures/SpaceHierarchy.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/structures/UserMenu.tsx
  src/components/views/audio_messages/PlayPauseButton.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/context_menus/KebabContextMenu.tsx
  src/components/views/context_menus/ThreadListContextMenu.tsx
  src/components/views/dialogs/spotlight/Option.tsx
  src/components/views/dialogs/spotlight/TooltipOption.tsx
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/elements/AccessibleTooltipButton.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/elements/Dropdown.tsx
  src/components/views/elements/ImageView.tsx
  src/components/views/elements/PollCreateDialog.tsx
  src/components/views/messages/CallEvent.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/messages/ReactionsRow.tsx
  src/components/views/right_panel/WidgetCard.tsx
  src/components/views/rooms/CollapsibleButton.tsx
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/components/views/rooms/ReadReceiptGroup.tsx
  src/components/views/rooms/RoomBreadcrumbs.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomListHeader.tsx
  src/components/views/rooms/RoomSublist.tsx
  src/components/views/rooms/RoomTile.tsx
  src/components/views/spaces/QuickSettingsButton.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  src/components/views/voip/CallView.tsx
  src/components/views/voip/LegacyCallView/LegacyCallViewButtons.tsx
Labels: T-Task

#12076 Workaround Rust Crypto key upload race condition for Playwright tests
  playwright/pages/bot.ts
Labels: T-Task

#12079 Adjust tooltip side for DecoratedRoomAvatar to not obscure room name
  src/components/views/avatars/DecoratedRoomAvatar.tsx
Labels: T-Enhancement

#12080 Switch Pill & E2EIcon to using Compound Tooltips
  src/components/views/elements/Pill.tsx
  src/components/views/rooms/E2EIcon.tsx
  src/components/views/rooms/LegacyRoomHeader.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/elements/Pill-test.tsx
  test/components/views/elements/__snapshots__/Pill-test.tsx.snap
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/components/views/rooms/MemberTile-test.tsx
  test/components/views/rooms/__snapshots__/MemberTile-test.tsx.snap
Labels: T-Task, T-Enhancement

#12083 Playwright: Enable `redactions.spec.ts` > `A thread with a redacted unread is still read after restart`
  playwright/e2e/read-receipts/redactions.spec.ts
Labels: T-Task

#12087 Allow element-web hash to be specified when calling playwright tests workflow
  .github/workflows/element-web.yaml
  scripts/ci/layered.sh
Labels: T-Task

#12088 Playwright: Add tests around room list order in case of unread
  playwright/e2e/read-receipts/high-level.spec.ts
  playwright/e2e/read-receipts/index.ts
Labels: T-Task
