Repository matrix-org/matrix-react-sdk, pull requests merged in 2023-08, with the labels that each got.

#11345 Add feature flag 'feature_new_room_decoration_ui' and segrate legacy UI component
  cypress/e2e/create-room/create-room.spec.ts
  cypress/e2e/invite/invite-dialog.spec.ts
  cypress/e2e/lazy-loading/lazy-loading.spec.ts
  cypress/e2e/one-to-one-chat/one-to-one-chat.spec.ts
  cypress/e2e/room/room-header.spec.ts
  cypress/e2e/spotlight/spotlight.spec.ts
  cypress/e2e/threads/threads.spec.ts
  cypress/e2e/timeline/timeline.spec.ts
  res/css/_components.pcss
  res/css/structures/_MainSplit.pcss
  res/css/structures/_RoomView.pcss
  res/css/views/rooms/_LegacyRoomHeader.pcss
  res/css/views/rooms/_RoomHeader.pcss
  src/components/structures/RoomView.tsx
  src/components/structures/WaitingForThirdPartyRoomView.tsx
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/right_panel/HeaderButton.tsx
  src/components/views/right_panel/LegacyRoomHeaderButtons.tsx
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/utils/exportUtils/HtmlExport.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/right_panel/LegacyRoomHeaderButtons-test.tsx
  test/components/views/right_panel/__snapshots__/LegacyRoomHeaderButtons-test.tsx.snap
  test/components/views/rooms/LegacyRoomHeader-test.tsx
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
Labels: T-Task

#11292 ElementR: Provide `userId` parameter to `findVerificationRequestDMInProgress`
  src/verification.ts
Labels: T-Task

#11344 Make keyboard handling in and out of autocomplete completions consistent
  src/components/views/rooms/BasicMessageComposer.tsx
  test/components/views/rooms/BasicMessageComposer-test.tsx
Labels: T-Defect

#11313 Adjust typography in key part of the app
  res/css/components/views/settings/devices/_DeviceDetails.pcss
  res/css/components/views/settings/devices/_DeviceTile.pcss
  res/css/views/elements/_Dropdown.pcss
  res/css/views/right_panel/_BaseCard.pcss
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/_ThreadSummary.pcss
Labels: T-Task

#11346 Create useRoomName hook
  res/css/views/rooms/_RoomHeader.pcss
  src/components/structures/RoomView.tsx
  src/components/views/elements/RoomName.tsx
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/hooks/useRoomName.ts
  src/i18n/strings/en_EN.json
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
Labels: T-Task

#11347 Fix joining a suggested room switching space away
  src/stores/spaces/SpaceStore.ts
Labels: T-Defect

#11337 Fix clicking on home all rooms space notification not working
  src/stores/spaces/SpaceStore.ts
  test/stores/SpaceStore-test.ts
Labels: T-Defect

#11352 Add room topic and animation
  res/css/views/rooms/_RoomHeader.pcss
  src/components/views/rooms/RoomHeader.tsx
  src/hooks/room/useTopic.ts
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
Labels: T-Task

#11354 Integrate @vector-im/compound-web
  package.json
  res/css/_common.pcss
  res/css/views/rooms/_RoomHeader.pcss
  src/components/views/rooms/RoomHeader.tsx
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
  yarn.lock
Labels: T-Task

#11338 Re-add typecheck without yarn link
  .github/workflows/static_analysis.yaml
Labels: T-Task

#11355 Make room model mandatory on the RoomHeader
  src/components/structures/RoomView.tsx
  src/components/structures/WaitingForThirdPartyRoomView.tsx
  src/components/views/rooms/RoomHeader.tsx
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
Labels: T-Task

#11357 Upgrade compound-web@0.2.3
  package.json
  yarn.lock
Labels: T-Task

#11358 Fix AppTile context menu not always showing up when it has options
  src/components/views/elements/AppTile.tsx
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
Labels: T-Defect

#11321 Clear requiresClient and show pop-out if widget-api fails to ready
  package.json
  src/components/views/elements/AppTile.tsx
  src/stores/widgets/StopGapWidget.ts
  yarn.lock
Labels: T-Enhancement

#11360 Switch to importing matrix-js-sdk from its main export
  .eslintrc.js
  cypress/e2e/composer/composer.spec.ts
  cypress/e2e/editing/editing.spec.ts
  cypress/e2e/invite/invite-dialog.spec.ts
  cypress/e2e/read-receipts/read-receipts.spec.ts
  cypress/e2e/spaces/spaces.spec.ts
  cypress/e2e/timeline/timeline.spec.ts
  cypress/support/axe.ts
  cypress/support/client.ts
  package.json
  src/AddThreepid.ts
  src/Modal.tsx
  src/components/structures/RoomSearchView.tsx
  src/components/structures/WaitingForThirdPartyRoomView.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/components/views/voip/DialPadModal.tsx
  src/events/RelationsHelper.ts
  src/hooks/useCall.ts
  src/hooks/useEventEmitter.ts
  src/models/Call.ts
  src/modules/ProxiedModuleApi.ts
  src/stores/OwnBeaconStore.ts
  src/stores/notifications/NotificationState.ts
  src/stores/widgets/StopGapWidget.ts
  src/utils/oidc/authorize.ts
  src/voice-broadcast/audio/VoiceBroadcastRecorder.ts
  src/voice-broadcast/models/VoiceBroadcastPlayback.ts
  src/voice-broadcast/models/VoiceBroadcastPreRecording.ts
  src/voice-broadcast/models/VoiceBroadcastRecording.ts
  src/voice-broadcast/stores/VoiceBroadcastPlaybacksStore.ts
  src/voice-broadcast/stores/VoiceBroadcastPreRecordingStore.ts
  src/voice-broadcast/stores/VoiceBroadcastRecordingsStore.ts
  test/components/views/dialogs/IncomingSasDialog-test.tsx
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/right_panel/VerificationPanel-test.tsx
  test/components/views/rooms/EventTile/EventTileThreadToolbar-test.tsx
  test/components/views/rooms/LegacyRoomHeader-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/components/views/spaces/SpaceSettingsVisibilityTab-test.tsx
  test/components/views/toasts/VerificationRequestToast-test.tsx
  test/hooks/useUnreadNotifications-test.ts
  test/models/Call-test.ts
  test/stores/notifications/RoomNotificationState-test.ts
  test/stores/room-list/SpaceWatcher-test.ts
Labels: T-Task

#9866 Add notes to PR template to make it easier to remeber to set type of PR.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: T-Task

#9017 Support adding space-restricted joins on rooms not members of those spaces
  src/components/views/dialogs/ManageRestrictedJoinRuleDialog.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/ManageRestrictedJoinRuleDialog-test.tsx
  test/components/views/dialogs/__snapshots__/ManageRestrictedJoinRuleDialog-test.tsx.snap
Labels: T-Enhancement

#11304 Search for users on paste
  src/components/views/dialogs/InviteDialog.tsx
  test/components/views/dialogs/InviteDialog-test.tsx
Labels: Z-Community-PR, T-Defect

#11372 Make a11y related lint rules more strict
  .eslintrc.js
  cypress/e2e/register/register.spec.ts
  cypress/support/axe.ts
Labels: T-Task

#11359 Remove feature_right_panel_default_open
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/right-panel/RightPanelStore.ts
Labels: T-Task

#11367 Fix create subspace dialog not working for public space creation
  src/components/views/dialogs/CreateSubspaceDialog.tsx
Labels: T-Defect

#11371 Fix some missing 1-count pluralisations around event list summaries
  src/i18n/strings/en_EN.json
Labels: T-Defect

#11349 Mark more logs as debug to tidy the console
  src/Presence.ts
  src/components/structures/MatrixChat.tsx
  src/components/structures/TimelinePanel.tsx
Labels: T-Task

#10696 Fix "Export chat" not respecting configured time format in plain text mode
  src/utils/exportUtils/PlainTextExport.ts
  test/utils/exportUtils/PlainTextExport-test.ts
Labels: Z-Community-PR, T-Defect

#11368 Switch to importing more js-sdk models from the main export
  .eslintrc.js
  src/MatrixClientPeg.ts
  src/SlashCommands.tsx
  src/autocomplete/UserProvider.tsx
  src/components/structures/FilePanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/avatars/DecoratedRoomAvatar.tsx
  src/components/views/dialogs/BulkRedactDialog.tsx
  src/components/views/dialogs/ManualDeviceKeyVerificationDialog.tsx
  src/components/views/dialogs/ShareDialog.tsx
  src/components/views/dialogs/UntrustedDeviceDialog.tsx
  src/components/views/dialogs/VerificationRequestDialog.tsx
  src/components/views/messages/DateSeparator.tsx
  src/components/views/right_panel/EncryptionInfo.tsx
  src/components/views/right_panel/EncryptionPanel.tsx
  src/components/views/right_panel/TimelineCard.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/right_panel/VerificationPanel.tsx
  src/components/views/rooms/HistoryTile.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/rooms/NewRoomIntro.tsx
  src/dispatcher/payloads/ViewStartChatOrReusePayload.ts
  src/dispatcher/payloads/ViewUserPayload.ts
  src/indexing/EventIndex.ts
  src/stores/OwnProfileStore.ts
  src/stores/SetupEncryptionStore.ts
  src/stores/right-panel/RightPanelStoreIPanelState.ts
  src/utils/exportUtils/Exporter.ts
  src/utils/leave-behaviour.ts
  src/verification.ts
  test/DeviceListener-test.ts
  test/components/structures/TimelinePanel-test.tsx
  test/components/views/dialogs/ManualDeviceKeyVerificationDialog-test.tsx
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/right_panel/VerificationPanel-test.tsx
  test/components/views/rooms/MemberList-test.tsx
  test/components/views/rooms/NotificationBadge/UnreadNotificationBadge-test.tsx
  test/stores/SetupEncryptionStore-test.ts
Labels: T-Task

#11379 Change formatCount impl to use Intl.NumberFormat
  src/utils/FormattingUtils.ts
  test/utils/FormattingUtils-test.ts
Labels: T-Task

#11378 Show error when searching public rooms fails
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/hooks/usePublicRoomDirectory.ts
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/SpotlightDialog-test.tsx
Labels: T-Defect

#10362 Enable `jsx-a11y/click-events-have-key-events` eslint rule
  cypress/e2e/composer/composer.spec.ts
  res/css/views/rooms/_EventTile.pcss
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/elements/InviteReason.tsx
  src/components/views/elements/Spoiler.tsx
  src/components/views/spaces/SpaceBasicSettings.tsx
  test/components/structures/PictureInPictureDragger-test.tsx
  test/components/views/elements/Pill-test.tsx
  test/components/views/messages/TextualBody-test.tsx
Labels: T-Task

#11375 Improve randomString mock for better snapshots
  jest.config.ts
  test/components/structures/RoomView-test.tsx
  test/components/structures/SpaceHierarchy-test.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/structures/__snapshots__/SpaceHierarchy-test.tsx.snap
  test/components/views/beacon/BeaconListItem-test.tsx
  test/components/views/beacon/DialogSidebar-test.tsx
  test/components/views/beacon/ShareLatestLocation-test.tsx
  test/components/views/beacon/__snapshots__/BeaconListItem-test.tsx.snap
  test/components/views/beacon/__snapshots__/DialogSidebar-test.tsx.snap
  test/components/views/beacon/__snapshots__/ShareLatestLocation-test.tsx.snap
  test/components/views/dialogs/ManageRestrictedJoinRuleDialog-test.tsx
  test/components/views/dialogs/ServerPickerDialog-test.tsx
  test/components/views/dialogs/__snapshots__/ManageRestrictedJoinRuleDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ServerPickerDialog-test.tsx.snap
  test/components/views/elements/AppTile-test.tsx
  test/components/views/elements/LabelledCheckbox-test.tsx
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/components/views/elements/__snapshots__/LabelledCheckbox-test.tsx.snap
  test/components/views/location/LocationShareMenu-test.tsx
  test/components/views/location/__snapshots__/LocationShareMenu-test.tsx.snap
  test/components/views/messages/MLocationBody-test.tsx
  test/components/views/messages/__snapshots__/MLocationBody-test.tsx.snap
  test/components/views/polls/pollHistory/PollHistory-test.tsx
  test/components/views/polls/pollHistory/PollListItem-test.tsx
  test/components/views/polls/pollHistory/PollListItemEnded-test.tsx
  test/components/views/polls/pollHistory/__snapshots__/PollHistory-test.tsx.snap
  test/components/views/polls/pollHistory/__snapshots__/PollListItem-test.tsx.snap
  test/components/views/polls/pollHistory/__snapshots__/PollListItemEnded-test.tsx.snap
  test/components/views/right_panel/RoomSummaryCard-test.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/settings/FontScalingPanel-test.tsx
  test/components/views/settings/Notifications-test.tsx
  test/components/views/settings/ThemeChoicePanel-test.tsx
  test/components/views/settings/__snapshots__/FontScalingPanel-test.tsx.snap
  test/components/views/settings/devices/FilteredDeviceListHeader-test.tsx
  test/components/views/settings/devices/__snapshots__/FilteredDeviceListHeader-test.tsx.snap
  test/components/views/settings/notifications/Notifications2-test.tsx
  test/components/views/settings/notifications/__snapshots__/Notifications2-test.tsx.snap
  test/components/views/settings/tabs/user/AppearanceUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/components/views/settings/tabs/user/SidebarUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SidebarUserSettingsTab-test.tsx.snap
  test/components/views/spaces/SpaceSettingsVisibilityTab-test.tsx
  test/globalSetup.ts
  test/setupTests.ts
  test/utils/oidc/authorize-test.ts
Labels: T-Task

#11392 Fix useRoomMembers missing updates causing incorrect membership counts
  src/hooks/useRoomMembers.ts
  test/hooks/useRoomMembers-test.tsx
Labels: T-Defect

#11376 Switch to importing more things from the main js-sdk export
  .eslintrc.js
  src/LegacyCallHandler.tsx
  src/Searching.ts
  src/boundThreepids.ts
  src/components/structures/RoomView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/structures/auth/SoftLogout.tsx
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/dialogs/MessageEditHistoryDialog.tsx
  src/components/views/emojipicker/ReactionPicker.tsx
  src/components/views/location/shareLocation.ts
  src/components/views/messages/DateSeparator.tsx
  src/components/views/messages/MPollBody.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/messages/ReactionsRow.tsx
  src/components/views/polls/pollHistory/PollListItemEnded.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/PinnedEventTile.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/components/views/settings/Notifications.tsx
  src/components/views/settings/devices/DeviceDetails.tsx
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/dispatcher/payloads/JoinRoomErrorPayload.ts
  src/events/RelationsHelper.ts
  src/indexing/EventIndex.ts
  src/notifications/ContentRules.ts
  src/notifications/NotificationUtils.ts
  src/notifications/PushRuleVectorState.ts
  src/notifications/StandardActions.ts
  src/notifications/VectorPushRulesDefinitions.ts
  src/rageshake/submit-rageshake.ts
  src/settings/controllers/NotificationControllers.ts
  src/stores/RoomViewStore.tsx
  src/utils/DecryptFile.ts
  src/utils/ErrorUtils.tsx
  src/utils/IdentityServerUtils.ts
  src/utils/MultiInviter.ts
  src/utils/pushRules/monitorSyncedPushRules.ts
  test/RoomNotifs-test.ts
  test/components/structures/RoomSearchView-test.tsx
  test/components/structures/RoomStatusBar-test.tsx
  test/components/views/messages/DateSeparator-test.tsx
  test/components/views/messages/MBeaconBody-test.tsx
  test/components/views/messages/MPollBody-test.tsx
  test/components/views/settings/discovery/EmailAddresses-test.tsx
  test/test-utils/relations.ts
  test/utils/ErrorUtils-test.ts
  test/voice-broadcast/models/VoiceBroadcastRecording-test.ts
Labels: T-Task

#11377 Switch to importing more things from the main js-sdk export
  .eslintrc.js
  src/DeviceListener.ts
  src/IdentityAuthClient.tsx
  src/LegacyCallHandler.tsx
  src/Searching.ts
  src/Terms.ts
  src/components/structures/FilePanel.tsx
  src/components/structures/LoggedInView.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomSearchView.tsx
  src/components/structures/RoomStatusBar.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/dialogs/TermsDialog.tsx
  src/components/views/polls/pollHistory/fetchPastPolls.ts
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/components/views/voip/CallDuration.tsx
  src/events/EventTileFactory.tsx
  src/indexing/BaseEventIndexManager.ts
  src/indexing/EventIndex.ts
  src/models/Call.ts
  src/stores/AutoRageshakeStore.ts
  src/stores/CallStore.ts
  src/stores/ReadyWatchingStore.ts
  src/stores/notifications/RoomNotificationStateStore.ts
  src/utils/IdentityServerUtils.ts
  src/utils/connection.ts
  src/voice-broadcast/utils/VoiceBroadcastResumer.ts
  src/voice-broadcast/utils/checkVoiceBroadcastPreConditions.tsx
  test/Notifier-test.ts
  test/components/structures/MatrixChat-test.tsx
  test/components/structures/RoomSearchView-test.tsx
  test/components/views/messages/MLocationBody-test.tsx
  test/components/views/polls/pollHistory/PollHistory-test.tsx
  test/components/views/rooms/LegacyRoomHeader-test.tsx
  test/models/Call-test.ts
  test/stores/AutoRageshakeStore-test.ts
  test/stores/RoomNotificationStateStore-test.ts
  test/test-utils/call.ts
  test/test-utils/test-utils.ts
  test/utils/connection-test.ts
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip-test.tsx
  test/voice-broadcast/models/VoiceBroadcastRecording-test.ts
  test/voice-broadcast/utils/VoiceBroadcastResumer-test.ts
  test/voice-broadcast/utils/setUpVoiceBroadcastPreRecording-test.ts
  test/voice-broadcast/utils/startNewVoiceBroadcastRecording-test.ts
Labels: T-Task

#11301 Tests for read/unread status
  cypress/e2e/read-receipts/high-level.spec.ts
  cypress/support/views.ts
Labels: T-Task

#11374 Include non-matching DMs in Spotlight recent conversations when the DM's userId is part of the search API results
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/utils/SortMembers.ts
  test/components/views/dialogs/SpotlightDialog-test.tsx
Labels: Z-Community-PR, T-Defect

#11397 Avoid using state for immutable fields
  src/components/views/auth/CountryDropdown.tsx
Labels: T-Task

#11399 Stabilise Percy snapshot of the user view
  cypress/e2e/user-view/user-view.spec.ts
Labels: T-Task

#9819 Support Matrix 1.1 (drop legacy r0 versions)
  cypress/e2e/read-receipts/read-receipts.spec.ts
  cypress/e2e/timeline/timeline.spec.ts
  cypress/support/login.ts
  src/AddThreepid.ts
  src/Lifecycle.ts
  src/components/structures/auth/ForgotPassword.tsx
  src/components/views/settings/ChangePassword.tsx
  src/components/views/settings/account/PhoneNumbers.tsx
  src/components/views/settings/discovery/EmailAddresses.tsx
  src/components/views/settings/discovery/PhoneNumbers.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/utils/AutoDiscoveryUtils.tsx
  test/Lifecycle-test.ts
  test/components/structures/MatrixChat-test.tsx
  test/components/structures/auth/Login-test.tsx
  test/components/structures/auth/Registration-test.tsx
  test/components/views/dialogs/ServerPickerDialog-test.tsx
  test/components/views/messages/MImageBody-test.tsx
  test/components/views/messages/MVideoBody-test.tsx
  test/components/views/messages/__snapshots__/MImageBody-test.tsx.snap
  test/components/views/messages/__snapshots__/MVideoBody-test.tsx.snap
  test/components/views/settings/ChangePassword-test.tsx
  test/components/views/settings/__snapshots__/ChangePassword-test.tsx.snap
  test/components/views/settings/account/PhoneNumbers-test.tsx
  test/components/views/settings/account/__snapshots__/PhoneNumbers-test.tsx.snap
  test/components/views/settings/discovery/EmailAddresses-test.tsx
  test/components/views/settings/discovery/PhoneNumbers-test.tsx
  test/components/views/settings/discovery/__snapshots__/PhoneNumbers-test.tsx.snap
  test/test-utils/client.ts
  test/test-utils/test-utils.ts
  test/utils/AutoDiscoveryUtils-test.tsx
Labels: T-Enhancement

#11394 Switch to importing more things from the main js-sdk export
  .eslintrc.js
  src/ContentMessages.ts
  src/components/structures/FilePanel.tsx
  src/components/structures/RoomSearchView.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/structures/ThreadView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/dialogs/devtools/RoomNotifications.tsx
  src/components/views/location/shareLocation.ts
  src/components/views/right_panel/LegacyRoomHeaderButtons.tsx
  src/components/views/right_panel/TimelineCard.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/components/views/rooms/ThreadSummary.tsx
  src/components/views/rooms/wysiwyg_composer/utils/event.ts
  src/components/views/rooms/wysiwyg_composer/utils/message.ts
  src/indexing/EventIndex.ts
  src/stores/room-list/MessagePreviewStore.ts
  src/stores/widgets/StopGapWidgetDriver.ts
  src/utils/EventUtils.ts
  src/utils/Reply.ts
  src/utils/StorageManager.ts
  src/utils/createMatrixClient.ts
  test/components/structures/MessagePanel-test.tsx
  test/components/structures/ThreadPanel-test.tsx
  test/components/structures/ThreadView-test.tsx
  test/components/structures/TimelinePanel-test.tsx
  test/components/views/context_menus/MessageContextMenu-test.tsx
  test/components/views/messages/MessageActionBar-test.tsx
  test/components/views/rooms/MessageComposer-test.tsx
  test/components/views/rooms/RoomTile-test.tsx
  test/test-utils/threads.ts
  test/utils/EventUtils-test.ts
Labels: T-Task

#11391 correct home server URL
  src/components/views/dialogs/ServerPickerDialog.tsx
  test/components/views/dialogs/__snapshots__/ServerPickerDialog-test.tsx.snap
Labels: Z-Community-PR, T-Defect

#11401 Add a cypress test for SSO login
  cypress/e2e/login/login.spec.ts
  cypress/plugins/dendritedocker/index.ts
  cypress/plugins/index.ts
  cypress/plugins/oauth_server/README.md
  cypress/plugins/oauth_server/index.ts
  cypress/plugins/oauth_server/res/oauth/auth.html
  cypress/plugins/synapsedocker/index.ts
  cypress/plugins/synapsedocker/templates/default/homeserver.yaml
  cypress/support/homeserver.ts
  package.json
  yarn.lock
Labels: T-Task

#11403 Clean up the MatrixChat initSession code
  src/Lifecycle.ts
  src/components/structures/MatrixChat.tsx
  test/components/structures/MatrixChat-test.tsx
  test/components/structures/__snapshots__/MatrixChat-test.tsx.snap
Labels: T-Task

#11405 Remove dead & duplicated code
  src/AddThreepid.ts
  src/BasePlatform.ts
  src/IdentityAuthClient.tsx
  src/LegacyCallHandler.tsx
  src/PasswordReset.ts
  src/RoomNotifs.ts
  src/ScalarMessaging.ts
  src/components/views/dialogs/FeedbackDialog.tsx
  src/editor/model.ts
  src/indexing/BaseEventIndexManager.ts
  src/integrations/IntegrationManagers.ts
  src/mjolnir/BanList.ts
  src/models/Call.ts
  src/rageshake/submit-rageshake.ts
  src/sentry.ts
  src/stores/room-list/RoomListStore.ts
  src/stores/room-list/SlidingRoomListStore.ts
  src/stores/room-list/algorithms/Algorithm.ts
  src/stores/widgets/StopGapWidget.ts
  src/stores/widgets/StopGapWidgetDriver.ts
  src/utils/WidgetUtils.ts
  src/utils/permalinks/PermalinkConstructor.ts
  src/utils/permalinks/Permalinks.ts
  test/utils/SearchInput-test.ts
  test/utils/permalinks/Permalinks-test.ts
Labels: T-Task

#11408 Wire up more high level read receipt tests
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11398 Simplify registration with email validation
  cypress/e2e/register/email.spec.ts
  cypress/plugins/index.ts
  cypress/plugins/mailhog/index.ts
  cypress/plugins/synapsedocker/index.ts
  cypress/plugins/synapsedocker/templates/email/README.md
  cypress/plugins/synapsedocker/templates/email/homeserver.yaml
  cypress/plugins/synapsedocker/templates/email/log.config
  cypress/support/e2e.ts
  cypress/support/homeserver.ts
  cypress/support/mailhog.ts
  cypress/support/promise.ts
  package.json
  src/components/structures/MatrixChat.tsx
  src/components/structures/auth/Registration.tsx
  test/components/structures/MatrixChat-test.tsx
  test/components/structures/auth/Registration-test.tsx
  yarn.lock
Labels: T-Defect

#11406 Switch to importing most things from the main matrix-js-sdk export
  .eslintrc.js
  src/Lifecycle.ts
  src/Login.ts
  src/MatrixClientPeg.ts
  src/SlashCommands.tsx
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/structures/SpaceHierarchy.tsx
  src/components/structures/auth/Login.tsx
  src/components/structures/auth/Registration.tsx
  src/components/structures/auth/SoftLogout.tsx
  src/components/views/beacon/BeaconListItem.tsx
  src/components/views/beacon/BeaconMarker.tsx
  src/components/views/beacon/BeaconStatusTooltip.tsx
  src/components/views/beacon/DialogOwnBeaconStatus.tsx
  src/components/views/beacon/ShareLatestLocation.tsx
  src/components/views/beacon/displayStatus.ts
  src/components/views/dialogs/ForwardDialog.tsx
  src/components/views/dialogs/InteractiveAuthDialog.tsx
  src/components/views/dialogs/ServerPickerDialog.tsx
  src/components/views/dialogs/security/CreateCrossSigningDialog.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/elements/SSOButtons.tsx
  src/components/views/location/shareLocation.ts
  src/components/views/messages/MBeaconBody.tsx
  src/components/views/rooms/wysiwyg_composer/DynamicImportWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useEditing.ts
  src/components/views/spaces/SpaceCreateMenu.tsx
  src/dispatcher/payloads/JoinRoomPayload.ts
  src/dispatcher/payloads/SubmitAskToJoinPayload.ts
  src/hooks/room/useTopic.ts
  src/hooks/usePublicRoomDirectory.ts
  src/hooks/useSpaceResults.ts
  src/stores/OwnBeaconStore.ts
  src/stores/spaces/SpaceStore.ts
  src/stores/spaces/index.ts
  src/utils/AutoDiscoveryUtils.tsx
  src/utils/UserInteractiveAuth.ts
  src/utils/ValidatedServerConfig.ts
  src/utils/beacon/duration.ts
  src/utils/oidc/authorize.ts
  test/components/structures/SpaceHierarchy-test.tsx
  test/components/structures/auth/Login-test.tsx
  test/components/views/beacon/BeaconListItem-test.tsx
  test/components/views/location/LocationViewDialog-test.tsx
  test/components/views/location/shareLocation-test.ts
  test/components/views/messages/MLocationBody-test.tsx
  test/stores/OwnBeaconStore-test.ts
  test/test-utils/beacon.ts
  test/test-utils/location.ts
  test/test-utils/oidc.ts
  test/utils/AutoDiscoveryUtils-test.tsx
  test/utils/location/isSelfLocation-test.ts
Labels: T-Task

#11411 Create flexbox layout helper
  res/css/_components.pcss
  res/css/components/views/utils/_Box.pcss
  res/css/components/views/utils/_Flex.pcss
  res/css/views/rooms/_RoomHeader.pcss
  src/components/utils/Box.tsx
  src/components/utils/Flex.tsx
  src/components/views/rooms/RoomHeader.tsx
Labels: T-Task

#11404 Allow managing room knocks
  res/css/_components.pcss
  res/css/views/dialogs/_RoomSettingsDialog.pcss
  res/css/views/elements/_AccessibleButton.pcss
  res/css/views/settings/tabs/room/_PeopleRoomSettingsTab.pcss
  res/img/feather-customised/check.svg
  res/img/feather-customised/x.svg
  src/components/views/dialogs/RoomSettingsDialog.tsx
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/settings/tabs/room/PeopleRoomSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/RoomSettingsDialog-test.tsx
  test/components/views/settings/tabs/room/PeopleRoomSettingsTab-test.tsx
  test/components/views/settings/tabs/room/__snapshots__/PeopleRoomSettingsTab-test.tsx.snap
Labels: Z-Community-PR, T-Enhancement

#11413 Move `mediaDevices` mock out of `setupManualMocks`
  test/audio/VoiceRecording-test.ts
  test/components/structures/PipContainer-test.tsx
  test/components/views/messages/CallEvent-test.tsx
  test/components/views/rooms/RoomTile-test.tsx
  test/components/views/voip/CallView-test.tsx
  test/setup/setupManualMocks.ts
  test/stores/room-list/algorithms/Algorithm-test.ts
  test/test-utils/utilities.ts
  test/utils/media/requestMediaPermissions-test.tsx
Labels: T-Task

#11414 Remove dead CSS
  res/css/_components.pcss
  res/css/voice-broadcast/atoms/_PlaybackControlButton.pcss
Labels: T-Task

#11409 Update Jest to more recent release
  package.json
  test/DeviceListener-test.ts
  test/components/structures/MatrixChat-test.tsx
  test/components/structures/PipContainer-test.tsx
  test/components/structures/RoomView-test.tsx
  test/components/views/context_menus/WidgetContextMenu-test.tsx
  test/components/views/polls/pollHistory/PollHistory-test.tsx
  test/components/views/rooms/LegacyRoomHeader-test.tsx
  test/components/views/rooms/RoomTile-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/FormattingButtons-test.tsx
  test/components/views/settings/tabs/user/SidebarUserSettingsTab-test.tsx
  test/components/views/user-onboarding/UserOnboardingPage-test.tsx
  test/setup/setupManualMocks.ts
  yarn.lock
Labels: T-Task

#11415 Fix Room Settings > Notifications file upload input being shown superfluously
  res/css/views/settings/tabs/room/_NotificationSettingsTab.pcss
Labels: T-Defect

#11419 MatrixChat-test: stop mocking localStorage
  test/components/structures/MatrixChat-test.tsx
Labels: T-Task

#11412 Switch to nested object pluralisation format for i18n files
  package.json
  scripts/check-i18n.pl
  scripts/fix-i18n.pl
  scripts/fixup-imports.pl
  sonar-project.properties
  src/i18n/strings/ar.json
  src/i18n/strings/bg.json
  src/i18n/strings/ca.json
  src/i18n/strings/cs.json
  src/i18n/strings/da.json
  src/i18n/strings/de_DE.json
  src/i18n/strings/el.json
  src/i18n/strings/en_EN.json
  src/i18n/strings/en_US.json
  src/i18n/strings/eo.json
  src/i18n/strings/es.json
  src/i18n/strings/et.json
  src/i18n/strings/eu.json
  src/i18n/strings/fa.json
  src/i18n/strings/fi.json
  src/i18n/strings/fr.json
  src/i18n/strings/ga.json
  src/i18n/strings/gl.json
  src/i18n/strings/he.json
  src/i18n/strings/hi.json
  src/i18n/strings/hu.json
  src/i18n/strings/id.json
  src/i18n/strings/is.json
  src/i18n/strings/it.json
  src/i18n/strings/ja.json
  src/i18n/strings/jbo.json
  src/i18n/strings/kab.json
  src/i18n/strings/ko.json
  src/i18n/strings/lo.json
  src/i18n/strings/lt.json
  src/i18n/strings/lv.json
  src/i18n/strings/nb_NO.json
  src/i18n/strings/nl.json
  src/i18n/strings/nn.json
  src/i18n/strings/pl.json
  src/i18n/strings/pt.json
  src/i18n/strings/pt_BR.json
  src/i18n/strings/ru.json
  src/i18n/strings/sk.json
  src/i18n/strings/sq.json
  src/i18n/strings/sr.json
  src/i18n/strings/sv.json
  src/i18n/strings/th.json
  src/i18n/strings/tr.json
  src/i18n/strings/uk.json
  src/i18n/strings/vi.json
  src/i18n/strings/vls.json
  src/i18n/strings/zh_Hans.json
  src/i18n/strings/zh_Hant.json
  test/setup/setupLanguage.ts
  yarn.lock
Labels: T-Task

#11407 Pin the action buttons to the bottom of the scrollable dialogs
  res/css/views/dialogs/_CompoundDialog.pcss
Labels: Z-Community-PR, T-Enhancement

#6833 Treat lists with a single empty item as plain text, not Markdown.
  src/Markdown.ts
  test/editor/serialize-test.ts
Labels: T-Enhancement

#11424 Update MatrixChat-test to `restoreAllMocks` after each test
  src/stores/OwnProfileStore.ts
  test/components/structures/MatrixChat-test.tsx
Labels: T-Task

#11426 Fix export type "Current timeline" to match its behaviour to its name
  src/utils/exportUtils/Exporter.ts
  test/utils/exportUtils/HTMLExport-test.ts
Labels: T-Defect

#11421 Support Podman style of accessing the host network in Cypress tests
  cypress/e2e/register/email.spec.ts
  cypress/plugins/docker/index.ts
  cypress/plugins/synapsedocker/index.ts
  cypress/plugins/synapsedocker/templates/default/homeserver.yaml
  cypress/support/homeserver.ts
Labels: T-Task

#11429 Load SAS Emoji translations from `@matrix-org/spec`
  docs/settings.md
  package.json
  src/components/views/verification/VerificationShowSas.tsx
  src/i18n/strings/en_EN.json
  test/components/views/VerificationShowSas-test.tsx
  yarn.lock
Labels: T-Task

#11423 Polish & delabs `Exploring public spaces` feature
  cypress/e2e/spotlight/spotlight.spec.ts
  res/css/views/dialogs/_SpotlightDialog.pcss
  res/img/element-icons/spaces.svg
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomSearch.tsx
  src/components/views/dialogs/spotlight/Filter.ts
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
  src/components/views/spaces/SpaceSettingsVisibilityTab.tsx
  src/dispatcher/actions.ts
  src/dispatcher/payloads/OpenSpotlightPayload.ts
  src/hooks/spotlight/useDebouncedCallback.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/views/dialogs/SpotlightDialog-test.tsx
  test/components/views/settings/tabs/user/LabsUserSettingsTab-test.tsx
  test/components/views/spaces/SpacePanel-test.tsx
Labels: T-Enhancement

#11436 Update matrix-web-i18n
  package.json
  yarn.lock
Labels: T-Task

#11395 Implement updated open dialog method of the Module API
  package.json
  src/components/views/dialogs/ModuleUiDialog.tsx
  src/components/views/dialogs/ScrollableBaseModal.tsx
  src/modules/ProxiedModuleApi.ts
  test/modules/ProxiedModuleApi-test.ts
  test/modules/ProxiedModuleApi-test.tsx
  yarn.lock
Labels: Z-Community-PR, T-Enhancement

#11442 Bump module api from 2.0.0 to 2.1.0
  package.json
  yarn.lock
Labels: Z-Community-PR, T-Task

#11433 Consume @matrix-org/emojibase-bindings
  package.json
  src/HtmlUtils.tsx
  src/autocomplete/EmojiProvider.tsx
  src/components/views/emojipicker/Category.tsx
  src/components/views/emojipicker/Emoji.tsx
  src/components/views/emojipicker/EmojiPicker.tsx
  src/components/views/emojipicker/Preview.tsx
  src/components/views/emojipicker/QuickReactions.tsx
  src/components/views/rooms/BasicMessageComposer.tsx
  src/emoji.ts
  yarn.lock
Labels: T-Task

#11422 Use Intl to localise dates and times
  cypress/e2e/editing/editing.spec.ts
  res/css/views/messages/_DateSeparator.pcss
  src/DateUtils.ts
  src/components/views/dialogs/ForwardDialog.tsx
  src/components/views/messages/DateSeparator.tsx
  src/i18n/strings/en_EN.json
  src/languageHandler.tsx
  test/components/structures/TimelinePanel-test.tsx
  test/components/structures/__snapshots__/MessagePanel-test.tsx.snap
  test/components/views/dialogs/MessageEditHistoryDialog-test.tsx
  test/components/views/dialogs/__snapshots__/MessageEditHistoryDialog-test.tsx.snap
  test/components/views/messages/DateSeparator-test.tsx
  test/components/views/messages/__snapshots__/DateSeparator-test.tsx.snap
  test/components/views/rooms/SearchResultTile-test.tsx
  test/components/views/rooms/__snapshots__/PinnedEventTile-test.tsx.snap
  test/test-utils/beacon.ts
  test/test-utils/location.ts
  test/test-utils/test-utils.ts
  test/utils/DateUtils-test.ts
  test/utils/exportUtils/PlainTextExport-test.ts
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
Labels: T-Task

#11431 OIDC: disable multi session signout for OIDC-aware servers in session manager
  src/components/views/settings/devices/FilteredDeviceList.tsx
  src/components/views/settings/devices/FilteredDeviceListHeader.tsx
  src/components/views/settings/devices/OtherSessionsSectionHeading.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/utils/oidc/getDelegatedAuthAccountUrl.ts
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
  test/utils/oidc/getDelegatedAuthAccountUrl-test.ts
Labels: T-Enhancement

#11430 Disable 3pid fields in settings when `m.3pid_changes` capability is disabled
  src/components/views/settings/account/EmailAddresses.tsx
  src/components/views/settings/account/PhoneNumbers.tsx
  src/components/views/settings/discovery/EmailAddresses.tsx
  src/components/views/settings/discovery/PhoneNumbers.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  test/components/views/settings/tabs/user/GeneralUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/GeneralUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#11432 OIDC: Redirect to delegated auth provider when signing out
  src/components/structures/InteractiveAuth.tsx
  src/components/views/dialogs/DeactivateAccountDialog.tsx
  src/components/views/dialogs/InteractiveAuthDialog.tsx
  src/components/views/dialogs/oidc/OidcLogoutDialog.tsx
  src/components/views/settings/devices/deleteDevices.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  src/utils/oidc/getOidcLogoutUrl.ts
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: X-Release-Blocker, T-Enhancement

#11416 Add mechanism to check only one instance of the app is running
  jest.config.ts
  package.json
  sonar-project.properties
  src/utils/SessionLock.ts
  test/utils/SessionLock-test.ts
  yarn.lock
Labels: T-Task

#11428 Get country names from the browser instead of manual i18n
  src/components/views/auth/CountryDropdown.tsx
  src/i18n/strings/en_EN.json
  src/phonenumber.ts
  test/components/views/auth/CountryDropdown-test.tsx
Labels: T-Task

#11435 Align `a11y_*` strings with Element X project in Localazy
  src/components/structures/UserMenu.tsx
  src/i18n/strings/bg.json
  src/i18n/strings/cs.json
  src/i18n/strings/de_DE.json
  src/i18n/strings/el.json
  src/i18n/strings/en_EN.json
  src/i18n/strings/eo.json
  src/i18n/strings/es.json
  src/i18n/strings/et.json
  src/i18n/strings/eu.json
  src/i18n/strings/fa.json
  src/i18n/strings/fi.json
  src/i18n/strings/fr.json
  src/i18n/strings/gl.json
  src/i18n/strings/he.json
  src/i18n/strings/hu.json
  src/i18n/strings/id.json
  src/i18n/strings/is.json
  src/i18n/strings/it.json
  src/i18n/strings/ja.json
  src/i18n/strings/kab.json
  src/i18n/strings/lo.json
  src/i18n/strings/lv.json
  src/i18n/strings/nb_NO.json
  src/i18n/strings/nl.json
  src/i18n/strings/pl.json
  src/i18n/strings/pt_BR.json
  src/i18n/strings/ru.json
  src/i18n/strings/sk.json
  src/i18n/strings/sq.json
  src/i18n/strings/sv.json
  src/i18n/strings/tr.json
  src/i18n/strings/uk.json
  src/i18n/strings/vi.json
  src/i18n/strings/zh_Hans.json
  src/i18n/strings/zh_Hant.json
Labels: T-Task

#11450 Avoid importing mkEvent from matrix-js-sdk/spec since that is not in the package
  test/components/views/dialogs/RoomSettingsDialog-test.tsx
Labels: T-Task, backport staging

#11456 Disable some IRC audio player tests because they are flaky
  cypress/e2e/audio-player/audio-player.spec.ts
Labels: T-Task

#11452 Migrate keyboard translations to IDs
  src/accessibility/KeyboardShortcuts.ts
  src/i18n/strings/ar.json
  src/i18n/strings/az.json
  src/i18n/strings/be.json
  src/i18n/strings/bg.json
  src/i18n/strings/ca.json
  src/i18n/strings/cs.json
  src/i18n/strings/da.json
  src/i18n/strings/de_DE.json
  src/i18n/strings/el.json
  src/i18n/strings/en_EN.json
  src/i18n/strings/en_US.json
  src/i18n/strings/eo.json
  src/i18n/strings/es.json
  src/i18n/strings/et.json
  src/i18n/strings/eu.json
  src/i18n/strings/fa.json
  src/i18n/strings/fi.json
  src/i18n/strings/fr.json
  src/i18n/strings/ga.json
  src/i18n/strings/gl.json
  src/i18n/strings/he.json
  src/i18n/strings/hi.json
  src/i18n/strings/hr.json
  src/i18n/strings/hu.json
  src/i18n/strings/id.json
  src/i18n/strings/is.json
  src/i18n/strings/it.json
  src/i18n/strings/ja.json
  src/i18n/strings/jbo.json
  src/i18n/strings/kab.json
  src/i18n/strings/ko.json
  src/i18n/strings/lo.json
  src/i18n/strings/lt.json
  src/i18n/strings/lv.json
  src/i18n/strings/ml.json
  src/i18n/strings/nb_NO.json
  src/i18n/strings/nl.json
  src/i18n/strings/nn.json
  src/i18n/strings/oc.json
  src/i18n/strings/pl.json
  src/i18n/strings/pt.json
  src/i18n/strings/pt_BR.json
  src/i18n/strings/ro.json
  src/i18n/strings/ru.json
  src/i18n/strings/sk.json
  src/i18n/strings/sl.json
  src/i18n/strings/sq.json
  src/i18n/strings/sr.json
  src/i18n/strings/sv.json
  src/i18n/strings/ta.json
  src/i18n/strings/te.json
  src/i18n/strings/th.json
  src/i18n/strings/tr.json
  src/i18n/strings/tzm.json
  src/i18n/strings/uk.json
  src/i18n/strings/vi.json
  src/i18n/strings/vls.json
  src/i18n/strings/zh_Hans.json
  src/i18n/strings/zh_Hant.json
Labels: T-Task

#11444 Add Voice and Video call in room header
  package.json
  res/css/components/views/utils/_Box.pcss
  res/css/components/views/utils/_Flex.pcss
  res/css/views/rooms/_RoomHeader.pcss
  src/components/utils/Box.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/hooks/room/useRoomCallStatus.ts
  src/hooks/room/useRoomThreadNotifications.ts
  src/hooks/useGlobalNotificationState.ts
  src/hooks/useRoomMembers.ts
  src/i18n/strings/en_EN.json
  test/components/views/rooms/RoomHeader-test.tsx
  yarn.lock
Labels: T-Task

#11425 Lock out the first tab if Element is opened in a second tab.
  package.json
  res/css/_components.pcss
  res/css/structures/auth/_ConfirmSessionLockTheftView.pcss
  res/css/structures/auth/_SessionLockStolenView.pcss
  src/Lifecycle.ts
  src/PosthogTrackers.ts
  src/Views.ts
  src/components/structures/MatrixChat.tsx
  src/components/structures/auth/ConfirmSessionLockTheftView.tsx
  src/components/structures/auth/SessionLockStolenView.tsx
  src/i18n/strings/en_EN.json
  src/utils/SessionLock.ts
  test/components/structures/MatrixChat-test.tsx
  test/components/structures/__snapshots__/MatrixChat-test.tsx.snap
  test/test-utils/utilities.ts
  test/utils/SessionLock-test.ts
  yarn.lock
Labels: T-Enhancement

#11466 Remove dead TooltipButton component
  res/css/_components.pcss
  res/css/views/elements/_TooltipButton.pcss
  src/components/views/elements/TooltipButton.tsx
Labels: T-Task

#11454 Migrate labs translations to IDs
  src/i18n/strings/ar.json
  src/i18n/strings/az.json
  src/i18n/strings/be.json
  src/i18n/strings/bg.json
  src/i18n/strings/ca.json
  src/i18n/strings/cs.json
  src/i18n/strings/da.json
  src/i18n/strings/de_DE.json
  src/i18n/strings/el.json
  src/i18n/strings/en_EN.json
  src/i18n/strings/en_US.json
  src/i18n/strings/eo.json
  src/i18n/strings/es.json
  src/i18n/strings/et.json
  src/i18n/strings/eu.json
  src/i18n/strings/fa.json
  src/i18n/strings/fi.json
  src/i18n/strings/fr.json
  src/i18n/strings/ga.json
  src/i18n/strings/gl.json
  src/i18n/strings/he.json
  src/i18n/strings/hi.json
  src/i18n/strings/hr.json
  src/i18n/strings/hu.json
  src/i18n/strings/id.json
  src/i18n/strings/is.json
  src/i18n/strings/it.json
  src/i18n/strings/ja.json
  src/i18n/strings/jbo.json
  src/i18n/strings/kab.json
  src/i18n/strings/ko.json
  src/i18n/strings/lo.json
  src/i18n/strings/lt.json
  src/i18n/strings/lv.json
  src/i18n/strings/ml.json
  src/i18n/strings/nb_NO.json
  src/i18n/strings/nl.json
  src/i18n/strings/nn.json
  src/i18n/strings/oc.json
  src/i18n/strings/pl.json
  src/i18n/strings/pt.json
  src/i18n/strings/pt_BR.json
  src/i18n/strings/ro.json
  src/i18n/strings/ru.json
  src/i18n/strings/sk.json
  src/i18n/strings/sl.json
  src/i18n/strings/sq.json
  src/i18n/strings/sr.json
  src/i18n/strings/sv.json
  src/i18n/strings/ta.json
  src/i18n/strings/te.json
  src/i18n/strings/th.json
  src/i18n/strings/tr.json
  src/i18n/strings/tzm.json
  src/i18n/strings/uk.json
  src/i18n/strings/vi.json
  src/i18n/strings/vls.json
  src/i18n/strings/zh_Hans.json
  src/i18n/strings/zh_Hant.json
  src/settings/Settings.tsx
Labels: T-Task

#11467 Add debug to diagnose flaky composer test
  src/components/views/rooms/wysiwyg_composer/components/WysiwygAutocomplete.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
Labels: T-Task

#11468 Fix incompatibility of Soft Logout with Element-R
  src/components/structures/auth/SoftLogout.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/__snapshots__/MatrixChat-test.tsx.snap
Labels: T-Defect

#11470 Fix colour of avatar and colour matching with username
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light-high-contrast/css/_light-high-contrast.pcss
  res/themes/light/css/_light.pcss
  src/components/views/messages/DisambiguatedProfile.tsx
  src/utils/FormattingUtils.ts
  test/components/structures/__snapshots__/MessagePanel-test.tsx.snap
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/structures/__snapshots__/SpaceHierarchy-test.tsx.snap
  test/components/structures/__snapshots__/UserMenu-test.tsx.snap
  test/components/views/avatars/__snapshots__/RoomAvatar-test.tsx.snap
  test/components/views/beacon/__snapshots__/BeaconMarker-test.tsx.snap
  test/components/views/beacon/__snapshots__/BeaconViewDialog-test.tsx.snap
  test/components/views/beacon/__snapshots__/DialogSidebar-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ConfirmUserActionDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ManageRestrictedJoinRuleDialog-test.tsx.snap
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/components/views/elements/__snapshots__/FacePile-test.tsx.snap
  test/components/views/elements/__snapshots__/Pill-test.tsx.snap
  test/components/views/location/Marker-test.tsx
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/MLocationBody-test.tsx.snap
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/components/views/rooms/__snapshots__/PinnedEventTile-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomTile-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/PeopleRoomSettingsTab-test.tsx.snap
  test/components/views/spaces/__snapshots__/AddExistingToSpaceDialog-test.tsx.snap
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
  yarn.lock
Labels: T-Defect

#11465 Fix read receipt tests with incorrect read counts
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11453 Migrate credits translations to IDs
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/i18n/strings/cs.json
  src/i18n/strings/de_DE.json
  src/i18n/strings/en_EN.json
  src/i18n/strings/es.json
  src/i18n/strings/et.json
  src/i18n/strings/fi.json
  src/i18n/strings/fr.json
  src/i18n/strings/hu.json
  src/i18n/strings/id.json
  src/i18n/strings/it.json
  src/i18n/strings/pl.json
  src/i18n/strings/sk.json
  src/i18n/strings/sq.json
  src/i18n/strings/sv.json
  src/i18n/strings/uk.json
  src/i18n/strings/vi.json
  src/i18n/strings/vls.json
  src/i18n/strings/zh_Hant.json
Labels: T-Task

#11440 Fix flaky Cypress test cypress/e2e/widgets/stickers.spec.ts
  cypress/e2e/widgets/stickers.spec.ts
  cypress/support/views.ts
Labels: T-Task

#11472 Fix consistent avatar output for Percy
  res/css/views/avatars/_BaseAvatar.pcss
  res/css/views/avatars/_DecoratedRoomAvatar.pcss
  res/css/views/elements/_MiniAvatarUploader.pcss
Labels: T-Defect

#11473 Fix avatar defects
  res/css/views/elements/_Pill.pcss
  res/css/views/rooms/_EventBubbleTile.pcss
  src/components/views/right_panel/UserInfo.tsx
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
Labels: T-Defect

#11476 Revert "Update react-types (#10762)"
  package.json
  yarn.lock
Labels: T-Task

#11477 Remove unwanted console.table
  src/hooks/room/useRoomCallStatus.ts
Labels: T-Task

#11482 Allow requesting to join knock rooms via spotlight
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/SpotlightDialog-test.tsx
Labels: Z-Community-PR, T-Enhancement

#11484 Improve error handling for `DeviceListener`
  src/DeviceListener.ts
  test/DeviceListener-test.ts
Labels: T-Task

#11489 Use a single synapse for all unread tests.
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11492 Support for E2EE in Element Call
  src/models/Call.ts
  src/stores/widgets/StopGapWidgetDriver.ts
Labels: T-Enhancement

#11493 Add E2E status in room header
  res/css/_common.pcss
  src/components/views/rooms/RoomHeader.tsx
  src/hooks/useAccountData.ts
  src/hooks/useEncryptionStatus.ts
  src/i18n/strings/en_EN.json
  test/components/views/rooms/RoomHeader-test.tsx
Labels: T-Task

#11491 Minor improvements to unread tests
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11494 Extract place call logic to its own file
  src/components/views/rooms/RoomHeader.tsx
  src/hooks/room/useRoomCallStatus.ts
  src/utils/room/placeCall.ts
Labels: T-Task

#11475 Introduce room knocks bar
  res/css/_components.pcss
  res/css/views/rooms/_RoomKnocksBar.pcss
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/components/views/rooms/RoomKnocksBar.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/RoomKnocksBar-test.tsx
Labels: Z-Community-PR, T-Enhancement
