Repository matrix-org/matrix-react-sdk, pull requests merged in 2023-10, with the labels that each got.

#11674 Fix: Edited message remove button is hard to reach.
  res/css/views/dialogs/_MessageEditHistoryDialog.pcss
Labels: Z-Community-PR, T-Defect

#11692 Downgrade Cypress to v12.
  cypress.config.ts
  package.json
  yarn.lock
Labels: T-Task

#11682 Fix expectations in edit tests: edits should not cause unread
  cypress/e2e/read-receipts/editing-messages.spec.ts
Labels: T-Task

#11685 Update custom translations to support nested fields in structured JSON
  package.json
  src/@types/common.ts
  src/languageHandler.tsx
  test/languageHandler-test.tsx
  yarn.lock
Labels: X-Release-Blocker, T-Defect

#11693 Ensure the bot has joined the correct room before we start the test
  cypress/e2e/read-receipts/editing-messages.spec.ts
  cypress/e2e/read-receipts/high-level.spec.ts
  cypress/e2e/read-receipts/missing-referents.spec.ts
  cypress/e2e/read-receipts/new-messages.spec.ts
  cypress/e2e/read-receipts/reactions.spec.ts
  cypress/e2e/read-receipts/redactions.spec.ts
Labels: T-Task

#11688 Cypress test for incoming user verification
  cypress/e2e/crypto/crypto.spec.ts
  cypress/e2e/crypto/utils.ts
  cypress/e2e/crypto/verification.spec.ts
Labels: T-Task

#11687 Fix a flaky cypress crypto test
  cypress/e2e/crypto/crypto.spec.ts
Labels: T-Task

#11690 OIDC: extract token persistence functions to utils
  src/Lifecycle.ts
  src/utils/tokens/tokens.ts
Labels: T-Task

#11698 Fix: Avatar shrinks with long names
  res/css/views/rooms/_ReadReceiptGroup.pcss
Labels: Z-Community-PR, T-Defect

#11686 Cypress: Check that the new verified device is connected to key backup
  cypress/e2e/crypto/utils.ts
  cypress/e2e/crypto/verification.spec.ts
  cypress/support/bot.ts
Labels: T-Task

#11678 Fix: Wierd shadow below room avatar in dark mode.
  res/css/views/right_panel/_RoomSummaryCard.pcss
Labels: Z-Community-PR, T-Defect, X-Needs-Percy

#11695 Share code for room initialisation between read receipt tests
  cypress/e2e/read-receipts/editing-messages.spec.ts
  cypress/e2e/read-receipts/high-level.spec.ts
  cypress/e2e/read-receipts/missing-referents.spec.ts
  cypress/e2e/read-receipts/new-messages.spec.ts
  cypress/e2e/read-receipts/reactions.spec.ts
  cypress/e2e/read-receipts/read-receipts-utils.ts
  cypress/e2e/read-receipts/redactions.spec.ts
Labels: T-Task

#11689 Enable some cypress tests for rust crypto
  cypress/e2e/crypto/crypto.spec.ts
Labels: T-Task

#11696 Unflake redaction tests by checking unread state before sending redactions
  cypress/e2e/read-receipts/redactions.spec.ts
Labels: T-Task

#11681 Fix start_sso / start_cas URLs failing to redirect to a authentication prompt
  src/components/structures/MatrixChat.tsx
  test/components/structures/MatrixChat-test.tsx
Labels: T-Defect

#11704 Skip redaction tests that are still flaking
  cypress/e2e/read-receipts/redactions.spec.ts
Labels: T-Task

#11710 Skip flaky cypress test on rust crypto
  cypress/e2e/crypto/verification.spec.ts
Labels: T-Task

#11691 OIDC: persist id token claims
  src/Lifecycle.ts
  src/utils/oidc/authorize.ts
  src/utils/oidc/persistOidcSettings.ts
  test/components/structures/MatrixChat-test.tsx
  test/utils/oidc/authorize-test.ts
  test/utils/oidc/persistOidcSettings-test.ts
Labels: T-Task

#11712 Cypress: write logs to file
  .github/workflows/cypress.yaml
  .gitignore
  cypress-ci-reporter-config.json
  cypress/plugins/index.ts
Labels: T-Task

#11715 Unflake JoinRuleSettings test
  test/components/views/settings/JoinRuleSettings-test.tsx
Labels: T-Task

#11719 Disable a bunch of flaky cypress tests
  cypress/e2e/composer/composer.spec.ts
  cypress/e2e/crypto/crypto.spec.ts
  cypress/e2e/read-receipts/editing-messages.spec.ts
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11720 Disable cypress debug logs
  .github/workflows/cypress.yaml
Labels: T-Task

#11657 Fix: Clicking on members pile does nothing.
  res/css/structures/_SpaceRoomView.pcss
  src/components/views/elements/FacePile.tsx
  src/components/views/elements/RoomFacePile.tsx
  test/components/views/elements/__snapshots__/FacePile-test.tsx.snap
  test/components/views/elements/__snapshots__/RoomFacePile-test.tsx.snap
Labels: Z-Community-PR, T-Defect

#11597 Prevent select element in General settings overflowing in a room with very long room-id
  cypress/e2e/settings/general-room-settings-tab.spec.ts
  res/css/views/elements/_Field.pcss
  res/css/views/settings/tabs/_SettingsSection.pcss
Labels: Z-Community-PR, T-Defect

#11709 Element-R: Use `MatrixClient.CryptoApi.getUserVerificationStatus` instead of `MatrixClient.checkUserTrust` in `UserInfo.tsx`
  src/components/views/right_panel/UserInfo.tsx
  test/components/views/right_panel/UserInfo-test.tsx
Labels: T-Task

#11730 Include Percy command in config for Cypress
  .github/workflows/cypress.yaml
Labels: T-Task

#11729 Usability fixes for new room header
  res/css/views/rooms/_RoomHeader.pcss
  res/themes/dark/css/_dark.pcss
  res/themes/legacy-dark/css/_legacy-dark.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light-custom/css/_custom.pcss
  res/themes/light/css/_light.pcss
  src/components/views/elements/FacePile.tsx
  src/components/views/rooms/RoomHeader.tsx
  test/components/views/elements/__snapshots__/FacePile-test.tsx.snap
  test/components/views/elements/__snapshots__/RoomFacePile-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
Labels: T-Task

#11722 Fix alignment and poor contrast on user pills in invite dialog
  res/css/views/dialogs/_InviteDialog.pcss
Labels: Z-Community-PR, T-Defect

#11727 OIDC: register
  src/Login.ts
  src/components/structures/auth/Registration.tsx
  src/utils/oidc/authorize.ts
  src/utils/oidc/isUserRegistrationSupported.ts
  test/components/structures/auth/Login-test.tsx
  test/components/structures/auth/Registration-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#11734 Fix untranslated headings in the devtools dialog
  src/components/views/dialogs/DevtoolsDialog.tsx
  src/components/views/dialogs/devtools/AccountData.tsx
  src/components/views/dialogs/devtools/BaseTool.tsx
  src/components/views/dialogs/devtools/Event.tsx
  src/components/views/dialogs/devtools/RoomState.tsx
  src/components/views/dialogs/devtools/SettingExplorer.tsx
Labels: T-Defect

#11699 OIDC: refresh tokens
  src/Lifecycle.ts
  src/MatrixClientPeg.ts
  src/utils/oidc/TokenRefresher.ts
  src/utils/oidc/persistOidcSettings.ts
  test/Lifecycle-test.ts
  test/utils/oidc/TokenRefresher-test.ts
  test/utils/oidc/persistOidcSettings-test.ts
Labels: T-Enhancement

#11735 Add data attribute to know what header is used
  src/components/structures/RoomView.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
Labels: T-Task

#11731 Always use cypress-multi-reporters XML report, not just in CI
  .github/workflows/cypress.yaml
  cypress.config.ts
Labels: T-Task

#11742 Increase the timeout for the bot to enter the room
  cypress/e2e/read-receipts/read-receipts-utils.ts
Labels: T-Task

#11740 Disable spotlight unknown people test
  cypress/e2e/spotlight/spotlight.spec.ts
Labels: T-Task

#11741 Avoid rendering app download buttons if disabled in config
  src/IConfigOptions.ts
  src/SdkConfig.ts
  src/components/structures/MatrixChat.tsx
  src/components/views/dialogs/AppDownloadDialog.tsx
  src/hooks/useUserOnboardingTasks.ts
  test/components/views/dialogs/AppDownloadDialog-test.tsx
  test/components/views/dialogs/__snapshots__/AppDownloadDialog-test.tsx.snap
Labels: T-Enhancement

#11744 Disable upgraderoom command without developer mode enabled
  src/SlashCommands.tsx
  test/SlashCommands-test.tsx
Labels: T-Enhancement

#11743 Consolidate 4s passphrase input fields and use stable IDs
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/views/auth/PassphraseConfirmField.tsx
Labels: T-Enhancement

#11746 Show all labs flags if developerMode enabled
  src/IConfigOptions.ts
  src/SdkConfig.ts
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/settings/tabs/user/KeyboardUserSettingsTab.tsx
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
Labels: T-Enhancement

#11733 Show `io.element.late_event` in MessageTimestamp when known
  src/components/views/messages/MessageTimestamp.tsx
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
  test/components/views/messages/MessageTimestamp-test.tsx
  yarn.lock
Labels: T-Enhancement

#11718 OIDC: revoke tokens on logout
  src/Lifecycle.ts
  src/components/structures/MatrixChat.tsx
  src/components/structures/auth/SoftLogout.tsx
  src/stores/oidc/OidcClientStore.ts
  test/Lifecycle-test.ts
  test/stores/oidc/OidcClientStore-test.ts
Labels: T-Enhancement

#11723 OIDC: use delegated auth account URL from `OidcClientStore`
  src/components/structures/MatrixChat.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/utils/oidc/getDelegatedAuthAccountUrl.ts
  test/components/views/dialogs/UserSettingsDialog-test.tsx
  test/components/views/settings/tabs/user/GeneralUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/utils/oidc/getDelegatedAuthAccountUrl-test.ts
Labels: T-Defect

#11750 Write mdbook summary
  docs/SUMMARY.md
Labels: T-Task

#11738 Move timeline groupers into their own directory
  src/components/structures/MessagePanel.tsx
  src/components/structures/grouper/BaseGrouper.ts
  src/components/structures/grouper/CreationGrouper.tsx
  src/components/structures/grouper/MainGrouper.tsx
Labels: T-Task

#11747 Clean up docker containers created by cypress tests
  cypress/plugins/docker/index.ts
Labels: T-Task

#11749 Update Element Call URL generation to match new parameter semantics
  src/models/Call.ts
Labels: T-Task

#11703 Fix: Message shield alignment is not right.
  res/css/views/rooms/_EventBubbleTile.pcss
  res/css/views/rooms/_EventTile.pcss
Labels: Z-Community-PR, T-Defect

#11754 Avoid error when DMing oneself
  src/createRoom.ts
  test/createRoom-test.ts
Labels: T-Defect

#11760 Iterate `io.element.late_event` decoration
  res/css/views/messages/_MessageTimestamp.pcss
  res/img/sensor.svg
  src/components/views/messages/MessageTimestamp.tsx
  src/i18n/strings/en_EN.json
  test/components/views/messages/MessageTimestamp-test.tsx
Labels: T-Enhancement

#11761 Disable two tests that flake after matrix-js-sdk#3798
  cypress/e2e/read-receipts/redactions.spec.ts
Labels: T-Task

#11769 Cypress: try to stabilise 'Configured room on IRC layout' percy snapshot
  cypress/e2e/timeline/timeline.spec.ts
Labels: T-Task

#11763 Fix: Bubble layout design is broken
  res/css/views/rooms/_EventBubbleTile.pcss
Labels: Z-Community-PR, T-Defect

#11770 Cypress: distinguish logs from bot clients
  cypress/support/bot.ts
Labels: T-Task

#11757 Fix: emoji size in room header topic, remove obsolete emoji style
  res/css/views/elements/_RichText.pcss
Labels: T-Defect

#11184 OIDC: add friendly errors
  src/Lifecycle.ts
  src/i18n/strings/en_EN.json
  src/utils/oidc/authorize.ts
  src/utils/oidc/error.ts
  test/components/structures/MatrixChat-test.tsx
  test/utils/oidc/authorize-test.ts
Labels: T-Enhancement

#11751 Fix CSS for uploading-files in threads
  res/css/structures/_UploadBar.pcss
Labels: Z-Community-PR, T-Task

#11773 OIDC: feature flag copy
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Task

#11724 Skip flaky test 'Looking in thread view to find old threads'
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11774 Revert "Fix: emoji size in room header topic, remove obsolete emoji style"
  res/css/views/elements/_RichText.pcss
Labels: T-Defect

#11664 New right panel visual language
  cypress/e2e/invite/invite-dialog.spec.ts
  cypress/e2e/right-panel/file-panel.spec.ts
  cypress/e2e/right-panel/right-panel.spec.ts
  package.json
  res/css/_common.pcss
  res/css/structures/_MainSplit.pcss
  res/css/structures/_MatrixChat.pcss
  res/css/structures/_RightPanel.pcss
  res/css/views/right_panel/_BaseCard.pcss
  res/css/views/right_panel/_RoomSummaryCard.pcss
  res/css/views/right_panel/_TimelineCard.pcss
  res/css/views/rooms/_LegacyRoomHeader.pcss
  res/css/views/rooms/_MemberList.pcss
  res/css/views/rooms/_RoomHeader.pcss
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/utils/Flex.tsx
  src/components/views/right_panel/BaseCard.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/components/views/right_panel/RoomSummaryCard-test.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
  yarn.lock
Labels: T-Enhancement

#11779 Set max size for Element logo in search warning
  src/components/views/elements/SearchWarning.tsx
Labels: T-Defect, backport staging

#11784 Update base64 import
  src/BasePlatform.ts
  src/SecurityManager.ts
Labels: T-Defect

#11783 Rename the per-participant e2ee keys event
  src/stores/widgets/StopGapWidgetDriver.ts
Labels: T-Task

#11780 Fix margin of invite to room button
  res/css/views/rooms/_MemberList.pcss
Labels: T-Defect

#11697 Fix: Right panel keeps showing chat when unmaximizing widget.
  cypress/e2e/widgets/layout.spec.ts
  src/components/structures/RoomView.tsx
Labels: Z-Community-PR, T-Defect

#11775 Cypress: add emoji messages to message display Percy screenshots
  cypress/e2e/timeline/timeline.spec.ts
Labels: T-Task

#11786 Revert "Fix: Right panel keeps showing chat when unmaximizing widget. "
  cypress/e2e/widgets/layout.spec.ts
  src/components/structures/RoomView.tsx
Labels: T-Defect

#11788 Element-R: Disable `can receive a verification request when there is no existing DM` cypress test for EWR
  cypress/e2e/crypto/verification.spec.ts
Labels: T-Task

#11753 Make invitation dialog scrollable when infos are too long
  res/css/views/dialogs/_InviteDialog.pcss
  res/css/views/rooms/_RoomPreviewBar.pcss
Labels: Z-Community-PR, T-Defect

#11789 Fix io.element.late_event received_ts vs received_at
  src/components/structures/grouper/LateEventGrouper.ts
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#11795 Element-R: Disable `After marking room as read, paging up to find old threads that were never read leaves the room read`
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#9618 Fix unfederated invite dialog
  src/components/views/dialogs/InviteDialog.tsx
  src/i18n/strings/en_EN.json
  src/utils/MultiInviter.ts
  test/components/views/dialogs/InviteDialog-test.tsx
  test/test-utils/test-utils.ts
  test/utils/MultiInviter-test.ts
Labels: Z-Community-PR, T-Enhancement

#11796 Use configurable github issue links more consistently
  src/components/views/dialogs/BugReportDialog.tsx
  src/components/views/elements/ErrorBoundary.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
Labels: T-Defect

#11785 Element-R: Add current version of the rust-sdk and vodozemac
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/UserSettingsDialog-test.tsx
  test/test-utils/client.ts
Labels: T-Enhancement

#11794 Fix: Unable to restore a soft-logged-out session established via SSO
  cypress/e2e/login/soft_logout.spec.ts
  src/components/structures/auth/SoftLogout.tsx
Labels: T-Defect

#11793 Fix Incorrect message scaling for verification request
  res/css/views/messages/_EventTileBubble.pcss
  res/css/views/rooms/_EventTile.pcss
Labels: Z-Community-PR, T-Defect

#11801 Cypress flake: disable `Paging up through old messages after a room is read leaves the room read`
  cypress/e2e/read-receipts/high-level.spec.ts
Labels: T-Task

#11797 Element-R: Include crypto info in rageshake
  src/rageshake/submit-rageshake.ts
Labels: T-Enhancement

#11800 Fix multi-tab session lock on Firefox not being cleared
  src/utils/SessionLock.ts
Labels: Z-Community-PR, T-Defect

#11802 Disable flaky verification test for Element-R
  cypress/e2e/crypto/crypto.spec.ts
Labels: T-Task

#11805 Deserialise spoilers back into slash command form
  src/editor/deserialize.ts
  test/editor/deserialize-test.ts
Labels: T-Defect

#11798 Element-R: Include crypto info in sentry
  src/sentry.ts
Labels: T-Enhancement

#11804 Disable flaky filepanel test
  cypress/e2e/right-panel/file-panel.spec.ts
Labels: T-Task

#11787 Knock on a ask-to-join room if a module wants to join the room when navigating to a room
  src/modules/ProxiedModuleApi.ts
Labels: T-Enhancement, A-Timesheet-1

#11807 Use olm from default npm registry, since it's there now
  package.json
  yarn.lock
Labels: T-Task

#11792 Use new matrixRTC calling
  src/components/views/beacon/RoomCallBanner.tsx
  src/components/views/messages/CallEvent.tsx
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/components/views/voip/CallDuration.tsx
  src/models/Call.ts
  src/stores/CallStore.ts
  src/stores/WidgetStore.ts
  src/widgets/WidgetType.ts
  test/components/structures/MatrixChat-test.tsx
  test/components/views/messages/CallEvent-test.tsx
  test/models/Call-test.ts
  test/test-utils/call.ts
  test/test-utils/test-utils.ts
Labels: T-Task

#11810 Disable a flaky threads test
  cypress/e2e/threads/threads.spec.ts
Labels: T-Task
