Repository matrix-org/matrix-react-sdk, pull requests merged in 2023-05, with the labels that each got.

#10755 Update existing Cypress tests - use Cypress Testing Library
  cypress/e2e/crypto/crypto.spec.ts
  cypress/e2e/crypto/decryption-failure.spec.ts
  cypress/e2e/right-panel/right-panel.spec.ts
Labels: Z-Community-PR, T-Task

#10750 Flaky test SecurityRoomSettingsTab enables encryption after confirmation
  test/components/views/settings/tabs/room/SecurityRoomSettingsTab-test.tsx
Labels: T-Task

#10744 Tidy up `_RoomView.pcss`
  res/css/structures/_RoomView.pcss
Labels: Z-Community-PR, T-Task, X-Needs-Percy

#10751 Use semantic headings in space settings
  res/css/_components.pcss
  res/css/views/room_settings/_AliasSettings.pcss
  res/css/views/settings/tabs/room/_GeneralRoomSettingsTab.pcss
  src/components/views/room_settings/AliasSettings.tsx
  src/components/views/settings/tabs/room/GeneralRoomSettingsTab.tsx
  src/components/views/spaces/SpaceSettingsGeneralTab.tsx
  src/components/views/spaces/SpaceSettingsVisibilityTab.tsx
  test/components/views/spaces/__snapshots__/SpaceSettingsVisibilityTab-test.tsx.snap
Labels: T-Enhancement

#10776 Replace Sass variables with CSS custom properties - $container-gap-width and $container-border-width
  res/css/_common.pcss
  res/css/structures/_MainSplit.pcss
  res/css/structures/_MatrixChat.pcss
  res/css/structures/_RightPanel.pcss
  res/css/structures/_RoomView.pcss
  res/css/views/right_panel/_TimelineCard.pcss
  res/css/views/rooms/_AppsDrawer.pcss
  res/css/views/rooms/_RoomPreviewBar.pcss
  res/css/views/voip/_CallView.pcss
  res/css/views/voip/_LegacyCallView.pcss
Labels: Z-Community-PR, T-Task

#10700 Merge style rules related to EventTile on IRC layout
  cypress/e2e/timeline/timeline.spec.ts
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/_IRCLayout.pcss
Labels: Z-Community-PR, T-Task

#10769 Cypress test for unthreaded receipts not clobbering main thread ones
  cypress/e2e/read-receipts/read-receipts.spec.ts
  cypress/support/client.ts
Labels: T-Task

#10679 Merge styles of `_EmailAddresses.pcss` and `_PhoneNumbers.pcss`
  res/css/_components.pcss
  res/css/views/settings/_EmailAddresses.pcss
  res/css/views/settings/_PhoneNumbers.pcss
  res/css/views/settings/tabs/user/_GeneralUserSettingsTab.pcss
  src/components/views/settings/account/EmailAddresses.tsx
  src/components/views/settings/account/PhoneNumbers.tsx
  src/components/views/settings/discovery/EmailAddresses.tsx
  src/components/views/settings/discovery/PhoneNumbers.tsx
Labels: Z-Community-PR, T-Task

#10771 Remove unused prop from `ResizeHandle` - reverse
  src/components/structures/LoggedInView.tsx
  src/components/views/elements/ResizeHandle.tsx
  src/components/views/rooms/AppsDrawer.tsx
Labels: Z-Community-PR, T-Task

#10754 Remove some obsolete CSS rules
  res/css/views/messages/_MImageReplyBody.pcss
  res/css/views/right_panel/_WidgetCard.pcss
  res/css/views/room_settings/_AliasSettings.pcss
  res/css/views/rooms/_RoomList.pcss
  res/css/views/rooms/_Stickers.pcss
Labels: Z-Community-PR, T-Task

#10768 Support launching Cypress tests in Podman on Ubuntu
  cypress/plugins/docker/index.ts
Labels: T-Task

#10716 Replace remaining use of `checkDeviceTrust`
  src/stores/SetupEncryptionStore.ts
Labels: T-Task

#10758 use ExternalLink components for external links
  src/components/structures/RoomStatusBar.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/views/dialogs/AnalyticsLearnMoreDialog.tsx
  src/components/views/dialogs/FeedbackDialog.tsx
  src/components/views/dialogs/ServerPickerDialog.tsx
  src/components/views/dialogs/TermsDialog.tsx
  src/components/views/settings/EventIndexPanel.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/utils/ErrorUtils.tsx
  test/components/structures/RoomStatusBar-test.tsx
  test/components/structures/__snapshots__/RoomStatusBar-test.tsx.snap
  test/components/views/dialogs/__snapshots__/FeedbackDialog-test.tsx.snap
  test/utils/__snapshots__/ErrorUtils-test.ts.snap
Labels: T-Enhancement

#10753 Remove obsolete CSS files - `_AuthButtons.pcss`, `_NewSessionReviewDialog.pcss`, and `_ManageIntegsButton.pcss`
  res/css/_components.pcss
  res/css/views/auth/_AuthButtons.pcss
  res/css/views/dialogs/_NewSessionReviewDialog.pcss
  res/css/views/elements/_ManageIntegsButton.pcss
Labels: Z-Community-PR, T-Task

#10767 Tidy up `_MessageComposer.pcss`
  res/css/views/rooms/_MessageComposer.pcss
Labels: Z-Community-PR, T-Task

#10752 Use semantic headings in user settings Help & About
  res/css/components/views/settings/shared/_SettingsSubsection.pcss
  res/css/components/views/settings/shared/_SettingsSubsectionHeading.pcss
  src/components/views/settings/shared/SettingsSubsection.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  test/components/views/dialogs/UserSettingsDialog-test.tsx
  test/components/views/settings/devices/__snapshots__/SecurityRecommendations-test.tsx.snap
  test/components/views/settings/shared/__snapshots__/SettingsSubsection-test.tsx.snap
Labels: T-Enhancement

#10785 Add a waitFor in case it fixes flaky SecurityRoomSettingsTab test
  test/components/views/settings/tabs/room/SecurityRoomSettingsTab-test.tsx
Labels: T-Task

#10693 Add E2E test: `invite-dialog.spec.ts`
  cypress/e2e/invite/invite-dialog.spec.ts
  src/components/views/dialogs/InviteDialog.tsx
Labels: Z-Community-PR, T-Task

#10772 Update `_ResizeHandle.pcss`
  res/css/structures/_MainSplit.pcss
  res/css/structures/_MatrixChat.pcss
  res/css/views/elements/_ResizeHandle.pcss
  res/css/views/rooms/_AppsDrawer.pcss
  src/components/structures/LoggedInView.tsx
  src/components/structures/MainSplit.tsx
  src/components/views/elements/ResizeHandle.tsx
  src/components/views/rooms/AppsDrawer.tsx
Labels: Z-Community-PR, T-Task

#10592 Sort muted rooms to the bottom of their section of the room list
  src/RoomNotifs.ts
  src/actions/MatrixActionCreators.ts
  src/stores/notifications/NotificationColor.ts
  src/stores/notifications/NotificationState.ts
  src/stores/notifications/RoomNotificationState.ts
  src/stores/room-list/RoomListStore.ts
  src/stores/room-list/algorithms/list-ordering/ImportanceAlgorithm.ts
  src/stores/room-list/algorithms/list-ordering/NaturalAlgorithm.ts
  src/stores/room-list/algorithms/list-ordering/OrderingAlgorithm.ts
  src/stores/room-list/models.ts
  src/stores/room-list/utils/roomMute.ts
  test/stores/room-list/RoomListStore-test.ts
  test/stores/room-list/algorithms/list-ordering/ImportanceAlgorithm-test.ts
  test/stores/room-list/algorithms/list-ordering/NaturalAlgorithm-test.ts
  test/stores/room-list/utils/roomMute-test.ts
Labels: T-Enhancement

#10781 Fix: reveal images when image previews are disabled
  src/components/views/messages/MImageBody.tsx
  test/components/views/messages/MImageBody-test.tsx
Labels: T-Defect

#10742 Improve quality of Typescript types
  src/DeviceListener.ts
  src/IdentityAuthClient.tsx
  src/MatrixClientPeg.ts
  src/NodeAnimator.tsx
  src/audio/VoiceRecording.ts
  src/autocomplete/AutocompleteProvider.tsx
  src/autocomplete/QueryMatcher.ts
  src/autocomplete/UserProvider.tsx
  src/components/views/auth/PasswordLogin.tsx
  src/components/views/auth/RegistrationForm.tsx
  src/components/views/avatars/DecoratedRoomAvatar.tsx
  src/components/views/rooms/Autocomplete.tsx
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/rooms/Stickerpicker.tsx
  src/components/views/settings/ThemeChoicePanel.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/components/views/toasts/VerificationRequestToast.tsx
  src/components/views/voip/LegacyCallView.tsx
  src/components/views/voip/VideoFeed.tsx
  src/editor/autocomplete.ts
  src/integrations/IntegrationManagers.ts
  src/models/LocalRoom.ts
  src/models/RoomUpload.ts
  src/stores/ActiveWidgetStore.ts
  src/stores/OwnProfileStore.ts
  src/stores/local-echo/GenericEchoChamber.ts
  src/utils/LazyValue.ts
  src/utils/ValidatedServerConfig.ts
  src/widgets/Jitsi.ts
  test/components/structures/auth/ForgotPassword-test.tsx
Labels: T-Task

#10724 Apply `strictNullChecks` to `src/components/views/settings`
  src/components/views/elements/Tag.tsx
  src/components/views/settings/JoinRuleSettings.tsx
  src/components/views/settings/Notifications.tsx
  src/components/views/settings/ProfileSettings.tsx
  src/components/views/settings/SecureBackupPanel.tsx
  src/components/views/settings/tabs/user/VoiceUserSettingsTab.tsx
  test/components/views/settings/JoinRuleSettings-test.tsx
  test/components/views/settings/Notifications-test.tsx
  test/components/views/settings/SecureBackupPanel-test.tsx
  test/components/views/settings/__snapshots__/SecureBackupPanel-test.tsx.snap
  test/components/views/settings/tabs/user/VoiceUserSettingsTab-test.tsx
Labels: T-Task

#10601 Move reaction message previews out of labs
  src/components/views/context_menus/MessageContextMenu.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/room-list/previews/ReactionEventPreview.ts
  src/stores/room-list/previews/utils.ts
  test/components/views/settings/tabs/user/LabsUserSettingsTab-test.tsx
  test/stores/room-list/previews/PollStartEventPreview-test.ts
  test/stores/room-list/previews/ReactionEventPreview-test.ts
Labels: T-Enhancement

#10725 Remove one of the tsc strict check CIs
  .github/workflows/static_analysis.yaml
Labels: T-Task

#10729 Ensure tooltip contents is linked via aria to the target element
  res/css/views/right_panel/_UserInfo.pcss
  src/components/structures/auth/forgot-password/CheckEmail.tsx
  src/components/structures/auth/forgot-password/VerifyEmailModal.tsx
  src/components/views/dialogs/UntrustedDeviceDialog.tsx
  src/components/views/elements/LinkWithTooltip.tsx
  src/components/views/elements/Pill.tsx
  src/components/views/elements/TextWithTooltip.tsx
  src/components/views/elements/Tooltip.tsx
  src/components/views/messages/ReactionsRowButton.tsx
  src/components/views/messages/ReactionsRowButtonTooltip.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/E2EIcon.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/MessageComposer.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/elements/Pill-test.tsx
  test/components/views/elements/__snapshots__/Pill-test.tsx.snap
  test/components/views/elements/__snapshots__/TooltipTarget-test.tsx.snap
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
Labels: T-Defect

#10787 Remove mixin `mx_Dialog_link`
  res/css/_common.pcss
  res/css/views/auth/_AuthBody.pcss
  res/css/views/auth/_CompleteSecurityBody.pcss
Labels: Z-Community-PR, T-Task

#10653 Apply strictNullChecks to src/components/views/rooms/wysiwyg_composer/*
  src/components/views/rooms/wysiwyg_composer/components/EditionButtons.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useInitialContent.ts
Labels: T-Task

#10717 Fix accessibility issues around the room list and space panel
  src/components/views/rooms/NotificationBadge.tsx
  src/components/views/rooms/NotificationBadge/StatelessNotificationBadge.tsx
  src/components/views/rooms/RoomSublist.tsx
Labels: T-Defect

#10739 Add better error for email invites without identity server
  src/i18n/strings/en_EN.json
  src/utils/MultiInviter.ts
  test/utils/MultiInviter-test.ts
Labels: T-Enhancement

#10789 Fix use of logger that assumes it interpolates strings
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomView.tsx
  src/components/views/auth/CaptchaForm.tsx
  src/editor/commands.tsx
Labels: T-Task

#10790 Fix the repository that we check out from for the cypress tests
  .github/workflows/cypress.yaml
Labels: T-Task

#10756 Make cascading of `mx_RoomHeader_closeButton` easy to understand and be able to be managed more easily
  res/css/views/rooms/_RoomHeader.pcss
Labels: Z-Community-PR, T-Task

#10692 Apply strictNullChecks to src/components/views/voip/*
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/voip/DialPad.tsx
  test/components/views/voip/DialPad-test.tsx
Labels: T-Task

#10804 Remove obsolete style blocks from `_RightPanel.pcss`
  res/css/structures/_RightPanel.pcss
Labels: Z-Community-PR, T-Task

#10690 Apply strictNullChecks to src/LegacyCallHandler.tsx
  src/LegacyCallHandler.tsx
  src/Typeguards.ts
Labels: T-Task

#10795 Fix: No feedback when waiting for the server on a /delete_devices request with SSO
  src/components/structures/InteractiveAuth.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  test/components/views/dialogs/InteractiveAuthDialog-test.tsx
Labels: T-Defect

#10812 Fix the color of the verified E2EE icon on `RoomSummaryCard`
  cypress/e2e/crypto/crypto.spec.ts
  res/css/views/right_panel/_RoomSummaryCard.pcss
Labels: Z-Community-PR, T-Defect

#10815 Remove an obsolete selector from `_RightPanel.pcss` - `mx_RightPanel_blank`
  res/css/structures/_RightPanel.pcss
Labels: Z-Community-PR, T-Task

#10801 Remove mixin `mx_Tooltip_dark` and rename class `mx_Tooltip_dark`
  res/css/_common.pcss
  res/css/views/rooms/_AppsDrawer.pcss
  src/components/views/elements/AppPermission.tsx
Labels: Z-Community-PR, T-Task

#10814 Update file-panel.spec.ts to take a snapshot of the empty file panel
  cypress/e2e/right-panel/file-panel.spec.ts
Labels: Z-Community-PR, T-Task

#10818 Fix the top heading of notification panel
  src/components/structures/NotificationPanel.tsx
Labels: Z-Community-PR, T-Defect

#10783 Update `mx_AppLoading` to improve maintainability
  res/css/views/rooms/_AppsDrawer.pcss
  src/components/views/elements/AppTile.tsx
Labels: Z-Community-PR, T-Task

#10819 Fix: Threads button is highlighted when I create a new room
  src/components/views/right_panel/RoomHeaderButtons.tsx
  test/components/views/right_panel/RoomHeaderButtons-test.tsx
Labels: T-Defect

#10820 "Show rooms with unread messages first" should not be on by default for new users
  src/stores/room-list/RoomListStore.ts
  test/stores/room-list/RoomListStore-test.ts
Labels: T-Enhancement

#10817 Fix icon on empty notification panel
  cypress/e2e/right-panel/notification-panel.spec.ts
  res/css/_components.pcss
  res/css/structures/_FilePanel.pcss
  res/css/structures/_NotificationPanel.pcss
  res/css/structures/_RightPanel.pcss
Labels: Z-Community-PR, T-Defect

#10779 Remove obsolete variable and use a custom property for `Slider`
  res/css/_common.pcss
  res/css/views/elements/_Slider.pcss
Labels: Z-Community-PR, T-Task

#10798 Update finite automata to match user identifiers as per spec
  src/linkify-matrix.ts
  test/linkify-matrix-test.ts
Labels: T-Defect

#10805 Null-guard sync handler in AutoRageshakeStore
  src/stores/AutoRageshakeStore.ts
Labels: T-Task

#10806 Fix more detached DOM leaks
  src/components/structures/AutoHideScrollbar.tsx
  src/components/structures/MessagePanel.tsx
  src/components/structures/ScrollPanel.tsx
  src/components/views/rooms/EventTile.tsx
Labels: T-Task

#10811 Fix long room address and name not being clipped on room info card and update `_RoomSummaryCard.pcss`
  cypress/e2e/right-panel/right-panel.spec.ts
  res/css/views/right_panel/_RoomSummaryCard.pcss
  src/components/views/right_panel/RoomSummaryCard.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
Labels: Z-Community-PR, T-Defect

#10823 Remove unused class names from `AppWarning`
  src/components/views/elements/AppWarning.tsx
Labels: Z-Community-PR, T-Task

#10802 Fix merge queue X-Needs-Percy handling
  .github/workflows/cypress.yaml
Labels: T-Task

#10816 Remove obsolete style blocks from _MemberInfo.pcss
  res/css/views/rooms/_MemberInfo.pcss
Labels: Z-Community-PR, T-Task

#10828 Avoid calling prepareToEncrypt onKeyDown
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
Labels: T-Enhancement

#10831 Use semantically correct elements for room sublist context menu
  src/components/views/rooms/RoomSublist.tsx
Labels: T-Enhancement

#10826 `DeviceListener`: use new `getUserDeviceInfo` method
  src/DeviceListener.ts
  test/DeviceListener-test.ts
Labels: T-Task

#10738 Conform more of the codebase to `strictNullChecks`
  package.json
  src/LegacyCallHandler.tsx
  src/Notifier.ts
  src/actions/RoomListActions.ts
  src/components/structures/FilePanel.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/spaces/SpacePublicShare.tsx
  src/hooks/useRoomNotificationState.ts
  src/linkify-matrix.ts
  src/modules/ProxiedModuleApi.ts
  src/notifications/PushRuleVectorState.ts
  src/utils/FormattingUtils.ts
  yarn.lock
Labels: T-Task

#10469 Add E2E test of `ThemeChoicePanel`
  cypress/e2e/settings/theme-choice-panel.spec.ts
  src/components/views/settings/ThemeChoicePanel.tsx
  test/components/views/settings/__snapshots__/ThemeChoicePanel-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
Labels: Z-Community-PR, T-Task

#10792 Replace `$timeline-image-border-radius` with a CSS custom property
  res/css/_common.pcss
  res/css/components/views/messages/_MBeaconBody.pcss
  res/css/views/messages/_MImageBody.pcss
  res/css/views/messages/_MLocationBody.pcss
  res/css/views/messages/_MVideoBody.pcss
  res/css/views/rooms/_EventBubbleTile.pcss
Labels: Z-Community-PR, T-Task

#10777 Update some class names of `AppTile` on the naming policy
  res/css/views/rooms/_AppsDrawer.pcss
  src/components/views/elements/AppTile.tsx
Labels: Z-Community-PR, T-Task

#10800 Conform more of the codebase to strictNullChecks
  src/LegacyCallHandler.tsx
  src/audio/PlaybackClock.ts
  src/audio/VoiceMessageRecording.ts
  src/audio/VoiceRecording.ts
  src/components/structures/IndicatorScrollbar.tsx
  src/components/structures/LegacyCallEventGrouper.ts
  src/components/structures/LoggedInView.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/ScrollPanel.tsx
  src/components/structures/UserMenu.tsx
  src/components/structures/auth/Registration.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/dialogs/ReportEventDialog.tsx
  src/components/views/dialogs/RoomSettingsDialog.tsx
  src/components/views/dialogs/RoomUpgradeDialog.tsx
  src/components/views/dialogs/ServerPickerDialog.tsx
  src/components/views/dialogs/SetEmailDialog.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/elements/DesktopCapturerSourcePicker.tsx
  src/components/views/elements/PersistedElement.tsx
  src/components/views/messages/IMediaBody.ts
  src/components/views/messages/LegacyCallEvent.tsx
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MVideoBody.tsx
  src/components/views/messages/MessageEvent.tsx
  src/components/views/rooms/AppsDrawer.tsx
  src/components/views/rooms/Autocomplete.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/MemberTile.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/components/views/rooms/RoomSublist.tsx
  src/components/views/rooms/Stickerpicker.tsx
  src/components/views/settings/ChangePassword.tsx
  src/components/views/settings/IntegrationManager.tsx
  src/components/views/settings/SetIdServer.tsx
  src/customisations/Media.ts
  src/i18n/strings/en_EN.json
  src/stores/RoomViewStore.tsx
  src/stores/SetupEncryptionStore.ts
  src/stores/TypingStore.ts
  src/stores/widgets/StopGapWidget.ts
  src/utils/DMRoomMap.ts
  src/utils/WidgetUtils.ts
  src/voice-broadcast/audio/VoiceBroadcastRecorder.ts
  test/settings/watchers/ThemeWatcher-test.tsx
Labels: T-Task

#10839 Revert "Update browser-actions/setup-chrome digest to 5dc4fd3 (#10759)"
  .github/workflows/cypress.yaml
Labels: T-Task

#10835 Flaky Cypress test - `should handle long room address and long room name` on right-panel.spec.ts
  cypress/e2e/right-panel/right-panel.spec.ts
Labels: T-Task

#10697 Add `appearance-user-settings-tab.spec.ts`
  cypress/e2e/settings/appearance-user-settings-tab.spec.ts
  src/components/views/settings/tabs/user/AppearanceUserSettingsTab.tsx
  test/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
Labels: Z-Community-PR, T-Task

#10830 Remove unused class name - `mx_AppsDrawer_fullWidth`
  src/components/views/rooms/AppsDrawer.tsx
Labels: Z-Community-PR, T-Task

#10842 Conform more of the codebase to `strictNullChecks`
  src/components/structures/RoomSearchView.tsx
  src/components/views/avatars/WidgetAvatar.tsx
  src/components/views/context_menus/WidgetContextMenu.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/elements/ReplyChain.tsx
  src/components/views/messages/IBodyProps.ts
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MVideoBody.tsx
  src/components/views/messages/TextualBody.tsx
  src/components/views/rooms/AppsDrawer.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/LinkPreviewGroup.tsx
  src/components/views/rooms/Stickerpicker.tsx
  src/createRoom.ts
  src/customisations/Security.ts
  src/events/EventTileFactory.tsx
  src/i18n/strings/en_EN.json
  src/stores/ActiveWidgetStore.ts
  src/stores/WidgetStore.ts
  src/stores/widgets/StopGapWidget.ts
  src/stores/widgets/WidgetLayoutStore.ts
  src/utils/WidgetUtils.ts
  src/utils/direct-messages.ts
  test/components/views/elements/AppTile-test.tsx
Labels: T-Task

#10853 Fall back from server generated thumbnail to original image
  src/components/views/messages/MImageBody.tsx
  test/components/views/messages/MImageBody-test.tsx
Labels: T-Enhancement

#10855 Fix snapshot `File Panel - empty`
  cypress/e2e/right-panel/file-panel.spec.ts
Labels: Z-Community-PR, T-Task

#10834 Fix: Edit history modal crash
  src/utils/MessageDiffUtils.tsx
  test/utils/MessageDiffUtils-test.tsx
  test/utils/__snapshots__/MessageDiffUtils-test.tsx.snap
Labels: T-Defect

#10843 Fix CSP problems due to cypress-axe
  .github/workflows/cypress.yaml
  cypress/support/axe.ts
Labels: T-Task

#10654 Add audible notifcation on broadcast error
  res/media/error.mp3
  res/media/error.ogg
  src/voice-broadcast/models/VoiceBroadcastRecording.ts
  test/voice-broadcast/models/VoiceBroadcastRecording-test.ts
Labels: T-Enhancement

#10863 Don't run SonarCloud when a change is in the merge queue
  .github/workflows/sonarqube.yml
Labels: T-Task

#10862 Tidy up `_MemberInfo.pcss`
  res/css/views/rooms/_MemberInfo.pcss
Labels: Z-Community-PR, T-Task

#10854 Fix regression in emoji picker order mangling after clearing filter
  src/components/views/emojipicker/EmojiPicker.tsx
  test/components/views/emojipicker/EmojiPicker-test.tsx
Labels: T-Defect

#10665 Room and user mentions for plain text editor
  cypress/e2e/composer/composer.spec.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
  test/components/views/rooms/wysiwyg_composer/hooks/useSuggestion-test.tsx
Labels: T-Enhancement

#10775 Tidy up `_AppsDrawer.pcss`
  res/css/views/rooms/_AppsDrawer.pcss
Labels: Z-Community-PR, T-Task

#10866 Specify lazy loading for avatars
  src/components/views/avatars/BaseAvatar.tsx
  test/components/structures/__snapshots__/MessagePanel-test.tsx.snap
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/structures/__snapshots__/SpaceHierarchy-test.tsx.snap
  test/components/structures/__snapshots__/UserMenu-test.tsx.snap
  test/components/views/avatars/__snapshots__/RoomAvatar-test.tsx.snap
  test/components/views/beacon/__snapshots__/BeaconMarker-test.tsx.snap
  test/components/views/beacon/__snapshots__/BeaconViewDialog-test.tsx.snap
  test/components/views/beacon/__snapshots__/DialogSidebar-test.tsx.snap
  test/components/views/elements/__snapshots__/Pill-test.tsx.snap
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/MLocationBody-test.tsx.snap
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomTile-test.tsx.snap
  test/components/views/spaces/__snapshots__/AddExistingToSpaceDialog-test.tsx.snap
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
Labels: T-Enhancement

#10836 Percy: hide timestamp in permalink rendering screenshot test
  cypress/e2e/permalinks/permalinks.spec.ts
Labels: T-Task

#10870 Respect configured auth_header_logo_url for default Welcome page
  src/components/views/auth/Welcome.tsx
Labels: T-Enhancement

#10859 Make more of the codebase conform to strict types
  src/autocomplete/UserProvider.tsx
  src/components/structures/FilePanel.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/TimelinePanel.tsx
  src/components/structures/UserMenu.tsx
  src/components/structures/auth/SetupEncryptionBody.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/avatars/BaseAvatar.tsx
  src/components/views/avatars/MemberAvatar.tsx
  src/components/views/dialogs/StorageEvictedDialog.tsx
  src/components/views/dialogs/security/AccessSecretStorageDialog.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/elements/PersistentApp.tsx
  src/components/views/messages/MBeaconBody.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/messages/UnknownBody.tsx
  src/components/views/messages/ViewSourceEvent.tsx
  src/components/views/room_settings/AliasSettings.tsx
  src/components/views/room_settings/RoomProfileSettings.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/JumpToBottomButton.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
  src/components/views/rooms/NotificationBadge/StatelessNotificationBadge.tsx
  src/components/views/rooms/RoomSublist.tsx
  src/components/views/rooms/RoomTile.tsx
  src/components/views/rooms/TopUnreadMessagesBar.tsx
  src/components/views/settings/ProfileSettings.tsx
  src/components/views/settings/account/EmailAddresses.tsx
  src/components/views/settings/account/PhoneNumbers.tsx
  src/components/views/settings/devices/DeviceDetailHeading.tsx
  src/components/views/settings/discovery/EmailAddresses.tsx
  src/components/views/settings/discovery/PhoneNumbers.tsx
  src/components/views/settings/tabs/room/GeneralRoomSettingsTab.tsx
  src/components/views/settings/tabs/room/NotificationSettingsTab.tsx
  src/indexing/EventIndex.ts
  src/settings/handlers/AccountSettingsHandler.ts
  src/settings/handlers/RoomAccountSettingsHandler.ts
  src/settings/handlers/RoomSettingsHandler.ts
  src/stores/AutoRageshakeStore.ts
  src/toasts/IncomingLegacyCallToast.tsx
  src/utils/connection.ts
  test/components/views/rooms/MessageComposer-test.tsx
  test/voice-broadcast/stores/VoiceBroadcastPlaybacksStore-test.ts
  test/voice-broadcast/stores/VoiceBroadcastRecordingsStore-test.ts
Labels: T-Task

#10872 Cypress tests for read receipts - threaded and unthreaded
  cypress/e2e/read-receipts/read-receipts.spec.ts
  cypress/support/bot.ts
Labels: T-Task

#10878 Disable flaky Percy tests
  cypress/e2e/permalinks/permalinks.spec.ts
  cypress/e2e/timeline/timeline.spec.ts
Labels: T-Task

#10861 Edit widths of Percy snapshots of "User settings tab - Appearance"
  cypress/e2e/settings/appearance-user-settings-tab.spec.ts
Labels: Z-Community-PR, T-Task

#10869 Add tooltip to disabled invite button due to lack of permissions
  src/components/views/rooms/MemberList.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#10867 Use brand variable consistently
  src/components/structures/WaitingForThirdPartyRoomView.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#10595 Conform the style rules of `GeneralUserSettingsTab.tsx` to the style guide
  cypress/e2e/settings/general-user-settings-tab.spec.ts
  res/css/views/settings/_PhoneNumbers.pcss
  res/css/views/settings/tabs/user/_GeneralUserSettingsTab.pcss
  src/components/views/settings/account/EmailAddresses.tsx
  src/components/views/settings/account/PhoneNumbers.tsx
  src/components/views/settings/discovery/EmailAddresses.tsx
  src/components/views/settings/discovery/PhoneNumbers.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
Labels: Z-Community-PR, T-Task

#10849 Fix people space notification badge not updating for new DM invites
  src/stores/spaces/SpaceStore.ts
  test/stores/SpaceStore-test.ts
Labels: T-Defect

#10865 Improve bundle size, dynamic imports & remove parse5
  __mocks__/maplibre-gl.js
  package.json
  src/HtmlUtils.tsx
  src/SlashCommands.tsx
  src/editor/serialize.ts
  src/rageshake/submit-rageshake.ts
  yarn.lock
Labels: T-Task

#10877 Conform `_AppsDrawer.pcss` to our naming policy - move styles specific to `mx_AppTileMenuBar` to be nested inside it
  res/css/views/rooms/_AppsDrawer.pcss
Labels: Z-Community-PR, T-Task

#10880 Add string for membership event where both displayname & avatar change
  src/TextForEvent.tsx
  src/i18n/strings/en_EN.json
  test/TextForEvent-test.ts
Labels: T-Defect

#10883 DeviceListener: replace calls to deprecated APIs
  src/DeviceListener.ts
  test/DeviceListener-test.ts
Labels: T-Task

#10757 Enable pagination for overlay timelines
  package.json
  src/components/structures/TimelinePanel.tsx
  test/components/structures/TimelinePanel-test.tsx
  test/test-utils/test-utils.ts
  yarn.lock
Labels: T-Enhancement

#10807 Add a snapshot for `RoomHeaderButtons`
  test/components/views/right_panel/RoomHeaderButtons-test.tsx
  test/components/views/right_panel/__snapshots__/RoomHeaderButtons-test.tsx.snap
Labels: Z-Community-PR, T-Task

#10896 Fix ResizeHandle of the third pinned widget
  src/components/structures/LoggedInView.tsx
  src/components/views/elements/ResizeHandle.tsx
  src/components/views/rooms/AppsDrawer.tsx
Labels: Z-Community-PR, T-Defect

#10890 Merge `theme-choice-panel.spec.ts` with `appearance-user-settings-tab.spec.ts`
  cypress/e2e/settings/appearance-user-settings-tab.spec.ts
  cypress/e2e/settings/theme-choice-panel.spec.ts
Labels: Z-Community-PR, T-Task

#10856 Conform _AppsDrawer.pcss to the naming policy - AppDrawer variants
  res/css/views/rooms/_AppsDrawer.pcss
  src/components/views/rooms/AppsDrawer.tsx
Labels: Z-Community-PR, T-Task

#10884 Fix cypress test in spotlight tests
  cypress/e2e/spotlight/spotlight.spec.ts
Labels: T-Task

#10745 Fix class name of the read marker on `MessagePanel`
  cypress/e2e/audio-player/audio-player.spec.ts
  cypress/e2e/permalinks/permalinks.spec.ts
  cypress/e2e/polls/polls.spec.ts
  cypress/e2e/right-panel/file-panel.spec.ts
  cypress/e2e/threads/threads.spec.ts
  cypress/e2e/timeline/timeline.spec.ts
  res/css/_components.pcss
  res/css/structures/_MessagePanel.pcss
  res/css/structures/_RoomView.pcss
  src/components/structures/MessagePanel.tsx
  test/components/structures/MessagePanel-test.tsx
Labels: Z-Community-PR, T-Task, X-Needs-Percy

#10886 Make widgets take up the full height of the PiP again
  res/css/views/rooms/_AppsDrawer.pcss
Labels: T-Task

#10809 Fix timeline search bar being overlapped by the right panel
  cypress/e2e/timeline/timeline.spec.ts
  res/css/views/rooms/_SearchBar.pcss
Labels: Z-Community-PR, T-Defect

#10900 Fix aria-required-children axe violation
  cypress/e2e/invite/invite-dialog.spec.ts
  src/components/views/rooms/RoomSublist.tsx
Labels: T-Enhancement

#10864 Send correct receipts when viewing a room
  cypress/e2e/read-receipts/read-receipts.spec.ts
  src/components/structures/TimelinePanel.tsx
  test/components/structures/TimelinePanel-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Defect

#10868 Ignore edits in message previews when they concern messages other than latest
  src/stores/room-list/MessagePreviewStore.ts
  test/stores/room-list/MessagePreviewStore-test.ts
Labels: T-Defect

#10907 Remove default margin and padding from `mx_TabbedView_tabLabels`
  res/css/structures/_TabbedView.pcss
Labels: Z-Community-PR, T-Task

#10885 Use new `getCrossSigningKeyId` instead of old `getCrossSigningId`
  src/DeviceListener.ts
  src/rageshake/submit-rageshake.ts
  src/stores/SetupEncryptionStore.ts
  src/verification.ts
  test/DeviceListener-test.ts
Labels: T-Task

#10773 Use semantic headings in user settings Labs
  res/css/_components.pcss
  res/css/components/views/settings/shared/_SettingsSubsection.pcss
  res/css/views/beta/_BetaCard.pcss
  res/css/views/elements/_SettingsFlag.pcss
  res/css/views/settings/tabs/user/_LabsUserSettingsTab.pcss
  src/components/views/settings/shared/SettingsSubsection.tsx
  src/components/views/settings/tabs/SettingsTab.tsx
  src/components/views/settings/tabs/user/LabsUserSettingsTab.tsx
  test/components/views/settings/tabs/user/LabsUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/LabsUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#10808 Replace Sass variables with custom properties - `mx_Indicator`
  res/css/structures/_RightPanel.pcss
  res/css/structures/_RoomView.pcss
  res/css/views/rooms/_RoomHeader.pcss
Labels: Z-Community-PR, T-Task, X-Needs-Percy

#10824 Split `mx_AppPermissionWarning` on `_AppsDrawer.pcss` into two classes
  res/css/_components.pcss
  res/css/components/views/elements/_AppPermission.pcss
  res/css/views/rooms/_AppsDrawer.pcss
  src/components/views/elements/AppPermission.tsx
  src/components/views/elements/AppWarning.tsx
Labels: Z-Community-PR, T-Task, X-Needs-Percy

#10912 Let TimelinePanel only send a receipt if there is an event
  src/components/structures/TimelinePanel.tsx
  test/components/structures/TimelinePanel-test.tsx
Labels: X-Release-Blocker, T-Task

#10852 RTE plain text mentions as pills
  cypress/e2e/composer/composer.spec.ts
  src/Typeguards.ts
  src/components/views/rooms/wysiwyg_composer/hooks/usePlainTextListeners.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
  test/components/views/rooms/wysiwyg_composer/hooks/usePlainTextListeners-test.tsx
  test/components/views/rooms/wysiwyg_composer/hooks/useSuggestion-test.tsx
Labels: T-Enhancement

#10908 Add intercept of `config.json`
  cypress/e2e/login/login.spec.ts
  cypress/e2e/register/register.spec.ts
  cypress/fixtures/matrix-org-client-login.json
  cypress/fixtures/matrix-org-client-well-known.json
  cypress/fixtures/vector-im-identity-v2.json
  cypress/support/axe.ts
  cypress/support/config.json.ts
  cypress/support/e2e.ts
  cypress/support/network.ts
Labels: T-Task

#10914 Make `Privacy Notice` external link on integration manager ToS clickable
  res/css/views/dialogs/_TermsDialog.pcss
  src/components/views/dialogs/TermsDialog.tsx
Labels: Z-Community-PR, T-Defect

#10857 Make more of the codebase conform to strict types
  src/AddThreepid.ts
  src/ContentMessages.ts
  src/IdentityAuthClient.tsx
  src/Notifier.ts
  src/SlidingSyncManager.ts
  src/accessibility/KeyboardShortcutUtils.ts
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/boundThreepids.ts
  src/components/structures/FilePanel.tsx
  src/components/structures/GenericDropdownMenu.tsx
  src/components/structures/ScrollPanel.tsx
  src/components/structures/auth/CompleteSecurity.tsx
  src/components/structures/auth/Login.tsx
  src/components/structures/auth/SetupEncryptionBody.tsx
  src/components/structures/auth/SoftLogout.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/dialogs/ConfirmSpaceUserActionDialog.tsx
  src/components/views/dialogs/InfoDialog.tsx
  src/components/views/dialogs/MessageEditHistoryDialog.tsx
  src/components/views/dialogs/ServerPickerDialog.tsx
  src/components/views/dialogs/devtools/Event.tsx
  src/components/views/dialogs/security/SetupEncryptionDialog.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/elements/AppPermission.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/elements/Field.tsx
  src/components/views/elements/InteractiveTooltip.tsx
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
  src/components/views/rooms/RoomSublist.tsx
  src/components/views/rooms/SearchBar.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/components/views/settings/tabs/user/KeyboardUserSettingsTab.tsx
  src/editor/dom.ts
  src/editor/history.ts
  src/hooks/usePublicRoomDirectory.ts
  src/indexing/EventIndex.ts
  src/stores/SetupEncryptionStore.ts
  src/theme.ts
  src/utils/IdentityServerUtils.ts
  src/utils/Timer.ts
  src/utils/beacon/useOwnLiveBeacons.ts
  test/editor/mock.ts
  test/editor/position-test.ts
  test/stores/SetupEncryptionStore-test.ts
Labels: T-Task

#10899 Destroy idb worker when stopping client
  src/Lifecycle.ts
  src/MatrixClientPeg.ts
Labels: T-Task

#10821 Deprecate `mx_RightPanel_headerButton` class
  cypress/e2e/room/room-header.spec.ts
  cypress/e2e/threads/threads.spec.ts
  res/css/structures/_RightPanel.pcss
  res/css/views/rooms/_RoomHeader.pcss
  src/components/views/right_panel/HeaderButton.tsx
  src/components/views/right_panel/RoomHeaderButtons.tsx
  test/components/views/right_panel/RoomHeaderButtons-test.tsx
  test/components/views/right_panel/__snapshots__/RoomHeaderButtons-test.tsx.snap
Labels: Z-Community-PR, T-Task

#10924 Remove a duplicate external link icon from `AnalyticsLearnMoreDialog`
  res/css/views/dialogs/_AnalyticsLearnMoreDialog.pcss
  src/components/views/dialogs/AnalyticsLearnMoreDialog.tsx
Labels: X-Release-Blocker, Z-Community-PR, T-Defect, backport staging

#10794 Use semantic headings in user settings Preferences
  cypress/e2e/settings/preferences-user-settings-tab.spec.ts
  res/css/_components.pcss
  res/css/views/settings/tabs/user/_PreferencesUserSettingsTab.pcss
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  test/components/views/settings/tabs/user/__snapshots__/PreferencesUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#10793 Use semantic headings in user settings Keyboard
  res/css/views/settings/tabs/user/_KeyboardUserSettingsTab.pcss
  src/components/views/settings/tabs/user/KeyboardUserSettingsTab.tsx
  test/components/views/settings/tabs/user/__snapshots__/KeyboardUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#10837 Use semantic headings in user settings - integrations and account deletion
  cypress/e2e/settings/general-user-settings-tab.spec.ts
  res/css/views/settings/_SetIntegrationManager.pcss
  src/components/views/settings/SetIntegrationManager.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/tabs/user/GeneralUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/GeneralUserSettingsTab-test.tsx.snap
Labels: X-Release-Blocker, T-Enhancement, backport staging

#10916 Fix widget permission tooltip style rules by applying the naming policy properly
  res/css/components/views/elements/_AppPermission.pcss
  src/components/views/elements/AppPermission.tsx
Labels: Z-Community-PR, T-Task

#10930 Remove `url` npm dependency and use Web URL constructor
  package.json
  src/ScalarAuthClient.ts
  src/components/views/dialogs/TermsDialog.tsx
  src/components/views/elements/AppPermission.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/settings/SetIdServer.tsx
  src/integrations/IntegrationManagerInstance.ts
  src/integrations/IntegrationManagers.ts
  src/utils/UrlUtils.ts
  src/utils/WidgetUtils.ts
  test/components/views/elements/AppTile-test.tsx
  test/utils/UrlUtils-test.ts
  yarn.lock
Labels: T-Task

#10901 Fix roving tab index getting confused after dragging space order
  src/accessibility/RovingTabIndex.tsx
  src/components/views/spaces/SpacePanel.tsx
  test/components/views/spaces/SpacePanel-test.tsx
Labels: T-Defect

#10447 Hide empty `MessageActionBar` on message edit history dialog
  src/components/views/messages/EditHistoryMessage.tsx
Labels: Z-Community-PR, T-Defect

#10876 Replace Sass variable with CSS custom property: --selected-message-border-width
  res/css/_common.pcss
  res/css/views/rooms/_EventTile.pcss
Labels: Z-Community-PR, T-Task

#10937 Check spec version for MSC3827.
  src/settings/Settings.tsx
Labels: T-Task

#10932 Fix big emoji in replies
  src/HtmlUtils.tsx
  test/HtmlUtils-test.tsx
  test/__snapshots__/HtmlUtils-test.tsx.snap
Labels: T-Defect

#10888 Update `_AuxPanel.pcss`
  res/css/structures/_RoomView.pcss
  res/css/views/rooms/_AuxPanel.pcss
  src/components/views/rooms/AuxPanel.tsx
Labels: Z-Community-PR, T-Task

#10934 Edit `room-header.spec.ts` to check apps button
  cypress/e2e/room/room-header.spec.ts
  src/components/views/rooms/RoomHeader.tsx
Labels: Z-Community-PR, T-Task

#10941 Minor cleanups to `handleVerificationRequest` in cypress tests
  cypress/e2e/crypto/decryption-failure.spec.ts
  cypress/e2e/crypto/utils.ts
Labels: T-Task

#10943 Deflake `spotlight` cypress tests
  cypress/e2e/spotlight/spotlight.spec.ts
Labels: T-Task

#10774 Use semantic headings in user settings Security
  res/css/views/settings/_CryptographyPanel.pcss
  res/css/views/settings/tabs/_SettingsTab.pcss
  res/css/views/settings/tabs/user/_SecurityUserSettingsTab.pcss
  src/components/views/settings/CrossSigningPanel.tsx
  src/components/views/settings/CryptographyPanel.tsx
  src/components/views/settings/E2eAdvancedPanel.tsx
  src/components/views/settings/EventIndexPanel.tsx
  src/components/views/settings/SecureBackupPanel.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  test/components/views/settings/CrossSigningPanel-test.tsx
  test/components/views/settings/EventIndexPanel-test.tsx
  test/components/views/settings/__snapshots__/CrossSigningPanel-test.tsx.snap
  test/components/views/settings/__snapshots__/EventIndexPanel-test.tsx.snap
  test/components/views/settings/__snapshots__/SecureBackupPanel-test.tsx.snap
Labels: T-Enhancement

#10782 Use semantic heading in user settings Sidebar & Voip
  res/css/_components.pcss
  res/css/structures/_QuickSettingsButton.pcss
  res/css/views/settings/tabs/user/_SidebarUserSettingsTab.pcss
  res/css/views/settings/tabs/user/_VoiceUserSettingsTab.pcss
  res/img/element-icons/home.svg
  res/img/element-icons/room/members.svg
  res/img/element-icons/roomlist/favorite.svg
  res/img/element-icons/roomlist/hash-circle.svg
  src/components/views/settings/tabs/user/SidebarUserSettingsTab.tsx
  src/components/views/settings/tabs/user/VoiceUserSettingsTab.tsx
  test/components/views/settings/tabs/user/SidebarUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SidebarUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#10874 Fix: flaky percy test "Rendering permalinks"
  cypress/e2e/permalinks/permalinks.spec.ts
Labels: T-Task

#10945 StickerPicker: update when accountdata is updated
  src/components/views/rooms/Stickerpicker.tsx
Labels: T-Defect

#10944 shieldStatusForRoom: avoid deprecated MatrixClient methods
  src/utils/ShieldUtils.ts
  src/utils/arrays.ts
  test/utils/ShieldUtils-test.ts
Labels: T-Task

#10951 Cypress: allow enabling Rust Crypto via env var
  cypress/support/config.json.ts
  docs/cypress.md
Labels: T-Task

#10950 Ensure that open message context menus are updated when the event is sent
  src/components/views/context_menus/MessageContextMenu.tsx
Labels: T-Defect

#10827 Use semantic headings in user settings Appearance
  cypress/e2e/audio-player/audio-player.spec.ts
  cypress/e2e/settings/appearance-user-settings-tab.spec.ts
  res/css/_components.pcss
  res/css/views/elements/_EventTilePreview.pcss
  res/css/views/settings/_FontScalingPanel.pcss
  res/css/views/settings/_ImageSizePanel.pcss
  res/css/views/settings/_LayoutSwitcher.pcss
  res/css/views/settings/_ThemeChoicePanel.pcss
  res/css/views/settings/tabs/user/_AppearanceUserSettingsTab.pcss
  res/themes/light-high-contrast/css/_light-high-contrast.pcss
  src/components/views/settings/FontScalingPanel.tsx
  src/components/views/settings/ImageSizePanel.tsx
  src/components/views/settings/LayoutSwitcher.tsx
  src/components/views/settings/ThemeChoicePanel.tsx
  src/components/views/settings/tabs/user/AppearanceUserSettingsTab.tsx
  test/components/views/settings/__snapshots__/FontScalingPanel-test.tsx.snap
  test/components/views/settings/__snapshots__/ThemeChoicePanel-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#10949 Remove an obsolete CSS file - `_ChatCreateOrReuseChatDialog.pcss`
  res/css/_components.pcss
  res/css/views/dialogs/_ChatCreateOrReuseChatDialog.pcss
Labels: Z-Community-PR, T-Task

#10875 Apply `strictNullChecks` to `src/components/views/rooms/*`
  src/components/views/rooms/AppsDrawer.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/PinnedEventTile.tsx
  src/components/views/rooms/ReadReceiptMarker.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/components/views/rooms/ThirdPartyMemberInfo.tsx
  test/components/views/rooms/EditMessageComposer-test.tsx
  test/components/views/rooms/PinnedEventTile-test.tsx
  test/components/views/rooms/RoomPreviewBar-test.tsx
  test/components/views/rooms/ThirdPartyMemberInfo-test.tsx
  test/components/views/rooms/__snapshots__/PinnedEventTile-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
  test/components/views/rooms/__snapshots__/ThirdPartyMemberInfo-test.tsx.snap
Labels: T-Task

#10786 Replace a Sass variable with a CSS custom property - hover-transition
  res/css/_animations.pcss
  res/css/_common.pcss
  res/css/views/settings/_AvatarSetting.pcss
Labels: Z-Community-PR, T-Task

#10955 Use `Icon` component for icons on AppTile's menu bar
  cypress/e2e/widgets/layout.spec.ts
  res/css/views/rooms/_AppsDrawer.pcss
  res/img/element-icons/maximise-expand.svg
  res/img/element-icons/minimise-collapse.svg
  res/img/element-icons/room/ellipsis.svg
  res/img/feather-customised/widget/external-link.svg
  src/components/views/elements/AppTile.tsx
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
Labels: Z-Community-PR, T-Task

#10961 Cypress: workaround for EventTile being remounted
  cypress/e2e/audio-player/audio-player.spec.ts
Labels: T-Task

#10929 Switch from cheerio to DOMParser
  package.json
  src/HtmlUtils.tsx
  src/editor/serialize.ts
  test/HtmlUtils-test.tsx
  test/__snapshots__/HtmlUtils-test.tsx.snap
  test/editor/serialize-test.ts
  yarn.lock
Labels: T-Task

#10209 Pass device id to widgets
  package.json
  src/components/views/elements/AppPermission.tsx
  src/i18n/strings/en_EN.json
  src/stores/widgets/StopGapWidget.ts
  test/stores/widgets/StopGapWidget-test.ts
  yarn.lock
Labels: Z-Community-PR, T-Enhancement

#10960 Fix: content overflow in settings subsection
  res/css/components/views/settings/shared/_SettingsSubsection.pcss
  res/css/views/settings/_LayoutSwitcher.pcss
Labels: T-Defect

#10959 Use semantic headings in user settings - spellcheck and language
  res/css/views/settings/_SpellCheckLanguages.pcss
  res/css/views/settings/tabs/user/_GeneralUserSettingsTab.pcss
  src/components/views/settings/SpellCheckSettings.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
Labels: T-Enhancement

#10838 Use semantic headings in user settings - discovery
  res/css/structures/_RoomStatusBar.pcss
  res/css/views/settings/_SetIdServer.pcss
  res/css/views/settings/_SettingsFieldset.pcss
  res/css/views/settings/tabs/user/_GeneralUserSettingsTab.pcss
  res/img/feather-customised/warning-triangle.svg
  src/components/structures/RoomStatusBar.tsx
  src/components/views/settings/SetIdServer.tsx
  src/components/views/settings/SettingsFieldset.tsx
  src/components/views/settings/discovery/EmailAddresses.tsx
  src/components/views/settings/discovery/PhoneNumbers.tsx
  src/components/views/settings/shared/SettingsSubsection.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  test/components/views/settings/__snapshots__/SettingsFieldset-test.tsx.snap
  test/components/views/settings/discovery/EmailAddresses-test.tsx
  test/components/views/settings/discovery/PhoneNumbers-test.tsx
  test/components/views/settings/discovery/__snapshots__/EmailAddresses-test.tsx.snap
  test/components/views/settings/discovery/__snapshots__/PhoneNumbers-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/SecurityRoomSettingsTab-test.tsx.snap
  test/components/views/spaces/__snapshots__/SpaceSettingsVisibilityTab-test.tsx.snap
Labels: T-Enhancement

#10925 Add `security-user-settings-tab.spec.ts`
  cypress/e2e/settings/security-user-settings-tab.spec.ts
Labels: Z-Community-PR, T-Task
