Repository matrix-org/matrix-react-sdk, pull requests merged in 2023-07, with the labels that each got.

#11170 Fix font-family definition for emojis
  res/css/_common.pcss
Labels: T-Defect

#11066 Do not trim trailing whitespaces for test snapshots
  .editorconfig
Labels: T-Task

#11177 Fix markdown content spacing
  res/css/_common.pcss
  res/css/views/rooms/_EventTile.pcss
Labels: T-Defect

#11181 Make event info size consistent with state events
  res/css/views/right_panel/_TimelineCard.pcss
Labels: T-Defect

#11160 Inhibit url previews on MXIDs containing slashes same as those without
  src/components/views/messages/TextualBody.tsx
Labels: T-Defect

#11187 Add isLocation to ComposerEvent analytics events
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/components/views/rooms/wysiwyg_composer/utils/message.ts
Labels: T-Defect

#11168 munge the emoji names from rust-sdk to match translations
  src/components/views/verification/VerificationShowSas.tsx
Labels: T-Task

#11179 Conform more of the codebase to strictNullChecks + noImplicitAny
  src/AddThreepid.ts
  src/Lifecycle.ts
  src/Login.ts
  src/MatrixClientPeg.ts
  src/components/structures/InteractiveAuth.tsx
  src/components/structures/auth/Registration.tsx
  src/components/views/dialogs/DeactivateAccountDialog.tsx
  src/components/views/dialogs/InteractiveAuthDialog.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/components/views/settings/devices/deleteDevices.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/MatrixChat-test.tsx
  test/components/structures/auth/Login-test.tsx
  test/components/views/dialogs/InteractiveAuthDialog-test.tsx
  test/components/views/rooms/RoomPreviewBar-test.tsx
  test/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
Labels: T-Task

#11186 Tweak branch matching to allow not applying outside of PRs for matrix-analytics-events
  scripts/ci/install-deps.sh
  scripts/ci/layered.sh
  scripts/fetchdep.sh
Labels: T-Task

#11190 Revert "Add isLocation to ComposerEvent analytics events"
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/components/views/rooms/wysiwyg_composer/utils/message.ts
Labels: T-Task

#11189 Compound Typography pass regression fixes
  res/css/components/views/settings/shared/_SettingsSubsection.pcss
  res/css/views/rooms/_RoomTile.pcss
  res/css/views/settings/_NotificationSettings2.pcss
  res/css/views/settings/tabs/_SettingsSection.pcss
  src/components/views/dialogs/BaseDialog.tsx
  src/components/views/rooms/RoomTileSubtitle.tsx
  src/components/views/settings/shared/SettingsSection.tsx
  test/components/structures/__snapshots__/MatrixChat-test.tsx.snap
  test/components/views/dialogs/UserSettingsDialog-test.tsx
  test/components/views/dialogs/__snapshots__/ChangelogDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/DevtoolsDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ExportDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/FeedbackDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ManualDeviceKeyVerificationDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/MessageEditHistoryDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ServerPickerDialog-test.tsx.snap
  test/components/views/dialogs/security/__snapshots__/CreateKeyBackupDialog-test.tsx.snap
  test/components/views/dialogs/security/__snapshots__/ImportE2eKeysDialog-test.tsx.snap
  test/components/views/settings/notifications/__snapshots__/Notifications2-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/AdvancedRoomSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/BridgeSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/SecurityRoomSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/GeneralUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/KeyboardUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/LabsUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/MjolnirUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/PreferencesUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SecurityUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SidebarUserSettingsTab-test.tsx.snap
  test/components/views/spaces/__snapshots__/AddExistingToSpaceDialog-test.tsx.snap
  test/components/views/spaces/__snapshots__/SpaceSettingsVisibilityTab-test.tsx.snap
Labels: T-Task

#11178 Scope smaller font size to user info panel
  res/css/views/right_panel/_BaseCard.pcss
  res/css/views/right_panel/_UserInfo.pcss
Labels: T-Defect

#11185 Fix: hide unsupported login elements
  src/components/structures/auth/Login.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/auth/Login-test.tsx
Labels: T-Defect

#11175 OIDC: tweak static client config shape
  src/IConfigOptions.ts
  src/Login.ts
  src/utils/oidc/registerClient.ts
  test/components/structures/auth/Login-test.tsx
  test/utils/oidc/registerClient-test.ts
Labels: T-Task

#11180 Consider more user inputs when calculating zxcvbn score
  src/components/views/auth/PassphraseField.tsx
  src/components/views/auth/RegistrationForm.tsx
  src/utils/PasswordScorer.ts
Labels: T-Enhancement

#11191 Conform more of the codebase to strict types
  src/ScalarMessaging.ts
  src/SlashCommands.tsx
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/structures/auth/Registration.tsx
  src/components/views/dialogs/ChangelogDialog.tsx
  src/components/views/dialogs/LogoutDialog.tsx
  src/components/views/dialogs/ReportEventDialog.tsx
  src/components/views/dialogs/security/CreateCrossSigningDialog.tsx
  src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx
  src/components/views/elements/LazyRenderList.tsx
  src/components/views/elements/RoomAliasField.tsx
  src/components/views/settings/devices/deleteDevices.tsx
  src/components/views/toasts/VerificationRequestToast.tsx
  src/hooks/useLocalStorageState.ts
  src/hooks/useStateCallback.ts
  src/i18n/strings/en_EN.json
  src/settings/SettingsStore.ts
  src/utils/MultiInviter.ts
  src/utils/UserInteractiveAuth.ts
  test/components/structures/auth/Registration-test.tsx
  test/components/views/dialogs/CreateRoomDialog-test.tsx
  test/components/views/dialogs/InteractiveAuthDialog-test.tsx
  test/components/views/settings/devices/deleteDevices-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/utils/MultiInviter-test.ts
Labels: T-Task

#11192 Limit width of user menu in space panel
  res/css/structures/_SpacePanel.pcss
  res/css/structures/_UserMenu.pcss
  src/components/structures/UserMenu.tsx
  test/components/structures/__snapshots__/UserMenu-test.tsx.snap
Labels: T-Defect

#11166 Handle newlines in user pills
  src/Markdown.ts
  src/editor/serialize.ts
  test/editor/deserialize-test.ts
  test/editor/serialize-test.ts
Labels: T-Defect

#11188 Replace brittle custom function with lodash implementation
  src/utils/MessageDiffUtils.tsx
Labels: T-Task

#11194 Enable strictNullChecks and noImplicitAny
  src/components/views/dialogs/BaseDialog.tsx
  src/components/views/dialogs/ScrollableBaseModal.tsx
  tsconfig.json
Labels: T-Task

#11196 Fix room tile text clipping
  res/css/views/rooms/_RoomTile.pcss
Labels: T-Defect

#11195 Conform more of the codebase to strict typing
  src/AddThreepid.ts
  src/SlidingSyncManager.ts
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/views/rooms/RoomSublist.tsx
  src/components/views/settings/account/EmailAddresses.tsx
  src/components/views/settings/account/PhoneNumbers.tsx
  src/components/views/settings/discovery/EmailAddresses.tsx
  src/components/views/settings/discovery/PhoneNumbers.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/hooks/useSlidingSyncRoomSearch.ts
  src/stores/room-list/SlidingRoomListStore.ts
  test/stores/room-list/SlidingRoomListStore-test.ts
Labels: T-Task

#11197 Quick and dirty devtool to explore state history
  src/components/views/dialogs/devtools/BaseTool.tsx
  src/components/views/dialogs/devtools/Event.tsx
  src/components/views/dialogs/devtools/RoomState.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#11198 Fix TimelinePanel-test over-driving Thread model into compliance
  test/components/structures/TimelinePanel-test.tsx
Labels: T-Task

#11200 Enable strictPropertyInitialization
  tsconfig.json
Labels: T-Task

#7015 Change wording from avatar to profile picture
  src/SlashCommands.tsx
  src/components/views/avatars/BaseAvatar.tsx
  src/components/views/avatars/MemberAvatar.tsx
  src/components/views/elements/AppPermission.tsx
  src/components/views/elements/EventListSummary.tsx
  src/components/views/messages/EncryptionEvent.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/views/messages/EncryptionEvent-test.tsx
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/PreferencesUserSettingsTab-test.tsx.snap
  test/components/views/voip/CallView-test.tsx
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
Labels: Z-Community-PR, T-Enhancement

#11139 Remove hidden read receipts migration
  cypress/e2e/settings/hidden-rr-migration.spec.ts
  src/settings/SettingsStore.ts
Labels: T-Task

#9029 Hide URL preview if it will be empty
  src/components/views/rooms/LinkPreviewGroup.tsx
  src/components/views/rooms/LinkPreviewWidget.tsx
Labels: T-Enhancement

#11201 Enable strictFunctionTypes
  package.json
  src/@types/common.ts
  src/components/structures/LoggedInView.tsx
  src/components/structures/RoomSearchView.tsx
  src/components/structures/ScrollPanel.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/dialogs/ModuleUiDialog.tsx
  src/components/views/messages/DecryptionFailureBody.tsx
  src/components/views/messages/IBodyProps.ts
  src/components/views/messages/MAudioBody.tsx
  src/components/views/messages/MBeaconBody.tsx
  src/components/views/messages/MFileBody.tsx
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MPollEndBody.tsx
  src/components/views/messages/MVideoBody.tsx
  src/components/views/messages/MessageEvent.tsx
  src/components/views/messages/MjolnirBody.tsx
  src/components/views/messages/RedactedBody.tsx
  src/components/views/messages/UnknownBody.tsx
  src/components/views/rooms/AppsDrawer.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  src/events/EventTileFactory.tsx
  src/modules/ProxiedModuleApi.ts
  src/resizer/distributors/collapse.ts
  src/resizer/distributors/fixed.ts
  src/resizer/item.ts
  src/resizer/resizer.ts
  tsconfig.json
  yarn.lock
Labels: T-Task

#11203 Enable strictPropertyInitialization
  .github/workflows/static_analysis.yaml
  src/Lifecycle.ts
  src/PosthogAnalytics.ts
  src/components/views/auth/CaptchaForm.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/beacon/BeaconViewDialog.tsx
  src/components/views/dialogs/AddExistingToSpaceDialog.tsx
  src/components/views/dialogs/BugReportDialog.tsx
  src/components/views/dialogs/SessionRestoreErrorDialog.tsx
  src/components/views/dialogs/SlidingSyncOptionsDialog.tsx
  src/components/views/dialogs/devtools/Event.tsx
  src/components/views/dialogs/devtools/SettingExplorer.tsx
  src/components/views/dialogs/security/CreateCrossSigningDialog.tsx
  src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx
  src/components/views/directory/NetworkDropdown.tsx
  src/components/views/elements/EditableTextContainer.tsx
  src/components/views/messages/MAudioBody.tsx
  src/components/views/messages/MImageBody.tsx
  src/components/views/settings/CrossSigningPanel.tsx
  src/components/views/settings/EventIndexPanel.tsx
  src/components/views/settings/JoinRuleSettings.tsx
  src/components/views/settings/SecureBackupPanel.tsx
  src/customisations/Security.ts
  src/dispatcher/payloads/UploadPayload.ts
  src/hooks/useLocalEcho.ts
  src/i18n/strings/en_EN.json
  src/indexing/EventIndexPeg.ts
  src/sentry.ts
  src/stores/OwnBeaconStore.ts
  src/stores/RoomViewStore.tsx
  src/utils/AutoDiscoveryUtils.tsx
  src/utils/IdentityServerUtils.ts
  src/utils/beacon/geolocation.ts
  src/utils/leave-behaviour.ts
  src/utils/location/useMap.ts
  test/components/views/settings/EventIndexPanel-test.tsx
  test/stores/OwnBeaconStore-test.ts
  tsconfig.json
Labels: T-Task

#9342 feat(faq): remove keyboard shortcuts button
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
Labels: Z-Community-PR, T-Enhancement

#11173 Cypress: Use Rust crypto for the bot user in verification tests
  cypress/e2e/crypto/crypto.spec.ts
  cypress/e2e/crypto/utils.ts
  cypress/e2e/crypto/verification.spec.ts
  cypress/support/bot.ts
Labels: T-Task

#11193 OIDC: update to `oidc-client-ts` functions from js-sdk
  src/utils/AutoDiscoveryUtils.tsx
  src/utils/ValidatedServerConfig.ts
  src/utils/oidc/authorize.ts
  test/test-utils/oidc.ts
  test/utils/oidc/authorize-test.ts
Labels: T-Task

#11208 Add commented-out waitForIFrameLoad option to Element Call widget
  src/models/Call.ts
Labels: T-Task

#11210 GYU: Disable sound for DMs checkbox when DM notifications are disabled
  src/components/views/settings/notifications/NotificationSettings2.tsx
Labels: T-Defect

#11207 PosthogAnalytics unwatch settings on logout
  src/Lifecycle.ts
  src/PosthogAnalytics.ts
Labels: T-Defect

#11209 Autoapprove Element Call oidc requests
  src/stores/widgets/StopGapWidgetDriver.ts
  test/stores/widgets/WidgetPermissionStore-test.ts
Labels: T-Enhancement

#11215 Handle all permitted url schemes in linkify
  src/HtmlUtils.tsx
  src/linkify-matrix.ts
  src/utils/Reply.ts
  src/utils/UrlUtils.ts
Labels: T-Enhancement

#11199 OIDC: Log in
  src/Lifecycle.ts
  src/components/structures/MatrixChat.tsx
  src/components/structures/auth/Login.tsx
  src/i18n/strings/en_EN.json
  src/utils/oidc/authorize.ts
  test/components/structures/MatrixChat-test.tsx
  test/utils/oidc/authorize-test.ts
Labels: T-Enhancement

#11213 Linkify mxc:// URLs as links to your media repo
  src/linkify-matrix.ts
Labels: T-Enhancement

#11211 GYU: Update banner
  res/css/views/settings/tabs/_SettingsBanner.pcss
  src/components/views/settings/notifications/NotificationSettings2.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#11218 GYU: Fix issues with audible keywords without activated mentions
  src/models/notificationsettings/toNotificationSettings.ts
  test/models/notificationsettings/NotificationSettings-test.ts
  test/models/notificationsettings/pushrules_bug_keyword_only.json
Labels: T-Defect

#11224 Make checkboxes less rounded
  res/css/views/elements/_StyledCheckbox.pcss
Labels: X-Release-Blocker, T-Defect

#11217 Cypress: Add test to verify device after login
  cypress/e2e/crypto/verification.spec.ts
  cypress/support/bot.ts
Labels: T-Task

#11226 Use cypress-terminal-report
  .github/workflows/cypress.yaml
  cypress.config.ts
  cypress/plugins/index.ts
  cypress/support/e2e.ts
  package.json
  yarn.lock
Labels: T-Task

#10967 Stabilize support for MSC3952: intentional mentions
  src/components/views/rooms/SendMessageComposer.tsx
  src/settings/Settings.tsx
  test/ContentMessages-test.ts
  test/components/views/rooms/EditMessageComposer-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/components/views/rooms/VoiceRecordComposerTile-test.tsx
  test/models/notificationsettings/pushrules_bug_botnotices.json
  test/models/notificationsettings/pushrules_bug_keyword_only.json
  test/models/notificationsettings/pushrules_default.json
  test/models/notificationsettings/pushrules_default_new.json
  test/models/notificationsettings/pushrules_sample.json
  test/test-utils/pushRules.ts
Labels: T-Task

#11221 Strip emoji variation when searching emoji by emoji
  src/components/views/emojipicker/EmojiPicker.tsx
Labels: T-Defect

#11239 Improve types
  src/AddThreepid.ts
  src/PosthogAnalytics.ts
  src/components/structures/auth/ForgotPassword.tsx
  src/components/structures/auth/forgot-password/EnterEmail.tsx
  src/components/views/dialogs/DeactivateAccountDialog.tsx
  src/components/views/dialogs/devtools/RoomState.tsx
  src/components/views/messages/DownloadActionButton.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/settings/JoinRuleSettings.tsx
  src/hooks/useLocalEcho.ts
  src/utils/dm/startDm.ts
Labels: T-Task

#11244 Document `@media only percy`
  docs/cypress.md
Labels: T-Task

#11242 Fix: Flaky cypress test: `Audio player > should be rendered, play and support replying on a thread`
  cypress/e2e/audio-player/audio-player.spec.ts
Labels: T-Task

#11079 Compound color pass
  cypress/e2e/room/room-header.spec.ts
  cypress/e2e/settings/appearance-user-settings-tab.spec.ts
  cypress/e2e/threads/threads.spec.ts
  res/css/_common.pcss
  res/css/components/views/context_menus/_KebabContextMenu.pcss
  res/css/components/views/settings/devices/_DeviceExpandDetailsButton.pcss
  res/css/components/views/settings/devices/_DeviceSecurityCard.pcss
  res/css/components/views/settings/devices/_DeviceTypeIcon.pcss
  res/css/components/views/settings/devices/_FilteredDeviceListHeader.pcss
  res/css/compound/_Icon.pcss
  res/css/structures/_FilePanel.pcss
  res/css/structures/_LeftPanel.pcss
  res/css/structures/_RoomView.pcss
  res/css/structures/_SpacePanel.pcss
  res/css/structures/_UserMenu.pcss
  res/css/views/beta/_BetaCard.pcss
  res/css/views/context_menus/_IconizedContextMenu.pcss
  res/css/views/context_menus/_MessageContextMenu.pcss
  res/css/views/dialogs/_PollCreateDialog.pcss
  res/css/views/elements/_AccessibleButton.pcss
  res/css/views/elements/_GenericEventListSummary.pcss
  res/css/views/elements/_SSOButtons.pcss
  res/css/views/elements/_StyledCheckbox.pcss
  res/css/views/elements/_StyledRadioButton.pcss
  res/css/views/elements/_ToggleSwitch.pcss
  res/css/views/messages/_DisambiguatedProfile.pcss
  res/css/views/messages/_ReactionsRowButton.pcss
  res/css/views/messages/_RedactedBody.pcss
  res/css/views/messages/_TextualEvent.pcss
  res/css/views/right_panel/_BaseCard.pcss
  res/css/views/right_panel/_ThreadPanel.pcss
  res/css/views/right_panel/_UserInfo.pcss
  res/css/views/rooms/_EditMessageComposer.pcss
  res/css/views/rooms/_EmojiButton.pcss
  res/css/views/rooms/_EntityTile.pcss
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/_MessageComposer.pcss
  res/css/views/rooms/_RoomHeader.pcss
  res/css/views/rooms/_RoomSublist.pcss
  res/css/views/rooms/_ThreadSummary.pcss
  res/css/views/rooms/wysiwyg_composer/_EditWysiwygComposer.pcss
  res/css/views/rooms/wysiwyg_composer/components/_FormattingButtons.pcss
  res/css/views/settings/_FontScalingPanel.pcss
  res/css/views/settings/_KeyboardShortcut.pcss
  res/css/views/settings/_LayoutSwitcher.pcss
  res/css/views/settings/_ThemeChoicePanel.pcss
  res/css/views/voip/_CallView.pcss
  res/themes/dark/css/_dark.pcss
  res/themes/legacy-dark/css/_legacy-dark.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light-custom/css/_custom.pcss
  res/themes/light-high-contrast/css/_light-high-contrast.pcss
  res/themes/light/css/_light.pcss
  res/themes/light/css/light.pcss
Labels: T-Enhancement

#11172 Integration work for rich text editor 2.3.1
  package.json
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/wysiwyg_composer/DynamicImportWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/usePlainTextInitialization.ts
  src/components/views/rooms/wysiwyg_composer/hooks/usePlainTextListeners.ts
  src/components/views/rooms/wysiwyg_composer/utils/createMessageContent.ts
  yarn.lock
Labels: T-Enhancement

#11252 Fix event info events size and color
  res/css/views/messages/_RoomAvatarEvent.pcss
  res/css/views/rooms/_EventTile.pcss
  src/components/views/messages/RoomAvatarEvent.tsx
Labels: T-Defect

#11255 Make event highliht use primary content token
  res/css/views/rooms/_EventTile.pcss
Labels: T-Defect

#11241 Replace `getQRCodeBytes` with `generateQRCode`
  src/components/views/elements/QRCode.tsx
  src/components/views/elements/crypto/VerificationQRCode.tsx
  src/components/views/right_panel/VerificationPanel.tsx
  test/components/views/elements/QRCode-test.tsx
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/right_panel/VerificationPanel-test.tsx
Labels: T-Task

#11253 Allow emoji presentation selector to not break BigEmoji styling
  src/HtmlUtils.tsx
Labels: T-Defect

#11202 Restoring optional ligatures by resetting letter-spacing
  res/css/_common.pcss
Labels: T-Defect

#11258 Disable failing login with SSSS tests running against rust crypto
  cypress/e2e/crypto/verification.spec.ts
Labels: T-Task

#11238 Fix jest/valid-expects lints
  .eslintrc.js
  test/components/views/dialogs/ConfirmRedactDialog-test.tsx
  test/components/views/dialogs/CreateRoomDialog-test.tsx
  test/components/views/dialogs/DevtoolsDialog-test.tsx
  test/components/views/right_panel/UserInfo-test.tsx
  test/utils/oidc/authorize-test.ts
  test/utils/oidc/registerClient-test.ts
Labels: T-Task

#11261 Deprecate camelCase config options
  src/utils/SnakedObject.ts
Labels: T-Deprecation

#11263 Fix clicking MXID in timeline going to matrix.to
  src/linkify-matrix.ts
  test/linkify-matrix-test.ts
Labels: T-Defect

#11259 Split join and goto slash commands, the latter shouldn't auto_join
  src/SlashCommands.tsx
  src/i18n/strings/en_EN.json
  src/slash-commands/join.ts
  test/SlashCommands-test.tsx
Labels: T-Enhancement

#11256 Offer to unban user during invite if inviter has sufficient permissions
  src/i18n/strings/en_EN.json
  src/utils/MultiInviter.ts
  test/utils/MultiInviter-test.ts
Labels: T-Enhancement

#10947 Fix: cypress `findByTestId` and `percySnapshotElement` do not work together
  cypress/support/percy.ts
Labels: T-Task

#11269 Fix missing metaspace notification badges
  src/components/views/spaces/SpaceTreeLevel.tsx
  test/components/views/spaces/SpaceTreeLevel-test.tsx
  test/components/views/spaces/__snapshots__/SpaceTreeLevel-test.tsx.snap
Labels: X-Release-Blocker, T-Defect, backport staging

#11254 Prevent user from accidentally double clicking user info admin actions
  src/components/views/right_panel/UserInfo.tsx
  test/components/views/right_panel/UserInfo-test.tsx
Labels: T-Defect

#11266 Switch to the new `session` API for screen-sharing
  src/components/views/elements/DesktopCapturerSourcePicker.tsx
  src/components/views/voip/LegacyCallView.tsx
  src/models/Call.ts
  src/stores/widgets/ElementWidgetActions.ts
  test/models/Call-test.ts
Labels: T-Task

#11272 Fix log spam during cypress CI
  .github/workflows/cypress.yaml
Labels: T-Task

#11223 Switch to updating presence via /sync calls instead of PUT /presence
  src/Presence.ts
Labels: T-Enhancement

#11267 Increase timeout for wysiwyg composer test due to wasm being slow in CI
  test/components/views/rooms/wysiwyg_composer/SendWysiwygComposer-test.tsx
Labels: T-Task

#11274 Fix room view not properly maintaining scroll position
  src/components/structures/RoomView.tsx
Labels: T-Defect

#11273 Fix colour regressions
  res/css/views/messages/_MNoticeBody.pcss
  res/css/views/messages/_MediaBody.pcss
  res/css/views/rooms/_EventTile.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light/css/_light.pcss
Labels: T-Defect

#11257 Hide widget menu button if it there are no options available
  src/components/views/context_menus/WidgetContextMenu.tsx
  src/components/views/elements/AppTile.tsx
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
Labels: T-Defect

#11275 Replace sinon fake timers with jest timers
  package.json
  test/UserActivity-test.ts
  test/components/structures/MessagePanel-test.tsx
Labels: T-Task

#11278 Remove reply fallback from notifications
  src/Notifier.ts
  test/Notifier-test.ts
Labels: T-Defect

#9556 Do not filter users post search
  cypress/e2e/spotlight/spotlight.spec.ts
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  test/components/views/dialogs/SpotlightDialog-test.tsx
Labels: Z-Community-PR, T-Enhancement

#11280 Update sliding sync proxy image for cypress
  cypress.config.ts
Labels: T-Task

#11279 Fix layout of sessions tab buttons
  res/css/components/views/settings/devices/_FilteredDeviceListHeader.pcss
Labels: T-Defect

#11285 Fix voice call tile size
  res/css/views/messages/_LegacyCallEvent.pcss
Labels: T-Defect

#11284 Fix bubble message layout avatar overlap
  res/css/views/messages/_DisambiguatedProfile.pcss
Labels: T-Defect

#11287 Restore offline presence badge color
  res/themes/light-high-contrast/css/_light-high-contrast.pcss
  res/themes/light/css/_light.pcss
Labels: T-Defect

#11281 Enable Cypress experimentalMemoryManagement
  cypress.config.ts
Labels: T-Task

#11293 Update jest snapshot
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
Labels: T-Task

#11294 Fix over-simplified cypress test
  cypress/e2e/read-receipts/read-receipts.spec.ts
Labels: T-Task

#11243 Jest test coverage for `Lifecycle.persistCredentials`
  test/Lifecycle-test.ts
Labels: T-Task

#11212 Try to find out the Matrix homeserver version and include in rageshakes
  src/components/views/dialogs/devtools/ServerInfo.tsx
  src/rageshake/submit-rageshake.ts
Labels: T-Task

#11286 Fix changelog dialog heading size
  src/components/views/dialogs/ChangelogDialog.tsx
  test/components/views/dialogs/__snapshots__/ChangelogDialog-test.tsx.snap
Labels: T-Defect

#11248 Allow setting room join rule to knock
  src/components/views/dialogs/RoomUpgradeWarningDialog.tsx
  src/components/views/settings/JoinRuleSettings.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/JoinRuleSettings-test.tsx
Labels: Z-Community-PR, T-Enhancement

#11298 Don't show composer send button if user cannot send
  src/components/views/rooms/MessageComposer.tsx
Labels: T-Defect

#11297 Only error log url preview failure if not 404 matrix error
  src/components/views/rooms/LinkPreviewGroup.tsx
Labels: T-Task

#11300 Restore room list backdrop
  res/css/structures/_LeftPanel.pcss
  res/themes/dark/css/_dark.pcss
  res/themes/legacy-dark/css/_legacy-dark.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light/css/_light.pcss
Labels: T-Task

#11302 OIDC: Persist details in session storage, create store
  package.json
  src/Lifecycle.ts
  src/contexts/SDKContext.ts
  src/stores/oidc/OidcClientStore.ts
  src/utils/oidc/authorize.ts
  src/utils/oidc/persistOidcSettings.ts
  test/components/structures/MatrixChat-test.tsx
  test/contexts/SdkContext-test.ts
  test/stores/oidc/OidcClientStore-test.ts
  test/utils/oidc/authorize-test.ts
  test/utils/oidc/persistOidcSettings-test.ts
Labels: T-Enhancement

#9712 Don't hide room header buttons in video rooms and rooms with a call
  cypress/e2e/room/room-header.spec.ts
  src/components/structures/RoomView.tsx
Labels: T-Enhancement

#11299 Fix blockquote colour contrast
  res/css/_common.pcss
  res/css/views/rooms/_EventTile.pcss
Labels: T-Enhancement

#11307 Avoid warning about config.json fallback keys more than once
  src/utils/SnakedObject.ts
Labels: T-Task

#11308 Fix invite dialog showing the same user multiple times
  src/components/views/dialogs/InviteDialog.tsx
  test/components/views/dialogs/InviteDialog-test.tsx
Labels: T-Defect

#11306 Fix issues around room notification settings flaking out
  src/RoomNotifs.ts
Labels: T-Defect

#10898 Do not show "Forget room" button in Room View header for guest users
  src/components/structures/RoomView.tsx
  test/components/structures/RoomView-test.tsx
Labels: Z-Community-PR, T-Enhancement

#11312 Fix GIF label on dark theme
  res/themes/light/css/_light.pcss
Labels: X-Release-Blocker, T-Defect

#11290 Prevent re-filtering user directory results in spotlight
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  test/components/views/dialogs/SpotlightDialog-test.tsx
Labels: T-Defect

#11309 Temporarily add missing @types imports
  .github/workflows/static_analysis.yaml
  package.json
  yarn.lock
Labels: X-Release-Blocker, T-Task

#11314 Ensure consistency when rendering the sent event indicator
  src/components/structures/MessagePanel.tsx
  src/components/views/rooms/EventTile.tsx
  test/components/structures/MessagePanel-test.tsx
Labels: T-Defect

#11316 Fix peeked rooms showing up in historical
  src/stores/room-list/algorithms/Algorithm.ts
  src/utils/membership.ts
Labels: T-Defect

#11317 Add `cy.viewRoomById` command
  cypress/e2e/composer/composer.spec.ts
  cypress/support/views.ts
Labels: T-Task

#11319 Handle empty own profile
  src/stores/OwnProfileStore.ts
  test/stores/OwnProfileStore-test.ts
Labels: T-Defect

#11310 Improve notifications debug devtool
  src/components/views/dialogs/devtools/RoomNotifications.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#11315 Use correct translation function for WYSIWYG buttons
  src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
  test/components/views/rooms/wysiwyg_composer/components/FormattingButtons-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/__snapshots__/FormattingButtons-test.tsx.snap
Labels: T-Defect

#11320 Fix edge case with sent indicator being drawn when it shouldn't be
  src/components/structures/MessagePanel.tsx
  src/components/views/rooms/EventTile.tsx
  test/components/structures/MessagePanel-test.tsx
Labels: X-Release-Blocker, T-Defect

#11222 Use PassphraseFields in ExportE2eKeysDialog to enforce minimum passphrase complexity
  src/async-components/views/dialogs/security/ExportE2eKeysDialog.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/security/ExportE2eKeysDialog-test.tsx
  test/components/views/dialogs/security/__snapshots__/ExportE2eKeysDialog-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#11323 ElementR: Enable cypress test about login with SSSS to run with rust-crypto
  cypress/e2e/crypto/verification.spec.ts
Labels: T-Task

#11333 Remove display of key backup signatures from backup settings
  res/css/views/settings/_SecureBackupPanel.pcss
  src/components/views/settings/SecureBackupPanel.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/__snapshots__/SecureBackupPanel-test.tsx.snap
Labels: T-Enhancement

#11303 Unit test logout action in MatrixChat
  test/components/structures/MatrixChat-test.tsx
Labels: T-Task

#11336 Unhide the view source event toggle - it works well enough
  res/css/views/rooms/_EventTile.pcss
Labels: T-Defect

#11324 Upgrade wysiwyg editor for ctrl+backspace windows fix
  package.json
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/wysiwyg_composer/DynamicImportWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/utils/createMessageContent.ts
  yarn.lock
Labels: T-Defect

#11322 Update `SecureBackupPanel` to use `getCrypto()`
  src/components/views/settings/SecureBackupPanel.tsx
  test/components/views/settings/SecureBackupPanel-test.tsx
  test/test-utils/client.ts
Labels: T-Task

#11335 Fix disable_3pid_login being ignored for the email field
  src/components/views/auth/RegistrationForm.tsx
Labels: T-Defect

#11339 Improve comments on key-setup dialogs
  src/async-components/views/dialogs/security/CreateKeyBackupDialog.tsx
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
Labels: T-Task

#11340 De-duplicate reactions by sender to account for faulty/malicious servers
  src/components/views/messages/ReactionsRow.tsx
  src/components/views/messages/ReactionsRowButton.tsx
  src/components/views/messages/ReactionsRowButtonTooltip.tsx
Labels: T-Defect

#11342 Bump pagination sizes due to hidden events
  src/components/structures/TimelinePanel.tsx
Labels: T-Enhancement
