Repository matrix-org/matrix-react-sdk, pull requests merged in 2024-07, with the labels that each got.

#12719 Fix `Match system theme` toggle
  package.json
  playwright/e2e/settings/appearance-user-settings-tab/index.ts
  yarn.lock
Labels: T-Defect

#12709 Clear autocomplete input on selection accept
  src/components/structures/AutocompleteInput.tsx
  test/components/structures/AutocompleteInput-test.tsx
Labels: T-Defect

#12652 Disable profile controls if the HS doesn't allow them to be set
  src/components/views/settings/AvatarSetting.tsx
  src/components/views/settings/UserProfileSettings.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/UserProfileSettings-test.tsx
  test/test-utils/client.ts
Labels: T-Enhancement

#12718 Update @vector-im/compound-web
  package.json
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/theme-panel-custom-theme-added-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/theme-panel-custom-theme-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-smallscreen-linux.png
  res/css/views/settings/_UserProfileSettings.pcss
  src/components/views/settings/ThemeChoicePanel.tsx
  src/components/views/settings/UserProfileSettings.tsx
  test/components/views/settings/__snapshots__/ThemeChoicePanel-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
  yarn.lock
Labels: T-Task

#12699 Update new room header facepile tooltip
  src/i18n/strings/en_EN.json
Labels: T-Task

#12720 Disable xvfb as it is not necessary for headless mode
  .github/workflows/end-to-end-tests.yaml
Labels: T-Task

#12721 Extract `focus_search` dispatch action into enum
  src/components/structures/LoggedInView.tsx
  src/components/structures/RoomView.tsx
  src/dispatcher/actions.ts
  test/components/structures/LoggedInView-test.tsx
Labels: T-Task

#12636 Replace deprecated temporal proposal polyfill
  package.json
  src/components/views/audio_messages/Clock.tsx
  yarn.lock
Labels: T-Task

#12726 Use LTS nodejs in github workflows
  .github/workflows/end-to-end-tests.yaml
  .github/workflows/static_analysis.yaml
  .github/workflows/tests.yml
Labels: T-Task

#12663 Move the account management button
  res/css/views/settings/_UserProfileSettings.pcss
  src/components/views/settings/UserProfileSettings.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/tabs/user/GeneralUserSettingsTab-test.tsx
Labels: T-Enhancement

#12727 Flaky-test bot: reopen existing issues
  playwright/flaky-reporter.ts
Labels: T-Task

#12729 Remove references to some deprecated js-sdk identifiers
  .eslintrc.js
  src/DecryptionFailureTracker.ts
  src/async-components/views/dialogs/security/NewRecoveryMethodDialog.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/auth/SetupEncryptionBody.tsx
  src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx
  src/components/views/messages/EncryptionEvent.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/MemberTile.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/createRoom.ts
  src/customisations/Security.ts
  src/stores/SetupEncryptionStore.ts
  src/utils/crypto/index.ts
  src/utils/dm/createDmLocalRoom.ts
  test/DeviceListener-test.ts
  test/components/structures/RoomView-test.tsx
Labels: T-Task

#12582 Don't consider textual characters to be emoji
  .eslintrc.js
  src/HtmlUtils.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/editor/parts.ts
  test/HtmlUtils-test.tsx
  test/__snapshots__/HtmlUtils-test.tsx.snap
Labels: T-Defect

#10995 Prevent Element appearing in system media controls
  jest.config.ts
  package.json
  src/LegacyCallHandler.tsx
  src/Notifier.ts
  src/audio/BackgroundAudio.ts
  src/voice-broadcast/models/VoiceBroadcastRecording.ts
  test/LegacyCallHandler-test.ts
  test/Notifier-test.ts
  test/setup/mocks.ts
  test/setup/setupManualMocks.ts
  test/voice-broadcast/models/VoiceBroadcastRecording-test.ts
  yarn.lock
Labels: Z-Community-PR, T-Enhancement

#12676 New layout selector ui in user settings
  playwright/e2e/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts
  playwright/e2e/settings/appearance-user-settings-tab/index.ts
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/message-layout-panel-bubble-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/message-layout-panel-modern-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  res/css/views/settings/_LayoutSwitcher.pcss
  src/components/views/elements/EventTilePreview.tsx
  src/components/views/settings/LayoutSwitcher.tsx
  src/components/views/settings/tabs/user/AppearanceUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/LayoutSwitcher-test.tsx
  test/components/views/settings/__snapshots__/LayoutSwitcher-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#12732 Fix close button on forgot password flow
  playwright/e2e/forgot-password/forgot-password.spec.ts
  playwright/e2e/login/login.spec.ts
  playwright/e2e/utils.ts
  playwright/plugins/homeserver/index.ts
  playwright/plugins/homeserver/synapse/index.ts
  playwright/snapshots/forgot-password/forgot-password.spec.ts/forgot-password-linux.png
  playwright/snapshots/forgot-password/forgot-password.spec.ts/forgot-password-verify-email-linux.png
  res/css/_common.pcss
Labels: T-Defect

#12728 Fix closing all modals
  src/Modal.tsx
  src/components/structures/LoggedInView.tsx
  src/components/structures/MatrixChat.tsx
  test/Modal-test.ts
  test/components/structures/LoggedInView-test.tsx
  test/components/views/context_menus/RoomGeneralContextMenu-test.tsx
  test/components/views/dialogs/InviteDialog-test.tsx
  test/test-utils/utilities.ts
Labels: T-Defect

#12723 Move language settings to 'preferences'
  playwright/e2e/settings/general-user-settings-tab.spec.ts
  playwright/e2e/settings/preferences-user-settings-tab.spec.ts
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
  res/css/views/settings/tabs/user/_GeneralUserSettingsTab.pcss
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/tabs/user/PreferencesUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/PreferencesUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#12677 Redesign room search interface
  playwright/e2e/timeline/timeline.spec.ts
  playwright/snapshots/crypto/crypto.spec.ts/RoomSummaryCard-with-verified-e2ee-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-room-with-user-pill-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-room-without-user-linux.png
  playwright/snapshots/right-panel/right-panel.spec.ts/with-name-and-address-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/highlighted-search-results-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/search-aux-panel-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/search-bar-on-timeline-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/search-results-with-TextualEvent-linux.png
  res/css/_common.pcss
  res/css/_components.pcss
  res/css/views/right_panel/_RoomSummaryCard.pcss
  res/css/views/rooms/_RoomSearchAuxPanel.pcss
  res/css/views/rooms/_SearchBar.pcss
  src/components/structures/RightPanel.tsx
  src/components/structures/RoomSearchView.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/WaitingForThirdPartyRoomView.tsx
  src/components/views/elements/SearchWarning.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/RoomSearchAuxPanel.tsx
  src/components/views/rooms/SearchBar.tsx
  src/hooks/useTransition.ts
  src/i18n/strings/en_EN.json
  src/stores/right-panel/RightPanelStore.ts
  src/stores/right-panel/RightPanelStoreIPanelState.ts
  test/components/structures/RoomSearchView-test.tsx
  test/components/views/elements/SearchWarning-test.tsx
  test/components/views/elements/__snapshots__/SearchWarning-test.tsx.snap
  test/components/views/right_panel/RoomSummaryCard-test.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/rooms/RoomSearchAuxPanel-test.tsx
  test/components/views/rooms/SearchBar-test.tsx
Labels: T-Enhancement

#12738 Remove redundant call to `setCrypto`
  .eslintrc.js
  test/Lifecycle-test.ts
Labels: T-Task

#12725 Improve new room header accessibility
  res/css/views/rooms/_RoomHeader.pcss
  src/components/views/elements/FacePile.tsx
  src/components/views/rooms/RoomHeader.tsx
Labels: T-Defect

#12739 Promote new room header from labs to Beta
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/SettingsStore.ts
  test/components/views/settings/tabs/user/__snapshots__/LabsUserSettingsTab-test.tsx.snap
  test/settings/SettingsStore-test.ts
Labels: X-Release-Blocker, T-Enhancement

#12741 Split up slow Playwright tests
  playwright/e2e/composer/CIDER.spec.ts
  playwright/e2e/composer/RTE.spec.ts
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/crypto/decryption-failure-messages.spec.ts
  playwright/e2e/crypto/device-verification.spec.ts
  playwright/e2e/crypto/event-shields.spec.ts
  playwright/e2e/crypto/user-verification.spec.ts
  playwright/e2e/crypto/utils.ts
  playwright/e2e/read-receipts/editing-messages-in-threads.spec.ts
  playwright/e2e/read-receipts/editing-messages-main-timeline.spec.ts
  playwright/e2e/read-receipts/editing-messages-thread-roots.spec.ts
  playwright/e2e/read-receipts/editing-messages.spec.ts
  playwright/e2e/read-receipts/high-level.spec.ts
  playwright/e2e/read-receipts/message-ordering.spec.ts
  playwright/e2e/read-receipts/new-messages-in-threads.spec.ts
  playwright/e2e/read-receipts/new-messages-main-timeline.spec.ts
  playwright/e2e/read-receipts/new-messages-thread-roots.spec.ts
  playwright/e2e/read-receipts/notifications.spec.ts
  playwright/e2e/read-receipts/reactions-in-threads.spec.ts
  playwright/e2e/read-receipts/reactions-main-timeline.spec.ts
  playwright/e2e/read-receipts/reactions-thread-roots.spec.ts
  playwright/e2e/read-receipts/redactions-in-threads.spec.ts
  playwright/e2e/read-receipts/redactions-main-timeline.spec.ts
  playwright/e2e/read-receipts/redactions-thread-roots.spec.ts
  playwright/e2e/read-receipts/room-list-order.spec.ts
  playwright/e2e/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts
  playwright/e2e/settings/appearance-user-settings-tab/message-layout-panel.ts
  playwright/e2e/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts
  playwright/snapshots/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts/theme-panel-custom-theme-added-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts/theme-panel-custom-theme-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts/theme-panel-dark-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts/theme-panel-light-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/theme-choice-panel.spec.ts/theme-panel-match-system-enabled-linux.png
Labels: T-Task

#12755 Element-R: Report events with withheld keys separately to Posthog.
  package.json
  src/DecryptionFailureTracker.ts
  src/components/views/messages/DecryptionFailureBody.tsx
  test/DecryptionFailureTracker-test.ts
  test/components/views/messages/DecryptionFailureBody-test.tsx
  yarn.lock
Labels: T-Enhancement

#12733 Move integrations switch
  playwright/e2e/settings/general-user-settings-tab.spec.ts
  playwright/e2e/settings/security-user-settings-tab.spec.ts
  src/components/views/settings/SetIntegrationManager.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  test/components/views/settings/SetIntegrationManager-test.tsx
  test/components/views/settings/__snapshots__/SetIntegrationManager-test.tsx.snap
  test/components/views/settings/tabs/user/GeneralUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/GeneralUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SecurityUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#12761 Update wording shown when keys are withheld
  src/i18n/strings/en_EN.json
  test/components/views/messages/__snapshots__/DecryptionFailureBody-test.tsx.snap
Labels: T-Task

#12769 Use multiple workers in Playwright CI to make use of multiple cores
  playwright.config.ts
Labels: T-Task

#12770 Hide tooltips for certain playwright screenshots to avoid flakiness
  playwright/e2e/timeline/timeline.spec.ts
  playwright/element-web-test.ts
Labels: T-Task

#12706 remove "Manually verify all remote sessions" setting
  src/components/views/settings/E2eAdvancedPanel.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/controllers/OrderedMultiController.ts
  src/settings/controllers/PushToMatrixClientController.ts
  test/components/views/settings/tabs/user/__snapshots__/SecurityUserSettingsTab-test.tsx.snap
Labels: T-Task

#12764 Cleanup tasks in SecurityManager/SetupEncryptionStore
  src/SecurityManager.ts
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/stores/SetupEncryptionStore.ts
  test/test-utils/test-utils.ts
Labels: T-Task

#12765 Add logging to encryption setup
  src/SecurityManager.ts
  src/stores/SetupEncryptionStore.ts
  test/SecurityManager-test.ts
Labels: T-Task

#12760 Align `widget_build_url_ignore_dm` with call behaviour switch between 1:1 and Widget
  src/LegacyCallHandler.tsx
  src/hooks/room/useRoomCall.ts
  src/widgets/ManagedHybrid.ts
  test/LegacyCallHandler-test.ts
  test/widgets/ManagedHybrid-test.ts
Labels: T-Enhancement

#12771 Fix edge case of landing on 3pid email link with registration disabled
  src/components/structures/MatrixChat.tsx
Labels: T-Defect

#12772 Fix inability to change accent colour consistently in custom theming
  res/themes/light-custom/css/_custom.pcss
Labels: T-Defect

#12774 Fix HTML export missing a bunch of Compound variables
  package.json
  playwright/e2e/chat-export/html-export.spec.ts
  playwright/snapshots/chat-export/html-export.spec.ts/html-export-linux.png
  src/utils/exportUtils/HtmlExport.tsx
  src/utils/exportUtils/exportCSS.ts
  src/utils/exportUtils/exportCustomCSS.css
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
  yarn.lock
Labels: T-Defect

#12778 Fix HTML export test
  playwright/e2e/chat-export/html-export.spec.ts
  playwright/snapshots/chat-export/html-export.spec.ts/html-export-linux.png
Labels: T-Defect

#12743 Add test reporter to prevent stale screenshots
  .github/workflows/end-to-end-tests.yaml
  package.json
  playwright/@types/playwright-core.d.ts
  playwright/e2e/settings/general-room-settings-tab.spec.ts
  playwright/e2e/settings/preferences-user-settings-tab.spec.ts
  playwright/e2e/settings/security-user-settings-tab.spec.ts
  playwright/e2e/user-onboarding/user-onboarding-new.spec.ts
  playwright/element-web-test.ts
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/font-slider-11-darwin.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/font-slider-11-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/font-slider-21-darwin.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/font-slider-21-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/message-layout-panel-bubble-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/message-layout-panel-modern-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/hidden-event-line-padding-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/hidden-event-line-zero-padding-irc-layout-linux.png
  playwright/snapshots/user-view/user-view.spec.ts/UserView-should-render-the-user-view-as-expected-1-linux.png
  playwright/stale-screenshot-reporter.ts
  yarn.lock
Labels: T-Task

#12768 Update right panel base card styling to match Compound
  package.json
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/crypto/event-shields.spec.ts
  playwright/e2e/read-receipts/index.ts
  playwright/e2e/right-panel/right-panel.spec.ts
  playwright/e2e/threads/threads.spec.ts
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-bubble-layout-linux.png
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-group-layout-linux.png
  playwright/snapshots/right-panel/file-panel.spec.ts/empty-linux.png
  playwright/snapshots/right-panel/notification-panel.spec.ts/empty-linux.png
  playwright/snapshots/threads/threads.spec.ts/Reply-to-the-location-on-ThreadView-linux.png
  playwright/snapshots/user-view/user-view.spec.ts/user-info-linux.png
  res/css/views/right_panel/_BaseCard.pcss
  res/themes/dark/css/_dark.pcss
  res/themes/legacy-dark/css/_legacy-dark.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light/css/_light.pcss
  src/components/structures/ThreadPanel.tsx
  src/components/views/right_panel/BaseCard.tsx
  src/components/views/right_panel/UserInfo.tsx
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/components/views/rooms/__snapshots__/ThirdPartyMemberInfo-test.tsx.snap
  yarn.lock
Labels: T-Enhancement

#12713 Let Element Call widget set session memberships
  src/stores/widgets/StopGapWidgetDriver.ts
  test/stores/widgets/StopGapWidgetDriver-test.ts
Labels: T-Enhancement

#12710 Let Element Call widget receive m.room.create
  src/stores/widgets/StopGapWidgetDriver.ts
  test/stores/widgets/StopGapWidgetDriver-test.ts
Labels: T-Enhancement

#12786 Clear settings store cache on logout
  src/Lifecycle.ts
  src/settings/SettingsStore.ts
  src/settings/handlers/LocalEchoWrapper.ts
  src/settings/handlers/SettingsHandler.ts
  test/stores/WidgetLayoutStore-test.ts
Labels: T-Task

#12190 Accessibility: Add Landmark navigation
  playwright/e2e/accessibility/keyboard-navigation.spec.ts
  src/@types/global.d.ts
  src/Keyboard.ts
  src/accessibility/KeyboardShortcuts.ts
  src/accessibility/LandmarkNavigation.ts
  src/components/structures/LeftPanel.tsx
  src/components/structures/LoggedInView.tsx
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/i18n/strings/en_EN.json
  test/accessibility/LandmarkNavigation-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/KeyboardUserSettingsTab-test.tsx.snap
Labels: Z-Community-PR, T-Enhancement

#12782 Stop using the js-sdk's compare function
  src/components/views/rooms/WhoIsTypingTile.tsx
  src/components/views/settings/PowerLevelSelector.tsx
  src/integrations/IntegrationManagers.ts
  src/stores/room-list/algorithms/tag-sorting/AlphabeticAlgorithm.ts
  src/stores/widgets/WidgetLayoutStore.ts
  src/theme.ts
  test/components/views/rooms/MemberList-test.tsx
  test/integrations/IntegrationManagers-test.ts
  test/stores/WidgetLayoutStore-test.ts
  test/theme-test.ts
Labels: T-Task

#12787 Add test for the unsupported browser screen
  playwright/e2e/app-loading/feature-detection.spec.ts
  playwright/snapshots/app-loading/feature-detection.spec.ts/unsupported-browser-linux.png
Labels: T-Defect

#12791 Fix stray 'account' heading
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
Labels: T-Defect

#12792 Test for lack of WebAssembly support
  playwright/e2e/app-loading/feature-detection.spec.ts
  playwright/snapshots/app-loading/feature-detection.spec.ts/unsupported-browser-CompatibilityView-linux.png
Labels: T-Defect

#12788 Update styling of UserInfo right panel card
  playwright/snapshots/user-view/user-view.spec.ts/user-info-linux.png
  res/css/views/right_panel/_UserInfo.pcss
  res/css/views/rooms/_PresenceLabel.pcss
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/PresenceLabel.tsx
  src/i18n/strings/en_EN.json
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
Labels: T-Enhancement

#12796 Iterate design of right panel empty state
  playwright/e2e/right-panel/file-panel.spec.ts
  playwright/e2e/right-panel/notification-panel.spec.ts
  playwright/e2e/right-panel/right-panel.spec.ts
  playwright/snapshots/right-panel/file-panel.spec.ts/empty-linux.png
  playwright/snapshots/right-panel/notification-panel.spec.ts/empty-linux.png
  res/css/_components.pcss
  res/css/structures/_FilePanel.pcss
  res/css/structures/_NotificationPanel.pcss
  res/css/structures/_RightPanel.pcss
  res/css/views/right_panel/_EmptyState.pcss
  res/css/views/right_panel/_ThreadPanel.pcss
  src/components/structures/FilePanel.tsx
  src/components/structures/NotificationPanel.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/views/right_panel/EmptyState.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/FilePanel-test.tsx
  test/components/structures/ThreadPanel-test.tsx
  test/components/structures/__snapshots__/FilePanel-test.tsx.snap
  test/components/structures/__snapshots__/ThreadPanel-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#12777 Close any open modals on logout
  src/Modal.tsx
  test/Modal-test.ts
Labels: T-Enhancement

#12797 Update Thread Panel to match latest designs
  res/css/_common.pcss
  res/css/views/right_panel/_ThreadPanel.pcss
  res/css/views/rooms/_EventTile.pcss
  res/img/element-icons/thread-summary.svg
  src/components/structures/ThreadPanel.tsx
  test/components/structures/__snapshots__/ThreadPanel-test.tsx.snap
Labels: T-Enhancement

#12803 Default the room header to on
  playwright/e2e/app-loading/stored-credentials.spec.ts
  playwright/e2e/chat-export/html-export.spec.ts
  playwright/e2e/create-room/create-room.spec.ts
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/crypto/event-shields.spec.ts
  playwright/e2e/crypto/utils.ts
  playwright/e2e/file-upload/image-upload.spec.ts
  playwright/e2e/integration-manager/get-openid-token.spec.ts
  playwright/e2e/integration-manager/kick.spec.ts
  playwright/e2e/integration-manager/read_events.spec.ts
  playwright/e2e/integration-manager/send_event.spec.ts
  playwright/e2e/integration-manager/utils.ts
  playwright/e2e/invite/invite-dialog.spec.ts
  playwright/e2e/knock/create-knock-room.spec.ts
  playwright/e2e/lazy-loading/lazy-loading.spec.ts
  playwright/e2e/one-to-one-chat/one-to-one-chat.spec.ts
  playwright/e2e/polls/pollHistory.spec.ts
  playwright/e2e/presence/presence.spec.ts
  playwright/e2e/read-receipts/index.ts
  playwright/e2e/right-panel/right-panel.spec.ts
  playwright/e2e/right-panel/utils.ts
  playwright/e2e/room/room-header.spec.ts
  playwright/e2e/spotlight/spotlight.spec.ts
  playwright/e2e/threads/threads.spec.ts
  playwright/e2e/timeline/timeline.spec.ts
  playwright/pages/ElementAppPage.ts
  playwright/pages/settings.ts
  playwright/snapshots/file-upload/image-upload.spec.ts/image-upload-preview-linux.png
  playwright/snapshots/permalinks/permalinks.spec.ts/permalink-rendering-linux.png
  playwright/snapshots/room/room-header.spec.ts/encrypted-room-header-linux.png
  playwright/snapshots/room/room-header.spec.ts/room-header-highlighted-linux.png
  playwright/snapshots/room/room-header.spec.ts/room-header-linux.png
  playwright/snapshots/room/room-header.spec.ts/room-header-long-name-linux.png
  playwright/snapshots/room/room-header.spec.ts/room-header-video-room-linux.png
  playwright/snapshots/room/room-header.spec.ts/room-header-with-apps-button-highlighted-linux.png
  playwright/snapshots/room/room-header.spec.ts/room-header-with-apps-button-not-highlighted-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/collapsed-gels-and-messages-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/collapsed-gels-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/configured-room-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-line-inline-start-margin-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-compact-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-and-messages-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-emote-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-redaction-placeholder-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/highlighted-search-results-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/image-in-timeline-default-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/long-strings-with-reply-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/long-strings-with-reply-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/long-strings-with-reply-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/search-results-with-TextualEvent-linux.png
  src/settings/Settings.tsx
  test/components/structures/RoomView-test.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
Labels: X-Release-Blocker, T-Enhancement

#12802 Add release announcement for the new room header
  src/components/views/rooms/RoomHeader.tsx
  src/i18n/strings/en_EN.json
  src/stores/ReleaseAnnouncementStore.ts
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
  test/stores/ReleaseAnnouncementStore-test.tsx
Labels: X-Release-Blocker, T-Enhancement

#12808 Update compound-design-tokens to satisfy compound-web peer dependency
  package.json
  src/components/structures/FilePanel.tsx
  src/components/structures/NotificationPanel.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/views/auth/LoginWithQRFlow.tsx
  src/components/views/right_panel/BaseCard.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomHeader/CallGuestLinkButton.tsx
  src/components/views/rooms/RoomSearchAuxPanel.tsx
  src/components/views/settings/AvatarSetting.tsx
  src/components/views/settings/ThemeChoicePanel.tsx
  test/components/structures/__snapshots__/FilePanel-test.tsx.snap
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/components/views/settings/__snapshots__/ThemeChoicePanel-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/LoginWithQRFlow-test.tsx.snap
  yarn.lock
Labels: X-Release-Blocker, T-Task, backport staging

#12807 Fix flake in timeline screenshot test
  playwright/e2e/timeline/timeline.spec.ts
  playwright/snapshots/timeline/timeline.spec.ts/long-strings-with-reply-bubble-layout-linux.png
Labels: T-Task

#12790 Acknowledge `DeviceMute` widget actions
  src/models/Call.ts
  src/stores/widgets/ElementWidgetActions.ts
  test/models/Call-test.ts
Labels: T-Enhancement

#12742 Fix unwanted ringing of other devices even though the user is already connected to the call.
  src/Notifier.ts
  test/Notifier-test.ts
Labels: T-Enhancement

#12780 Remove MatrixRTC realted import ES lint exceptions using a index.ts for matrixrtc
  .eslintrc.js
  src/Notifier.ts
  src/components/views/voip/CallDuration.tsx
  src/models/Call.ts
  src/stores/CallStore.ts
  test/Notifier-test.ts
  test/components/views/rooms/LegacyRoomHeader-test.tsx
  test/createRoom-test.ts
  test/models/Call-test.ts
  test/test-utils/test-utils.ts
  test/toasts/IncomingCallToast-test.tsx
  yarn.lock
Labels: T-Enhancement

#11113 Allow Chrome page translator to translate messages in rooms
  src/HtmlUtils.tsx
  test/__snapshots__/HtmlUtils-test.tsx.snap
  test/components/views/dialogs/__snapshots__/MessageEditHistoryDialog-test.tsx.snap
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/components/views/rooms/__snapshots__/PinnedEventTile-test.tsx.snap
  test/components/views/settings/__snapshots__/LayoutSwitcher-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
Labels: Z-Community-PR, T-Defect

#12827 Revert "Use multiple workers in Playwright CI to make use of multiple cores"
  playwright.config.ts
Labels: T-Task

#12826 Fix compound typography font component issues
  playwright/e2e/app-loading/feature-detection.spec.ts
  playwright/snapshots/app-loading/feature-detection.spec.ts/unsupported-browser-CompatibilityView-linux.png
  res/css/_common.pcss
Labels: T-Defect

#12666 Add sign out button to settings profile section
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-linux.png
  src/components/structures/UserMenu.tsx
  src/components/views/dialogs/LogoutDialog.tsx
  src/components/views/settings/UserProfileSettings.tsx
  test/components/views/settings/UserProfileSettings-test.tsx
Labels: T-Enhancement

#11908 Make micIcon display on primary
  src/components/views/voip/VideoFeed.tsx
Labels: Z-Community-PR, T-Defect

#12830 Warn users on unsupported browsers before they lack features
  package.json
  src/@types/electron-to-chromium.d.ts
  src/Lifecycle.ts
  src/SupportedBrowser.ts
  src/components/views/dialogs/BugReportDialog.tsx
  src/i18n/strings/en_EN.json
  src/utils/device/parseUserAgent.ts
  test/SupportedBrowser-test.ts
  test/utils/device/parseUserAgent-test.ts
  yarn.lock
Labels: T-Enhancement

#12835 Stabilise screenshot tests
  playwright/e2e/file-upload/image-upload.spec.ts
  playwright/e2e/register/register.spec.ts
  playwright/e2e/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts
  playwright/e2e/timeline/timeline.spec.ts
  playwright/e2e/user-view/user-view.spec.ts
  playwright/element-web-test.ts
  playwright/snapshots/file-upload/image-upload.spec.ts/image-upload-preview-linux.png
  playwright/snapshots/forgot-password/forgot-password.spec.ts/forgot-password-verify-email-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-dm-with-user-pill-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-dm-without-user-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-room-with-user-pill-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-room-without-user-linux.png
  playwright/snapshots/register/register.spec.ts/email-prompt-linux.png
  playwright/snapshots/register/register.spec.ts/server-picker-linux.png
  playwright/snapshots/room-directory/room-directory.spec.ts/filtered-no-results-linux.png
  playwright/snapshots/room-directory/room-directory.spec.ts/filtered-one-result-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  playwright/snapshots/settings/general-room-settings-tab.spec.ts/General-room-settings-tab-should-be-rendered-properly-1-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-smallscreen-linux.png
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
  playwright/snapshots/settings/security-user-settings-tab.spec.ts/Security-user-settings-tab-with-posthog-enable-b5d89-csLearnMoreDialog-should-be-rendered-properly-1-linux.png
  playwright/snapshots/user-view/user-view.spec.ts/user-info-linux.png
Labels: T-Task

#12833 Update toast styles to match Figma
  package.json
  playwright/pages/toasts.ts
  playwright/snapshots/release-announcement/releaseAnnouncement.spec.ts/release-announcement-Threads-Activity-Centre-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  playwright/snapshots/spaces/spaces.spec.ts/space-panel-expanded-linux.png
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-button-expanded-linux.png
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-hovered-expanded-linux.png
  res/css/structures/_ToastContainer.pcss
  src/SupportedBrowser.ts
  src/components/structures/MatrixChat.tsx
  src/components/structures/ToastContainer.tsx
  src/components/views/toasts/GenericExpiringToast.tsx
  src/components/views/toasts/GenericToast.tsx
  src/components/views/toasts/VerificationRequestToast.tsx
  src/stores/LifecycleStore.ts
  src/toasts/AnalyticsToast.tsx
  src/toasts/BulkUnverifiedSessionsToast.ts
  src/toasts/DesktopNotificationsToast.ts
  src/toasts/MobileGuideToast.ts
  src/toasts/ServerLimitToast.tsx
  src/toasts/SetupEncryptionToast.ts
  src/toasts/UnverifiedSessionToast.tsx
  src/toasts/UpdateToast.tsx
  test/components/views/toasts/GenericToast-test.tsx
  test/components/views/toasts/__snapshots__/GenericToast-test.tsx.snap
  test/components/views/toasts/__snapshots__/VerificationRequestToast-test.tsx.snap
  test/stores/LifecycleStore-test.ts
  test/toasts/__snapshots__/UnverifiedSessionToast-test.tsx.snap
  yarn.lock
Labels: T-Enhancement

#12836 Update tests for new unsupported browser view
  playwright/e2e/app-loading/feature-detection.spec.ts
  playwright/snapshots/app-loading/feature-detection.spec.ts/unsupported-browser-CompatibilityView-linux.png
  src/IConfigOptions.ts
  src/SdkConfig.ts
Labels: T-Task

#12840 Split up bodyToHtml
  src/HtmlUtils.tsx
  src/components/views/messages/EditHistoryMessage.tsx
  src/components/views/messages/TextualBody.tsx
  src/utils/MessageDiffUtils.tsx
  test/HtmlUtils-test.tsx
Labels: T-Task

#11806 feat: Add autoformat and lint for ts/tsx files
  .husky/pre-commit
  .lintstagedrc
  package.json
  yarn.lock
Labels: Z-Community-PR, T-Task

#12839 Rework how the onboarding notifications task works
  src/Notifier.ts
  src/hooks/useUserOnboardingContext.ts
  src/hooks/useUserOnboardingTasks.ts
  src/i18n/strings/en_EN.json
  src/toasts/DesktopNotificationsToast.ts
  test/hooks/useUserOnboardingTasks-test.tsx
Labels: T-Enhancement

#12845 Fix picklekey debug
  src/Lifecycle.ts
Labels: T-Task

#12843 Extract useIsVideoRoom hook
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/RoomInfoLine.tsx
  src/components/views/rooms/RoomPreviewCard.tsx
  src/utils/video-rooms.ts
Labels: T-Task

#12842 Remove topic from new room header and expand right panel topic
  playwright/e2e/create-room/create-room.spec.ts
  res/css/views/right_panel/_RoomSummaryCard.pcss
  res/css/views/rooms/_RoomHeader.pcss
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/RoomHeader.tsx
  test/components/views/right_panel/RoomSummaryCard-test.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/rooms/RoomHeader-test.tsx
Labels: T-Enhancement

#12844 Extract Extensions into their own right panel tab
  playwright/e2e/integration-manager/utils.ts
  playwright/e2e/right-panel/right-panel.spec.ts
  playwright/snapshots/crypto/crypto.spec.ts/RoomSummaryCard-with-verified-e2ee-linux.png
  playwright/snapshots/right-panel/right-panel.spec.ts/with-name-and-address-linux.png
  res/css/_components.pcss
  res/css/views/right_panel/_BaseCard.pcss
  res/css/views/right_panel/_ExtensionsCard.pcss
  res/css/views/right_panel/_RoomSummaryCard.pcss
  res/themes/light-high-contrast/css/_light-high-contrast.pcss
  src/components/structures/RightPanel.tsx
  src/components/views/right_panel/BaseCard.tsx
  src/components/views/right_panel/ExtensionsCard.tsx
  src/components/views/right_panel/RightPanelTabs.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/right_panel/WidgetCard.tsx
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/hooks/room/useRoomCall.ts
  src/i18n/strings/en_EN.json
  src/stores/right-panel/RightPanelStorePhases.ts
  src/utils/WidgetUtils.ts
  test/components/views/right_panel/ExtensionsCard-test.tsx
  test/components/views/right_panel/RightPanelTabs-test.tsx
  test/components/views/right_panel/__snapshots__/ExtensionsCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RightPanelTabs-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
Labels: T-Enhancement

#12848 Handle media download errors better
  src/components/views/messages/DownloadActionButton.tsx
  src/customisations/Media.ts
  src/i18n/strings/en_EN.json
  test/components/views/messages/DownloadActionButton-test.tsx
  test/customisations/Media-test.ts
  test/test-utils/test-utils.ts
Labels: T-Defect

#12837 Fix alignment of RTL messages
  playwright/e2e/messages/messages.spec.ts
  playwright/snapshots/messages/messages.spec.ts/basic-message-ltr-ltrdisplayname-linux.png
  playwright/snapshots/messages/messages.spec.ts/basic-message-ltr-rtldisplayname-linux.png
  playwright/snapshots/messages/messages.spec.ts/basic-message-rtl-ltrdisplayname-linux.png
  playwright/snapshots/messages/messages.spec.ts/basic-message-rtl-rtldisplayname-linux.png
  playwright/snapshots/messages/messages.spec.ts/edited-message-ltr-ltrdisplayname-linux.png
  playwright/snapshots/messages/messages.spec.ts/edited-message-ltr-rtldisplayname-linux.png
  playwright/snapshots/messages/messages.spec.ts/edited-message-rtl-ltrdisplayname-linux.png
  playwright/snapshots/messages/messages.spec.ts/edited-message-rtl-rtldisplayname-linux.png
  playwright/snapshots/messages/messages.spec.ts/emote-ltr-ltrdisplayname-linux.png
  playwright/snapshots/messages/messages.spec.ts/emote-ltr-rtldisplayname-linux.png
  playwright/snapshots/messages/messages.spec.ts/emote-rtl-ltrdisplayname-linux.png
  playwright/snapshots/messages/messages.spec.ts/emote-rtl-rtldisplayname-linux.png
  res/css/views/messages/_MEmoteBody.pcss
  res/css/views/rooms/_EventTile.pcss
  src/HtmlUtils.tsx
  src/components/views/messages/EditHistoryMessage.tsx
  src/components/views/messages/TextualBody.tsx
  test/HtmlUtils-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/components/views/rooms/__snapshots__/PinnedEventTile-test.tsx.snap
  test/components/views/settings/__snapshots__/LayoutSwitcher-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
Labels: T-Defect
