Repository matrix-org/matrix-react-sdk, pull requests merged in 2024-09, with the labels that each got.

#12775 Allow user to set timezone
  playwright/e2e/settings/preferences-user-settings-tab.spec.ts
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
  res/css/components/views/settings/shared/_SettingsSubsection.pcss
  src/DateUtils.ts
  src/TimezoneHandler.ts
  src/components/structures/RoomView.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/contexts/RoomContext.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/TimezoneHandler-test.ts
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/components/views/settings/tabs/user/PreferencesUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/PreferencesUserSettingsTab-test.tsx.snap
  test/test-utils/room.ts
Labels: Z-Community-PR, T-Enhancement

#12944 The pinned message banner or list are triggering 🎉 effect.
  src/hooks/usePinnedEvents.ts
Labels: T-Defect

#12945 Always display last pinned message on the banner
  playwright/e2e/pinned-messages/pinned-messages.spec.ts
  src/components/views/rooms/PinnedMessageBanner.tsx
  test/components/views/rooms/PinnedMessageBanner-test.tsx
  test/components/views/rooms/__snapshots__/PinnedMessageBanner-test.tsx.snap
Labels: T-Defect

#12946 Display the indicator even with one message in pinned message banner
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-1-Msg1-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-2-Msg1-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-2-Msg2-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-4-Msg1-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-4-Msg2-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-4-Msg3-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-4-Msg4-linux.png
  res/css/views/rooms/_PinnedMessageBanner.pcss
  src/components/views/rooms/PinnedMessageBanner.tsx
  test/components/views/rooms/__snapshots__/PinnedMessageBanner-test.tsx.snap
Labels: T-Defect

#12943 Update RTE to 2.37.9
  package.json
  yarn.lock
Labels: T-Task

#12923 Fix read receipt animation
  src/components/structures/MessagePanel.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/ReadReceiptGroup.tsx
  src/components/views/rooms/ReadReceiptMarker.tsx
  test/components/views/rooms/ReadReceiptMarker-test.tsx
Labels: T-Defect

#12951 Fix location sharing overflow in pinned message list
  res/css/views/rooms/_PinnedEventTile.pcss
Labels: T-Defect

#12947 Pinned message list: prevent sender name to overflow pinned event tile
  res/css/views/rooms/_PinnedEventTile.pcss
  src/components/views/rooms/PinnedEventTile.tsx
  test/components/views/right_panel/__snapshots__/PinnedMessagesCard-test.tsx.snap
  test/components/views/rooms/__snapshots__/PinnedEventTile-test.tsx.snap
Labels: T-Defect

#12941 Add error handling for room publish toggle
  src/components/views/room_settings/RoomPublishSetting.tsx
  src/i18n/strings/en_EN.json
Labels: Z-Community-PR, T-Defect

#12963 Log phases in the verification process
  src/components/views/right_panel/EncryptionPanel.tsx
Labels: T-Task

#12964 Migrate all pinning checks and actions into `PinningUtils`
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/dialogs/UnpinAllDialog.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/right_panel/PinnedMessagesCard.tsx
  src/components/views/rooms/PinnedEventTile.tsx
  src/utils/PinningUtils.ts
  test/components/views/rooms/PinnedEventTile-test.tsx
  test/utils/PinningUtils-test.ts
Labels: T-Task

#12965 Add analytics event for pinned messages
  package.json
  src/PosthogTrackers.ts
  src/TextForEvent.tsx
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/dialogs/UnpinAllDialog.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/PinnedEventTile.tsx
  src/components/views/rooms/PinnedMessageBanner.tsx
  yarn.lock
Labels: T-Task

#12970 Update README.md with archive notice
  README.md
Labels: T-Task
