Repository matrix-org/matrix-react-sdk, pull requests merged in 2024-04, with the labels that each got.

#12386 Add `EventType.RoomEncryption` to the auto approve capabilities of Element Call widgets
  src/stores/widgets/StopGapWidgetDriver.ts
Labels: T-Enhancement

#12388 playwright: Document some of the fixtures
  playwright/element-web-test.ts
  playwright/pages/ElementAppPage.ts
Labels: T-Task

#12390 Remove redundant workaround in playwright test
  playwright/e2e/crypto/crypto.spec.ts
Labels: T-Task

#12384 Add analytics for mark all threads unread
  package.json
  src/components/structures/ThreadPanel.tsx
  yarn.lock
Labels: T-Enhancement

#12385 Show the call and share button if the user can create a guest link.
  src/hooks/room/useRoomCall.ts
  test/components/views/rooms/RoomHeader-test.tsx
Labels: T-Enhancement

#12402 Fix/disable failing playwright tests
  playwright/e2e/presence/presence.spec.ts
  playwright/e2e/timeline/timeline.spec.ts
  playwright/snapshots/timeline/timeline.spec.ts/long-strings-with-reply-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/long-strings-with-reply-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/long-strings-with-reply-modern-layout-linux.png
Labels: T-Task

#12406 Fix room topic in-app links not being handled correctly on topic dialog
  src/components/views/elements/RoomTopic.tsx
Labels: T-Defect

#12380 TAC: Release Announcement
  package.json
  playwright/e2e/release-announcement/index.ts
  playwright/e2e/release-announcement/releaseAnnouncement.spec.ts
  playwright/element-web-test.ts
  playwright/snapshots/release-announcement/releaseAnnouncement.spec.ts/release-announcement-Threads-Activity-Centre-linux.png
  src/components/structures/ReleaseAnnouncement.tsx
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentre.tsx
  src/hooks/useIsReleaseAnnouncementOpen.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/handlers/AccountSettingsHandler.ts
  src/stores/ReleaseAnnouncementStore.ts
  test/components/structures/ReleaseAnnouncement-test.tsx
  test/components/views/settings/tabs/user/LabsUserSettingsTab-test.tsx
  test/components/views/spaces/ThreadsActivityCentre-test.tsx
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
  test/stores/ReleaseAnnouncementStore-test.tsx
  yarn.lock
Labels: T-Enhancement

#12410 Focus the thread panel when clicking on an item in the TAC
  playwright/e2e/spaces/threads-activity-centre/index.ts
  playwright/e2e/spaces/threads-activity-centre/threadsActivityCentre.spec.ts
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/views/right_panel/BaseCard.tsx
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentre.tsx
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentreButton.tsx
  src/dispatcher/actions.ts
  src/dispatcher/payloads/ViewRoomPayload.ts
  test/components/structures/MatrixChat-test.tsx
  test/components/structures/ThreadPanel-test.tsx
Labels: T-Defect

#12401 Call Guest Access, give user the option to change the acces level so they can generate a call link.
  res/css/_components.pcss
  res/css/views/rooms/_CallGuestLinkButton.pcss
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomHeader/CallGuestLinkButton.tsx
  src/hooks/room/useGuestAccessInformation.ts
  src/hooks/room/useRoomCall.ts
  src/i18n/strings/en_EN.json
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/RoomHeader/CallGuestLinkButton-test.tsx
Labels: T-Enhancement

#12409 Humanize spell check language labels
  src/components/views/settings/SpellCheckSettings.tsx
Labels: T-Enhancement

#12404 Fix inability to join a `knock` room via space hierarchy view
  src/components/structures/SpaceHierarchy.tsx
  test/components/structures/SpaceHierarchy-test.tsx
  test/components/structures/__snapshots__/SpaceHierarchy-test.tsx.snap
Labels: T-Defect

#12412 Fix thread navigation in timeline
  playwright/e2e/threads/threads.spec.ts
  src/components/structures/RoomView.tsx
Labels: T-Defect

#12411 Fix link modal not shown after access upgrade
  src/components/views/rooms/RoomHeader/CallGuestLinkButton.tsx
  src/hooks/room/useGuestAccessInformation.ts
Labels: T-Defect

#12342 Replace `SecurityCustomisations` with `CryptoSetupExtension`
  package.json
  src/Lifecycle.ts
  src/Login.ts
  src/MatrixClientPeg.ts
  src/SecurityManager.ts
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/structures/MatrixChat.tsx
  src/modules/ModuleRunner.ts
  src/toasts/SetupEncryptionToast.ts
  test/MatrixClientPeg-test.ts
  test/modules/MockModule.ts
  test/modules/ModuleRunner-test.ts
  yarn.lock
Labels: Z-Community-PR, T-Enhancement

#12316 Add support for device dehydration v2
  playwright/e2e/crypto/dehydration.spec.ts
  playwright/plugins/homeserver/synapse/templates/dehydration/README.md
  playwright/plugins/homeserver/synapse/templates/dehydration/homeserver.yaml
  playwright/plugins/homeserver/synapse/templates/dehydration/log.config
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  src/stores/SetupEncryptionStore.ts
  src/utils/device/dehydration.ts
  test/components/views/dialogs/security/CreateSecretStorageDialog-test.tsx
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/settings/tabs/user/SecurityUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/stores/SetupEncryptionStore-test.ts
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#12417 New context for local device verification
  src/components/structures/LoggedInView.tsx
  src/components/structures/MatrixClientContextProvider.tsx
  src/contexts/LocalDeviceVerificationStateContext.ts
  test/components/structures/LoggedInView-test.tsx
  test/components/structures/MatrixChat-test.tsx
  test/components/structures/MatrixClientContextProvider-test.tsx
Labels: T-Task

#12419 Make empty state copy for TAC depend on the value of the setting
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentre.tsx
  src/i18n/strings/en_EN.json
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
Labels: T-Enhancement

#12433 Fix selector so maths support doesn't mangle divs
  src/HtmlUtils.tsx
  test/HtmlUtils-test.tsx
  test/__snapshots__/HtmlUtils-test.tsx.snap
Labels: T-Defect

#12434 Use the same logic in prevews as the timeline to hide events that should be hidden
  src/stores/room-list/MessagePreviewStore.ts
  test/stores/room-list/MessagePreviewStore-test.ts
Labels: T-Defect

#12389 Expected UTDs: report a different Posthog code
  .eslintrc.js
  src/DecryptionFailureTracker.ts
  src/components/structures/MatrixChat.tsx
  test/DecryptionFailureTracker-test.ts
  yarn.lock
Labels: T-Enhancement

#12436 Collect decryption failure translations together
  src/components/views/messages/DecryptionFailureBody.tsx
  src/components/views/rooms/ThreadSummary.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#12438 Move the TAC to above the button
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentre.tsx
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
Labels: T-Defect

#12445 Decrypt events in reverse order without copying the array
  src/components/structures/TimelinePanel.tsx
Labels: Z-Community-PR, T-Enhancement

#12418 Add analytics to activity toggles
  src/settings/Settings.tsx
  src/settings/controllers/AnalyticsController.ts
  test/settings/controllers/AnalyticsController-test.ts
  yarn.lock
Labels: T-Enhancement

#12446 Disable some tests that aren't passing
  playwright/e2e/read-receipts/redactions.spec.ts
Labels: T-Task

#12451 Show the local echo in previews
  src/stores/room-list/MessagePreviewStore.ts
  test/stores/room-list/MessagePreviewStore-test.ts
Labels: T-Defect

#12443 Add `Tooltip` to `AccessibleButton`
  playwright/e2e/read-receipts/index.ts
  playwright/e2e/spaces/threads-activity-centre/index.ts
  src/accessibility/context_menu/ContextMenuButton.tsx
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/elements/AccessibleTooltipButton.tsx
  src/components/views/right_panel/UserInfo.tsx
  test/components/structures/__snapshots__/UserMenu-test.tsx.snap
  test/components/views/beacon/__snapshots__/DialogSidebar-test.tsx.snap
  test/components/views/beacon/__snapshots__/LeftPanelLiveShareWarning-test.tsx.snap
  test/components/views/beacon/__snapshots__/RoomLiveShareWarning-test.tsx.snap
  test/components/views/elements/AppTile-test.tsx
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/components/views/location/__snapshots__/LocationViewDialog-test.tsx.snap
  test/components/views/location/__snapshots__/ZoomButtons-test.tsx.snap
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/components/views/rooms/MemberList-test.tsx
  test/components/views/rooms/__snapshots__/MemberTile-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/LoginWithQRFlow-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/PeopleRoomSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
  test/components/views/spaces/__snapshots__/SpacePanel-test.tsx.snap
Labels: T-Enhancement

#12391 Expected UTDs: use a different message for UTDs sent before login
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/crypto/utils.ts
  src/components/views/messages/DecryptionFailureBody.tsx
  src/i18n/strings/en_EN.json
  test/components/views/messages/DecryptionFailureBody-test.tsx
Labels: T-Enhancement

#12456 Add extra attribute to `AccessibleButton`
  src/components/views/elements/AccessibleButton.tsx
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
Labels: T-Task

#12455 MenuItem: fix caption usage
  src/accessibility/context_menu/MenuItem.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomListHeader.tsx
Labels: T-Defect

#12439 Take the Threads Activity Centre out of labs
  playwright/e2e/read-receipts/editing-messages.spec.ts
  playwright/e2e/read-receipts/high-level.spec.ts
  playwright/e2e/read-receipts/new-messages.spec.ts
  playwright/e2e/read-receipts/reactions.spec.ts
  playwright/e2e/read-receipts/read-receipts.spec.ts
  playwright/e2e/read-receipts/redactions.spec.ts
  playwright/e2e/threads/threads.spec.ts
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  playwright/snapshots/spaces/spaces.spec.ts/space-panel-collapsed-linux.png
  playwright/snapshots/spaces/spaces.spec.ts/space-panel-expanded-linux.png
  src/components/views/dialogs/devtools/RoomNotifications.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/hooks/useUnreadNotifications.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/notifications/RoomNotificationStateStore.ts
  test/components/structures/MatrixChat-test.tsx
  test/components/views/settings/tabs/user/LabsUserSettingsTab-test.tsx
  test/components/views/spaces/__snapshots__/SpacePanel-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: X-Release-Blocker, T-Enhancement

#12453 Use a different error message for UTDs when you weren't in the room.
  package.json
  src/DecryptionFailureTracker.ts
  src/components/views/messages/DecryptionFailureBody.tsx
  src/i18n/strings/en_EN.json
  test/DecryptionFailureTracker-test.ts
  test/components/views/messages/DecryptionFailureBody-test.tsx
  yarn.lock
Labels: T-Enhancement

#12461 Tooltip: Use `AccessibleButton` in reusable elements
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/elements/CopyableText.tsx
  src/components/views/elements/ImageView.tsx
  src/components/views/elements/SSOButtons.tsx
  src/components/views/elements/ToggleSwitch.tsx
  test/components/views/beacon/__snapshots__/BeaconListItem-test.tsx.snap
  test/components/views/beacon/__snapshots__/DialogSidebar-test.tsx.snap
  test/components/views/beacon/__snapshots__/ShareLatestLocation-test.tsx.snap
  test/components/views/dialogs/__snapshots__/DevtoolsDialog-test.tsx.snap
  test/components/views/elements/ImageView-test.tsx
  test/components/views/elements/__snapshots__/ImageView-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/AdvancedRoomSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/LabsUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/PreferencesUserSettingsTab-test.tsx.snap
Labels: T-Task

#12460 Tooltip: Use `AccessibleButton` in dialogs
  src/components/views/dialogs/ForwardDialog.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/dialogs/spotlight/TooltipOption.tsx
Labels: T-Enhancement

#12458 Tooltip: Use `AccessibleButton` in `RovingAccessibleTooltipButton`
  package.json
  playwright/snapshots/timeline/timeline.spec.ts/event-tile-reply-chains-irc-layout-linux.png
  src/accessibility/roving/RovingAccessibleTooltipButton.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/pips/WidgetPip.tsx
  src/components/views/rooms/MessageComposerFormatBar.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/rooms/EventTile/__snapshots__/EventTileThreadToolbar-test.tsx.snap
  yarn.lock
Labels: T-Enhancement

#12463 Prepare for OIDC QR Login PR
  res/css/views/auth/_LoginWithQR.pcss
  src/components/views/auth/LoginWithQR-types.ts
  src/components/views/auth/LoginWithQR.tsx
  src/components/views/auth/LoginWithQRFlow.tsx
  src/components/views/settings/devices/LoginWithQRSection.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/LoginWithQR-test.tsx
  test/components/views/settings/devices/LoginWithQRFlow-test.tsx
  test/components/views/settings/devices/__snapshots__/LoginWithQRFlow-test.tsx.snap
Labels: T-Task

#12474 Convert UserSettings to functional component
  src/components/views/dialogs/UserSettingsDialog.tsx
  test/components/views/dialogs/UserSettingsDialog-test.tsx
Labels: T-Task
