Repository matrix-org/matrix-react-sdk, pull requests merged in 2024-05, with the labels that each got.

#12477 Improve comments and types in MatrixClientPeg
  src/MatrixClientPeg.ts
Labels: T-Task

#12472 TAC: hide tooltip when the release announcement is displayed
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentre.tsx
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentreButton.tsx
  test/components/views/spaces/ThreadsActivityCentre-test.tsx
Labels: T-Defect

#12475 TAC: Close Release Announcement when TAC button is clicked
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentre.tsx
  test/components/views/spaces/ThreadsActivityCentre-test.tsx
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
Labels: X-Release-Blocker, T-Defect, backport staging

#12482 TAC: Fix accessibility issue when the Release announcement is displayed
  package.json
  test/components/views/spaces/__snapshots__/SpacePanel-test.tsx.snap
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
  yarn.lock
Labels: X-Release-Blocker, T-Defect, backport staging

#12485 [Backport staging] TAC: Close Release Announcement when TAC button is clicked
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentre.tsx
  test/components/views/spaces/ThreadsActivityCentre-test.tsx
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
Labels: X-Release-Blocker, T-Defect

#12486 Fix flaky jest tests
  test/components/structures/ThreadView-test.tsx
  test/components/views/beacon/BeaconMarker-test.tsx
  test/components/views/beacon/BeaconViewDialog-test.tsx
  test/components/views/dialogs/ForwardDialog-test.tsx
  test/components/views/messages/MLocationBody-test.tsx
  test/components/views/rooms/MessageComposerButtons-test.tsx
  test/components/views/settings/Notifications-test.tsx
  test/setupTests.ts
Labels: T-Task

#12414 Extract functions for service worker usage, and add initial MSC3916 playwright test (when supported)
  playwright/e2e/timeline/timeline.spec.ts
  playwright/element-web-test.ts
  playwright/snapshots/timeline/timeline.spec.ts/image-in-timeline-default-layout-linux.png
  src/BasePlatform.ts
  src/Lifecycle.ts
  src/utils/StorageAccess.ts
  src/utils/StorageManager.ts
  src/utils/tokens/pickling.ts
  src/utils/tokens/tokens.ts
  test/Lifecycle-test.ts
  test/components/structures/MatrixChat-test.tsx
  test/utils/StorageAccess-test.ts
Labels: T-Task

#12492 Use OPTIONS for sliding sync detection poke
  src/SlidingSyncManager.ts
  test/SlidingSyncManager-test.ts
Labels: T-Defect

#12490 Tooltip: improve accessibility of the right panel
  playwright/snapshots/room/room-header.spec.ts/room-header-highlighted-linux.png
  playwright/snapshots/room/room-header.spec.ts/room-header-with-apps-button-not-highlighted-linux.png
  src/components/views/right_panel/HeaderButton.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  test/components/views/right_panel/__snapshots__/LegacyRoomHeaderButtons-test.tsx.snap
Labels: T-Enhancement

#12478 Convert tabbedview to functional component
  src/components/structures/TabbedView.tsx
Labels: T-Task

#12497 Tooltip: improve accessibility of spaces
  src/components/structures/LeftPanel.tsx
  src/components/structures/SpaceHierarchy.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/views/spaces/QuickSettingsButton.tsx
  src/components/views/spaces/SpaceCreateMenu.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  test/components/structures/__snapshots__/SpaceHierarchy-test.tsx.snap
  test/components/views/spaces/__snapshots__/SpacePanel-test.tsx.snap
Labels: T-Enhancement

#12480 Make TabbedView a controlled component
  src/components/structures/TabbedView.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/dialogs/RoomSettingsDialog.tsx
  src/components/views/dialogs/SpacePreferencesDialog.tsx
  src/components/views/dialogs/SpaceSettingsDialog.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/elements/DesktopCapturerSourcePicker.tsx
  src/utils/DialogOpener.ts
  test/components/structures/TabbedView-test.tsx
  test/components/views/elements/DesktopCapturerSourcePicker-test.tsx
Labels: T-Task

#12498 Check native sliding sync support against an unstable feature flag
  src/SlidingSyncManager.ts
  test/SlidingSyncManager-test.ts
Labels: T-Defect

#12494 fix avatar stretched on 1:1 call
  res/css/views/toasts/_IncomingLegacyCallToast.pcss
Labels: Z-Community-PR, T-Defect

#12483 Tooltip: Remove extra data attribute
  package.json
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/structures/__snapshots__/SpaceHierarchy-test.tsx.snap
  test/components/structures/__snapshots__/ThreadPanel-test.tsx.snap
  test/components/views/avatars/__snapshots__/DecoratedRoomAvatar-test.tsx.snap
  test/components/views/beacon/__snapshots__/BeaconListItem-test.tsx.snap
  test/components/views/beacon/__snapshots__/DialogSidebar-test.tsx.snap
  test/components/views/beacon/__snapshots__/LeftPanelLiveShareWarning-test.tsx.snap
  test/components/views/beacon/__snapshots__/RoomLiveShareWarning-test.tsx.snap
  test/components/views/beacon/__snapshots__/ShareLatestLocation-test.tsx.snap
  test/components/views/dialogs/__snapshots__/DevtoolsDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ServerPickerDialog-test.tsx.snap
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/components/views/elements/__snapshots__/FacePile-test.tsx.snap
  test/components/views/elements/__snapshots__/ImageView-test.tsx.snap
  test/components/views/elements/__snapshots__/InfoTooltip-test.tsx.snap
  test/components/views/elements/__snapshots__/Pill-test.tsx.snap
  test/components/views/elements/__snapshots__/RoomFacePile-test.tsx.snap
  test/components/views/location/__snapshots__/LocationViewDialog-test.tsx.snap
  test/components/views/location/__snapshots__/ZoomButtons-test.tsx.snap
  test/components/views/messages/MessageTimestamp-test.tsx
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/components/views/polls/pollHistory/__snapshots__/PollHistory-test.tsx.snap
  test/components/views/polls/pollHistory/__snapshots__/PollListItem-test.tsx.snap
  test/components/views/polls/pollHistory/__snapshots__/PollListItemEnded-test.tsx.snap
  test/components/views/right_panel/__snapshots__/LegacyRoomHeaderButtons-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/components/views/rooms/EventTile/__snapshots__/EventTileThreadToolbar-test.tsx.snap
  test/components/views/rooms/RoomHeader/__snapshots__/VideoRoomChatButton-test.tsx.snap
  test/components/views/rooms/__snapshots__/MemberTile-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/CurrentDeviceSection-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/FilteredDeviceListHeader-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/LoginWithQRFlow-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/AdvancedRoomSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/PeopleRoomSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/PreferencesUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SessionManagerTab-test.tsx.snap
  test/components/views/spaces/__snapshots__/SpacePanel-test.tsx.snap
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
  yarn.lock
Labels: T-Task

#12481 Move the active tab in user settings to the dialog title
  playwright/e2e/settings/appearance-user-settings-tab.spec.ts
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-linux.png
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
  src/components/views/dialogs/BaseDialog.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/settings/notifications/NotificationSettings2.tsx
  src/components/views/settings/shared/SettingsSection.tsx
  src/components/views/settings/tabs/user/AppearanceUserSettingsTab.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/components/views/settings/tabs/user/KeyboardUserSettingsTab.tsx
  src/components/views/settings/tabs/user/MjolnirUserSettingsTab.tsx
  src/components/views/settings/tabs/user/NotificationUserSettingsTab.tsx
  src/components/views/settings/tabs/user/PreferencesUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/components/views/settings/tabs/user/SidebarUserSettingsTab.tsx
  src/components/views/settings/tabs/user/VoiceUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/UserSettingsDialog-test.tsx
  test/components/views/settings/notifications/__snapshots__/Notifications2-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/KeyboardUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/MjolnirUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/PreferencesUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SidebarUserSettingsTab-test.tsx.snap
  test/test-utils/client.ts
Labels: T-Enhancement

#12489 Tooltip: improve accessibility for call and voice messages
  src/components/views/audio_messages/PlayPauseButton.tsx
  src/components/views/voip/LegacyCallView/LegacyCallViewButtons.tsx
  src/components/views/voip/LegacyCallView/LegacyCallViewHeader.tsx
  src/toasts/IncomingCallToast.tsx
  src/toasts/IncomingLegacyCallToast.tsx
  src/voice-broadcast/components/atoms/VoiceBroadcastHeader.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip.tsx
  test/components/views/voip/LegacyCallView/LegacyCallViewButtons-test.tsx
  test/components/views/voip/LegacyCallView/__snapshots__/LegacyCallViewButtons-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#12493 Tooltip: improve accessibility in room
  playwright/snapshots/room/room-header.spec.ts/room-header-with-apps-button-not-highlighted-linux.png
  res/css/views/rooms/_RoomBreadcrumbs.pcss
  src/components/views/rooms/CollapsibleButton.tsx
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/components/views/rooms/PinnedEventTile.tsx
  src/components/views/rooms/RoomBreadcrumbs.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/RoomSublist.tsx
  src/components/views/rooms/RoomTile.tsx
  src/components/views/rooms/VoiceRecordComposerTile.tsx
Labels: T-Enhancement

#12499 OIDC: pass `id_token` via `id_token_hint` on Manage Account interaction
  src/Lifecycle.ts
  src/stores/oidc/OidcClientStore.ts
  src/utils/oidc/authorize.ts
  src/utils/oidc/persistOidcSettings.ts
  test/Lifecycle-test.ts
  test/components/structures/MatrixChat-test.tsx
  test/utils/oidc/authorize-test.ts
  test/utils/oidc/persistOidcSettings-test.ts
Labels: T-Enhancement

#12504 Use h tag for widget title instead of b tag
  res/css/views/rooms/_AppsDrawer.pcss
  src/components/views/elements/AppTile.tsx
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
Labels: T-Task

#12510 Fix beta notifications reconciliation for intentional mentions push rules
  src/models/notificationsettings/reconcileNotificationSettings.ts
Labels: T-Defect

#12496 Add note about MSC3886, MSC3903 and MSC3906 being closed
  src/components/views/auth/LoginWithQR.tsx
  src/components/views/auth/LoginWithQRFlow.tsx
Labels: T-Task

#12503 Add room topic to right panel room info
  playwright/snapshots/crypto/crypto.spec.ts/RoomSummaryCard-with-verified-e2ee-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-room-with-user-pill-linux.png
  playwright/snapshots/invite/invite-dialog.spec.ts/invite-dialog-room-without-user-linux.png
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-bubble-layout-linux.png
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-group-layout-linux.png
  playwright/snapshots/right-panel/file-panel.spec.ts/file-tiles-list-linux.png
  playwright/snapshots/right-panel/right-panel.spec.ts/with-name-and-address-linux.png
  playwright/snapshots/threads/threads.spec.ts/Reply-to-the-location-on-ThreadView-linux.png
  playwright/snapshots/user-view/user-view.spec.ts/user-info-linux.png
  res/css/views/right_panel/_BaseCard.pcss
  res/css/views/right_panel/_RoomSummaryCard.pcss
  src/HtmlUtils.tsx
  src/components/views/elements/RoomTopic.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/right_panel/RoomSummaryCard-test.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
Labels: T-Enhancement

#12509 Fix Playwright github reporter to run in the pull_request context once more
  .github/workflows/end-to-end-tests-netlify.yaml
  playwright.config.ts
Labels: T-Task

#12505 Collapse UserSettings tabs to just icons on narrow screens
  playwright/e2e/settings/general-user-settings-tab.spec.ts
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-smallscreen-linux.png
  res/css/structures/_TabbedView.pcss
  src/components/structures/TabbedView.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
Labels: T-Enhancement

#12464 Remove old pre-join UTD logic
  playwright/e2e/crypto/crypto.spec.ts
  playwright/plugins/homeserver/synapse/templates/default/homeserver.yaml
  src/components/structures/TimelinePanel.tsx
  src/components/views/rooms/HistoryTile.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#12513 Remove spurious type casts and avoid deprecated symbols
  src/components/views/rooms/RoomHeader/CallGuestLinkButton.tsx
  src/components/views/rooms/RoomPreviewBar.tsx
  src/components/views/settings/JoinRuleSettings.tsx
Labels: T-Task

#12495 Fix `element-desktop-ssoid being` included in OIDC Authorization call
  src/BasePlatform.ts
  src/Lifecycle.ts
  src/stores/oidc/OidcClientStore.ts
  src/utils/oidc/authorize.ts
  test/utils/oidc/registerClient-test.ts
Labels: T-Defect

#12512 Fix flakiness in playwright tests
  playwright/e2e/login/overwrite_login.spec.ts
  playwright/e2e/one-to-one-chat/one-to-one-chat.spec.ts
  playwright/e2e/user-onboarding/user-onboarding-new.spec.ts
  playwright/pages/settings.ts
  playwright/snapshots/user-onboarding/user-onboarding-new.spec.ts/User-Onboarding-new-user-app-download-dialog-1-linux.png
Labels: T-Task

#12507 Disable the login overwriting test
  playwright/e2e/login/overwrite_login.spec.ts
Labels: T-Task

#12487 Tooltip: improve accessibility for messages
  src/components/views/messages/CallEvent.tsx
  src/components/views/messages/DownloadActionButton.tsx
  src/components/views/messages/LegacyCallEvent.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/messages/TextualBody.tsx
Labels: T-Enhancement

#12514 Allow explicit configuration of OIDC dynamic registration metadata
  src/BasePlatform.ts
  src/IConfigOptions.ts
  test/utils/oidc/registerClient-test.ts
Labels: T-Enhancement

#12519 Fix well-known lookup for sliding sync labs check
  src/SlidingSyncManager.ts
  test/SlidingSyncManager-test.ts
Labels: T-Defect

#12521 Fix Netlify deployments not publishing when expected
  .github/workflows/end-to-end-tests-netlify.yaml
  .github/workflows/netlify.yaml
Labels: T-Task

#12459 Tooltip: Improve the accessibility of the composer and the rich text editor
  package.json
  res/css/views/rooms/_MessageComposerFormatBar.pcss
  res/css/views/rooms/wysiwyg_composer/components/_FormattingButtons.pcss
  src/components/views/elements/AccessibleButton.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/MessageComposerButtons.tsx
  src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
  test/components/views/rooms/wysiwyg_composer/components/FormattingButtons-test.tsx
  yarn.lock
Labels: T-Enhancement

#12523 Use `*` for italics as it doesn't break when used mid-word
  src/editor/operations.ts
  test/editor/operations-test.ts
Labels: T-Defect

#12537 Fix avatar in chat export
  package.json
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/PeopleRoomSettingsTab-test.tsx.snap
  test/components/views/spaces/__snapshots__/AddExistingToSpaceDialog-test.tsx.snap
  yarn.lock
Labels: T-Defect

#12462 Tooltip: Improve accessibility for context menus
  src/accessibility/context_menu/ContextMenuTooltipButton.tsx
  src/components/views/elements/AccessibleButton.tsx
  test/components/views/spaces/__snapshots__/SpacePanel-test.tsx.snap
Labels: T-Enhancement

#12524 Stop using deprecated methods, fields & exports
  src/PasswordReset.ts
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/audio/VoiceMessageRecording.ts
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/dialogs/security/CreateCrossSigningDialog.tsx
  src/components/views/settings/ChangePassword.tsx
  src/utils/createVoiceMessageContent.ts
  test/audio/VoiceMessageRecording-test.ts
  test/components/structures/auth/ForgotPassword-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/test-utils/test-utils.ts
  test/utils/createVoiceMessageContent-test.ts
Labels: T-Task

#12526 Ensure we do not fire the verification mismatch modal multiple times
  playwright/e2e/crypto/verification.spec.ts
  src/components/views/right_panel/EncryptionPanel.tsx
Labels: T-Defect

#12540 Shown own sent state indicator even when showReadReceipts is disabled
  src/components/views/rooms/EventTile.tsx
Labels: T-Defect

#12415 Add more encryption properties to PostHog
  src/DecryptionFailureTracker.ts
  src/components/structures/MatrixChat.tsx
  test/DecryptionFailureTracker-test.ts
  test/components/structures/MatrixChat-test.tsx
  test/test-utils/client.ts
Labels: T-Task

#12538 Fix deformed avatar in a call in a narrow timeline
  res/css/views/messages/_LegacyCallEvent.pcss
Labels: T-Defect

#12541 Tooltip: Improve placement for space settings
  src/components/structures/SpaceRoomView.tsx
Labels: T-Defect

#12539 Tooltip: Use `RovingAccessibleButton` instead of `RovingAccessibleTooltipButton`
  src/accessibility/RovingTabIndex.tsx
  src/accessibility/roving/RovingAccessibleTooltipButton.tsx
  src/components/structures/UserMenu.tsx
  src/components/views/messages/DownloadActionButton.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/pips/WidgetPip.tsx
  src/components/views/rooms/EventTile/EventTileThreadToolbar.tsx
  src/components/views/rooms/ExtraTile.tsx
  src/components/views/rooms/MessageComposerFormatBar.tsx
  test/components/views/rooms/__snapshots__/ExtraTile-test.tsx.snap
Labels: T-Task

#12522 Tooltip: migrate remaining tooltips from `AccessibleTooltipButton` to `AccessibleButton`
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/beta/BetaCard.tsx
  src/components/views/elements/AccessibleTooltipButton.tsx
  src/components/views/settings/devices/DeviceExpandDetailsButton.tsx
  test/components/views/auth/InteractiveAuthEntryComponents-test.tsx
  test/components/views/auth/__snapshots__/InteractiveAuthEntryComponents-test.tsx.snap
Labels: T-Task

#12545 Fix E2E icon display in room header
  playwright/e2e/room/room-header.spec.ts
  playwright/snapshots/room/room-header.spec.ts/encrypted-room-header-linux.png
  res/css/views/rooms/_LegacyRoomHeader.pcss
Labels: T-Defect

#12544 Refactor some logic into common AvatarSetting component
  playwright/e2e/settings/general-user-settings-tab.spec.ts
  res/css/views/settings/_AvatarSetting.pcss
  res/css/views/settings/_ProfileSettings.pcss
  src/components/views/room_settings/RoomProfileSettings.tsx
  src/components/views/settings/AvatarSetting.tsx
  src/components/views/settings/ProfileSettings.tsx
  test/components/views/room_settings/RoomProfileSettings-test.tsx
  test/components/views/settings/AvatarSetting-test.tsx
Labels: T-Task

#12547 Remove code smell assertion identified by Sonar
  src/SlidingSyncManager.ts
Labels: Z-Community-PR, T-Task

#12516 Report verification and recovery state to posthog
  package.json
  src/DeviceListener.ts
  test/DeviceListener-test.ts
  yarn.lock
Labels: T-Task

#12542 Migrate `TooltipTarget` usage to compound `Tooltip`
  playwright/snapshots/threads/threads.spec.ts/Reply-to-the-location-on-ThreadView-linux.png
  res/css/components/views/elements/_AppPermission.pcss
  src/components/views/elements/AppPermission.tsx
  src/components/views/elements/RoomTopic.tsx
  src/components/views/elements/TooltipTarget.tsx
  src/components/views/messages/MLocationBody.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/elements/RoomTopic-test.tsx
  test/components/views/elements/TooltipTarget-test.tsx
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/components/views/elements/__snapshots__/TooltipTarget-test.tsx.snap
  test/components/views/messages/__snapshots__/MLocationBody-test.tsx.snap
Labels: T-Task

#12549 Tooltip: Use tooltip compound instead of react-sdk tooltip
  src/components/views/elements/Tooltip.tsx
  src/components/views/messages/ReactionsRowButton.tsx
  src/components/views/messages/ReactionsRowButtonTooltip.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/ReadReceiptGroup.tsx
  src/i18n/strings/en_EN.json
  src/utils/useTooltip.tsx
  test/components/views/messages/ReactionsRowButton-test.tsx
  test/components/views/messages/__snapshots__/ReactionsRowButton-test.tsx.snap
  test/components/views/rooms/ReadReceiptGroup-test.tsx
  test/components/views/rooms/__snapshots__/ReadReceiptGroup-test.tsx.snap
Labels: T-Task

#12552 Add seedrandom dep to `resolutions`
  package.json
  yarn.lock
Labels: T-Task

#12555 Avoid using deprecated exports, fields, and duplicate code
  src/MatrixClientPeg.ts
  src/SecurityManager.ts
  src/components/views/dialogs/CreateRoomDialog.tsx
  src/components/views/dialogs/ServerOfflineDialog.tsx
  src/components/views/dialogs/devtools/ServerInfo.tsx
  src/components/views/directory/NetworkDropdown.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/hooks/usePublicRoomDirectory.ts
  src/rageshake/submit-rageshake.ts
  src/utils/AutoDiscoveryUtils.tsx
  src/utils/PasswordScorer.ts
  src/utils/device/dehydration.ts
  src/utils/dm/createDmLocalRoom.ts
  test/DeviceListener-test.ts
  test/PosthogAnalytics-test.ts
  test/TextForEvent-test.ts
  test/components/structures/RoomView-test.tsx
  test/components/views/dialogs/SpotlightDialog-test.tsx
  test/components/views/dialogs/security/CreateSecretStorageDialog-test.tsx
  test/components/views/dialogs/security/ExportE2eKeysDialog-test.tsx
  test/components/views/dialogs/security/ImportE2eKeysDialog-test.tsx
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/components/views/rooms/EventTile-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/createRoom-test.ts
  test/hooks/usePublicRoomDirectory-test.tsx
  test/hooks/useUserDirectory-test.tsx
  test/stores/SetupEncryptionStore-test.ts
  test/submit-rageshake-test.ts
  test/test-utils/test-utils.ts
  test/toasts/UnverifiedSessionToast-test.tsx
  test/utils/AutoDiscoveryUtils-test.tsx
Labels: T-Task

#12556 Fix tabbedview breakpoint width
  res/css/structures/_TabbedView.pcss
Labels: T-Defect

#12553 Tooltip: close field tooltip when ESC is pressed
  src/components/views/elements/Field.tsx
  test/components/views/elements/Field-test.tsx
Labels: T-Defect

#12559 Close the release announcement when a dialog is opened
  src/Modal.tsx
  src/hooks/useIsReleaseAnnouncementOpen.ts
  src/stores/ReleaseAnnouncementStore.ts
  test/components/structures/ReleaseAnnouncement-test.tsx
Labels: X-Release-Blocker, T-Defect

#12571 Pin playwright synapse docker image to 2 days ago
  .github/workflows/playwright-image-updates.yaml
  playwright/plugins/homeserver/synapse/index.ts
Labels: T-Task
