Repository matrix-org/matrix-react-sdk, pull requests merged in 2024-08, with the labels that each got.

#11726 Ignore permalink_prefix when serializing pills
  src/editor/serialize.ts
  src/utils/permalinks/Permalinks.ts
  test/editor/serialize-test.ts
  test/utils/permalinks/Permalinks-test.ts
Labels: Z-Community-PR, T-Defect

#12855 Fix React contexts
  src/components/structures/EmbeddedPage.tsx
  src/components/structures/FilePanel.tsx
  src/components/structures/NotificationPanel.tsx
  src/components/structures/RoomStatusBar.tsx
  src/components/structures/ThreadView.tsx
  src/components/structures/UserView.tsx
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/location/LocationPicker.tsx
  src/components/views/messages/EditHistoryMessage.tsx
  src/components/views/messages/MAudioBody.tsx
  src/components/views/messages/MFileBody.tsx
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MLocationBody.tsx
  src/components/views/messages/MPollBody.tsx
  src/components/views/messages/MVideoBody.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/messages/TextualBody.tsx
  src/components/views/right_panel/TimelineCard.tsx
  src/components/views/rooms/Autocomplete.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/rooms/MessageComposer.tsx
  src/components/views/rooms/ReplyPreview.tsx
  src/components/views/rooms/RoomList.tsx
  src/components/views/rooms/VoiceRecordComposerTile.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/components/views/settings/tabs/user/VoiceUserSettingsTab.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  test/components/views/context_menus/MessageContextMenu-test.tsx
  test/components/views/messages/MLocationBody-test.tsx
  test/components/views/messages/MVideoBody-test.tsx
  test/components/views/rooms/RoomList-test.tsx
Labels: T-Task

#12793 Align RoomSummaryCard styles with Figma
  playwright/e2e/polls/pollHistory.spec.ts
  playwright/snapshots/crypto/crypto.spec.ts/RoomSummaryCard-with-verified-e2ee-linux.png
  playwright/snapshots/right-panel/right-panel.spec.ts/with-name-and-address-linux.png
  playwright/snapshots/settings/general-room-settings-tab.spec.ts/General-room-settings-tab-should-be-rendered-properly-1-linux.png
  res/css/views/right_panel/_RoomSummaryCard.pcss
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/RoomSettingsDialog-test.tsx
  test/components/views/dialogs/__snapshots__/RoomSettingsDialog-test.tsx.snap
  test/components/views/polls/pollHistory/PollHistory-test.tsx
  test/components/views/polls/pollHistory/__snapshots__/PollHistory-test.tsx.snap
  test/components/views/right_panel/RoomSummaryCard-test.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
Labels: T-Enhancement

#11756 Invite dialog: display MXID on its own line
  res/css/views/rooms/_RoomPreviewBar.pcss
  src/components/views/rooms/RoomPreviewBar.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
Labels: T-Enhancement

#12856 Convert general user settings to functional component
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
Labels: T-Task

#12860 Preparations for React 18
  src/components/structures/GenericDropdownMenu.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/structures/auth/Registration.tsx
  src/components/views/avatars/BaseAvatar.tsx
  src/components/views/dialogs/spotlight/Option.tsx
  src/components/views/directory/NetworkDropdown.tsx
  src/components/views/elements/PersistentApp.tsx
  src/components/views/messages/RoomPredecessorTile.tsx
  src/components/views/messages/TextualEvent.tsx
  src/components/views/messages/TimelineSeparator.tsx
  src/components/views/pips/WidgetPip.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/settings/UserProfileSettings.tsx
  src/components/views/spaces/QuickSettingsButton.tsx
  src/hooks/useAccountData.ts
  src/languageHandler.tsx
Labels: T-Task

#12859 Clear settings caches on reset rather than custom lifecycle method
  src/Lifecycle.ts
  src/settings/handlers/AbstractLocalStorageSettingsHandler.ts
Labels: T-Task

#12798 Fixed custom emotes background color #27745
  res/css/views/rooms/_EventTile.pcss
Labels: Z-Community-PR, T-Defect

#12862 Fix formatting of rich text emotes
  playwright/e2e/messages/messages.spec.ts
  playwright/snapshots/messages/messages.spec.ts/emote-rich-ltr-ltrdisplayname-linux.png
  playwright/snapshots/messages/messages.spec.ts/emote-rich-ltr-rtldisplayname-linux.png
  playwright/snapshots/messages/messages.spec.ts/emote-rich-rtl-ltrdisplayname-linux.png
  playwright/snapshots/messages/messages.spec.ts/emote-rich-rtl-rtldisplayname-linux.png
  res/css/views/rooms/_EventTile.pcss
Labels: T-Defect

#12865 Add missing presence indicator to new room header
  res/css/_components.pcss
  res/css/views/avatars/_WithPresenceIndicator.pcss
  src/components/views/avatars/WithPresenceIndicator.tsx
  src/components/views/rooms/PresenceLabel.tsx
  src/components/views/rooms/RoomHeader.tsx
  test/components/views/avatars/WithPresenceIndicator-test.tsx
  test/components/views/avatars/__snapshots__/WithPresenceIndicator-test.tsx.snap
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
Labels: T-Defect

#12863 Disable jump to read receipt button instead of hiding when nothing to jump to
  playwright/snapshots/user-view/user-view.spec.ts/user-info-linux.png
  src/components/views/right_panel/UserInfo.tsx
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
Labels: T-Enhancement

#12867 Update settings tab icons
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-smallscreen-linux.png
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
  res/css/structures/_TabbedView.pcss
  res/css/views/dialogs/_UserSettingsDialog.pcss
  src/components/structures/TabbedView.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  test/components/views/dialogs/__snapshots__/UserSettingsDialog-test.tsx.snap
Labels: T-Enhancement

#12869 Switch to ghcr.io image for Synapse
  .github/workflows/playwright-image-updates.yaml
  docs/playwright.md
  playwright/plugins/homeserver/synapse/index.ts
Labels: T-Task

#12841 Rename general user settings to account
  playwright/e2e/oidc/oidc-aware.spec.ts
  playwright/e2e/oidc/oidc-native.spec.ts
  playwright/e2e/settings/account-user-settings-tab.spec.ts
  playwright/snapshots/settings/account-user-settings-tab.spec.ts/account-linux.png
  playwright/snapshots/settings/account-user-settings-tab.spec.ts/account-smallscreen-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-smallscreen-linux.png
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/dialogs/UserTab.ts
  src/components/views/settings/notifications/NotificationPusherSettings.tsx
  src/components/views/settings/tabs/user/AccountUserSettingsTab.tsx
  src/hooks/useUserOnboardingTasks.ts
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/UserSettingsDialog-test.tsx
  test/components/views/dialogs/__snapshots__/UserSettingsDialog-test.tsx.snap
  test/components/views/settings/tabs/user/AccountUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/AccountUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#12861 Make tests more resilient for React 18 upgrade
  test/components/structures/MatrixChat-test.tsx
  test/components/structures/UserMenu-test.tsx
  test/components/views/dialogs/AccessSecretStorageDialog-test.tsx
  test/components/views/dialogs/InviteDialog-test.tsx
  test/components/views/dialogs/MessageEditHistoryDialog-test.tsx
  test/components/views/dialogs/RoomSettingsDialog-test.tsx
  test/components/views/dialogs/UserSettingsDialog-test.tsx
  test/components/views/elements/Field-test.tsx
  test/components/views/elements/SearchWarning-test.tsx
  test/components/views/elements/SpellCheckLanguagesDropdown-test.tsx
  test/components/views/messages/MImageBody-test.tsx
  test/components/views/messages/MLocationBody-test.tsx
  test/components/views/messages/MPollEndBody-test.tsx
  test/components/views/polls/pollHistory/PollHistory-test.tsx
  test/components/views/polls/pollHistory/PollListItemEnded-test.tsx
  test/components/views/right_panel/LegacyRoomHeaderButtons-test.tsx
  test/components/views/right_panel/PinnedMessagesCard-test.tsx
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/rooms/MemberList-test.tsx
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/RoomHeader/VideoRoomChatButton-test.tsx
  test/components/views/rooms/RoomPreviewBar-test.tsx
  test/components/views/settings/Notifications-test.tsx
  test/components/views/settings/SetIntegrationManager-test.tsx
  test/components/views/settings/devices/DeviceDetailHeading-test.tsx
  test/components/views/settings/devices/FilteredDeviceList-test.tsx
  test/components/views/settings/discovery/EmailAddresses-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/hooks/useNotificationSettings-test.tsx
  test/hooks/useUserOnboardingTasks-test.tsx
  test/languageHandler-test.tsx
  test/modules/ProxiedModuleApi-test.tsx
  test/test-utils/client.ts
  test/voice-broadcast/components/molecules/VoiceBroadcastPreRecordingPip-test.tsx
  test/voice-broadcast/components/molecules/VoiceBroadcastRecordingPip-test.tsx
Labels: T-Task

#12871 Import base64 utils directly from js-sdk
  playwright/e2e/timeline/timeline.spec.ts
  src/utils/tokens/pickling.ts
Labels: T-Task

#12850 Clean up editor drafts for unknown rooms
  src/DraftCleaner.ts
  src/components/structures/MatrixChat.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  test/components/structures/MatrixChat-test.tsx
Labels: T-Enhancement

#12828 Rich text Editor: Auto-replace plain text emoticons with emoji
  package.json
  src/components/views/rooms/wysiwyg_composer/components/PlainTextComposer.tsx
  src/components/views/rooms/wysiwyg_composer/components/WysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/usePlainTextListeners.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
  test/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/hooks/useSuggestion-test.tsx
  yarn.lock
Labels: T-Enhancement

#12866 Stop the ongoing ring if another device joins the call session.
  src/toasts/IncomingCallToast.tsx
Labels: T-Enhancement

#12714 Delayed events (Futures) / MSC4140 for call widget
  package.json
  src/stores/widgets/StopGapWidgetDriver.ts
  test/stores/widgets/StopGapWidgetDriver-test.ts
  test/test-utils/test-utils.ts
  yarn.lock
Labels: Z-Experiment, T-Enhancement

#12876 Update @vector-im/compound-design-tokens
  package.json
  playwright/snapshots/app-loading/feature-detection.spec.ts/unsupported-browser-CompatibilityView-linux.png
  playwright/snapshots/chat-export/html-export.spec.ts/html-export-linux.png
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-bubble-layout-linux.png
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-group-layout-linux.png
  playwright/snapshots/release-announcement/releaseAnnouncement.spec.ts/release-announcement-Threads-Activity-Centre-linux.png
  playwright/snapshots/right-panel/notification-panel.spec.ts/empty-linux.png
  playwright/snapshots/settings/account-user-settings-tab.spec.ts/account-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
  playwright/snapshots/spaces/spaces.spec.ts/space-panel-expanded-linux.png
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-button-expanded-linux.png
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-hovered-expanded-linux.png
  playwright/snapshots/threads/threads.spec.ts/Reply-to-the-location-on-ThreadView-linux.png
  playwright/snapshots/user-onboarding/user-onboarding-new.spec.ts/User-Onboarding-new-user-page-is-shown-and-preference-exists-1-linux.png
  playwright/snapshots/user-view/user-view.spec.ts/user-info-linux.png
  res/css/structures/_ToastContainer.pcss
  res/css/views/right_panel/_BaseCard.pcss
  res/css/views/right_panel/_UserInfo.pcss
  res/css/views/user-onboarding/_UserOnboardingTask.pcss
  test/components/views/dialogs/__snapshots__/UserSettingsDialog-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
  yarn.lock
Labels: T-Task

#12883 Show spinner whilst initial search request is in progress
  src/components/views/rooms/RoomSearchAuxPanel.tsx
Labels: T-Defect

#12882 Add chat button on new room header for maximised widgets
  playwright/snapshots/room/room-header.spec.ts/room-header-video-room-linux.png
  src/components/structures/RoomView.tsx
  src/components/views/rooms/RoomHeader.tsx
  test/components/views/rooms/RoomHeader-test.tsx
Labels: T-Defect

#12884 Refactor the various email/phone management UI into a single component
  res/css/_components.pcss
  res/css/components/views/settings/_AddRemoveThreepids.pcss
  src/AddThreepid.ts
  src/components/views/settings/AddRemoveThreepids.tsx
  src/components/views/settings/UserPersonalInfoSettings.tsx
  src/components/views/settings/account/EmailAddresses.tsx
  src/components/views/settings/account/PhoneNumbers.tsx
  src/components/views/settings/discovery/DiscoverySettings.tsx
  src/components/views/settings/discovery/EmailAddresses.tsx
  src/components/views/settings/discovery/PhoneNumbers.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/AddRemoveThreepids-test.tsx
  test/components/views/settings/__snapshots__/AddRemoveThreepids-test.tsx.snap
  test/components/views/settings/account/PhoneNumbers-test.tsx
  test/components/views/settings/account/__snapshots__/PhoneNumbers-test.tsx.snap
  test/components/views/settings/discovery/EmailAddresses-test.tsx
  test/components/views/settings/discovery/PhoneNumbers-test.tsx
  test/components/views/settings/discovery/__snapshots__/EmailAddresses-test.tsx.snap
  test/components/views/settings/discovery/__snapshots__/PhoneNumbers-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/AccountUserSettingsTab-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Task

#12888 Hide pinned messages when grouped in timeline when feature pinning is disabled
  src/components/structures/grouper/MainGrouper.tsx
Labels: T-Defect

#12878 Tweak UIA postMessage check to work cross-origin
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
Labels: T-Enhancement

#12825 Message Pinning: rework the message pinning list in the right panel
  playwright/e2e/pinned-messages/index.ts
  playwright/e2e/pinned-messages/pinned-messages.spec.ts
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-messages-list-empty-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-messages-list-messages-2-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-messages-list-messages-3-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/unpin-all-dialog-linux.png
  res/css/_common.pcss
  res/css/_components.pcss
  res/css/views/dialogs/_UnpinAllDialog.pcss
  res/css/views/right_panel/_PinnedMessagesCard.pcss
  res/css/views/rooms/_PinnedEventTile.pcss
  src/components/structures/RightPanel.tsx
  src/components/views/dialogs/UnpinAllDialog.tsx
  src/components/views/right_panel/PinnedMessagesCard.tsx
  src/components/views/rooms/PinnedEventTile.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/UnpinAllDialog-test.tsx
  test/components/views/dialogs/__snapshots__/UnpinAllDialog-test.tsx.snap
  test/components/views/right_panel/PinnedMessagesCard-test.tsx
  test/components/views/right_panel/__snapshots__/PinnedMessagesCard-test.tsx.snap
  test/components/views/rooms/PinnedEventTile-test.tsx
  test/components/views/rooms/__snapshots__/PinnedEventTile-test.tsx.snap
Labels: T-Enhancement

#12895 Ensure elements on Login page are disabled when in-flight
  src/components/structures/auth/Login.tsx
  src/components/views/elements/SSOButtons.tsx
  src/components/views/elements/ServerPicker.tsx
Labels: T-Defect

#12897 Add Pin/Unpin action in quick access of the message action bar
  playwright/e2e/pinned-messages/index.ts
  playwright/e2e/pinned-messages/pinned-messages.spec.ts
  res/css/views/context_menus/_MessageContextMenu.pcss
  src/components/views/context_menus/MessageContextMenu.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/utils/PinningUtils.ts
  test/components/views/context_menus/MessageContextMenu-test.tsx
  test/components/views/messages/MessageActionBar-test.tsx
  test/utils/PinningUtils-test.ts
Labels: T-Enhancement

#12902 Add thread information in pinned message list
  res/css/views/rooms/_PinnedEventTile.pcss
  src/components/views/rooms/PinnedEventTile.tsx
  src/i18n/strings/en_EN.json
  test/components/views/rooms/PinnedEventTile-test.tsx
  test/components/views/rooms/__snapshots__/PinnedEventTile-test.tsx.snap
Labels: T-Enhancement

#12906 Set entrypoints to use ./lib rather than ./src
  package.json
Labels: T-Task

#12904 Rename prettier config file to .cjs (staging version)
  .github/workflows/static_analysis.yaml
  .prettierrc.cjs
Labels: T-Task

#12674 RTE drafts
  playwright/e2e/composer/RTE.spec.ts
  src/DraftCleaner.ts
  src/components/views/rooms/MessageComposer.tsx
  test/components/structures/MatrixChat-test.tsx
  test/components/views/rooms/MessageComposer-test.tsx
Labels: T-Enhancement

#12919 Remove unused CryptoCallbacks implementations
  src/MatrixClientPeg.ts
  src/SecurityManager.ts
  test/MatrixClientPeg-test.ts
Labels: T-Task

#12928 Ignore desktop for minimum browser support.
  package.json
  src/SupportedBrowser.ts
  yarn.lock
Labels: T-Defect

#12893 Add a config option to control the default widget container height
  src/IConfigOptions.ts
  src/components/views/rooms/AppsDrawer.tsx
  test/components/views/rooms/AppsDrawer-test.tsx
Labels: T-Enhancement

#12933 Rename all the slow reporter stuff to cjs
  jest.config.ts
  test/slowReporter.cjs
Labels: T-Task

#12932 Install deja-vu font in docker image
  playwright/Dockerfile
Labels: T-Task

#12934 Fix pin/unpin slowness and non refresh from the message action bar
  src/components/views/messages/MessageActionBar.tsx
  src/utils/EventUtils.ts
  src/utils/PinningUtils.ts
  test/components/views/messages/MessageActionBar-test.tsx
  test/utils/PinningUtils-test.ts
Labels: T-Defect

#12929 Fix reply message truncation on 2 lines
  playwright/e2e/messages/messages.spec.ts
  playwright/snapshots/messages/messages.spec.ts/reply-message-ltr-ltrdisplayname-linux.png
  playwright/snapshots/messages/messages.spec.ts/reply-message-ltr-rtldisplayname-linux.png
  playwright/snapshots/messages/messages.spec.ts/reply-message-trl-ltrdisplayname-linux.png
  playwright/snapshots/messages/messages.spec.ts/reply-message-trl-rtldisplayname-linux.png
  res/css/views/elements/_ReplyChain.pcss
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/_ReplyTile.pcss
Labels: T-Defect

#12917 Display pinned messages on a banner at the top of a room
  playwright/e2e/pinned-messages/index.ts
  playwright/e2e/pinned-messages/pinned-messages.spec.ts
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-1-Msg1-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-2-Msg1-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-2-Msg2-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-2-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-4-Msg1-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-4-Msg2-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-4-Msg3-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-4-Msg4-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-messages-list-messages-2-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-messages-list-messages-3-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-messages-list-pin-3-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-messages-list-unpin-2-linux.png
  res/css/_components.pcss
  res/css/views/rooms/_PinnedMessageBanner.pcss
  src/components/structures/RoomView.tsx
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/right_panel/LegacyRoomHeaderButtons.tsx
  src/components/views/right_panel/PinnedMessagesCard.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/PinnedMessageBanner.tsx
  src/hooks/usePinnedEvents.ts
  src/i18n/strings/en_EN.json
  src/utils/PinningUtils.ts
  test/components/views/right_panel/PinnedMessagesCard-test.tsx
  test/components/views/rooms/PinnedMessageBanner-test.tsx
  test/components/views/rooms/__snapshots__/PinnedMessageBanner-test.tsx.snap
  test/utils/PinningUtils-test.ts
Labels: T-Enhancement

#12939 Fix JS-SDK failing import
  playwright/tsconfig.json
  tsconfig.json
Labels: T-Task

#12931 Implement download_file in widget driver
  package.json
  src/stores/widgets/StopGapWidgetDriver.ts
  test/stores/widgets/StopGapWidgetDriver-test.ts
  yarn.lock
Labels: X-Release-Blocker, Z-Community-PR, T-Enhancement

#12937 Sort the pinning message list in the same order than the banner. By timeline order.
  src/components/views/right_panel/PinnedMessagesCard.tsx
  test/components/views/right_panel/PinnedMessagesCard-test.tsx
  test/components/views/right_panel/__snapshots__/PinnedMessagesCard-test.tsx.snap
Labels: T-Enhancement
