Repository matrix-org/matrix-react-sdk, pull requests merged in 2024-01, with the labels that each got.

#12082 Prepare for switching AccessibleTooltipButton to using Compound Tooltips
  playwright/e2e/room-directory/room-directory.spec.ts
  res/css/_common.pcss
  src/components/views/elements/SettingsFlag.tsx
  test/components/views/dialogs/__snapshots__/DevtoolsDialog-test.tsx.snap
  test/components/views/settings/__snapshots__/FontScalingPanel-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/PreferencesUserSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SecurityUserSettingsTab-test.tsx.snap
Labels: T-Task

#12074 Added meaning full error message based on platform
  src/MatrixClientPeg.ts
  src/i18n/strings/en_EN.json
  test/MatrixClientPeg-test.ts
Labels: Z-Community-PR, T-Defect

#12101 Update teams names in CODEOWNERS
  .github/CODEOWNERS
Labels: T-Task

#12100 Fix regression around read receipt animation from refs changes
  src/NodeAnimator.tsx
  src/components/views/rooms/ReadReceiptMarker.tsx
Labels: X-Release-Blocker, T-Defect

#12077 Add RoomKnocksBar to RoomHeader
  src/components/views/rooms/RoomHeader.tsx
  test/components/views/rooms/RoomHeader-test.tsx
Labels: Z-Community-PR, T-Enhancement

#12102 Revert "Set up key backup using non-deprecated APIs (#12005)"
  playwright/e2e/crypto/backups.spec.ts
  playwright/e2e/crypto/utils.ts
  playwright/e2e/crypto/verification.spec.ts
  playwright/element-web-test.ts
  playwright/pages/ElementAppPage.ts
  src/SecurityManager.ts
  src/async-components/views/dialogs/security/CreateKeyBackupDialog.tsx
  test/SecurityManager-test.ts
  test/components/views/dialogs/security/CreateKeyBackupDialog-test.tsx
  test/components/views/dialogs/security/__snapshots__/CreateKeyBackupDialog-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Defect, backport staging

#12106 Fix a fresh login creating a new key backup
  playwright/e2e/crypto/backups.spec.ts
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/crypto/utils.ts
  playwright/e2e/crypto/verification.spec.ts
  playwright/element-web-test.ts
  playwright/pages/ElementAppPage.ts
  src/SecurityManager.ts
  src/async-components/views/dialogs/security/CreateKeyBackupDialog.tsx
  src/components/views/settings/CrossSigningPanel.tsx
  test/SecurityManager-test.ts
  test/components/views/dialogs/security/CreateKeyBackupDialog-test.tsx
  test/components/views/dialogs/security/__snapshots__/CreateKeyBackupDialog-test.tsx.snap
  test/components/views/settings/CrossSigningPanel-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SecurityUserSettingsTab-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Defect

#12105 fix: microphone and camera dropdown doesn't work In legacy call
  src/components/views/voip/LegacyCallView/LegacyCallViewButtons.tsx
Labels: X-Release-Blocker, Z-Community-PR, T-Defect

#12103 Factor out post-login splash screen to a new component
  res/css/_components.pcss
  res/css/structures/_MatrixChat.pcss
  res/css/structures/auth/_LoginSplashView.pcss
  src/components/structures/MatrixChat.tsx
  src/components/structures/auth/LoginSplashView.tsx
  test/components/structures/auth/LoginSplashView-test.tsx
  test/components/structures/auth/__snapshots__/LoginSplashView-test.tsx.snap
Labels: T-Task

#12066 Playwright: Convert `e2e/threads`
  cypress/e2e/threads/threads.spec.ts
  playwright/e2e/threads/threads.spec.ts
  playwright/pages/client.ts
  playwright/snapshots/threads/threads.spec.ts/Reply-to-the-location-on-ThreadView-linux.png
Labels: T-Task

#12062 Accessibility improvements around aria-labels and tooltips
  src/components/views/audio_messages/SeekBar.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/i18n/strings/en_EN.json
  test/components/views/audio_messages/__snapshots__/SeekBar-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPlaybackBody-test.tsx.snap
Labels: T-Enhancement

#12081 Update tests not to mock out an ancient server
  test/components/structures/MatrixChat-test.tsx
  test/components/structures/auth/Registration-test.tsx
  test/components/views/dialogs/ServerPickerDialog-test.tsx
Labels: T-Task

#12061 Shard Jest tests to run complete them faster
  .github/workflows/sonarqube.yml
  .github/workflows/tests.yml
Labels: T-Task

#12069 fix: removed stray semicolon on sign-out confirm model
  src/components/views/dialogs/LogoutDialog.tsx
Labels: Z-Community-PR, T-Task

#12109 Fix Identity Server terms accepting not working as expected
  src/IdentityAuthClient.tsx
Labels: T-Defect

#12111 Only retry Jest tests in CI mode
  test/setupTests.ts
Labels: T-Task

#12094 Fix regression around CSS stacking contexts and PIP widgets
  res/css/_common.pcss
  res/css/components/views/pips/_WidgetPip.pcss
  res/css/views/rooms/_AppsDrawer.pcss
  src/components/structures/PipContainer.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/elements/PersistedElement.tsx
  src/components/views/elements/PersistentApp.tsx
  src/components/views/pips/WidgetPip.tsx
  test/components/structures/PipContainer-test.tsx
Labels: X-Release-Blocker, T-Defect

#12113 Add CODEOWNERS for crypto-sensitive areas
  .github/CODEOWNERS
Labels: T-Task

#12065 Playwright: Convert /e2e/polls
  cypress/e2e/dummy.spec.ts
  cypress/e2e/polls/pollHistory.spec.ts
  cypress/e2e/polls/polls.spec.ts
  playwright/e2e/polls/pollHistory.spec.ts
  playwright/e2e/polls/polls.spec.ts
  playwright/snapshots/polls/polls.spec.ts/Polls-Timeline-tile-no-votes-linux.png
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-bubble-layout-linux.png
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-group-layout-linux.png
Labels: T-Task

#12126 Fix Stickerpicker layout crossing multiple CSS stacking contexts
  src/components/views/rooms/Stickerpicker.tsx
Labels: X-Release-Blocker, T-Defect, backport staging

#12098 Set up key backup using non-deprecated APIs (2nd take)
  playwright/e2e/crypto/backups.spec.ts
  playwright/pages/ElementAppPage.ts
  src/SecurityManager.ts
  src/async-components/views/dialogs/security/CreateKeyBackupDialog.tsx
  test/SecurityManager-test.ts
  test/components/views/dialogs/security/CreateKeyBackupDialog-test.tsx
  test/components/views/dialogs/security/__snapshots__/CreateKeyBackupDialog-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Task, T-Defect

#12129 Fix OIDC end to end test which failed since Synapse updated authlib
  playwright/plugins/homeserver/synapse/templates/default/homeserver.yaml
Labels: T-Task

#12125 Cleanup tasks in the Settings code
  src/components/views/elements/SettingsFlag.tsx
  src/components/views/settings/CryptographyPanel.tsx
  src/components/views/settings/E2eAdvancedPanel.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/settings/Settings.tsx
  src/settings/SettingsStore.ts
  test/components/views/settings/tabs/user/PreferencesUserSettingsTab-test.tsx
Labels: T-Task

#11809 Gracefully handle rate limit response when attempting to Sign in with QR
  src/components/views/auth/LoginWithQR.tsx
  src/components/views/auth/LoginWithQRFlow.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/LoginWithQR-test.tsx
  test/components/views/settings/devices/LoginWithQRFlow-test.tsx
  test/components/views/settings/devices/__snapshots__/LoginWithQRFlow-test.tsx.snap
Labels: T-Task

#12140 Add test for useRoomThreadNotifications
  test/hooks/room/useRoomThreadNotifications-test.tsx
Labels: T-Task

#12141 Change Quick Settings icon
  playwright/snapshots/spaces/spaces.spec.ts/space-panel-collapsed-linux.png
  playwright/snapshots/spaces/spaces.spec.ts/space-panel-expanded-linux.png
  res/css/structures/_QuickSettingsButton.pcss
Labels: T-Enhancement

#11016 Fix Safari IME support
  src/components/views/rooms/BasicMessageComposer.tsx
Labels: Z-Community-PR, T-Defect

#12138 Don't reference the notification levels by colour
  res/css/views/rooms/_LegacyRoomHeader.pcss
  res/css/views/rooms/_ThreadSummary.pcss
  src/RoomNotifs.ts
  src/components/structures/MatrixChat.tsx
  src/components/views/context_menus/RoomGeneralContextMenu.tsx
  src/components/views/dialogs/devtools/RoomNotifications.tsx
  src/components/views/right_panel/HeaderButtons.tsx
  src/components/views/right_panel/LegacyRoomHeaderButtons.tsx
  src/components/views/rooms/NotificationBadge.tsx
  src/components/views/rooms/NotificationBadge/StatelessNotificationBadge.tsx
  src/components/views/rooms/NotificationBadge/UnreadNotificationBadge.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomHeader/VideoRoomChatButton.tsx
  src/components/views/rooms/RoomSublist.tsx
  src/components/views/rooms/VoiceRecordComposerTile.tsx
  src/components/views/settings/notifications/NotificationSettings2.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
  src/hooks/room/useRoomThreadNotifications.ts
  src/hooks/useUnreadNotifications.ts
  src/i18n/strings/en_EN.json
  src/stores/notifications/ListNotificationState.ts
  src/stores/notifications/NotificationLevel.ts
  src/stores/notifications/NotificationState.ts
  src/stores/notifications/RoomNotificationState.ts
  src/stores/notifications/RoomNotificationStateStore.ts
  src/stores/notifications/SpaceNotificationState.ts
  src/stores/notifications/StaticNotificationState.ts
  src/stores/notifications/SummarizedNotificationState.ts
  src/stores/room-list/algorithms/list-ordering/ImportanceAlgorithm.ts
  test/RoomNotifs-test.ts
  test/components/views/right_panel/LegacyRoomHeaderButtons-test.tsx
  test/components/views/rooms/NotificationBadge/NotificationBadge-test.tsx
  test/components/views/rooms/NotificationBadge/StatelessNotificationBadge-test.tsx
  test/components/views/rooms/RoomHeader/VideoRoomChatButton-test.tsx
  test/components/views/spaces/SpaceTreeLevel-test.tsx
  test/hooks/room/useRoomThreadNotifications-test.tsx
  test/hooks/useUnreadNotifications-test.ts
  test/stores/SpaceStore-test.ts
  test/stores/notifications/NotificationColor-test.ts
  test/stores/notifications/RoomNotificationState-test.ts
  test/stores/room-list/algorithms/list-ordering/ImportanceAlgorithm-test.ts
  test/stores/room-list/algorithms/list-ordering/NaturalAlgorithm-test.ts
Labels: T-Task

#11906 Fix missing device keys in rageshakes and sentry reports
  src/rageshake/submit-rageshake.ts
  src/sentry.ts
Labels: T-Task

#12144 Fix account management link for delegated auth OIDC setups
  src/stores/oidc/OidcClientStore.ts
  src/utils/oidc/getDelegatedAuthAccountUrl.ts
  test/utils/oidc/getDelegatedAuthAccountUrl-test.ts
Labels: T-Defect

#12147 Update Twemoji to Jdecked v15.0.3
  res/fonts/Twemoji_Mozilla/TwemojiMozilla-colr.woff2
  res/fonts/Twemoji_Mozilla/TwemojiMozilla-sbix.woff2
Labels: T-Enhancement

#12148 Update comments in settings logic
  src/settings/Settings.tsx
  src/settings/SettingsStore.ts
Labels: T-Task

#12114 Enable the rust-crypto labs button
  src/MatrixClientPeg.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/controllers/RustCryptoSdkController.ts
  test/MatrixClientPeg-test.ts
  test/components/views/settings/tabs/user/LabsUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/LabsUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#12149 Fixed shield alignment on message Input
  res/css/views/rooms/_MessageComposer.pcss
  src/components/views/rooms/MessageComposer.tsx
Labels: Z-Community-PR, T-Defect

#12152 Use Github Artifacts v4
  .github/workflows/element-web.yaml
  .github/workflows/end-to-end-tests.yaml
  .github/workflows/netlify.yaml
  .github/workflows/tests.yml
Labels: T-Task

#12154 Broaden support for matrix spec versions
  src/Lifecycle.ts
  test/Lifecycle-test.ts
Labels: T-Enhancement, backport staging

#12161 Open thread panel when thread clicked in Threads Activity Centre
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentre.tsx
Labels: T-Defect

#12071 Expose apps/widgets
  package.json
  src/modules/ProxiedModuleApi.ts
  test/components/views/rooms/wysiwyg_composer/utils/autocomplete-test.ts
  test/components/views/settings/AddPrivilegedUsers-test.tsx
  test/modules/ProxiedModuleApi-test.tsx
  test/stores/AutoRageshakeStore-test.ts
  test/stores/RoomViewStore-test.ts
  test/utils/SearchInput-test.ts
  test/voice-broadcast/components/VoiceBroadcastBody-test.tsx
  yarn.lock
Labels: Z-Community-PR, T-Enhancement

#12156 Make threads activity centre labs flag split out unread counts
  src/RoomNotifs.ts
  src/Unread.ts
  src/settings/Settings.tsx
  test/components/views/rooms/LegacyRoomHeader-test.tsx
  test/stores/RoomNotificationStateStore-test.ts
Labels: T-Enhancement

#12166 Fix OIDC bugs due to amnesiac stores forgetting OIDC issuer & other data
  src/utils/oidc/persistOidcSettings.ts
  test/components/structures/MatrixChat-test.tsx
  test/stores/oidc/OidcClientStore-test.ts
  test/utils/oidc/persistOidcSettings-test.ts
Labels: T-Defect

#12167 Use the StatelessNotificationBadge component in ThreadsActivityCentre
  res/css/structures/_ThreadsActivityCentre.pcss
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentre.tsx
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentreBadge.tsx
  src/components/views/spaces/threads-activity-centre/useUnreadThreadRooms.ts
Labels: T-Task

#12176 Playwright: Disable failing read-receipts test
  playwright/e2e/read-receipts/read-receipts.spec.ts
Labels: T-Task

#12175 Fix 1F97A and 1F979 in Twemoji COLR font
  res/fonts/Twemoji_Mozilla/TwemojiMozilla-colr.woff2
  res/fonts/Twemoji_Mozilla/TwemojiMozilla-sbix.woff2
Labels: X-Release-Blocker, T-Defect, backport staging

#12146 Add notification dots to thread summary icons
  package.json
  res/css/views/rooms/_NotificationBadge.pcss
  src/components/views/rooms/NotificationBadge/StatelessNotificationBadge.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/ThreadSummary.tsx
  src/hooks/room/useRoomThreadNotifications.ts
  src/utils/notifications.ts
  test/components/structures/TimelinePanel-test.tsx
  test/components/structures/__snapshots__/RoomStatusBar-test.tsx.snap
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/rooms/EventTile-test.tsx
  test/components/views/rooms/NotificationBadge/StatelessNotificationBadge-test.tsx
  test/components/views/rooms/NotificationBadge/UnreadNotificationBadge-test.tsx
  test/components/views/rooms/RoomHeader/__snapshots__/VideoRoomChatButton-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
  test/components/views/settings/notifications/__snapshots__/Notifications2-test.tsx.snap
  test/components/views/spaces/__snapshots__/SpaceTreeLevel-test.tsx.snap
  test/utils/notifications-test.ts
  yarn.lock
Labels: T-Enhancement

#12179 Add analytics to the TAC
  package.json
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentre.tsx
  yarn.lock
Labels: T-Task

#9271 Hide the "Message" button in the sidebar if the CreateRooms components should not be shown
  src/components/views/right_panel/UserInfo.tsx
  test/components/views/right_panel/UserInfo-test.tsx
Labels: Z-Community-PR, T-Enhancement

#12183 Fix display of room notification debug info
  src/components/views/dialogs/devtools/RoomNotifications.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/devtools/__snapshots__/RoomNotifications-test.tsx.snap
Labels: T-Defect

#12057 Refactor element call lobby + skip lobby
  playwright/e2e/room/room-header.spec.ts
  src/components/structures/RoomView.tsx
  src/components/views/beacon/RoomCallBanner.tsx
  src/components/views/elements/AppTile.tsx
  src/components/views/messages/CallEvent.tsx
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/components/views/rooms/LiveContentSummary.tsx
  src/components/views/rooms/RoomTileCallSummary.tsx
  src/components/views/voip/CallView.tsx
  src/dispatcher/payloads/ViewRoomPayload.ts
  src/hooks/room/useRoomCall.ts
  src/i18n/strings/en_EN.json
  src/models/Call.ts
  src/stores/RoomViewStore.tsx
  src/stores/WidgetStore.ts
  src/stores/widgets/StopGapWidget.ts
  src/toasts/IncomingCallToast.tsx
  src/utils/room/placeCall.ts
  test/components/structures/PipContainer-test.tsx
  test/components/views/messages/CallEvent-test.tsx
  test/components/views/rooms/LegacyRoomHeader-test.tsx
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/RoomTile-test.tsx
  test/components/views/voip/CallView-test.tsx
  test/models/Call-test.ts
  test/stores/room-list/algorithms/Algorithm-test.ts
  test/stores/widgets/StopGapWidget-test.ts
  test/toasts/IncomingCallToast-test.tsx
Labels: T-Enhancement

#12137 Add labs flag for Threads Activity Centre
  src/RoomNotifs.ts
  src/Unread.ts
  src/components/views/dialogs/devtools/RoomNotifications.tsx
  src/hooks/useUnreadNotifications.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/stores/notifications/RoomNotificationState.ts
  src/stores/notifications/RoomNotificationStateStore.ts
  test/RoomNotifs-test.ts
  test/Unread-test.ts
  test/components/views/rooms/LegacyRoomHeader-test.tsx
  test/components/views/rooms/RoomHeader/VideoRoomChatButton-test.tsx
  test/components/views/settings/tabs/user/LabsUserSettingsTab-test.tsx
  test/stores/RoomNotificationStateStore-test.ts
  test/stores/notifications/RoomNotificationState-test.ts
Labels: T-Enhancement

#12186 Update TAC label
  src/i18n/strings/en_EN.json
Labels: T-Task

#12182 Add `IndicatorIcon` to the TAC button
  res/css/structures/_ThreadsActivityCentre.pcss
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentre.tsx
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentreButton.tsx
  src/components/views/spaces/threads-activity-centre/useUnreadThreadRooms.ts
  src/utils/notifications.ts
Labels: T-Enhancement

#12192 Threads don't have activity if the room is muted
  src/Unread.ts
Labels: T-Defect

#12195 Re-use doesRoomHaveUnreadThreads for useRoomThreadNotifications
  src/hooks/room/useRoomThreadNotifications.ts
Labels: T-Defect

#12091 Add Element call related functionality to new room header
  src/components/structures/RoomView.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomHeader/VideoRoomChatButton.tsx
  src/hooks/room/useRoomCall.ts
  src/hooks/useCall.ts
  src/i18n/strings/en_EN.json
  src/models/Call.ts
  src/stores/widgets/StopGapWidget.ts
  src/toasts/IncomingCallToast.tsx
  src/utils/room/placeCall.ts
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/RoomHeader/VideoRoomChatButton-test.tsx
  test/components/views/rooms/RoomHeader/__snapshots__/VideoRoomChatButton-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
Labels: T-Enhancement

#12197 Add TAC description in labs
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Task

#12199 Fix position & size of dot on the tac button
  res/css/structures/_ThreadsActivityCentre.pcss
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentreButton.tsx
Labels: T-Defect
