Repository matrix-org/matrix-react-sdk, pull requests merged in 2024-02, with the labels that each got.

#12202 Saner Releases - allow pre-public testing (pack)
  package.json
Labels: T-Task

#12201 Hotfix fix: `waitForEvent` does resolve immediatly.
  src/models/Call.ts
Labels: T-Task, T-Defect

#12200 TAC: Utils tests
  src/Unread.ts
  test/Unread-test.ts
  test/utils/notifications-test.ts
Labels: T-Task

#12206 Support rust in StorageManager
  src/MatrixClientPeg.ts
  src/utils/StorageManager.ts
Labels: T-Task

#12205 Fix `Mark all as read` in settings
  src/Unread.ts
  src/components/views/settings/Notifications.tsx
  src/stores/ReadyWatchingStore.ts
  src/utils/notifications.ts
  test/Unread-test.ts
  test/components/views/settings/Notifications-test.tsx
Labels: T-Defect

#12208 Update to compound-web 3.0.1
  package.json
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/rooms/RoomHeader/__snapshots__/VideoRoomChatButton-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
  yarn.lock
Labels: T-Task

#12210 Disable flaky test: `should set inline start padding to a hidden event line`
  playwright/e2e/timeline/timeline.spec.ts
Labels: T-Task

#12211 Fix sending call notify
  src/models/Call.ts
Labels: T-Task

#12191 Fix logout can take ages
  playwright/e2e/crypto/logout.spec.ts
  src/components/structures/UserMenu.tsx
  test/components/structures/UserMenu-test.tsx
  test/components/structures/__snapshots__/UserMenu-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Defect

#12203 SettingsStore: Change feature_rust_crypto to default true
  playwright/e2e/crypto/staged-rollout.spec.ts
  playwright/element-web-test.ts
  src/settings/Settings.tsx
  test/MatrixClientPeg-test.ts
  test/components/structures/MatrixChat-test.tsx
  test/components/views/settings/tabs/user/LabsUserSettingsTab-test.tsx
Labels: T-Task

#12212 Fix narrow hover background on TAC button
  res/css/structures/_ThreadsActivityCentre.pcss
Labels: T-Defect

#12207 Add test for the ThreadsActivityCentre component
  test/components/views/spaces/ThreadsActivityCentre-test.tsx
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
Labels: T-Task

#12213 Remove stale release automation bits
  .github/workflows/release.yml
Labels: T-Task

#12225 Fix the StorageManger detecting a false positive consistency check when manually migrating to rust from labs
  package.json
  playwright/e2e/crypto/staged-rollout.spec.ts
  src/utils/StorageManager.ts
  test/utils/StorageManager-test.ts
  yarn.lock
Labels: T-Defect

#12226 Add caption for empty TAC
  res/css/structures/_ThreadsActivityCentre.pcss
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentre.tsx
  src/i18n/strings/en_EN.json
  test/components/views/spaces/ThreadsActivityCentre-test.tsx
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
Labels: T-Defect

#12231 Use the non-deprecated exportRoomKeys method on CryptoApi
  src/async-components/views/dialogs/security/ExportE2eKeysDialog.tsx
  test/components/views/dialogs/security/ExportE2eKeysDialog-test.tsx
Labels: T-Task

#12209 Use new semantic tokens for username colors
  package.json
  playwright/snapshots/crypto/crypto.spec.ts/RoomSummaryCard-with-verified-e2ee-linux.png
  playwright/snapshots/right-panel/right-panel.spec.ts/with-name-and-address-linux.png
  res/css/_common.pcss
  res/css/views/elements/_ReplyChain.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light-custom/css/_custom.pcss
  res/themes/light-high-contrast/css/_light-high-contrast.pcss
  res/themes/light/css/_light.pcss
  src/components/views/right_panel/RoomSummaryCard.tsx
  yarn.lock
Labels: T-Enhancement

#12227 Add playwright tests for the TAC
  playwright/e2e/spaces/threads-activity-centre/index.ts
  playwright/e2e/spaces/threads-activity-centre/threadsActivityCentre.spec.ts
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-no-indicator-linux.png
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-panel-mix-unread-linux.png
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-panel-notification-unread-linux.png
Labels: T-Task

#12136 Pop out of Threads Activity Centre
  package.json
  playwright/e2e/spaces/threads-activity-centre/index.ts
  playwright/e2e/spaces/threads-activity-centre/threadsActivityCentre.spec.ts
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-no-indicator-linux.png
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-panel-mix-unread-linux.png
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-panel-notification-unread-linux.png
  res/css/_components.pcss
  res/css/structures/_ThreadsActivityCentre.pcss
  src/Unread.ts
  src/components/views/avatars/DecoratedRoomAvatar.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentre.tsx
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentreButton.tsx
  src/components/views/spaces/threads-activity-centre/index.ts
  src/components/views/spaces/threads-activity-centre/useUnreadThreadRooms.ts
  src/hooks/room/useRoomThreadNotifications.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/utils/notifications.ts
  test/Unread-test.ts
  test/components/views/spaces/ThreadsActivityCentre-test.tsx
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
  test/utils/notifications-test.ts
  yarn.lock
Labels: T-Enhancement

#12234 Upgrade compound-web
  jest.config.ts
  package.json
  test/components/structures/__snapshots__/MessagePanel-test.tsx.snap
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/structures/__snapshots__/SpaceHierarchy-test.tsx.snap
  test/components/structures/__snapshots__/UserMenu-test.tsx.snap
  test/components/views/avatars/__snapshots__/DecoratedRoomAvatar-test.tsx.snap
  test/components/views/avatars/__snapshots__/RoomAvatar-test.tsx.snap
  test/components/views/beacon/__snapshots__/BeaconMarker-test.tsx.snap
  test/components/views/beacon/__snapshots__/BeaconViewDialog-test.tsx.snap
  test/components/views/beacon/__snapshots__/DialogSidebar-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ConfirmUserActionDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ManageRestrictedJoinRuleDialog-test.tsx.snap
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/components/views/elements/__snapshots__/FacePile-test.tsx.snap
  test/components/views/elements/__snapshots__/Pill-test.tsx.snap
  test/components/views/elements/__snapshots__/RoomFacePile-test.tsx.snap
  test/components/views/location/Marker-test.tsx
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/MLocationBody-test.tsx.snap
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/components/views/rooms/__snapshots__/MemberTile-test.tsx.snap
  test/components/views/rooms/__snapshots__/PinnedEventTile-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomPreviewBar-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomTile-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/PeopleRoomSettingsTab-test.tsx.snap
  test/components/views/spaces/__snapshots__/AddExistingToSpaceDialog-test.tsx.snap
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
  yarn.lock
Labels: T-Task, X-Upcoming-Release-Blocker

#12238 Fix TAC button alignment when expanded
  playwright/e2e/spaces/threads-activity-centre/index.ts
  playwright/e2e/spaces/threads-activity-centre/threadsActivityCentre.spec.ts
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-button-expanded-linux.png
  res/css/structures/_ThreadsActivityCentre.pcss
Labels: T-Defect

#12239 Reduce TAC width by `16px`
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-panel-mix-unread-linux.png
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-panel-notification-unread-linux.png
  res/css/structures/_ThreadsActivityCentre.pcss
Labels: T-Enhancement

#12235 New Header edgecase fixes: Close lobby button not shown, disable join button in various places, more...
  src/components/views/rooms/RoomHeader.tsx
  src/hooks/room/useRoomCall.ts
  src/hooks/useCall.ts
  src/toasts/IncomingCallToast.tsx
  test/components/views/rooms/RoomHeader-test.tsx
Labels: T-Defect

#12232 Use the non-deprecated importRoomKeys method on CryptoApi
  src/async-components/views/dialogs/security/ImportE2eKeysDialog.tsx
  test/components/views/dialogs/security/ImportE2eKeysDialog-test.tsx
Labels: T-Task

#12142 Enable redirected media by default
  playwright/e2e/timeline/timeline.spec.ts
  src/customisations/Media.ts
  src/linkify-matrix.ts
Labels: T-Enhancement

#12153 Remove welcome bot `welcome_user_id` support
  src/IConfigOptions.ts
  src/components/structures/MatrixChat.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/InviteDialog-test.tsx
Labels: T-Deprecation

#12237 Add new playwright test for shield migration
  playwright/e2e/crypto/logout.spec.ts
  playwright/e2e/crypto/staged-rollout.spec.ts
  playwright/e2e/crypto/utils.ts
Labels: T-Task

#12242 Fix OIDC delegated auth account url check
  src/stores/oidc/OidcClientStore.ts
  test/components/structures/MatrixChat-test.tsx
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/test-utils/client.ts
  test/test-utils/test-utils.ts
Labels: T-Defect

#12243 Update the TAC indicator on event decryption
  src/components/views/spaces/threads-activity-centre/useUnreadThreadRooms.ts
  test/components/views/spaces/useUnreadThreadRooms-test.tsx
Labels: T-Defect

#12233 Call the AsJson forms of import and exportRoomKeys
  src/async-components/views/dialogs/security/ExportE2eKeysDialog.tsx
  src/async-components/views/dialogs/security/ImportE2eKeysDialog.tsx
  test/components/views/dialogs/security/ExportE2eKeysDialog-test.tsx
  test/components/views/dialogs/security/ImportE2eKeysDialog-test.tsx
Labels: T-Enhancement

#12247 Refine menu, toast, and popover colors
  playwright/snapshots/audio-player/audio-player.spec.ts/Selected-EventTile-of-audio-player--high-contrast--bubble-layout-linux.png
  playwright/snapshots/audio-player/audio-player.spec.ts/Selected-EventTile-of-audio-player--high-contrast--group-layout-linux.png
  playwright/snapshots/audio-player/audio-player.spec.ts/Selected-EventTile-of-audio-player--high-contrast--irc-layout-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  playwright/snapshots/settings/general-room-settings-tab.spec.ts/General-room-settings-tab-should-be-rendered-properly-1-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-linux.png
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
  playwright/snapshots/spaces/spaces.spec.ts/space-create-menu-linux.png
  playwright/snapshots/spaces/spaces.spec.ts/space-panel-collapsed-linux.png
  playwright/snapshots/spaces/spaces.spec.ts/space-panel-expanded-linux.png
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-button-expanded-linux.png
  playwright/snapshots/threads/threads.spec.ts/Reply-to-the-location-on-ThreadView-linux.png
  res/css/structures/_ContextualMenu.pcss
  res/css/structures/_QuickSettingsButton.pcss
  res/css/structures/_ToastContainer.pcss
  res/css/views/context_menus/_IconizedContextMenu.pcss
  res/css/views/context_menus/_MessageContextMenu.pcss
  res/css/views/elements/_AccessibleButton.pcss
  res/css/views/messages/_MessageActionBar.pcss
  res/css/views/right_panel/_BaseCard.pcss
  res/css/views/right_panel/_PinnedMessagesCard.pcss
  res/css/views/rooms/_MessageComposer.pcss
  res/css/views/rooms/_MessageComposerFormatBar.pcss
Labels: T-Enhancement

#9329 Fix forced lowercase username in login/registration flows
  playwright/snapshots/register/register.spec.ts/registration-linux.png
  src/components/views/auth/PasswordLogin.tsx
  src/components/views/auth/RegistrationForm.tsx
Labels: Z-Community-PR, T-Defect

#12249 Fix: Enable previously skipped Playwright crypto test for 'gray shields'
  playwright/e2e/crypto/crypto.spec.ts
Labels: T-Task

#12251 Add A-Element-R labels to rageshakes if rust
  src/rageshake/submit-rageshake.ts
  test/submit-rageshake-test.ts
  test/test-utils/client.ts
Labels: T-Task

#12256 Update setup-xvfb action to fix node16 deprecation warning
  .github/workflows/end-to-end-tests.yaml
Labels: T-Task

#12250 Use h1 as first heading in dialogs
  playwright/e2e/user-onboarding/user-onboarding-new.spec.ts
  res/css/_common.pcss
  src/components/views/dialogs/BaseDialog.tsx
  test/components/structures/__snapshots__/MatrixChat-test.tsx.snap
  test/components/views/dialogs/__snapshots__/AppDownloadDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ChangelogDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ConfirmUserActionDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/DevtoolsDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ExportDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/FeedbackDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/LogoutDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ManageRestrictedJoinRuleDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ManualDeviceKeyVerificationDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/MessageEditHistoryDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ServerPickerDialog-test.tsx.snap
  test/components/views/dialogs/security/__snapshots__/CreateKeyBackupDialog-test.tsx.snap
  test/components/views/dialogs/security/__snapshots__/CreateSecretStorageDialog-test.tsx.snap
  test/components/views/dialogs/security/__snapshots__/ExportE2eKeysDialog-test.tsx.snap
  test/components/views/dialogs/security/__snapshots__/ImportE2eKeysDialog-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/SecurityRoomSettingsTab-test.tsx.snap
  test/components/views/spaces/__snapshots__/AddExistingToSpaceDialog-test.tsx.snap
Labels: T-Defect

#12257 Improve client metadata used for OIDC dynamic registration
  src/@types/common.ts
  src/BasePlatform.ts
  src/Login.ts
  src/utils/oidc/registerClient.ts
  test/components/structures/auth/Login-test.tsx
  test/test-utils/platform.ts
  test/utils/oidc/registerClient-test.ts
Labels: T-Enhancement

#12258 Saner releases clean up
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  post-release.sh
  release.sh
  yarn.lock
Labels: T-Task

#12253 Fix Native OIDC for Element Desktop
  src/BasePlatform.ts
  src/Lifecycle.ts
  src/stores/oidc/OidcClientStore.ts
  src/utils/oidc/authorize.ts
  test/stores/oidc/OidcClientStore-test.ts
  test/utils/oidc/authorize-test.ts
Labels: T-Enhancement

#12260 Improvements to Playwright test infrastructure
  playwright/e2e/crypto/utils.ts
  playwright/e2e/register/email.spec.ts
  playwright/element-web-test.ts
  playwright/pages/ElementAppPage.ts
Labels: T-Task

#12263 Revert "Refine menu, toast, and popover colors"
  playwright/snapshots/audio-player/audio-player.spec.ts/Selected-EventTile-of-audio-player--high-contrast--bubble-layout-linux.png
  playwright/snapshots/audio-player/audio-player.spec.ts/Selected-EventTile-of-audio-player--high-contrast--group-layout-linux.png
  playwright/snapshots/audio-player/audio-player.spec.ts/Selected-EventTile-of-audio-player--high-contrast--irc-layout-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  playwright/snapshots/settings/general-room-settings-tab.spec.ts/General-room-settings-tab-should-be-rendered-properly-1-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-linux.png
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
  playwright/snapshots/spaces/spaces.spec.ts/space-create-menu-linux.png
  playwright/snapshots/spaces/spaces.spec.ts/space-panel-collapsed-linux.png
  playwright/snapshots/spaces/spaces.spec.ts/space-panel-expanded-linux.png
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-button-expanded-linux.png
  playwright/snapshots/threads/threads.spec.ts/Reply-to-the-location-on-ThreadView-linux.png
  res/css/structures/_ContextualMenu.pcss
  res/css/structures/_QuickSettingsButton.pcss
  res/css/structures/_ToastContainer.pcss
  res/css/views/context_menus/_IconizedContextMenu.pcss
  res/css/views/context_menus/_MessageContextMenu.pcss
  res/css/views/elements/_AccessibleButton.pcss
  res/css/views/messages/_MessageActionBar.pcss
  res/css/views/right_panel/_BaseCard.pcss
  res/css/views/right_panel/_PinnedMessagesCard.pcss
  res/css/views/rooms/_MessageComposer.pcss
  res/css/views/rooms/_MessageComposerFormatBar.pcss
Labels: T-Enhancement

#12266 Remove hardcoded `Element` in tac labs description
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Defect

#12252 Add Playwright tests for OIDC-aware & OIDC-native
  docs/playwright.md
  playwright/.gitignore
  playwright/e2e/oidc/index.ts
  playwright/e2e/oidc/oidc-aware.spec.ts
  playwright/e2e/oidc/oidc-native.spec.ts
  playwright/plugins/homeserver/synapse/index.ts
  playwright/plugins/homeserver/synapse/templates/mas-oidc/README.md
  playwright/plugins/homeserver/synapse/templates/mas-oidc/homeserver.yaml
  playwright/plugins/homeserver/synapse/templates/mas-oidc/log.config
  playwright/plugins/matrix-authentication-service/config.yaml
  playwright/plugins/matrix-authentication-service/index.ts
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/stores/oidc/OidcClientStore.ts
Labels: T-Task

#12246 Use browser's font size instead of hardcoded `16px` as root font size
  playwright/e2e/settings/appearance-user-settings-tab.spec.ts
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  res/css/views/settings/_FontScalingPanel.pcss
  src/components/views/settings/FontScalingPanel.tsx
  src/dispatcher/actions.ts
  src/dispatcher/payloads/UpdateFontSizeDeltaPayload.ts
  src/i18n/strings/en_EN.json
  src/models/Call.ts
  src/settings/Settings.tsx
  src/settings/controllers/FontSizeController.ts
  src/settings/watchers/FontWatcher.ts
  test/components/views/settings/FontScalingPanel-test.tsx
  test/components/views/settings/__snapshots__/FontScalingPanel-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
  test/models/Call-test.ts
  test/settings/watchers/FontWatcher-test.tsx
Labels: T-Enhancement

#12269 Ignore activity in TAC
  src/components/views/spaces/threads-activity-centre/useUnreadThreadRooms.ts
  test/components/views/spaces/ThreadsActivityCentre-test.tsx
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
  test/components/views/spaces/useUnreadThreadRooms-test.tsx
Labels: T-Enhancement

#12267 Fix the space panel getting bigger when gaining a scroll bar
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  playwright/snapshots/spaces/spaces.spec.ts/space-panel-collapsed-linux.png
  playwright/snapshots/spaces/spaces.spec.ts/space-panel-expanded-linux.png
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-button-expanded-linux.png
  res/css/structures/_SpacePanel.pcss
Labels: T-Defect

#12272 ModuleAPI: `overwrite_login` action was not stopping the existing client resulting in the action failing with rust-sdk
  playwright/e2e/login/overwrite_login.spec.ts
  src/Lifecycle.ts
  src/modules/ProxiedModuleApi.ts
  test/Lifecycle-test.ts
Labels: T-Defect

#12245 Update MSC2965 OIDC Discovery implementation
  src/Lifecycle.ts
  src/components/views/dialogs/ServerPickerDialog.tsx
  src/stores/oidc/OidcClientStore.ts
  src/utils/AutoDiscoveryUtils.tsx
  src/utils/ValidatedServerConfig.ts
  src/utils/oidc/TokenRefresher.ts
  src/utils/oidc/getDelegatedAuthAccountUrl.ts
  src/utils/oidc/registerClient.ts
  test/Lifecycle-test.ts
  test/components/structures/MatrixChat-test.tsx
  test/components/structures/auth/Registration-test.tsx
  test/components/views/dialogs/ServerPickerDialog-test.tsx
  test/stores/oidc/OidcClientStore-test.ts
  test/test-utils/oidc.ts
  test/utils/AutoDiscoveryUtils-test.tsx
  test/utils/oidc/TokenRefresher-test.ts
  test/utils/oidc/authorize-test.ts
  test/utils/oidc/getDelegatedAuthAccountUrl-test.ts
  test/utils/oidc/registerClient-test.ts
Labels: T-Enhancement

#12280 Fix spurious session corruption error
  src/Lifecycle.ts
  src/stores/LifecycleStore.ts
  test/Lifecycle-test.ts
  test/stores/LifecycleStore-test.ts
Labels: T-Defect

#12286 Hide the archived section
  playwright/e2e/knock/knock-into-room.spec.ts
  playwright/e2e/one-to-one-chat/one-to-one-chat.spec.ts
  src/components/views/rooms/RoomList.tsx
  src/stores/room-list/algorithms/Algorithm.ts
Labels: T-Enhancement

#12288 Fix buttons of widget in a room
  src/components/structures/RoomView.tsx
  src/dispatcher/actions.ts
  src/stores/RoomViewStore.tsx
  test/components/structures/RoomView-test.tsx
  test/stores/RoomViewStore-test.ts
Labels: T-Defect

#12289 Fix alignment of user menu avatar
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  playwright/snapshots/spaces/spaces.spec.ts/space-panel-collapsed-linux.png
  playwright/snapshots/spaces/spaces.spec.ts/space-panel-expanded-linux.png
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-button-expanded-linux.png
  res/css/structures/_SpacePanel.pcss
Labels: T-Defect

#12291 Allow screenshot update docker to run multiple test files
  playwright/docker-entrypoint.sh
Labels: T-Defect

#12290 Add custom reporter to auto-report flaky Playwright tests
  .github/workflows/end-to-end-tests.yaml
  playwright/flaky-reporter.ts
Labels: T-Task

#12294 PR template: reminder to document your stuff
  .github/PULL_REQUEST_TEMPLATE.md
Labels: T-Task

#12296 Prevent "Element" hardcoded in i18n files
  .github/workflows/static_analysis.yaml
  package.json
  yarn.lock
Labels: T-Task

#12285 Fix TAC opening with keyboard
  res/css/structures/_ThreadsActivityCentre.pcss
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentreButton.tsx
  test/components/views/spaces/ThreadsActivityCentre-test.tsx
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
Labels: T-Defect

#12283 Feeds event with relation to unknown to the widget
  src/stores/widgets/StopGapWidget.ts
  test/stores/widgets/StopGapWidget-test.ts
Labels: Z-Community-PR, T-Defect
