Repository matrix-org/matrix-react-sdk, pull requests merged in 2024-06, with the labels that each got.

#12570 Build the playwright html report in the main workflow
  .github/workflows/end-to-end-tests-netlify.yaml
  .github/workflows/end-to-end-tests.yaml
Labels: T-Task

#12543 Element-R: pass pickleKey in as raw key for indexeddb encryption
  src/BasePlatform.ts
  src/Lifecycle.ts
  src/MatrixClientPeg.ts
  src/utils/tokens/pickling.ts
  test/Lifecycle-test.ts
  test/MatrixClientPeg-test.ts
Labels: T-Defect

#12578 Use LegacyRendezvousFailureReason over RendezvousFailureReason
  src/components/views/auth/LoginWithQR.tsx
  src/components/views/auth/LoginWithQRFlow.tsx
  test/components/views/settings/devices/LoginWithQR-test.tsx
  test/components/views/settings/devices/LoginWithQRFlow-test.tsx
Labels: T-Task

#12370 MSC4108 support OIDC QR code login
  .eslintrc.js
  .github/workflows/static_analysis.yaml
  .github/workflows/tests.yml
  res/css/structures/_UserMenu.pcss
  src/components/structures/MatrixChat.tsx
  src/components/structures/UserMenu.tsx
  src/components/views/auth/LoginWithQR-types.ts
  src/components/views/auth/LoginWithQR.tsx
  src/components/views/auth/LoginWithQRFlow.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/settings/devices/LoginWithQRSection.tsx
  src/components/views/settings/tabs/user/SessionManagerTab.tsx
  src/dispatcher/payloads/OpenToTabPayload.ts
  src/i18n/strings/en_EN.json
  test/components/structures/UserMenu-test.tsx
  test/components/views/settings/devices/LoginWithQR-test.tsx
  test/components/views/settings/devices/LoginWithQRFlow-test.tsx
  test/components/views/settings/devices/LoginWithQRSection-test.tsx
  test/components/views/settings/devices/__snapshots__/LoginWithQRFlow-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/LoginWithQRSection-test.tsx.snap
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
  test/test-utils/client.ts
  test/test-utils/oidc.ts
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#12569 Add flag for tests to avoid double-reporting check
  src/DecryptionFailureTracker.ts
  test/DecryptionFailureTracker-test.ts
Labels: T-Task

#12548 New user profile UI in User Settings
  package.json
  playwright/e2e/settings/general-user-settings-tab.spec.ts
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-smallscreen-linux.png
  res/css/_common.pcss
  res/css/_components.pcss
  res/css/views/dialogs/_UserSettingsDialog.pcss
  res/css/views/settings/_RoomProfileSettings.pcss
  res/css/views/settings/_UserProfileSettings.pcss
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/elements/CopyableText.tsx
  src/components/views/room_settings/RoomProfileSettings.tsx
  src/components/views/settings/AvatarSetting.tsx
  src/components/views/settings/ProfileSettings.tsx
  src/components/views/settings/UserProfileSettings.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/contexts/ToastContext.tsx
  src/i18n/strings/en_EN.json
  src/utils/useId.ts
  test/components/views/settings/UserProfileSettings-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/GeneralUserSettingsTab-test.tsx.snap
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
  test/contexts/ToastContext-test.ts
  test/test-utils/test-utils.ts
  yarn.lock
Labels: T-Enhancement

#12558 Fix display of no avatar in avatar setting controls
  playwright/snapshots/settings/general-room-settings-tab.spec.ts/General-room-settings-tab-should-be-rendered-properly-1-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-smallscreen-linux.png
  res/css/views/settings/_AvatarSetting.pcss
  res/img/feather-customised/user.svg
  src/components/views/avatars/RoomAvatar.tsx
  src/components/views/room_settings/RoomProfileSettings.tsx
  src/components/views/settings/AvatarSetting.tsx
  src/components/views/settings/UserProfileSettings.tsx
  test/components/views/dialogs/RoomSettingsDialog-test.tsx
  test/components/views/room_settings/RoomProfileSettings-test.tsx
  test/components/views/settings/AvatarSetting-test.tsx
  test/components/views/settings/UserProfileSettings-test.tsx
  test/components/views/settings/tabs/user/GeneralUserSettingsTab-test.tsx
Labels: T-Defect

#12575 Fix incorrect assumptions about required fields in /search response
  src/Searching.ts
  src/components/structures/RoomSearchView.tsx
Labels: T-Defect

#12585 Change avatarsetting componment to use a menu
  playwright/e2e/settings/general-user-settings-tab.spec.ts
  playwright/snapshots/settings/general-room-settings-tab.spec.ts/General-room-settings-tab-should-be-rendered-properly-1-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-smallscreen-linux.png
  res/css/views/settings/_AvatarSetting.pcss
  src/components/views/room_settings/RoomProfileSettings.tsx
  src/components/views/settings/AvatarSetting.tsx
  src/components/views/settings/UserProfileSettings.tsx
  src/i18n/strings/en_EN.json
  test/components/views/room_settings/RoomProfileSettings-test.tsx
  test/components/views/settings/AvatarSetting-test.tsx
  test/components/views/settings/UserProfileSettings-test.tsx
Labels: T-Enhancement

#12589 Fix EditInPlace button styles
  res/css/_common.pcss
Labels: T-Defect

#12590 Add hover / active state on avatsetting upload button
  res/css/views/settings/_AvatarSetting.pcss
  src/components/views/settings/AvatarSetting.tsx
Labels: T-Defect

#12587 Add missing a11y label to dismiss onboarding button in room list
  src/components/views/user-onboarding/UserOnboardingButton.tsx
Labels: T-Defect

#12591 Keep dialog glass border on narrow screens
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-smallscreen-linux.png
  res/css/_common.pcss
Labels: T-Defect

#12594 Fix roving tab index crash `compareDocumentPosition`
  src/accessibility/RovingTabIndex.tsx
  test/accessibility/RovingTabIndex-test.tsx
  test/components/views/emojipicker/EmojiPicker-test.tsx
Labels: X-Release-Blocker, T-Defect

#12607 Fix image upload preview size
  playwright/e2e/file-upload/image-upload.spec.ts
  playwright/snapshots/file-upload/image-upload.spec.ts/image-upload-preview-linux.png
  res/css/_common.pcss
Labels: T-Defect

#12608 Remove stale `#start` route as it hasn't been used in a long time
  src/components/structures/MatrixChat.tsx
Labels: T-Task

#12600 Don't show 'saved' on display name save error
  src/components/views/settings/UserProfileSettings.tsx
  test/components/views/settings/UserProfileSettings-test.tsx
Labels: T-Defect

#12604 Support s tags for strikethrough for Matrix v1.10
  src/HtmlUtils.tsx
  src/Linkify.tsx
  src/Markdown.ts
  src/editor/deserialize.ts
Labels: T-Enhancement

#12614 Replace setImmediate with setTimeout
  .eslintrc.js
  src/Lifecycle.ts
  src/Modal.tsx
  src/components/structures/ContextMenu.tsx
  src/components/structures/PictureInPictureDragger.tsx
  src/components/views/dialogs/BulkRedactDialog.tsx
  src/components/views/dialogs/ForwardDialog.tsx
  src/components/views/dialogs/spotlight/SpotlightDialog.tsx
  src/components/views/rooms/NewRoomIntro.tsx
  src/components/views/rooms/RoomSublist.tsx
  src/components/views/rooms/RoomTile.tsx
  src/stores/room-list/RoomListStore.ts
  src/stores/room-list/filters/SpaceFilterCondition.ts
  test/components/views/context_menus/RoomGeneralContextMenu-test.tsx
  test/components/views/dialogs/ForwardDialog-test.tsx
  test/components/views/right_panel/PinnedMessagesCard-test.tsx
  test/components/views/rooms/RoomPreviewBar-test.tsx
  test/setup/setupManualMocks.ts
  test/stores/LifecycleStore-test.ts
  test/stores/room-list/RoomListStore-test.ts
  test/utils/leave-behaviour-test.ts
Labels: T-Task

#12605 Tweak copy for user verification toast
  playwright/e2e/crypto/verification.spec.ts
  src/components/views/toasts/VerificationRequestToast.tsx
  src/i18n/strings/en_EN.json
Labels: T-Enhancement

#12615 Avoid flakiness from hover styling in screenshot tests
  playwright/element-web-test.ts
Labels: T-Task

#12606 Cache e2eStatus to avoid concerning unencrypted flicker when changing rooms
  src/components/structures/RoomView.tsx
Labels: T-Enhancement

#12613 Update gfm.css to github-markdown-css
  package.json
  playwright/snapshots/timeline/timeline.spec.ts/highlighted-search-results-linux.png
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/_MessageComposer.pcss
  res/themes/dark-custom/css/dark-custom.pcss
  res/themes/dark/css/dark.pcss
  res/themes/legacy-dark/css/legacy-dark.pcss
  res/themes/legacy-light/css/legacy-light.pcss
  res/themes/light-custom/css/light-custom.pcss
  res/themes/light-high-contrast/css/light-high-contrast.pcss
  res/themes/light/css/light.pcss
  yarn.lock
Labels: T-Enhancement

#12602 Use stable endpoints for MSC3916
  playwright/e2e/timeline/timeline.spec.ts
Labels: T-Task

#12622 Add login page option for SSO redirects
  src/IConfigOptions.ts
Labels: Z-Community-PR, T-Task

#12593 Fix config override of other settings levels
  src/components/views/elements/SettingsFlag.tsx
  src/settings/Settings.tsx
  src/settings/SettingsStore.ts
  test/components/views/dialogs/UserSettingsDialog-test.tsx
  test/settings/SettingsStore-test.ts
Labels: T-Defect

#12618 Remove room key history sharing
  src/RoomInvite.tsx
  src/SlashCommands.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/i18n/strings/en_EN.json
  src/utils/MultiInviter.ts
  src/utils/RoomUpgrade.ts
Labels: T-Task

#12609 Add in-progress view to display name EditInPlace
  package.json
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-smallscreen-linux.png
  res/css/views/settings/_UserProfileSettings.pcss
  src/components/views/settings/UserProfileSettings.tsx
  src/i18n/strings/en_EN.json
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  yarn.lock
Labels: T-Defect

#12624 Show tooltips on narrow tabbed views
  playwright/e2e/settings/general-user-settings-tab.spec.ts
  src/components/structures/TabbedView.tsx
  src/hooks/useWindowWidth.ts
  test/hooks/useWindowWidth-test.ts
Labels: T-Enhancement

#12586 Improve accessibility of the room summary card
  src/components/views/right_panel/RoomSummaryCard.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
Labels: T-Enhancement

#12616 Fix widgets not being cleaned up correctly.
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomView.tsx
  src/components/views/voip/CallView.tsx
  src/hooks/room/useRoomCall.ts
  src/models/Call.ts
  src/stores/ActiveWidgetStore.ts
  src/stores/CallStore.ts
  src/stores/room-list/algorithms/Algorithm.ts
  src/stores/widgets/StopGapWidget.ts
  src/toasts/IncomingCallToast.tsx
  test/components/structures/MatrixChat-test.tsx
  test/components/views/rooms/RoomHeader-test.tsx
  test/toasts/IncomingCallToast-test.tsx
Labels: T-Defect

#12632 Remove stray setState which caused encryption state shields to flicker
  src/components/structures/RoomView.tsx
Labels: X-Release-Blocker, T-Defect

#12635 Replace deprecated babel proposal plugins
  babel.config.js
  package.json
  yarn.lock
Labels: T-Task

#12588 Remove unused state fields in qr oidc
  src/components/views/auth/LoginWithQR.tsx
Labels: T-Task

#12637 Update `@vector-im/compound-web` & fix jest snapshot updates
  package.json
  yarn.lock
Labels: T-Task

#12639 Hide voice call button when redundant
  src/components/views/rooms/RoomHeader.tsx
  src/hooks/room/useRoomCall.ts
  test/components/views/rooms/RoomHeader-test.tsx
Labels: T-Enhancement

#12650 Update to compound-web 4.8.0
  package.json
  playwright/snapshots/crypto/crypto.spec.ts/RoomSummaryCard-with-verified-e2ee-linux.png
  playwright/snapshots/right-panel/right-panel.spec.ts/with-name-and-address-linux.png
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  yarn.lock
Labels: T-Task

#12654 Playwright tests to replace old `loading-test.tsx`
  playwright/e2e/app-loading/guest-registration.spec.ts
  playwright/e2e/app-loading/stored-credentials.spec.ts
  playwright/plugins/homeserver/synapse/templates/guest-enabled/README.md
  playwright/plugins/homeserver/synapse/templates/guest-enabled/homeserver.yaml
  playwright/plugins/homeserver/synapse/templates/guest-enabled/log.config
Labels: X-Release-Blocker, T-Task

#12651 Minor tweaks to UserSettings dialog
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-smallscreen-linux.png
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
  res/css/views/dialogs/_UserSettingsDialog.pcss
  src/components/views/dialogs/BaseDialog.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  test/components/structures/__snapshots__/MatrixChat-test.tsx.snap
  test/components/views/dialogs/__snapshots__/AppDownloadDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ChangelogDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ConfirmUserActionDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/DevtoolsDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ExportDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/LogoutDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ManageRestrictedJoinRuleDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ManualDeviceKeyVerificationDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/MessageEditHistoryDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ServerPickerDialog-test.tsx.snap
  test/components/views/dialogs/security/__snapshots__/CreateKeyBackupDialog-test.tsx.snap
  test/components/views/dialogs/security/__snapshots__/ExportE2eKeysDialog-test.tsx.snap
  test/components/views/dialogs/security/__snapshots__/ImportE2eKeysDialog-test.tsx.snap
  test/components/views/location/__snapshots__/LocationViewDialog-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/SecurityRoomSettingsTab-test.tsx.snap
  test/components/views/spaces/__snapshots__/AddExistingToSpaceDialog-test.tsx.snap
Labels: T-Enhancement

#12633 Remove outdated iframe sandbox attribute
  src/components/views/messages/MFileBody.tsx
  src/utils/FileDownloader.ts
Labels: T-Defect

#12629 Fix background on live location sharing footer
  res/css/components/views/messages/_MBeaconBody.pcss
Labels: T-Defect

#12653 Move the account management button
  res/css/views/settings/_UserProfileSettings.pcss
  src/components/views/settings/UserProfileSettings.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/tabs/user/GeneralUserSettingsTab-test.tsx
Labels: T-Enhancement

#12665 Add a github action to check the base branch
  .github/workflows/pull_request_base_branch.yaml
Labels: T-Task

#12657 Playwright test: ensure that links are preserved over login
  playwright/e2e/login/login.spec.ts
Labels: T-Task

#12664 Hide voip buttons in group rooms in environments with widgets disabled
  src/components/views/rooms/RoomHeader.tsx
  src/hooks/room/useRoomCall.ts
  test/components/views/rooms/RoomHeader-test.tsx
Labels: T-Enhancement

#12660 Playwright: check the welcome page is loaded and works
  playwright/e2e/login/login.spec.ts
Labels: T-Task

#12649 Fix high contrast theme in settings
  res/themes/light-high-contrast/css/_light-high-contrast.pcss
Labels: T-Defect

#12668 Remove redundant copy in deactive uia modal
  src/components/views/dialogs/DeactivateAccountDialog.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#12669 Deflake verification playwright tests
  playwright/e2e/crypto/utils.ts
  playwright/e2e/crypto/verification.spec.ts
Labels: T-Task

#12630 Switch to Rust crypto stack for all logins
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/crypto/staged-rollout.spec.ts
  src/MatrixClientPeg.ts
  src/SecurityManager.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/controllers/RustCryptoSdkController.ts
  src/utils/StorageManager.ts
  test/MatrixClientPeg-test.ts
  test/components/views/settings/tabs/user/LabsUserSettingsTab-test.tsx
  test/utils/StorageManager-test.ts
Labels: X-Release-Blocker, T-Enhancement

#12662 Disable playwright tests for legacy crypto
  playwright.config.ts
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/crypto/verification.spec.ts
  playwright/e2e/read-receipts/high-level.spec.ts
  playwright/e2e/timeline/timeline.spec.ts
  playwright/element-web-test.ts
Labels: T-Task

#12675 Update `@vector-im/compound-web`
  package.json
  test/components/structures/__snapshots__/ThreadPanel-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/rooms/RoomHeader/__snapshots__/VideoRoomChatButton-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
  test/components/views/settings/__snapshots__/PowerLevelSelector-test.tsx.snap
  test/components/views/spaces/__snapshots__/SpacePanel-test.tsx.snap
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
  yarn.lock
Labels: T-Task

#12679 Remove legacy crypto in playwright docker entrypoint
  playwright/docker-entrypoint.sh
Labels: T-Task

#12695 Reduce number of parallel runners for Playwright
  .github/workflows/end-to-end-tests.yaml
Labels: T-Task

#12697 Switch from graphemer to Intl.Segmenter
  package.json
  src/HtmlUtils.tsx
  src/editor/parts.ts
  src/utils/strings.ts
  tsconfig.json
Labels: T-Task

#12696 Pass through BASE_URL env on playwright screenshot docker wrapper
  package.json
Labels: T-Task

#12698 Extract SearchScope and SearchInfo into Searching
  src/Searching.ts
  src/components/structures/RoomSearchView.tsx
  src/components/structures/RoomView.tsx
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/components/views/rooms/SearchBar.tsx
  test/components/structures/RoomSearchView-test.tsx
  test/components/structures/RoomView-test.tsx
  test/components/views/rooms/LegacyRoomHeader-test.tsx
  test/components/views/rooms/SearchBar-test.tsx
Labels: T-Task

#12670 Split out email & phone number settings to separate components & move discovery to privacy tab
  playwright/e2e/settings/general-user-settings-tab.spec.ts
  playwright/e2e/settings/security-user-settings-tab.spec.ts
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-linux.png
  res/css/views/terms/_InlineTermsAgreement.pcss
  src/components/views/settings/UserPersonalInfoSettings.tsx
  src/components/views/settings/discovery/DiscoverySettings.tsx
  src/components/views/settings/tabs/user/GeneralUserSettingsTab.tsx
  src/components/views/settings/tabs/user/SecurityUserSettingsTab.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/discovery/DiscoverySettings-test.tsx
  test/components/views/settings/discovery/__snapshots__/EmailAddresses-test.tsx.snap
  test/components/views/settings/discovery/__snapshots__/PhoneNumbers-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/GeneralUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#12576 New theme ui in user settings
  playwright/e2e/audio-player/audio-player.spec.ts
  playwright/e2e/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts
  playwright/e2e/settings/appearance-user-settings-tab/index.ts
  playwright/snapshots/editing/editing.spec.ts/message-edit-history-dialog-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/theme-panel-custom-theme-added-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/theme-panel-custom-theme-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/theme-panel-dark-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/theme-panel-light-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/theme-panel-match-system-enabled-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  res/css/_common.pcss
  res/css/components/views/settings/shared/_SettingsSubsection.pcss
  res/css/views/settings/_ThemeChoicePanel.pcss
  src/components/views/dialogs/BaseDialog.tsx
  src/components/views/settings/ThemeChoicePanel.tsx
  src/components/views/settings/shared/SettingsSubsection.tsx
  src/components/views/settings/shared/SettingsSubsectionHeading.tsx
  src/components/views/settings/tabs/user/AppearanceUserSettingsTab.tsx
  src/components/views/spaces/QuickThemeSwitcher.tsx
  src/hooks/useSettings.ts
  src/hooks/useTheme.ts
  src/i18n/strings/en_EN.json
  src/settings/SettingsStore.ts
  src/theme.ts
  test/components/views/settings/ThemeChoicePanel-test.tsx
  test/components/views/settings/__snapshots__/ThemeChoicePanel-test.tsx.snap
  test/components/views/settings/tabs/user/PreferencesUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/AppearanceUserSettingsTab-test.tsx.snap
  test/components/views/spaces/QuickThemeSwitcher-test.tsx
Labels: T-Enhancement

#12708 Playwright: use rust crypto for the bot user
  playwright/e2e/crypto/verification.spec.ts
  playwright/pages/bot.ts
Labels: T-Task
