Repository matrix-org/matrix-react-sdk, pull requests merged in 2024-03, with the labels that each got.

#12157 fix automatic DM avatar with functional members
  src/components/views/avatars/DecoratedRoomAvatar.tsx
  test/components/views/avatars/DecoratedRoomAvatar-test.tsx
  test/components/views/avatars/__snapshots__/DecoratedRoomAvatar-test.tsx.snap
Labels: Z-Community-PR, T-Defect

#12304 Fix requests for senders to submit auto-rageshakes
  src/stores/AutoRageshakeStore.ts
  test/stores/AutoRageshakeStore-test.ts
Labels: T-Defect

#12321 Remove references to internal js-sdk type `CryptoBackend`
  .eslintrc.js
  test/components/views/rooms/EventTile-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Task

#12320 Use `strong` element to semantically denote visually emphasised content
  res/css/views/dialogs/security/_AccessSecretStorageDialog.pcss
  src/async-components/views/dialogs/security/NewRecoveryMethodDialog.tsx
  src/async-components/views/dialogs/security/RecoveryMethodRemovedDialog.tsx
  src/components/structures/MatrixChat.tsx
  src/components/views/dialogs/security/AccessSecretStorageDialog.tsx
  src/components/views/settings/SetIdServer.tsx
  src/components/views/settings/tabs/user/MjolnirUserSettingsTab.tsx
  test/components/views/settings/tabs/user/__snapshots__/MjolnirUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#12303 Remove unused slider component
  res/css/_components.pcss
  res/css/views/elements/_Slider.pcss
  res/themes/dark/css/_dark.pcss
  res/themes/legacy-dark/css/_legacy-dark.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light-high-contrast/css/_light-high-contrast.pcss
  res/themes/light/css/_light.pcss
  src/components/views/elements/Slider.tsx
Labels: T-Task

#12326 Fix TAC width due to compound update
  res/css/structures/_ThreadsActivityCentre.pcss
Labels: T-Task

#12315 Fix spotlight opening in TAC
  playwright/e2e/spaces/threads-activity-centre/threadsActivityCentre.spec.ts
  res/css/structures/_ThreadsActivityCentre.pcss
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentre.tsx
  test/components/views/spaces/ThreadsActivityCentre-test.tsx
Labels: T-Defect

#12319 Reset power selector on API failure to prevent state mismatch
  src/components/views/elements/PowerSelector.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  test/components/views/elements/PowerSelector-test.tsx
  test/components/views/settings/tabs/room/RolesRoomSettingsTab-test.tsx
Labels: T-Defect

#12306 Improve Forward Dialog a11y by switching to roving tab index interactions
  res/css/views/dialogs/_ForwardDialog.pcss
  src/accessibility/RovingTabIndex.tsx
  src/components/views/dialogs/ForwardDialog.tsx
  src/components/views/elements/TruncatedList.tsx
  test/accessibility/RovingTabIndex-test.tsx
  test/components/views/dialogs/ForwardDialog-test.tsx
Labels: T-Enhancement

#12308 Reuse media content/info types from the js-sdk
  .eslintrc.js
  src/@types/matrix-js-sdk.d.ts
  src/ContentMessages.ts
  src/components/views/messages/MAudioBody.tsx
  src/components/views/messages/MFileBody.tsx
  src/components/views/messages/MImageBody.tsx
  src/components/views/messages/MImageReplyBody.tsx
  src/components/views/messages/MStickerBody.tsx
  src/components/views/messages/MVideoBody.tsx
  src/customisations/Media.ts
  src/customisations/models/IMediaEventContent.ts
  src/models/RoomUpload.ts
  src/utils/DecryptFile.ts
  src/utils/FileUtils.ts
  src/utils/MediaEventHelper.ts
  src/utils/exportUtils/Exporter.ts
  src/utils/image-media.ts
  src/voice-broadcast/models/VoiceBroadcastRecording.ts
  test/voice-broadcast/models/VoiceBroadcastRecording-test.ts
Labels: T-Task

#12333 TAC: Fix CSS & component typos
  res/css/structures/_ThreadsActivityCentre.pcss
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentre.tsx
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
Labels: T-Task

#12292 Element Call: fix widget shown while its still loading (`waitForIframeLoad=false`)
  src/components/views/elements/AppTile.tsx
  src/models/Call.ts
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/test-utils/call.ts
Labels: T-Enhancement

#12295 Make EC widget theme reactive - Update widget url when the theme changes
  src/components/views/elements/AppTile.tsx
  src/settings/watchers/ThemeWatcher.ts
  src/stores/widgets/StopGapWidget.ts
  src/theme.ts
  test/components/views/elements/AppTile-test.tsx
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/stores/widgets/StopGapWidget-test.ts
Labels: T-Enhancement

#12339 Update `@vector-im/compound-design-tokens` in package.json
  package.json
  yarn.lock
Labels: T-Defect, backport staging

#12327 Change 'type' prop on badges to 'forceDot'
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/NotificationBadge/StatelessNotificationBadge.tsx
  src/components/views/rooms/NotificationBadge/UnreadNotificationBadge.tsx
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentre.tsx
  test/components/views/rooms/NotificationBadge/StatelessNotificationBadge-test.tsx
Labels: T-Task

#12341 Fix the image view
  res/css/_common.pcss
Labels: T-Defect

#12337 TAC: Fix hover state when expanded
  playwright/e2e/spaces/threads-activity-centre/index.ts
  playwright/e2e/spaces/threads-activity-centre/threadsActivityCentre.spec.ts
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-hovered-expanded-linux.png
  playwright/snapshots/spaces/threads-activity-centre/threadsActivityCentre.spec.ts/tac-hovered-linux.png
  res/css/structures/_ThreadsActivityCentre.pcss
Labels: T-Defect

#12344 Replace forceCount prop with hideIfDot
  src/components/views/avatars/DecoratedRoomAvatar.tsx
  src/components/views/rooms/ExtraTile.tsx
  src/components/views/rooms/NotificationBadge.tsx
  src/components/views/rooms/RoomBreadcrumbs.tsx
  src/components/views/rooms/RoomSublist.tsx
  src/components/views/rooms/RoomTile.tsx
  src/components/views/spaces/SpaceTreeLevel.tsx
Labels: T-Task

#12348 Fix incorrect check for private read receipt support
  src/components/structures/TimelinePanel.tsx
Labels: Z-Community-PR, T-Defect

#12343 Refine the colors of some more components
  playwright/snapshots/permalinks/permalinks.spec.ts/permalink-rendering-linux.png
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-bubble-layout-linux.png
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-group-layout-linux.png
  playwright/snapshots/room/room-header.spec.ts/room-header-highlighted-linux.png
  playwright/snapshots/room/room-header.spec.ts/room-header-with-apps-button-not-highlighted-linux.png
  playwright/snapshots/threads/threads.spec.ts/Reply-to-the-location-on-ThreadView-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/collapsed-gels-and-messages-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/collapsed-gels-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/configured-room-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-line-inline-start-margin-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tile-reply-chains-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tile-reply-chains-compact-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tile-reply-chains-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tile-reply-chains-irc-modern-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-compact-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tiles-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-and-messages-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-emote-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-redaction-placeholder-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/hidden-event-line-padding-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/hidden-event-line-zero-padding-irc-layout-linux.png
  res/css/_common.pcss
  res/css/views/elements/_Pill.pcss
  res/css/views/elements/_Tooltip.pcss
  res/css/views/messages/_DateSeparator.pcss
  res/css/views/messages/_TimelineSeparator.pcss
  res/css/views/rooms/_BasicMessageComposer.pcss
  res/css/views/rooms/_E2EIcon.pcss
  res/css/views/rooms/_EventTile.pcss
  res/css/views/rooms/_JumpToBottomButton.pcss
  res/css/views/rooms/_LegacyRoomHeader.pcss
  res/css/views/rooms/_MessageComposer.pcss
  res/css/views/rooms/_NotificationBadge.pcss
  res/css/views/rooms/_RoomSublist.pcss
  res/css/views/rooms/_RoomTile.pcss
  res/css/views/rooms/_TopUnreadMessagesBar.pcss
  res/css/views/rooms/wysiwyg_composer/components/_Editor.pcss
  res/themes/dark/css/_dark.pcss
  res/themes/legacy-dark/css/_legacy-dark.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light-custom/css/_custom.pcss
  res/themes/light-high-contrast/css/_light-high-contrast.pcss
  res/themes/light/css/_light.pcss
  src/components/views/dialogs/security/AccessSecretStorageDialog.tsx
Labels: T-Enhancement

#12350 Prepare for `Improve types for sendStateEvent`
  playwright/tsconfig.json
  src/@types/matrix-js-sdk.d.ts
  src/call-types.ts
  src/models/Call.ts
  src/stores/widgets/WidgetLayoutStore.ts
  src/stores/widgets/types.ts
Labels: T-Task

#12254 Mark as Unread
  package.json
  playwright/e2e/room_options/marked_unread.spec.ts
  res/css/views/context_menus/_RoomGeneralContextMenu.pcss
  res/img/element-icons/roomlist/mark-as-unread.svg
  src/RoomNotifs.ts
  src/components/views/context_menus/RoomGeneralContextMenu.tsx
  src/components/views/rooms/NotificationBadge.tsx
  src/components/views/rooms/NotificationBadge/StatelessNotificationBadge.tsx
  src/components/views/rooms/RoomTile.tsx
  src/i18n/strings/en_EN.json
  src/stores/RoomViewStore.tsx
  src/stores/notifications/RoomNotificationState.ts
  src/utils/notifications.ts
  test/components/views/context_menus/RoomGeneralContextMenu-test.tsx
  test/components/views/rooms/NotificationBadge/NotificationBadge-test.tsx
  test/components/views/rooms/NotificationBadge/StatelessNotificationBadge-test.tsx
  test/stores/RoomViewStore-test.ts
  test/stores/notifications/RoomNotificationState-test.ts
  test/utils/notifications-test.ts
  yarn.lock
Labels: T-Enhancement

#12346 Change user permission by using a new apply button
  playwright/e2e/settings/roles-permissions-room-settings-tab.spec.ts
  res/css/_components.pcss
  res/css/views/settings/_PowerLevelSelector.pcss
  src/components/views/settings/PowerLevelSelector.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  test/components/views/settings/PowerLevelSelector-test.tsx
  test/components/views/settings/__snapshots__/PowerLevelSelector-test.tsx.snap
  test/components/views/settings/tabs/room/RolesRoomSettingsTab-test.tsx
Labels: T-Enhancement

#12325 Use data-mx-color for rainbows
  src/utils/colour.ts
  test/__snapshots__/SlashCommands-test.tsx.snap
  test/utils/colour-test.ts
Labels: Z-Community-PR, T-Enhancement

#12331 Improve types for `sendStateEvent`
  playwright/e2e/room/room-header.spec.ts
  playwright/pages/client.ts
  src/@types/common.ts
  src/ScalarMessaging.ts
  src/SlashCommands.tsx
  src/components/structures/SpaceHierarchy.tsx
  src/components/views/dialogs/devtools/RoomState.tsx
  src/components/views/room_settings/AliasSettings.tsx
  src/components/views/rooms/ThirdPartyMemberInfo.tsx
  src/components/views/settings/tabs/room/RolesRoomSettingsTab.tsx
  src/mjolnir/BanList.ts
  src/mjolnir/ListRule.ts
  src/settings/handlers/RoomSettingsHandler.ts
  src/stores/widgets/StopGapWidgetDriver.ts
  src/utils/RoomUpgrade.ts
  test/components/views/rooms/LegacyRoomHeader-test.tsx
  test/models/Call-test.ts
Labels: T-Task

#12357 Fix some playwright flaky tests
  playwright/e2e/audio-player/audio-player.spec.ts
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/room/room.spec.ts
  playwright/snapshots/audio-player/audio-player.spec.ts/Selected-EventTile-of-audio-player--dark-theme--group-layout-linux.png
  playwright/snapshots/audio-player/audio-player.spec.ts/Selected-EventTile-of-audio-player--high-contrast--group-layout-linux.png
  playwright/snapshots/audio-player/audio-player.spec.ts/Selected-EventTile-of-audio-player--light-theme--group-layout-linux.png
  playwright/snapshots/audio-player/audio-player.spec.ts/Selected-EventTile-of-audio-player--light-theme--monospace-font--group-layout-linux.png
Labels: T-Task

#12360 Improve readability of badges and pills
  playwright/snapshots/permalinks/permalinks.spec.ts/permalink-rendering-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tile-reply-chains-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tile-reply-chains-compact-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tile-reply-chains-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-tile-reply-chains-irc-modern-linux.png
  res/css/views/elements/_Pill.pcss
  res/themes/dark/css/_dark.pcss
  res/themes/legacy-dark/css/_legacy-dark.pcss
  res/themes/legacy-light/css/_legacy-light.pcss
  res/themes/light-custom/css/_custom.pcss
  res/themes/light/css/_light.pcss
  src/components/views/rooms/NotificationBadge/StatelessNotificationBadge.tsx
  test/components/structures/__snapshots__/RoomStatusBar-test.tsx.snap
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/settings/notifications/__snapshots__/Notifications2-test.tsx.snap
  test/components/views/spaces/__snapshots__/SpaceTreeLevel-test.tsx.snap
Labels: T-Defect

#12358 Remove the Lazy Loading `InvalidStoreError` Dialogs
  src/Lifecycle.ts
  src/components/structures/MatrixChat.tsx
  src/components/views/dialogs/LazyLoadingDisabledDialog.tsx
  src/components/views/dialogs/LazyLoadingResyncDialog.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#12364 Use test helpers from js-sdk for encrypted events
  .eslintrc.js
  test/DecryptionFailureTracker-test.js
  test/components/views/rooms/EventTile-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Task

#12356 Iterate styles around Link new device via QR
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/appearance-tab-linux.png
  playwright/snapshots/settings/appearance-user-settings-tab.spec.ts/window-12px-linux.png
  playwright/snapshots/settings/general-user-settings-tab.spec.ts/general-linux.png
  playwright/snapshots/settings/preferences-user-settings-tab.spec.ts/Preferences-user-settings-tab-should-be-rendered-properly-1-linux.png
  res/css/views/auth/_LoginWithQR.pcss
  src/components/views/auth/LoginWithQRFlow.tsx
  src/components/views/dialogs/UserSettingsDialog.tsx
  src/components/views/settings/devices/LoginWithQRSection.tsx
  src/i18n/strings/en_EN.json
  test/components/views/dialogs/__snapshots__/UserSettingsDialog-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/LoginWithQRFlow-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/LoginWithQRSection-test.tsx.snap
  test/components/views/settings/tabs/user/SessionManagerTab-test.tsx
Labels: T-Enhancement

#9452 Add leave room warning for last admin
  src/components/structures/MatrixChat.tsx
  src/i18n/strings/en_EN.json
Labels: Z-Community-PR, T-Enhancement

#12359 Avoid using deprecated exports & methods from matrix-js-sdk
  src/ContentMessages.ts
  src/ScalarMessaging.ts
  src/components/structures/InteractiveAuth.tsx
  src/components/structures/auth/Registration.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/settings/AddPrivilegedUsers.tsx
  src/components/views/settings/devices/deleteDevices.tsx
  src/createRoom.ts
  src/utils/exportUtils/JSONExport.ts
  test/ContentMessages-test.ts
  test/Reply-test.ts
  test/TextForEvent-test.ts
  test/Unread-test.ts
  test/components/structures/ViewSource-test.tsx
  test/components/views/messages/MBeaconBody-test.tsx
  test/components/views/messages/MPollEndBody-test.tsx
  test/components/views/messages/MessageActionBar-test.tsx
  test/components/views/right_panel/UserInfo-test.tsx
  test/createRoom-test.ts
  test/stores/room-list/previews/VoiceBroadcastPreview-test.ts
  test/utils/EventUtils-test.ts
  test/utils/beacon/timeline-test.ts
  test/voice-broadcast/models/VoiceBroadcastPlayback-test.tsx
Labels: T-Task

#12335 Improve types for `sendEvent`
  playwright/pages/client.ts
  src/@types/matrix-js-sdk.d.ts
  src/ContentMessages.ts
  src/components/structures/MatrixChat.tsx
  src/components/views/dialogs/EndPollDialog.tsx
  src/components/views/dialogs/ForwardDialog.tsx
  src/components/views/dialogs/ReportEventDialog.tsx
  src/components/views/dialogs/devtools/Event.tsx
  src/components/views/elements/PollCreateDialog.tsx
  src/components/views/emojipicker/ReactionPicker.tsx
  src/components/views/location/shareLocation.ts
  src/components/views/messages/MPollBody.tsx
  src/components/views/messages/ReactionsRowButton.tsx
  src/components/views/rooms/EditMessageComposer.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/components/views/rooms/wysiwyg_composer/utils/createMessageContent.ts
  src/components/views/rooms/wysiwyg_composer/utils/isContentModified.ts
  src/components/views/rooms/wysiwyg_composer/utils/message.ts
  src/editor/commands.tsx
  src/slash-commands/interface.ts
  src/stores/widgets/StopGapWidgetDriver.ts
  src/utils/createVoiceMessageContent.ts
  src/voice-broadcast/models/VoiceBroadcastRecording.ts
  test/components/views/elements/PollCreateDialog-test.tsx
  test/components/views/rooms/EditMessageComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/utils/message-test.ts
Labels: T-Task

#12365 Remove references to `matrix-js-sdk/src/crypto/verification`
  .eslintrc.js
  playwright/e2e/crypto/utils.ts
  src/MatrixClientPeg.ts
  src/components/views/right_panel/VerificationPanel.tsx
  src/verification.ts
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/toasts/VerificationRequestToast-test.tsx
Labels: T-Task

#12297 Video call meta space
  res/css/structures/_SpacePanel.pcss
  src/components/views/rooms/RoomList.tsx
  src/components/views/settings/tabs/user/SidebarUserSettingsTab.tsx
  src/components/views/spaces/SpacePanel.tsx
  src/i18n/strings/en_EN.json
  src/stores/room-list/RoomListStore.ts
  src/stores/room-list/algorithms/Algorithm.ts
  src/stores/room-list/models.ts
  src/stores/spaces/SpaceStore.ts
  src/stores/spaces/index.ts
  test/components/views/rooms/RoomList-test.tsx
  test/components/views/settings/tabs/user/SidebarUserSettingsTab-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SidebarUserSettingsTab-test.tsx.snap
  test/components/views/spaces/SpacePanel-test.tsx
  test/components/views/spaces/__snapshots__/SpacePanel-test.tsx.snap
  test/stores/SpaceStore-test.ts
  test/stores/room-list/RoomListStore-test.ts
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#12368 Convert `DecryptionFailureTracker-test` to typescript
  test/DecryptionFailureTracker-test.ts
Labels: T-Task

#12376 Allow popping out a Jitsi widget to respect Desktop `web_base_url` config
  src/utils/WidgetUtils.ts
  test/utils/WidgetUtils-test.ts
Labels: T-Defect

#12377 Fix space topic jumping on hover/focus
  src/components/views/elements/RoomTopic.tsx
Labels: T-Defect

#12374 Fix video rooms not showing share link button
  src/hooks/room/useRoomCall.ts
Labels: T-Defect

#12382 Revert "Make EC widget theme reactive - Update widget url when the theme changes"
  src/components/views/elements/AppTile.tsx
  src/settings/watchers/ThemeWatcher.ts
  src/stores/widgets/StopGapWidget.ts
  src/theme.ts
  test/components/views/elements/AppTile-test.tsx
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/stores/widgets/StopGapWidget-test.ts
Labels: X-Release-Blocker, T-Defect, backport staging

#12345 Fix external guest access url for unencrypted rooms
  src/hooks/room/useRoomCall.ts
  src/models/Call.ts
  test/components/views/rooms/RoomHeader-test.tsx
  test/models/Call-test.ts
  test/test-utils/test-utils.ts
Labels: T-Defect

#12378 Mark all threads as read button
  playwright/e2e/spaces/threads-activity-centre/index.ts
  playwright/e2e/spaces/threads-activity-centre/threadsActivityCentre.spec.ts
  res/css/views/right_panel/_ThreadPanel.pcss
  res/img/element-icons/check-all.svg
  src/components/structures/ThreadPanel.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/ThreadPanel-test.tsx
  test/components/structures/__snapshots__/ThreadPanel-test.tsx.snap
  test/test-utils/test-utils.ts
Labels: T-Enhancement
